Repository deephaven/deephaven-core, pull requests merged in 2021-11, with the labels that each got.

#1504 Web v0.6.0
  web/client-ui/Dockerfile
Labels: web-client-ui, NoDocumentationNeeded

#1510 Add exception message for JDK compatibility
  build.gradle
Labels: build, NoDocumentationNeeded

#1514 Choose generic versions for Java version in CI
  .github/workflows/build-ci.yml
  .github/workflows/check-ci.yml
  .github/workflows/docs-ci.yml
  .github/workflows/long-check-ci.yml
  .github/workflows/nightly-benchmarks.yml
  .github/workflows/nightly-check-ci.yml
  .github/workflows/publish-ci.yml
  build.gradle
Labels: ci, NoDocumentationNeeded

#1508 [barrage] correctly advertise String[] types
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/BarrageUtil.java
  grpc-api/src/flightTest/java/io/deephaven/grpc_api/flight/FlightMessageRoundTripTest.java
Labels: bug, barrage, NoDocumentationNeeded

#1520 Make PyListWrapper a previewed column
  DB/src/main/java/io/deephaven/db/tables/remote/preview/ArrayPreview.java
  DB/src/main/java/io/deephaven/db/tables/remote/preview/ColumnPreviewManager.java
  py/jpy/src/main/java/org/jpy/PyListWrapper.java
Labels: feature request, grpc, DocumentationNeeded, repl

#1490 Enable casting PyObject's to primitives; provide type param info for py lists
  DB/src/main/java/io/deephaven/db/tables/lang/DBLanguageFunctionGenerator.java
  DB/src/main/java/io/deephaven/db/tables/lang/DBLanguageFunctionUtil.java
  DB/src/main/java/io/deephaven/db/tables/lang/DBLanguageParser.java
  DB/src/main/java/io/deephaven/db/tables/select/Param.java
  DB/src/main/java/io/deephaven/db/v2/select/AbstractConditionFilter.java
  DB/src/main/java/io/deephaven/db/v2/select/ConditionFilter.java
  DB/src/main/java/io/deephaven/db/v2/select/DhFormulaColumn.java
  DB/src/main/java/io/deephaven/db/v2/select/codegen/FormulaAnalyzer.java
  DB/src/test/java/io/deephaven/db/tables/lang/TestDBLanguageParser.java
Labels: bug, NoDocumentationNeeded, repl, python-server-side

#1515 Bump gradle-docker-plugin to 7.1.0
  buildSrc/build.gradle
Labels: build, clean up, NoDocumentationNeeded

#1527 Upgrade OSHI-core dependency version to 5.8.3
  DHProcess/build.gradle
Labels: build, NoDocumentationNeeded

#1530 Use default workingDir for tests
  .github/workflows/check-ci.yml
  .github/workflows/long-check-ci.yml
  .github/workflows/nightly-check-ci.yml
  Configuration/build.gradle
  Net/build.gradle
  Stats/build.gradle
  build.gradle
Labels: ci, NoDocumentationNeeded

#1531 Bump to version 0.7.0
  .github/workflows/build-ci.yml
  build.gradle
  pyclient/README.md
  pyclient/pydeephaven/__init__.py
  pyclient/setup.py
Labels: NoDocumentationNeeded, release

#1536 Update web UI to latest markdown notebooks
  demo/push.sh
Labels: bug, NoDocumentationNeeded

#1534 [jsapi] fix RangeSet::addRange when there are ranges remaining post merge of a range
  web/shared-beans/src/main/java/io/deephaven/web/shared/data/Range.java
  web/shared-beans/src/main/java/io/deephaven/web/shared/data/RangeSet.java
  web/shared-beans/src/test/java/io/deephaven/web/shared/data/RangeSetTest.java
Labels: bug, jsapi, NoDocumentationNeeded

#1440 Provide gRPC api for input tables
  Base/build.gradle
  Base/src/main/java/io/deephaven/base/ClassUtil.java
  Base/src/test/java/io/deephaven/base/ClassUtilTest.java
  DB/src/main/java/io/deephaven/db/tables/TableDefinition.java
  DB/src/main/java/io/deephaven/db/util/config/MutableInputTable.java
  DB/src/main/java/io/deephaven/db/v2/utils/AppendOnlyArrayBackedMutableTable.java
  DB/src/main/java/io/deephaven/db/v2/utils/BaseArrayBackedMutableTable.java
  DB/src/main/java/io/deephaven/db/v2/utils/KeyedArrayBackedMutableTable.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/BarrageUtil.java
  grpc-api/src/flightTest/java/io/deephaven/grpc_api/flight/FlightMessageRoundTripTest.java
  grpc-api/src/main/java/io/deephaven/grpc_api/runner/DeephavenApiServerModule.java
  grpc-api/src/main/java/io/deephaven/grpc_api/table/TableModule.java
  grpc-api/src/main/java/io/deephaven/grpc_api/table/TableServiceGrpcImpl.java
  grpc-api/src/main/java/io/deephaven/grpc_api/table/inputtables/InputTableModule.java
  grpc-api/src/main/java/io/deephaven/grpc_api/table/inputtables/InputTableServiceGrpcImpl.java
  grpc-api/src/main/java/io/deephaven/grpc_api/table/ops/CreateInputTableGrpcImpl.java
  proto/proto-backplane-grpc-flight/src/main/java/io/deephaven/grpc_api/util/SchemaHelper.java
  proto/proto-backplane-grpc/Dockerfile
  proto/proto-backplane-grpc/src/main/java/io/deephaven/grpc_api/util/OperationHelper.java
  proto/proto-backplane-grpc/src/main/proto/deephaven/proto/inputtable.proto
  proto/proto-backplane-grpc/src/main/proto/deephaven/proto/table.proto
  web/shared-beans/src/main/java/io/deephaven/web/shared/data/InputTableDefinition.java
Labels: feature request, grpc, NoDocumentationNeeded, input-tables

#1537 Back down jdk 17
  buildSrc/src/main/groovy/io.deephaven.java-conventions.gradle
  buildSrc/src/main/groovy/io.deephaven.java-open-nio.gradle
  py/jpy/Dockerfile
Labels: NoDocumentationNeeded

#1535 Set `NULL_CHAR` to `MAX_VALUE`.
  DB/src/test/java/io/deephaven/db/v2/ssa/SsaTestHelpers.java
  Integrations/python/deephaven/conversion_utils.py
  Util/src/main/java/io/deephaven/util/QueryConstants.java
  cpp-client/deephaven/client/include/public/deephaven/client/highlevel/types.h
  qst/src/main/java/io/deephaven/qst/array/Util.java
  web/client-api/src/main/java/io/deephaven/web/client/api/input/ColumnValueDehydrater.java
  web/client-api/src/main/java/io/deephaven/web/client/api/subscription/QueryConstants.java
Labels: feature request, open api, query engine, core, DocumentationNeeded, cpp api, python-client, python-server-side, breaking

#1551 Update node to latest 14.x release
  proto/raw-js-openapi/Dockerfile
  protoc/Dockerfile
  web/client-ui/Dockerfile
Labels: NoDocumentationNeeded

#1547 Move wheel building to own projects
  Integrations/build.gradle
  build.gradle
  buildSrc/src/main/groovy/Docker.groovy
  envoy/build.gradle
  grpc-proxy/build.gradle
  protoc/build.gradle
  py/deephaven-wheel/build.gradle
  py/deephaven2-wheel/build.gradle
  settings.gradle
  web/client-ide/client-ide.gradle
Labels: NoDocumentationNeeded

#1559 Add a 'used memory' column to the PerformanceQueries ProcessMemory table.
  DB/src/main/java/io/deephaven/db/v2/utils/PerformanceQueries.java
Labels: NoDocumentationNeeded

#1543 DHLearn: Scatterer: For Python, cast scatter results to PyObject before casting to provided type
  Integrations/src/main/java/io/deephaven/integrations/learn/Output.java
  Integrations/src/main/java/io/deephaven/integrations/learn/Scatterer.java
  Integrations/src/test/java/io/deephaven/integrations/learn/OutputTest.java
  Integrations/src/test/java/io/deephaven/integrations/learn/ScattererTest.java
Labels: bug, python, NoDocumentationNeeded, python-server-side

#1563 Update web v0.6.1
  web/client-ui/Dockerfile
Labels: web-client-ui, NoDocumentationNeeded

#1567 Update web to v0.6.2
  web/client-ui/Dockerfile
Labels: NoDocumentationNeeded, internal

#1555 Use wheels directly in the build process
  Integrations/build.gradle
  Integrations/src/main/docker/Dockerfile
  buildSrc/src/main/groovy/Docker.groovy
  gradle/deephaven-jpy.gradle
  py/jpy/Dockerfile
  sphinx/sphinx.gradle
Labels: docker, NoDocumentationNeeded

#1576 Make IndexUtilities.equals work for ReadOnlyIndex arguments.
  DB/src/main/java/io/deephaven/db/v2/utils/IndexUtilities.java
Labels: NoDocumentationNeeded

#1556 Extract deephaven/java-and-python
  Generators/Generators.gradle
  Integrations/build.gradle
  build.gradle
  docker/java-and-python/build.gradle
  docker/java-and-python/src/main/docker/Dockerfile
  gradle/deephaven-jpy.gradle
  py/jpy/Dockerfile
  settings.gradle
Labels: clean up, docker, NoDocumentationNeeded

#1564 Correctly account for modified rows that shifted in the current delta
  web/client-api/src/main/java/io/deephaven/web/client/api/subscription/ViewportData.java
Labels: jsapi, NoDocumentationNeeded

#1557 Extract deephaven/runtime-base
  DB-test/build.gradle
  Integrations/build.gradle
  Integrations/src/main/docker/Dockerfile
  build.gradle
  docker/java-and-python/src/main/docker/Dockerfile
  docker/java-and-python/src/main/docker/requirements.txt
  docker/runtime-base/build.gradle
  docker/runtime-base/src/main/docker/Dockerfile
  docker/runtime-base/src/main/docker/requirements.txt
  grpc-api/server/docker/build.gradle
  py/jpy-integration/build.gradle
  settings.gradle
  sphinx/sphinx.gradle
Labels: clean up, docker, NoDocumentationNeeded

#1585 Add Replayer to TableManipulation
  Integrations/python/deephaven/TableManipulation/__init__.py
  Integrations/python/deephaven/__init__.py
Labels: size:1, python, NoDocumentationNeeded

#1587 Validate batch requests
  grpc-api/src/main/java/io/deephaven/grpc_api/table/TableServiceGrpcImpl.java
  grpc-api/src/test/java/io/deephaven/grpc_api/runner/OperationsTest.java
  java-client/session/src/main/java/io/deephaven/client/impl/BatchTableRequestBuilder.java
  qst/src/main/java/io/deephaven/qst/table/AggregationTable.java
  qst/src/main/java/io/deephaven/qst/table/ByTable.java
  qst/src/main/java/io/deephaven/qst/table/ByTableBase.java
Labels: bug, grpc, NoDocumentationNeeded

#1516 Fix up char filters
  DB/src/main/java/io/deephaven/db/v2/select/MatchFilter.java
Labels: bug, NoDocumentationNeeded

#1579 Add InputTable to QST
  DB/src/main/java/io/deephaven/db/tables/TableCreatorImpl.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/BarrageUtil.java
  grpc-api/src/main/java/io/deephaven/grpc_api/arrow/FlightServiceGrpcImpl.java
  grpc-api/src/main/java/io/deephaven/grpc_api/barrage/BarrageStreamGenerator.java
  java-client/flight-examples/build.gradle
  java-client/flight-examples/src/main/java/io/deephaven/client/examples/AddToInputTable.java
  java-client/flight-examples/src/main/java/io/deephaven/client/examples/KeyValueInputTable.java
  java-client/flight/src/main/java/io/deephaven/client/impl/FieldAdapter.java
  java-client/flight/src/main/java/io/deephaven/client/impl/FieldVectorAdapter.java
  java-client/flight/src/main/java/io/deephaven/client/impl/FlightSession.java
  java-client/flight/src/main/java/io/deephaven/client/impl/SchemaAdapter.java
  java-client/flight/src/main/java/io/deephaven/client/impl/SchemaBytesImpl.java
  java-client/flight/src/main/java/io/deephaven/client/impl/VectorHelper.java
  java-client/flight/src/main/java/io/deephaven/client/impl/VectorSchemaRootAdapter.java
  java-client/flight/src/main/resources/META-INF/services/io.deephaven.client.impl.SchemaBytes
  java-client/session/src/main/java/io/deephaven/client/impl/BatchTableRequestBuilder.java
  java-client/session/src/main/java/io/deephaven/client/impl/SchemaBytes.java
  java-client/session/src/main/java/io/deephaven/client/impl/Session.java
  java-client/session/src/main/java/io/deephaven/client/impl/SessionImpl.java
  java-client/session/src/main/java/io/deephaven/client/impl/TableHandleManagerBase.java
  java-client/session/src/main/java/io/deephaven/client/impl/TableHandleManagerDelegate.java
  proto/proto-backplane-grpc-flight/src/main/java/io/deephaven/grpc_api/util/MessageHelper.java
  proto/proto-backplane-grpc/src/main/java/io/deephaven/grpc_api/DeephavenChannel.java
  qst/graphviz/src/main/java/io/deephaven/graphviz/LabelBuilder.java
  qst/src/main/java/io/deephaven/qst/TableAdapterImpl.java
  qst/src/main/java/io/deephaven/qst/TableCreator.java
  qst/src/main/java/io/deephaven/qst/table/InMemoryAppendOnlyInputTable.java
  qst/src/main/java/io/deephaven/qst/table/InMemoryKeyBackedInputTable.java
  qst/src/main/java/io/deephaven/qst/table/InputTable.java
  qst/src/main/java/io/deephaven/qst/table/InputTableBase.java
  qst/src/main/java/io/deephaven/qst/table/LinkDescriber.java
  qst/src/main/java/io/deephaven/qst/table/ParentsVisitor.java
  qst/src/main/java/io/deephaven/qst/table/StackTraceMixInCreator.java
  qst/src/main/java/io/deephaven/qst/table/TableBase.java
  qst/src/main/java/io/deephaven/qst/table/TableCreatorImpl.java
  qst/src/main/java/io/deephaven/qst/table/TableHeader.java
  qst/src/main/java/io/deephaven/qst/table/TableSchema.java
  qst/src/main/java/io/deephaven/qst/table/TableSpec.java
  qst/src/main/java/io/deephaven/qst/table/TableVisitorGeneric.java
  qst/src/test/java/io/deephaven/qst/table/InMemoryAppendOnlyInputTableTest.java
  qst/src/test/java/io/deephaven/qst/table/InMemoryKeyBackedInputTableTest.java
Labels: NoDocumentationNeeded, qst, input-tables

#1592 resolve calendar resources via classpath
  DB/src/main/java/io/deephaven/db/util/GroovyDeephavenSession.java
  DB/src/main/java/io/deephaven/util/calendar/Calendars.java
  configs/default_calendar_imports.txt
  configs/dh-defaults.prop
  configs/grpc-api.prop
  test-configs/dh-tests.prop
Labels: bug, NoDocumentationNeeded

#1593 Update redpanda version and enable embedded schema registry.
  Integrations/docker-compose.yml
  Integrations/python/test/testConsumeKafka.py
  Integrations/python/test/testProduceKafka.py
  redpanda-standalone/docker-compose.yml
  redpanda/examples/avro/README.md
  redpanda/examples/avro/share_price.json
  redpanda/examples/post-share-price-schema.sh
  redpanda/examples/python/kafka-produce-avro.py
Labels: kafka, NoDocumentationNeeded

#1562 docker registry
  .github/workflows/nightly-image-check.yml
  Generators/Generators.gradle
  build.gradle
  buildSrc/src/main/groovy/Docker.groovy
  buildSrc/src/main/groovy/io.deephaven.docker-registry-conventions.gradle
  docker/README.md
  docker/java-and-python/build.gradle
  docker/java-and-python/src/main/docker/Dockerfile
  docker/registry/alpine/gradle.properties
  docker/registry/debian/gradle.properties
  docker/registry/envoyproxy/gradle.properties
  docker/registry/nginx/gradle.properties
  docker/registry/node/gradle.properties
  docker/registry/python/gradle.properties
  envoy/Dockerfile
  envoy/build.gradle
  grpc-proxy/Dockerfile
  grpc-proxy/build.gradle
  proto/raw-js-openapi/Dockerfile
  proto/raw-js-openapi/build.gradle
  protoc/Dockerfile
  protoc/build.gradle
  pyclient/build.gradle
  settings.gradle
  web/client-ide/client-ide.gradle
  web/client-ide/docker/Dockerfile
  web/client-ui/Dockerfile
  web/client-ui/client-ui.gradle
Labels: docker, NoDocumentationNeeded

#1565 Update JS API to support gRPC input tables
  grpc-api/src/main/java/io/deephaven/grpc_api/table/inputtables/InputTableServiceGrpcImpl.java
  proto/raw-js-openapi/src/index.js
  web/client-api/src/main/java/io/deephaven/web/client/api/Column.java
  web/client-api/src/main/java/io/deephaven/web/client/api/JsTable.java
  web/client-api/src/main/java/io/deephaven/web/client/api/QueryConnectable.java
  web/client-api/src/main/java/io/deephaven/web/client/api/Sort.java
  web/client-api/src/main/java/io/deephaven/web/client/api/WorkerConnection.java
  web/client-api/src/main/java/io/deephaven/web/client/api/barrage/def/ColumnDefinition.java
  web/client-api/src/main/java/io/deephaven/web/client/api/barrage/def/InitialTableDefinition.java
  web/client-api/src/main/java/io/deephaven/web/client/api/barrage/def/TableAttributesDefinition.java
  web/client-api/src/main/java/io/deephaven/web/client/api/barrage/stream/BiDiStream.java
  web/client-api/src/main/java/io/deephaven/web/client/api/barrage/stream/ResponseStreamWrapper.java
  web/client-api/src/main/java/io/deephaven/web/client/api/batch/RequestBatcher.java
  web/client-api/src/main/java/io/deephaven/web/client/api/csv/CsvTypeParser.java
  web/client-api/src/main/java/io/deephaven/web/client/api/input/ColumnValueDehydrater.java
  web/client-api/src/main/java/io/deephaven/web/client/api/input/JsInputTable.java
  web/client-api/src/main/java/io/deephaven/web/client/api/parse/JsDataHandler.java
  web/client-api/src/main/java/io/deephaven/web/client/api/subscription/TableViewportSubscription.java
  web/client-api/src/main/java/io/deephaven/web/client/api/tree/JsTreeTable.java
  web/client-api/src/main/java/io/deephaven/web/client/api/widget/plot/JsFigure.java
  web/client-api/src/main/java/io/deephaven/web/client/state/ClientTableState.java
  web/client-api/src/main/java/io/deephaven/web/client/state/TableReviver.java
  web/client-api/src/main/java/io/deephaven/web/public/index.html
  web/client-api/src/main/java/io/deephaven/web/public/init.js
  web/client-api/src/main/java/io/deephaven/web/public/input_table.html
  web/client-api/src/main/java/io/deephaven/web/public/input_tables.js
  web/client-api/src/test/java/io/deephaven/web/client/api/filter/FilterConditionTestGwt.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/inputtable_pb/AddTableRequest.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/inputtable_pb/AddTableResponse.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/inputtable_pb/DeleteTableRequest.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/inputtable_pb/DeleteTableResponse.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/inputtable_pb_service/BidirectionalStream.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/inputtable_pb_service/InputTableService.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/inputtable_pb_service/InputTableServiceClient.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/inputtable_pb_service/RequestStream.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/inputtable_pb_service/ResponseStream.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/inputtable_pb_service/UnaryResponse.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/table_pb/AsOfJoinTablesRequest.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/table_pb/BatchTableRequest.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/table_pb/ComboAggregateRequest.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/table_pb/Condition.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/table_pb/CreateInputTableRequest.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/table_pb/Literal.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/table_pb/RunChartDownsampleRequest.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/table_pb/batchtablerequest/Operation.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/table_pb/batchtablerequest/operation/OpCase.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/table_pb/createinputtablerequest/DefinitionCase.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/table_pb/createinputtablerequest/InputTableKind.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/table_pb/createinputtablerequest/inputtablekind/InMemoryAppendOnly.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/table_pb/createinputtablerequest/inputtablekind/InMemoryKeyBacked.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/table_pb/createinputtablerequest/inputtablekind/KindCase.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/table_pb_service/TableService.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/table_pb_service/TableServiceClient.java
  web/shared-beans/src/main/java/io/deephaven/web/shared/data/ColumnValue.java
  web/shared-beans/src/main/java/io/deephaven/web/shared/data/RowValues.java
  web/shared-beans/src/main/java/io/deephaven/web/shared/data/TableAttributesDefinition.java
Labels: jsapi, NoDocumentationNeeded

#1597 Fix broken build-ci
  envoy/build.gradle
  grpc-api/server/docker/build.gradle
  grpc-proxy/build.gradle
  web/client-ide/client-ide.gradle
Labels: bug, ci, NoDocumentationNeeded

#1595 Removed DbTypes and related functionality.
  DbTypes/DbTypes.gradle
  DbTypes/src/main/java/io/deephaven/dbtypes/DbFile.java
  DbTypes/src/main/java/io/deephaven/dbtypes/DbFileFactory.java
  DbTypes/src/main/java/io/deephaven/dbtypes/DbImage.java
  DbTypes/src/main/java/io/deephaven/dbtypes/DbImageFactory.java
  DbTypes/src/main/java/io/deephaven/dbtypes/FactoryInstances.java
  DbTypes/src/test/java/io/deephaven/dbtypes/DbFileTest.java
  DbTypes/src/test/java/io/deephaven/dbtypes/DbImageTest.java
  DbTypesImpl/DbTypesImpl.gradle
  DbTypesImpl/src/main/java/io/deephaven/dbtypes/DbFileImpl.java
  DbTypesImpl/src/main/java/io/deephaven/dbtypes/DbImageImpl.java
  DbTypesImpl/src/test/java/io/deephaven/dbtypes/DbFileImplTest.java
  DbTypesImpl/src/test/java/io/deephaven/dbtypes/DbImageImplTest.java
  DbTypesImpl/src/test/resources/io/deephaven/dbtypes/white.jpg
  Integrations/build.gradle
  Integrations/python/deephaven/__init__.py
  Integrations/python/deephaven/npy/__init__.py
  Integrations/python/deephaven/npy/table2numpy.py
  Integrations/src/main/java/io/deephaven/integrations/numpy/Java2NumpyCopy.java
  Integrations/src/test/java/io/deephaven/integrations/numpy/Java2NumpyCopyTest.java
  Integrations/src/test/java/io/deephaven/integrations/numpy/dh.jpg
  Integrations/src/test/java/io/deephaven/integrations/numpy/quadrant1.jpg
  Integrations/src/test/java/io/deephaven/integrations/numpy/quadrant2.png
  classpaths.gradle
  configs/dh-defaults.prop
  settings.gradle
  test-configs/dh-tests.prop
Labels: clean up, python, java, DocumentationNeeded, python-server-side

#1599 Add driver:docker to build-ci to fix
  .github/workflows/build-ci.yml
Labels: bug, ci, NoDocumentationNeeded

#1600 Add missing DEEPHAVEN_APPLICATION_DIR to .env files in other docker-compose directories
  redpanda-apicurio/.env
  redpanda/.env
Labels: docker, NoDocumentationNeeded

#1591 Update the debug statement for Java 9+
  grpc-api/server/docker/build.gradle
Labels: NoDocumentationNeeded, internal

#1594 Expose ScopeTicketHelper; refactor java-client for better management …
  grpc-api/src/flightTest/java/io/deephaven/grpc_api/flight/FlightMessageRoundTripTest.java
  grpc-api/src/main/java/io/deephaven/grpc_api/appmode/ApplicationTicketResolver.java
  grpc-api/src/main/java/io/deephaven/grpc_api/console/ScopeTicketResolver.java
  grpc-api/src/main/java/io/deephaven/grpc_api/table/TableServiceGrpcImpl.java
  grpc-api/src/test/java/io/deephaven/grpc_api/session/SessionStateTest.java
  java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java
  java-client/flight-examples/build.gradle
  java-client/flight-examples/src/main/java/io/deephaven/client/examples/DoPutNew.java
  java-client/flight-examples/src/main/java/io/deephaven/client/examples/DoPutSpray.java
  java-client/flight-examples/src/main/java/io/deephaven/client/examples/DoPutTable.java
  java-client/flight-examples/src/main/java/io/deephaven/client/examples/GetApplicationSchema.java
  java-client/flight-examples/src/main/java/io/deephaven/client/examples/GetApplicationTable.java
  java-client/flight-examples/src/main/java/io/deephaven/client/examples/GetDirectSchema.java
  java-client/flight-examples/src/main/java/io/deephaven/client/examples/GetDirectTable.java
  java-client/flight-examples/src/main/java/io/deephaven/client/examples/GetScopeSchema.java
  java-client/flight-examples/src/main/java/io/deephaven/client/examples/GetScopeTable.java
  java-client/flight-examples/src/main/java/io/deephaven/client/examples/KeyValueInputTable.java
  java-client/flight/src/main/java/io/deephaven/client/impl/FlightClientHelper.java
  java-client/flight/src/main/java/io/deephaven/client/impl/FlightSession.java
  java-client/session/src/main/java/io/deephaven/client/impl/ApplicationFieldId.java
  java-client/session/src/main/java/io/deephaven/client/impl/BatchTableRequestBuilder.java
  java-client/session/src/main/java/io/deephaven/client/impl/ConsoleService.java
  java-client/session/src/main/java/io/deephaven/client/impl/Export.java
  java-client/session/src/main/java/io/deephaven/client/impl/ExportId.java
  java-client/session/src/main/java/io/deephaven/client/impl/ExportStates.java
  java-client/session/src/main/java/io/deephaven/client/impl/ExportTicketCreator.java
  java-client/session/src/main/java/io/deephaven/client/impl/HasExportId.java
  java-client/session/src/main/java/io/deephaven/client/impl/HasPathId.java
  java-client/session/src/main/java/io/deephaven/client/impl/HasTicket.java
  java-client/session/src/main/java/io/deephaven/client/impl/HasTicketId.java
  java-client/session/src/main/java/io/deephaven/client/impl/InputTableService.java
  java-client/session/src/main/java/io/deephaven/client/impl/PathId.java
  java-client/session/src/main/java/io/deephaven/client/impl/ScopeId.java
  java-client/session/src/main/java/io/deephaven/client/impl/Session.java
  java-client/session/src/main/java/io/deephaven/client/impl/SessionImpl.java
  java-client/session/src/main/java/io/deephaven/client/impl/TableHandle.java
  java-client/session/src/main/java/io/deephaven/client/impl/TableService.java
  java-client/session/src/main/java/io/deephaven/client/impl/TicketId.java
  java-client/session/src/test/java/io/deephaven/client/impl/ExportStatesTest.java
  proto/proto-backplane-grpc-flight/src/main/java/io/deephaven/grpc_api/util/ArrowHelper.java
  proto/proto-backplane-grpc-flight/src/main/java/io/deephaven/grpc_api/util/FlightExportTicketHelper.java
  proto/proto-backplane-grpc/src/main/java/io/deephaven/grpc_api/util/ApplicationTicketHelper.java
  proto/proto-backplane-grpc/src/main/java/io/deephaven/grpc_api/util/ByteHelper.java
  proto/proto-backplane-grpc/src/main/java/io/deephaven/grpc_api/util/ExportTicketHelper.java
  proto/proto-backplane-grpc/src/main/java/io/deephaven/grpc_api/util/ScopeTicketHelper.java
Labels: clean up, NoDocumentationNeeded, java-client

#1541 Implemented the Table class wrapper, fixes #1486
  configs/dh-defaults.prop
  pyclient/pydeephaven/_table_interface.py
  pyintegration/deephaven2/__init__.py
  pyintegration/deephaven2/_utils/bootstrap.py
  pyintegration/deephaven2/_utils/start_jvm.py
  pyintegration/deephaven2/agg.py
  pyintegration/deephaven2/column.py
  pyintegration/deephaven2/constants.py
  pyintegration/deephaven2/csv.py
  pyintegration/deephaven2/dherror.py
  pyintegration/deephaven2/dtypes.py
  pyintegration/deephaven2/table.py
  pyintegration/tests/__init__.py
  pyintegration/tests/data/test_csv.csv
  pyintegration/tests/data/test_table.csv
  pyintegration/tests/test_csv.py
  pyintegration/tests/test_dbtype.py
  pyintegration/tests/test_script_session.py
  pyintegration/tests/test_table.py
  pyintegration/tests/utils/__init__.py
Labels: NoDocumentationNeeded, python-server-side

#1581 Consolidate test setup/teardown
  DB/benchmark/io/deephaven/benchmark/db/TestSortIncrementalPerformance.java
  DB/src/main/java/io/deephaven/db/v2/utils/AppendOnlyArrayBackedMutableTable.java
  DB/src/main/java/io/deephaven/db/v2/utils/ColumnsToRowsTransform.java
  DB/src/main/java/io/deephaven/db/v2/utils/KeyedArrayBackedMutableTable.java
  DB/src/test/java/io/deephaven/db/tables/select/SelectFilterFactoryTest.java
  DB/src/test/java/io/deephaven/db/tables/utils/TestWindowCheck.java
  DB/src/test/java/io/deephaven/db/tables/verify/TestTableAssertions.java
  DB/src/test/java/io/deephaven/db/v2/FuzzerTest.java
  DB/src/test/java/io/deephaven/db/v2/IndexGroupingTest.java
  DB/src/test/java/io/deephaven/db/v2/JUnit4QueryTableTestBase.java
  DB/src/test/java/io/deephaven/db/v2/LiveTableTestCase.java
  DB/src/test/java/io/deephaven/db/v2/QueryTableAggregationTest.java
  DB/src/test/java/io/deephaven/db/v2/QueryTableAjTest.java
  DB/src/test/java/io/deephaven/db/v2/QueryTableHugeSortTest.java
  DB/src/test/java/io/deephaven/db/v2/QueryTableJoinTest.java
  DB/src/test/java/io/deephaven/db/v2/QueryTableSelectUpdateTest.java
  DB/src/test/java/io/deephaven/db/v2/QueryTableTest.java
  DB/src/test/java/io/deephaven/db/v2/QueryTableTestBase.java
  DB/src/test/java/io/deephaven/db/v2/QueryTableWhereTest.java
  DB/src/test/java/io/deephaven/db/v2/QueryTableWouldMatchTest.java
  DB/src/test/java/io/deephaven/db/v2/StreamTableAggregationTest.java
  DB/src/test/java/io/deephaven/db/v2/StreamTableOperationsTest.java
  DB/src/test/java/io/deephaven/db/v2/TableMapTest.java
  DB/src/test/java/io/deephaven/db/v2/TestComboBy.java
  DB/src/test/java/io/deephaven/db/v2/TestPartitionAwareSourceTable.java
  DB/src/test/java/io/deephaven/db/v2/TestTotalsTable.java
  DB/src/test/java/io/deephaven/db/v2/by/TestSortedFirstOrLastByFactory.java
  DB/src/test/java/io/deephaven/db/v2/select/TestFormulaColumn.java
  DB/src/test/java/io/deephaven/db/v2/select/TestFormulaColumnGeneration.java
  DB/src/test/java/io/deephaven/db/v2/utils/TestDynamicTableWriter.java
  DB/src/test/java/io/deephaven/db/v2/utils/TestKeyedArrayBackedMutableTable.java
  DB/src/test/java/io/deephaven/db/v2/utils/TestReadOnlyRedirectedColumnSource.java
  DB/src/test/java/io/deephaven/test/junit4/EngineCleanup.java
  DB/src/test/java/io/deephaven/test/junit4/JUnit4BaseArrayTestCase.java
  DB/src/test/java/io/deephaven/test/junit4/JUnit4LiveTableTestCase.java
  DB/src/test/java/io/deephaven/util/calendar/StaticCalendarMethodsTest.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/ByteChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/CharChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/DoubleChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/FloatChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/IntChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/LongChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/ShortChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/VarBinaryChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/VarListChunkInputStreamGenerator.java
  extensions/barrage/src/test/java/io/deephaven/extensions/barrage/chunk/BarrageColumnRoundTripTest.java
  grpc-api/src/test/java/io/deephaven/grpc_api/appmode/ApplicationTest.java
  grpc-api/src/test/java/io/deephaven/grpc_api/barrage/BarrageMessageRoundTripTest.java
Labels: test, NoDocumentationNeeded

#1601 Simplify server startup and dagger usage
  grpc-api/src/main/java/io/deephaven/grpc_api/runner/DeephavenApiServer.java
  grpc-api/src/main/java/io/deephaven/grpc_api/runner/DeephavenApiServerComponent.java
  grpc-api/src/main/java/io/deephaven/grpc_api/runner/DeephavenApiServerInProcessComponent.java
  grpc-api/src/main/java/io/deephaven/grpc_api/runner/DeephavenApiServerModule.java
  grpc-api/src/main/java/io/deephaven/grpc_api/runner/Main.java
  grpc-api/src/main/java/io/deephaven/grpc_api/runner/ServerBuilderModule.java
  grpc-api/src/test/java/io/deephaven/grpc_api/runner/DeephavenApiServerTestBase.java
Labels: clean up, NoDocumentationNeeded, internal

#1580 All Time Zones
  web/client-api/src/main/java/io/deephaven/web/client/api/i18n/JsTimeZone.java
Labels: jsapi, DocumentationNeeded

#1614 Cleaned up application script creation. Got barrage-examples running.
  java-client/barrage-examples/build.gradle
  java-client/barrage-examples/src/main/java/io/deephaven/client/examples/SubscribeApplicationField.java
  java-client/barrage-examples/src/main/java/io/deephaven/client/examples/SubscribeExampleBase.java
  java-client/flight-examples/build.gradle
  java-client/session-examples/build.gradle
Labels: clean up, NoDocumentationNeeded

#1612 Set Context.ROOT for Barrage subscription DoExchange
  java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java
Labels: bug, grpc, NoDocumentationNeeded
