Repository deephaven/deephaven-core, pull requests merged in 2021-06, with the labels that each got.

#688 Bring missed RspArray packing from DHE, including latest bugfix for AIOOBE. Fixes #687.
  Container/src/main/java/io/deephaven/db/v2/utils/rsp/container/ArrayContainer.java
  Container/src/main/java/io/deephaven/db/v2/utils/rsp/container/BitmapContainer.java
  Container/src/main/java/io/deephaven/db/v2/utils/rsp/container/RunContainer.java
  DB/benchmark/com/illumon/iris/db/v2/utils/SmallIndexCreation.java
  DB/benchmark/io/deephaven/db/v2/utils/IndexCreation.java
  DB/benchmark/io/deephaven/db/v2/utils/RandomIndexBuilderBench.java
  DB/src/main/java/io/deephaven/db/v2/utils/TreeIndexImplSequentialBuilder.java
  DB/src/main/java/io/deephaven/db/v2/utils/rsp/DisposableRspBitmap.java
  DB/src/main/java/io/deephaven/db/v2/utils/rsp/RspArray.java
  DB/src/main/java/io/deephaven/db/v2/utils/rsp/RspBitmap.java
  DB/src/main/java/io/deephaven/db/v2/utils/rsp/RspIterator.java
  DB/src/main/java/io/deephaven/db/v2/utils/rsp/RspRangeBatchIterator.java
  DB/src/main/java/io/deephaven/db/v2/utils/rsp/RspRangeIterator.java
  DB/src/main/java/io/deephaven/db/v2/utils/rsp/RspReverseIterator.java
  DB/src/test/java/io/deephaven/db/v2/utils/SortedIndexTestBase.java
  DB/src/test/java/io/deephaven/db/v2/utils/TreeIndexTest.java
  DB/src/test/java/io/deephaven/db/v2/utils/rsp/RspBitmapTest.java
Labels: NoDocumentationNeeded

#681 removed the use of DH's own numba annotations, fixes #630
  DB/src/main/java/io/deephaven/db/tables/lang/DBLanguageParser.java
  DB/src/main/java/io/deephaven/db/util/PythonScopeJpyImpl.java
  DB/src/main/java/io/deephaven/db/v2/select/DhFormulaColumn.java
  DB/src/main/java/io/deephaven/db/v2/select/SwitchColumn.java
Labels: DocumentationNeeded

#676 Update badges
  README.md
Labels: NoDocumentationNeeded, ci

#680 Clean up Parquet codec handling for #570
  DB/src/main/java/io/deephaven/db/tables/ColumnDefinition.java
  DB/src/main/java/io/deephaven/db/v2/locations/local/ReadOnlyParquetTableLocation.java
  DB/src/main/java/io/deephaven/db/v2/parquet/TypeInfos.java
  DB/src/main/java/io/deephaven/db/v2/sources/chunk/util/SimpleTypeMap.java
  DB/src/test/java/io/deephaven/db/v2/TestCodecColumns.java
Labels: NoDocumentationNeeded, bug, core, parquet

#717 Fix a bug in RspArray.setOrInsertFullBlockSpan. Fixes #716.
  DB/src/main/java/io/deephaven/db/v2/utils/rsp/RspArray.java
  DB/src/test/java/io/deephaven/db/v2/utils/rsp/RspBitmapTest.java
Labels: NoDocumentationNeeded

#722 Add Cristian and James to github workflows code owners
  .github/CODEOWNERS
Labels: NoDocumentationNeeded, bug

#725 Stop exposing server-created export as a long
  grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java
  grpc-api/src/test/java/io/deephaven/grpc_api/session/SessionStateTest.java
  grpc-api/src/test/java/io/deephaven/grpc_api/table/ExportTableUpdateListenerTest.java
Labels: NoDocumentationNeeded

#720 Update protobuf version to newer to add optional support
  proto/build.gradle
  proto/package-lock.json
  proto/package.json
  protoc/package-lock.json
  protoc/package.json
Labels: NoDocumentationNeeded

#703 removed the DH's numba annotations, fixes #672
  DB/src/main/java/io/deephaven/db/tables/lang/DBLanguageParser.java
  DB/src/main/java/io/deephaven/db/util/PythonScopeJpyImpl.java
  DB/src/main/java/io/deephaven/db/v2/select/AbstractConditionFilter.java
  DB/src/main/java/io/deephaven/db/v2/select/ConditionFilter.java
  DB/src/main/java/io/deephaven/db/v2/select/python/ConditionFilterPython.java
  DB/src/main/java/io/deephaven/db/v2/select/python/DeephavenCompatibleFunction.java
  Integrations/python/deephaven/java/__init__.py
  Integrations/python/deephaven/java/integration.py
  Integrations/python/deephaven/java/primitives.py
  Integrations/python/deephaven/numba/__init__.py
  Integrations/python/deephaven/numba/integration.py
Labels: DocumentationNeeded, python

#731 Fix broken javadoc links.
  build.gradle
Labels: NoDocumentationNeeded, bug, documentation

#739 [Python] initialize global script session after stdout/stderr have been set
  grpc-api/src/main/java/io/deephaven/grpc_api/console/ConsoleServiceGrpcImpl.java
  grpc-api/src/main/java/io/deephaven/grpc_api/runner/DeephavenApiServer.java
Labels: NoDocumentationNeeded

#740 Fix broken javadoc links (part 2)
  .github/workflows/docs-ci.yml
  build.gradle
Labels: NoDocumentationNeeded, bug, documentation

#727 #726: Pass component type into regioned column sources of objects on construction
  DB/src/main/java/io/deephaven/db/tables/CodecLookup.java
  DB/src/main/java/io/deephaven/db/tables/ColumnDefinition.java
  DB/src/main/java/io/deephaven/db/tables/utils/TableManagementTools.java
  DB/src/main/java/io/deephaven/db/v2/locations/local/ReadOnlyParquetTableLocation.java
  DB/src/main/java/io/deephaven/db/v2/locations/parquet/topage/ToDbArrayPage.java
  DB/src/main/java/io/deephaven/db/v2/parquet/MappedSchema.java
  DB/src/main/java/io/deephaven/db/v2/parquet/ParquetTableWriter.java
  DB/src/main/java/io/deephaven/db/v2/parquet/TypeInfos.java
  DB/src/main/java/io/deephaven/db/v2/sources/regioned/RegionedColumnSourceArray.java
  DB/src/main/java/io/deephaven/db/v2/sources/regioned/RegionedColumnSourceBase.java
  DB/src/main/java/io/deephaven/db/v2/sources/regioned/RegionedColumnSourceObject.java
  DB/src/main/java/io/deephaven/db/v2/sources/regioned/RegionedTableComponentFactoryImpl.java
  DB/src/test/java/io/deephaven/db/tables/utils/TestTableManagementTools.java
  DB/src/test/java/io/deephaven/db/v2/TestCodecColumns.java
  DB/src/test/java/io/deephaven/db/v2/sources/regioned/TestDbArrayUngroup.java
Labels: NoDocumentationNeeded, bug, core

#736 implemented a mechanism to add and run Python functional tests on the…
  DB/src/main/java/io/deephaven/db/util/PythonScopeJpyImpl.java
  Integrations/build.gradle
  Integrations/python/functional-tests/__init__.py
  Integrations/python/functional-tests/bootstrap.py
  Integrations/python/functional-tests/numba_vectorized_column_test.py
  Integrations/python/functional-tests/numba_vectorized_filter_test.py
  Integrations/python/functional-tests/pyobj_field_access_test.py
  Integrations/python/run-functional-tests.sh
Labels: NoDocumentationNeeded

#744 Add support for reading Parquet logical type timestamp with millis and micros units. #743
  DB/src/main/java/io/deephaven/db/v2/locations/local/ReadOnlyParquetTableLocation.java
  DB/src/main/java/io/deephaven/db/v2/locations/parquet/topage/ToDBDateTimePage.java
  DB/src/main/java/io/deephaven/db/v2/parquet/ParquetReaderUtil.java
Labels: NoDocumentationNeeded, bug, core, parquet

#735 Run remaining tests in docker (so python is available)
  DB-test/build.gradle
  DB-test/src/test/build.gradle.template
  DB-test/src/test/java/io/deephaven/db/tables/select/PythonMatchFilterTest.java
  DB-test/src/test/java/io/deephaven/db/util/TestWorkerPythonEnvironment.java
  DB-test/src/test/java/io/deephaven/db/v2/select/TestConditionFilter.java
Labels: NoDocumentationNeeded, build, docker, python, test

#737 Added missing `Integrations` dependency
  grpc-api/grpc-api.gradle
Labels: NoDocumentationNeeded, configuration, python

#745 Update the default heap to 4g. Allow introspection using jinfo/jmap.
  docker-compose.yml
Labels: NoDocumentationNeeded, docker

#746 Ensure that the label-check-ci action reruns on new PR commits
  .github/workflows/label-check-ci.yml
Labels: NoDocumentationNeeded, ci

#708 Disable scheduled jobs on forks
  .github/workflows/nightly-benchmarks.yml
  .github/workflows/nightly-check-ci.yml
Labels: NoDocumentationNeeded, ci

#604 Session State Impl Review
  DB/src/main/java/io/deephaven/db/tables/live/LiveTableMonitor.java
  DB/src/main/java/io/deephaven/db/util/liveness/LivenessStateException.java
  Util/src/main/java/io/deephaven/util/datastructures/SimpleReferenceManager.java
  grpc-api/client/simple/src/main/java/io/deephaven/grpc_api/example/SimpleDeephavenClient.java
  grpc-api/src/main/java/io/deephaven/grpc_api/barrage/BarrageServiceGrpcImpl.java
  grpc-api/src/main/java/io/deephaven/grpc_api/console/ConsoleServiceGrpcImpl.java
  grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionService.java
  grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionServiceGrpcImpl.java
  grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java
  grpc-api/src/main/java/io/deephaven/grpc_api/table/ExportedTableUpdateListener.java
  grpc-api/src/main/java/io/deephaven/grpc_api/table/TableServiceGrpcImpl.java
  grpc-api/src/main/java/io/deephaven/grpc_api/util/GrpcUtil.java
  grpc-api/src/test/java/io/deephaven/grpc_api/session/SessionServiceTest.java
  grpc-api/src/test/java/io/deephaven/grpc_api/session/SessionStateTest.java
  grpc-api/src/test/java/io/deephaven/grpc_api/table/ExportTableUpdateListenerTest.java
  proto/proto-backplane-grpc/src/main/proto/io/deephaven/proto/session.proto
  proto/proto-backplane-grpc/src/main/proto/io/deephaven/proto/table.proto
Labels: NoDocumentationNeeded, grpc

#686 Improve release process, ensure proper docker tags, ensure CI jobs on…
  .github/workflows/build-ci.yml
  .github/workflows/check-ci.yml
  .github/workflows/long-check-ci.yml
  .github/workflows/nightly-check-ci.yml
  build.gradle
Labels: NoDocumentationNeeded, ci

#748 SessionState: retain reference to nonExports until work is complete
  grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java
  grpc-api/src/test/java/io/deephaven/grpc_api/session/SessionStateTest.java
Labels: NoDocumentationNeeded, grpc

#705 Remove ADO support/dependency from TableDefinition and ColumnDefinition. Fixes #704
  BenchmarkSupport/src/main/java/io/deephaven/benchmarking/impl/AbstractGeneratedTable.java
  DB/resources/DeephavenColumns.xml
  DB/src/main/java/io/deephaven/db/tables/ColumnDefinition.java
  DB/src/main/java/io/deephaven/db/tables/DefaultColumnDefinition.java
  DB/src/main/java/io/deephaven/db/tables/DefaultTableDefinition.java
  DB/src/main/java/io/deephaven/db/tables/Table.java
  DB/src/main/java/io/deephaven/db/tables/TableDefinition.java
  DB/src/main/java/io/deephaven/db/tables/utils/NewColumnsBufferUtils.java
  DB/src/main/java/io/deephaven/db/tables/utils/TableManagementTools.java
  DB/src/main/java/io/deephaven/db/util/string/StringUtils.java
  DB/src/main/java/io/deephaven/db/v2/InMemoryTable.java
  DB/src/main/java/io/deephaven/db/v2/NestedPartitionedDiskBackedTable.java
  DB/src/main/java/io/deephaven/db/v2/PartitionAwareSourceTable.java
  DB/src/main/java/io/deephaven/db/v2/SourceTable.java
  DB/src/main/java/io/deephaven/db/v2/SourceTableMap.java
  DB/src/main/java/io/deephaven/db/v2/SplayedDiskBackedTable.java
  DB/src/main/java/io/deephaven/db/v2/by/ByExternalChunkedOperator.java
  DB/src/main/java/io/deephaven/db/v2/sources/EmptyToNullStringRegionedColumnSource.java
  DB/src/test/java/io/deephaven/db/tables/TestColumnDefinition.java
  DB/src/test/java/io/deephaven/db/tables/lang/TestDBLanguageParser.java
  DB/src/test/java/io/deephaven/db/v2/TestPartitionAwareSourceTable.java
  DB/src/test/java/io/deephaven/db/v2/locations/TestGroupingProviders.java
  DB/src/test/java/io/deephaven/db/v2/select/TestFormulaColumn.java
  DB/src/test/java/io/deephaven/db/v2/sources/regioned/TestChunkedRegionedOperations.java
  DataObjects/build.gradle
  DataObjects/src/main/java/io/deephaven/dataobjects/AbstractDataObject.java
  DataObjects/src/main/java/io/deephaven/dataobjects/AbstractDataObjectImpl.java
  DataObjects/src/main/java/io/deephaven/dataobjects/DataObjectColumn.java
  DataObjects/src/main/java/io/deephaven/dataobjects/DataObjectColumnSet.java
  DataObjects/src/main/java/io/deephaven/dataobjects/DataObjectColumnSetManager.java
  DataObjects/src/main/java/io/deephaven/dataobjects/persistence/ColumnsetConversionSchema.java
  DataObjects/src/main/java/io/deephaven/dataobjects/persistence/CustomClassLoaderObjectInputStream.java
  DataObjects/src/main/java/io/deephaven/dataobjects/persistence/DataObjectInputConversions.java
  DataObjects/src/main/java/io/deephaven/dataobjects/persistence/DataObjectInputStream.java
  DataObjects/src/main/java/io/deephaven/dataobjects/persistence/DataObjectOutputStream.java
  DataObjects/src/main/java/io/deephaven/dataobjects/persistence/DataObjectStreamConstants.java
  DataObjects/src/main/java/io/deephaven/dataobjects/persistence/PersistentInputStream.java
  DataObjects/src/main/java/io/deephaven/dataobjects/persistence/PersistentOutputStream.java
  DataStructures/src/main/java/io/deephaven/datastructures/util/HashCodeUtil.java
  Net/build.gradle
  Plot/src/main/java/io/deephaven/db/plot/util/functions/SerializableClosure.java
  classpaths.gradle
  settings.gradle
Labels: NoDocumentationNeeded

#750 Do not register script session as global except in the grpc worker.
  DB/src/main/java/io/deephaven/db/util/AbstractScriptSession.java
  DB/src/main/java/io/deephaven/db/util/GroovyDeephavenSession.java
  DB/src/main/java/io/deephaven/db/util/NoLanguageDeephavenSession.java
  DB/src/main/java/io/deephaven/db/util/PythonDeephavenSession.java
  DB/src/main/java/io/deephaven/db/util/ScalaDeephavenSession.java
  grpc-api/src/main/java/io/deephaven/grpc_api/console/groovy/GroovyConsoleSessionModule.java
  grpc-api/src/main/java/io/deephaven/grpc_api/console/python/PythonConsoleSessionModule.java
Labels: NoDocumentationNeeded, grpc

#751 Port of DH-11264: Static cross join rehash bug fix
  DB/src/main/java/io/deephaven/db/v2/AsOfJoinHelper.java
  DB/src/main/java/io/deephaven/db/v2/CrossJoinHelper.java
  DB/src/main/java/io/deephaven/db/v2/JoinRedirectionIndex.java
  DB/src/main/java/io/deephaven/db/v2/ReplicateHashTable.java
  DB/src/main/java/io/deephaven/db/v2/StaticChunkedCrossJoinStateManager.java
  DB/src/test/java/io/deephaven/db/v2/QueryTableCrossJoinTestBase.java
Labels: NoDocumentationNeeded, core, query engine

#749 Regenerate GWT bindings for features already merged
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/barrage/flatbuf/barrage_generated/io/deephaven/barrage/flatbuf/BarragePutMetadata.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/console_pb/GetConsoleTypesRequest.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/console_pb/GetConsoleTypesResponse.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/console_pb_service/ConsoleService.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/console_pb_service/ConsoleServiceClient.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/session_pb/exportnotification/StateMap.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/table_pb/ExportedTableUpdateBatchMessage.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/table_pb/TableReference.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/table_pb_service/TableServiceClient.java
Labels: NoDocumentationNeeded

#724 Remove plot theme api
  Generators/src/main/java/io/deephaven/db/plot/util/GeneratePlottingConvenience.java
  Integrations/python/test/testFigureWrapper.py
  Integrations/python/test/testPlot.py
  Plot/src/main/java/io/deephaven/db/plot/BaseFigure.java
  Plot/src/main/java/io/deephaven/db/plot/BaseFigureImpl.java
  Plot/src/main/java/io/deephaven/db/plot/ChartImpl.java
  Plot/src/main/java/io/deephaven/db/plot/Figure.java
  Plot/src/main/java/io/deephaven/db/plot/FigureImpl.java
  Plot/src/main/java/io/deephaven/db/plot/FigureWidgetTranslator.java
  Plot/src/main/java/io/deephaven/db/plot/PlottingConvenience.java
  Plot/src/main/java/io/deephaven/db/plot/Theme.java
  Plot/src/main/java/io/deephaven/db/plot/themes/ThemeImpl.java
  Plot/src/main/java/io/deephaven/db/plot/themes/Themes.java
  Plot/src/main/java/io/deephaven/db/plot/util/PlotUtils.java
  Plot/src/test/java/io/deephaven/db/plot/TestBaseFigureImpl.java
  Plot/src/test/java/io/deephaven/db/plot/datasets/category/TestAbstractCategoryDataSeries.java
  Plot/src/test/java/io/deephaven/db/plot/datasets/xy/TestAbstractXYDataSeries.java
  Plot/src/test/java/io/deephaven/db/plot/datasets/xy/TestXYDataSeriesArray.java
  Plot/src/test/java/io/deephaven/db/plot/example_plots/PrettyChart1.java
  Plot/src/test/java/io/deephaven/db/plot/example_plots/SimpleXYPlot4.java
  Plot/src/test/java/io/deephaven/db/plot/example_plots/SimpleXYPlot5.java
  Plot/src/test/java/io/deephaven/db/plot/example_plots/plotting_samples.groovy
  Plot/src/test/java/io/deephaven/db/plot/themes/Test.theme
  Plot/src/test/java/io/deephaven/db/plot/themes/TestTheme.java
Labels: NoDocumentationNeeded

#756 Add server notebook storage support
  docker-compose.yml
  envoy/contents/envoy.yaml
  web/client-ide/client-ide.gradle
  web/client-ide/docker/Dockerfile
  web/client-ide/nginx/99-init-notebooks.sh
  web/client-ide/nginx/default.conf
  web/client-ide/nginx/nginx.conf
Labels: DocumentationNeeded, feature request, notebook

#758 Update web to v0.1.4
  web/client-ui/Dockerfile
Labels: NoDocumentationNeeded, web ui

#682 Revive autocomplete in IDE #649
  DB/DB.gradle
  DB/src/main/java/io/deephaven/db/util/AbstractScriptSession.java
  DB/src/main/java/io/deephaven/db/util/ScriptSession.java
  DB/src/main/java/io/deephaven/db/util/VariableProvider.java
  grpc-api/grpc-api.gradle
  grpc-api/src/main/java/io/deephaven/grpc_api/console/ConsoleServiceGrpcImpl.java
  open-api/lang-api/lang-api.gradle
  open-api/lang-api/src/main/java/io/deephaven/lang/parse/api/CompletionParseService.java
  open-api/lang-api/src/main/java/io/deephaven/lang/parse/api/CompletionParseServiceNoOp.java
  open-api/lang-api/src/main/java/io/deephaven/lang/parse/api/ParsedResult.java
  open-api/lang-parser/lang-parser.gradle
  open-api/lang-parser/src/javacc/java/io/deephaven/lang/generated/ChunkerTokenManager.java
  open-api/lang-parser/src/jjtree/java/io/deephaven/lang/generated/Chunker.jj
  open-api/lang-parser/src/main/java/io/deephaven/lang/generated/BaseToken.java
  open-api/lang-parser/src/main/java/io/deephaven/lang/generated/Node.java
  open-api/lang-parser/src/main/java/io/deephaven/lang/parse/CompletionParser.java
  open-api/lang-parser/src/main/java/io/deephaven/lang/parse/LspTools.java
  open-api/lang-parser/src/main/java/io/deephaven/lang/parse/ParsedDocument.java
  open-api/lang-parser/src/main/java/io/deephaven/lang/parse/PendingParse.java
  open-api/lang-parser/src/main/jjtree/io/deephaven/lang/generated/Chunker.jjt
  open-api/lang-parser/src/main/resources/META-INF/services/io.deephaven.lang.parse.api.CompletionParseService
  open-api/lang-tools/src/main/java/io/deephaven/lang/completion/ChunkerCompleter.java
  open-api/lang-tools/src/main/java/io/deephaven/lang/completion/CompletionHandler.java
  open-api/lang-tools/src/main/java/io/deephaven/lang/completion/CompletionRequest.java
  open-api/lang-tools/src/main/java/io/deephaven/lang/completion/DelegatingCompletionHandler.java
  open-api/lang-tools/src/main/java/io/deephaven/lang/completion/results/CompleteAssignment.java
  open-api/lang-tools/src/main/java/io/deephaven/lang/completion/results/CompleteColumnExpression.java
  open-api/lang-tools/src/main/java/io/deephaven/lang/completion/results/CompleteColumnName.java
  open-api/lang-tools/src/main/java/io/deephaven/lang/completion/results/CompleteInvocation.java
  open-api/lang-tools/src/main/java/io/deephaven/lang/completion/results/CompleteTableName.java
  open-api/lang-tools/src/main/java/io/deephaven/lang/completion/results/CompleteTableNamespace.java
  open-api/lang-tools/src/main/java/io/deephaven/lang/completion/results/CompleteVarName.java
  open-api/lang-tools/src/main/java/io/deephaven/lang/completion/results/CompletionBuilder.java
  open-api/lang-tools/src/test/groovy/io/deephaven/lang/completion/ChunkerCompleterMixin.groovy
  open-api/lang-tools/src/test/groovy/io/deephaven/lang/completion/ChunkerCompletionHandlerTest.groovy
  open-api/lang-tools/src/test/groovy/io/deephaven/lang/completion/ChunkerParseTestMixin.groovy
  open-api/lang-tools/src/test/groovy/io/deephaven/lang/completion/ChunkerParserTest.groovy
  open-api/lang-tools/src/test/groovy/io/deephaven/lang/completion/ColumnExpressionCompletionHandlerTest.groovy
  settings.gradle
  web/client-api/src/main/java/io/deephaven/ide/shared/IdeSession.java
  web/client-api/src/main/java/io/deephaven/ide/shared/LspTranslate.java
Labels: NoDocumentationNeeded

#747 Remove the rest of BUILD_PY and the old python build wiring
  .github/workflows/docs-ci.yml
  DB-test/build.gradle
  Generators/Generators.gradle
  Integrations/build.gradle
  buildSrc/src/main/groovy/PyEnv.groovy
  buildSrc/src/main/groovy/PyInstall.groovy
  buildSrc/src/main/groovy/PySpec.groovy
  buildSrc/src/main/groovy/PySpecType.groovy
  buildSrc/src/main/groovy/PythonConstants.groovy
  buildSrc/src/main/groovy/PythonVersion.groovy
  buildSrc/src/main/groovy/Venv.groovy
  buildSrc/src/main/groovy/VenvType.groovy
  gradle/deephaven-jpy.gradle
  py/jpy-integration/build.gradle
  sphinx/sphinx.gradle
Labels: NoDocumentationNeeded, build, python

#773 improve the performance of tableToDataFrame()
  DB/src/main/java/io/deephaven/db/v2/IndexedDataColumn.java
  Integrations/python/deephaven/java_to_python.py
Labels: NoDocumentationNeeded, bug, python

#763 Automatically map spaces in column names to underscores. Support loading binary data without codec. Towards #713
  DB/src/main/java/io/deephaven/db/tables/ColumnDefinition.java
  DB/src/main/java/io/deephaven/db/tables/utils/TableManagementTools.java
  DB/src/main/java/io/deephaven/db/v2/locations/AbstractTableLocation.java
  DB/src/main/java/io/deephaven/db/v2/locations/local/ReadOnlyLocalTableLocationProvider.java
  DB/src/main/java/io/deephaven/db/v2/locations/local/ReadOnlyLocalTableLocationProviderByParquetFile.java
  DB/src/main/java/io/deephaven/db/v2/locations/local/ReadOnlyParquetTableLocation.java
  DB/src/main/java/io/deephaven/db/v2/parquet/ParquetInstructions.java
  DB/src/main/java/io/deephaven/db/v2/parquet/ParquetReaderUtil.java
  DB/src/test/java/io/deephaven/db/v2/TestCodecColumns.java
  DB/src/test/java/io/deephaven/db/v2/locations/TestGroupingProviders.java
  DB/src/test/java/io/deephaven/db/v2/sources/regioned/TestChunkedRegionedOperations.java
  Util/src/main/java/io/deephaven/util/codec/ByteArrayCodec.java
  Util/src/main/java/io/deephaven/util/codec/SimpleByteArrayCodec.java
  Util/src/test/java/io/deephaven/util/codec/ByteArrayCodecTest.java
Labels: NoDocumentationNeeded

#765 Port Parquet INT96 timestamp support from DHE. Towards #620
  DB/src/main/java/io/deephaven/db/v2/locations/local/ReadOnlyParquetTableLocation.java
  DB/src/main/java/io/deephaven/db/v2/locations/parquet/topage/ToDBDateTimePageFromInt96.java
  DB/src/main/java/io/deephaven/db/v2/parquet/ParquetReaderUtil.java
Labels: NoDocumentationNeeded

#784 Update web to v0.1.5
  web/client-ui/Dockerfile
Labels: NoDocumentationNeeded

#791 Update hadoop-common (parquet depdendency) to 2.10.1. Fixes #790
  Parquet/Parquet.gradle
  ParquetHadoop/build.gradle
Labels: NoDocumentationNeeded

#789 Use DBNameValidator for checking parquet column names and column name mappings. Fixes #787
  DB/src/main/java/io/deephaven/db/tables/utils/TableManagementTools.java
  DB/src/main/java/io/deephaven/db/v2/parquet/ParquetInstructions.java
  DB/src/main/java/io/deephaven/db/v2/parquet/ParquetReaderUtil.java
Labels: NoDocumentationNeeded

#792 Snapshot: manage snapshotTable for liveness
  DB/src/main/java/io/deephaven/db/v2/snapshot/SnapshotInternalListener.java
  DB/src/test/java/io/deephaven/db/v2/TestConcurrentInstantiation.java
Labels: NoDocumentationNeeded, bug, core

#797 Reduce autocomplete logging noise (#796)
  grpc-api/src/main/java/io/deephaven/grpc_api/console/ConsoleServiceGrpcImpl.java
  open-api/lang-api/src/main/java/io/deephaven/lang/parse/api/CompletionParseService.java
  open-api/lang-api/src/main/java/io/deephaven/lang/parse/api/CompletionParseServiceNoOp.java
  open-api/lang-parser/lang-parser.gradle
  open-api/lang-parser/src/main/java/io/deephaven/lang/parse/CompletionParser.java
  open-api/lang-parser/src/main/java/io/deephaven/lang/parse/PendingParse.java
  open-api/lang-tools/src/test/groovy/io/deephaven/lang/completion/ChunkerCompletionHandlerTest.groovy
Labels: NoDocumentationNeeded

#794 Remove TableTools.emptyTable overload that takes a definition
  BenchmarkSupport/src/main/java/io/deephaven/benchmarking/impl/AbstractGeneratedTable.java
  DB/src/main/java/io/deephaven/db/tables/utils/TableTools.java
  DB/src/main/java/io/deephaven/db/v2/LocalTableMap.java
  DB/src/main/java/io/deephaven/db/v2/by/NullColumnAggregationTransformer.java
  DB/src/main/java/io/deephaven/db/v2/select/NullSelectColumn.java
  DB/src/main/java/io/deephaven/db/v2/sources/NullValueColumnSource.java
  DB/src/main/java/io/deephaven/db/v2/utils/AppendOnlyArrayBackedMutableTable.java
  DB/src/main/java/io/deephaven/db/v2/utils/KeyedArrayBackedMutableTable.java
  DB/src/main/java/io/deephaven/db/v2/utils/TableBuilder.java
  Integrations/python/deephaven/TableTools/__init__.py
  Integrations/python/deephaven/doc/io/deephaven/db/tables/utils/TableTools.json
  Integrations/python/test/testTableTools.py
  grpc-api/src/main/java/io/deephaven/grpc_api/table/ops/EmptyTableGrpcImpl.java
  proto/proto-backplane-grpc/src/main/proto/io/deephaven/proto/table.proto
  web/client-api/src/main/java/io/deephaven/ide/shared/IdeSession.java
  web/client-api/src/main/java/io/deephaven/web/client/api/WorkerConnection.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/table_pb/EmptyTableRequest.java
Labels: NoDocumentationNeeded

#805 Support empty pooled writable chunks
  DB/src/main/java/io/deephaven/db/v2/sources/chunk/util/pools/BooleanChunkPool.java
  DB/src/main/java/io/deephaven/db/v2/sources/chunk/util/pools/ByteChunkPool.java
  DB/src/main/java/io/deephaven/db/v2/sources/chunk/util/pools/CharChunkPool.java
  DB/src/main/java/io/deephaven/db/v2/sources/chunk/util/pools/DoubleChunkPool.java
  DB/src/main/java/io/deephaven/db/v2/sources/chunk/util/pools/FloatChunkPool.java
  DB/src/main/java/io/deephaven/db/v2/sources/chunk/util/pools/IntChunkPool.java
  DB/src/main/java/io/deephaven/db/v2/sources/chunk/util/pools/LongChunkPool.java
  DB/src/main/java/io/deephaven/db/v2/sources/chunk/util/pools/ObjectChunkPool.java
  DB/src/main/java/io/deephaven/db/v2/sources/chunk/util/pools/ShortChunkPool.java
  DB/src/test/java/io/deephaven/db/v2/sources/chunk/util/pools/TestChunkPooling.java
Labels: NoDocumentationNeeded, core

#798 Support additional parquet compression codecs. Fixes #714
  DB/src/main/java/io/deephaven/db/tables/utils/TableManagementTools.java
  DB/src/main/java/io/deephaven/db/v2/parquet/ParquetTableWriter.java
  DB/src/test/java/io/deephaven/db/tables/utils/TestTableManagementTools.java
  Integrations/build.gradle
  Integrations/python/deephaven/TableManagementTools/__init__.py
  Parquet/Parquet.gradle
  Parquet/src/main/java/io/deephaven/parquet/utils/CachedChannelProvider.java
  ParquetHadoop/build.gradle
  build.gradle
Labels: NoDocumentationNeeded

#808 Make Ryan co-code owner with Chip
  .github/CODEOWNERS
Labels: NoDocumentationNeeded

#811 Add BarrageRoundTripTest to OutOfBand test category
  grpc-api/grpc-api.gradle
  grpc-api/src/test/java/io/deephaven/grpc_api/table/BarrageMessageRoundTripTest.java
Labels: NoDocumentationNeeded, build

#812 Fix location of grpc-api-client tests so they actually run
  grpc-api-client/src/test/java/io/deephaven/grpc_api_client/barrage/chunk/BarrageColumnRoundTripTest.java
Labels: NoDocumentationNeeded, test

#809 Fixes #807 by null checking before invalid unbox during ungroup
  DB/src/main/java/io/deephaven/db/v2/sources/UngroupedBoxedByteArrayColumnSource.java
  DB/src/main/java/io/deephaven/db/v2/sources/UngroupedBoxedCharArrayColumnSource.java
  DB/src/main/java/io/deephaven/db/v2/sources/UngroupedBoxedDoubleArrayColumnSource.java
  DB/src/main/java/io/deephaven/db/v2/sources/UngroupedBoxedFloatArrayColumnSource.java
  DB/src/main/java/io/deephaven/db/v2/sources/UngroupedBoxedIntArrayColumnSource.java
  DB/src/main/java/io/deephaven/db/v2/sources/UngroupedBoxedLongArrayColumnSource.java
  DB/src/main/java/io/deephaven/db/v2/sources/UngroupedBoxedShortArrayColumnSource.java
  DB/src/test/java/io/deephaven/db/v2/QueryTableTest.java
Labels: NoDocumentationNeeded, bug, core

#810 Extracted ticket utility code so it can be used without depending on DB
  DB/DB.gradle
  grpc-api-client/build.gradle
  grpc-api-client/console/src/main/java/io/deephaven/grpc_api/example/ConsoleClient.java
  grpc-api-client/simple/src/main/java/io/deephaven/grpc_api/example/SimpleDeephavenClient.java
  grpc-api/grpc-api.gradle
  grpc-api/src/main/java/io/deephaven/grpc_api/console/ScopeTicketResolver.java
  grpc-api/src/main/java/io/deephaven/grpc_api/session/ExportTicketResolver.java
  grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java
  grpc-api/src/main/java/io/deephaven/grpc_api/session/TicketRouter.java
  grpc-api/src/main/java/io/deephaven/grpc_api/table/ExportedTableUpdateListener.java
  grpc-api/src/main/java/io/deephaven/grpc_api/table/TableServiceGrpcImpl.java
  grpc-api/src/main/java/io/deephaven/grpc_api/util/GrpcUtil.java
  grpc-api/src/test/java/io/deephaven/grpc_api/session/SessionStateTest.java
  open-api/lang-parser/lang-parser.gradle
  proto/proto-backplane-grpc-util/build.gradle
  proto/proto-backplane-grpc-util/src/main/java/com/google/protobuf/ByteStringAccess.java
  proto/proto-backplane-grpc-util/src/main/java/io/deephaven/grpc_api/util/Exceptions.java
  proto/proto-backplane-grpc-util/src/main/java/io/deephaven/grpc_api/util/ExportTicketHelper.java
  proto/proto-backplane-grpc-util/src/main/java/io/deephaven/grpc_api/util/TicketRouterHelper.java
  settings.gradle
Labels: NoDocumentationNeeded, grpc
