Repository deephaven/deephaven-core, pull requests merged in 2021-07, with the labels that each got.

#815 Bump next version to 0.3.0
  .github/workflows/build-ci.yml
  build.gradle
Labels: NoDocumentationNeeded, build, ci

#823 Update Web UI v0.1.7
  web/client-ui/Dockerfile
Labels: DocumentationNeeded

#783 Add static analysis to autocomplete from newTable calls (#655)
  open-api/lang-tools/src/main/java/io/deephaven/lang/completion/ChunkerCompleter.java
  open-api/lang-tools/src/main/java/io/deephaven/lang/completion/CompletionRequest.java
  open-api/lang-tools/src/test/groovy/io/deephaven/lang/completion/ChunkerCompletionHandlerTest.groovy
  open-api/lang-tools/src/test/groovy/io/deephaven/lang/completion/ChunkerGroovyTest.groovy
  open-api/lang-tools/src/test/groovy/io/deephaven/lang/completion/ChunkerParseTestMixin.groovy
  open-api/lang-tools/src/test/groovy/io/deephaven/lang/completion/ChunkerParserTest.groovy
  open-api/lang-tools/src/test/groovy/io/deephaven/lang/completion/ChunkerPythonTest.groovy
  open-api/lang-tools/src/test/groovy/io/deephaven/lang/completion/ColumnExpressionCompletionHandlerTest.groovy
Labels: NoDocumentationNeeded, console-autocomplete, py-autocomplete

#839 Fix loading of parquet non-dictionary encoded pages from a column chunk that has a dictionary. Fixes #838
  DB/src/main/java/io/deephaven/db/v2/locations/parquet/topage/ToObjectPage.java
  DB/src/main/java/io/deephaven/db/v2/locations/parquet/topage/ToPageWithDictionary.java
  DB/src/main/java/io/deephaven/db/v2/locations/parquet/topage/ToStringPage.java
  Parquet/src/main/java/io/deephaven/parquet/ColumnChunkReaderImpl.java
Labels: NoDocumentationNeeded

#844 Make autocomplete stop spamming logs with junk
  open-api/lang-tools/src/main/java/io/deephaven/lang/completion/ChunkerCompleter.java
Labels: NoDocumentationNeeded, autocomplete

#852 Fix aj/raj match expression parsing
  DB/src/main/java/io/deephaven/db/tables/Table.java
Labels: NoDocumentationNeeded, test

#851 Name validator rename
  DB/src/main/java/io/deephaven/db/tables/select/MatchPair.java
  DB/src/main/java/io/deephaven/db/tables/select/QueryScope.java
  DB/src/main/java/io/deephaven/db/tables/select/WouldMatchPair.java
  DB/src/main/java/io/deephaven/db/tables/utils/CsvHelpers.java
  DB/src/main/java/io/deephaven/db/tables/utils/LayoutHintBuilder.java
  DB/src/main/java/io/deephaven/db/tables/utils/ParquetTools.java
  DB/src/main/java/io/deephaven/db/util/GroovyDeephavenSession.java
  DB/src/main/java/io/deephaven/db/v2/by/ApproximatePercentile.java
  DB/src/main/java/io/deephaven/db/v2/by/CountAggregationFactory.java
  DB/src/main/java/io/deephaven/db/v2/by/FirstOrLastByAggregationFactory.java
  DB/src/main/java/io/deephaven/db/v2/select/AbstractFormulaColumn.java
  DB/src/main/java/io/deephaven/db/v2/select/FunctionalColumn.java
  DB/src/main/java/io/deephaven/db/v2/select/MultiSourceFunctionalColumn.java
  DB/src/main/java/io/deephaven/db/v2/select/ReinterpretedColumn.java
  DB/src/main/java/io/deephaven/db/v2/select/SourceColumn.java
  DB/src/main/java/io/deephaven/db/v2/select/SwitchColumn.java
  DB/src/main/java/io/deephaven/db/v2/utils/ColumnHolder.java
  DB/src/main/java/io/deephaven/util/calendar/Calendars.java
  DB/src/test/java/io/deephaven/db/tables/utils/TestDBNameValidator.java
  KafkaIngester/src/main/java/io/deephaven/kafka/ingest/PojoConsumerRecordToTableWriterAdapter.java
  grpc-api/src/main/java/io/deephaven/grpc_api/barrage/util/BarrageSchemaUtil.java
  table-api/src/main/java/io/deephaven/api/ColumnName.java
  table-api/src/main/java/io/deephaven/db/tables/utils/NameValidator.java
  table-api/src/test/java/io/deephaven/db/tables/utils/TestNameValidator.java
Labels: NoDocumentationNeeded, clean up, test

#856 Fix writing empty tables; fix missing beginning magic number. Fixes #855
  DB/src/main/java/io/deephaven/db/v2/locations/local/ReadOnlyParquetTableLocation.java
  DB/src/main/java/io/deephaven/db/v2/parquet/ParquetTableWriter.java
  DB/src/test/java/io/deephaven/db/v2/parquet/ParquetTableReadWriteTest.java
  Parquet/src/main/java/io/deephaven/parquet/ColumnWriterImpl.java
  Parquet/src/main/java/io/deephaven/parquet/ParquetFileReader.java
  Parquet/src/main/java/io/deephaven/parquet/ParquetFileWriter.java
Labels: NoDocumentationNeeded

#848 Use symbol tables for table definitions loaded from parquet files when appropriate. Fixes #847
  DB/src/main/java/io/deephaven/db/tables/ColumnDefinition.java
  DB/src/main/java/io/deephaven/db/tables/utils/ParquetTools.java
  DB/src/main/java/io/deephaven/db/v2/locations/parquet/topage/ToStringPage.java
  DB/src/main/java/io/deephaven/db/v2/parquet/ParquetSchemaReader.java
  DB/src/main/java/io/deephaven/db/v2/parquet/ParquetTableWriter.java
  DB/src/test/java/io/deephaven/db/v2/parquet/ParquetTableReadWriteTest.java
  Parquet/src/main/java/io/deephaven/parquet/ParquetFileReader.java
  Parquet/src/main/java/io/deephaven/parquet/RowGroupReaderImpl.java
Labels: NoDocumentationNeeded

#864 Ensure replicate is deterministic, doesn't try writing to the wrong project
  CompilerTools/src/main/java/io/deephaven/compilertools/ReplicatePrimitiveCode.java
Labels: NoDocumentationNeeded, build

#870 Update build.gradle
  build.gradle
Labels: NoDocumentationNeeded, size:1, triage

#876 Update web-client-ui to v0.2.0
  web/client-ui/Dockerfile
Labels: NoDocumentationNeeded, web-client-ui

#885 Support arbitrary types in partitioning columns
  DB/src/main/java/io/deephaven/db/tables/utils/ParquetTools.java
  DB/src/main/java/io/deephaven/db/v2/PartitionAwareSourceTable.java
  DB/src/main/java/io/deephaven/db/v2/locations/impl/TableLocationFactory.java
  DB/src/main/java/io/deephaven/db/v2/locations/local/DeephavenNestedPartitionLayout.java
  DB/src/main/java/io/deephaven/db/v2/sources/chunk/page/Page.java
  DB/src/main/java/io/deephaven/db/v2/sources/regioned/ColumnRegion.java
  DB/src/main/java/io/deephaven/db/v2/sources/regioned/ColumnRegionByte.java
  DB/src/main/java/io/deephaven/db/v2/sources/regioned/ColumnRegionChar.java
  DB/src/main/java/io/deephaven/db/v2/sources/regioned/ColumnRegionDouble.java
  DB/src/main/java/io/deephaven/db/v2/sources/regioned/ColumnRegionFloat.java
  DB/src/main/java/io/deephaven/db/v2/sources/regioned/ColumnRegionInt.java
  DB/src/main/java/io/deephaven/db/v2/sources/regioned/ColumnRegionLong.java
  DB/src/main/java/io/deephaven/db/v2/sources/regioned/ColumnRegionObject.java
  DB/src/main/java/io/deephaven/db/v2/sources/regioned/ColumnRegionShort.java
  DB/src/main/java/io/deephaven/db/v2/sources/regioned/ParquetColumnRegionBase.java
  DB/src/main/java/io/deephaven/db/v2/sources/regioned/ParquetColumnRegionByte.java
  DB/src/main/java/io/deephaven/db/v2/sources/regioned/ParquetColumnRegionChar.java
  DB/src/main/java/io/deephaven/db/v2/sources/regioned/ParquetColumnRegionDouble.java
  DB/src/main/java/io/deephaven/db/v2/sources/regioned/ParquetColumnRegionFloat.java
  DB/src/main/java/io/deephaven/db/v2/sources/regioned/ParquetColumnRegionInt.java
  DB/src/main/java/io/deephaven/db/v2/sources/regioned/ParquetColumnRegionLong.java
  DB/src/main/java/io/deephaven/db/v2/sources/regioned/ParquetColumnRegionShort.java
  DB/src/main/java/io/deephaven/db/v2/sources/regioned/PartitioningSourceFactory.java
  DB/src/main/java/io/deephaven/db/v2/sources/regioned/RegionedColumnSourceByte.java
  DB/src/main/java/io/deephaven/db/v2/sources/regioned/RegionedColumnSourceChar.java
  DB/src/main/java/io/deephaven/db/v2/sources/regioned/RegionedColumnSourceDouble.java
  DB/src/main/java/io/deephaven/db/v2/sources/regioned/RegionedColumnSourceFloat.java
  DB/src/main/java/io/deephaven/db/v2/sources/regioned/RegionedColumnSourceInt.java
  DB/src/main/java/io/deephaven/db/v2/sources/regioned/RegionedColumnSourceLong.java
  DB/src/main/java/io/deephaven/db/v2/sources/regioned/RegionedColumnSourceObject.java
  DB/src/main/java/io/deephaven/db/v2/sources/regioned/RegionedColumnSourcePartitioning.java
  DB/src/main/java/io/deephaven/db/v2/sources/regioned/RegionedColumnSourceShort.java
  DB/src/main/java/io/deephaven/db/v2/sources/regioned/RegionedColumnSourceStringSet.java
  DB/src/main/java/io/deephaven/db/v2/sources/regioned/RegionedPageStore.java
  DB/src/main/java/io/deephaven/db/v2/sources/regioned/RegionedTableComponentFactoryImpl.java
  DB/src/test/java/io/deephaven/db/tables/utils/TestParquetTools.java
  DB/src/test/java/io/deephaven/db/v2/TestPartitioningColumns.java
  Integrations/python/deephaven/doc/io/deephaven/datastructures/util/CollectionUtil.json
  Integrations/python/deephaven/doc/io/deephaven/datastructures/util/HashCodeUtil.json
  Integrations/python/deephaven/doc/io/deephaven/datastructures/util/SmartKey.json
  Integrations/python/deephaven/doc/io/deephaven/db/v2/sources/chunk/page/Page.json
  Integrations/python/deephaven/doc/io/deephaven/db/v2/sources/chunk/page/Page/WithDefaults.json
  Integrations/python/deephaven/doc/io/deephaven/db/v2/sources/chunk/page/Page/WithDefaultsForRepeatingValues.json
  Integrations/python/deephaven/doc/io/deephaven/db/v2/sources/regioned/ColumnRegionByte/Constant.json
  Integrations/python/deephaven/doc/io/deephaven/db/v2/sources/regioned/ColumnRegionChar/Constant.json
  Integrations/python/deephaven/doc/io/deephaven/db/v2/sources/regioned/ColumnRegionDouble/Constant.json
  Integrations/python/deephaven/doc/io/deephaven/db/v2/sources/regioned/ColumnRegionFloat/Constant.json
  Integrations/python/deephaven/doc/io/deephaven/db/v2/sources/regioned/ColumnRegionInt/Constant.json
  Integrations/python/deephaven/doc/io/deephaven/db/v2/sources/regioned/ColumnRegionLong/Constant.json
  Integrations/python/deephaven/doc/io/deephaven/db/v2/sources/regioned/ColumnRegionObject.json
  Integrations/python/deephaven/doc/io/deephaven/db/v2/sources/regioned/ColumnRegionObject/Constant.json
  Integrations/python/deephaven/doc/io/deephaven/db/v2/sources/regioned/ColumnRegionObject/Null.json
  Integrations/python/deephaven/doc/io/deephaven/db/v2/sources/regioned/ColumnRegionShort/Constant.json
Labels: DocumentationNeeded, core, parquet

#887 Ensure that bindTableToVariable manages live references
  grpc-api/src/main/java/io/deephaven/grpc_api/console/ConsoleServiceGrpcImpl.java
Labels: NoDocumentationNeeded, grpc

#889 Make ScriptSession a LivenessScope instead of LivenessNode
  DB/src/main/java/io/deephaven/db/util/AbstractScriptSession.java
  DB/src/main/java/io/deephaven/db/util/ScriptSession.java
  grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java
  grpc-api/src/main/java/io/deephaven/grpc_api/util/GrpcUtil.java
Labels: NoDocumentationNeeded, clean up, grpc

#899 Move parquet compression tests to an out of band test class. Fixes #898
  DB/src/test/java/io/deephaven/db/tables/utils/TestParquetTools.java
  DB/src/test/java/io/deephaven/db/v2/parquet/ParquetTableReadWriteTest.java
Labels: NoDocumentationNeeded

#908 ExportTicketResolver: resolves ticket before computing flight info
  grpc-api/src/flightTest/java/io/deephaven/grpc_api/flight/FlightMessageRoundTripTest.java
  grpc-api/src/main/java/io/deephaven/grpc_api/arrow/FlightServiceGrpcImpl.java
  grpc-api/src/main/java/io/deephaven/grpc_api/console/ScopeTicketResolver.java
  grpc-api/src/main/java/io/deephaven/grpc_api/session/ExportTicketResolver.java
  grpc-api/src/main/java/io/deephaven/grpc_api/session/SessionState.java
  grpc-api/src/main/java/io/deephaven/grpc_api/session/TicketResolver.java
  grpc-api/src/main/java/io/deephaven/grpc_api/session/TicketRouter.java
Labels: NoDocumentationNeeded, arrow, bug, grpc

#913 Fix QueryTableTest.testSnapshot to follow new initial snapshot semant…
  DB/src/test/java/io/deephaven/db/v2/QueryTableTest.java
Labels: NoDocumentationNeeded

#863 Expose IdeConnection and getConsoleTypes to the client
  grpc-api/src/main/java/io/deephaven/grpc_api/console/ConsoleServiceGrpcImpl.java
  open-api/shared-ide/src/main/java/io/deephaven/web/shared/ide/ConsoleAddress.java
  web/WebDevelopersGuide.md
  web/client-api/src/main/java/io/deephaven/web/client/api/JsWorkspaceData.java
  web/client-api/src/main/java/io/deephaven/web/client/api/QueryConnectable.java
  web/client-api/src/main/java/io/deephaven/web/public/console.html
  web/client-api/src/main/java/io/deephaven/web/public/index.html
  web/client-api/src/main/java/io/deephaven/web/public/simple.html
  web/client-api/src/main/java/io/deephaven/web/public/table_filter.html
  web/client-api/src/main/java/io/deephaven/web/public/table_sort.html
  web/client-api/src/main/java/io/deephaven/web/public/table_viewport.html
  web/client-ide/src/main/java/io/deephaven/ide/client/IdeClient.java
  web/client-ide/src/main/java/io/deephaven/ide/client/IdeConnection.java
  web/client-ide/src/main/java/io/deephaven/ide/client/IdeConnectionOptions.java
Labels: DocumentationNeeded, jsapi

#920 Adding missing doc dir to git.
  Integrations/python/deephaven/doc/io/deephaven/db/v2/select/Formula/FillContext.json
  Integrations/python/deephaven/doc/io/deephaven/db/v2/select/Formula/GetContext.json
Labels: NoDocumentationNeeded

#919 Fix inconsistencies in argument order in ParquetTools.readTable and writeTable. Fixes #918
  BenchmarkSupport/src/main/java/io/deephaven/benchmarking/runner/BenchmarkRunner.java
  BenchmarkSupport/src/main/java/io/deephaven/benchmarking/runner/TableBenchmarkState.java
  DB/src/main/java/io/deephaven/db/tables/utils/ParquetTools.java
  DB/src/test/java/io/deephaven/db/tables/TestAppendableColumn.java
  DB/src/test/java/io/deephaven/db/tables/utils/TestParquetTools.java
  DB/src/test/java/io/deephaven/db/v2/QueryTableNaturalJoinTest.java
  DB/src/test/java/io/deephaven/db/v2/QueryTableSortTest.java
  DB/src/test/java/io/deephaven/db/v2/QueryTableTest.java
  DB/src/test/java/io/deephaven/db/v2/TestAggregatedSelect.java
  DB/src/test/java/io/deephaven/db/v2/TestCodecColumns.java
  DB/src/test/java/io/deephaven/db/v2/TestMapCodecColumns.java
  DB/src/test/java/io/deephaven/db/v2/locations/impl/TestGroupingProviders.java
  DB/src/test/java/io/deephaven/db/v2/parquet/ParquetTableReadWriteTest.java
  Generators/src/main/java/io/deephaven/pythonPreambles/ParquetToolsPreamble.txt
  Integrations/python/deephaven/ParquetTools/__init__.py
Labels: NoDocumentationNeeded

#915 Remove non-class level usages of out of band test annotation. Fixes #914
  DB/src/test/java/io/deephaven/db/tables/QueryTableHugeSortTest.java
  DB/src/test/java/io/deephaven/db/tables/utils/TestTableTools.java
  DB/src/test/java/io/deephaven/db/tables/utils/TestWindowCheck.java
  DB/src/test/java/io/deephaven/db/util/datastructures/intrusive/TestIntrusiveSoftLRU.java
  DB/src/test/java/io/deephaven/db/v2/QueryTableAggregationTest.java
  DB/src/test/java/io/deephaven/db/v2/QueryTableAjTest.java
  DB/src/test/java/io/deephaven/db/v2/QueryTableCrossJoinSmallRightBitsTest.java
  DB/src/test/java/io/deephaven/db/v2/QueryTableCrossJoinTestBase.java
  DB/src/test/java/io/deephaven/db/v2/QueryTableJoinTest.java
  DB/src/test/java/io/deephaven/db/v2/QueryTableNaturalJoinTest.java
  DB/src/test/java/io/deephaven/db/v2/QueryTableSelectUpdateTest.java
  DB/src/test/java/io/deephaven/db/v2/QueryTableSliceTest.java
  DB/src/test/java/io/deephaven/db/v2/QueryTableSortTest.java
  DB/src/test/java/io/deephaven/db/v2/QueryTableStaticNaturalJoinRandomTest.java
  DB/src/test/java/io/deephaven/db/v2/QueryTableTest.java
  DB/src/test/java/io/deephaven/db/v2/QueryTableTreeTest.java
  DB/src/test/java/io/deephaven/db/v2/QueryTableWhereTest.java
  DB/src/test/java/io/deephaven/db/v2/QueryTableWouldMatchTest.java
  DB/src/test/java/io/deephaven/db/v2/TableMapTest.java
  DB/src/test/java/io/deephaven/db/v2/TestByExternal.java
  DB/src/test/java/io/deephaven/db/v2/TestComboBy.java
  DB/src/test/java/io/deephaven/db/v2/TestConcurrentInstantiation.java
  DB/src/test/java/io/deephaven/db/v2/TestSelectOverheadLimiter.java
  DB/src/test/java/io/deephaven/db/v2/TestSort.java
  DB/src/test/java/io/deephaven/db/v2/TestSymbolTableCombiner.java
  DB/src/test/java/io/deephaven/db/v2/TickSuppressorTest.java
  DB/src/test/java/io/deephaven/db/v2/by/TestSortedFirstOrLastByFactory.java
  DB/src/test/java/io/deephaven/db/v2/select/TestFormulaColumn.java
  DB/src/test/java/io/deephaven/db/v2/sources/regioned/TestChunkedRegionedOperations.java
  DB/src/test/java/io/deephaven/db/v2/utils/RedirectionIndexLockFreeTest.java
  DB/src/test/java/io/deephaven/db/v2/utils/SortedIndexTestBase.java
  DB/src/test/java/io/deephaven/db/v2/utils/TestIncrementalReleaseFilter.java
  DB/src/test/java/io/deephaven/db/v2/utils/TestSyncTableFilter.java
  DB/src/test/java/io/deephaven/db/v2/utils/rsp/RspBitmapTest.java
  DB/src/test/java/io/deephaven/db/v2/utils/sortedranges/SortedRangesTest.java
  DB/src/test/java/io/deephaven/util/calendar/StaticCalendarMethodsTest.java
Labels: NoDocumentationNeeded

#891 fixes #880 listFlights is now compatible with proper FlightClient
  DB/src/main/java/io/deephaven/db/util/GroovyDeephavenSession.java
  grpc-api-client/src/main/java/io/deephaven/grpc_api_client/table/BarrageSourcedTable.java
  grpc-api/src/flightTest/java/io/deephaven/grpc_api/flight/FlightMessageRoundTripTest.java
  grpc-api/src/main/java/io/deephaven/grpc_api/arrow/FlightServiceGrpcImpl.java
  grpc-api/src/main/java/io/deephaven/grpc_api/barrage/BarrageStreamGenerator.java
  grpc-api/src/main/java/io/deephaven/grpc_api/barrage/util/BarrageSchemaUtil.java
  grpc-api/src/main/java/io/deephaven/grpc_api/session/TicketRouter.java
  grpc-api/src/main/java/io/deephaven/grpc_api/table/TableServiceGrpcImpl.java
Labels: NoDocumentationNeeded, arrow, bug

#921 Chunk column source.
  DB/src/main/java/io/deephaven/db/v2/sources/BooleanAsByteColumnSource.java
  DB/src/main/java/io/deephaven/db/v2/sources/ByteAsBooleanColumnSource.java
  DB/src/main/java/io/deephaven/db/v2/sources/DatetimeAsLongColumnSource.java
  DB/src/main/java/io/deephaven/db/v2/sources/LongAsDateTimeColumnSource.java
  DB/src/main/java/io/deephaven/db/v2/sources/ReplicateSourcesAndChunks.java
  DB/src/main/java/io/deephaven/db/v2/sources/chunkcolumnsource/ByteChunkColumnSource.java
  DB/src/main/java/io/deephaven/db/v2/sources/chunkcolumnsource/CharChunkColumnSource.java
  DB/src/main/java/io/deephaven/db/v2/sources/chunkcolumnsource/ChunkColumnSource.java
  DB/src/main/java/io/deephaven/db/v2/sources/chunkcolumnsource/DoubleChunkColumnSource.java
  DB/src/main/java/io/deephaven/db/v2/sources/chunkcolumnsource/FloatChunkColumnSource.java
  DB/src/main/java/io/deephaven/db/v2/sources/chunkcolumnsource/IntChunkColumnSource.java
  DB/src/main/java/io/deephaven/db/v2/sources/chunkcolumnsource/LongChunkColumnSource.java
  DB/src/main/java/io/deephaven/db/v2/sources/chunkcolumnsource/ObjectChunkColumnSource.java
  DB/src/main/java/io/deephaven/db/v2/sources/chunkcolumnsource/ShortChunkColumnSource.java
  DB/src/test/java/io/deephaven/db/v2/sources/chunkcolumnsource/TestChunkColumnSource.java
Labels: NoDocumentationNeeded, kafka

#917 WIP: stream table interfaces for discussion
  DB/src/main/java/io/deephaven/stream/StreamConsumer.java
  DB/src/main/java/io/deephaven/stream/StreamPublisher.java
  DB/src/main/java/io/deephaven/stream/StreamToTableAdapter.java
Labels: NoDocumentationNeeded, kafka

#928 Split docker-compose in preparation of kafka/redpanda. Reduce version.
  docker-compose-common.yml
  docker-compose.yml
Labels: NoDocumentationNeeded, docker, kafka

#926 Standardize on Arrow's Flight Schema representation
  grpc-api/src/flightTest/java/io/deephaven/grpc_api/flight/FlightMessageRoundTripTest.java
  grpc-api/src/main/java/io/deephaven/grpc_api/barrage/util/BarrageSchemaUtil.java
  grpc-api/src/main/java/io/deephaven/grpc_api/session/TicketRouter.java
  grpc-api/src/main/java/io/deephaven/grpc_api/table/TableServiceGrpcImpl.java
  web/client-api/src/main/java/io/deephaven/web/client/api/barrage/BarrageUtils.java
  web/client-api/src/main/java/io/deephaven/web/client/state/ClientTableState.java
Labels: NoDocumentationNeeded, arrow, barrage, grpc

#922 Add dockerized redpanda; do an initial very simple spike end-to-end
  Generators/Generators.gradle
  Generators/src/main/java/io/deephaven/python/PythonStaticGenerator.java
  Generators/src/main/java/io/deephaven/pythonPreambles/KafkaToolsPreamble.txt
  Integrations/build.gradle
  Integrations/python/deephaven/KafkaTools/__init__.py
  Integrations/python/deephaven/ParquetTools/__init__.py
  Integrations/python/deephaven/doc/io/deephaven/db/tables/utils/ParquetTools.json
  Integrations/python/deephaven/doc/io/deephaven/db/util/GroovyDeephavenSession/RunScripts.json
  Integrations/python/deephaven/doc/io/deephaven/db/v2/sources/ByteAsBooleanColumnSource.json
  Integrations/python/deephaven/doc/io/deephaven/db/v2/sources/LongAsDateTimeColumnSource.json
  Integrations/python/deephaven/doc/io/deephaven/db/v2/sources/chunkcolumnsource/ByteChunkColumnSource.json
  Integrations/python/deephaven/doc/io/deephaven/db/v2/sources/chunkcolumnsource/CharChunkColumnSource.json
  Integrations/python/deephaven/doc/io/deephaven/db/v2/sources/chunkcolumnsource/ChunkColumnSource.json
  Integrations/python/deephaven/doc/io/deephaven/db/v2/sources/chunkcolumnsource/DoubleChunkColumnSource.json
  Integrations/python/deephaven/doc/io/deephaven/db/v2/sources/chunkcolumnsource/FloatChunkColumnSource.json
  Integrations/python/deephaven/doc/io/deephaven/db/v2/sources/chunkcolumnsource/IntChunkColumnSource.json
  Integrations/python/deephaven/doc/io/deephaven/db/v2/sources/chunkcolumnsource/LongChunkColumnSource.json
  Integrations/python/deephaven/doc/io/deephaven/db/v2/sources/chunkcolumnsource/ObjectChunkColumnSource.json
  Integrations/python/deephaven/doc/io/deephaven/db/v2/sources/chunkcolumnsource/ShortChunkColumnSource.json
  Integrations/python/deephaven/doc/io/deephaven/grpc_api/barrage/BarrageStreamGenerator.json
  Integrations/python/deephaven/doc/io/deephaven/grpc_api/barrage/util/BarrageSchemaUtil.json
  Integrations/python/deephaven/doc/io/deephaven/grpc_api/console/ScopeTicketResolver.json
  Integrations/python/deephaven/doc/io/deephaven/grpc_api/session/ExportTicketResolver.json
  Integrations/python/deephaven/doc/io/deephaven/grpc_api/session/SessionState.json
  Integrations/python/deephaven/doc/io/deephaven/grpc_api/session/TicketResolver.json
  Integrations/python/deephaven/doc/io/deephaven/grpc_api/session/TicketRouter.json
  Integrations/python/deephaven/doc/io/deephaven/kafka/KafkaTools.json
  Integrations/python/deephaven/doc/io/deephaven/kafka/ingest/GenericRecordConsumerRecordToTableWriterAdapter.json
  Integrations/python/deephaven/doc/io/deephaven/kafka/ingest/GenericRecordConsumerRecordToTableWriterAdapter/Builder.json
  Integrations/python/deephaven/doc/io/deephaven/kafka/ingest/KafkaIngester.json
  Integrations/python/deephaven/doc/io/deephaven/kafka/ingest/KafkaIngester/PartitionRange.json
  Integrations/python/deephaven/doc/io/deephaven/kafka/ingest/KafkaIngester/PartitionRoundRobin.json
  Integrations/python/deephaven/doc/io/deephaven/kafka/ingest/KafkaIngester/SinglePartition.json
  Integrations/python/deephaven/doc/io/deephaven/kafka/ingest/SimpleConsumerRecordToTableWriterAdapter.json
  Integrations/python/deephaven/doc/io/deephaven/stream/StreamConsumer.json
  Integrations/python/deephaven/doc/io/deephaven/stream/StreamPublisher.json
  Integrations/python/deephaven/doc/io/deephaven/stream/StreamToTableAdapter.json
  KafkaIngester/src/main/java/io/deephaven/kafka/KafkaTools.java
  KafkaIngester/src/main/java/io/deephaven/kafka/ingest/GenericRecordConsumerRecordToTableWriterAdapter.java
  KafkaIngester/src/main/java/io/deephaven/kafka/ingest/KafkaIngester.java
  KafkaIngester/src/main/java/io/deephaven/kafka/ingest/SimpleConsumerRecordToTableWriterAdapter.java
  KafkaIngester/src/test/java/io/deephaven/kafka/ingest/TestGenericRecordAdapter.java
  grpc-api/grpc-api.gradle
  redpanda-standalone/.env
  redpanda-standalone/docker-compose.yml
  redpanda/.env
  redpanda/docker-compose.yml
Labels: NoDocumentationNeeded, kafka

#905 Split Join gRPC call into one per type of join
  DB/src/main/java/io/deephaven/db/v2/CrossJoinHelper.java
  grpc-api/src/main/java/io/deephaven/grpc_api/table/TableModule.java
  grpc-api/src/main/java/io/deephaven/grpc_api/table/TableServiceGrpcImpl.java
  grpc-api/src/main/java/io/deephaven/grpc_api/table/ops/AsOfJoinTablesGrpcImpl.java
  grpc-api/src/main/java/io/deephaven/grpc_api/table/ops/JoinTablesGrpcImpl.java
  proto/proto-backplane-grpc/src/main/proto/io/deephaven/proto/table.proto
  web/client-api/src/main/java/io/deephaven/web/client/api/JsTable.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/table_pb/BatchTableRequest.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/table_pb/CrossJoinTablesRequest.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/table_pb/ExactJoinTablesRequest.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/table_pb/LeftJoinTablesRequest.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/table_pb/NaturalJoinTablesRequest.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/table_pb/batchtablerequest/Operation.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/table_pb/batchtablerequest/operation/OpCase.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/table_pb/jointablesrequest/TypeMap.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/table_pb_service/TableService.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/table_pb_service/TableServiceClient.java
Labels: DocumentationNeeded, bug, grpc

#932 Upgrade to junit 4.13.2
  Container/build.gradle
  Internals/build.gradle
  KafkaIngester/KafkaIngester.gradle
  Parquet/Parquet.gradle
  gradle/deephaven-jpy.gradle
  py/jpy/pom.xml
Labels: NoDocumentationNeeded, clean up, security, test

#933 Remove unused python requirements files
  py/py36/specs/jpy-only/requirements.txt
  py/py36/specs/jupyter-notebook-server/requirements.txt
  py/py36/specs/worker-jupyter/requirements.txt
  py/py36/specs/worker-standard/requirements.txt
  py/py37/specs/jpy-only/requirements.txt
  py/py37/specs/jupyter-notebook-server/requirements.txt
  py/py37/specs/worker-jupyter/requirements.txt
  py/py37/specs/worker-standard/requirements.txt
Labels: NoDocumentationNeeded, clean up, security

#930 StreamToTableAdapter implementation and simple unit test.
  DB/src/main/java/io/deephaven/db/tables/Table.java
  DB/src/main/java/io/deephaven/db/v2/sources/ReplicateSourcesAndChunks.java
  DB/src/main/java/io/deephaven/db/v2/sources/SwitchColumnSource.java
  DB/src/main/java/io/deephaven/db/v2/sources/chunkcolumnsource/ByteChunkColumnSource.java
  DB/src/main/java/io/deephaven/db/v2/sources/chunkcolumnsource/CharChunkColumnSource.java
  DB/src/main/java/io/deephaven/db/v2/sources/chunkcolumnsource/ChunkColumnSource.java
  DB/src/main/java/io/deephaven/db/v2/sources/chunkcolumnsource/DoubleChunkColumnSource.java
  DB/src/main/java/io/deephaven/db/v2/sources/chunkcolumnsource/FloatChunkColumnSource.java
  DB/src/main/java/io/deephaven/db/v2/sources/chunkcolumnsource/IntChunkColumnSource.java
  DB/src/main/java/io/deephaven/db/v2/sources/chunkcolumnsource/LongChunkColumnSource.java
  DB/src/main/java/io/deephaven/db/v2/sources/chunkcolumnsource/ObjectChunkColumnSource.java
  DB/src/main/java/io/deephaven/db/v2/sources/chunkcolumnsource/ShortChunkColumnSource.java
  DB/src/main/java/io/deephaven/stream/StreamToTableAdapter.java
  DB/src/test/java/io/deephaven/db/v2/QueryTableTestBase.java
  DB/src/test/java/io/deephaven/db/v2/SimpleShiftAwareListener.java
  DB/src/test/java/io/deephaven/db/v2/sources/chunkcolumnsource/TestChunkColumnSource.java
  DB/src/test/java/io/deephaven/stream/TestStreamToTableAdapter.java
Labels: NoDocumentationNeeded, kafka

#939 Update web UI to version v0.2.1
  web/client-ui/Dockerfile
Labels: NoDocumentationNeeded, web-client-ui

#931 Remove @JsMethod from JsTable and JsTreeTable features that do not currently work.
  web/client-api/src/main/java/io/deephaven/ide/shared/IdeSession.java
  web/client-api/src/main/java/io/deephaven/web/client/api/JsTable.java
Labels: NoDocumentationNeeded, bug

#942 Bump next version to 0.4.0
  .github/workflows/build-ci.yml
  build.gradle
Labels: NoDocumentationNeeded, build
