Repository deephaven/deephaven-core, pull requests merged in 2021-05, with the labels that each got.

#550 Surefire report reference correct sha
  .github/workflows/publish-check-ci.yml
  .github/workflows/publish-long-check-ci.yml
Labels: build

#569 Search in more directories for XML reports
  .github/workflows/publish-check-ci.yml
  .github/workflows/publish-long-check-ci.yml
Labels: build

#584 Fix racy TestKeyedArrayBackedMutableTable behavior, improve LTM unit test messaging, eliminate deprecated LTM methods
  DB/src/main/java/io/deephaven/db/tables/live/LiveTableMonitor.java
  DB/src/main/java/io/deephaven/db/v2/utils/BaseArrayBackedMutableTable.java
  DB/src/test/java/io/deephaven/db/v2/utils/TestKeyedArrayBackedMutableTable.java
Labels: bug, core

#557 cherry-picked the fix from Deephaven Enterprise, fixes #553
  DB/src/main/java/io/deephaven/db/tables/lang/DBLanguageParser.java
Labels: bug, query engine

#596 Remove deephaven/web and grpc-api docker-compose buildability, partial #516
  build.gradle
  docker-compose.yml
Labels: build, docker

#597 #171 / #556 Clean up property files and eliminate many sources of logging in unit tests
  Configuration/build.gradle
  Configuration/src/main/resources/lib-tests.prop
  Configuration/src/test/java/io/deephaven/configuration/TestConfiguration.java
  Configuration/src/test/resources/resources/lib-tests.prop
  DB-test/src/test/java/io/deephaven/db/v2/select/TestConditionFilter.java
  DB-test/src/test/java/io/deephaven/db/v2/select/TestNumbaFormula.java
  DB/groovy/core/deephaven_core_utils.groovy
  DB/src/main/java/io/deephaven/db/tables/live/LiveTableMonitor.java
  DB/src/main/java/io/deephaven/db/util/scripts/ScriptRepository.java
  DB/src/main/java/io/deephaven/process/ProcessInfoConfig.java
  DB/src/test/java/io/deephaven/db/tables/utils/TestTableTools.java
  DB/src/test/java/io/deephaven/db/v2/IndexGroupingTest.java
  DB/src/test/java/io/deephaven/db/v2/QueryFactory.java
  DB/src/test/java/io/deephaven/db/v2/QueryTableTest.java
  DB/src/test/java/io/deephaven/db/v2/QueryTableTestBase.java
  DB/src/test/java/io/deephaven/db/v2/TestByExternal.java
  DB/src/test/java/io/deephaven/db/v2/TestComboBy.java
  DB/src/test/java/io/deephaven/db/v2/TestSort.java
  DB/src/test/java/io/deephaven/db/v2/TestTotalsTable.java
  DB/src/test/java/io/deephaven/db/v2/TstUtils.java
  DB/src/test/java/io/deephaven/db/v2/by/TestSortedFirstOrLastByFactory.java
  DB/src/test/java/io/deephaven/db/v2/select/TestFormulaColumn.java
  Integrations/python/deephaven/start_jvm.py
  Net/build.gradle
  Research/java/com/illumon/examples/DataTypeExamples.java
  Stats/build.gradle
  configs/dh-defaults.prop
  configs/grpc-api.prop
  test-configs/dh-tests.prop
  test-configs/routing_service_tests.yml
Labels: clean up, core

#586 Rename project to Deephaven Community Core
  settings.gradle
Labels: clean up

#595 update grpc-proxy. Partial #516.
  .github/workflows/build-ci.yml
  build.gradle
  docker-compose.yml
  grpc-proxy/.dockerignore
  grpc-proxy/Dockerfile
  grpc-proxy/README.md
  grpc-proxy/build.gradle
  grpc-proxy/contents/checksums.txt
  grpc-proxy/contents/docker-entrypoint.sh
  settings.gradle
Labels: build, docker

#593 remove the need to use 'call' on Groovy closures in Query Strings, fixes #577
  DB/src/main/java/io/deephaven/db/tables/lang/DBLanguageParser.java
Labels: feature request

#603 Add license information to public docker images, fixes #518
  build.gradle
  buildSrc/src/main/groovy/io/deephaven/tools/License.groovy
  envoy/Dockerfile
  envoy/LICENSE
  envoy/NOTICE
  envoy/build.gradle
  grpc-api/server/docker/build.gradle
  grpc-proxy/LICENSE
  grpc-proxy/NOTICE
  grpc-proxy/build.gradle
  web/client-ide/client-ide.gradle
  web/client-ide/docker/Dockerfile
Labels: build, docker

#588 Do not set ignoreFailures on tests, fixes #572
  .github/scripts/fail-on-xml-failures.sh
  .github/workflows/check-ci.yml
  .github/workflows/long-check-ci.yml
  Configuration/build.gradle
  Net/build.gradle
  Stats/build.gradle
  build.gradle
  buildSrc/src/main/groovy/TestTools.groovy
Labels: build, test

#613 Publish test reports as CI artifacts, fixes #609
  .github/workflows/check-ci.yml
  .github/workflows/long-check-ci.yml
Labels: ci

#619 Fix context leak in RedirectedColumnSource.RedirectionFillFrom
  DB/src/main/java/io/deephaven/db/v2/sources/RedirectedColumnSource.java
Labels: bug, core

#625 Set ownership of DevRel relevant files
  .github/CODEOWNERS
Labels: community

#616 Speed up long check
  DB/src/test/java/io/deephaven/db/tables/QueryTableHugeSortTest.java
  DB/src/test/java/io/deephaven/db/tables/utils/TestTableTools.java
  DB/src/test/java/io/deephaven/db/util/datastructures/intrusive/TestIntrusiveSoftLRU.java
  DB/src/test/java/io/deephaven/db/v2/IndexGroupingTest.java
  DB/src/test/java/io/deephaven/db/v2/QueryTableAggregationTest.java
  DB/src/test/java/io/deephaven/db/v2/QueryTableAjTest.java
  DB/src/test/java/io/deephaven/db/v2/QueryTableCrossJoinSmallRightBitsTest.java
  DB/src/test/java/io/deephaven/db/v2/QueryTableCrossJoinTest.java
  DB/src/test/java/io/deephaven/db/v2/QueryTableCrossJoinTestBase.java
  DB/src/test/java/io/deephaven/db/v2/QueryTableJoinTest.java
  DB/src/test/java/io/deephaven/db/v2/QueryTableNaturalJoinTest.java
  DB/src/test/java/io/deephaven/db/v2/QueryTableSliceTest.java
  DB/src/test/java/io/deephaven/db/v2/QueryTableSortTest.java
  DB/src/test/java/io/deephaven/db/v2/QueryTableStaticNaturalJoinRandomTest.java
  DB/src/test/java/io/deephaven/db/v2/QueryTableTest.java
  DB/src/test/java/io/deephaven/db/v2/QueryTableTreeTest.java
  DB/src/test/java/io/deephaven/db/v2/QueryTableWhereTest.java
  DB/src/test/java/io/deephaven/db/v2/QueryTableWouldMatchTest.java
  DB/src/test/java/io/deephaven/db/v2/TableMapTest.java
  DB/src/test/java/io/deephaven/db/v2/TestByExternal.java
  DB/src/test/java/io/deephaven/db/v2/TestComboBy.java
  DB/src/test/java/io/deephaven/db/v2/TestConcurrentInstantiation.java
  DB/src/test/java/io/deephaven/db/v2/TestSelectOverheadLimiter.java
  DB/src/test/java/io/deephaven/db/v2/TestSort.java
  DB/src/test/java/io/deephaven/db/v2/TestSymbolTableCombiner.java
  DB/src/test/java/io/deephaven/db/v2/TickSuppressorTest.java
  DB/src/test/java/io/deephaven/db/v2/by/TestSortedFirstOrLastByFactory.java
  DB/src/test/java/io/deephaven/db/v2/parquet/ParquetTableReadWriteTest.java
  DB/src/test/java/io/deephaven/db/v2/select/TestFormulaColumn.java
  DB/src/test/java/io/deephaven/db/v2/sources/regioned/TestChunkedRegionedOperations.java
  DB/src/test/java/io/deephaven/db/v2/utils/CurrentOnlyIndexTest.java
  DB/src/test/java/io/deephaven/db/v2/utils/RedirectionIndexLockFreeTest.java
  DB/src/test/java/io/deephaven/db/v2/utils/SortedIndexTestBase.java
  DB/src/test/java/io/deephaven/db/v2/utils/TestIncrementalReleaseFilter.java
  DB/src/test/java/io/deephaven/db/v2/utils/TestSyncTableFilter.java
  DB/src/test/java/io/deephaven/db/v2/utils/TreeIndexTest.java
  DB/src/test/java/io/deephaven/db/v2/utils/rsp/RspBitmapTest.java
  DB/src/test/java/io/deephaven/db/v2/utils/sortedranges/SortedRangesTest.java
  DB/src/test/java/io/deephaven/util/calendar/StaticCalendarMethodsTest.java
Labels: build, ci

#633 Add the new documentation site to the readme
  README.md
Labels: documentation

#635 Try to tune down logging from SSA and SSM unit tests
  DB/src/test/java/io/deephaven/db/v2/ssa/SsaTestHelpers.java
  DB/src/test/java/io/deephaven/db/v2/ssa/TestByteSegmentedSortedArray.java
  DB/src/test/java/io/deephaven/db/v2/ssa/TestCharSegmentedSortedArray.java
  DB/src/test/java/io/deephaven/db/v2/ssa/TestDoubleSegmentedSortedArray.java
  DB/src/test/java/io/deephaven/db/v2/ssa/TestFloatSegmentedSortedArray.java
  DB/src/test/java/io/deephaven/db/v2/ssa/TestIntSegmentedSortedArray.java
  DB/src/test/java/io/deephaven/db/v2/ssa/TestLongSegmentedSortedArray.java
  DB/src/test/java/io/deephaven/db/v2/ssa/TestObjectSegmentedSortedArray.java
  DB/src/test/java/io/deephaven/db/v2/ssa/TestShortSegmentedSortedArray.java
  DB/src/test/java/io/deephaven/db/v2/ssms/ReplicateSegmentedSortedMultisetTests.java
  DB/src/test/java/io/deephaven/db/v2/ssms/TestByteSegmentedSortedMultiset.java
  DB/src/test/java/io/deephaven/db/v2/ssms/TestCharSegmentedSortedMultiset.java
  DB/src/test/java/io/deephaven/db/v2/ssms/TestDoubleSegmentedSortedMultiset.java
  DB/src/test/java/io/deephaven/db/v2/ssms/TestFloatSegmentedSortedMultiset.java
  DB/src/test/java/io/deephaven/db/v2/ssms/TestIntSegmentedSortedMultiset.java
  DB/src/test/java/io/deephaven/db/v2/ssms/TestLongSegmentedSortedMultiset.java
  DB/src/test/java/io/deephaven/db/v2/ssms/TestObjectSegmentedSortedMultiset.java
  DB/src/test/java/io/deephaven/db/v2/ssms/TestShortSegmentedSortedMultiset.java
Labels: clean up, core

#629 Fix a link formatting bug in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: bug, documentation

#645 Javadoc search
  .github/workflows/docs-ci.yml
  build.gradle
  buildSrc/build.gradle
  buildSrc/settings.gradle
  buildSrc/src/compat/java/io/deephaven/javadoc/IncludeDoclet.java
  gradle.properties
  javadoc/README.md
  javadoc/build.gradle
  javadoc/src/main/java/io/deephaven/javadoc/IncludeDoclet.java
  javadoc/src/main/java/module-info.java
  settings.gradle
Labels: build, ci, documentation

#638 port the numba integration prototype from Enterprise to OSS, fixes feature-523
  DB-test/src/test/java/io/deephaven/db/v2/select/TestConditionFilter.java
  DB-test/src/test/java/io/deephaven/db/v2/select/TestNumbaFormula.java
  DB-test/src/test/java/io/deephaven/python/ASTHelperTest.java
  DB/python/io/deephaven/python/ast_helper.py
  DB/src/main/java/io/deephaven/db/v2/select/AbstractConditionFilter.java
  DB/src/main/java/io/deephaven/db/v2/select/AbstractFormulaColumn.java
  DB/src/main/java/io/deephaven/db/v2/select/ArgumentsBuilder.java
  DB/src/main/java/io/deephaven/db/v2/select/ConditionFilter.java
  DB/src/main/java/io/deephaven/db/v2/select/DbArrayArgumentsBuilder.java
  DB/src/main/java/io/deephaven/db/v2/select/FormulaColumn.java
  DB/src/main/java/io/deephaven/db/v2/select/FormulaKernelTypedBase.java
  DB/src/main/java/io/deephaven/db/v2/select/NumbaCompileTools.java
  DB/src/main/java/io/deephaven/db/v2/select/NumbaFormulaColumn.java
  DB/src/main/java/io/deephaven/db/v2/select/PrimitiveArgumentsBuilder.java
  DB/src/main/java/io/deephaven/db/v2/select/PrimitiveArrayArgumentsBuilder.java
  DB/src/main/java/io/deephaven/db/v2/select/PythonVectorFilter.java
  DB/src/main/java/io/deephaven/db/v2/select/StringArgumentsBuilder.java
  DB/src/main/java/io/deephaven/db/v2/select/python/ArgumentsChunked.java
  DB/src/main/java/io/deephaven/db/v2/select/python/ArgumentsSingular.java
  DB/src/main/java/io/deephaven/db/v2/select/python/ConditionFilterPython.java
  DB/src/main/java/io/deephaven/db/v2/select/python/DeephavenCompatibleFunction.java
  DB/src/main/java/io/deephaven/db/v2/select/python/FillContextPython.java
  DB/src/main/java/io/deephaven/db/v2/select/python/FilterKernelPythonChunkedFunction.java
  DB/src/main/java/io/deephaven/db/v2/select/python/FilterKernelPythonSingularFunction.java
  DB/src/main/java/io/deephaven/db/v2/select/python/FormulaColumnPython.java
  DB/src/main/java/io/deephaven/db/v2/select/python/FormulaKernelPythonChunkedFunction.java
  DB/src/main/java/io/deephaven/db/v2/select/python/FormulaKernelPythonSingularFunction.java
  DB/src/main/java/io/deephaven/db/v2/sources/chunk/BooleanChunk.java
  DB/src/main/java/io/deephaven/db/v2/sources/chunk/ByteChunk.java
  DB/src/main/java/io/deephaven/db/v2/sources/chunk/CharChunk.java
  DB/src/main/java/io/deephaven/db/v2/sources/chunk/Chunk.java
  DB/src/main/java/io/deephaven/db/v2/sources/chunk/DoubleChunk.java
  DB/src/main/java/io/deephaven/db/v2/sources/chunk/FloatChunk.java
  DB/src/main/java/io/deephaven/db/v2/sources/chunk/IntChunk.java
  DB/src/main/java/io/deephaven/db/v2/sources/chunk/LongChunk.java
  DB/src/main/java/io/deephaven/db/v2/sources/chunk/ObjectChunk.java
  DB/src/main/java/io/deephaven/db/v2/sources/chunk/ShortChunk.java
  DB/src/main/java/io/deephaven/python/ASTHelper.java
  DB/src/main/java/io/deephaven/python/ASTHelperSetup.java
  Integrations/python/deephaven/java/__init__.py
  Integrations/python/deephaven/java/integration.py
  Integrations/python/deephaven/java/primitives.py
  Integrations/python/deephaven/numba/__init__.py
  Integrations/python/deephaven/numba/integration.py
  py/jpy/src/main/java/org/jpy/Assignment.java
  py/jpy/src/main/java/org/jpy/PyObject.java
  py/jpy/src/main/java/org/jpy/PyProxyHandler.java
Labels: python

#671 Check documentation labels, fixes #627
  .github/scripts/check-doc-labels.sh
  .github/workflows/label-check-ci.yml
Labels: DocumentationNeeded, ci

#641 Nightly / fix nightly check
  .github/env/Linux/gradle.properties
  .github/workflows/build-ci.yml
  .github/workflows/check-ci.yml
  .github/workflows/docs-ci.yml
  .github/workflows/long-check-ci.yml
  .github/workflows/nightly-benchmarks.yml
  .github/workflows/nightly-check-ci.yml
  ClientSupport/src/main/java/io/deephaven/treetable/AbstractTreeSnapshotImpl.java
  ClientSupport/src/main/java/io/deephaven/treetable/RollupSnapshotImpl.java
  ClientSupport/src/main/java/io/deephaven/treetable/TreeSnapshotQuery.java
  ClientSupport/src/main/java/io/deephaven/treetable/TreeTableSnapshotImpl.java
  ClientSupport/src/test/java/io/deephaven/treetable/TreeSnapshotQueryTest.java
  DB-test/src/test/java/io/deephaven/db/util/TestWorkerPythonEnvironment.java
  DB/DB.gradle
  DB/src/main/java/io/deephaven/db/tables/utils/TableToolsMergeHelper.java
  DB/src/main/java/io/deephaven/db/tables/utils/WindowCheck.java
  DB/src/main/java/io/deephaven/db/v2/AsOfJoinHelper.java
  DB/src/main/java/io/deephaven/db/v2/BaseTable.java
  DB/src/main/java/io/deephaven/db/v2/CrossJoinHelper.java
  DB/src/main/java/io/deephaven/db/v2/MergedListener.java
  DB/src/main/java/io/deephaven/db/v2/NaturalJoinHelper.java
  DB/src/main/java/io/deephaven/db/v2/QueryTable.java
  DB/src/main/java/io/deephaven/db/v2/ReverseLookupListener.java
  DB/src/main/java/io/deephaven/db/v2/ReverseOperation.java
  DB/src/main/java/io/deephaven/db/v2/ShiftAwareSwapListener.java
  DB/src/main/java/io/deephaven/db/v2/SortOperation.java
  DB/src/main/java/io/deephaven/db/v2/SourceTable.java
  DB/src/main/java/io/deephaven/db/v2/SwapListener.java
  DB/src/main/java/io/deephaven/db/v2/SwapListenerBase.java
  DB/src/main/java/io/deephaven/db/v2/TreeTableFilter.java
  DB/src/main/java/io/deephaven/db/v2/WouldMatchOperation.java
  DB/src/main/java/io/deephaven/db/v2/join/BucketedChunkedAjMergedListener.java
  DB/src/main/java/io/deephaven/db/v2/join/ZeroKeyChunkedAjMergedListener.java
  DB/src/main/java/io/deephaven/db/v2/snapshot/SnapshotIncrementalListener.java
  DB/src/main/java/io/deephaven/db/v2/sources/UnionSourceManager.java
  DB/src/main/java/io/deephaven/db/v2/utils/SyncTableFilter.java
  DB/src/test/java/io/deephaven/db/tables/utils/TestWindowCheck.java
  DB/src/test/java/io/deephaven/db/v2/QueryFactory.java
  DB/src/test/java/io/deephaven/db/v2/QueryTableAjTest.java
  DB/src/test/java/io/deephaven/db/v2/QueryTableCrossJoinTestBase.java
  DB/src/test/java/io/deephaven/db/v2/QueryTableNaturalJoinTest.java
  DB/src/test/java/io/deephaven/db/v2/QueryTableStaticNaturalJoinRandomTest.java
  DB/src/test/java/io/deephaven/db/v2/QueryTableTreeTest.java
  DB/src/test/java/io/deephaven/db/v2/SelectOverheadLimiter.java
  DB/src/test/java/io/deephaven/db/v2/TestConcurrentInstantiation.java
  DB/src/test/java/io/deephaven/db/v2/TestSelectOverheadLimiter.java
  DB/src/test/java/io/deephaven/db/v2/fuzzertest.groovy
  Plot/src/test/java/io/deephaven/db/plot/example_plots/plotting_samples.groovy
  gradle.properties
  grpc-api/src/main/java/io/deephaven/grpc_api/table/ExportedTableUpdateListener.java
Labels: NoDocumentationNeeded, build, ci

#678 Remove top level building of deephaven-jpy in CI, is handled implicit…
  .github/workflows/build-ci.yml
Labels: NoDocumentationNeeded, ci, clean up

#679 Remove extraneous workflow action
  .github/workflows/build-ci.yml
  .github/workflows/check-ci.yml
  .github/workflows/long-check-ci.yml
  .github/workflows/workflow-sync.yml
Labels: NoDocumentationNeeded, ci, clean up

#677 Explicitly set 'local-build' tag for docker images
  Generators/Generators.gradle
  Integrations/build.gradle
  buildSrc/src/main/groovy/Docker.groovy
  docker-compose.yml
  envoy/build.gradle
  gradle/deephaven-jpy.gradle
  grpc-api/server/docker/build.gradle
  grpc-api/server/docker/gradle.properties
  grpc-proxy/build.gradle
  proto/proto-backplane-grpc/Dockerfile
  proto/proto-backplane-grpc/build.gradle
  proto/raw-js-openapi/Dockerfile
  proto/raw-js-openapi/build.gradle
  protoc/build.gradle
  py/jpy-integration/build.gradle
  sphinx/docker/Dockerfile
  sphinx/sphinx.gradle
  web/client-ide/client-ide.gradle
  web/client-ide/docker/Dockerfile
  web/client-ui/client-ui.gradle
Labels: NoDocumentationNeeded, build, ci

#683 Update web-client-ui to v0.1.1
  web/client-ui/Dockerfile
Labels: NoDocumentationNeeded

#684 upgrade docker info for release prep
  .github/workflows/build-ci.yml
  envoy/Dockerfile
  grpc-api/server/docker/build.gradle
  grpc-api/server/docker/gradle.properties
  grpc-proxy/Dockerfile
Labels: NoDocumentationNeeded, ci
