Repository deephaven/deephaven-core, pull requests merged in 2022-03, with the labels that each got.

#1973 JS API updated to specify viewport rows/columns when taking snapshots
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/BarrageMessage.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/BarrageStreamReader.java
  java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshotImpl.java
  proto/package-lock.json
  proto/package.json
  proto/proto-backplane-grpc/build.gradle
  server/src/main/java/io/deephaven/server/barrage/BarrageStreamGenerator.java
  web/client-api/src/main/java/io/deephaven/web/client/api/WorkerConnection.java
  web/client-api/src/main/java/io/deephaven/web/client/api/barrage/BarrageUtils.java
  web/client-api/src/main/java/io/deephaven/web/client/api/subscription/TableViewportSubscription.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/barrage/flatbuf/barrage_generated/io/deephaven/barrage/flatbuf/BarrageMessageType.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/barrage/flatbuf/barrage_generated/io/deephaven/barrage/flatbuf/BarragePublicationOptions.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/barrage/flatbuf/barrage_generated/io/deephaven/barrage/flatbuf/BarragePublicationRequest.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/barrage/flatbuf/barrage_generated/io/deephaven/barrage/flatbuf/BarrageSnapshotOptions.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/barrage/flatbuf/barrage_generated/io/deephaven/barrage/flatbuf/BarrageSnapshotRequest.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/barrage/flatbuf/barrage_generated/io/deephaven/barrage/flatbuf/BarrageSubscriptionRequest.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/application_pb/RemovedField.java
Labels: jsapi, barrage, NoDocumentationNeeded

#2056 Update jetty to latest to fix fragmented deflated message bug
  server/jetty/build.gradle
Labels: jsapi, NoDocumentationNeeded, jetty

#2055 Discard listener for incremental release filters to avoid python holding it forever.
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/AutoTuningIncrementalReleaseFilter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/BaseIncrementalReleaseFilter.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/util/TestIncrementalReleaseFilter.java
Labels: query engine, NoDocumentationNeeded

#2048 Drop requirement for Java 8 in buildSrc
  buildSrc/build.gradle
Labels: build, NoDocumentationNeeded

#2059 Bump base images
  docker/registry/nltk-base/gradle.properties
  docker/registry/node/gradle.properties
  docker/registry/python-dev-base/gradle.properties
  docker/registry/python/gradle.properties
  docker/registry/pytorch-base/gradle.properties
  docker/registry/server-base/gradle.properties
  docker/registry/sklearn-base/gradle.properties
  docker/registry/slim-base/gradle.properties
  docker/registry/tensorflow-base/gradle.properties
  docker/server/src/main/server-nltk/requirements.txt
  docker/server/src/main/server-tensorflow/requirements.txt
Labels: NoDocumentationNeeded, version-bump

#2058 Add deephaven2 to sphinx
  sphinx/source/conf.py
  sphinx/sphinx.gradle
Labels: documentation, DocumentationNeeded

#2061 Allow flight integration tests to clean up without warnings
  server/netty/src/test/java/io/deephaven/server/netty/NettyFlightRoundTripTest.java
  server/test/src/main/java/io/deephaven/server/test/FlightMessageRoundTripTest.java
Labels: test, NoDocumentationNeeded

#2065 Debezium perf improvements: better message rate tracking; send to multiple kafka partitions.
  debezium/demo/.env
  debezium/demo/docker-compose.yml
  debezium/docker-compose-debezium-common.yml
  debezium/loadgen/generate_load.py
  debezium/perf/.env
  debezium/perf/docker-compose.yml
  debezium/perf/redpanda/Dockerfile
  debezium/perf/redpanda/redpanda.yaml
Labels: NoDocumentationNeeded

#2064 Fix expiration race condition
  server/src/main/java/io/deephaven/server/session/SessionService.java
Labels: bug, NoDocumentationNeeded

#2067 Migrated debezium perf to process executors; can send 500k msg/s now.
  debezium/loadgen/generate_load.py
  debezium/perf/.env
  debezium/perf/docker-compose.yml
Labels: NoDocumentationNeeded

#2072 Use update instead of updateView in latency tracking view for debezium demo.
  debezium/scripts/demo.py
Labels: NoDocumentationNeeded

#2074 Nightly builds to run on both Java11 and 17
  .github/workflows/nightly-check-ci.yml
Labels: build, NoDocumentationNeeded

#2077 Correct yaml to say "fail-fast" for nightly matrix build
  .github/workflows/nightly-check-ci.yml
Labels: build, NoDocumentationNeeded

#2076 Bump registry images
  docker/registry/node/gradle.properties
  docker/registry/protoc-base/gradle.properties
  docker/registry/python/gradle.properties
Labels: NoDocumentationNeeded, version-bump

#2082 Revert GroovyObject casting
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/FormulaGenerator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/FormulaGeneratorFactory.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/QueryScopeParamTypeUtil.java
  engine/table/src/test/java/io/deephaven/engine/util/scripts/TestGroovyDeephavenSession.java
Labels: NoDocumentationNeeded, groovy

#2066 Change the default Deephaven java client TLS port to 443
  java-client/example-utilities/src/main/java/io/deephaven/client/examples/ConnectOptions.java
  java-client/session/build.gradle
  java-client/session/src/main/java/io/deephaven/client/impl/ChannelHelper.java
  java-client/session/src/main/java/io/deephaven/client/impl/DeephavenTargetNameResolverProviders.java
  java-client/uri/src/main/java/io/deephaven/uri/DeephavenTarget.java
  server/src/main/java/io/deephaven/server/uri/BarrageTableResolver.java
Labels: NoDocumentationNeeded, java-client

#2085 Bump version to 0.11.0
  .github/workflows/build-ci.yml
  buildSrc/src/main/groovy/io.deephaven.common-conventions.gradle
  pyclient/README.md
  pyintegration/deephaven2/__init__.py
  server/jetty/README.md
Labels: NoDocumentationNeeded, version-bump

#2069 Support client fragmentation over Barrage
  Integrations/python/deephaven/doc/io/deephaven/engine/table/impl/select/formula/FillContext.json
  Integrations/python/deephaven/doc/io/deephaven/engine/table/impl/select/formula/GetContext.json
  engine/chunk/src/main/java/io/deephaven/chunk/util/pools/ChunkPoolConstants.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/ByteChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/CharChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/ChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/DoubleChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/FixedWidthChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/FloatChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/IntChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/LongChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/ShortChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/VarBinaryChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/VarListChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/VectorChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/array/ArrayExpansionKernel.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/array/BooleanArrayExpansionKernel.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/array/ByteArrayExpansionKernel.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/array/CharArrayExpansionKernel.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/array/DoubleArrayExpansionKernel.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/array/FloatArrayExpansionKernel.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/array/IntArrayExpansionKernel.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/array/LongArrayExpansionKernel.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/array/ObjectArrayExpansionKernel.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/array/ShortArrayExpansionKernel.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/vector/BooleanVectorExpansionKernel.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/vector/ByteVectorExpansionKernel.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/vector/CharVectorExpansionKernel.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/vector/DoubleVectorExpansionKernel.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/vector/FloatVectorExpansionKernel.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/vector/IntVectorExpansionKernel.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/vector/LongVectorExpansionKernel.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/vector/ObjectVectorExpansionKernel.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/vector/ShortVectorExpansionKernel.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/vector/VectorExpansionKernel.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/BarrageStreamReader.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/StreamReaderOptions.java
  extensions/barrage/src/test/java/io/deephaven/extensions/barrage/chunk/BarrageColumnRoundTripTest.java
  server/src/main/java/io/deephaven/server/arrow/ArrowFlightUtil.java
  server/src/main/java/io/deephaven/server/arrow/ArrowModule.java
  server/src/main/java/io/deephaven/server/arrow/FlightServiceGrpcImpl.java
  server/src/main/java/io/deephaven/server/barrage/BarrageMessageProducer.java
  server/src/main/java/io/deephaven/server/barrage/BarrageStreamGenerator.java
  server/src/test/java/io/deephaven/server/barrage/BarrageMessageRoundTripTest.java
Labels: barrage, NoDocumentationNeeded

#2088 c1 python lists
  demo/web/src/main/notebooks/C. Python/C1 Python lists.md
Labels: demo notebook

#1992 first draft a4 group and aggregate
  demo/web/src/main/notebooks/A. Real-time table ops/A1 Create tables and fake data .md
  demo/web/src/main/notebooks/A. Real-time table ops/A2 Filter and decorate .md
  demo/web/src/main/notebooks/A. Real-time table ops/A3 Do time series and relational joins.md
  demo/web/src/main/notebooks/A. Real-time table ops/A4 Group and aggregate .md
  demo/web/src/main/notebooks/A. Real-time table ops/A5 If-thens and conditions.md
  demo/web/src/main/notebooks/A. Real-time table ops/A6 Time methods.md
Labels: demo notebook

#2096 Correctly close http2-based emulated bidi streams from JS
  web/client-api/src/main/java/io/deephaven/ide/shared/IdeSession.java
  web/client-api/src/main/java/io/deephaven/web/client/api/WorkerConnection.java
  web/client-api/src/main/java/io/deephaven/web/client/api/barrage/stream/BiDiStream.java
  web/client-api/src/main/java/io/deephaven/web/client/api/subscription/TableViewportSubscription.java
Labels: jsapi, grpc, NoDocumentationNeeded

#2092 Update envoy to 1.21.1, and modernize envoy.yaml
  docker/README.md
  docker/registry/envoyproxy/gradle.properties
  envoy/contents/envoy.yaml
Labels: docker, DocumentationNeeded, envoy

#2101 Bump docker images
  docker/registry/nginx-base/gradle.properties
  docker/registry/nltk-base/gradle.properties
  docker/registry/protoc-base/gradle.properties
  docker/registry/python-dev-base/gradle.properties
  docker/registry/pytorch-base/gradle.properties
  docker/registry/server-base/gradle.properties
  docker/registry/sklearn-base/gradle.properties
  docker/registry/slim-base/gradle.properties
  docker/registry/tensorflow-base/gradle.properties
Labels: NoDocumentationNeeded, version-bump

#2099 Provide the means to run the dockerized server under jprofiler if needed.
  debezium/perf/.env
  debezium/perf/docker-compose.yml
  docker-compose-common.yml
  jprofiler-server/Dockerfile
Labels: NoDocumentationNeeded

#2104 Update (commented out, reference only) latency tracking query.
  debezium/scripts/demo.sql
Labels: NoDocumentationNeeded

#2106 Bump deephaven-csv to 0.2.0
  extensions/csv/build.gradle
Labels: NoDocumentationNeeded, version-bump

#2105 jpy vararg leak
  py/jpy/src/main/c/jni/org_jpy_PyLib.c
  py/jpy/src/main/c/jpy_conv.c
  py/jpy/src/main/c/jpy_jmethod.c
  py/jpy/src/main/c/jpy_jobj.c
  py/jpy/src/main/c/jpy_jtype.c
  py/jpy/src/main/c/jpy_module.c
  py/jpy/src/main/c/jpy_module.h
  py/jpy/src/test/python/jpy_exception_test.py
Labels: NoDocumentationNeeded

#2108 Fix pydeephaven version
  pyclient/pydeephaven/__init__.py
  pyclient/setup.py
Labels: NoDocumentationNeeded, version-bump

#2111 Revert "jpy vararg leak"
  py/jpy/src/main/c/jni/org_jpy_PyLib.c
  py/jpy/src/main/c/jpy_conv.c
  py/jpy/src/main/c/jpy_jmethod.c
  py/jpy/src/main/c/jpy_jobj.c
  py/jpy/src/main/c/jpy_jtype.c
  py/jpy/src/main/c/jpy_module.c
  py/jpy/src/main/c/jpy_module.h
  py/jpy/src/test/python/jpy_exception_test.py
Labels: NoDocumentationNeeded

#2109 Add scripts to fully automate debezium/perf testing.
  debezium/demo/docker-compose.yml
  debezium/perf/.gitignore
  debezium/perf/README.md
  debezium/perf/dh_run_demo.sh
  debezium/perf/dh_sample_dt.sh
  debezium/perf/docker-compose.yml
  debezium/perf/mz_run_demo.sh
  debezium/perf/mz_sample_dt.sh
  debezium/perf/pid_from_cmdline.py
  debezium/perf/run_experiment.sh
  debezium/perf/sample_top.py
  debezium/perf/sample_top.sh
  debezium/perf/set_pageviews_per_second.sh
  debezium/perf/start_perf_run.sh
  debezium/perf/stop_all.sh
  debezium/scripts/sample_dt.py
  debezium/scripts/sample_dt.sql
Labels: NoDocumentationNeeded

#2110 Update to latest action versions. Add dependabot for action maintenance.
  .github/dependabot.yml
  .github/workflows/build-ci.yml
  .github/workflows/check-ci.yml
  .github/workflows/docs-ci.yml
  .github/workflows/label-check-ci.yml
  .github/workflows/nightly-benchmarks.yml
  .github/workflows/nightly-check-ci.yml
  .github/workflows/nightly-image-check.yml
  .github/workflows/publish-check-ci.yml
  .github/workflows/publish-ci.yml
  .github/workflows/quick-ci.yml
Labels: ci, NoDocumentationNeeded

#2113 ticking_crypto_milliseconds byte casting
  Integrations/python/deephaven/tutorials/crypto_trades.py
Labels: NoDocumentationNeeded

#2114 Fix publish-check-ci.yml
  .github/workflows/publish-check-ci.yml
Labels: ci, NoDocumentationNeeded

#2115 Improving debezium/demo/README.md.
  debezium/perf/README.md
  debezium/perf/run_experiment.sh
  debezium/perf/sample_top.sh
Labels: NoDocumentationNeeded

#2117 Added standard deviation and standard error of the mean to stats calculated in debezium/perf experiments.
  debezium/perf/README.md
  debezium/perf/run_experiment.sh
  debezium/perf/sample_top.py
Labels: NoDocumentationNeeded

#2122 Bump base images
  docker/registry/alpine/gradle.properties
  docker/registry/nltk-base/gradle.properties
  docker/registry/node/gradle.properties
  docker/registry/protoc-base/gradle.properties
  docker/registry/python-dev-base/gradle.properties
  docker/registry/python/gradle.properties
  docker/registry/pytorch-base/gradle.properties
  docker/registry/server-base/gradle.properties
  docker/registry/sklearn-base/gradle.properties
  docker/registry/slim-base/gradle.properties
  docker/registry/tensorflow-base/gradle.properties
  docker/server/src/main/server-nltk/requirements.txt
  docker/server/src/main/server-pytorch/requirements.txt
  docker/server/src/main/server-sklearn/requirements.txt
  docker/server/src/main/server-tensorflow/requirements.txt
  docker/server/src/main/server/requirements.txt
Labels: NoDocumentationNeeded, version-bump

#2119 Remove an empty duplicate file
  Plot/src/main/resources/groovy/1-performance.groovy
Labels: NoDocumentationNeeded, groovy

#2126 Avoid clock checks for snapshots of static tables
  ClientSupport/src/main/java/io/deephaven/treetable/AbstractTreeSnapshotImpl.java
  ModelFarm/src/main/java/io/deephaven/modelfarm/ModelFarmBase.java
  ModelFarm/src/main/java/io/deephaven/modelfarm/ModelFarmOnDemand.java
  ModelFarm/src/main/java/io/deephaven/modelfarm/RDMModelFarm.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/BaseTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/remote/ConstructSnapshot.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestConcurrentInstantiation.java
  server/src/main/java/io/deephaven/server/barrage/BarrageMessageProducer.java
Labels: core, NoDocumentationNeeded, enhancement

#2107 Pyclient groovy support
  pyclient/pydeephaven/_console_service.py
  pyclient/pydeephaven/session.py
Labels: NoDocumentationNeeded

#2137 Fix Groovy evaluateScript to order variables in declaration order
  engine/table/src/main/java/io/deephaven/engine/util/GroovyDeephavenSession.java
  engine/table/src/main/java/io/deephaven/engine/util/ScriptSession.java
  engine/table/src/test/java/io/deephaven/engine/util/scripts/TestGroovyDeephavenSession.java
Labels: bug, NoDocumentationNeeded, groovy

#2131 Add nested JSON support to KafkaTools.consumeToTable.
  Integrations/python/deephaven/ConsumeKafka.py
  extensions/kafka/src/main/java/io/deephaven/kafka/KafkaTools.java
  extensions/kafka/src/main/java/io/deephaven/kafka/ingest/JsonNodeBooleanFieldCopier.java
  extensions/kafka/src/main/java/io/deephaven/kafka/ingest/JsonNodeByteFieldCopier.java
  extensions/kafka/src/main/java/io/deephaven/kafka/ingest/JsonNodeCharFieldCopier.java
  extensions/kafka/src/main/java/io/deephaven/kafka/ingest/JsonNodeChunkAdapter.java
  extensions/kafka/src/main/java/io/deephaven/kafka/ingest/JsonNodeDateTimeFieldCopier.java
  extensions/kafka/src/main/java/io/deephaven/kafka/ingest/JsonNodeDoubleFieldCopier.java
  extensions/kafka/src/main/java/io/deephaven/kafka/ingest/JsonNodeFloatFieldCopier.java
  extensions/kafka/src/main/java/io/deephaven/kafka/ingest/JsonNodeIntFieldCopier.java
  extensions/kafka/src/main/java/io/deephaven/kafka/ingest/JsonNodeLongFieldCopier.java
  extensions/kafka/src/main/java/io/deephaven/kafka/ingest/JsonNodeShortFieldCopier.java
  extensions/kafka/src/main/java/io/deephaven/kafka/ingest/JsonNodeStringFieldCopier.java
  extensions/kafka/src/main/java/io/deephaven/kafka/ingest/JsonNodeUtil.java
  extensions/kafka/src/test/java/io/deephaven/kafka/KafkaToolsTest.java
  pyintegration/deephaven2/stream/kafka/consumer.py
  redpanda/examples/python/kafka-produce.py
Labels: NoDocumentationNeeded

#2144 Bump base images
  docker/registry/alpine/gradle.properties
  docker/registry/nltk-base/gradle.properties
  docker/registry/protoc-base/gradle.properties
  docker/registry/python-dev-base/gradle.properties
  docker/registry/pytorch-base/gradle.properties
  docker/registry/server-base/gradle.properties
  docker/registry/sklearn-base/gradle.properties
  docker/registry/slim-base/gradle.properties
  docker/registry/tensorflow-base/gradle.properties
  docker/server/src/main/server-nltk/requirements.txt
  docker/server/src/main/server-pytorch/requirements.txt
  docker/server/src/main/server-sklearn/requirements.txt
  docker/server/src/main/server-tensorflow/requirements.txt
  docker/server/src/main/server/requirements.txt
Labels: NoDocumentationNeeded, version-bump

#2145 Fix debezium/perf/sample_top.py being tripped by leading spaces in top output.
  debezium/perf/sample_top.py
Labels: NoDocumentationNeeded

#2013 Add the calendars module
  pyintegration/deephaven2/calendar.py
  pyintegration/deephaven2/time.py
  pyintegration/tests/test_calendar.py
Labels: NoDocumentationNeeded, python-server-side

#2031 Create uri.py to wrap ResolveTools
  Integrations/build.gradle
  pyintegration/deephaven2/_wrapper.py
  pyintegration/deephaven2/_wrapper_abc.py
  pyintegration/deephaven2/column.py
  pyintegration/deephaven2/numpy.py
  pyintegration/deephaven2/replay.py
  pyintegration/deephaven2/server/script_session/__init__.py
  pyintegration/deephaven2/stream/kafka/consumer.py
  pyintegration/deephaven2/stream/kafka/producer.py
  pyintegration/deephaven2/table.py
  pyintegration/deephaven2/table_factory.py
  pyintegration/deephaven2/uri.py
  pyintegration/tests/test_uri.py
Labels: NoDocumentationNeeded, python-server-side

#2149 Fix an import error after module renaming
  pyintegration/deephaven2/calendar.py
Labels: NoDocumentationNeeded, python-server-side

#2141 JS API should treat addedRowsIncluded as potentially updates
  web/client-api/src/main/java/io/deephaven/web/client/api/barrage/stream/BiDiStream.java
  web/client-api/src/main/java/io/deephaven/web/client/api/subscription/ViewportData.java
Labels: jsapi, barrage, NoDocumentationNeeded

#2146 Update object allocation stats so it works, but disabled by default
  Plot/Plot.gradle
  Stats/build.gradle
  Stats/src/main/java/io/deephaven/stats/ObjectAllocationCollector.java
  buildSrc/src/main/groovy/io.deephaven.java-classpath-conventions.gradle
  engine/api/build.gradle
  engine/table/build.gradle
  props/configs/src/main/resources/dh-defaults.prop
Labels: build, NoDocumentationNeeded

#2154 Fix a missing unwrap operation when calling Java
  pyintegration/deephaven2/learn/__init__.py
Labels: NoDocumentationNeeded, python-server-side

#2155 Bump deephaven-csv to 0.3.0
  extensions/csv/build.gradle
  extensions/csv/src/main/java/io/deephaven/csv/CsvTools.java
Labels: NoDocumentationNeeded, csv, version-bump

#2153 Update to web v0.11.4
  web/client-ui/Dockerfile
Labels: feature request, DocumentationNeeded

#2100 Java Client & W2W: increase default inbound message size
  java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshotImpl.java
  java-client/example-utilities/src/main/java/io/deephaven/client/examples/ConnectOptions.java
  server/src/main/java/io/deephaven/server/barrage/BarrageStreamGenerator.java
  server/src/main/java/io/deephaven/server/uri/BarrageTableResolver.java
Labels: barrage, NoDocumentationNeeded, java-client

#2161 Change get/set_default_timezone to static methods
  pyintegration/deephaven2/time.py
Labels: NoDocumentationNeeded

#2091 Fix #2087 bug in SingleRange.ixSubIndexByPosOnNew.
  engine/rowset/src/main/java/io/deephaven/engine/rowset/impl/singlerange/SingleRange.java
  engine/rowset/src/test/java/io/deephaven/engine/rowset/impl/SingleRangeTest.java
Labels: NoDocumentationNeeded
