Repository deephaven/deephaven-core, pull requests merged in 2022-10, with the labels that each got.

#2939 Version bump web v0.19.0
  web/client-ui/Dockerfile
Labels: NoDocumentationNeeded

#2940 Only set storage path to $rootDir/data when run from gradle
  server/jetty-app/build.gradle
Labels: bug, build, NoDocumentationNeeded, jetty

#2847 De-root nginx (and grpc-proxy)
  .github/workflows/build-ci.yml
  containers/groovy-examples/docker-compose.yml
  containers/groovy/docker-compose.yml
  containers/python-examples/NLTK/docker-compose.yml
  containers/python-examples/PyTorch/docker-compose.yml
  containers/python-examples/SciKit-Learn/docker-compose.yml
  containers/python-examples/TensorFlow/docker-compose.yml
  containers/python-examples/base/docker-compose.yml
  containers/python/NLTK/docker-compose.yml
  containers/python/PyTorch/docker-compose.yml
  containers/python/SciKit-Learn/docker-compose.yml
  containers/python/TensorFlow/docker-compose.yml
  containers/python/base/docker-compose.yml
  docker-compose-common.yml
  docker/registry/nginx-base/gradle.properties
  docker/registry/nginx-noroot-base/build.gradle
  docker/registry/nginx-noroot-base/gradle.properties
  docker/web/build.gradle
  docker/web/src/main/docker/Dockerfile
  docker/web/src/main/docker/nginx/99-init-notebooks.sh
  docker/web/src/main/docker/nginx/default.conf
  docker/web/src/main/docker/nginx/nginx.conf
  envoy/contents/envoy.yaml
  grpc-proxy/src/main/common/docker-entrypoint.sh
  grpc-proxy/src/main/docker/Dockerfile
  web/client-ide/client-ide.gradle
Labels: NoDocumentationNeeded

#2849 Add all-ai server docker image
  .github/workflows/build-ci.yml
  containers/python-examples/All-AI/README.md
  containers/python-examples/All-AI/docker-compose.yml
  containers/python/All-AI/README.md
  containers/python/All-AI/docker-compose.yml
  docker/registry/all-ai-base/build.gradle
  docker/registry/all-ai-base/gradle.properties
  docker/registry/scripts/update-requirements.sh
  docker/server/build.gradle
  docker/server/src/main/server-all-ai/requirements.txt
Labels: DocumentationNeeded

#2848 Add HealthStatusManager and correctly enterTerminalState
  server/src/main/java/io/deephaven/server/healthcheck/HealthCheckModule.java
  server/src/main/java/io/deephaven/server/runner/DeephavenApiServer.java
  server/src/main/java/io/deephaven/server/runner/DeephavenApiServerModule.java
Labels: NoDocumentationNeeded

#2914 In the cpp client, fix a compilation issue with optional definitions missing from table.cc.
  cpp-client/README.md
  cpp-client/deephaven/client/src/table/table.cc
Labels: NoDocumentationNeeded

#2944 Post release bump from 0.17.0 to 0.18.0
  .github/workflows/build-ci.yml
  buildSrc/src/main/groovy/io.deephaven.common-conventions.gradle
  py/client/README.md
  py/client/pydeephaven/__init__.py
  py/client/setup.py
  py/embedded-server/deephaven_server/__init__.py
  py/server/deephaven/__init__.py
  server/jetty-app/README.md
Labels: NoDocumentationNeeded, version-bump

#2952 Bump commons-io
  buildSrc/src/main/groovy/io.deephaven.java-classpath-conventions.gradle
  replication/util/build.gradle
Labels: security, NoDocumentationNeeded, version-bump

#2951 Bump woodstox dependency
  ParquetHadoop/build.gradle
Labels: security, NoDocumentationNeeded, version-bump

#2954 Bump jdom2
  buildSrc/src/main/groovy/io.deephaven.java-classpath-conventions.gradle
Labels: security, NoDocumentationNeeded, version-bump

#2957 Bump base images
  =0.3.0
  docker/registry/all-ai-base/gradle.properties
  docker/registry/go/gradle.properties
  docker/registry/nltk-base/gradle.properties
  docker/registry/node/gradle.properties
  docker/registry/protoc-base/gradle.properties
  docker/registry/python/gradle.properties
  docker/registry/pytorch-base/gradle.properties
  docker/registry/scripts/update-requirements.sh
  docker/registry/server-base/gradle.properties
  docker/registry/sklearn-base/gradle.properties
  docker/registry/slim-base/gradle.properties
  docker/registry/tensorflow-base/gradle.properties
  docker/server/src/main/server-all-ai-netty/requirements.txt
  docker/server/src/main/server-netty/requirements.txt
  docker/server/src/main/server-nltk-netty/requirements.txt
  docker/server/src/main/server-pytorch-netty/requirements.txt
  docker/server/src/main/server-sklearn-netty/requirements.txt
  docker/server/src/main/server-tensorflow-netty/requirements.txt
Labels: NoDocumentationNeeded, version-bump

#2959 Remove extra file
  =0.3.0
Labels: NoDocumentationNeeded

#2961 Upload error logs on pydoc failure
  .github/workflows/docs-ci.yml
Labels: logging, ci, NoDocumentationNeeded

#2936 Plumb ungroup through TableOperations.
  engine/api/src/main/java/io/deephaven/engine/table/Table.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/HierarchicalTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/TableDefaults.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/UncoalescedTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/partitioned/PartitionedTableProxyImpl.java
  java-client/session/src/main/java/io/deephaven/client/impl/BatchTableRequestBuilder.java
  qst/graphviz/src/main/java/io/deephaven/graphviz/LabelBuilder.java
  qst/src/main/java/io/deephaven/qst/TableAdapterImpl.java
  qst/src/main/java/io/deephaven/qst/table/ParentsVisitor.java
  qst/src/main/java/io/deephaven/qst/table/TableBase.java
  qst/src/main/java/io/deephaven/qst/table/TableSpec.java
  qst/src/main/java/io/deephaven/qst/table/TableVisitorGeneric.java
  qst/src/main/java/io/deephaven/qst/table/UngroupTable.java
  server/src/main/java/io/deephaven/server/table/ops/UngroupGrpcImpl.java
  table-api/src/main/java/io/deephaven/api/TableOperations.java
  table-api/src/main/java/io/deephaven/api/TableOperationsAdapter.java
  table-api/src/main/java/io/deephaven/api/TableOperationsDefaults.java
Labels: table api, NoDocumentationNeeded

#2967 Update to latest groovy 3.0.x, adding support for Java 19
  buildSrc/src/main/groovy/Classpaths.groovy
Labels: NoDocumentationNeeded, groovy

#2973 Update web code studio to v0.19.1
  web/client-ui/Dockerfile
Labels: NoDocumentationNeeded

#2969 Update slf4j and logback dependencies
  buildSrc/src/main/groovy/Classpaths.groovy
Labels: logging, NoDocumentationNeeded, version-bump

#2824 Parse date times correctly when importing CSV
  web/client-api/src/main/java/io/deephaven/web/client/api/i18n/JsTimeZone.java
  web/client-api/src/main/java/io/deephaven/web/client/api/parse/JsDataHandler.java
Labels: bug, NoDocumentationNeeded

#2974 Devroot cleanup
  Configuration/build.gradle
  Configuration/src/main/java/io/deephaven/configuration/Configuration.java
  Configuration/src/test/java/io/deephaven/configuration/TestConfiguration.java
  Generators/Generators.gradle
  Generators/src/main/java/io/deephaven/libs/GroovyStaticImportGenerator.java
  Generators/src/main/java/io/deephaven/plot/util/GenerateAxesPlotMethods.java
  Generators/src/main/java/io/deephaven/plot/util/GenerateFigureImmutable.java
  Generators/src/main/java/io/deephaven/plot/util/GenerateMultiSeries.java
  Generators/src/main/java/io/deephaven/plot/util/GeneratePlottingConvenience.java
  Integrations/build.gradle
  Integrations/src/main/java/io/deephaven/integrations/python/PythonDeephavenSession.java
  Net/build.gradle
  Stats/build.gradle
  Util/src/test/java/io/deephaven/utils/test/PropertySaverTest.java
  buildSrc/src/main/groovy/io.deephaven.java-test-conventions.gradle
  docker/server-jetty/src/main/configure/image-bootstrap.properties
  docker/server-slim/src/main/docker/image-bootstrap.properties
  docker/server/src/main/configure/image-bootstrap.properties
  engine/benchmark/build.gradle
  engine/table/build.gradle
  engine/table/groovy/core/deephaven_core_utils.groovy
  engine/table/groovy/groovy/0-base.groovy
  engine/table/src/main/java/io/deephaven/engine/util/GroovyDeephavenSession.java
  engine/table/src/main/java/io/deephaven/engine/util/ScriptFinder.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/FuzzerTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/util/ModelFileGenerator.java
  engine/table/src/test/resources/io/deephaven/engine/table/impl/fuzzertest.groovy
  extensions/kafka/src/test/java/io/deephaven/kafka/ingest/TestAvroAdapter.java
  extensions/parquet/benchmark/build.gradle
  props/configs/src/main/resources/dh-defaults.prop
  props/test-configs/src/main/resources/dh-tests.prop
  py/embedded-server/deephaven_server/start_jvm.py
  py/embedded-server/java-runtime/src/main/resources/bootstrap.properties
  py/server/test_helper/__init__.py
  python-engine-test/src/test/java/io/deephaven/engine/util/WorkerPythonEnvironment.java
  server/build.gradle
  server/jetty-app/src/main/resources/bootstrap.properties
  server/netty-app/src/main/resources/bootstrap.properties
  server/src/test/java/io/deephaven/server/appmode/ApplicationConfigs.java
  sphinx/source/conf.py
  sphinx/sphinx.gradle
Labels: configuration, clean up, NoDocumentationNeeded

#2970 Bump kafka clients and avro
  extensions/kafka/build.gradle
  redpanda-standalone/docker-compose.yml
Labels: kafka, NoDocumentationNeeded, version-bump

#2971 Auto create docs issues from closed PRs
  .github/workflows/create-docs-issues.js
  .github/workflows/create-docs-issues.yml
Labels: NoDocumentationNeeded

#2981 Update CPP client
  cpp-client/deephaven/client/CMakeLists.txt
  cpp-client/deephaven/client/include/private/deephaven/client/arrowutil/arrow_traits.h
  cpp-client/deephaven/client/include/private/deephaven/client/arrowutil/arrow_util.h
  cpp-client/deephaven/client/include/private/deephaven/client/arrowutil/arrow_value_converter.h
  cpp-client/deephaven/client/include/private/deephaven/client/arrowutil/arrow_visitors.h
  cpp-client/deephaven/client/include/private/deephaven/client/immerutil/abstract_flex_vector.h
  cpp-client/deephaven/client/include/private/deephaven/client/immerutil/immer_column_source.h
  cpp-client/deephaven/client/include/private/deephaven/client/impl/table_handle_impl.h
  cpp-client/deephaven/client/include/private/deephaven/client/subscription/update_processor.h
  cpp-client/deephaven/client/include/public/deephaven/client/table/table.h
  cpp-client/deephaven/client/include/public/deephaven/client/utility/callbacks.h
  cpp-client/deephaven/client/include/public/deephaven/client/utility/cbfuture.h
  cpp-client/deephaven/client/src/arrowutil/arrow_util.cc
  cpp-client/deephaven/client/src/chunk/chunk_filler.cc
  cpp-client/deephaven/client/src/impl/table_handle_impl.cc
  cpp-client/deephaven/client/src/impl/table_handle_manager_impl.cc
  cpp-client/deephaven/client/src/subscription/classic_table_state.cc
  cpp-client/deephaven/client/src/subscription/subscribe_thread.cc
  cpp-client/deephaven/client/src/subscription/update_processor.cc
  cpp-client/deephaven/client/src/table/table.cc
  cpp-client/deephaven/client/src/utility/cbfuture.cc
  cpp-examples/demos/CMakeLists.txt
  cpp-examples/demos/chapter3.cc
Labels: NoDocumentationNeeded

#2962 QueryCompiler: Use SHA-256 hash instead of String#hashCode on class body
  Util/src/main/java/io/deephaven/util/ByteUtils.java
  engine/context/src/main/java/io/deephaven/engine/context/QueryCompiler.java
Labels: bug, query engine, NoDocumentationNeeded

#2942 Barrage: apply redirection mapping is broken into disjoint groups
  Util/src/main/java/io/deephaven/util/datastructures/SizeException.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/ssmcountdistinct/distinct/LongChunkedDistinctOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/ssmcountdistinct/distinct/LongRollupDistinctOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/ssmcountdistinct/unique/LongChunkedUniqueOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/ssmcountdistinct/unique/LongRollupUniqueOperator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/BaseChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/ByteChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/CharChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/ChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/DoubleChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/FloatChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/IntChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/LongChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/ShortChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/VarBinaryChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/VarListChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/VectorChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/BarrageStreamReader.java
  extensions/barrage/src/test/java/io/deephaven/extensions/barrage/chunk/BarrageColumnRoundTripTest.java
  server/src/main/java/io/deephaven/server/arrow/ArrowFlightUtil.java
  server/src/main/java/io/deephaven/server/barrage/BarrageMessageProducer.java
  server/src/main/java/io/deephaven/server/barrage/BarrageStreamGenerator.java
  server/src/test/java/io/deephaven/server/barrage/BarrageMessageRoundTripTest.java
  server/test/src/main/java/io/deephaven/server/test/FlightMessageRoundTripTest.java
Labels: bug, barrage, NoDocumentationNeeded, barrage-wrkr2wrkr

#2865 Refine Authentication apis, clarify deprecation and migration
  authentication/src/main/java/io/deephaven/auth/BasicAuthMarshaller.java
  go/internal/proto/session/session.pb.go
  go/internal/proto/session/session_grpc.pb.go
  proto/proto-backplane-grpc/src/main/proto/deephaven/proto/session.proto
  py/client/pydeephaven/proto/session_pb2.py
  py/client/pydeephaven/proto/session_pb2_grpc.py
  server/src/main/java/io/deephaven/server/arrow/FlightServiceGrpcImpl.java
  server/src/main/java/io/deephaven/server/auth/AuthContextModule.java
  server/src/main/java/io/deephaven/server/session/SessionService.java
  server/src/main/java/io/deephaven/server/session/SessionServiceGrpcImpl.java
  server/src/test/java/io/deephaven/server/appmode/ApplicationServiceGrpcImplTest.java
  server/src/test/java/io/deephaven/server/session/SessionServiceTest.java
  server/test/src/main/java/io/deephaven/server/test/AuthTestModule.java
Labels: grpc, NoDocumentationNeeded, authentication

#2986 Better handling for session expiry
  server/src/main/java/io/deephaven/server/session/SessionService.java
  web/client-api/src/main/java/io/deephaven/web/client/api/WorkerConnection.java
Labels: NoDocumentationNeeded

#2945 Upgrade to Jetty images
  containers/groovy-examples/docker-compose.yml
  containers/groovy/docker-compose.yml
  containers/python-examples-redpanda/docker-compose.yml
  containers/python-examples/All-AI/docker-compose.yml
  containers/python-examples/NLTK/docker-compose.yml
  containers/python-examples/PyTorch/docker-compose.yml
  containers/python-examples/SciKit-Learn/docker-compose.yml
  containers/python-examples/TensorFlow/docker-compose.yml
  containers/python-examples/base/docker-compose.yml
  containers/python/All-AI/docker-compose.yml
  containers/python/NLTK/docker-compose.yml
  containers/python/PyTorch/docker-compose.yml
  containers/python/SciKit-Learn/docker-compose.yml
  containers/python/TensorFlow/docker-compose.yml
  containers/python/base/docker-compose.yml
Labels: docker, DocumentationNeeded, jetty

#2990 Bump base images, includes deephaven-plugin bump to 0.3.0
  docker/registry/all-ai-base/gradle.properties
  docker/registry/go/gradle.properties
  docker/registry/nltk-base/gradle.properties
  docker/registry/protoc-base/gradle.properties
  docker/registry/python/gradle.properties
  docker/registry/pytorch-base/gradle.properties
  docker/registry/server-base/gradle.properties
  docker/registry/sklearn-base/gradle.properties
  docker/registry/tensorflow-base/gradle.properties
  docker/server-jetty/src/main/server-jetty/requirements.txt
  docker/server/src/main/server-all-ai-netty/requirements.txt
  docker/server/src/main/server-netty/requirements.txt
  docker/server/src/main/server-nltk-netty/requirements.txt
  docker/server/src/main/server-pytorch-netty/requirements.txt
  docker/server/src/main/server-sklearn-netty/requirements.txt
  docker/server/src/main/server-tensorflow-netty/requirements.txt
Labels: NoDocumentationNeeded, version-bump

#2991 Update from set-output to environment files for output
  .github/workflows/build-ci.yml
Labels: clean up, ci, NoDocumentationNeeded

#2905 Support automatically using all processors for UGP/OpInitThreadPool
  engine/table/src/main/java/io/deephaven/engine/table/impl/OperationInitializationThreadPool.java
  engine/updategraph/src/main/java/io/deephaven/engine/updategraph/UpdateGraphProcessor.java
Labels: DocumentationNeeded

#3006 Add code to cpp-client/build.gradle to run tests in docker.
  cpp-client/README.md
  cpp-client/build.gradle
  cpp-client/cpp-tests-to-junit.sh
  cpp-client/deephaven/client/build-dependencies.sh
  cpp-client/tests/test_util.cc
  cpp-examples/demos/CMakeLists.txt
  docker/registry/cpp-client-base/build.gradle
  docker/registry/cpp-client-base/gradle.properties
  settings.gradle
Labels: NoDocumentationNeeded

#2887 Update Redpanda version in example files (includes newer version of their CLI)
  containers/python-examples-redpanda/docker-compose.yml
Labels: NoDocumentationNeeded

#3014 Update C++ client documentation
  cpp-client/deephaven/client/CMakeLists.txt
  cpp-client/deephaven/client/include/private/deephaven/client/immerutil/immer_column_source.h
  cpp-client/deephaven/client/include/private/deephaven/client/server/server.h
  cpp-client/deephaven/client/include/public/deephaven/client/chunk/chunk.h
  cpp-client/deephaven/client/include/public/deephaven/client/chunk/chunk_traits.h
  cpp-client/deephaven/client/include/public/deephaven/client/column/array_column_source.h
  cpp-client/deephaven/client/include/public/deephaven/client/column/column_source.h
  cpp-client/deephaven/client/include/public/deephaven/client/container/row_sequence.h
  cpp-client/deephaven/client/include/public/deephaven/client/table/table.h
  cpp-client/deephaven/client/include/public/deephaven/client/ticking.h
  cpp-client/deephaven/client/include/public/deephaven/client/utility/callbacks.h
  cpp-client/deephaven/client/src/chunk/chunk_filler.cc
  cpp-client/deephaven/client/src/container/row_sequence.cc
  cpp-client/deephaven/client/src/impl/table_handle_manager_impl.cc
  cpp-client/deephaven/client/src/server/server.cc
  cpp-client/deephaven/client/src/subscription/classic_table_state.cc
  cpp-client/deephaven/client/src/subscription/immer_table_state.cc
  cpp-client/deephaven/client/src/subscription/index_decoder.cc
  cpp-client/deephaven/client/src/subscription/space_mapper.cc
  cpp-client/deephaven/client/src/table/table.cc
  cpp-client/doc/chunks.rst
  cpp-client/doc/column_sources.rst
  cpp-client/doc/conf.py
  cpp-client/doc/index.rst
  cpp-client/doc/main.rst
  cpp-client/doc/row_sequences.rst
  cpp-client/doc/tablehandles.rst
  cpp-client/doc/ticking.rst
  cpp-examples/demos/CMakeLists.txt
  cpp-examples/doc/getting_started.rst
Labels: NoDocumentationNeeded

#3016 Update caching for web assets
  server/jetty/src/main/java/io/deephaven/server/jetty/JettyBackedGrpcServer.java
Labels: bug, NoDocumentationNeeded

#3017 Update check-ci-results path to include all build/test-results
  .github/workflows/check-ci.yml
  .github/workflows/nightly-check-ci.yml
Labels: ci, NoDocumentationNeeded

#3025 Add /engine/function to codeowners.
  .github/CODEOWNERS
Labels: NoDocumentationNeeded

#3023 Query library ifelse support for vector conditions and scalar true and false conditions and percentile bug fix
  engine/function/src/templates/Basic.ftl
  engine/function/src/templates/Numeric.ftl
  engine/function/src/templates/TestBasic.ftl
  engine/function/src/templates/TestNumeric.ftl
  engine/table/src/main/java/io/deephaven/libs/GroovyStaticImports.java
Labels: DocumentationNeeded, enhancement

#3028 Make ugp auto locking mode the default
  py/server/deephaven/ugp.py
Labels: python, DocumentationNeeded, python-server-side

#3030 Bump deephaven-csv to 0.8.0
  extensions/csv/build.gradle
Labels: NoDocumentationNeeded, csv, version-bump

#3033 C++ client: minor documentation changes
  cpp-client/deephaven/client/include/public/deephaven/client/chunk/chunk_maker.h
  cpp-client/doc/chunks.rst
  cpp-client/doc/column_sources.rst
  cpp-client/doc/conf.py
  cpp-client/doc/index.rst
  cpp-client/doc/main.rst
  cpp-client/doc/ticking.rst
Labels: NoDocumentationNeeded

#3027 Remove -netty and related image publishing
  .github/workflows/build-ci.yml
Labels: clean up, docker, DocumentationNeeded, release blocker

#3032 Disable autocomplete for python sessions
  server/src/main/java/io/deephaven/server/console/ConsoleServiceGrpcImpl.java
Labels: py-autocomplete, NoDocumentationNeeded

#3009 Remove explicit JVM flags around GC
  containers/groovy-examples/docker-compose.yml
  containers/groovy/docker-compose.yml
  containers/python-examples-redpanda/docker-compose.yml
  containers/python-examples/All-AI/docker-compose.yml
  containers/python-examples/NLTK/docker-compose.yml
  containers/python-examples/PyTorch/docker-compose.yml
  containers/python-examples/SciKit-Learn/docker-compose.yml
  containers/python-examples/TensorFlow/docker-compose.yml
  containers/python-examples/base/docker-compose.yml
  containers/python/All-AI/docker-compose.yml
  containers/python/NLTK/docker-compose.yml
  containers/python/PyTorch/docker-compose.yml
  containers/python/SciKit-Learn/docker-compose.yml
  containers/python/TensorFlow/docker-compose.yml
  containers/python/base/docker-compose.yml
  debezium/perf/docker-compose.yml
  docker-compose-common.yml
  docker/server-jetty/src/main/docker/Dockerfile
  docker/server/src/main/docker/Dockerfile
  java-client/barrage-examples/build.gradle
  java-client/flight-examples/build.gradle
  java-client/session-examples/build.gradle
  py/embedded-server/deephaven_server/start_jvm.py
  py/server/test_helper/__init__.py
  server/jetty-app/README.md
  server/jetty-app/build.gradle
  server/netty-app/README.md
  server/netty-app/build.gradle
Labels: configuration, DocumentationNeeded

#3038 Disable weak etags provided by Jetty
  server/jetty/src/main/java/io/deephaven/server/jetty/JettyBackedGrpcServer.java
Labels: web-client-ui, NoDocumentationNeeded, jetty

#3043 Add column and row to ChartDescriptor
  go/internal/proto/console/console.pb.go
  plugin/figure/src/main/java/io/deephaven/figure/FigureWidgetTranslator.java
  proto/proto-backplane-grpc/src/main/proto/deephaven/proto/console.proto
  py/client/pydeephaven/proto/console_pb2.py
  web/client-api/src/main/java/io/deephaven/web/client/api/widget/plot/JsChart.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/console_pb/figuredescriptor/ChartDescriptor.java
Labels: NoDocumentationNeeded

#3039 Clean up non-compliant code in the query library
  engine/function/src/templates/Basic.ftl
  engine/function/src/templates/Numeric.ftl
  engine/function/src/templates/TestBasic.ftl
  engine/function/src/templates/TestNumeric.ftl
  engine/table/src/main/java/io/deephaven/libs/GroovyStaticImports.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestCumMinMax.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestForwardFill.java
Labels: NoDocumentationNeeded

#2979 ConfigService gRPC and JS API
  go/internal/proto/config/config.pb.go
  go/internal/proto/config/config_grpc.pb.go
  props/configs/src/main/resources/dh-defaults.prop
  props/test-configs/src/main/resources/dh-tests.prop
  proto/proto-backplane-grpc/Dockerfile
  proto/proto-backplane-grpc/src/main/proto/deephaven/proto/config.proto
  proto/raw-js-openapi/src/index.js
  py/client/pydeephaven/proto/config_pb2.py
  py/client/pydeephaven/proto/config_pb2_grpc.py
  server/src/main/java/io/deephaven/server/auth/AuthContextModule.java
  server/src/main/java/io/deephaven/server/config/ConfigServiceGrpcImpl.java
  server/src/main/java/io/deephaven/server/config/ConfigServiceModule.java
  server/src/main/java/io/deephaven/server/runner/DeephavenApiServerModule.java
  web/client-api/src/main/java/io/deephaven/web/client/api/CoreClient.java
  web/client-api/src/main/java/io/deephaven/web/client/api/WorkerConnection.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/config_pb/AuthenticationConstantsRequest.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/config_pb/AuthenticationConstantsResponse.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/config_pb/ConfigValue.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/config_pb/ConfigurationConstantsRequest.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/config_pb/ConfigurationConstantsResponse.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/config_pb/configvalue/KindCase.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/config_pb_service/BidirectionalStream.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/config_pb_service/ConfigService.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/config_pb_service/ConfigServiceClient.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/config_pb_service/RequestStream.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/config_pb_service/ResponseStream.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/config_pb_service/UnaryResponse.java
Labels: jsapi, configuration, grpc, NoDocumentationNeeded

#3045 Wrap Jetty's Resource type to force an invalid last-modified header
  server/jetty/src/main/java/io/deephaven/server/jetty/ControlledCacheResource.java
  server/jetty/src/main/java/io/deephaven/server/jetty/DropIfModifiedSinceHeader.java
  server/jetty/src/main/java/io/deephaven/server/jetty/JettyBackedGrpcServer.java
Labels: NoDocumentationNeeded, jetty
