Repository deephaven/deephaven-core, pull requests merged in 2022-02, with the labels that each got.

#1912 Enable more logging to try to catch TestSyncTableFilter.testTableMapRandomized() failure cause
  engine/table/src/test/java/io/deephaven/engine/table/impl/util/TestSyncTableFilter.java
Labels: bug, query engine, NoDocumentationNeeded

#1915 Fixed a datetime@midnight unit test case issue, fixes #1910
  pyintegration/tests/test_time.py
Labels: python, NoDocumentationNeeded

#1888 JSAPI for fetching custom object
  web/client-api/src/main/java/io/deephaven/web/client/api/WorkerConnection.java
  web/client-api/src/main/java/io/deephaven/web/client/api/widget/JsWidget.java
  web/client-api/src/main/java/io/deephaven/web/client/api/widget/JsWidgetExportedObject.java
Labels: jsapi, DocumentationNeeded

#1922 Update README.md
  README.md
Labels: size:1, clean up, NoDocumentationNeeded

#1879 Jakemulf a3 time series joins
  demo/web/src/main/notebooks/A. Real-time table ops/A3 Do time series and relational joins.md
Labels: demo notebook

#1869 filter-and-decorate real-time data ops demo notebook
  demo/web/src/main/notebooks/A. Real-time table ops/A2 Filter and decorate .md
  demo/web/src/main/notebooks/A. Real-time table ops/A3 Do time series and relational joins.md
Labels: demo notebook

#1927 Fix column name remapping in Parquet writing, and add unit tests
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/ParquetTableWriter.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/TypeInfos.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/TestParquetGrouping.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/TestParquetTools.java
Labels: bug, parquet, NoDocumentationNeeded

#1931 Handle 'x == null' differently to avoid ambiguous eq overloads.
  engine/table/src/main/java/io/deephaven/engine/table/impl/lang/QueryLanguageParser.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/lang/TestQueryLanguageParser.java
Labels: NoDocumentationNeeded

#1928 Small improvement to exception message when a natural join finds multiple right hand matches.
  engine/table/src/main/java/io/deephaven/engine/table/impl/IncrementalChunkedNaturalJoinStateManager.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/NaturalJoinHelper.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/RightIncrementalChunkedNaturalJoinStateManager.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableNaturalJoinTest.java
Labels: NoDocumentationNeeded

#1822 draft of data frames notebook
  demo/web/src/main/notebooks/B. Data science, ML, & AI/B1 Pandas and Deephaven.md
  demo/web/src/main/notebooks/C. Python/C2 User-defined Python functions.md
Labels: demo notebook

#1846 fake data generator notebook
  demo/web/src/main/notebooks/A. Real-time table ops/A1 Create tables and fake data .md
  demo/web/src/main/notebooks/A. Real-time table ops/A2 Filter and decorate .md
  demo/web/src/main/notebooks/A. Real-time table ops/A3 Do time series and relational joins.md
Labels: demo notebook

#1933 Add renamed Python AI notebooks
  demo/web/src/main/notebooks/B. Data science, ML, & AI/B3 TensorFlow and Deephaven.md
  demo/web/src/main/notebooks/B. Data science, ML, & AI/B4 PyTorch and Deephaven.md
  demo/web/src/main/notebooks/B. Data science, ML, & AI/B5 SciKit-Learn and Deephaven.md
Labels: NoDocumentationNeeded, demo, demo notebook

#1934 Add NumPy and Numba notebooks
  demo/web/src/main/notebooks/B. Data science, ML, & AI/B2 NumPy and Deephaven.md
  demo/web/src/main/notebooks/C. Python/C3 Numba and Deephaven.md
Labels: NoDocumentationNeeded, demo, demo notebook

#1932 Followup to Paul's comments about debezium-demo over slack.
  debezium-demo/demo.py
Labels: NoDocumentationNeeded

#1936 Bump node and protoc-base registry images
  docker/registry/node/gradle.properties
  docker/registry/protoc-base/gradle.properties
Labels: NoDocumentationNeeded, version-bump

#1937 Cleanup project jars
  build.gradle
  py/py36/build.gradle
  py/py37/build.gradle
  settings.gradle
Labels: clean up, NoDocumentationNeeded

#1943 Allow local runs of test targets to parametrize parallelism and heap size.
  build.gradle
  buildSrc/src/main/groovy/TestTools.groovy
  engine/rowset/build.gradle
  engine/table/build.gradle
  engine/table/src/test/java/io/deephaven/engine/table/impl/FuzzerTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableAggregationTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableAjTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableSortTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/RefreshingTableTestCase.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/SparseSelectTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TableMapTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TstUtils.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/ssa/TestByteSegmentedSortedArray.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/ssa/TestCharSegmentedSortedArray.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/ssa/TestDoubleSegmentedSortedArray.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/ssa/TestFloatSegmentedSortedArray.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/ssa/TestIntSegmentedSortedArray.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/ssa/TestLongSegmentedSortedArray.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/ssa/TestObjectSegmentedSortedArray.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/ssa/TestShortSegmentedSortedArray.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/ssms/TestByteSegmentedSortedMultiset.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/ssms/TestCharSegmentedSortedMultiset.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/ssms/TestDoubleSegmentedSortedMultiset.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/ssms/TestFloatSegmentedSortedMultiset.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/ssms/TestIntSegmentedSortedMultiset.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/ssms/TestLongSegmentedSortedMultiset.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/ssms/TestObjectSegmentedSortedMultiset.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/ssms/TestShortSegmentedSortedMultiset.java
  engine/table/src/test/java/io/deephaven/engine/util/TestWindowCheck.java
  extensions/csv/build.gradle
  extensions/parquet/table/build.gradle
Labels: NoDocumentationNeeded

#1904 Embeddable grid in iframes
  envoy/contents/envoy.yaml
  web/client-ui/Dockerfile
  web/client-ui/client-ui.gradle
Labels: web-client-ui, DocumentationNeeded

#1950 gRPC: Fix licenses for distribution and pull upstream changes
  grpc-java/grpc-servlet-jakarta/LICENSE
  grpc-java/grpc-servlet-jakarta/NOTICE
  grpc-java/grpc-servlet-jakarta/src/main/java/io/grpc/servlet/jakarta/AsyncServletOutputStreamWriter.java
  grpc-java/grpc-servlet-jakarta/src/main/java/io/grpc/servlet/jakarta/GrpcServlet.java
  grpc-java/grpc-servlet-jakarta/src/main/java/io/grpc/servlet/jakarta/ServletAdapter.java
  grpc-java/grpc-servlet-jakarta/src/main/java/io/grpc/servlet/jakarta/ServletServerBuilder.java
  grpc-java/grpc-servlet-jakarta/src/main/java/io/grpc/servlet/jakarta/ServletServerStream.java
  grpc-java/grpc-servlet-jakarta/src/main/java/io/grpc/servlet/jakarta/package-info.java
  grpc-java/grpc-servlet-websocket-jakarta/LICENSE
  grpc-java/grpc-servlet-websocket-jakarta/NOTICE
  server/jetty/src/main/java/io/deephaven/server/jetty/GrpcFilter.java
  server/jetty/src/main/java/io/deephaven/server/jetty/JettyServerModule.java
Labels: grpc, NoDocumentationNeeded

#1920 Use deephaven-csv
  Integrations/python/deephaven/csv.py
  extensions/csv/build.gradle
  extensions/csv/src/main/java/io/deephaven/csv/ColumnNameLegalizer.java
  extensions/csv/src/main/java/io/deephaven/csv/CsvSpecs.java
  extensions/csv/src/main/java/io/deephaven/csv/CsvTools.java
  extensions/csv/src/main/java/io/deephaven/csv/DeephavenTimeZoneParser.java
  extensions/csv/src/main/java/io/deephaven/csv/InferenceSpecs.java
  extensions/csv/src/main/java/io/deephaven/csv/containers/ByteSlice.java
  extensions/csv/src/main/java/io/deephaven/csv/containers/GrowableByteBuffer.java
  extensions/csv/src/main/java/io/deephaven/csv/densestorage/DenseStorageConstants.java
  extensions/csv/src/main/java/io/deephaven/csv/densestorage/DenseStorageReader.java
  extensions/csv/src/main/java/io/deephaven/csv/densestorage/DenseStorageWriter.java
  extensions/csv/src/main/java/io/deephaven/csv/densestorage/QueueNode.java
  extensions/csv/src/main/java/io/deephaven/csv/densestorage/QueueReader.java
  extensions/csv/src/main/java/io/deephaven/csv/densestorage/QueueWriter.java
  extensions/csv/src/main/java/io/deephaven/csv/parsers/BooleanAsByteParser.java
  extensions/csv/src/main/java/io/deephaven/csv/parsers/ByteParser.java
  extensions/csv/src/main/java/io/deephaven/csv/parsers/CharParser.java
  extensions/csv/src/main/java/io/deephaven/csv/parsers/DateTimeAsLongParser.java
  extensions/csv/src/main/java/io/deephaven/csv/parsers/DoubleParser.java
  extensions/csv/src/main/java/io/deephaven/csv/parsers/FloatFastParser.java
  extensions/csv/src/main/java/io/deephaven/csv/parsers/FloatStrictParser.java
  extensions/csv/src/main/java/io/deephaven/csv/parsers/IntParser.java
  extensions/csv/src/main/java/io/deephaven/csv/parsers/IteratorHolder.java
  extensions/csv/src/main/java/io/deephaven/csv/parsers/LongParser.java
  extensions/csv/src/main/java/io/deephaven/csv/parsers/Parser.java
  extensions/csv/src/main/java/io/deephaven/csv/parsers/Parsers.java
  extensions/csv/src/main/java/io/deephaven/csv/parsers/ShortParser.java
  extensions/csv/src/main/java/io/deephaven/csv/parsers/StringParser.java
  extensions/csv/src/main/java/io/deephaven/csv/parsers/TimestampMicrosParser.java
  extensions/csv/src/main/java/io/deephaven/csv/parsers/TimestampMillisParser.java
  extensions/csv/src/main/java/io/deephaven/csv/parsers/TimestampNanosParser.java
  extensions/csv/src/main/java/io/deephaven/csv/parsers/TimestampParserBase.java
  extensions/csv/src/main/java/io/deephaven/csv/parsers/TimestampSecondsParser.java
  extensions/csv/src/main/java/io/deephaven/csv/reading/CellGrabber.java
  extensions/csv/src/main/java/io/deephaven/csv/reading/CsvReader.java
  extensions/csv/src/main/java/io/deephaven/csv/reading/ParseDenseStorageToColumn.java
  extensions/csv/src/main/java/io/deephaven/csv/reading/ParseInputToDenseStorage.java
  extensions/csv/src/main/java/io/deephaven/csv/reading/TypeConverter.java
  extensions/csv/src/main/java/io/deephaven/csv/sinks/Sink.java
  extensions/csv/src/main/java/io/deephaven/csv/sinks/SinkFactory.java
  extensions/csv/src/main/java/io/deephaven/csv/sinks/Source.java
  extensions/csv/src/main/java/io/deephaven/csv/tokenization/RangeTests.java
  extensions/csv/src/main/java/io/deephaven/csv/tokenization/Tokenizer.java
  extensions/csv/src/main/java/io/deephaven/csv/util/CsvReaderException.java
  extensions/csv/src/main/java/io/deephaven/csv/util/Renderer.java
  extensions/csv/src/test/java/io/deephaven/csv/CsvReaderTest.java
  extensions/csv/src/test/java/io/deephaven/csv/CsvTestSuite.java
  extensions/csv/src/test/java/io/deephaven/csv/DeephavenCsvTest.java
  pyintegration/deephaven2/csv.py
Labels: build, DocumentationNeeded, csv

#1954 Bump python base image
  docker/registry/python/gradle.properties
Labels: NoDocumentationNeeded, version-bump

#1962 Use asyncio for python load generation script.
  debezium-demo/loadgen/generate_load.py
Labels: NoDocumentationNeeded

#1966 Fix broken generate_load.py
  debezium-demo/loadgen/docker-entrypoint.sh
  debezium-demo/loadgen/generate_load.py
Labels: NoDocumentationNeeded

#1969 Refactor debezium demo towards a perf oriented version.
  debezium-demo/loadgen/generate_load.py
  debezium/demo/.env
  debezium/demo/README.md
  debezium/demo/demo.py
  debezium/demo/docker-compose.yml
  debezium/docker-compose-debezium-common.yml
  debezium/loadgen/Dockerfile
  debezium/loadgen/docker-entrypoint.sh
  debezium/loadgen/generate_load.py
Labels: NoDocumentationNeeded

#1953 Arrays of tables/tablemaps should be sized correctly
  web/client-api/src/main/java/io/deephaven/web/client/api/widget/plot/JsFigure.java
Labels: jsapi, plotting, NoDocumentationNeeded

#1980 Fix broken default_groovy.env from my last merge.
  default_groovy.env
Labels: NoDocumentationNeeded

#1825 Hand wrapped KafkaTools, ParquetTools, fixes #1643, #1546, #1892
  Integrations/build.gradle
  pyintegration/deephaven2/__init__.py
  pyintegration/deephaven2/_init/bootstrap.py
  pyintegration/deephaven2/_init/start_jvm.py
  pyintegration/deephaven2/_jcompat.py
  pyintegration/deephaven2/_wrapper_abc.py
  pyintegration/deephaven2/column.py
  pyintegration/deephaven2/config/__init__.py
  pyintegration/deephaven2/dtypes.py
  pyintegration/deephaven2/parquet.py
  pyintegration/deephaven2/server/script_session/__init__.py
  pyintegration/deephaven2/stream/__init__.py
  pyintegration/deephaven2/stream/kafka/consumer.py
  pyintegration/deephaven2/stream/kafka/producer.py
  pyintegration/deephaven2/table.py
  pyintegration/setup.py
  pyintegration/tests/test_config.py
  pyintegration/tests/test_dtypes.py
  pyintegration/tests/test_kafka_consumer.py
  pyintegration/tests/test_kafka_producer.py
  pyintegration/tests/test_parquet.py
Labels: python, NoDocumentationNeeded

#1988 git ignore docker-compose.override.yml
  .gitignore
Labels: NoDocumentationNeeded, internal

#1975 Debezium demo improvements: scripts via volume; perf uses pypy
  debezium/demo/.env
  debezium/demo/README.md
  debezium/demo/docker-compose.yml
  debezium/docker-compose-debezium-common.yml
  debezium/loadgen/generate_load.py
  debezium/loadgen/pypy-Dockerfile
  debezium/loadgen/pypy-docker-entrypoint.sh
  debezium/loadgen/python-Dockerfile
  debezium/loadgen/python-docker-entrypoint.sh
  debezium/perf/.env
  debezium/perf/docker-compose.yml
  debezium/scripts/demo.py
  debezium/scripts/demo.sql
Labels: NoDocumentationNeeded

#1990 Enable formatting of BigDecimal and BigInteger in the web console.
  web/client-api/src/main/java/io/deephaven/web/client/api/i18n/JsNumberFormat.java
Labels: DocumentationNeeded

#1993 Bump python requirements
  docker/registry/nltk-base/gradle.properties
  docker/registry/python-dev-base/gradle.properties
  docker/registry/pytorch-base/gradle.properties
  docker/registry/server-base/gradle.properties
  docker/registry/sklearn-base/gradle.properties
  docker/registry/slim-base/gradle.properties
  docker/registry/tensorflow-base/gradle.properties
  docker/server/src/main/server-nltk/requirements.txt
  docker/server/src/main/server-pytorch/requirements.txt
  docker/server/src/main/server-sklearn/requirements.txt
  docker/server/src/main/server-tensorflow/requirements.txt
  docker/server/src/main/server/requirements.txt
Labels: NoDocumentationNeeded, version-bump

#1959 time series notebooks feedback from pete
  demo/web/src/main/notebooks/A. Real-time table ops/A1 Create tables and fake data .md
  demo/web/src/main/notebooks/A. Real-time table ops/A2 Filter and decorate .md
  demo/web/src/main/notebooks/A. Real-time table ops/A3 Do time series and relational joins.md
Labels: demo notebook

#1996 Pandas Notebook Review Edits
  demo/web/src/main/notebooks/B. Data science, ML, & AI/B1 Pandas and Deephaven.md
Labels: demo notebook

#1985 Exclude certain engine methods from Tier 4 compilation
  buildSrc/src/main/groovy/io.deephaven.java-conventions.gradle
  buildSrc/src/main/resources/unixStartScript.txt
Labels: build, DocumentationNeeded

#1987 Update the web UI to v0.9.3
  demo/push.sh
  web/client-ui/gradle.properties
Labels: feature request, web-client-ui, NoDocumentationNeeded

#2001 Update demo layout for web v0.9.3
  demo/web/src/main/layouts/layout-introduction.json
Labels: demo

#2012 Fix an issue with MetricsManager.resetCounters()
  Util/src/main/java/io/deephaven/util/metrics/MetricsManager.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/MetricsManagerTest.java
Labels: NoDocumentationNeeded

#2011 JS Plugins packaging and discovery
  .github/workflows/build-ci.yml
  docker/web-plugin-packager/build.gradle
  docker/web-plugin-packager/src/main/docker/Dockerfile
  docker/web-plugin-packager/src/main/docker/files/pack-plugins.sh
  envoy/contents/envoy.yaml
  settings.gradle
Labels: feature request, DocumentationNeeded

#2021 Add slack to the readme
  README.md
Labels: documentation, NoDocumentationNeeded

#2024 Update web to v0.11.0
  web/client-ui/Dockerfile
Labels: web-client-ui, DocumentationNeeded

#1919 pandas module for Pandas integration, fixes 1826
  pyintegration/deephaven2/column.py
  pyintegration/deephaven2/constants.py
  pyintegration/deephaven2/dherror.py
  pyintegration/deephaven2/dtypes.py
  pyintegration/deephaven2/numpy.py
  pyintegration/deephaven2/pandas.py
  pyintegration/tests/test_column.py
  pyintegration/tests/test_dtypes.py
  pyintegration/tests/test_kafka_consumer.py
  pyintegration/tests/test_numpy.py
  pyintegration/tests/test_pandas.py
  pyintegration/tests/test_time.py
Labels: python, NoDocumentationNeeded

#2028 Remove dead code in debezium demo sciprt.
  debezium/scripts/demo.py
Labels: NoDocumentationNeeded

#2025 Add README for web-plugin-packager
  docker/web-plugin-packager/README.md
Labels: documentation, DocumentationNeeded

#2041 Remove forkEvery test settings
  buildSrc/src/main/groovy/io.deephaven.java-test-conventions.gradle
Labels: build, test, NoDocumentationNeeded

#2040 Bump python image. Update bumpImage task to not clobber project type.
  buildSrc/src/main/groovy/Docker.groovy
  docker/registry/python/gradle.properties
Labels: NoDocumentationNeeded, version-bump

#2042 fix javadocs
  .github/workflows/docs-ci.yml
Labels: documentation, ci, NoDocumentationNeeded

#1949 Hand-wrap TableReplayer/DynamicTableWriter/TableLoggers, fixes #1944
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/DynamicTableWriter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/TableLoggers.java
  engine/table/src/main/java/io/deephaven/engine/util/PythonScopeJpyImpl.java
  py/jpy-integration/src/javaToPython/java/io/deephaven/jpy/integration/MyNumbersBoxed.java
  py/jpy-integration/src/javaToPython/java/io/deephaven/jpy/integration/MyNumbersNumber.java
  py/jpy-integration/src/javaToPython/java/io/deephaven/jpy/integration/MyNumbersObject.java
  py/jpy-integration/src/javaToPython/java/io/deephaven/jpy/integration/MyNumbersPrimitive.java
  py/jpy-integration/src/javaToPython/java/io/deephaven/jpy/integration/PyLibTest.java
  py/jpy-integration/src/javaToPython/python/io/deephaven/jpy/integration/my_numbers.py
  py/jpy/src/main/c/jpy_jtype.c
  py/jpy/src/main/c/jpy_module.c
  py/jpy/src/main/c/jpy_module.h
  pyintegration/deephaven2/__init__.py
  pyintegration/deephaven2/_init/bootstrap.py
  pyintegration/deephaven2/_jcompat.py
  pyintegration/deephaven2/perfmon.py
  pyintegration/deephaven2/replay.py
  pyintegration/deephaven2/table_factory.py
  pyintegration/tests/test_perfmon.py
  pyintegration/tests/test_replay.py
  pyintegration/tests/test_table.py
  pyintegration/tests/test_table_factory.py
  pyintegration/tests/testbase.py
Labels: python, NoDocumentationNeeded

#2045 Removed unused imports from debezium/scripts/demo.py.
  debezium/scripts/demo.py
Labels: NoDocumentationNeeded

#2047 Remove unneccessary downstream dependencies of prepareCompose
  .github/workflows/build-ci.yml
  docker/server/build.gradle
Labels: docker, ci, NoDocumentationNeeded

#1998 Added README.md file to debezium/perf. Improved the one in debezium/demo.
  debezium/demo/README.md
  debezium/perf/README.md
Labels: NoDocumentationNeeded

#2036 Migrate deephaven/__init__.py to v2
  pyintegration/deephaven2/_jcompat.py
  pyintegration/deephaven2/numpy.py
  pyintegration/deephaven2/table_listener.py
  pyintegration/tests/test_jcompat.py
  pyintegration/tests/test_table_listener.py
  pyintegration/tests/testbase.py
Labels: NoDocumentationNeeded, python-server-side

#1968 Implement reverse viewport logic on `BarrageSnapshotRequest` and `BarrageSubscriptionRequest`
  engine/rowset/src/main/java/io/deephaven/engine/rowset/RowSet.java
  engine/rowset/src/main/java/io/deephaven/engine/rowset/impl/WritableRowSetImpl.java
  engine/rowset/src/test/java/io/deephaven/engine/rowset/impl/WritableRowSetImplTest.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/remote/ConstructSnapshot.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/BarrageMessage.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/ShiftInversionHelper.java
  extensions/barrage/build.gradle
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/table/BarrageTable.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/BarrageStreamReader.java
  java-client/barrage-examples/src/main/java/io/deephaven/client/examples/SnapshotExampleBase.java
  java-client/barrage-examples/src/main/java/io/deephaven/client/examples/SubscribeExampleBase.java
  java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshot.java
  java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshotImpl.java
  java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscription.java
  java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java
  server/src/main/java/io/deephaven/server/arrow/ArrowFlightUtil.java
  server/src/main/java/io/deephaven/server/barrage/BarrageMessageProducer.java
  server/src/main/java/io/deephaven/server/barrage/BarrageStreamGenerator.java
  server/src/main/java/io/deephaven/server/uri/BarrageTableResolver.java
  server/src/test/java/io/deephaven/server/barrage/BarrageMessageRoundTripTest.java
Labels: DocumentationNeeded

#1964 Increased compatibility with `Flight` reference implementation of `DoExchange`
  java-client/flight-examples/build.gradle
  java-client/flight-examples/src/main/java/io/deephaven/client/examples/DoExchange.java
  java-client/flight/src/main/java/io/deephaven/client/impl/FlightSession.java
  server/src/main/java/io/deephaven/server/arrow/ArrowFlightUtil.java
  server/test/src/main/java/io/deephaven/server/test/FlightMessageRoundTripTest.java
Labels: NoDocumentationNeeded

#2049 Add BOM
  bom/build.gradle
  bom/gradle.properties
  buildSrc/src/main/groovy/io.deephaven.java-publishing-conventions.gradle
  buildSrc/src/main/groovy/io.deephaven.project.bom-public.gradle
  buildSrc/src/main/groovy/io.deephaven.project.java-external.gradle
  buildSrc/src/main/groovy/io.deephaven.project.java-public.gradle
  buildSrc/src/main/groovy/io.deephaven.project.root.gradle
  buildSrc/src/main/groovy/io/deephaven/project/ProjectType.groovy
  buildSrc/src/main/groovy/io/deephaven/project/util/CombinedJavadoc.groovy
  buildSrc/src/main/groovy/io/deephaven/project/util/JavaDependencies.groovy
  buildSrc/src/main/groovy/io/deephaven/project/util/PublishingConstants.groovy
  combined-javadoc/build.gradle
  settings.gradle
Labels: build, NoDocumentationNeeded

#2022 Add Table agg_all_by() implementation
  pyintegration/deephaven2/agg.py
  pyintegration/deephaven2/csv.py
  pyintegration/deephaven2/table.py
  pyintegration/tests/test_table.py
  pyintegration/tests/test_time.py
Labels: NoDocumentationNeeded, python-server-side

#2029 Clean up deephaven_jpy_init.py
  engine/table/python/core/deephaven_jpy_init.py
Labels: NoDocumentationNeeded, python-server-side
