Repository deephaven/deephaven-core, pull requests merged in 2022-08, with the labels that each got.

#2707 Bump protoc and python base images
  docker/registry/protoc-base/gradle.properties
  docker/registry/python/gradle.properties
Labels: NoDocumentationNeeded, version-bump

#2706 Fixed a race condition in one of the examples
  go/pkg/client/example_input_table_test.go
  go/pkg/client/flight_stub.go
Labels: bug, NoDocumentationNeeded

#2708 Move the "flatbuffers" library to a "private" namespace
  cpp-client/deephaven/client/flatbuf/deephaven/flatbuf/Barrage_generated.h
  cpp-client/deephaven/client/include/private/deephaven/client/subscription/index_decoder.h
  cpp-client/deephaven/client/third_party/flatbuffers/allocator.h
  cpp-client/deephaven/client/third_party/flatbuffers/array.h
  cpp-client/deephaven/client/third_party/flatbuffers/base.h
  cpp-client/deephaven/client/third_party/flatbuffers/buffer.h
  cpp-client/deephaven/client/third_party/flatbuffers/buffer_ref.h
  cpp-client/deephaven/client/third_party/flatbuffers/default_allocator.h
  cpp-client/deephaven/client/third_party/flatbuffers/detached_buffer.h
  cpp-client/deephaven/client/third_party/flatbuffers/flatbuffer_builder.h
  cpp-client/deephaven/client/third_party/flatbuffers/flatbuffers.h
  cpp-client/deephaven/client/third_party/flatbuffers/stl_emulation.h
  cpp-client/deephaven/client/third_party/flatbuffers/string.h
  cpp-client/deephaven/client/third_party/flatbuffers/struct.h
  cpp-client/deephaven/client/third_party/flatbuffers/table.h
  cpp-client/deephaven/client/third_party/flatbuffers/util.h
  cpp-client/deephaven/client/third_party/flatbuffers/vector.h
  cpp-client/deephaven/client/third_party/flatbuffers/vector_downward.h
  cpp-client/deephaven/client/third_party/flatbuffers/verifier.h
Labels: NoDocumentationNeeded

#2710 Bump to next version 0.16.0
  .github/workflows/build-ci.yml
  buildSrc/src/main/groovy/io.deephaven.common-conventions.gradle
  py/client/README.md
  py/client/pydeephaven/__init__.py
  py/client/setup.py
  py/server/deephaven/__init__.py
  server/jetty-app/README.md
Labels: NoDocumentationNeeded, version-bump

#2709 Bump base images
  docker/registry/go/gradle.properties
  docker/registry/nltk-base/gradle.properties
  docker/registry/node/gradle.properties
  docker/registry/protoc-base/gradle.properties
  docker/registry/python-dev-base/gradle.properties
  docker/registry/python/gradle.properties
  docker/registry/pytorch-base/gradle.properties
  docker/registry/server-base/gradle.properties
  docker/registry/sklearn-base/gradle.properties
  docker/registry/slim-base/gradle.properties
  docker/registry/tensorflow-base/gradle.properties
  docker/server/src/main/server-nltk/requirements.txt
  docker/server/src/main/server-pytorch/requirements.txt
  docker/server/src/main/server-sklearn/requirements.txt
  docker/server/src/main/server-tensorflow/requirements.txt
  docker/server/src/main/server/requirements.txt
  go/internal/proto/application/application.pb.go
  go/internal/proto/console/console.pb.go
  go/internal/proto/inputtable/inputtable.pb.go
  go/internal/proto/object/object.pb.go
  go/internal/proto/partitionedtable/partitionedtable.pb.go
  go/internal/proto/session/session.pb.go
  go/internal/proto/table/table.pb.go
  go/internal/proto/ticket/ticket.pb.go
Labels: NoDocumentationNeeded, version-bump

#2712 Update web version to v0.15.4
  web/client-ui/Dockerfile
Labels: bug, NoDocumentationNeeded

#2711 Update web version to v0.15.4
  web/client-ui/Dockerfile
Labels: NoDocumentationNeeded

#2722 Eliminate a race that could cause BaseArrayBackedMutableTable.waitForSequence to hang when there are concurrent updates
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/BaseArrayBackedMutableTable.java
Labels: query engine, NoDocumentationNeeded, input-tables

#2716 Remove explicit field syncing from Python client
  py/client/pydeephaven/session.py
  py/client/tests/test_console.py
  py/client/tests/test_multi_session.py
Labels: NoDocumentationNeeded, python-client

#2729 Bump protoc-base
  docker/registry/protoc-base/gradle.properties
  go/internal/proto/application/application.pb.go
  go/internal/proto/application/application_grpc.pb.go
  go/internal/proto/console/console.pb.go
  go/internal/proto/console/console_grpc.pb.go
  go/internal/proto/inputtable/inputtable_grpc.pb.go
  go/internal/proto/partitionedtable/partitionedtable.pb.go
  go/internal/proto/partitionedtable/partitionedtable_grpc.pb.go
  go/internal/proto/session/session.pb.go
  go/internal/proto/session/session_grpc.pb.go
  go/internal/proto/table/table.pb.go
  go/internal/proto/table/table_grpc.pb.go
  go/internal/proto/ticket/ticket.pb.go
Labels: NoDocumentationNeeded, version-bump

#2728 isNormal was replaced with isFinite
  web/WebDevelopersGuide.md
Labels: NoDocumentationNeeded

#2736 Make jpy related jars java 8 compatible.
  engine/table/src/main/java/io/deephaven/engine/util/jpy/JpyInit.java
  py/jpy-config/gradle.properties
  py/jpy-config/src/main/java/io/deephaven/jpy/JpyConfigFromSubprocess.java
  py/jpy-ext/build.gradle
  py/jpy-ext/gradle.properties
  py/jpy-ext/src/main/java/io/deephaven/jpy/JpyConfigExt.java
Labels: clean up, NoDocumentationNeeded, jpy

#2745 Update web version 0.15.5
  web/client-ui/Dockerfile
Labels: NoDocumentationNeeded

#2747 Don't submit parallel initialization jobs from the parallel initialization thread pool. Don't allow FORCE_PARALLEL_SELECT_AND_UPDATE to break the query engine.
  engine/table/src/main/java/io/deephaven/engine/table/impl/OperationInitializationThreadPool.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/SelectOrUpdateListener.java
Labels: bug, query engine, NoDocumentationNeeded, partitioned_tables

#2422 Make Python local and global scopes available for query formulas
  Integrations/src/main/java/io/deephaven/integrations/python/PythonDeephavenSession.java
  engine/table/src/main/java/io/deephaven/engine/util/AbstractScriptSession.java
  engine/table/src/main/java/io/deephaven/engine/util/PythonScope.java
  engine/table/src/main/java/io/deephaven/engine/util/PythonScopeJpyImpl.java
  py/server/deephaven/table.py
  py/server/tests/test_pandas.py
  py/server/tests/test_partitioned_table.py
  py/server/tests/test_pt_proxy.py
  py/server/tests/test_table.py
  sphinx/source/conf.py
Labels: NoDocumentationNeeded, python-server-side

#2752 Support reading Kafka JSON composite fields as string. Fixes #2751
  extensions/kafka/src/main/java/io/deephaven/kafka/ingest/JsonNodeUtil.java
Labels: NoDocumentationNeeded

#2365 Optimize snapshots for large tables
  engine/table/src/main/java/io/deephaven/engine/table/impl/remote/ConstructSnapshot.java
  extensions/barrage/build.gradle
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/BarrageSnapshotOptions.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/BarrageSubscriptionOptions.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/table/BarrageRedirectedTable.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/table/BarrageStreamTable.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/table/BarrageTable.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/StreamReaderOptions.java
  java-client/barrage-examples/src/main/java/io/deephaven/client/examples/SnapshotExampleBase.java
  java-client/barrage-examples/src/main/java/io/deephaven/client/examples/SubscribeExampleBase.java
  java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshotImpl.java
  java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscription.java
  java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java
  java-client/flight-examples/build.gradle
  java-client/flight-examples/src/main/java/io/deephaven/client/examples/DoExchange.java
  props/configs/src/main/resources/dh-defaults.prop
  props/test-configs/src/main/resources/dh-tests.prop
  proto/package-lock.json
  proto/package.json
  proto/proto-backplane-grpc/build.gradle
  server/src/main/java/io/deephaven/server/arrow/ArrowFlightUtil.java
  server/src/main/java/io/deephaven/server/arrow/FlightServiceGrpcImpl.java
  server/src/main/java/io/deephaven/server/barrage/BarrageMessageProducer.java
  server/src/main/java/io/deephaven/server/barrage/BarrageStreamGenerator.java
  server/src/main/java/io/deephaven/server/uri/BarrageTableResolver.java
  server/src/test/java/io/deephaven/server/barrage/BarrageMessageRoundTripTest.java
  server/src/test/java/io/deephaven/server/barrage/BarrageStreamTableTest.java
  server/test/src/main/java/io/deephaven/server/test/FlightMessageRoundTripTest.java
  web/client-api/src/main/java/io/deephaven/web/client/api/WorkerConnection.java
  web/client-api/src/main/java/io/deephaven/web/client/api/subscription/TableViewportSubscription.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/barrage/flatbuf/barrage_generated/io/deephaven/barrage/flatbuf/BarrageSnapshotOptions.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/barrage/flatbuf/barrage_generated/io/deephaven/barrage/flatbuf/BarrageSubscriptionOptions.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/barrage/flatbuf/barrage_generated/io/deephaven/barrage/flatbuf/BarrageUpdateMetadata.java
Labels: barrage, NoDocumentationNeeded, java-client, barrage-wrkr2wrkr

#2750 Bump node and python registry images
  docker/registry/node/gradle.properties
  docker/registry/python/gradle.properties
Labels: docker, NoDocumentationNeeded, version-bump

#2755 Support reading composite Kafka JSON fields as a JsonNode. Fixes #2754.
  extensions/kafka/src/main/java/io/deephaven/kafka/ingest/JsonNodeChunkAdapter.java
  extensions/kafka/src/main/java/io/deephaven/kafka/ingest/JsonNodeJsonNodeFieldCopier.java
Labels: NoDocumentationNeeded

#2748 Improve `SortedRanges` iterator performance through caching
  engine/rowset/src/main/java/io/deephaven/engine/rowset/impl/sortedranges/SortedRanges.java
  engine/rowset/src/test/java/io/deephaven/engine/rowset/impl/sortedranges/SortedRangesTest.java
Labels: NoDocumentationNeeded

#2757 fix deephaven learn issue with query param scoping
  py/server/deephaven/learn/__init__.py
Labels: bug, NoDocumentationNeeded

#2743 Change Bootstrap.log to System.out instead of System.err
  log-factory/src/main/java/io/deephaven/internal/log/Bootstrap.java
  server/src/main/java/io/deephaven/server/runner/Main.java
Labels: jupyter, NoDocumentationNeeded

#2759 Use Sample for getHeapInfo
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/RuntimeMemory.java
  server/src/main/java/io/deephaven/server/console/ConsoleServiceGrpcImpl.java
Labels: grpc, NoDocumentationNeeded

#2762 Update web to v0.15.6
  web/client-ui/Dockerfile
Labels: NoDocumentationNeeded

#2635 UpdateBy gRPC
  go/internal/proto/table/table.pb.go
  go/internal/proto/table/table_grpc.pb.go
  java-client/flight-dagger/src/test/java/io/deephaven/client/DeephavenFlightSessionTest.java
  java-client/session-dagger/src/test/java/io/deephaven/client/UpdateOrSelectSessionTest.java
  java-client/session/src/main/java/io/deephaven/client/impl/BatchTableRequestBuilder.java
  java-client/session/src/main/java/io/deephaven/client/impl/UpdateByBuilder.java
  java-client/session/src/test/java/io/deephaven/client/impl/UpdateByControlBuilderTest.java
  java-client/session/src/test/java/io/deephaven/client/impl/UpdateByOperationBuilderTest.java
  java-client/session/src/test/java/io/deephaven/client/impl/UpdateBySpecBuilderTest.java
  proto/proto-backplane-grpc/src/main/java/io/deephaven/proto/util/OperationHelper.java
  proto/proto-backplane-grpc/src/main/proto/deephaven/proto/table.proto
  py/client/pydeephaven/proto/table_pb2.py
  py/client/pydeephaven/proto/table_pb2_grpc.py
  server/src/main/java/io/deephaven/server/table/TableModule.java
  server/src/main/java/io/deephaven/server/table/TableServiceGrpcImpl.java
  server/src/main/java/io/deephaven/server/table/ops/UpdateByGrpcImpl.java
  table-api/src/main/java/io/deephaven/api/updateby/BadDataBehavior.java
Labels: grpc, NoDocumentationNeeded, java-client

#2725 Fail incoming grpc connections that don't use http2
  server/jetty/src/main/java/io/deephaven/server/jetty/GrpcFilter.java
Labels: grpc, NoDocumentationNeeded

#2767 Fix DeephavenFlightSessionTest.updateBy; account for split streams
  java-client/flight-dagger/src/test/java/io/deephaven/client/DeephavenFlightSessionTest.java
Labels: bug, test, NoDocumentationNeeded

#2758 Server side application support
  application-mode/src/main/java/io/deephaven/appmode/ApplicationConfig.java
  application-mode/src/main/java/io/deephaven/appmode/ApplicationState.java
  server/src/main/java/io/deephaven/server/appmode/AppMode.java
  server/src/main/java/io/deephaven/server/appmode/ApplicationInjector.java
  server/src/main/java/io/deephaven/server/appmode/ApplicationServiceGrpcImpl.java
  server/src/main/java/io/deephaven/server/runner/DeephavenApiServer.java
  server/src/main/java/io/deephaven/server/runner/DeephavenApiServerModule.java
  server/src/test/java/io/deephaven/server/appmode/ApplicationExampleTest.java
  server/src/test/java/io/deephaven/server/appmode/ApplicationServiceGrpcImplTest.java
Labels: NoDocumentationNeeded, application mode, enhancement

#2770 Correctly check for main module when blding scope
  py/server/deephaven/table.py
  py/server/tests/test_table.py
Labels: NoDocumentationNeeded, python-server-side

#2775 BaseArrayBackedMutableTable#run never reset processedSequence to -1
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/BaseArrayBackedMutableTable.java
Labels: bug, NoDocumentationNeeded, input-tables

#2780 Fix DoPutObserver memory leaks
  engine/updategraph/src/main/java/io/deephaven/engine/liveness/LivenessArtifact.java
  server/src/main/java/io/deephaven/server/arrow/ArrowFlightUtil.java
  server/src/main/java/io/deephaven/server/console/ScopeTicketResolver.java
  server/src/main/java/io/deephaven/server/session/SessionState.java
Labels: bug, grpc, NoDocumentationNeeded, arrow

#2773 Add getObject to IdeConnection instead of just IdeSession
  web/client-api/src/main/java/io/deephaven/ide/shared/IdeSession.java
  web/client-api/src/main/java/io/deephaven/web/client/api/QueryConnectable.java
  web/client-api/src/main/java/io/deephaven/web/client/api/WorkerConnection.java
  web/client-ide/src/main/java/io/deephaven/ide/client/IdeConnection.java
Labels: NoDocumentationNeeded
