Repository deephaven/deephaven-core, pull requests merged in 2022-04, with the labels that each got.

#2174 Fix a missing renaming in the server plugin code
  pyintegration/deephaven/server/plugin/object/__init__.py
Labels: python, NoDocumentationNeeded

#2169 Update index page and add stream/__init__.py
  pyintegration/README.md
  pyintegration/deephaven/stream/kafka/__init__.py
  sphinx/source/index.rst
Labels: NoDocumentationNeeded

#2123 Add SafePoint times to UpdateGraphProcessor cycle times logging.
  Base/src/main/java/io/deephaven/base/MathUtil.java
  IO/src/main/java/io/deephaven/io/log/LogEntry.java
  IO/src/test/java/io/deephaven/io/log/impl/TestLogOutput.java
  buildSrc/src/main/groovy/io.deephaven.java-toolchain-conventions.gradle
  combined-javadoc/build.gradle
  debezium/perf/sample_top.py
  docker/server-slim/build.gradle
  docker/server/build.gradle
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/RuntimeMemory.java
  engine/updategraph/build.gradle
  engine/updategraph/src/main/java/io/deephaven/engine/updategraph/UpdateGraphProcessor.java
  hotspot-impl/build.gradle
  hotspot-impl/gradle.properties
  hotspot-impl/src/main/java/io/deephaven/hotspot/impl/HotSpotImpl.java
  hotspot/build.gradle
  hotspot/gradle.properties
  hotspot/src/main/java/io/deephaven/hotspot/HotSpot.java
  hotspot/src/main/java/io/deephaven/hotspot/JvmIntrospectionContext.java
  server/jetty-app/README.md
  server/jetty-app/build.gradle
  server/jetty-app/gradle.properties
  server/jetty-app/src/main/java/io/deephaven/server/jetty/JettyAppMain.java
  server/jetty/build.gradle
  server/netty-app/README.md
  server/netty-app/build.gradle
  server/netty-app/gradle.properties
  server/netty-app/src/main/java/io/deephaven/server/netty/NettyAppMain.java
  server/netty/README.md
  server/netty/build.gradle
  settings.gradle
Labels: NoDocumentationNeeded

#2178 Accept both single value/multi values in params
  pyintegration/deephaven/table.py
  pyintegration/tests/test_table.py
Labels: python, NoDocumentationNeeded

#2180 Refer to new python package name from redpanda manual tests.
  redpanda-apicurio/examples/python/kafka-produce-avro.py
  redpanda/examples/python/kafka-produce-avro.py
  redpanda/examples/python/kafka-produce.py
Labels: NoDocumentationNeeded

#2179 As a quick short term fix, move debezium/perf to deephaven_legacy. Also fix a bug in column name mapping for CDC.
  debezium/scripts/demo.py
  debezium/scripts/sample_dt.py
  extensions/kafka/src/main/java/io/deephaven/kafka/CdcTools.java
  extensions/kafka/src/main/java/io/deephaven/kafka/KafkaTools.java
Labels: NoDocumentationNeeded

#2187 More efficient contiguous ABC getChunk
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/ArrayBackedColumnSource.java
Labels: query engine, NoDocumentationNeeded

#2158 Don't keep hard references to Table
  engine/table/src/main/java/io/deephaven/stream/StreamToTableAdapter.java
  java-client/session-examples/src/main/java/io/deephaven/client/examples/ExecuteScript.java
  server/src/main/java/io/deephaven/server/appmode/ApplicationServiceGrpcImpl.java
Labels: java, NoDocumentationNeeded, application mode

#2188 Bump docker registry images
  docker/registry/node/gradle.properties
  docker/registry/protoc-base/gradle.properties
  docker/registry/python/gradle.properties
Labels: NoDocumentationNeeded, version-bump

#2186 Add return type annotations for columns()
  pyintegration/deephaven/table.py
Labels: NoDocumentationNeeded, python-server-side

#2157 Don't remove subscriptions while iterating them
  server/src/main/java/io/deephaven/server/appmode/ApplicationServiceGrpcImpl.java
  server/src/test/java/io/deephaven/server/appmode/ApplicationServiceGrpcImplTest.java
Labels: bug, grpc, NoDocumentationNeeded, application mode

#2192 Provide the compact Java exception stack by deflt
  pyintegration/deephaven/dherror.py
Labels: python, NoDocumentationNeeded

#2194 typo fix for countDistinct
  pyintegration/deephaven/agg.py
Labels: NoDocumentationNeeded

#2195 Updated json generation.
  Integrations/python/deephaven_legacy/doc/io/deephaven/base/MathUtil.json
  Integrations/python/deephaven_legacy/doc/io/deephaven/engine/table/impl/select/Formula/FillContext.json
  Integrations/python/deephaven_legacy/doc/io/deephaven/engine/table/impl/select/Formula/GetContext.json
  Integrations/python/deephaven_legacy/doc/io/deephaven/engine/table/impl/util/RuntimeMemory.json
  Integrations/python/deephaven_legacy/doc/io/deephaven/hotspot/HotSpot.json
  Integrations/python/deephaven_legacy/doc/io/deephaven/hotspot/JvmIntrospectionContext.json
  Integrations/python/deephaven_legacy/doc/io/deephaven/io/log/LogEntry.json
  Integrations/python/deephaven_legacy/doc/io/deephaven/kafka/KafkaTools/Produce.json
  Integrations/python/deephaven_legacy/doc/io/deephaven/stream/StreamToTableAdapter.json
Labels: NoDocumentationNeeded

#2164 Update demo notebook folders B and C
  demo/web/src/main/notebooks/B. Data science, ML, & AI/B1 Pandas and Deephaven.md
  demo/web/src/main/notebooks/B. Data science, ML, & AI/B2 NumPy and Deephaven.md
  demo/web/src/main/notebooks/B. Data science, ML, & AI/B3 TensorFlow and Deephaven.md
  demo/web/src/main/notebooks/B. Data science, ML, & AI/B4 PyTorch and Deephaven.md
  demo/web/src/main/notebooks/B. Data science, ML, & AI/B5 SciKit-Learn and Deephaven.md
  demo/web/src/main/notebooks/C. Python/C1 Python lists.md
  demo/web/src/main/notebooks/C. Python/C2 User-defined Python functions.md
  demo/web/src/main/notebooks/C. Python/C3 Numba and Deephaven.md
Labels: python, demo, demo notebook

#2197 Add cdc module in the new Python API
  extensions/kafka/src/main/java/io/deephaven/kafka/CdcTools.java
  pyintegration/deephaven/stream/__init__.py
  pyintegration/deephaven/stream/kafka/cdc.py
  pyintegration/deephaven/stream/kafka/consumer.py
Labels: NoDocumentationNeeded, python-server-side

#2202 Make the redpanda examples work with deephaven v2 on Mac
  redpanda-apicurio/examples/python/kafka-produce-avro.py
  redpanda/examples/post-share-price-schema.sh
  redpanda/examples/python/kafka-produce-avro.py
  redpanda/examples/python/kafka-produce.py
Labels: python, NoDocumentationNeeded

#2201 Remove TensorFlow/PyTorch notebooks. Rename SciKit-Learn
  demo/web/src/main/notebooks/B. Data science, ML, & AI/B3 SciKit-Learn and Deephaven.md
  demo/web/src/main/notebooks/B. Data science, ML, & AI/B3 TensorFlow and Deephaven.md
  demo/web/src/main/notebooks/B. Data science, ML, & AI/B4 PyTorch and Deephaven.md
Labels: NoDocumentationNeeded, demo, update-demo, demo notebook

#2198 Barrage needs a snapshot to sync last notification step and avoid missing first update
  server/src/main/java/io/deephaven/server/barrage/BarrageMessageProducer.java
Labels: bug, barrage, NoDocumentationNeeded

#2208 Fix a bug of not unwrapping param to call Java
  pyintegration/deephaven/stream/kafka/cdc.py
Labels: NoDocumentationNeeded

#2211 Make by param optional in agg_by
  pyintegration/deephaven/table.py
Labels: python, NoDocumentationNeeded

#2209 debexium v2 changes
  debezium/scripts/demo.py
Labels: NoDocumentationNeeded

#2216 Revert "debexium v2 changes (#2209)"
  debezium/scripts/demo.py
Labels: NoDocumentationNeeded

#2219 Rename the methods to delete(),read(), write(), batch_write()
  pyintegration/deephaven/parquet.py
  pyintegration/tests/test_parquet.py
Labels: NoDocumentationNeeded, python-server-side

#2218 Add the meta_table property in Table
  pyintegration/deephaven/table.py
  pyintegration/tests/test_table.py
Labels: NoDocumentationNeeded

#2224 crypto remove legacy
  Integrations/python/deephaven_legacy/tutorials/crypto_trades.py
Labels: NoDocumentationNeeded

#2230 Wrap RegexFilter in deephaven V2
  pyintegration/deephaven/_wrapper.py
  pyintegration/deephaven/filters.py
  pyintegration/deephaven/table.py
  pyintegration/tests/test_filters.py
Labels: NoDocumentationNeeded, python-server-side

#2170 Fix JS API examples after deephaven2 -> deephaven rename
  web/client-api/src/main/java/io/deephaven/web/public/input_table.html
  web/client-api/src/main/java/io/deephaven/web/public/table_basic.html
  web/client-api/src/main/java/io/deephaven/web/public/table_filter.html
  web/client-api/src/main/java/io/deephaven/web/public/table_sort.html
  web/client-api/src/main/java/io/deephaven/web/public/table_viewport.html
Labels: bug, jsapi, NoDocumentationNeeded

#2229 Csv parser v3 wrapper
  Integrations/python/deephaven_legacy/doc/io/deephaven/server/barrage/BarrageMessageProducer/Operation.json
  pyintegration/deephaven/csv.py
Labels: NoDocumentationNeeded

#2235 Bump tensorflow-base
  docker/registry/tensorflow-base/gradle.properties
  docker/server/src/main/server-tensorflow/requirements.txt
Labels: python, docker, NoDocumentationNeeded, version-bump

#2241 Add AsOfMatchRule and add match rule param in aj
  pyintegration/deephaven/__init__.py
  pyintegration/deephaven/constants.py
  pyintegration/deephaven/table.py
  pyintegration/tests/test_table.py
Labels: NoDocumentationNeeded

#2238 Avoid a naturalJoin in the definition of PerformanceQueries.serverState.
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/PerformanceQueries.java
Labels: NoDocumentationNeeded

#2068 Support `growing` viewports for subscriptions
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/table/BarrageTable.java
  java-client/barrage-examples/src/main/java/io/deephaven/client/examples/SubscribeExampleBase.java
  java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshotImpl.java
  java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscription.java
  java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java
  server/src/main/java/io/deephaven/server/barrage/BarrageMessageProducer.java
  server/src/main/java/io/deephaven/server/barrage/BarrageStreamGenerator.java
  web/client-api/src/main/java/io/deephaven/web/client/api/barrage/BarrageUtils.java
Labels: NoDocumentationNeeded

#2204 Add tests for java 18 now that it is available
  .github/workflows/nightly-check-ci.yml
  Configuration/src/test/java/io/deephaven/configuration/TestConfiguration.java
  buildSrc/src/main/groovy/io.deephaven.java-jacoco-conventions.gradle
Labels: ci, NoDocumentationNeeded

#2196 Simplify and relocate deephaven py server library
  Integrations/build.gradle
  Integrations/python/deephaven_legacy/start_jvm.py
  Integrations/python/functional-tests/bootstrap.py
  pyintegration/deephaven/__init__.py
  pyintegration/deephaven/_init/bootstrap.py
  pyintegration/deephaven/_init/start_jvm.py
  pyintegration/integration-tests/null_integers_test.py
  pyintegration/integration-tests/numba_vectorized_column_test.py
  pyintegration/integration-tests/numba_vectorized_filter_test.py
  pyintegration/integration-tests/numbers_from_list_and_func.py
  pyintegration/integration-tests/pylong_conv_test.py
  pyintegration/integration-tests/pyobj_field_access_test.py
  pyintegration/integration-tests/run-tests.sh
  pyintegration/setup.py
  pyintegration/test_helper/__init__.py
  pyintegration/tests/__init__.py
  sphinx/source/conf.py
  sphinx/sphinx.gradle
Labels: NoDocumentationNeeded

#2248 Add missing array dtypes used by DTW
  pyintegration/deephaven/dtypes.py
  pyintegration/tests/test_table_factory.py
Labels: python, NoDocumentationNeeded

#2247 Add format_columns, format_column/row_where
  pyintegration/deephaven/column.py
  pyintegration/deephaven/table.py
  pyintegration/tests/test_table.py
Labels: python, NoDocumentationNeeded

#2251 Fix gradle not telling us docker tasks are failing, and the actual failure
  Integrations/build.gradle
  buildSrc/src/main/groovy/Docker.groovy
  pyintegration/integration-tests/run-tests.sh
Labels: build, NoDocumentationNeeded

#2253 Fix an issue with column names in PerformanceQueries.java; add py integration test for it.
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/PerformanceQueries.java
  pyintegration/integration-tests/numbers_from_list_and_func_test.py
  pyintegration/integration-tests/perfmon_test.py
Labels: NoDocumentationNeeded

#2254 jpy debug refcount
  py/jpy/src/main/c/jni/org_jpy_PyLib.c
  py/jpy/src/main/c/jpy_compat.c
  py/jpy/src/main/c/jpy_jarray.c
  py/jpy/src/main/c/jpy_jfield.c
  py/jpy/src/main/c/jpy_jmethod.c
  py/jpy/src/main/c/jpy_jobj.c
  py/jpy/src/main/c/jpy_jtype.c
  py/jpy/src/main/c/jpy_module.c
  py/jpy/src/main/c/jpy_module.h
Labels: NoDocumentationNeeded, jpy

#2256 Make initializeWithSnapshot/makeDownsampledQueryTable static
  ClientSupport/src/main/java/io/deephaven/clientsupport/plotdownsampling/RunChartDownsample.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/BaseTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/HierarchicalTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/ChunkedOperatorAggregationHelper.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/RegionedColumnSourceWithDictionary.java
  server/src/main/java/io/deephaven/server/table/ExportedTableUpdateListener.java
Labels: clean up, NoDocumentationNeeded

#2264 Bump version to 0.12.0
  .github/workflows/build-ci.yml
  buildSrc/src/main/groovy/io.deephaven.common-conventions.gradle
  pyclient/README.md
  pyclient/pydeephaven/__init__.py
  pyclient/setup.py
  pyintegration/deephaven/__init__.py
  server/jetty-app/README.md
Labels: NoDocumentationNeeded, version-bump

#2236 Update demo notebooks to v2 syntax
  demo/web/src/main/notebooks/00 The Deephaven IDE.md
  demo/web/src/main/notebooks/01 Tables, Updates, and the Engine.md
  demo/web/src/main/notebooks/02 Stream and Batch Together.md
  demo/web/src/main/notebooks/03 Kafka Stream vs Append.md
  demo/web/src/main/notebooks/07 Data Replay.md
  demo/web/src/main/notebooks/08 Table Listeners.md
  demo/web/src/main/notebooks/A. Real-time table ops/A1 Create tables and fake data.md
  demo/web/src/main/notebooks/A. Real-time table ops/A2 Filter and decorate.md
  demo/web/src/main/notebooks/A. Real-time table ops/A3 Do time series and relational joins.md
  demo/web/src/main/notebooks/A. Real-time table ops/A4 Group and aggregate.md
  demo/web/src/main/notebooks/A. Real-time table ops/A5 If-thens and conditions.md
  demo/web/src/main/notebooks/A. Real-time table ops/A6 Time methods.md
  demo/web/src/main/notebooks/B. Data science, ML, & AI/B1 Pandas and Deephaven.md
  demo/web/src/main/notebooks/B. Data science, ML, & AI/B2 NumPy and Deephaven.md
  demo/web/src/main/notebooks/B. Data science, ML, & AI/B3 TensorFlow and Deephaven.md
  demo/web/src/main/notebooks/B. Data science, ML, & AI/B4 PyTorch and Deephaven.md
  demo/web/src/main/notebooks/B. Data science, ML, & AI/B5 SciKit-Learn and Deephaven.md
  demo/web/src/main/notebooks/C. Python/C1 Python lists.md
  demo/web/src/main/notebooks/C. Python/C2 User-defined Python functions.md
  demo/web/src/main/notebooks/C. Python/C3 Numba and Deephaven.md
  demo/web/src/main/notebooks/C. Python/C4 Formulas in Python.md
Labels: demo, update-demo, demo notebook

#2261 Fix setLayoutHints not setting table attribute
  engine/table/src/main/java/io/deephaven/engine/table/impl/BaseTable.java
Labels: bug, NoDocumentationNeeded

#2266 Rename to get rid of wrong/inconsistent naming
  Generators/src/main/java/io/deephaven/pythonPreambles/plotV2.py
  py/server/deephaven/jcompat.py
  py/server/deephaven/parquet.py
  py/server/deephaven/perfmon.py
  py/server/deephaven/plot/figure.py
  py/server/deephaven/stream/kafka/cdc.py
  py/server/deephaven/stream/kafka/consumer.py
  py/server/deephaven/stream/kafka/producer.py
  py/server/deephaven/table.py
  py/server/tests/test_column.py
  py/server/tests/test_jcompat.py
  py/server/tests/test_numpy.py
  py/server/tests/test_pandas.py
  py/server/tests/test_uri.py
Labels: NoDocumentationNeeded, python-server-side

#2268 Permit null log streams, as the code is null safe
  server/src/main/java/io/deephaven/server/log/LogModule.java
  server/src/main/java/io/deephaven/server/runner/DeephavenApiServerComponent.java
Labels: logging, NoDocumentationNeeded

#2269 Only include server app resources in the app
  server/jetty-app/src/main/resources/bootstrap.properties
  server/jetty-app/src/main/resources/logback-debug.xml
  server/jetty-app/src/main/resources/logback-minimal.xml
  server/jetty-app/src/main/resources/logback.xml
  server/netty-app/src/main/resources/bootstrap.properties
  server/netty-app/src/main/resources/logback-debug.xml
  server/netty-app/src/main/resources/logback-minimal.xml
  server/netty-app/src/main/resources/logback.xml
Labels: NoDocumentationNeeded

#2263 Add wrappers for application mode
  py/server/deephaven/appmode.py
  py/server/integration-tests/run-tests.sh
  py/server/test_helper/__init__.py
Labels: NoDocumentationNeeded

#2272 Remove TensorFlow, PyTorch, and Numba notebooks
  demo/web/src/main/notebooks/B. Data science, ML, & AI/B3 TensorFlow and Deephaven.md
  demo/web/src/main/notebooks/B. Data science, ML, & AI/B4 PyTorch and Deephaven.md
  demo/web/src/main/notebooks/C. Python/C3 Numba and Deephaven.md
Labels: demo, update-demo, demo notebook

#2271 Add time_window in the new experimental module
  engine/table/src/main/java/io/deephaven/engine/util/WindowCheck.java
  py/server/deephaven/_jcompat.py
  py/server/deephaven/experimental.py
  py/server/tests/test_experiments.py
  py/server/tests/testbase.py
Labels: NoDocumentationNeeded

#2276 Reduce Java Heap usage for the test
  py/server/tests/test_experiments.py
Labels: NoDocumentationNeeded

#2281 Bump deephaven-csv to 0.4.0
  extensions/csv/build.gradle
Labels: NoDocumentationNeeded, version-bump

#2220 Add a ring table
  Integrations/python/deephaven_legacy/TableTools/__init__.py
  engine/api/src/main/java/io/deephaven/engine/table/ChunkSource.java
  engine/rowset/src/main/java/io/deephaven/engine/rowset/RowSequence.java
  engine/rowset/src/main/java/io/deephaven/engine/rowset/RowSequenceFactory.java
  engine/rowset/src/main/java/io/deephaven/engine/rowset/impl/singlerange/SingleRangeRowSequence.java
  engine/rowset/src/test/java/io/deephaven/engine/rowset/impl/RowSetTstUtils.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/BaseTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/StreamTableTools.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/ArraySourceHelper.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/ring/AbstractRingChunkSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/ring/AddsToRingsListener.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/ring/ByteRingChunkSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/ring/CharacterRingChunkSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/ring/DoubleRingChunkSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/ring/FloatRingChunkSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/ring/IntegerRingChunkSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/ring/LongRingChunkSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/ring/ObjectRingChunkSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/ring/RingColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/ring/RingTableTools.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/ring/ShortRingChunkSource.java
  engine/table/src/main/java/io/deephaven/engine/util/TableTools.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TstUtils.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/sources/ring/DoubleRingChunkSourceTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/sources/ring/RingChunkSourceTestBase.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/sources/ring/RingTableToolsTest.java
  replication/static/build.gradle
  replication/static/src/main/java/io/deephaven/replicators/ReplicateRingChunkSources.java
Labels: query engine, java, NoDocumentationNeeded

#2285 Disable test_metrics_get_counters temporarily
  py/server/tests/test_perfmon.py
Labels: python, NoDocumentationNeeded

#2289 Fix flakiness in test_perfmon.py for test_metrics_get_counters.
  py/server/tests/test_perfmon.py
  py/server/tests/test_plot/test_figure.py
Labels: NoDocumentationNeeded

#2291 Fix reference counting macros
  py/jpy/src/main/c/jpy_module.h
Labels: NoDocumentationNeeded, jpy

#2292 Add proper error handling for PyObject.getPointer() from jpy
  py/jpy/src/main/c/jpy_jtype.c
Labels: NoDocumentationNeeded, jpy

#2294 Revert "Revert "jpy vararg leak (#2105)" (#2111)"
  py/jpy/src/main/c/jni/org_jpy_PyLib.c
  py/jpy/src/main/c/jpy_conv.c
  py/jpy/src/main/c/jpy_jmethod.c
  py/jpy/src/main/c/jpy_jobj.c
  py/jpy/src/main/c/jpy_jtype.c
  py/jpy/src/main/c/jpy_module.c
  py/jpy/src/main/c/jpy_module.h
  py/jpy/src/test/python/jpy_exception_test.py
Labels: NoDocumentationNeeded, jpy

#2297 Call CallBooleanMethod instead of CallIntMethod
  py/jpy/src/main/c/jpy_jobj.c
Labels: NoDocumentationNeeded, jpy

#2231 Barrage Performance Metrics
  engine/api/src/main/java/io/deephaven/engine/table/Table.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/BaseTable.java
  extensions/barrage/build.gradle
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/BarragePerformanceLog.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/BarragePerformanceLogLogger.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/table/BarrageTable.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/BarrageStreamReader.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/BarrageUtil.java
  java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSession.java
  java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshotImpl.java
  java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java
  java-client/session/src/main/java/io/deephaven/client/impl/SessionImpl.java
  server/build.gradle
  server/src/main/java/io/deephaven/server/arrow/ArrowFlightUtil.java
  server/src/main/java/io/deephaven/server/arrow/FlightServiceGrpcImpl.java
  server/src/main/java/io/deephaven/server/barrage/BarrageMessageProducer.java
  server/src/main/java/io/deephaven/server/barrage/BarrageStreamGenerator.java
  server/src/main/java/io/deephaven/server/util/Scheduler.java
  server/src/test/java/io/deephaven/server/barrage/BarrageMessageRoundTripTest.java
  server/src/test/java/io/deephaven/server/util/TestControlledScheduler.java
  server/test/src/main/java/io/deephaven/server/test/FlightMessageRoundTripTest.java
Labels: barrage, NoDocumentationNeeded

#2298 Add the 'cols' param to Table.snapshot() method
  py/server/deephaven/table.py
  py/server/tests/test_table.py
Labels: NoDocumentationNeeded, python-server-side

#2295 Fix naming inconsistency and default param values
  py/server/deephaven/table.py
  py/server/tests/test_table.py
Labels: python, DocumentationNeeded, python-server-side

#2307 BarrageMessageProducer must always flip state
  server/src/main/java/io/deephaven/server/barrage/BarrageMessageProducer.java
Labels: bug, barrage, NoDocumentationNeeded

#2290 ring table for kafka
  extensions/kafka/build.gradle
  extensions/kafka/src/main/java/io/deephaven/kafka/CdcTools.java
  extensions/kafka/src/main/java/io/deephaven/kafka/KafkaTools.java
  py/server/deephaven/stream/kafka/cdc.py
  py/server/deephaven/stream/kafka/consumer.py
Labels: python, kafka, DocumentationNeeded

#2319 Add support for arrays of primitive types and String for Kafka Avro.
  Util/src/main/java/io/deephaven/util/type/ArrayTypeUtils.java
  docker-compose-common.yml
  engine/time/src/main/java/io/deephaven/time/DateTime.java
  engine/vector/src/main/java/io/deephaven/vector/ByteVectorDirect.java
  engine/vector/src/main/java/io/deephaven/vector/CharVectorDirect.java
  engine/vector/src/main/java/io/deephaven/vector/DoubleVectorDirect.java
  engine/vector/src/main/java/io/deephaven/vector/FloatVectorDirect.java
  engine/vector/src/main/java/io/deephaven/vector/IntVectorDirect.java
  engine/vector/src/main/java/io/deephaven/vector/LongVectorDirect.java
  engine/vector/src/main/java/io/deephaven/vector/ObjectVectorDirect.java
  engine/vector/src/main/java/io/deephaven/vector/ShortVectorDirect.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/vector/ByteVectorExpansionKernel.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/vector/CharVectorExpansionKernel.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/vector/DoubleVectorExpansionKernel.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/vector/FloatVectorExpansionKernel.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/vector/IntVectorExpansionKernel.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/vector/LongVectorExpansionKernel.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/vector/ObjectVectorExpansionKernel.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/vector/ShortVectorExpansionKernel.java
  extensions/kafka/src/main/java/io/deephaven/kafka/KafkaSchemaUtils.java
  extensions/kafka/src/main/java/io/deephaven/kafka/KafkaTools.java
  extensions/kafka/src/main/java/io/deephaven/kafka/ingest/FieldCopier.java
  extensions/kafka/src/main/java/io/deephaven/kafka/ingest/GenericRecordArrayFieldCopier.java
  extensions/kafka/src/main/java/io/deephaven/kafka/ingest/GenericRecordChunkAdapter.java
  extensions/kafka/src/main/java/io/deephaven/kafka/ingest/GenericRecordDateTimeArrayFieldCopier.java
  extensions/kafka/src/main/java/io/deephaven/kafka/ingest/JsonNodeChunkAdapter.java
  extensions/kafka/src/main/java/io/deephaven/kafka/ingest/MultiFieldChunkAdapter.java
  redpanda-apicurio/examples/python/kafka-produce-avro.py
  redpanda/examples/avro/metric_sample.json
  redpanda/examples/avro/more_types.json
  redpanda/examples/python/kafka-produce-avro-more-types.py
  redpanda/examples/python/kafka-produce-avro.py
Labels: NoDocumentationNeeded

#2318 Return full traceback by default in DHError
  py/server/deephaven/dherror.py
Labels: NoDocumentationNeeded, python-server-side

#2299 update Debezium script for v2 python
  debezium/scripts/demo.py
Labels: NoDocumentationNeeded

#2328 Add missing endl for KafkaIngester
  extensions/kafka/src/main/java/io/deephaven/kafka/ingest/KafkaIngester.java
Labels: bug, NoDocumentationNeeded

#2296 Deephaven2 Python layout hints
  py/server/deephaven/table.py
  py/server/tests/test_table.py
Labels: python, DocumentationNeeded, python-server-side

#2330 Bump images
  docker/registry/nginx-base/gradle.properties
  docker/registry/nltk-base/gradle.properties
  docker/registry/node/gradle.properties
  docker/registry/protoc-base/gradle.properties
  docker/registry/python-dev-base/gradle.properties
  docker/registry/python/gradle.properties
  docker/registry/pytorch-base/gradle.properties
  docker/registry/server-base/gradle.properties
  docker/registry/sklearn-base/gradle.properties
  docker/registry/slim-base/gradle.properties
  docker/registry/tensorflow-base/gradle.properties
  docker/server/src/main/server-nltk/requirements.txt
  docker/server/src/main/server-pytorch/requirements.txt
  docker/server/src/main/server-sklearn/requirements.txt
  docker/server/src/main/server-tensorflow/requirements.txt
  docker/server/src/main/server/requirements.txt
Labels: NoDocumentationNeeded, version-bump

#2334 Make agg factory funcs accept 'one or many' type arguments
  py/server/deephaven/agg.py
  py/server/deephaven/jcompat.py
  py/server/deephaven/table.py
Labels: python, NoDocumentationNeeded

#2270 Defensively include Dockerfile
  buildSrc/src/main/groovy/Docker.groovy
Labels: docker, NoDocumentationNeeded

#2323 Undo default debug, remove unnecessary static.
  docker-compose-common.yml
  engine/time/src/main/java/io/deephaven/time/DateTime.java
  extensions/kafka/src/main/java/io/deephaven/kafka/ingest/GenericRecordDateTimeArrayFieldCopier.java
Labels: NoDocumentationNeeded

#2267 Allow deephaven_legacy to not be installed
  py/server/deephaven/server/script_session/__init__.py
Labels: NoDocumentationNeeded, python-server-side

#2338 Bump base images, includes deephaven-plugin
  docker/registry/nltk-base/gradle.properties
  docker/registry/pytorch-base/gradle.properties
  docker/registry/server-base/gradle.properties
  docker/registry/sklearn-base/gradle.properties
  docker/registry/tensorflow-base/gradle.properties
  docker/server/src/main/server-nltk/requirements.txt
  docker/server/src/main/server-pytorch/requirements.txt
  docker/server/src/main/server-sklearn/requirements.txt
  docker/server/src/main/server-tensorflow/requirements.txt
  docker/server/src/main/server/requirements.txt
Labels: NoDocumentationNeeded, version-bump

#2336 Wrap the Filter interface
  py/server/deephaven/calendar.py
  py/server/deephaven/filters.py
  py/server/tests/test_filters.py
Labels: python, DocumentationNeeded

#2339 Update debezium perf scripts to py2.
  debezium/scripts/sample_dt.py
Labels: NoDocumentationNeeded

#2333 Add docstrings for predefined DType instances
  py/server/deephaven/dtypes.py
  py/server/tests/test_table_factory.py
Labels: python, NoDocumentationNeeded

#2343 Disable CLA check for forks other than main deephaven one.
  .github/workflows/cla.yml
Labels: NoDocumentationNeeded

#2337 Refactor ScriptSession injection
  engine/table/src/main/java/io/deephaven/engine/util/AbstractScriptSession.java
  engine/table/src/main/java/io/deephaven/engine/util/GroovyDeephavenSession.java
  engine/table/src/main/java/io/deephaven/engine/util/NoLanguageDeephavenSession.java
  engine/table/src/main/java/io/deephaven/engine/util/PythonDeephavenSession.java
  server/src/main/java/io/deephaven/server/appmode/ApplicationInjector.java
  server/src/main/java/io/deephaven/server/console/ConsoleServiceGrpcImpl.java
  server/src/main/java/io/deephaven/server/console/GlobalSessionProvider.java
  server/src/main/java/io/deephaven/server/console/ScopeTicketResolver.java
  server/src/main/java/io/deephaven/server/console/python/PythonConsoleSessionModule.java
  server/src/main/java/io/deephaven/server/plugin/python/PythonPluginsRegistration.java
  server/src/main/java/io/deephaven/server/runner/DeephavenApiServer.java
  server/src/main/java/io/deephaven/server/runner/DeephavenApiServerModule.java
  server/src/main/java/io/deephaven/server/uri/QueryScopeResolver.java
  server/test/src/main/java/io/deephaven/server/test/FlightMessageRoundTripTest.java
Labels: NoDocumentationNeeded, dagger

#2346 Add proper check for JsonNode.isMissingNode()
  extensions/kafka/src/main/java/io/deephaven/kafka/ingest/JsonNodeUtil.java
Labels: kafka, NoDocumentationNeeded

#2341 Add ISO8601 support for convertDateTime.
  engine/time/src/main/java/io/deephaven/time/DateTimeUtils.java
  engine/time/src/test/java/io/deephaven/time/TestDateTimeUtils.java
  py/server/deephaven/time.py
Labels: NoDocumentationNeeded

#2314 JPy should release the GIL while in Java, with a special method to deliberately acquire it
  py/jpy-integration/src/javaToPython/java/io/deephaven/jpy/CreateModuleTest.java
  py/jpy-integration/src/javaToPython/java/io/deephaven/jpy/integration/PyLibTest.java
  py/jpy-integration/src/pythonToJava/python/test/test_jpy.py
  py/jpy/src/main/c/jni/org_jpy_PyLib.c
  py/jpy/src/main/c/jni/org_jpy_PyLib.h
  py/jpy/src/main/c/jpy_jmethod.c
  py/jpy/src/main/c/jpy_jtype.c
  py/jpy/src/main/c/jpy_module.c
  py/jpy/src/main/c/jpy_module.h
  py/jpy/src/main/java/org/jpy/PyLib.java
  py/jpy/src/main/java/org/jpy/PyObjectReferences.java
  py/jpy/src/test/java/org/jpy/PyLibTest.java
Labels: NoDocumentationNeeded, jpy

#1942 Plugin for pandas dataframes and JS API/UI support
  Integrations/python/setup.py
  py/server/deephaven/pandasplugin/__init__.py
  py/server/deephaven/pandasplugin/pandas_as_table.py
  py/server/setup.py
  web/client-api/src/main/java/io/deephaven/ide/shared/IdeSession.java
  web/client-api/src/main/java/io/deephaven/web/client/api/WorkerConnection.java
  web/client-api/src/main/java/io/deephaven/web/client/api/console/JsVariableChanges.java
  web/client-api/src/main/java/io/deephaven/web/client/api/widget/JsWidgetExportedObject.java
Labels: jsapi, python, NoDocumentationNeeded, plug-ins

#2350 Support providing Avro schemas as a JSON schema definition from python. Fixes #2305.
  extensions/kafka/src/main/java/io/deephaven/kafka/KafkaTools.java
  py/server/deephaven/stream/kafka/consumer.py
Labels: NoDocumentationNeeded

#2352 Support string values for Kafka json ingestion of DateTime types
  extensions/kafka/src/main/java/io/deephaven/kafka/ingest/JsonNodeDateTimeFieldCopier.java
Labels: kafka, NoDocumentationNeeded

#2349 Write websocket errors to JULI instead of stdout
  grpc-java/grpc-servlet-websocket-jakarta/src/main/java/io/grpc/servlet/web/websocket/WebSocketServerStream.java
Labels: bug, NoDocumentationNeeded, jetty

#2358 Update web to v0.11.7
  web/client-ui/Dockerfile
Labels: NoDocumentationNeeded
