Repository deephaven/deephaven-core, pull requests merged in 2022-07, with the labels that each got.

#2613 Web version v0.14.1
  web/client-ui/Dockerfile
Labels: web-client-ui, NoDocumentationNeeded

#2610 Wrap partitioned table factory and add Partition aggregation
  py/server/deephaven/agg.py
  py/server/deephaven/column.py
  py/server/deephaven/parquet.py
  py/server/deephaven/table.py
  py/server/tests/test_partitioned_table.py
  py/server/tests/test_table.py
Labels: DocumentationNeeded, python-server-side

#2609 Add UpdateByTable QST
  engine/api/src/main/java/io/deephaven/engine/table/Table.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/TableWithDefaults.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/UpdateByOperatorFactory.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/partitioned/PartitionedTableProxyImpl.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestCumProd.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestCumSum.java
  java-client/session/src/main/java/io/deephaven/client/impl/BatchTableRequestBuilder.java
  qst/graphviz/src/main/java/io/deephaven/graphviz/LabelBuilder.java
  qst/src/main/java/io/deephaven/qst/TableAdapterImpl.java
  qst/src/main/java/io/deephaven/qst/table/ParentsVisitor.java
  qst/src/main/java/io/deephaven/qst/table/TableBase.java
  qst/src/main/java/io/deephaven/qst/table/TableSpec.java
  qst/src/main/java/io/deephaven/qst/table/TableVisitorGeneric.java
  qst/src/main/java/io/deephaven/qst/table/UpdateByTable.java
  qst/src/test/java/io/deephaven/qst/table/TableCreatorImplTest.java
  table-api/src/main/java/io/deephaven/api/TableOperations.java
  table-api/src/main/java/io/deephaven/api/TableOperationsAdapter.java
  table-api/src/main/java/io/deephaven/api/updateby/UpdateByControl.java
Labels: NoDocumentationNeeded, qst

#2617 Allow table/partitionedtable arrays to grow as needed in JS Figure
  web/client-api/src/main/java/io/deephaven/web/client/api/widget/plot/JsFigure.java
Labels: jsapi, plotting, NoDocumentationNeeded, release blocker

#2615 Add PartitionedTable keys() helper method
  py/server/deephaven/table.py
  py/server/tests/test_partitioned_table.py
Labels: DocumentationNeeded, python-server-side

#2603 Package and publish applications / wheels
  .github/workflows/publish-ci.yml
Labels: ci, NoDocumentationNeeded, release

#2619 Bump to 0.15.0
  .github/workflows/build-ci.yml
  buildSrc/src/main/groovy/io.deephaven.common-conventions.gradle
  py/client/README.md
  py/client/pydeephaven/__init__.py
  py/client/setup.py
  py/server/deephaven/__init__.py
  server/jetty-app/README.md
Labels: NoDocumentationNeeded, version-bump

#2621 Fix DeephavenApiServer.run() javadoc regarding blocking.
  server/src/main/java/io/deephaven/server/runner/DeephavenApiServer.java
Labels: NoDocumentationNeeded

#2560 Treemaps
  Generators/src/main/java/io/deephaven/plot/util/GeneratePlottingConvenience.java
  Generators/src/main/java/io/deephaven/plot/util/GeneratePyV2FigureAPI.java
  Plot/src/main/java/io/deephaven/plot/Axes.java
  Plot/src/main/java/io/deephaven/plot/AxesImpl.java
  Plot/src/main/java/io/deephaven/plot/ChartType.java
  Plot/src/main/java/io/deephaven/plot/Figure.java
  Plot/src/main/java/io/deephaven/plot/FigureImpl.java
  Plot/src/main/java/io/deephaven/plot/PlotStyle.java
  Plot/src/main/java/io/deephaven/plot/PlottingConvenience.java
  Plot/src/main/java/io/deephaven/plot/datasets/category/CategoryTreeMapDataSeriesTableMap.java
  engine/table/src/main/java/io/deephaven/gui/color/Color.java
  plugin/figure/src/main/java/io/deephaven/figure/FigureWidgetTranslator.java
  proto/proto-backplane-grpc/src/main/proto/deephaven/proto/console.proto
  py/server/deephaven/plot/color.py
  py/server/deephaven/plot/figure.py
  web/client-api/src/main/java/io/deephaven/web/client/api/widget/plot/JsFigure.java
  web/client-api/src/main/java/io/deephaven/web/client/api/widget/plot/enums/JsChartType.java
  web/client-api/src/main/java/io/deephaven/web/client/api/widget/plot/enums/JsSeriesPlotStyle.java
  web/client-api/src/main/java/io/deephaven/web/client/api/widget/plot/enums/JsSourceType.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/console_pb/figuredescriptor/SeriesPlotStyleMap.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/console_pb/figuredescriptor/SourceTypeMap.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/console_pb/figuredescriptor/chartdescriptor/ChartTypeMap.java
Labels: plotting, DocumentationNeeded

#2620 Remove unnecessary null checks in js api for figures
  web/client-api/src/main/java/io/deephaven/web/client/api/widget/plot/JsFigure.java
Labels: jsapi, plotting, NoDocumentationNeeded

#2630 Bump node
  docker/registry/node/gradle.properties
Labels: NoDocumentationNeeded, version-bump

#2634 Bump node and protoc-base images
  docker/registry/node/gradle.properties
  docker/registry/protoc-base/gradle.properties
Labels: NoDocumentationNeeded, version-bump

#2633 UpdateBy config changes in support of gRPC
  engine/table/src/main/java/io/deephaven/engine/table/impl/BucketedUpdateBy.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/UpdateBy.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/UpdateByOperatorFactory.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/ZeroKeyUpdateBy.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/ema/BasePrimitiveEMAOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/ema/BigDecimalEMAOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/ema/BigIntegerEMAOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/ema/BigNumberEMAOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/ema/DoubleEMAOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/ema/FloatEMAOperator.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestCumProd.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestCumSum.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestEma.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestUpdateByGeneral.java
  table-api/src/main/java/io/deephaven/api/updateby/BadDataBehavior.java
  table-api/src/main/java/io/deephaven/api/updateby/EmaControl.java
  table-api/src/main/java/io/deephaven/api/updateby/UpdateByControl.java
  table-api/src/main/java/io/deephaven/api/updateby/spec/EmaSpec.java
Labels: configuration, NoDocumentationNeeded

#2645 Add support for single string arg for DTW
  py/server/deephaven/table_factory.py
  py/server/tests/test_table_factory.py
Labels: NoDocumentationNeeded, python-server-side

#2640 Skip JpyConfig if python is already initialized
  engine/table/src/main/java/io/deephaven/engine/util/jpy/JpyInit.java
Labels: NoDocumentationNeeded

#2632 Wrap PartitionedTableProxy in Python
  py/server/deephaven/parquet.py
  py/server/deephaven/table.py
  py/server/tests/test_pt_proxy.py
  py/server/tests/test_table.py
  py/server/tests/test_ugp.py
Labels: DocumentationNeeded, python-server-side

#2651 Update redpanda docker repo
  containers/python-examples-redpanda/docker-compose.yml
  debezium/docker-compose-debezium-common.yml
  debezium/perf/redpanda/Dockerfile
  redpanda-standalone/docker-compose.yml
Labels: bug, NoDocumentationNeeded

#2656 Bump base images and python requirements
  docker/registry/nginx-base/gradle.properties
  docker/registry/nltk-base/gradle.properties
  docker/registry/node/gradle.properties
  docker/registry/protoc-base/gradle.properties
  docker/registry/python-dev-base/gradle.properties
  docker/registry/python/gradle.properties
  docker/registry/pytorch-base/gradle.properties
  docker/registry/server-base/gradle.properties
  docker/registry/sklearn-base/gradle.properties
  docker/registry/slim-base/gradle.properties
  docker/registry/tensorflow-base/gradle.properties
  docker/server/src/main/server-nltk/requirements.txt
  docker/server/src/main/server-pytorch/requirements.txt
  docker/server/src/main/server-sklearn/requirements.txt
  docker/server/src/main/server-tensorflow/requirements.txt
  docker/server/src/main/server/requirements.txt
Labels: NoDocumentationNeeded, version-bump

#2652 Create java client tests for view, update, updateView, select, where, and aggBy
  java-client/session-dagger/src/test/java/io/deephaven/client/AggBySessionTest.java
  java-client/session-dagger/src/test/java/io/deephaven/client/UpdateOrSelectSessionTest.java
  java-client/session-dagger/src/test/java/io/deephaven/client/WhereSessionTest.java
Labels: test, NoDocumentationNeeded

#2657 Add port to the Embedded server instance
  py/embedded-server/README.md
  py/embedded-server/deephaven_server/server.py
  py/embedded-server/java-runtime/src/main/java/io/deephaven/python/server/EmbeddedServer.java
Labels: NoDocumentationNeeded

#2659 Improve usability and docs for UpdateBy
  engine/api/src/main/java/io/deephaven/engine/table/Table.java
  engine/table/src/main/java/io/deephaven/engine/util/GroovyDeephavenSession.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestCumMinMax.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestCumProd.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestCumSum.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestUpdateByGeneral.java
  table-api/src/main/java/io/deephaven/api/updateby/UpdateByClause.java
Labels: clean up, NoDocumentationNeeded

#2663 Add wavgBy, wsumBy, absSumBy in both Table and PartitionedTableProxy
  py/server/deephaven/table.py
  py/server/tests/test_pt_proxy.py
  py/server/tests/test_table.py
Labels: DocumentationNeeded, python-server-side

#2665 Don't expect nested protobuf objects to be null
  server/src/main/java/io/deephaven/server/table/ops/filter/FilterVisitor.java
  server/src/main/java/io/deephaven/server/table/ops/filter/NormalizeFilterUtil.java
  server/src/test/java/io/deephaven/server/table/ops/filter/FilterPrinterTest.java
  server/src/test/java/io/deephaven/server/table/ops/filter/FilterTestUtils.java
Labels: jsapi, grpc, NoDocumentationNeeded

#2667 Generate py from protos and correctly mangle python modules
  buildSrc/src/main/groovy/io/deephaven/tools/docker/DiffTask.groovy
  proto/proto-backplane-grpc/build.gradle
  proto/raw-js-openapi/build.gradle
  py/client/build.gradle
  py/client/pydeephaven/proto/application_pb2.py
  py/client/pydeephaven/proto/console_pb2.py
  py/client/pydeephaven/proto/inputtable_pb2.py
  py/client/pydeephaven/proto/object_pb2.py
  py/client/pydeephaven/proto/partitionedtable_pb2.py
  py/client/pydeephaven/proto/partitionedtable_pb2_grpc.py
  py/client/pydeephaven/proto/session_pb2.py
  py/client/pydeephaven/proto/table_pb2.py
  py/client/pydeephaven/proto/table_pb2_grpc.py
  py/client/pydeephaven/proto/ticket_pb2.py
Labels: build, grpc, NoDocumentationNeeded, python-client

#2670 Classpaths for junit (classic)
  Base/build.gradle
  Configuration/build.gradle
  Container/build.gradle
  buildSrc/src/main/groovy/Classpaths.groovy
  buildSrc/src/main/groovy/io.deephaven.java-classpath-conventions.gradle
  codegen/build.gradle
  engine/api/build.gradle
  engine/chunk/build.gradle
  engine/rowset/build.gradle
  engine/table/build.gradle
  engine/tuple/build.gradle
  engine/updategraph/build.gradle
  engine/vector/build.gradle
  extensions/csv/build.gradle
  extensions/kafka/build.gradle
  extensions/parquet/base/build.gradle
  extensions/parquet/table/build.gradle
  java-client/session/build.gradle
  server/test/build.gradle
Labels: build, clean up, NoDocumentationNeeded

#2650 Simplify ColumnExpressionValidator
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/SwitchColumn.java
  java-client/session-dagger/src/test/java/io/deephaven/client/AggBySessionTest.java
  java-client/session-dagger/src/test/java/io/deephaven/client/UpdateOrSelectSessionTest.java
  java-client/session-dagger/src/test/java/io/deephaven/client/WhereSessionTest.java
  py/client/tests/test_query.py
  server/src/main/java/io/deephaven/server/table/validation/ColumnExpressionValidator.java
Labels: java, NoDocumentationNeeded

#2669 Upgrade CI to ubuntu-22.04
  .github/workflows/build-ci.yml
  .github/workflows/check-ci.yml
  .github/workflows/cla.yml
  .github/workflows/docs-ci.yml
  .github/workflows/label-check-ci.yml
  .github/workflows/nightly-check-ci.yml
  .github/workflows/nightly-image-check.yml
  .github/workflows/publish-check-ci.yml
  .github/workflows/publish-ci.yml
  .github/workflows/quick-ci.yml
Labels: ci, NoDocumentationNeeded, version-bump

#2675 2673 Datetime col to numpy array not writeable error
  py/server/deephaven/numpy.py
Labels: NoDocumentationNeeded

#2677 Extract DH testing server to a gradle extension for reuse
  buildSrc/src/main/groovy/io.deephaven.deephaven-in-docker.gradle
  buildSrc/src/main/groovy/io/deephaven/tools/docker/DeephavenInDockerExtension.groovy
  py/client/build.gradle
Labels: build, test, NoDocumentationNeeded, python-client

#2676 Update web to 0.15.1
  web/client-ui/Dockerfile
Labels: NoDocumentationNeeded

#2680 Renamed Java updateBy objects
  engine/api/src/main/java/io/deephaven/engine/table/Table.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/DeferredViewTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/SimpleSourceTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/TableWithDefaults.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/UncoalescedTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/UpdateBy.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/UpdateByOperatorFactory.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/partitioned/PartitionedTableProxyImpl.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/ema/BasePrimitiveEMAOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/ema/BigDecimalEMAOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/ema/BigIntegerEMAOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/ema/BigNumberEMAOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/ema/ByteEMAOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/ema/DoubleEMAOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/ema/FloatEMAOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/ema/IntEMAOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/ema/LongEMAOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/ema/ShortEMAOperator.java
  engine/table/src/main/java/io/deephaven/engine/util/GroovyDeephavenSession.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestCumMinMax.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestCumProd.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestCumSum.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestEma.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestForwardFill.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestUpdateByGeneral.java
  qst/src/main/java/io/deephaven/qst/table/TableBase.java
  qst/src/main/java/io/deephaven/qst/table/UpdateByTable.java
  qst/src/test/java/io/deephaven/qst/table/TableCreatorImplTest.java
  table-api/src/main/java/io/deephaven/api/TableOperations.java
  table-api/src/main/java/io/deephaven/api/TableOperationsAdapter.java
  table-api/src/main/java/io/deephaven/api/updateby/ColumnUpdateOperation.java
  table-api/src/main/java/io/deephaven/api/updateby/OperationControl.java
  table-api/src/main/java/io/deephaven/api/updateby/UpdateByOperation.java
  table-api/src/main/java/io/deephaven/api/updateby/spec/EmaSpec.java
  table-api/src/main/java/io/deephaven/api/updateby/spec/UpdateBySpec.java
  table-api/src/main/java/io/deephaven/api/updateby/spec/UpdateBySpecBase.java
Labels: NoDocumentationNeeded

#2682 Port DHE fix for DH-12895 (RowSetSequentialBuilder.appendRowSequence bug) to DHE.
  engine/rowset/src/main/java/io/deephaven/engine/rowset/impl/rsp/RspBitmap.java
  engine/rowset/src/test/java/io/deephaven/engine/rowset/impl/WritableRowSetImplTest.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java
Labels: NoDocumentationNeeded

#2653 Wrap updateBy operation
  py/server/deephaven/table.py
  py/server/deephaven/table_factory.py
  py/server/deephaven/updateby.py
  py/server/tests/test_table_factory.py
  py/server/tests/test_updateby.py
Labels: DocumentationNeeded, python-server-side

#2684 Bump slim base image
  docker/registry/slim-base/gradle.properties
Labels: NoDocumentationNeeded, version-bump

#2666 Prune dead web classes
  web/shared-beans/src/main/java/io/deephaven/web/shared/ast/AbstractVisitor.java
  web/shared-beans/src/main/java/io/deephaven/web/shared/ast/ConvertEqToIn.java
  web/shared-beans/src/main/java/io/deephaven/web/shared/ast/ConvertInvalidInExpressions.java
  web/shared-beans/src/main/java/io/deephaven/web/shared/ast/FilterPrinter.java
  web/shared-beans/src/main/java/io/deephaven/web/shared/ast/FilterValidator.java
  web/shared-beans/src/main/java/io/deephaven/web/shared/ast/FlipNonReferenceMatchExpression.java
  web/shared-beans/src/main/java/io/deephaven/web/shared/ast/GetTopLevelFilters.java
  web/shared-beans/src/main/java/io/deephaven/web/shared/ast/MakeExpressionsNullSafe.java
  web/shared-beans/src/main/java/io/deephaven/web/shared/ast/MergeNestedBinaryOperations.java
  web/shared-beans/src/main/java/io/deephaven/web/shared/ast/MergeRelatedSiblingExpressions.java
  web/shared-beans/src/main/java/io/deephaven/web/shared/ast/NormalizeNots.java
  web/shared-beans/src/main/java/io/deephaven/web/shared/ast/ReplacingVisitor.java
  web/shared-beans/src/main/java/io/deephaven/web/shared/batch/BatchTableRequest.java
  web/shared-beans/src/main/java/io/deephaven/web/shared/batch/BatchTableResponse.java
  web/shared-beans/src/main/java/io/deephaven/web/shared/data/ColumnHolder.java
  web/shared-beans/src/main/java/io/deephaven/web/shared/util/ParseUtils.java
  web/shared-beans/src/test/java/io/deephaven/web/shared/ast/AbstractReplacingVisitorTest.java
  web/shared-beans/src/test/java/io/deephaven/web/shared/ast/ConvertEqToInTest.java
  web/shared-beans/src/test/java/io/deephaven/web/shared/ast/ConvertInvalidInExpressionsTest.java
  web/shared-beans/src/test/java/io/deephaven/web/shared/ast/FilterTestUtils.java
  web/shared-beans/src/test/java/io/deephaven/web/shared/ast/FlipNonReferenceMatchExpressionTest.java
  web/shared-beans/src/test/java/io/deephaven/web/shared/ast/MakeExpressionsNullSafeTest.java
  web/shared-beans/src/test/java/io/deephaven/web/shared/ast/MergeNestedBinaryOperationsTest.java
  web/shared-beans/src/test/java/io/deephaven/web/shared/ast/MergeRelatedSiblingExpressionsTest.java
  web/shared-beans/src/test/java/io/deephaven/web/shared/ast/NormalizeNotsTest.java
Labels: jsapi, clean up, NoDocumentationNeeded

#2683 Use better Dockerfile layer ordering to maximize cacheability
  go/build.gradle
  py/client/build.gradle
Labels: test, docker, NoDocumentationNeeded

#2688 Bump protoc-base image, which now includes go proto binaries
  docker/registry/protoc-base/gradle.properties
  proto/proto-backplane-grpc/Dockerfile
Labels: NoDocumentationNeeded, version-bump

#2691 Removed unneeded overrides for updateBy() from SimpleSourceTable and …
  engine/table/src/main/java/io/deephaven/engine/table/impl/DeferredViewTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/SimpleSourceTable.java
Labels: NoDocumentationNeeded

#2686 Have a more generous timeout for test cases
  py/server/tests/test_ugp.py
Labels: python, test, NoDocumentationNeeded

#2662 groupByColumns to ColumnName
  ClientSupport/src/main/java/io/deephaven/treetable/RollupDefinition.java
  ClientSupport/src/main/java/io/deephaven/treetable/RollupSnapshotImpl.java
  Plot/src/main/java/io/deephaven/plot/AxesImpl.java
  Plot/src/main/java/io/deephaven/plot/util/PlotUtils.java
  engine/api/src/main/java/io/deephaven/engine/table/Table.java
  engine/api/src/main/java/io/deephaven/engine/table/TableDefinition.java
  engine/benchmark/src/benchmark/java/io/deephaven/benchmark/engine/PercentileByBenchmark.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/DeferredViewTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/HierarchicalTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/MemoizedOperationKey.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/PartitionAwareSourceTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/RollupInfo.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/SimpleSourceTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/TableWithDefaults.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/UncoalescedTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/UpdateBy.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/ApproximatePercentile.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/ChunkedOperatorAggregationHelper.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/partitioned/PartitionedTableProxyImpl.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/FreezeBy.java
  engine/table/src/main/java/io/deephaven/engine/util/TotalsTableBuilder.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableAggregationTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestUpdateByGeneral.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/ParquetTableReadWriteTest.java
  java-client/session-dagger/src/test/java/io/deephaven/client/AggBySessionTest.java
  java-client/session/src/main/java/io/deephaven/client/impl/BatchTableRequestBuilder.java
  qst/graphviz/src/main/java/io/deephaven/graphviz/LabelBuilder.java
  qst/src/main/java/io/deephaven/qst/TableAdapterImpl.java
  qst/src/main/java/io/deephaven/qst/table/AggregateAllByTable.java
  qst/src/main/java/io/deephaven/qst/table/ByTableBase.java
  qst/src/main/java/io/deephaven/qst/table/SelectDistinctTable.java
  qst/src/main/java/io/deephaven/qst/table/TableBase.java
  server/src/main/java/io/deephaven/server/table/ops/ComboAggregateGrpcImpl.java
  table-api/src/main/java/io/deephaven/api/ColumnName.java
  table-api/src/main/java/io/deephaven/api/TableOperations.java
  table-api/src/main/java/io/deephaven/api/TableOperationsAdapter.java
  table-api/src/main/java/io/deephaven/api/agg/spec/AggSpecGroup.java
Labels: DocumentationNeeded

#2689 Use autolocking ctx manager instead of decorator
  py/server/deephaven/table.py
  py/server/deephaven/table_factory.py
  py/server/deephaven/ugp.py
Labels: python, NoDocumentationNeeded

#2694 Fix issue with merge of static and refreshing tables
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/analyzers/SelectColumnLayer.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/PartitionedTableTest.java
Labels: bug, query engine, NoDocumentationNeeded, partitioned_tables

#2644 Ensure that the server has been properly initialized before import
  engine/table/src/main/java/io/deephaven/engine/util/jpy/JpyInit.java
  py/embedded-server/deephaven_server/start_jvm.py
  py/server/deephaven/__init__.py
  py/server/deephaven/server/script_session/__init__.py
  py/server/deephaven_internal/__init__.py
  py/server/deephaven_internal/jvm/__init__.py
  py/server/test_helper/__init__.py
  server/src/main/java/io/deephaven/server/runner/DeephavenApiServer.java
  sphinx/source/conf.py
Labels: python, NoDocumentationNeeded, python-server-side

#2687 Update Figure Generator to allow nullable parameters
  Generators/src/main/java/io/deephaven/plot/util/GeneratePyV2FigureAPI.java
Labels: NoDocumentationNeeded, internal

#2696 Fix broken Go client documentation
  go/LICENSE
  go/NOTICE
  go/README.md
Labels: bug, documentation, NoDocumentationNeeded

#2678 Clean up the treemap API
  Generators/src/main/java/io/deephaven/plot/util/GeneratePlottingConvenience.java
  Generators/src/main/java/io/deephaven/plot/util/GeneratePyV2FigureAPI.java
  Plot/src/main/java/io/deephaven/plot/Axes.java
  Plot/src/main/java/io/deephaven/plot/AxesImpl.java
  Plot/src/main/java/io/deephaven/plot/Figure.java
  Plot/src/main/java/io/deephaven/plot/FigureImpl.java
  Plot/src/main/java/io/deephaven/plot/PlottingConvenience.java
  Plot/src/main/java/io/deephaven/plot/datasets/category/CategoryTreemapDataSeriesTableMap.java
  plugin/figure/src/main/java/io/deephaven/figure/FigureWidgetTranslator.java
  py/server/deephaven/plot/figure.py
  web/client-api/src/main/java/io/deephaven/web/client/api/console/JsVariableChanges.java
  web/client-api/src/main/java/io/deephaven/web/client/api/widget/plot/enums/JsSourceType.java
Labels: DocumentationNeeded

#2697 Add `go mod verify` to go test
  go/build.gradle
Labels: test, NoDocumentationNeeded

#2698 Add note and slightly simplify TableAdapterImpl
  java-client/session/src/main/java/io/deephaven/client/impl/TableHandleManagerSerial.java
  qst/src/main/java/io/deephaven/qst/TableAdapterImpl.java
  qst/src/main/java/io/deephaven/qst/TableAdapterResults.java
  qst/src/main/java/io/deephaven/qst/table/TableCreationLogicImpl.java
Labels: NoDocumentationNeeded

#2700 Fix broken link in Go client docs
  go/README.md
  go/pkg/client/client.go
Labels: documentation, NoDocumentationNeeded

#2699 LazyUpdateTable
  engine/table/src/main/java/io/deephaven/engine/table/impl/partitioned/PartitionedTableProxyImpl.java
  java-client/session-dagger/src/test/java/io/deephaven/client/UpdateOrSelectSessionTest.java
  java-client/session/src/main/java/io/deephaven/client/impl/BatchTableRequestBuilder.java
  qst/graphviz/src/main/java/io/deephaven/graphviz/LabelBuilder.java
  qst/src/main/java/io/deephaven/qst/TableAdapterImpl.java
  qst/src/main/java/io/deephaven/qst/table/LazyUpdateTable.java
  qst/src/main/java/io/deephaven/qst/table/ParentsVisitor.java
  qst/src/main/java/io/deephaven/qst/table/TableBase.java
  qst/src/main/java/io/deephaven/qst/table/TableSpec.java
  qst/src/main/java/io/deephaven/qst/table/TableVisitorGeneric.java
  table-api/src/main/java/io/deephaven/api/TableOperations.java
  table-api/src/main/java/io/deephaven/api/TableOperationsAdapter.java
Labels: NoDocumentationNeeded, qst, java-client

#2704 Web version updated to 0.15.2
  web/client-ui/Dockerfile
Labels: web-client-ui, NoDocumentationNeeded, internal

#2648 Add heap size API to community
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/PerformanceQueries.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/RuntimeMemory.java
  go/internal/proto/console/console.pb.go
  go/internal/proto/console/console_grpc.pb.go
  proto/proto-backplane-grpc/src/main/proto/deephaven/proto/console.proto
  py/client/pydeephaven/proto/console_pb2.py
  py/client/pydeephaven/proto/console_pb2_grpc.py
  server/src/main/java/io/deephaven/server/console/ConsoleServiceGrpcImpl.java
  web/WebDevelopersGuide.md
  web/client-api/src/main/java/io/deephaven/web/client/api/JsWorkerHeapInfo.java
  web/client-api/src/main/java/io/deephaven/web/client/api/QueryConnectable.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/console_pb/GetHeapInfoRequest.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/console_pb/GetHeapInfoResponse.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/console_pb_service/ConsoleService.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/console_pb_service/ConsoleServiceClient.java
Labels: feature request, DocumentationNeeded

#2348 Add LayoutHint column grouping API
  engine/table/src/main/java/io/deephaven/engine/util/LayoutHintBuilder.java
  py/server/deephaven/table.py
  py/server/tests/test_table.py
  web/client-api/src/main/java/io/deephaven/web/client/api/JsLayoutHints.java
Labels: feature request, jsapi, python, java, DocumentationNeeded
