Repository deephaven/deephaven-core, pull requests merged in 2022-11, with the labels that each got.

#3042 Allow rows/cols to be passed in to python `Figure` constructor
  Generators/src/main/java/io/deephaven/plot/util/GeneratePyV2FigureAPI.java
  Generators/src/main/java/io/deephaven/pythonPreambles/plotV2.py
  py/server/deephaven/plot/figure.py
Labels: DocumentationNeeded

#3051 Add a bit more detail to C++ python wrapping spike in py/client2.
  py/client2/.gitignore
  py/client2/README.md
Labels: NoDocumentationNeeded

#3035 Simplify Configuration
  BenchmarkSupport/src/main/java/io/deephaven/benchmarking/BenchmarkTools.java
  BenchmarkSupport/src/main/java/io/deephaven/benchmarking/runner/BenchmarkRunner.java
  BenchmarkSupport/src/main/java/io/deephaven/benchmarking/runner/TableBenchmarkState.java
  Configuration/src/main/java/io/deephaven/configuration/CacheDir.java
  Configuration/src/main/java/io/deephaven/configuration/ConfigDir.java
  Configuration/src/main/java/io/deephaven/configuration/Configuration.java
  Configuration/src/main/java/io/deephaven/configuration/DataDir.java
  Configuration/src/main/java/io/deephaven/configuration/ParsedProperties.java
  Configuration/src/test/java/io/deephaven/configuration/TestConfiguration.java
  FishUtil/src/main/java/io/deephaven/util/PidFileUtil.java
  FishUtil/src/main/java/io/deephaven/util/ProcessNameUtil.java
  Generators/Generators.gradle
  Integrations/build.gradle
  ModelFarm/src/test/java/io/deephaven/modelfarm/TestModelInputSerializerDeserializer.java
  Net/build.gradle
  Stats/build.gradle
  Util/src/main/java/io/deephaven/util/HeapDump.java
  docker/server-jetty/src/main/configure/image-bootstrap.properties
  docker/server-jetty/src/main/docker/Dockerfile
  docker/server-slim/src/main/docker/Dockerfile
  docker/server-slim/src/main/docker/image-bootstrap.properties
  docker/server/src/main/configure/image-bootstrap.properties
  docker/server/src/main/docker/Dockerfile
  engine/context/src/main/java/io/deephaven/engine/context/QueryCompiler.java
  engine/table/src/main/java/io/deephaven/engine/util/AbstractScriptSession.java
  engine/table/src/main/java/io/deephaven/engine/util/CacheDir.java
  engine/table/src/test/java/io/deephaven/engine/util/file/TestFileHandle.java
  engine/table/src/test/java/io/deephaven/engine/util/file/TestTrackedFileHandleFactory.java
  engine/table/src/test/java/io/deephaven/engine/util/file/TestTrackedSeekableByteChannel.java
  engine/table/src/test/java/io/deephaven/engine/util/jpy/JpyConfigLoaderTest.java
  extensions/parquet/benchmark/src/benchmark/java/io/deephaven/benchmark/parquet/table/TableWriteBenchmark.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/TestParquetTools.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/TestSymbolTableSource.java
  log-factory/src/main/java/io/deephaven/internal/log/Bootstrap.java
  py/embedded-server/deephaven_server/start_jvm.py
  py/embedded-server/java-runtime/src/main/java/io/deephaven/python/server/EmbeddedServer.java
  py/embedded-server/java-runtime/src/main/resources/bootstrap.properties
  py/server/deephaven/config/__init__.py
  py/server/test_helper/__init__.py
  py/server/tests/test_config.py
  server/build.gradle
  server/jetty-app/build.gradle
  server/jetty-app/src/main/resources/bootstrap.properties
  server/jetty/src/main/java/io/deephaven/server/jetty/JettyMain.java
  server/netty-app/build.gradle
  server/netty-app/src/main/resources/bootstrap.properties
  server/netty/src/main/java/io/deephaven/server/netty/NettyMain.java
  server/src/main/java/io/deephaven/server/notebook/FilesystemStorageServiceGrpcImpl.java
  server/src/main/java/io/deephaven/server/runner/Main.java
  sphinx/source/conf.py
Labels: configuration, clean up, docker, DocumentationNeeded

#3058 Fix getOrSet when environment variables are set
  Configuration/src/main/java/io/deephaven/configuration/CacheDir.java
  Configuration/src/main/java/io/deephaven/configuration/ConfigDir.java
  Configuration/src/main/java/io/deephaven/configuration/DataDir.java
Labels: bug, configuration, NoDocumentationNeeded, release blocker

#3060 Web version bump to v0.21.1
  web/client-ui/Dockerfile
Labels: bug, NoDocumentationNeeded

#3061 Add DEEPHAVEN_QUIET environment variable flag
  log-factory/src/main/java/io/deephaven/internal/log/Bootstrap.java
Labels: configuration, NoDocumentationNeeded

#3056 Add js-plugins pre-built support
  server/jetty/src/main/java/io/deephaven/server/jetty/JettyBackedGrpcServer.java
  server/jetty/src/main/java/io/deephaven/server/jetty/JsPlugins.java
Labels: web-client-ui, DocumentationNeeded, plug-ins

#3064 Multiplexed websocket instances should remove handlers when finished
  web/client-api/src/main/java/io/deephaven/web/client/api/grpc/MultiplexedWebsocketTransport.java
Labels: jsapi, grpc, NoDocumentationNeeded

#3066 Post release bump from 0.18.0 to 0.19.0
  .github/workflows/build-ci.yml
  buildSrc/src/main/groovy/io.deephaven.common-conventions.gradle
  py/client/README.md
  py/client/pydeephaven/__init__.py
  py/client/setup.py
  py/embedded-server/deephaven_server/__init__.py
  py/server/deephaven/__init__.py
  server/jetty-app/README.md
Labels: NoDocumentationNeeded, version-bump

#3068 Update docker registry images
  docker/registry/all-ai-base/gradle.properties
  docker/registry/cpp-client-base/gradle.properties
  docker/registry/go/gradle.properties
  docker/registry/nltk-base/gradle.properties
  docker/registry/node/gradle.properties
  docker/registry/protoc-base/gradle.properties
  docker/registry/python/gradle.properties
  docker/registry/pytorch-base/gradle.properties
  docker/registry/server-base/gradle.properties
  docker/registry/sklearn-base/gradle.properties
  docker/registry/slim-base/gradle.properties
  docker/registry/tensorflow-base/gradle.properties
  docker/server-jetty/src/main/server-jetty/requirements.txt
  docker/server/src/main/server-all-ai-netty/requirements.txt
  docker/server/src/main/server-netty/requirements.txt
  docker/server/src/main/server-nltk-netty/requirements.txt
  docker/server/src/main/server-pytorch-netty/requirements.txt
  docker/server/src/main/server-sklearn-netty/requirements.txt
  docker/server/src/main/server-tensorflow-netty/requirements.txt
Labels: NoDocumentationNeeded, version-bump

#3072 Call pkgutil.walk_packages with prefix set to 'deephaven' in _recursive_import
  py/server/deephaven/_wrapper.py
Labels: NoDocumentationNeeded, python-server-side

#3076 JS API stream tables should only adjust sizes if they have a viewport
  web/client-api/src/main/java/io/deephaven/web/client/state/ClientTableState.java
Labels: jsapi, NoDocumentationNeeded

#3069 Bump base images to jpy 0.13.0
  docker/registry/all-ai-base/gradle.properties
  docker/registry/go/gradle.properties
  docker/registry/nltk-base/gradle.properties
  docker/registry/node/gradle.properties
  docker/registry/protoc-base/gradle.properties
  docker/registry/pytorch-base/gradle.properties
  docker/registry/scripts/update-requirements.sh
  docker/registry/server-base/gradle.properties
  docker/registry/sklearn-base/gradle.properties
  docker/registry/tensorflow-base/gradle.properties
  docker/server-jetty/src/main/server-jetty/requirements.txt
  docker/server/src/main/server-all-ai-netty/requirements.txt
  docker/server/src/main/server-netty/requirements.txt
  docker/server/src/main/server-nltk-netty/requirements.txt
  docker/server/src/main/server-pytorch-netty/requirements.txt
  docker/server/src/main/server-sklearn-netty/requirements.txt
  docker/server/src/main/server-tensorflow-netty/requirements.txt
  py/embedded-server/setup.py
  py/jpy-ext/build.gradle
  py/server/setup.py
Labels: NoDocumentationNeeded, version-bump

#3083 Adds support for Python 3.11
  py/embedded-server/setup.py
  py/server/setup.py
Labels: NoDocumentationNeeded

#3037 Provide io.deephaven.appmode.ApplicationState.Factory via a Set
  server/src/main/java/io/deephaven/server/appmode/AppModeModule.java
  server/src/main/java/io/deephaven/server/appmode/ApplicationInjector.java
Labels: NoDocumentationNeeded, dagger

#3065 Set the defaults for start_jvm in code
  py/embedded-server/deephaven_server/start_jvm.py
Labels: bug, python, NoDocumentationNeeded

#3093 Corrected AsOfJoin `rehashInternalFull()` to update hashSlots correctly
  engine/table/src/main/java/io/deephaven/engine/table/impl/asofjoin/RightIncrementalAsOfJoinStateManagerTypedBase.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/asofjoin/TypedAsOfJoinFactory.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/asofjoin/typed/rightincopen/gen/RightIncrementalAsOfJoinHasherByte.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/asofjoin/typed/rightincopen/gen/RightIncrementalAsOfJoinHasherChar.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/asofjoin/typed/rightincopen/gen/RightIncrementalAsOfJoinHasherDouble.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/asofjoin/typed/rightincopen/gen/RightIncrementalAsOfJoinHasherFloat.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/asofjoin/typed/rightincopen/gen/RightIncrementalAsOfJoinHasherInt.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/asofjoin/typed/rightincopen/gen/RightIncrementalAsOfJoinHasherLong.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/asofjoin/typed/rightincopen/gen/RightIncrementalAsOfJoinHasherObject.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/asofjoin/typed/rightincopen/gen/RightIncrementalAsOfJoinHasherShort.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/typed/TypedHasherFactory.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableAjTest.java
Labels: NoDocumentationNeeded

#3094 Bump grpc and boring ssl
  buildSrc/src/main/groovy/Classpaths.groovy
Labels: NoDocumentationNeeded, version-bump

#3095 Bump immutables to 2.9.2
  Util/util-immutables/build.gradle
  Util/util-immutables/src/main/java/io/deephaven/annotations/BuildableStyle.java
  Util/util-immutables/src/main/java/io/deephaven/annotations/SimpleStyle.java
  Util/util-immutables/src/main/java/io/deephaven/annotations/TupleStyle.java
  buildSrc/src/main/groovy/Classpaths.groovy
  qst/src/main/java/io/deephaven/annotations/LeafStyle.java
  qst/src/main/java/io/deephaven/annotations/NodeStyle.java
  table-api/src/main/java/io/deephaven/api/agg/spec/AggSpecEmptyBase.java
Labels: NoDocumentationNeeded, version-bump

#3053 Update README
  README.md
Labels: documentation, NoDocumentationNeeded

#3084 Wrap the input tables
  py/server/deephaven/__init__.py
  py/server/deephaven/column.py
  py/server/deephaven/plot/selectable_dataset.py
  py/server/deephaven/table_factory.py
  py/server/tests/test_table_factory.py
Labels: DocumentationNeeded, python-server-side

#2929 Generalize Python func vectorization
  Integrations/src/main/java/io/deephaven/integrations/python/PythonDeephavenSession.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/lang/QueryLanguageParser.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/AbstractConditionFilter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/ConditionFilter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/DhFormulaColumn.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/python/ArgumentsChunked.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/python/DeephavenCompatibleFunction.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/python/FillContextPython.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/python/FilterKernelPythonChunkedFunction.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/python/FormulaColumnPython.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/python/FormulaKernelPythonChunkedFunction.java
  engine/table/src/main/java/io/deephaven/engine/util/PyCallableWrapper.java
  engine/table/src/main/java/io/deephaven/engine/util/PythonScopeJpyImpl.java
  py/server/deephaven/dtypes.py
  py/server/deephaven/numpy.py
  py/server/deephaven/table.py
  py/server/tests/test_column.py
  py/server/tests/test_dtypes.py
  py/server/tests/test_numba_vectorized_column.py
  py/server/tests/test_numba_vectorized_filter.py
  py/server/tests/test_numpy.py
  py/server/tests/test_pandas.py
  py/server/tests/test_table.py
  py/server/tests/test_vectorization.py
Labels: DocumentationNeeded, python-server-side

#3090 Plumb whereIn/whereNotIn through gRPC
  Util/src/main/java/io/deephaven/util/locks/FunctionalLock.java
  engine/updategraph/src/main/java/io/deephaven/engine/updategraph/UpdateGraphLock.java
  go/internal/proto/table/table.pb.go
  go/internal/proto/table/table_grpc.pb.go
  java-client/session-dagger/src/test/java/io/deephaven/client/WhereInSessionTest.java
  java-client/session/src/main/java/io/deephaven/client/impl/BatchTableRequestBuilder.java
  proto/proto-backplane-grpc/src/main/java/io/deephaven/proto/util/OperationHelper.java
  proto/proto-backplane-grpc/src/main/proto/deephaven/proto/table.proto
  py/client/pydeephaven/proto/table_pb2.py
  py/client/pydeephaven/proto/table_pb2_grpc.py
  qst/src/main/java/io/deephaven/qst/TableAdapterImpl.java
  qst/src/main/java/io/deephaven/qst/table/LinkDescriber.java
  qst/src/main/java/io/deephaven/qst/table/ParentsVisitor.java
  qst/src/main/java/io/deephaven/qst/table/TableBase.java
  qst/src/main/java/io/deephaven/qst/table/TableSpec.java
  qst/src/main/java/io/deephaven/qst/table/TableVisitorGeneric.java
  qst/src/main/java/io/deephaven/qst/table/WhereInTable.java
  qst/src/main/java/io/deephaven/qst/table/WhereNotInTable.java
  server/src/main/java/io/deephaven/server/table/TableModule.java
  server/src/main/java/io/deephaven/server/table/TableServiceGrpcImpl.java
  server/src/main/java/io/deephaven/server/table/ops/GrpcErrorHelper.java
  server/src/main/java/io/deephaven/server/table/ops/WhereInGrpcImpl.java
  server/src/test/java/io/deephaven/server/table/ops/WhereInGrpcTest.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/table_pb/BatchTableRequest.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/table_pb/WhereInRequest.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/table_pb/batchtablerequest/Operation.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/table_pb/batchtablerequest/operation/OpCase.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/table_pb_service/TableService.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/table_pb_service/TableServiceClient.java
Labels: grpc, table api, NoDocumentationNeeded, qst

#3104 Use the PyCallableWrapper in formula code generation
  engine/table/src/main/java/io/deephaven/engine/table/impl/lang/QueryLanguageParser.java
Labels: NoDocumentationNeeded, python-server-side

#3102 Bump protoc base, regen proto
  docker/registry/protoc-base/gradle.properties
  go/internal/proto/application/application.pb.go
  go/internal/proto/application/application_grpc.pb.go
  go/internal/proto/config/config.pb.go
  go/internal/proto/config/config_grpc.pb.go
  go/internal/proto/console/console.pb.go
  go/internal/proto/console/console_grpc.pb.go
  go/internal/proto/inputtable/inputtable.pb.go
  go/internal/proto/inputtable/inputtable_grpc.pb.go
  go/internal/proto/object/object.pb.go
  go/internal/proto/object/object_grpc.pb.go
  go/internal/proto/partitionedtable/partitionedtable.pb.go
  go/internal/proto/partitionedtable/partitionedtable_grpc.pb.go
  go/internal/proto/session/session.pb.go
  go/internal/proto/session/session_grpc.pb.go
  go/internal/proto/storage/storage.pb.go
  go/internal/proto/storage/storage_grpc.pb.go
  go/internal/proto/table/table.pb.go
  go/internal/proto/table/table_grpc.pb.go
  go/internal/proto/ticket/ticket.pb.go
Labels: NoDocumentationNeeded, version-bump

#3107 Bump protobuf-java version
  buildSrc/src/main/groovy/Classpaths.groovy
Labels: security, NoDocumentationNeeded, version-bump

#3108 Bump jackson to 2.14.1
  buildSrc/src/main/groovy/Classpaths.groovy
Labels: security, NoDocumentationNeeded, version-bump

#3112 Fixed a small issue in a comment.
  redpanda/examples/python/kafka-produce-avro.py
Labels: NoDocumentationNeeded

#3062 Be more specific in py/client2/README.md.
  py/client2/README.md
Labels: NoDocumentationNeeded

#3113 Bump to gradle 7.6
  buildSrc/src/main/groovy/Docker.groovy
  buildSrc/src/main/groovy/io/deephaven/tools/docker/DiffTask.groovy
  gradle/wrapper/gradle-wrapper.properties
Labels: NoDocumentationNeeded, version-bump

#3117 Closes #3116: Add null check for rowSet
  engine/table/src/main/java/io/deephaven/engine/table/impl/locations/TableLocationStateHolder.java
Labels: NoDocumentationNeeded

#3118 Fix writing files when shorter than previous files
  server/src/main/java/io/deephaven/server/notebook/FilesystemStorageServiceGrpcImpl.java
Labels: bug, NoDocumentationNeeded

#3099 Add the convenience function garbage_collect()
  py/server/deephaven/__init__.py
  py/server/deephaven/_gc.py
  py/server/tests/test_gc.py
Labels: DocumentationNeeded, python-server-side

#3124 Add a GitHub action to check for release notes labels.
  .github/scripts/check-releasenotes-labels.sh
  .github/workflows/label-check-ci.yml
Labels: community, NoDocumentationNeeded, enhancement

#3110 Wrap the Table slice op
  py/server/deephaven/table.py
  py/server/tests/test_table.py
Labels: DocumentationNeeded, python-server-side
