Repository deephaven/deephaven-core, pull requests merged in 2022-05, with the labels that each got.

#2361 Merge
  cpp-client/README.md
  cpp-client/deephaven/client/CMakeLists.txt
  cpp-client/deephaven/client/build-dependencies.sh
  cpp-client/deephaven/client/flatbuf/deephaven/flatbuf/Barrage_generated.h
  cpp-client/deephaven/client/include/private/deephaven/client/highlevel/impl/table_handle_impl.h
  cpp-client/deephaven/client/include/private/deephaven/client/highlevel/impl/util.h
  cpp-client/deephaven/client/include/public/deephaven/client/highlevel/client.h
  cpp-client/deephaven/client/include/public/deephaven/client/highlevel/sad/chunk_filler.h
  cpp-client/deephaven/client/include/public/deephaven/client/highlevel/sad/chunk_maker.h
  cpp-client/deephaven/client/include/public/deephaven/client/highlevel/sad/sad_chunk.h
  cpp-client/deephaven/client/include/public/deephaven/client/highlevel/sad/sad_column_source.h
  cpp-client/deephaven/client/include/public/deephaven/client/highlevel/sad/sad_context.h
  cpp-client/deephaven/client/include/public/deephaven/client/highlevel/sad/sad_row_sequence.h
  cpp-client/deephaven/client/include/public/deephaven/client/highlevel/sad/sad_table.h
  cpp-client/deephaven/client/include/public/deephaven/client/highlevel/sad/sad_ticking_table.h
  cpp-client/deephaven/client/include/public/deephaven/client/highlevel/sad/sad_unwrapped_table.h
  cpp-client/deephaven/client/include/public/deephaven/client/highlevel/ticking.h
  cpp-client/deephaven/client/include/public/deephaven/client/utility/table_maker.h
  cpp-client/deephaven/client/proto/deephaven/proto/application.grpc.pb.cc
  cpp-client/deephaven/client/proto/deephaven/proto/application.grpc.pb.h
  cpp-client/deephaven/client/proto/deephaven/proto/application.pb.cc
  cpp-client/deephaven/client/proto/deephaven/proto/application.pb.h
  cpp-client/deephaven/client/proto/deephaven/proto/console.grpc.pb.cc
  cpp-client/deephaven/client/proto/deephaven/proto/console.grpc.pb.h
  cpp-client/deephaven/client/proto/deephaven/proto/console.pb.cc
  cpp-client/deephaven/client/proto/deephaven/proto/console.pb.h
  cpp-client/deephaven/client/proto/deephaven/proto/object.grpc.pb.cc
  cpp-client/deephaven/client/proto/deephaven/proto/object.grpc.pb.h
  cpp-client/deephaven/client/proto/deephaven/proto/object.pb.cc
  cpp-client/deephaven/client/proto/deephaven/proto/object.pb.h
  cpp-client/deephaven/client/proto/deephaven/proto/ticket.pb.cc
  cpp-client/deephaven/client/proto/deephaven/proto/ticket.pb.h
  cpp-client/deephaven/client/src/highlevel/client.cc
  cpp-client/deephaven/client/src/highlevel/impl/table_handle_impl.cc
  cpp-client/deephaven/client/src/highlevel/sad/chunk_filler.cc
  cpp-client/deephaven/client/src/highlevel/sad/chunk_maker.cc
  cpp-client/deephaven/client/src/highlevel/sad/sad_chunk.cc
  cpp-client/deephaven/client/src/highlevel/sad/sad_column_source.cc
  cpp-client/deephaven/client/src/highlevel/sad/sad_context.cc
  cpp-client/deephaven/client/src/highlevel/sad/sad_row_sequence.cc
  cpp-client/deephaven/client/src/highlevel/sad/sad_table.cc
  cpp-client/deephaven/client/src/highlevel/sad/sad_ticking_table.cc
  cpp-client/deephaven/client/src/highlevel/sad/sad_unwrapped_table.cc
  cpp-client/deephaven/client/src/highlevel/ticking.cc
  cpp-examples/do_exchange/CMakeLists.txt
  cpp-examples/do_exchange/main.cc
Labels: NoDocumentationNeeded

#2331 Static Select must flatten when using intermediate columns
  engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/AbstractFormulaColumn.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/MultiSourceFunctionalColumn.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/analyzers/DependencyLayerBase.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/analyzers/RedirectionLayer.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/analyzers/SelectAndViewAnalyzer.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/analyzers/SelectColumnLayer.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/analyzers/StaticFlattenLayer.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/RedirectedColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/RowRedirection.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/WrappedRowSetWritableRowRedirection.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableTest.java
Labels: bug, query engine, NoDocumentationNeeded

#2362 PythonDeephavenSession#getVariables should unwrap PyObjects
  engine/table/src/main/java/io/deephaven/engine/util/PythonDeephavenSession.java
Labels: bug, python, console, NoDocumentationNeeded

#2332 Use CanonicalName for preview column description
  engine/table/src/main/java/io/deephaven/engine/table/impl/preview/ColumnPreviewManager.java
Labels: clean up, NoDocumentationNeeded

#2366 Update Arrow, gRPC, flatbuffers libs to more recent versions.
  buildSrc/src/main/groovy/Classpaths.groovy
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/ParquetTableReadWriteTest.java
  proto/package-lock.json
  proto/package.json
  proto/proto-backplane-grpc/build.gradle
  py/client/build.gradle
  server/src/main/java/io/deephaven/server/arrow/ArrowFlightUtil.java
  server/src/main/java/io/deephaven/server/barrage/BarrageMessageProducer.java
  sphinx/sphinx.gradle
Labels: NoDocumentationNeeded

#2372 Add PropertiesUtil for easy loading properties from a file
  Util/src/main/java/io/deephaven/util/PropertiesUtil.java
  Util/src/test/java/io/deephaven/util/PropertiesUtilTest.java
Labels: NoDocumentationNeeded

#2374 Use CachedSchemaRegistryClient instead of manual REST.
  extensions/kafka/build.gradle
  extensions/kafka/src/main/java/io/deephaven/kafka/KafkaTools.java
Labels: kafka, NoDocumentationNeeded

#2376 Parquet cleanup to match DHE
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/ParquetFileReader.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/ParquetFileWriter.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/PlainBinaryChunkedWriter.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/PlainBooleanChunkedWriter.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/PlainDoubleChunkedWriter.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/PlainFixedLenChunkedWriter.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/PlainFloatChunkedWriter.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/PlainIntChunkedWriter.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/PlainLongChunkedWriter.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/Reader.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/RleIntChunkedWriter.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/BigDecimalParquetBytesCodec.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/MappedSchema.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/ParquetTableWriter.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/TypeInfos.java
  replication/static/src/main/java/io/deephaven/replicators/ReplicateParquetChunkedWriters.java
Labels: clean up, parquet, NoDocumentationNeeded

#2321 Simplify the table listener interface
  Integrations/src/main/java/io/deephaven/integrations/python/PythonListenerTableUpdateDataReader.java
  Integrations/src/main/java/io/deephaven/integrations/python/PythonReplayListenerAdapter.java
  Integrations/src/main/java/io/deephaven/integrations/python/PythonUtils.java
  engine/api/src/main/java/io/deephaven/engine/table/ModifiedColumnSet.java
  engine/api/src/test/java/io/deephaven/engine/table/ModifiedColumnSetTest.java
  py/server/deephaven/_ugp.py
  py/server/deephaven/numpy.py
  py/server/deephaven/pandas.py
  py/server/deephaven/table_listener.py
  py/server/tests/test_experiments.py
  py/server/tests/test_table_listener.py
  py/server/tests/testbase.py
Labels: DocumentationNeeded

#2382 Fix RspBitmapTimeDrivenTest.java to not take one hour by default.
  engine/rowset/src/test/java/io/deephaven/engine/rowset/impl/rsp/RspBitmapTimeDrivenTest.java
Labels: NoDocumentationNeeded

#2387 Add support for multiple worker threads in RspBitmapTimeDrivenTest.
  buildSrc/src/main/groovy/io.deephaven.java-test-conventions.gradle
  engine/rowset/src/test/java/io/deephaven/engine/rowset/impl/rsp/RspBitmapTimeDrivenTest.java
Labels: NoDocumentationNeeded

#2388 Update web to v0.12.0
  web/client-ui/Dockerfile
Labels: NoDocumentationNeeded, enhancement

#2384 Wrap LivenessScope for advanced resource cleanup
  engine/table/src/test/java/io/deephaven/engine/liveness/TestLiveness.java
  py/server/deephaven/liveness_scope.py
  py/server/tests/test_liveness.py
Labels: DocumentationNeeded, python-server-side

#2389 Disable jacoco, keeping our existing code behind a property.
  buildSrc/src/main/groovy/TestTools.groovy
  buildSrc/src/main/groovy/io.deephaven.java-test-conventions.gradle
  engine/rowset/src/test/java/io/deephaven/engine/rowset/impl/rsp/RspBitmapTimeDrivenTest.java
Labels: NoDocumentationNeeded

#2391 Bump registry images, add helper script
  buildSrc/src/main/groovy/Docker.groovy
  docker/registry/nltk-base/gradle.properties
  docker/registry/node/gradle.properties
  docker/registry/protoc-base/gradle.properties
  docker/registry/python-dev-base/gradle.properties
  docker/registry/python/gradle.properties
  docker/registry/pytorch-base/gradle.properties
  docker/registry/scripts/compare-amd64-arm64.sh
  docker/registry/server-base/gradle.properties
  docker/registry/sklearn-base/gradle.properties
  docker/registry/slim-base/gradle.properties
  docker/registry/tensorflow-base/gradle.properties
  docker/server/src/main/server-nltk/requirements.txt
  docker/server/src/main/server-pytorch/requirements.txt
  docker/server/src/main/server-sklearn/requirements.txt
  docker/server/src/main/server-tensorflow/requirements.txt
  docker/server/src/main/server/requirements.txt
Labels: NoDocumentationNeeded, version-bump

#2394 rename buildSrc/ project name to 'buildSrc'
  buildSrc/settings.gradle
Labels: clean up, NoDocumentationNeeded

#2395 Update help link in readme
  README.md
Labels: documentation, NoDocumentationNeeded

#2287 Support very large tables
  engine/chunk/src/main/java/io/deephaven/chunk/ByteChunkToOutputStreamAdapter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/remote/ConstructSnapshot.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/BarrageMessage.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableTest.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/VarBinaryChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/table/BarrageTable.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/BarrageStreamReader.java
  java-client/barrage-examples/src/main/java/io/deephaven/client/examples/SubscribeExampleBase.java
  java-client/flight-examples/src/main/java/io/deephaven/client/examples/GetDirectTable.java
  server/src/main/java/io/deephaven/server/arrow/ArrowFlightUtil.java
  server/src/main/java/io/deephaven/server/barrage/BarrageMessageProducer.java
  server/src/main/java/io/deephaven/server/barrage/BarrageStreamGenerator.java
Labels: feature request, barrage, NoDocumentationNeeded, barrage-wrkr2wrkr

#2354 fix table str
  py/server/deephaven/table.py
  py/server/tests/test_table.py
Labels: bug, NoDocumentationNeeded

#2406 Rewrite JS/GWT to use row counts (vs. row batches)
  web/client-api/src/main/java/io/deephaven/web/client/api/barrage/BarrageUtils.java
Labels: bug, NoDocumentationNeeded

#2421 README note about running on M1 Macs
  README.md
Labels: documentation, NoDocumentationNeeded

#2424 Fix slack message key, append useful info about the branch
  .github/workflows/nightly-check-ci.yml
Labels: ci, NoDocumentationNeeded

#2423 Exclude AddOnlyFirstOrLastChunkedOperator::addChunk
  buildSrc/src/main/groovy/io.deephaven.java-toolchain-conventions.gradle
Labels: bug, NoDocumentationNeeded

#2409 JS API fix in filter
  server/src/main/java/io/deephaven/server/table/ops/filter/FilterPrinter.java
  server/src/test/java/io/deephaven/server/table/ops/filter/FilterPrinterTest.java
Labels: bug, NoDocumentationNeeded

#2413 Wrap QueryLibrary
  py/server/deephaven/query_library.py
  py/server/tests/test_query_library.py
Labels: DocumentationNeeded, python-server-side

#2428 Close snapshots from BarrageTableResolver
  java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshot.java
  server/src/main/java/io/deephaven/server/uri/BarrageTableResolver.java
Labels: barrage, clean up, NoDocumentationNeeded

#2429 Correct plots not being rendered in Web UI
  server/src/main/java/io/deephaven/server/barrage/BarrageStreamGenerator.java
Labels: bug, NoDocumentationNeeded

#2437 Nightly builds should always use jacoco to work around cglib issue
  .github/workflows/nightly-check-ci.yml
Labels: build, test, ci, NoDocumentationNeeded

#2442 fixed dependency versions for protobuf and grpcio
  py/client/requirements.txt
Labels: NoDocumentationNeeded

#2445 Fix python plotting autogeneration method resolution order and type conversion for strings
  Generators/src/main/java/io/deephaven/plot/util/GeneratePyV2FigureAPI.java
  Generators/src/main/java/io/deephaven/pythonPreambles/plotV2.py
  py/server/deephaven/dtypes.py
  py/server/deephaven/plot/figure.py
Labels: bug, python, NoDocumentationNeeded, python-server-side

#2441 Remove cast to int when getting size from Range
  web/shared-beans/src/main/java/io/deephaven/web/shared/data/Range.java
  web/shared-beans/src/test/java/io/deephaven/web/shared/data/RangeSetTest.java
  web/shared-beans/src/test/java/io/deephaven/web/shared/data/RangeTest.java
Labels: bug, NoDocumentationNeeded

#2440 Migrate away from custom junit, jmock
  .github/workflows/nightly-check-ci.yml
  Base/build.gradle
  Base/src/test/java/io/deephaven/base/testing/BaseCachedJMockTestCase.java
  ClientSupport/src/main/java/io/deephaven/treetable/AbstractTreeSnapshotImpl.java
  ClientSupport/src/main/java/io/deephaven/treetable/RollupSnapshotImpl.java
  ClientSupport/src/main/java/io/deephaven/treetable/TreeSnapshotQuery.java
  ClientSupport/src/main/java/io/deephaven/treetable/TreeTableClientTableManager.java
  ClientSupport/src/main/java/io/deephaven/treetable/TreeTableSnapshotImpl.java
  ClientSupport/src/test/java/io/deephaven/treetable/TreeTableClientTableManagerTest.java
  Configuration/build.gradle
  buildSrc/src/main/groovy/io.deephaven.java-classpath-conventions.gradle
  test-libs/jmock-wall-2.7-wall.1.jar
  test-libs/junit-wall-4.11.jar
Labels: build, test, ci, NoDocumentationNeeded

#2443 Update web version v0.13.0
  web/client-ui/Dockerfile
Labels: NoDocumentationNeeded

#2385 JDBC implementation of ResultSet -> Table
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/BarragePerformanceLog.java
  extensions/jdbc/build.gradle
  extensions/jdbc/gradle.properties
  extensions/jdbc/src/main/java/io/deephaven/jdbc/JdbcToTableAdapter.java
  extensions/jdbc/src/main/java/io/deephaven/jdbc/JdbcTypeMapper.java
  extensions/jdbc/src/main/java/io/deephaven/jdbc/JdbcTypeMapperException.java
  extensions/jdbc/src/main/java/io/deephaven/jdbc/util/ArrayParser.java
  extensions/jdbc/src/test/java/io/deephaven/jdbc/JdbcToTableAdapterTest.java
  server/build.gradle
  settings.gradle
Labels: mvp-odbc, DocumentationNeeded
