Repository deephaven/deephaven-core, pull requests merged in 2022-12, with the labels that each got.

#3091 Be explicit about GC application
  plugin/gc-app/build.gradle
  plugin/gc-app/src/main/java/io/deephaven/app/GcApplication.java
  server/build.gradle
  server/src/main/java/io/deephaven/server/appmode/ApplicationsModule.java
  server/src/main/java/io/deephaven/server/runner/DeephavenApiServerModule.java
Labels: NoDocumentationNeeded, application mode

#3129 Add a reference to the descriptor when creating a contains filter
  web/client-api/src/main/java/io/deephaven/web/client/api/filter/FilterValue.java
Labels: bug, NoDocumentationNeeded

#3120 Support column swaps in RedefinableTable
  engine/table/src/main/java/io/deephaven/engine/table/impl/RedefinableTable.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/TestParquetTools.java
Labels: bug, query engine, NoDocumentationNeeded

#2988 Remove OHLC charttype, XY will be used instead.
  Plot/src/main/java/io/deephaven/plot/AxesImpl.java
  Plot/src/main/java/io/deephaven/plot/ChartType.java
  go/internal/proto/console/console.pb.go
  proto/proto-backplane-grpc/src/main/proto/deephaven/proto/console.proto
  py/client/pydeephaven/proto/console_pb2.py
  web/client-api/src/main/java/io/deephaven/web/client/api/widget/plot/enums/JsChartType.java
Labels: plotting, NoDocumentationNeeded

#3122 DeferredViewTable's filter ordering logic needs to respect view side effects
  engine/table/src/main/java/io/deephaven/engine/table/impl/DeferredViewTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/AbstractConditionFilter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/ConditionFilter.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/PartitionedTableTest.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/TestParquetTools.java
Labels: bug, query engine, NoDocumentationNeeded, ReleaseNotesNeeded

#3057 Add dh-defaults.vmoptions file
  buildSrc/src/main/groovy/io.deephaven.java-toolchain-conventions.gradle
  buildSrc/src/main/resources/unixStartScript.txt
  docker/server-jetty/src/main/docker/Dockerfile
  docker/server-slim/src/main/docker/Dockerfile
  docker/server/src/main/docker/Dockerfile
  py/embedded-server/deephaven_server/start_jvm.py
  py/embedded-server/java-runtime/build.gradle
  server/jetty-app/build.gradle
  server/netty-app/build.gradle
Labels: configuration, DocumentationNeeded, ReleaseNotesNeeded

#3132 Bump base images to pick up jedi dependency
  docker/registry/all-ai-base/gradle.properties
  docker/registry/go/gradle.properties
  docker/registry/nltk-base/gradle.properties
  docker/registry/node/gradle.properties
  docker/registry/python/gradle.properties
  docker/registry/pytorch-base/gradle.properties
  docker/registry/server-base/gradle.properties
  docker/registry/sklearn-base/gradle.properties
  docker/registry/slim-base/gradle.properties
  docker/registry/tensorflow-base/gradle.properties
  docker/server-jetty/src/main/server-jetty/requirements.txt
  docker/server/src/main/server-all-ai-netty/requirements.txt
  docker/server/src/main/server-netty/requirements.txt
  docker/server/src/main/server-nltk-netty/requirements.txt
  docker/server/src/main/server-pytorch-netty/requirements.txt
  docker/server/src/main/server-sklearn-netty/requirements.txt
  docker/server/src/main/server-tensorflow-netty/requirements.txt
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#3136 Update Web version to v0.22.2
  web/client-ui/Dockerfile
Labels: web-client-ui, NoDocumentationNeeded, enhancement, ReleaseNotesNeeded

#3098 Improve DebugAwareFunctionalLock
  engine/updategraph/src/main/java/io/deephaven/engine/updategraph/UpdateGraphLock.java
  engine/updategraph/src/main/java/io/deephaven/engine/updategraph/UpdateGraphProcessor.java
Labels: NoDocumentationNeeded

#3126 Improve BigInteger handling in Parquet files (Closes #3125)
  engine/table/src/main/java/io/deephaven/engine/table/impl/CodecLookup.java
  engine/table/src/main/java/io/deephaven/engine/util/BigDecimalUtils.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestCodecColumns.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/BigIntegerParquetBytesCodec.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/ParquetSchemaReader.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/ParquetTableWriter.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/TypeInfos.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/location/ParquetColumnLocation.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/metadata/TableInfo.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/ParquetTableReadWriteTest.java
Labels: parquet, NoDocumentationNeeded, ReleaseNotesNeeded

#3138 Move completer to deephaven_internal
  py/server/deephaven_internal/auto_completer/__init__.py
  py/server/deephaven_internal/auto_completer/_completer.py
  server/src/main/java/io/deephaven/server/console/ConsoleServiceGrpcImpl.java
Labels: clean up, NoDocumentationNeeded, NoReleaseNotesNeeded

#3139 Add configuration to disable autocomplete
  server/src/main/java/io/deephaven/server/console/ConsoleServiceGrpcImpl.java
Labels: DocumentationNeeded, ReleaseNotesNeeded

#3140 Add dependency on autocomplete feature for PyPi deephaven-server
  py/embedded-server/setup.py
Labels: NoDocumentationNeeded, dependencies, NoReleaseNotesNeeded

#3143 TableReplayer fix
  engine/table/src/main/java/io/deephaven/engine/table/impl/replay/ReplayTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/replay/Replayer.java
Labels: bug, query engine, java, NoDocumentationNeeded, NoReleaseNotesNeeded

#3145 Cleanup DateTimeFormatters code-style
  engine/time/src/main/java/io/deephaven/time/DateTimeFormatters.java
Labels: clean up, NoDocumentationNeeded, NoReleaseNotesNeeded

#3123 Improve Jetty/gRPC shutdown
  grpc-java/grpc-servlet-websocket-jakarta/src/main/java/io/grpc/servlet/web/websocket/MultiplexedWebSocketServerStream.java
  py/embedded-server/java-runtime/src/main/java/io/deephaven/python/server/EmbeddedServer.java
  server/jetty/src/main/java/io/deephaven/server/jetty/JettyBackedGrpcServer.java
  server/jetty/src/main/java/io/deephaven/server/jetty/JettyServerComponent.java
  server/jetty/src/main/java/io/deephaven/server/jetty/JettyServerModule.java
  server/jetty/src/main/java/io/deephaven/server/jetty/WebsocketFactory.java
  server/netty/src/main/java/io/deephaven/server/netty/NettyServerComponent.java
  server/src/main/java/io/deephaven/server/console/ConsoleServiceGrpcImpl.java
  server/src/main/java/io/deephaven/server/console/completer/JavaAutoCompleteObserver.java
  server/src/main/java/io/deephaven/server/console/completer/PythonAutoCompleteObserver.java
  server/src/main/java/io/deephaven/server/healthcheck/HealthCheckModule.java
  server/src/main/java/io/deephaven/server/runner/DeephavenApiServer.java
  server/src/main/java/io/deephaven/server/runner/DeephavenApiServerModule.java
  server/src/main/java/io/deephaven/server/runner/GrpcServer.java
  web/client-api/src/main/java/io/deephaven/web/client/api/WorkerConnection.java
  web/client-api/src/main/java/io/deephaven/web/client/api/grpc/MultiplexedWebsocketTransport.java
Labels: jsapi, grpc, NoDocumentationNeeded, jetty, ReleaseNotesNeeded

#3150 Correct a merge conflict from #3123
  server/src/main/java/io/deephaven/server/console/ConsoleServiceGrpcImpl.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#3142 Improve performance for ConstituentDependency, tighter double-notification testing, MergeListener paranoia
  Base/src/main/java/io/deephaven/base/reference/SwappableDelegatingReference.java
  ClientSupport/src/main/java/io/deephaven/clientsupport/plotdownsampling/RunChartDownsample.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/BaseTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/ConstituentDependency.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/HierarchicalTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/InstrumentedTableUpdateListenerAdapter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/MergedListener.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/NotificationStepReceiver.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/ReverseLookupListener.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/ShiftObliviousSwapListener.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/SourceTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/StreamTableTools.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/SwapListener.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/SwapListenerBase.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/TreeTableFilter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/ChunkedOperatorAggregationHelper.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/locations/TableLocation.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/locations/impl/TableLocationSubscriptionBuffer.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/locations/impl/TableLocationUpdateSubscriptionBuffer.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/remote/ConstructSnapshot.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/replay/Replayer.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/WhereFilter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/RegionedColumnSourceWithDictionary.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/ring/AddsToRingsListener.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/ring/RingTableTools.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/SyncTableFilter.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/PartitionedTableTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestListenerFailure.java
  java-client/barrage-examples/src/main/java/io/deephaven/client/examples/SubscribeExampleBase.java
  java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java
  server/src/main/java/io/deephaven/server/barrage/BarrageMessageProducer.java
  server/src/main/java/io/deephaven/server/table/ExportedTableUpdateListener.java
Labels: query engine, NoDocumentationNeeded, user-reported, NoReleaseNotesNeeded

#3152 All project types should declare maven repositories
  buildSrc/src/main/groovy/io.deephaven.common-conventions.gradle
  buildSrc/src/main/groovy/io.deephaven.java-common-conventions.gradle
  buildSrc/src/main/groovy/io.deephaven.repository-conventions.gradle
Labels: build, NoDocumentationNeeded, NoReleaseNotesNeeded

#3154 Add extra safety checks to ensure the configuration types are known
  buildSrc/src/main/groovy/io/deephaven/project/util/JavaDependencies.groovy
Labels: test, NoDocumentationNeeded, NoReleaseNotesNeeded

#3155 Close the inner context of a RegionedContextHolder if it was set
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/RegionContextHolder.java
Labels: query engine, NoDocumentationNeeded, NoReleaseNotesNeeded

#3160 Bumps commons-text to 1.10.0
  buildSrc/src/main/groovy/Classpaths.groovy
  buildSrc/src/main/groovy/io.deephaven.java-classpath-conventions.gradle
Labels: security, NoDocumentationNeeded, version-bump, NoReleaseNotesNeeded

#3165 Fix ServiceAuthWiring logging of full method name
  authorization/src/main/java/io/deephaven/auth/ServiceAuthWiring.java
Labels: logging, clean up, NoDocumentationNeeded, NoReleaseNotesNeeded

#3161 Take buildTableCreationResponse out of safelyExecutes
  server/src/main/java/io/deephaven/server/partitionedtable/PartitionedTableServiceGrpcImpl.java
  server/src/main/java/io/deephaven/server/table/TableServiceGrpcImpl.java
Labels: clean up, NoDocumentationNeeded, NoReleaseNotesNeeded

#3169 Safely close autocomplete streams on the server to avoid logspam
  server/src/main/java/io/deephaven/server/console/ConsoleServiceGrpcImpl.java
  server/src/main/java/io/deephaven/server/console/completer/JavaAutoCompleteObserver.java
  server/src/main/java/io/deephaven/server/console/completer/PythonAutoCompleteObserver.java
Labels: grpc, autocomplete, NoDocumentationNeeded, ReleaseNotesNeeded

#3173 Associate java autocomplete data with the session, rather than stream
  server/src/main/java/io/deephaven/server/console/completer/JavaAutoCompleteObserver.java
Labels: grpc, autocomplete, NoDocumentationNeeded, groovy, ReleaseNotesNeeded

#3171 Cut table size in half for parquet tests to decrease heap usage
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/ParquetTableReadWriteTest.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#3179 Correct handling for checkInitiateOperation propagation to parallel jobs, fixing parallel partitioned transform
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/analyzers/SelectColumnLayer.java
Labels: bug, query engine, NoDocumentationNeeded, partitioned_tables, ReleaseNotesNeeded

#3181 SelectColumnLayer to only allow cross-column parallelization if its SelectColumn is stateless
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/analyzers/SelectColumnLayer.java
Labels: bug, query engine, NoDocumentationNeeded, ReleaseNotesNeeded

#3176 Fix jedi SAFE mode
  py/server/deephaven_internal/auto_completer/_completer.py
Labels: bug, autocomplete, NoDocumentationNeeded, ReleaseNotesNeeded

#3183 Fix incorrect Table casts of PartitionTables in PartitionedTableService
  server/src/main/java/io/deephaven/server/partitionedtable/PartitionedTableServiceGrpcImpl.java
Labels: bug, NoDocumentationNeeded, NoReleaseNotesNeeded

#3185 Bump commons-compress to 1.22
  buildSrc/src/main/groovy/io.deephaven.java-classpath-conventions.gradle
Labels: NoDocumentationNeeded, version-bump, NoReleaseNotesNeeded

#3188 Remove httpClient configuration
  buildSrc/src/main/groovy/io.deephaven.java-classpath-conventions.gradle
Labels: clean up, NoDocumentationNeeded, NoReleaseNotesNeeded

#3190 Bump woodstox-core to 6.4.0
  ParquetHadoop/build.gradle
Labels: security, NoDocumentationNeeded, version-bump, NoReleaseNotesNeeded

#3191 Bump uuid-creator to 5.2.0
  engine/context/build.gradle
  engine/table/build.gradle
  server/build.gradle
Labels: NoDocumentationNeeded, version-bump, NoReleaseNotesNeeded

#3193 Bump confluent platform to 7.3.0
  extensions/kafka/build.gradle
Labels: NoDocumentationNeeded, version-bump, NoReleaseNotesNeeded

#3194 Bump sslcontext to 7.4.8
  buildSrc/src/main/groovy/Classpaths.groovy
Labels: NoDocumentationNeeded, version-bump, NoReleaseNotesNeeded

#3189 Bump slf4j to 2.0.6 and logback to 1.4.5
  buildSrc/src/main/groovy/Classpaths.groovy
Labels: NoDocumentationNeeded, version-bump, NoReleaseNotesNeeded

#3192 Bump t-digest to 3.3
  engine/table/build.gradle
Labels: NoDocumentationNeeded, version-bump, NoReleaseNotesNeeded

#3186 Bump commons-lang3 to 3.12.0
  buildSrc/src/main/groovy/io.deephaven.java-classpath-conventions.gradle
Labels: NoDocumentationNeeded, version-bump, NoReleaseNotesNeeded

#3196 Bump groovy to 3.0.13
  buildSrc/src/main/groovy/Classpaths.groovy
Labels: NoDocumentationNeeded, version-bump, NoReleaseNotesNeeded

#3201 Bump deephaven-csv to 0.9.0
  extensions/csv/build.gradle
Labels: NoDocumentationNeeded, csv, version-bump, NoReleaseNotesNeeded

#3170 Shut down LogBuffer listeners when the client stream has closed
  server/src/main/java/io/deephaven/server/console/ConsoleServiceGrpcImpl.java
  server/src/main/java/io/deephaven/server/session/SessionCloseableObserver.java
  server/src/main/java/io/deephaven/server/session/SessionService.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#3205 Add additional RMSE logic to testTDigestMulti
  engine/table/build.gradle
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableAggregationTest.java
Labels: test, NoDocumentationNeeded, version-bump, NoReleaseNotesNeeded

#3210 Fix LivenessScope for SelectColumnLayer.doApplyUpdate, in order to ensure reference counting for parallel update in transform use cases
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/analyzers/SelectColumnLayer.java
Labels: bug, query engine, NoDocumentationNeeded, partitioned_tables, ReleaseNotesNeeded

#3211 Modify OA `doRehash()` functions to properly debit `rehashCredits`
  engine/table/src/main/java/io/deephaven/engine/table/impl/asofjoin/RightIncrementalAsOfJoinStateManagerTypedBase.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/naturaljoin/IncrementalNaturalJoinStateManagerTypedBase.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/hashing/UpdateByStateManagerTypedBase.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableNaturalJoinTest.java
Labels: bug, clean up, NoDocumentationNeeded, NoReleaseNotesNeeded

#3218 Bump base images
  docker/registry/all-ai-base/gradle.properties
  docker/registry/cpp-client-base/gradle.properties
  docker/registry/go/gradle.properties
  docker/registry/nltk-base/gradle.properties
  docker/registry/node/gradle.properties
  docker/registry/protoc-base/gradle.properties
  docker/registry/python/gradle.properties
  docker/registry/pytorch-base/gradle.properties
  docker/registry/server-base/gradle.properties
  docker/registry/sklearn-base/gradle.properties
  docker/registry/slim-base/gradle.properties
  docker/registry/tensorflow-base/gradle.properties
  docker/server/src/main/server-all-ai-netty/requirements.txt
  docker/server/src/main/server-pytorch-netty/requirements.txt
  docker/server/src/main/server-tensorflow-netty/requirements.txt
Labels: NoDocumentationNeeded, version-bump, NoReleaseNotesNeeded

#3215 Update Web version to v0.23.0
  web/client-ui/Dockerfile
Labels: NoDocumentationNeeded, enhancement, ReleaseNotesNeeded

#3222 Port DH-11271: Rearchitect Static Cross Join to Deal with Rehash More Efficiently
  engine/table/src/main/java/io/deephaven/engine/table/impl/CrossJoinHelper.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/StaticChunkedCrossJoinStateManager.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/sources/TestObjectArraySource.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/ssa/TestLongSegmentedSortedArray.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/ssms/TestObjectSegmentedSortedMultiset.java
Labels: query engine, NoDocumentationNeeded, port, ReleaseNotesNeeded

#3224 Mark ComboAggregate as deprecated
  go/internal/proto/table/table.pb.go
  go/internal/proto/table/table_grpc.pb.go
  proto/proto-backplane-grpc/src/main/proto/deephaven/proto/table.proto
  py/client/pydeephaven/proto/table_pb2.py
  py/client/pydeephaven/proto/table_pb2_grpc.py
Labels: documentation, NoDocumentationNeeded, NoReleaseNotesNeeded

#3226 Port DH-11736: Be more Parsimonious with Chunks during Cross Join
  engine/table/src/main/java/io/deephaven/engine/table/impl/CrossJoinModifiedSlotTracker.java
Labels: query engine, NoDocumentationNeeded, port, ReleaseNotesNeeded

#3225 Barrage: Extract Parsing Utilities for IPC Style Parsing
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/BarrageMessage.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/BarrageStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/BarrageStreamGeneratorImpl.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/ArrowToTableConverter.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/BarrageUtil.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/TableToArrowConverter.java
  extensions/barrage/src/test/java/io/deephaven/extensions/barrage/BarrageStreamGeneratorTest.java
  java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshotImpl.java
  proto/proto-backplane-grpc-flight/src/main/java/io/deephaven/proto/flight/util/MessageHelper.java
  py/server/tests/data/crypto_trades.parquet
  server/src/main/java/io/deephaven/server/appmode/ApplicationServiceGrpcImpl.java
  server/src/main/java/io/deephaven/server/arrow/ArrowFlightUtil.java
  server/src/main/java/io/deephaven/server/arrow/ArrowModule.java
  server/src/main/java/io/deephaven/server/arrow/FlightServiceGrpcImpl.java
  server/src/main/java/io/deephaven/server/auth/AuthContextModule.java
  server/src/main/java/io/deephaven/server/barrage/BarrageMessageProducer.java
  server/src/main/java/io/deephaven/server/runner/DeephavenApiServerModule.java
  server/src/main/java/io/deephaven/server/session/SessionState.java
  server/src/test/java/io/deephaven/server/barrage/BarrageMessageRoundTripTest.java
  server/src/test/java/io/deephaven/server/barrage/BarrageStreamTableTest.java
  web/client-api/src/main/java/io/deephaven/web/client/api/JsPartitionedTable.java
  web/client-api/src/main/java/io/deephaven/web/client/api/WorkerConnection.java
  web/client-api/src/main/java/io/deephaven/web/client/api/barrage/WebBarrageUtils.java
  web/client-api/src/main/java/io/deephaven/web/client/api/subscription/TableViewportSubscription.java
  web/client-api/src/main/java/io/deephaven/web/client/state/ClientTableState.java
Labels: barrage, clean up, NoDocumentationNeeded, NoReleaseNotesNeeded

#3234 Port DH-11635: Correct notification queue race in dependency satisfaction
  engine/table/src/main/java/io/deephaven/engine/table/impl/MergedListener.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/SelectOrUpdateListener.java
  engine/updategraph/src/main/java/io/deephaven/engine/updategraph/UpdateGraphProcessor.java
Labels: query engine, NoDocumentationNeeded, port, NoReleaseNotesNeeded

#3250 Update web version to v0.24.0
  web/client-ui/Dockerfile
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded
