Repository deephaven/deephaven-core, pull requests merged in 2022-01, with the labels that each got.

#1752 Unify prop files for builds and production
  configs/dh-defaults.prop
  configs/grpc-api.prop
  docker/server-slim/src/main/docker/image-bootstrap.properties
  docker/server/src/main/configure/image-bootstrap.properties
  pyintegration/deephaven2/_utils/bootstrap.py
  server/jetty/src/main/resources/bootstrap.properties
  server/jetty/src/main/resources/grpc-api-native.prop
  server/netty/src/main/resources/bootstrap.properties
  server/netty/src/main/resources/grpc-api-native.prop
Labels: configuration, NoDocumentationNeeded

#1794 Create a new array rather than slicing a typedarray to support nulls
  web/client-api/src/main/java/io/deephaven/web/client/api/subscription/ViewportData.java
Labels: jsapi, NoDocumentationNeeded

#1798 Do not use the "week year" when year is expected
  Util/src/main/java/io/deephaven/util/HeapDump.java
Labels: bug, NoDocumentationNeeded

#1749 Port Parallel Select Implementation from Deephaven Enterprise.
  engine/table/src/main/java/io/deephaven/engine/table/impl/EvenlyDividedTableMap.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/InstrumentedTableListenerBase.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/InstrumentedTableUpdateListenerAdapter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/InstrumentedUpdateSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/LocalTableMap.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/MergedListener.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/OperationInitializationThreadPool.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/SelectOrUpdateListener.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/ShiftObliviousInstrumentedListenerAdapter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/TableMapTransformThreadPool.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/TimeTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/AggregationContext.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/perf/BasePerformanceEntry.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/perf/PerformanceEntry.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/perf/QueryPerformanceNugget.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/perf/QueryPerformanceRecorder.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/perf/UpdatePerformanceTracker.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/analyzers/BaseLayer.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/analyzers/DependencyLayerBase.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/analyzers/PreserveColumnLayer.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/analyzers/RedirectionLayer.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/analyzers/SelectAndViewAnalyzer.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/analyzers/SelectColumnLayer.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/analyzers/ViewColumnLayer.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/AsyncErrorLogger.java
  engine/table/src/main/java/io/deephaven/engine/tablelogger/UpdatePerformanceLogLogger.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableSelectUpdateTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/SparseSelectTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestPartitionAwareSourceTable.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/table/BarrageTable.java
Labels: query engine, DocumentationNeeded

#1795 Replace Docker references from grpc-api to server
  .github/workflows/build-ci.yml
  containers/groovy-examples/docker-compose.yml
  containers/groovy/docker-compose.yml
  containers/python-examples-redpanda/docker-compose.yml
  containers/python-examples/docker-compose.yml
  containers/python/docker-compose.yml
  docker-compose-common.yml
  docker-compose.yml
  redpanda-apicurio/docker-compose.yml
  redpanda/docker-compose.yml
Labels: clean up, docker, NoDocumentationNeeded

#1797 Backport bench tweaks for RowSetGetFindBench and gradle setup for Benchmarks.
  BenchmarkSupport/src/main/java/io/deephaven/benchmarking/runner/EnvUtils.java
  engine/benchmark/build.gradle
  engine/benchmark/src/benchmark/java/io/deephaven/benchmark/engine/util/RowSetGetFindBench.java
Labels: NoDocumentationNeeded

#1801 Fix redpanda docker-compose.yml related files
  redpanda-apicurio/.env
  redpanda-apicurio/docker-compose.yml
  redpanda-apicurio/examples/post-share-price-schema.sh
  redpanda-apicurio/examples/python/kafka-produce-avro.py
  redpanda/.env
  redpanda/docker-compose.yml
Labels: NoDocumentationNeeded

#1802 Fix remaining references to 'grpc-api'. Add "connect-check" java-client-session-examples command
  .github/workflows/build-ci.yml
  envoy/contents/envoy.yaml
  java-client/session-examples/build.gradle
  java-client/session-examples/src/main/java/io/deephaven/client/examples/ConnectCheck.java
Labels: bug, NoDocumentationNeeded

#1631 Refactored away TableTools module, fixes #1553
  pyintegration/deephaven2/__init__.py
  pyintegration/deephaven2/_utils/bootstrap.py
  pyintegration/deephaven2/column.py
  pyintegration/deephaven2/constants.py
  pyintegration/deephaven2/csv.py
  pyintegration/deephaven2/dtypes.py
  pyintegration/deephaven2/table.py
  pyintegration/deephaven2/table_factory.py
  pyintegration/tests/__init__.py
  pyintegration/tests/test_column.py
  pyintegration/tests/test_constants.py
  pyintegration/tests/test_dtypes.py
  pyintegration/tests/test_table.py
  pyintegration/tests/test_table_factory.py
  pyintegration/tests/test_type.py
Labels: python, NoDocumentationNeeded, python-server-side

#1813 Added AggFormula in io.deephaven.api.agg.Aggregation, fixes #1699
  pyintegration/deephaven2/agg.py
  pyintegration/tests/test_table.py
  table-api/src/main/java/io/deephaven/api/agg/Aggregation.java
Labels: NoDocumentationNeeded, python-server-side

#1799 Use the same version of barrage in all parts of the project
  proto/proto-backplane-grpc/build.gradle
Labels: NoDocumentationNeeded

#1814 Support unions with null in Avro nested record traversals; BigDecimals via ByteBuffer.
  extensions/kafka/src/main/java/io/deephaven/kafka/ingest/GenericRecordBigDecimalFieldCopier.java
  extensions/kafka/src/main/java/io/deephaven/kafka/ingest/GenericRecordUtil.java
Labels: kafka, NoDocumentationNeeded

#1811 Add commented out debugging settings to docker-compose-common, to ease out turning debugging on.
  docker-compose-common.yml
Labels: NoDocumentationNeeded

#1817 Raise the gRPC max payload limit to 100mb
  server/jetty/src/main/java/io/deephaven/server/jetty/JettyMain.java
  server/jetty/src/main/java/io/deephaven/server/jetty/JettyServerModule.java
  server/netty/src/main/java/io/deephaven/server/netty/NettyMain.java
  server/netty/src/main/java/io/deephaven/server/netty/NettyServerModule.java
  server/src/main/java/io/deephaven/server/runner/DeephavenApiServerComponent.java
  server/src/main/java/io/deephaven/server/runner/DeephavenApiServerModule.java
  server/test/src/main/java/io/deephaven/server/test/FlightMessageRoundTripTest.java
Labels: grpc, NoDocumentationNeeded

#1821 Fix chunk leak in ReAvg and ReVar context.
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/ReAvgVarOrderingContext.java
Labels: bug, query engine, NoDocumentationNeeded

#1823 Update web to v0.9.0
  web/client-ui/Dockerfile
Labels: feature request, NoDocumentationNeeded

#1824 Add AutoService
  Configuration/build.gradle
  Configuration/src/main/java/io/deephaven/configuration/PropertyInputStreamLoaderTraditional.java
  Configuration/src/main/resources/META-INF/services/io.deephaven.configuration.PropertyInputStreamLoader
  Plot/Plot.gradle
  Plot/src/main/java/io/deephaven/engine/util/PerformanceScript.java
  Plot/src/main/java/io/deephaven/plot/PlottingScript.java
  Plot/src/main/resources/META-INF/services/io.deephaven.engine.util.GroovyDeephavenSession$InitScript
  buildSrc/src/main/groovy/Classpaths.groovy
  engine/table/build.gradle
  engine/table/src/main/java/io/deephaven/engine/table/impl/TableCreatorImpl.java
  engine/table/src/main/java/io/deephaven/engine/table/lang/impl/QueryLibraryImportsConfiguration.java
  engine/table/src/main/java/io/deephaven/engine/table/lang/impl/QueryLibraryImportsDefaults.java
  engine/table/src/main/java/io/deephaven/engine/util/GroovyDeephavenSession.java
  engine/table/src/main/resources/META-INF/services/io.deephaven.engine.table.TableFactory$TableCreatorProvider
  engine/table/src/main/resources/META-INF/services/io.deephaven.engine.table.lang.QueryLibraryImports
  engine/table/src/main/resources/META-INF/services/io.deephaven.engine.util.GroovyDeephavenSession$InitScript
  engine/tuplesource/build.gradle
  engine/tuplesource/src/main/java/io/deephaven/engine/table/impl/tuplesource/TupleSourceCreatorImpl.java
  engine/tuplesource/src/main/resources/META-INF/services/io.deephaven.engine.table.impl.TupleSourceFactory$TupleSourceCreatorProvider
  extensions/classgraph/build.gradle
  extensions/classgraph/src/main/java/io/deephaven/extensions/ClassGraphExtension.java
  extensions/classgraph/src/main/resources/META-INF/services/io.deephaven.engine.table.lang.QueryLibraryImports
  extensions/classgraph/src/main/resources/META-INF/services/io.deephaven.engine.util.GroovyDeephavenSession$InitScript
  extensions/suanshu/build.gradle
  extensions/suanshu/src/main/java/io/deephaven/numerics/suanshu/SuanShuIntegration.java
  extensions/suanshu/src/main/resources/META-INF/services/io.deephaven.engine.table.lang.QueryLibraryImports
  extensions/suanshu/src/main/resources/META-INF/services/io.deephaven.engine.util.GroovyDeephavenSession$InitScript
  fishconfig-local/build.gradle
  fishconfig-local/src/main/java/io/deephaven/fishconfig/PropertyInputStreamLoaderResourcesOnly.java
  fishconfig-local/src/main/resources/META-INF/services/io.deephaven.configuration.PropertyInputStreamLoader
  java-client/flight/build.gradle
  java-client/flight/src/main/java/io/deephaven/client/impl/SchemaBytesImpl.java
  java-client/flight/src/main/resources/META-INF/services/io.deephaven.client.impl.SchemaBytes
  log-factory/sinks/log-to-file/build.gradle
  log-factory/sinks/log-to-file/src/main/java/io/deephaven/internal/log/LoggerFactoryFile.java
  log-factory/sinks/log-to-file/src/main/resources/META-INF/services/io.deephaven.internal.log.LoggerFactory
  log-factory/sinks/log-to-logbuffer/build.gradle
  log-factory/sinks/log-to-logbuffer/src/main/java/io/deephaven/internal/log/LogToLogBuffer.java
  log-factory/sinks/log-to-logbuffer/src/main/resources/META-INF/services/io.deephaven.internal.log.InitSink
  log-factory/sinks/log-to-slf4j/build.gradle
  log-factory/sinks/log-to-slf4j/src/main/java/io/deephaven/internal/log/LoggerFactorySlf4j.java
  log-factory/sinks/log-to-slf4j/src/main/resources/META-INF/services/io.deephaven.internal.log.LoggerFactory
  log-factory/sinks/log-to-stream/build.gradle
  log-factory/sinks/log-to-stream/src/main/java/io/deephaven/internal/log/LoggerFactoryStream.java
  log-factory/sinks/log-to-stream/src/main/resources/META-INF/services/io.deephaven.internal.log.LoggerFactory
  log-factory/sources/slf4j-to-log/build.gradle
  log-factory/sources/slf4j-to-log/src/main/java/io/deephaven/internal/DeephavenLoggerServiceProvider.java
  log-factory/sources/slf4j-to-log/src/main/resources/META-INF/services/org.slf4j.spi.SLF4JServiceProvider
  open-api/lang-parser/src/main/resources/META-INF/services/io.deephaven.lang.parse.api.CompletionParseService
Labels: build, clean up, NoDocumentationNeeded

#1819 Initial CDC support for DHC
  Integrations/python/deephaven/ConsumeCdc.py
  Integrations/python/deephaven/ConsumeKafka.py
  debezium-demo/.env
  debezium-demo/README.md
  debezium-demo/docker-compose.yml
  debezium-demo/loadgen/Dockerfile
  debezium-demo/loadgen/docker-entrypoint.sh
  debezium-demo/loadgen/generate_load.py
  docker-compose-common.yml
  engine/table/src/main/java/io/deephaven/engine/table/impl/StreamTableTools.java
  extensions/kafka/src/main/java/io/deephaven/kafka/CdcTools.java
  extensions/kafka/src/main/java/io/deephaven/kafka/KafkaTools.java
  extensions/kafka/src/test/java/io/deephaven/kafka/KafkaToolsTest.java
Labels: kafka, NoDocumentationNeeded

#1805 Mark grpc dependencies as api
  java-client/example-utilities/build.gradle
  java-client/session-dagger/build.gradle
  java-client/session/build.gradle
  proto/proto-backplane-grpc/build.gradle
Labels: NoDocumentationNeeded

#1772 gRPC websocket streams should close sanely
  grpc-java/grpc-servlet-websocket-jakarta/src/main/java/io/grpc/servlet/web/websocket/WebSocketServerStream.java
  grpc-java/grpc-servlet-websocket-jakarta/src/main/java/io/grpc/servlet/web/websocket/WebsocketStreamImpl.java
  java-client/barrage-examples/src/main/resources/logback.xml
  java-client/flight-examples/src/main/resources/logback.xml
  java-client/session-examples/src/main/resources/logback.xml
  log-factory/examples/example-logback/src/main/resources/logback.xml
  qst/graphviz/src/main/resources/logback.xml
  server/build.gradle
  server/jetty/build.gradle
  server/jetty/src/main/resources/logback-debug.xml
  server/jetty/src/main/resources/logback-minimal.xml
  server/jetty/src/main/resources/logback.xml
  server/netty/build.gradle
  server/netty/src/main/resources/logback-debug.xml
  server/netty/src/main/resources/logback-minimal.xml
  server/netty/src/main/resources/logback.xml
  server/src/main/java/io/deephaven/server/runner/Main.java
Labels: jsapi, logging, grpc, NoDocumentationNeeded, jetty

#1828 Change gradle config to fetch FastDoubleParser from the Maven central repository
  extensions/csv/build.gradle
  extensions/csv/src/main/java/io/deephaven/csv/tokenization/Tokenizer.java
  extensions/csv/src/main/java/io/deephaven/csv/tokenization/external/FastDoubleMath.java
  extensions/csv/src/main/java/io/deephaven/csv/tokenization/external/FastDoubleParser.java
  extensions/csv/src/main/java/io/deephaven/csv/tokenization/external/FastDoubleParserFromByteArray.java
  extensions/csv/src/main/java/io/deephaven/csv/tokenization/external/FastDoubleParserFromCharArray.java
  extensions/csv/src/test/java/io/deephaven/csv/DeephavenCsvTest.java
Labels: NoDocumentationNeeded

#1837 CsvReader: provide correct logical and physical row numbers.
  extensions/csv/src/main/java/io/deephaven/csv/reading/CellGrabber.java
  extensions/csv/src/main/java/io/deephaven/csv/reading/CsvReader.java
  extensions/csv/src/main/java/io/deephaven/csv/reading/ParseInputToDenseStorage.java
  extensions/csv/src/test/java/io/deephaven/csv/CsvReaderTest.java
Labels: NoDocumentationNeeded

#1838 Bump node and protoc-base to latest versions
  docker/registry/node/gradle.properties
  docker/registry/protoc-base/gradle.properties
Labels: clean up, NoDocumentationNeeded

#1841 Bump in prep for end of month release of 0.9.0
  .github/workflows/build-ci.yml
  build.gradle
  pyclient/README.md
  pyclient/pydeephaven/__init__.py
  pyclient/setup.py
  pyintegration/deephaven2/__init__.py
  server/jetty/README.md
Labels: NoDocumentationNeeded

#1840 Tag protoc-base as part of the release.
  .github/workflows/build-ci.yml
Labels: build, ci, NoDocumentationNeeded, release

#1835 JS API should copy data for all columns, and should size consistently
  web/client-api/src/main/java/io/deephaven/web/client/api/WorkerConnection.java
  web/client-api/src/main/java/io/deephaven/web/client/api/subscription/TableViewportSubscription.java
  web/client-api/src/main/java/io/deephaven/web/client/api/subscription/ViewportData.java
Labels: jsapi, NoDocumentationNeeded

#1803 Add base+ images to repo and info to README
  README.md
  containers/python-examples/NLTK/README.md
  containers/python-examples/NLTK/docker-compose.yml
  containers/python-examples/PyTorch/README.md
  containers/python-examples/PyTorch/docker-compose.yml
  containers/python-examples/SciKit-Learn/README.md
  containers/python-examples/SciKit-Learn/docker-compose.yml
  containers/python-examples/TensorFlow/README.md
  containers/python-examples/TensorFlow/docker-compose.yml
  containers/python-examples/base/README.md
  containers/python-examples/base/docker-compose.yml
  containers/python/NLTK/README.md
  containers/python/NLTK/docker-compose.yml
  containers/python/PyTorch/README.md
  containers/python/PyTorch/docker-compose.yml
  containers/python/SciKit-Learn/README.md
  containers/python/SciKit-Learn/docker-compose.yml
  containers/python/TensorFlow/README.md
  containers/python/TensorFlow/docker-compose.yml
  containers/python/base/README.md
  containers/python/base/docker-compose.yml
Labels: documentation, python, docker, NoDocumentationNeeded

#1851 Ensure newline, print out gradle.properties
  .github/workflows/build-ci.yml
  .github/workflows/check-ci.yml
  .github/workflows/docs-ci.yml
  .github/workflows/long-check-ci.yml
  .github/workflows/nightly-benchmarks.yml
  .github/workflows/nightly-check-ci.yml
  .github/workflows/nightly-image-check.yml
  .github/workflows/publish-ci.yml
Labels: ci, NoDocumentationNeeded

#1843 A workaround to a JPY issue with long values, fixes #1461
  Integrations/python/functional-tests/pylong_conv_test.py
  engine/table/src/main/java/io/deephaven/engine/util/PythonScopeJpyImpl.java
Labels: NoDocumentationNeeded

#1522 [groovy] fix err msg for x[index] on anonymous object
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/QueryScopeParamTypeUtil.java
  engine/table/src/test/java/io/deephaven/engine/util/scripts/TestGroovyDeephavenSession.java
Labels: bug, NoDocumentationNeeded, repl

#1859 Fix batch export response handling pyclient
  pyclient/pydeephaven/_table_service.py
  pyclient/pydeephaven/table.py
Labels: NoDocumentationNeeded, python-client

#1862 Unordered Fill in LongAsDateTime and ByteAsBoolean needs to set size, fixes #1857
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/ByteAsBooleanColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/LongAsDateTimeColumnSource.java
Labels: query engine, NoDocumentationNeeded

#1865 Jpy's mvn build should be in batch mode to reduce log noise
  py/jpy/setup.py
Labels: build, NoDocumentationNeeded

#1863 Use virtual environment from latest upstream base images.
  docker/registry/nltk-base/gradle.properties
  docker/registry/python-dev-base/gradle.properties
  docker/registry/pytorch-base/gradle.properties
  docker/registry/server-base/gradle.properties
  docker/registry/sklearn-base/gradle.properties
  docker/registry/tensorflow-base/gradle.properties
  docker/runtime-base/src/main/docker/Dockerfile
  docker/server/src/main/docker/Dockerfile
  docker/server/src/main/server-nltk/requirements.txt
  docker/server/src/main/server-pytorch/requirements.txt
  docker/server/src/main/server-sklearn/requirements.txt
  docker/server/src/main/server-tensorflow/requirements.txt
  docker/server/src/main/server/requirements.txt
  py/jpy-integration/build.gradle
  py/jpy-integration/src/javaToPython/build.gradle.template
  py/jpy/Dockerfile
  python-engine-test/src/test/build.gradle.template
  sphinx/sphinx.gradle
Labels: python, docker, NoDocumentationNeeded

#1870 Update NLTK dependencies.
  docker/server/src/main/server-nltk/requirements.txt
Labels: bug, build, NoDocumentationNeeded

#1839 Add meta tags to deephaven demo loading page
  demo/src/main/java/io/deephaven/demo/index.html
Labels: NoDocumentationNeeded, demo

#1882 Factor out the need for docker compose from docker tasks, to apply only to the ones that really need it.
  Integrations/build.gradle
Labels: NoDocumentationNeeded

#1498 Upgrade to Arrow 6.0.1
  buildSrc/src/main/groovy/Classpaths.groovy
  pyclient/build.gradle
  pyclient/requirements.txt
  sphinx/sphinx.gradle
Labels: feature request, DocumentationNeeded, arrow

#1877 Support registering a schema for a table (definition) to schema registry. Support DateTime publishing to Kafka.
  Integrations/python/deephaven/ProduceKafka.py
  Integrations/python/deephaven/conversion_utils.py
  extensions/kafka/src/main/java/io/deephaven/kafka/KafkaTools.java
  extensions/kafka/src/main/java/io/deephaven/kafka/publish/GenericRecordKeyOrValueSerializer.java
Labels: NoDocumentationNeeded

#1856 Full version of derived tables for debezium demo.
  debezium-demo/.env
  debezium-demo/README.md
  debezium-demo/demo.py
Labels: NoDocumentationNeeded

#1876 Avoid exceptions on autocomplete
  open-api/lang-tools/src/main/java/io/deephaven/lang/completion/ChunkerCompleter.java
  open-api/lang-tools/src/main/java/io/deephaven/lang/completion/CompletionRequest.java
  open-api/lang-tools/src/test/groovy/io/deephaven/lang/completion/ChunkerCompletionHandlerTest.groovy
  server/src/main/java/io/deephaven/server/console/ConsoleServiceGrpcImpl.java
Labels: autocomplete, NoDocumentationNeeded

#1886 Fix variable order in console sessions
  engine/table/src/main/java/io/deephaven/engine/util/ScriptSession.java
  server/src/main/java/io/deephaven/server/appmode/ApplicationServiceGrpcImpl.java
Labels: bug, NoDocumentationNeeded

#1887 Send enough bits to represent the column set to subscribe to
  web/client-api/src/main/java/io/deephaven/web/client/api/barrage/BarrageUtils.java
Labels: NoDocumentationNeeded

#1889 Remove unused plugin dependency
  plugin/build.gradle
Labels: clean up, NoDocumentationNeeded, plug-ins

#1893 Properly unwrap deephaven2.table.Table for script session.
  pyintegration/deephaven2/server/script_session/__init__.py
Labels: bug, NoDocumentationNeeded

#1885 Renamed `Index` to `RowSet` in source
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/BarrageProtoUtil.java
  server/src/main/java/io/deephaven/server/arrow/ArrowFlightUtil.java
  server/src/main/java/io/deephaven/server/barrage/BarrageStreamGenerator.java
Labels: clean up, NoDocumentationNeeded

#1895 Add convert-to-table
  java-client/flight-examples/build.gradle
  java-client/flight-examples/src/main/java/io/deephaven/client/examples/ConvertToTable.java
  java-client/flight-examples/src/main/java/io/deephaven/client/examples/GetTable.java
Labels: NoDocumentationNeeded

#1894 Support publishing BigDecimal columns to Kafka Avro.
  Integrations/python/deephaven/ProduceKafka.py
  debezium-demo/demo.py
  engine/table/src/main/java/io/deephaven/engine/util/BigDecimalUtils.java
  extensions/kafka/src/main/java/io/deephaven/kafka/KafkaTools.java
  extensions/kafka/src/main/java/io/deephaven/kafka/publish/GenericRecordKeyOrValueSerializer.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/ParquetTableWriter.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/TypeInfos.java
Labels: NoDocumentationNeeded

#1897 Rename check to quick ci
  .github/workflows/check-ci.yml
  .github/workflows/publish-check-ci.yml
  .github/workflows/publish-long-check-ci.yml
  .github/workflows/quick-ci.yml
  README.md
  build.gradle
Labels: ci, NoDocumentationNeeded

#1900 Bump to latest base-images
  docker/registry/nltk-base/gradle.properties
  docker/registry/node/gradle.properties
  docker/registry/protoc-base/gradle.properties
  docker/registry/python-dev-base/gradle.properties
  docker/registry/python/gradle.properties
  docker/registry/pytorch-base/gradle.properties
  docker/registry/server-base/gradle.properties
  docker/registry/sklearn-base/gradle.properties
  docker/registry/slim-base/gradle.properties
  docker/registry/tensorflow-base/gradle.properties
Labels: clean up, NoDocumentationNeeded

#1899 Quality of life improvements for formula handling around BigDecimal columns.
  debezium-demo/demo.py
  engine/table/src/main/java/io/deephaven/engine/table/impl/lang/QueryLanguageFunctionUtils.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestBigDecimalColumns.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/lang/TestQueryLanguageFunctionUtils.java
Labels: NoDocumentationNeeded

#1901 Web version bump v0.9.1
  web/client-ui/Dockerfile
Labels: feature request, NoDocumentationNeeded

#1812 hand-wrapped the datetimeutils module, fixes #1640
  pyintegration/deephaven2/column.py
  pyintegration/deephaven2/constants.py
  pyintegration/deephaven2/dtypes.py
  pyintegration/deephaven2/html.py
  pyintegration/deephaven2/table.py
  pyintegration/deephaven2/table_factory.py
  pyintegration/deephaven2/time.py
  pyintegration/tests/test_dtypes.py
  pyintegration/tests/test_table.py
  pyintegration/tests/test_table_factory.py
  pyintegration/tests/test_time.py
Labels: python, NoDocumentationNeeded, python-server-side

#1906 Bump to latest python:3.7
  docker/registry/python/gradle.properties
Labels: build, NoDocumentationNeeded, version-bump

#1907 Remove unused gradle.properties options
  Generators/Generators.gradle
  Generators/python/javadocExtraction.py
  Generators/python/manualDocstrings.py
  build.gradle
  gradle.properties
  gradle/deephaven-jpy.gradle
  gradle/versions/mp
Labels: clean up, NoDocumentationNeeded

#1908 Set load generation parameters the same as original demo
  debezium-demo/loadgen/generate_load.py
Labels: NoDocumentationNeeded

#1909 Improve debezium-demo README.md
  debezium-demo/README.md
Labels: NoDocumentationNeeded
