Repository deephaven/deephaven-core, pull requests merged in 2023-10, with the labels that each got.

#4588 A few small cleanups to ring table and snapshot
  engine/table/src/main/java/io/deephaven/engine/table/impl/remote/ConstructSnapshot.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/ring/AbstractRingChunkSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/ring/AddsToRingsListener.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/ring/RingTableTools.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4590 Check easily made user mistake for count_ etc.
  py/server/deephaven/agg.py
  py/server/tests/test_table.py
Labels: NoDocumentationNeeded, python-server-side, NoReleaseNotesNeeded

#4583 C++ Client: Remove all the async entry points / logic
  cpp-client/deephaven/dhclient/include/private/deephaven/client/impl/client_impl.h
  cpp-client/deephaven/dhclient/include/private/deephaven/client/impl/table_handle_impl.h
  cpp-client/deephaven/dhclient/include/private/deephaven/client/impl/table_handle_manager_impl.h
  cpp-client/deephaven/dhclient/include/private/deephaven/client/server/server.h
  cpp-client/deephaven/dhclient/include/private/deephaven/client/utility/executor.h
  cpp-client/deephaven/dhclient/include/public/deephaven/client/client.h
  cpp-client/deephaven/dhclient/include/public/deephaven/client/update_by.h
  cpp-client/deephaven/dhclient/src/client.cc
  cpp-client/deephaven/dhclient/src/impl/client_impl.cc
  cpp-client/deephaven/dhclient/src/impl/table_handle_impl.cc
  cpp-client/deephaven/dhclient/src/impl/table_handle_manager_impl.cc
  cpp-client/deephaven/dhclient/src/server/server.cc
  cpp-client/deephaven/dhclient/src/subscription/subscribe_thread.cc
  cpp-client/deephaven/dhclient/src/utility/executor.cc
  cpp-client/deephaven/dhcore/CMakeLists.txt
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/ticking/ticking.h
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/utility/callbacks.h
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/utility/cbfuture.h
  cpp-client/deephaven/dhcore/src/utility/cbfuture.cc
  cpp-client/deephaven/tests/basic_test.cc
  cpp-client/deephaven/tests/select_test.cc
  cpp-client/deephaven/tests/validation_test.cc
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4597 Fix BarrageMessageProducer.SnapshotControl.usePreviousValues
  server/src/main/java/io/deephaven/server/barrage/BarrageMessageProducer.java
Labels: bug, barrage, core, NoDocumentationNeeded, ReleaseNotesNeeded

#4572 ClockFilter: Correct Missing Dependency and Improve Performance
  engine/table/src/main/java/io/deephaven/engine/table/impl/BaseTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/WhereListener.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/BaseIncrementalReleaseFilter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/ClockFilter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/RollingReleaseFilter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/SimulationClock.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/TimeSeriesFilter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/WhereFilterInvertedImpl.java
Labels: bug, core, NoDocumentationNeeded, ReleaseNotesNeeded

#4598 Make newTable, emptyTable flat. Fix flatten.
  engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java
  engine/table/src/main/java/io/deephaven/engine/util/TableTools.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableFlattenTest.java
  engine/table/src/test/java/io/deephaven/engine/util/TestTableTools.java
Labels: query engine, NoDocumentationNeeded, NoReleaseNotesNeeded

#4599 C++ client: in some contexts, catch and log exceptions rather than propagate
  cpp-client/deephaven/dhclient/src/client.cc
  cpp-client/deephaven/dhclient/src/impl/table_handle_impl.cc
  cpp-client/deephaven/dhclient/src/impl/table_handle_manager_impl.cc
  cpp-client/deephaven/dhclient/src/server/server.cc
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4389 Add package.json js-plugins support
  plugin/build.gradle
  plugin/dagger/src/main/java/io/deephaven/plugin/PluginModule.java
  plugin/src/main/java/io/deephaven/plugin/Plugin.java
  plugin/src/main/java/io/deephaven/plugin/js/JsPlugin.java
  plugin/src/main/java/io/deephaven/plugin/js/JsPluginBase.java
  plugin/src/main/java/io/deephaven/plugin/js/JsPluginManifestPath.java
  plugin/src/main/java/io/deephaven/plugin/js/JsPluginPackagePath.java
  server/jetty/src/main/java/io/deephaven/server/jetty/CopyHelper.java
  server/jetty/src/main/java/io/deephaven/server/jetty/JettyBackedGrpcServer.java
  server/jetty/src/main/java/io/deephaven/server/jetty/JettyServerModule.java
  server/jetty/src/main/java/io/deephaven/server/jetty/JsPluginManifest.java
  server/jetty/src/main/java/io/deephaven/server/jetty/JsPluginManifestEntry.java
  server/jetty/src/main/java/io/deephaven/server/jetty/JsPlugins.java
  server/jetty/src/main/java/io/deephaven/server/jetty/JsPluginsZipFilesystem.java
  server/jetty/src/main/java/io/deephaven/server/jetty/Json.java
  server/netty/src/main/java/io/deephaven/server/netty/NettyServerModule.java
  server/src/main/java/io/deephaven/server/plugin/PluginRegistration.java
  server/src/main/java/io/deephaven/server/plugin/PluginRegistrationVisitor.java
  server/src/main/java/io/deephaven/server/plugin/PluginsModule.java
  server/src/main/java/io/deephaven/server/plugin/js/JsPluginModule.java
  server/src/main/java/io/deephaven/server/plugin/js/JsPluginNoopConsumerModule.java
  server/src/main/java/io/deephaven/server/runner/MainHelper.java
  server/src/test/java/io/deephaven/server/runner/DeephavenApiServerTestBase.java
  server/test/src/main/java/io/deephaven/server/test/FlightMessageRoundTripTest.java
Labels: feature request, DocumentationNeeded, ReleaseNotesNeeded

#4600 R client: remove call to "Observe" in the C++ client, add missing dependencies
  R/rdeephaven/README.md
  R/rdeephaven/src/client.cpp
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4552 Enable figures to retain references to objects they rely on
  Generators/src/main/java/io/deephaven/plot/util/GenerateAxesPlotMethods.java
  Generators/src/main/java/io/deephaven/plot/util/GenerateFigureImmutable.java
  Plot/src/main/java/io/deephaven/plot/Figure.java
  Plot/src/main/java/io/deephaven/plot/FigureWidget.java
  Plot/src/test/java/io/deephaven/plot/TestFigureLiveness.java
  engine/updategraph/src/main/java/io/deephaven/engine/liveness/DelegatingLivenessNode.java
Labels: plotting, NoDocumentationNeeded, ReleaseNotesNeeded

#4497 Enhance Python LivenessScope API
  py/server/deephaven/liveness_scope.py
  py/server/deephaven/table_listener.py
  py/server/tests/test_liveness.py
  py/server/tests/test_perfmon.py
  py/server/tests/testbase.py
  sphinx/source/conf.py
Labels: DocumentationNeeded, python-server-side, plug-ins, ReleaseNotesNeeded

#4607 Ensure top-level java-client filters are preserved
  java-client/session-dagger/src/test/java/io/deephaven/client/WhereSessionTest.java
  java-client/session-examples/build.gradle
  java-client/session-examples/src/main/java/io/deephaven/client/examples/FilterTable.java
  java-client/session/src/main/java/io/deephaven/client/impl/BatchTableRequestBuilder.java
  sql/src/main/java/io/deephaven/sql/LogicalJoinAdapter.java
  table-api/src/main/java/io/deephaven/api/filter/ExtractAnds.java
  table-api/src/main/java/io/deephaven/api/filter/Filter.java
  table-api/src/test/java/io/deephaven/api/filter/FilterTest.java
Labels: NoDocumentationNeeded, java-client, NoReleaseNotesNeeded

#4579 auto convert Python return val to Java val
  engine/table/src/main/java/io/deephaven/engine/table/impl/lang/QueryLanguageParser.java
  engine/table/src/main/java/io/deephaven/engine/util/PyCallableWrapperJpyImpl.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/lang/PyCallableWrapperDummyImpl.java
  py/server/deephaven/column.py
  py/server/deephaven/dtypes.py
  py/server/deephaven/table.py
  py/server/tests/test_numba_guvectorize.py
  py/server/tests/test_numba_vectorized_column.py
  py/server/tests/test_numba_vectorized_filter.py
  py/server/tests/test_pyfunc_return_java_values.py
  py/server/tests/test_vectorization.py
Labels: DocumentationNeeded, python-server-side, ReleaseNotesNeeded

#4267 UPDATE: Secondary readmes
  proto/README.md
  py/README.md
  server/jetty-app/README.md
Labels: documentation, NoDocumentationNeeded, NoReleaseNotesNeeded

#4611 Make extensions-kafka source-compatible with confluent 5.5.x
  extensions/kafka/build.gradle
  extensions/kafka/src/main/java/io/deephaven/kafka/KafkaTools.java
Labels: NoDocumentationNeeded, user-reported, NoReleaseNotesNeeded

#4585 Provide options to parse Protobuf from classpath
  extensions/kafka/TESTING.md
  extensions/kafka/build.gradle
  extensions/kafka/src/main/java/io/deephaven/kafka/KafkaTools.java
  extensions/kafka/src/main/java/io/deephaven/kafka/ProtobufDeserializers.java
  extensions/kafka/src/main/java/io/deephaven/kafka/ProtobufImpl.java
  extensions/kafka/src/main/java/io/deephaven/kafka/protobuf/DescriptorMessageClass.java
  extensions/kafka/src/main/java/io/deephaven/kafka/protobuf/DescriptorProvider.java
  extensions/kafka/src/main/java/io/deephaven/kafka/protobuf/DescriptorSchemaRegistry.java
  extensions/kafka/src/main/java/io/deephaven/kafka/protobuf/ProtobufConsumeOptions.java
  extensions/kafka/src/main/java/io/deephaven/kafka/protobuf/Protocol.java
  extensions/kafka/src/test/java/io/deephaven/kafka/ProtobufImplSchemaChangeTest.java
  extensions/kafka/src/test/java/io/deephaven/kafka/protobuf/gen/BoolV1.java
  extensions/kafka/src/test/java/io/deephaven/kafka/protobuf/gen/BoolV2.java
  extensions/kafka/src/test/java/io/deephaven/kafka/protobuf/gen/MyMessageV1.java
  extensions/kafka/src/test/java/io/deephaven/kafka/protobuf/gen/MyMessageV2.java
  extensions/kafka/src/test/java/io/deephaven/kafka/protobuf/gen/MyMessageV3.java
  extensions/kafka/src/test/java/io/deephaven/kafka/protobuf/gen/MyMessageV4.java
  extensions/kafka/src/test/java/io/deephaven/kafka/protobuf/gen/MyMessageV5.java
  extensions/kafka/src/test/java/io/deephaven/kafka/protobuf/gen/RenameV1.java
  extensions/kafka/src/test/java/io/deephaven/kafka/protobuf/gen/RenameV2.java
  extensions/kafka/src/test/java/io/deephaven/kafka/protobuf/gen/SpecialTypesV1.java
  extensions/kafka/src/test/java/io/deephaven/kafka/protobuf/gen/SpecialTypesV2.java
  extensions/kafka/src/test/proto/BoolV1.proto.txt
  extensions/kafka/src/test/proto/BoolV2.proto.txt
  extensions/kafka/src/test/proto/MyMessageV1.proto.txt
  extensions/kafka/src/test/proto/MyMessageV2.proto.txt
  extensions/kafka/src/test/proto/MyMessageV3.proto.txt
  extensions/kafka/src/test/proto/MyMessageV4.proto.txt
  extensions/kafka/src/test/proto/MyMessageV5.proto.txt
  extensions/kafka/src/test/proto/RenameV1.proto.txt
  extensions/kafka/src/test/proto/RenameV2.proto.txt
  extensions/kafka/src/test/proto/SpecialTypesV1.proto.txt
  extensions/kafka/src/test/proto/SpecialTypesV2.proto.txt
  py/server/deephaven/stream/kafka/consumer.py
  py/server/tests/test_kafka_consumer.py
Labels: kafka, DocumentationNeeded, ReleaseNotesNeeded

#4619 Add uncaught exception handler to barrage-example mains
  java-client/barrage-examples/src/main/java/io/deephaven/client/examples/SnapshotTable.java
  java-client/barrage-examples/src/main/java/io/deephaven/client/examples/SubscribeQST.java
  java-client/barrage-examples/src/main/java/io/deephaven/client/examples/SubscribeTable.java
Labels: NoDocumentationNeeded, example, NoReleaseNotesNeeded

#4565 Better failure messages related to LFS
  README.md
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/InvalidParquetFileException.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/ParquetFileReader.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/ParquetTableReadWriteTest.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/TestParquetTools.java
Labels: bug, core, NoDocumentationNeeded, NoReleaseNotesNeeded

#4621 Ensure that js-plugins aren't cached
  server/jetty/src/main/java/io/deephaven/server/jetty/JettyBackedGrpcServer.java
Labels: bug, NoDocumentationNeeded, jetty, NoReleaseNotesNeeded

#4634 Update R client with best practices w.r.t other packages, update readme with MAKE directives
  R/rdeephaven/DESCRIPTION
  R/rdeephaven/NAMESPACE
  R/rdeephaven/R/exports.R
  R/rdeephaven/README.md
Labels: documentation, NoDocumentationNeeded, NoReleaseNotesNeeded, r-client

#4632 Always half-close DoExchange snapshot requests
  java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshotImpl.java
Labels: grpc, barrage, NoDocumentationNeeded, arrow, envoy, ReleaseNotesNeeded

#4638 Revert "auto convert Python return val to Java val (#4579)"
  engine/table/src/main/java/io/deephaven/engine/table/impl/lang/QueryLanguageParser.java
  engine/table/src/main/java/io/deephaven/engine/util/PyCallableWrapperJpyImpl.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/lang/PyCallableWrapperDummyImpl.java
  py/server/deephaven/column.py
  py/server/deephaven/dtypes.py
  py/server/deephaven/table.py
  py/server/tests/test_numba_guvectorize.py
  py/server/tests/test_numba_vectorized_column.py
  py/server/tests/test_numba_vectorized_filter.py
  py/server/tests/test_pyfunc_return_java_values.py
  py/server/tests/test_vectorization.py
Labels: bug, NoDocumentationNeeded, release blocker, NoReleaseNotesNeeded

#4625 R dockerized test run gradle target and CI
  .github/workflows/tag-base-images.yml
  R/build.gradle
  R/gradle.properties
  R/r-build.sh
  R/r-tests.sh
  R/rdeephaven/inst/tests/testthat/helper.R
  R/rdeephaven/inst/tests/testthat/test_agg_by.R
  R/rdeephaven/inst/tests/testthat/test_client_wrapper.R
  R/rdeephaven/inst/tests/testthat/test_table_handle_wrapper.R
  R/rdeephaven/inst/tests/testthat/test_table_ops.R
  R/rdeephaven/inst/tests/testthat/test_update_by.R
  cpp-client/.gitignore
  cpp-client/build.gradle
  cpp-client/cpp-tests-to-junit.sh
  docker/registry/cpp-client-base/gradle.properties
  docker/registry/r-client-base/build.gradle
  docker/registry/r-client-base/gradle.properties
  settings.gradle
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4646 Don't remove Kafka consumer properties
  extensions/kafka/src/main/java/io/deephaven/kafka/KafkaTools.java
Labels: feature request, core, kafka, NoDocumentationNeeded, ReleaseNotesNeeded

#4636 A few cleanups and bug fixes
  engine/rowset/src/main/java/io/deephaven/engine/rowset/impl/RefCountedCow.java
  engine/rowset/src/main/java/io/deephaven/engine/rowset/impl/rsp/RspRowSequence.java
  engine/rowset/src/main/java/io/deephaven/engine/rowset/impl/singlerange/SingleRange.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/partitioned/BaseTableTransformationColumn.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/partitioned/LongConstantColumn.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/perf/UpdatePerformanceTracker.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/AbstractFormulaColumn.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/FunctionalColumn.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/MultiSourceFunctionalColumn.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/NullSelectColumn.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/ReinterpretedColumn.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/SelectColumn.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/SourceColumn.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/SwitchColumn.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/NullValueColumnSource.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestFormulaArrayEvaluation.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/select/TestFormulaColumn.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/select/TestFormulaColumnGeneration.java
Labels: bug, query engine, core, NoDocumentationNeeded, ReleaseNotesNeeded

#4650 C++ Client: do proper authorization token handling
  cpp-client/deephaven/dhclient/src/server/server.cc
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4596 Enhance Groovy classloader experience
  engine/context/src/main/java/io/deephaven/engine/context/QueryCompiler.java
  engine/table/build.gradle
  engine/table/src/main/java/io/deephaven/engine/util/AbstractScriptSession.java
  engine/table/src/main/java/io/deephaven/engine/util/GroovyDeephavenSession.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/select/FilterKernelArraySample.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/select/FilterKernelSample.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/select/FormulaKernelSample.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/select/FormulaSample.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/select/TestConditionFilterGeneration.java
  engine/table/src/test/java/io/deephaven/engine/util/scripts/TestGroovyDeephavenSession.java
  engine/table/src/test/resources/io/deephaven/engine/util/scripts/Imported.groovy
  engine/table/src/test/resources/io/deephaven/engine/util/scripts/MainScript.groovy
  engine/table/src/test/resources/io/deephaven/engine/util/scripts/ShortSource.groovy
Labels: console, DocumentationNeeded, release blocker, groovy, ReleaseNotesNeeded

#4629 C++ Client: remove the "Fluent API" from code and docs. Also, fix docs.
  R/rdeephaven/src/client.cpp
  cpp-client/deephaven/dhclient/CMakeLists.txt
  cpp-client/deephaven/dhclient/include/private/deephaven/client/impl/boolean_expression_impl.h
  cpp-client/deephaven/dhclient/include/private/deephaven/client/impl/columns_impl.h
  cpp-client/deephaven/dhclient/include/private/deephaven/client/impl/datetime_expression_impl.h
  cpp-client/deephaven/dhclient/include/private/deephaven/client/impl/expression_impl.h
  cpp-client/deephaven/dhclient/include/private/deephaven/client/impl/numeric_expression_impl.h
  cpp-client/deephaven/dhclient/include/private/deephaven/client/impl/string_expression_impl.h
  cpp-client/deephaven/dhclient/include/private/deephaven/client/impl/table_handle_impl.h
  cpp-client/deephaven/dhclient/include/public/deephaven/client/client.h
  cpp-client/deephaven/dhclient/include/public/deephaven/client/columns.h
  cpp-client/deephaven/dhclient/include/public/deephaven/client/expressions.h
  cpp-client/deephaven/dhclient/include/public/deephaven/client/update_by.h
  cpp-client/deephaven/dhclient/src/client.cc
  cpp-client/deephaven/dhclient/src/columns.cc
  cpp-client/deephaven/dhclient/src/expressions.cc
  cpp-client/deephaven/dhclient/src/impl/boolean_expression_impl.cc
  cpp-client/deephaven/dhclient/src/impl/columns_impl.cc
  cpp-client/deephaven/dhclient/src/impl/datetime_expression_impl.cc
  cpp-client/deephaven/dhclient/src/impl/expression_impl.cc
  cpp-client/deephaven/dhclient/src/impl/numeric_expression_impl.cc
  cpp-client/deephaven/dhclient/src/impl/string_expression_impl.cc
  cpp-client/deephaven/dhclient/src/impl/table_handle_impl.cc
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/ticking/ticking.h
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/types.h
  cpp-client/deephaven/dhcore/src/ticking/ticking.cc
  cpp-client/deephaven/examples/create_table_with_arrow_flight/main.cc
  cpp-client/deephaven/examples/create_table_with_table_maker/main.cc
  cpp-client/deephaven/examples/demos/chapter1.cc
  cpp-client/deephaven/examples/read_table_with_arrow_flight/main.cc
  cpp-client/deephaven/examples/table_cleanup/main.cc
  cpp-client/deephaven/tests/add_drop_test.cc
  cpp-client/deephaven/tests/aggregates_test.cc
  cpp-client/deephaven/tests/date_time_test.cc
  cpp-client/deephaven/tests/filter_test.cc
  cpp-client/deephaven/tests/head_and_tail_test.cc
  cpp-client/deephaven/tests/join_test.cc
  cpp-client/deephaven/tests/lastby_test.cc
  cpp-client/deephaven/tests/merge_tables_test.cc
  cpp-client/deephaven/tests/select_test.cc
  cpp-client/deephaven/tests/sort_test.cc
  cpp-client/deephaven/tests/string_filter_test.cc
  cpp-client/deephaven/tests/ticking_test.cc
  cpp-client/deephaven/tests/ungroup_test.cc
  cpp-client/deephaven/tests/view_test.cc
  cpp-client/doc/chunks.rst
  cpp-client/doc/column_sources.rst
  cpp-client/doc/fluent.rst
  cpp-client/doc/fluent_columns.rst
  cpp-client/doc/fluent_expressions.rst
  cpp-client/doc/index.rst
  cpp-client/doc/main.rst
  cpp-client/doc/row_sequences.rst
  cpp-client/doc/tablehandles.rst
  cpp-client/doc/ticking.rst
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4647 auto convert Python return value to Java value v2
  engine/table/src/main/java/io/deephaven/engine/table/impl/lang/QueryLanguageParser.java
  engine/table/src/main/java/io/deephaven/engine/util/PyCallableWrapper.java
  engine/table/src/main/java/io/deephaven/engine/util/PyCallableWrapperJpyImpl.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/lang/PyCallableWrapperDummyImpl.java
  py/server/deephaven/column.py
  py/server/deephaven/dtypes.py
  py/server/deephaven/table.py
  py/server/tests/test_numba_guvectorize.py
  py/server/tests/test_numba_vectorized_column.py
  py/server/tests/test_numba_vectorized_filter.py
  py/server/tests/test_pyfunc_return_java_values.py
  py/server/tests/test_table_factory.py
  py/server/tests/test_vectorization.py
Labels: DocumentationNeeded, python-server-side, ReleaseNotesNeeded

#4653 DoExchange snapshot won't half-close until after client does
  server/src/main/java/io/deephaven/server/arrow/ArrowFlightUtil.java
Labels: grpc, barrage, NoDocumentationNeeded, envoy, ReleaseNotesNeeded

#4630 BarrageSubscriptionImpl: fix race conditions in subscription logic
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/table/BarrageBlinkTable.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/table/BarrageRedirectedTable.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/table/BarrageTable.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/ArrowToTableConverter.java
  java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshot.java
  java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshotImpl.java
  java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscription.java
  java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java
  server/src/main/java/io/deephaven/server/arrow/ArrowFlightUtil.java
  server/src/main/java/io/deephaven/server/barrage/BarrageMessageProducer.java
  server/src/main/java/io/deephaven/server/session/SessionState.java
  server/src/main/java/io/deephaven/server/table/ExportedTableUpdateListener.java
  server/src/test/java/io/deephaven/server/barrage/BarrageBlinkTableTest.java
  server/src/test/java/io/deephaven/server/barrage/BarrageMessageRoundTripTest.java
Labels: bug, core, NoDocumentationNeeded, barrage-wrkr2wrkr, ReleaseNotesNeeded

#4660 Better error message when input is ndim > 1 numpy array for dtypes.array()
  py/server/deephaven/dtypes.py
  py/server/tests/test_dtypes.py
  py/server/tests/test_pyfunc_return_java_values.py
Labels: NoDocumentationNeeded, python-server-side, NoReleaseNotesNeeded

#4643 Added error handling to `FunctionGeneratedTableFactory` processing
  engine/table/src/main/java/io/deephaven/engine/table/impl/MergedListener.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/FunctionGeneratedTableFactory.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/util/TestFunctionGeneratedTableFactory.java
  py/server/deephaven/table_factory.py
Labels: bug, NoDocumentationNeeded, NoReleaseNotesNeeded

#4662 Python ticking client: support ColumnsAsList server protocol
  py/client-ticking/setup.py
  py/client-ticking/src/pydeephaven_ticking/_core.pxd
  py/client-ticking/src/pydeephaven_ticking/_core.pyx
  py/client-ticking/src/pydeephaven_ticking/table_listener.py
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4661 Write parquet file headers to a bufferedOutputStream
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/ColumnWriterImpl.java
Labels: feature request, parquet, NoDocumentationNeeded, NoReleaseNotesNeeded

#4609 Avoid AIOOB in StatsCPUCollector
  Stats/src/main/java/io/deephaven/stats/StatsCPUCollector.java
Labels: bug, NoDocumentationNeeded, ReleaseNotesNeeded

#4663 Rename r-base image to cpp-clients-fat, in preparation of py ticking dockerized CI.
  .github/workflows/tag-base-images.yml
  cpp-client/README.md
  cpp-client/build.gradle
  docker/registry/cpp-clients-fat-base/build.gradle
  docker/registry/cpp-clients-fat-base/gradle.properties
  docker/registry/r-client-base/gradle.properties
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4652 BaseTable: Remove Swap Listener and Add Atomic addUpdateListener
  ClientSupport/src/main/java/io/deephaven/clientsupport/plotdownsampling/RunChartDownsample.java
  engine/api/src/main/java/io/deephaven/engine/table/Table.java
  engine/table/src/main/java/io/deephaven/engine/exceptions/SnapshotUnsuccessfulException.java
  engine/table/src/main/java/io/deephaven/engine/exceptions/TableAlreadyFailedException.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/AddOnlyToBlinkTableAdapter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/BaseTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/BlinkTableTools.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/NotificationStepReceiver.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/OperationSnapshotControl.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/OperationSnapshotControlEx.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/ReverseOperation.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/SortOperation.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/SourceTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/SwapListener.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/TableAdapter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/UncoalescedTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/ChunkedOperatorAggregationHelper.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/hierarchical/TreeTableFilter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/rangejoin/RangeJoinOperation.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/remote/ConstructSnapshot.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/RegionedColumnSourceWithDictionary.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/ring/AddsToRingsListener.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/ring/RingTableTools.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestListenerFailure.java
  engine/table/src/test/java/io/deephaven/engine/util/systemicmarking/TestSystemicObjectMarking.java
  server/src/main/java/io/deephaven/server/session/SessionState.java
  server/src/main/java/io/deephaven/server/table/ExportedTableUpdateListener.java
Labels: bug, core, NoDocumentationNeeded, release blocker, ReleaseNotesNeeded

#4614 UPDATE: Fix pydoc formatting
  py/server/deephaven/csv.py
  py/server/deephaven/filters.py
  py/server/deephaven/jcompat.py
  py/server/deephaven/perfmon.py
  py/server/deephaven/plot/axisformat.py
  py/server/deephaven/plot/color.py
  py/server/deephaven/stream/kafka/consumer.py
  py/server/deephaven/table.py
  py/server/deephaven/time.py
Labels: community, python, NoDocumentationNeeded, NoReleaseNotesNeeded

#4664 Support npt.NDArray annotation
  py/server/deephaven/dtypes.py
  py/server/tests/test_pyfunc_return_java_values.py
Labels: NoDocumentationNeeded, python-server-side, NoReleaseNotesNeeded

#4648 Add KafkaTools.Consume#objectProcessorSpec for custom KeyOrValueSpecs
  extensions/kafka/src/main/java/io/deephaven/kafka/KafkaTools.java
  extensions/kafka/src/main/java/io/deephaven/kafka/KeyOrValueSpecObjectProcessorImpl.java
  extensions/kafka/src/main/java/io/deephaven/kafka/ingest/ChunkUtils.java
  extensions/kafka/src/main/java/io/deephaven/processor/ObjectProcessor.java
  extensions/kafka/src/main/java/io/deephaven/processor/ObjectProcessorRowLimited.java
  extensions/kafka/src/main/java/io/deephaven/processor/ObjectProcessorStrict.java
  extensions/kafka/src/main/java/io/deephaven/processor/ObjectProcessorTypes.java
  extensions/kafka/src/main/java/io/deephaven/processor/functions/ObjectProcessorFunctions.java
  extensions/kafka/src/main/java/io/deephaven/processor/functions/ObjectProcessorFunctionsImpl.java
Labels: kafka, DocumentationNeeded, NoReleaseNotesNeeded

#4617 Upgrade jetty to 11.0.17
  buildSrc/src/main/groovy/Classpaths.groovy
Labels: security, NoDocumentationNeeded, version-bump, NoReleaseNotesNeeded

#4668 Fix incorrect super method invocation in OperationSnapshotControlEx.snapshotCompletedConsistently
  engine/table/src/main/java/io/deephaven/engine/table/impl/OperationSnapshotControlEx.java
Labels: bug, query engine, core, NoDocumentationNeeded, NoReleaseNotesNeeded

#4672 Remove the table size comparison based on wrong assumption
  py/client/tests/test_table.py
Labels: NoDocumentationNeeded, python-client, NoReleaseNotesNeeded

#4666 Post release bump to 0.30.0
  R/rdeephaven/DESCRIPTION
  authorization-codegen/protoc-gen-contextual-auth-wiring
  authorization-codegen/protoc-gen-service-auth-wiring
  buildSrc/src/main/groovy/io.deephaven.common-conventions.gradle
  py/client-ticking/README.md
  py/client-ticking/setup.py
  py/client/README.md
  py/client/pydeephaven/__init__.py
  py/client/setup.py
  py/embedded-server/deephaven_server/__init__.py
  py/server/deephaven/__init__.py
Labels: NoDocumentationNeeded, version-bump, NoReleaseNotesNeeded

#4671 Fortify numpy array typehint parsing
  py/server/deephaven/dtypes.py
  py/server/tests/test_pyfunc_return_java_values.py
Labels: NoDocumentationNeeded, python-server-side, NoReleaseNotesNeeded

#4679 Python client: add a simple demo that is similar to the C++ demo "chapter3"
  py/client-ticking/demos/demo_chapter3.py
  py/client-ticking/demos/demo_simple.py
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4684 Fix a bug in the use of liveness_scope in tests
  py/server/tests/testbase.py
Labels: NoDocumentationNeeded, python-server-side, NoReleaseNotesNeeded

#4682 Make TableUpdateValidator composable in a sequence of operations.
  engine/table/src/main/java/io/deephaven/engine/table/impl/TableUpdateValidator.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/ErrorListener.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableTest.java
  engine/test-utils/src/main/java/io/deephaven/engine/testutil/EvalNugget.java
  engine/test-utils/src/main/java/io/deephaven/engine/testutil/UpdateValidatorNugget.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4697 Create proper JS plugins URI
  server/jetty/src/main/java/io/deephaven/server/jetty/JsPluginsZipFilesystem.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#4676 `BarrageSession` Subscription/Snapshot Methods now Return `Future<Table>`
  engine/table/src/main/java/io/deephaven/engine/exceptions/RequestCancelledException.java
  engine/updategraph/src/main/java/io/deephaven/engine/updategraph/UpdateGraphAwareCompletableFuture.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/table/BarrageTable.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/GrpcUtil.java
  java-client/barrage-examples/src/main/java/io/deephaven/client/examples/SnapshotExampleBase.java
  java-client/barrage-examples/src/main/java/io/deephaven/client/examples/SubscribeExampleBase.java
  java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshot.java
  java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshotImpl.java
  java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscription.java
  java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java
  server/src/main/java/io/deephaven/server/arrow/ArrowFlightUtil.java
  server/src/main/java/io/deephaven/server/uri/BarrageTableResolver.java
Labels: bug, NoDocumentationNeeded, java-client, barrage-wrkr2wrkr, breaking, ReleaseNotesNeeded

#4669 Added buffered stream for all parquet writes
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/ColumnWriterImpl.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/ParquetFileWriter.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/PositionedBufferedOutputStream.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/RowGroupWriterImpl.java
Labels: core, parquet, NoDocumentationNeeded, NoReleaseNotesNeeded

#4692 Fix intermittent build failure, ensuring docker test output is still usable
  buildSrc/src/main/groovy/Docker.groovy
  buildSrc/src/main/groovy/io/deephaven/tools/docker/CombinedDockerRunTask.groovy
Labels: build, NoDocumentationNeeded, NoReleaseNotesNeeded

#4685 Add ObjectProcessor noop impl and ObjectProcessor tests
  extensions/kafka/build.gradle
  extensions/kafka/src/main/java/io/deephaven/processor/ObjectProcessor.java
  extensions/kafka/src/main/java/io/deephaven/processor/ObjectProcessorNoop.java
  extensions/kafka/src/main/java/io/deephaven/processor/ObjectProcessorStrict.java
  extensions/kafka/src/test/java/io/deephaven/processor/ObjectProcessorNoopTest.java
  extensions/kafka/src/test/java/io/deephaven/processor/ObjectProcessorRowLimitedTest.java
  extensions/kafka/src/test/java/io/deephaven/processor/ObjectProcessorStrictTest.java
  extensions/kafka/src/test/java/io/deephaven/processor/ObjectProcessorTest.java
  extensions/kafka/src/test/java/io/deephaven/processor/functions/ObjectProcessorFunctionsTest.java
Labels: test, NoDocumentationNeeded, NoReleaseNotesNeeded

#4688 Gradle build target and CI checks for python ticking client
  .github/workflows/tag-base-images.yml
  cpp-client/build.gradle
  docker/registry/cpp-clients-fat-base/gradle.properties
  docker/registry/cpp-clients-multi-base/build.gradle
  docker/registry/cpp-clients-multi-base/gradle.properties
  py/client-ticking/README.md
  py/client-ticking/build.gradle
  py/client-ticking/demos/demo_simple.py
  py/client-ticking/gradle.properties
  py/client-ticking/tests/__init__.py
  py/client-ticking/tests/suite.py
  py/client-ticking/tests/test_ticking_basic.py
  settings.gradle
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4698 Improve plotting error messages when the input type is bad.
  Plot/src/main/java/io/deephaven/plot/util/ArgumentValidations.java
Labels: bug, NoDocumentationNeeded, NoReleaseNotesNeeded

#4699 Missing TableUpdateValidator unit test.
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestTableUpdateValidator.java
Labels: query engine, core, NoDocumentationNeeded, NoReleaseNotesNeeded

#4702 Update nightly testing to include Java 21
  .github/workflows/nightly-check-ci.yml
  Base/src/test/java/io/deephaven/base/cache/TestOpenAddressedCanonicalizationCache.java
  Configuration/src/test/java/io/deephaven/configuration/TestConfiguration.java
  buildSrc/src/main/groovy/Classpaths.groovy
Labels: java, NoDocumentationNeeded, version-bump, NoReleaseNotesNeeded

#4704 Support time zone literals
  engine/time/src/main/java/io/deephaven/time/TimeLiteralReplacedExpression.java
  engine/time/src/test/java/io/deephaven/time/TestTimeLiteralReplacedExpression.java
Labels: query engine, DocumentationNeeded, enhancement, NoReleaseNotesNeeded

#4706 `AsOfJoin` cookie migration bug fix
  engine/table/src/main/java/io/deephaven/engine/table/impl/asofjoin/RightIncrementalAsOfJoinStateManagerTypedBase.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableAjTest.java
Labels: bug, query engine, core, NoDocumentationNeeded, ReleaseNotesNeeded

#4715 Barrage Protocol: Fix Writer of `byte[]` to Use Var Binary Encoding
  engine/test-utils/src/main/java/io/deephaven/engine/testutil/generator/ByteArrayGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/ChunkInputStreamGenerator.java
  server/src/test/java/io/deephaven/server/barrage/BarrageMessageRoundTripTest.java
Labels: bug, barrage, NoDocumentationNeeded, barrage-wrkr2wrkr, ReleaseNotesNeeded

#4713 Create a dockerized gradle task to update the generated R client documentation.
  R/build.gradle
  R/r-doc.sh
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4707 Support Optional annotation
  py/server/deephaven/dtypes.py
  py/server/deephaven/table.py
  py/server/tests/test_pyfunc_return_java_values.py
  py/server/tests/test_vectorization.py
Labels: DocumentationNeeded, python-server-side, ReleaseNotesNeeded

#4420 Don't leak the viewport subscription when the viewport data is read
  web/client-api/src/main/java/io/deephaven/web/client/api/JsTable.java
  web/client-api/src/main/java/io/deephaven/web/client/api/WorkerConnection.java
  web/client-api/src/main/java/io/deephaven/web/client/api/subscription/TableViewportSubscription.java
Labels: jsapi, NoDocumentationNeeded, ReleaseNotesNeeded

#4716 Re-read from start if a read from proc doesn't fill the buffer
  Stats/src/main/java/io/deephaven/stats/StatsCPUCollector.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#4722 Vector Expansion Kernel O(n^2) -> O(n)
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/vector/ByteVectorExpansionKernel.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/vector/CharVectorExpansionKernel.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/vector/DoubleVectorExpansionKernel.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/vector/FloatVectorExpansionKernel.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/vector/IntVectorExpansionKernel.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/vector/LongVectorExpansionKernel.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/vector/ObjectVectorExpansionKernel.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/vector/ShortVectorExpansionKernel.java
  java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSession.java
  replication/static/src/main/java/io/deephaven/replicators/ReplicateBarrageUtils.java
Labels: bug, core, NoDocumentationNeeded, NoReleaseNotesNeeded

#4725 C++ Client: Keep FlightStreamWriter alive for the duration of the DoExchange
  cpp-client/deephaven/dhclient/src/subscription/subscribe_thread.cc
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4727 Fix NullPointerException if connection is closed after server goes away
  web/client-api/src/main/java/io/deephaven/web/client/api/WorkerConnection.java
Labels: bug, NoDocumentationNeeded, NoReleaseNotesNeeded

#4732 Make Barrage URI resolver return a Table
  server/src/main/java/io/deephaven/server/uri/BarrageTableResolver.java
Labels: bug, NoDocumentationNeeded, ReleaseNotesNeeded

#4678 Pydoc formatting fixes
  py/server/deephaven/column.py
  py/server/deephaven/learn/__init__.py
  py/server/deephaven/plot/linestyle.py
  py/server/deephaven/stream/kafka/cdc.py
  py/server/deephaven/stream/kafka/consumer.py
  py/server/deephaven/table.py
  py/server/deephaven/table_listener.py
  py/server/deephaven/time.py
Labels: documentation, NoDocumentationNeeded, NoReleaseNotesNeeded

#4726 C++ Client: changes for compatibility with Arrow version 13
  cpp-client/README.md
  cpp-client/build.gradle
  cpp-client/deephaven/CMakeLists.txt
  cpp-client/deephaven/dhclient/include/private/deephaven/client/arrowutil/arrow_value_converter.h
  cpp-client/deephaven/dhcore/CMakeLists.txt
  cpp-client/deephaven/tests/join_test.cc
  cpp-client/deephaven/tests/test_util.cc
  docker/registry/cpp-clients-multi-base/gradle.properties
  py/client-ticking/build.gradle
  py/client-ticking/setup.py
  py/client-ticking/tests/test_ticking_basic.py
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4747 Eliminate initialization race condition in LiveAttributeMap.immutableAttributes, clean up a few things, and add a unit test
  engine/table/src/main/java/io/deephaven/engine/table/impl/LiveAttributeMap.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestLiveAttributeMap.java
Labels: bug, query engine, core, NoDocumentationNeeded, ReleaseNotesNeeded

#4525 Modify layout of grouping files
  engine/table/src/main/java/io/deephaven/engine/table/impl/locations/local/KeyValuePartitionLayout.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/ParquetTools.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/layout/ParquetFileHelper.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/location/ParquetColumnLocation.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/ParquetTableReadWriteTest.java
  extensions/parquet/table/src/test/resources/ParquetDataWithLegacyGroupingInfo.parquet
  extensions/parquet/table/src/test/resources/ParquetDataWithLegacyGroupingInfo_gcol_grouping.parquet
Labels: bug, parquet, NoDocumentationNeeded, NoReleaseNotesNeeded

#4748 Add FilterIn support via java-client
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/WhereFilterAdapter.java
  java-client/session-dagger/src/test/java/io/deephaven/client/WhereSessionTest.java
  java-client/session/src/main/java/io/deephaven/client/impl/BatchTableRequestBuilder.java
  server/src/test/java/io/deephaven/server/table/ops/filter/NormalizeNotsTest.java
  table-api/src/main/java/io/deephaven/api/filter/FilterIn.java
Labels: bug, NoDocumentationNeeded, java-client, user-reported, NoReleaseNotesNeeded
