Repository deephaven/deephaven-core, pull requests merged in 2023-06, with the labels that each got.

#3875 Add the header_row parameter in read_csv
  py/server/deephaven/csv.py
  py/server/tests/test_csv.py
Labels: DocumentationNeeded, python-server-side, ReleaseNotesNeeded

#3901 Add proto file codeowners
  .github/CODEOWNERS
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#3903 Fix RangeJoinTablesRequest enums, enable via TableServiceGrpcImpl
  cpp-client/deephaven/client/proto/deephaven/proto/table.pb.cc
  cpp-client/deephaven/client/proto/deephaven/proto/table.pb.h
  go/internal/proto/table/table.pb.go
  proto/proto-backplane-grpc/src/main/proto/deephaven/proto/table.proto
  py/client/pydeephaven/proto/table_pb2.py
  server/src/main/java/io/deephaven/server/table/ops/RangeJoinGrpcImpl.java
  server/src/main/java/io/deephaven/server/table/ops/TableServiceGrpcImpl.java
  server/src/test/java/io/deephaven/server/table/ops/RangeJoinGrpcTest.java
Labels: grpc, NoDocumentationNeeded, NoReleaseNotesNeeded

#3899 Add typed asOfJoin, delegate aj/raj
  engine/benchmark/src/benchmark/java/io/deephaven/benchmark/engine/AjBenchmark.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/TableAdapter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/UncoalescedTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/partitioned/PartitionedTableProxyImpl.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/AsOfJoinMatchFactory.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableAjTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableJoinTest.java
  java-client/session/src/main/java/io/deephaven/client/impl/BatchTableRequestBuilder.java
  py/server/deephaven/table.py
  py/server/tests/test_pt_proxy.py
  py/server/tests/test_table.py
  qst/graphviz/src/main/java/io/deephaven/graphviz/LabelBuilder.java
  qst/src/main/java/io/deephaven/qst/TableAdapterImpl.java
  qst/src/main/java/io/deephaven/qst/table/AsOfJoinTable.java
  qst/src/main/java/io/deephaven/qst/table/LinkDescriber.java
  qst/src/main/java/io/deephaven/qst/table/ParentsVisitor.java
  qst/src/main/java/io/deephaven/qst/table/ReverseAsOfJoinTable.java
  qst/src/main/java/io/deephaven/qst/table/TableBase.java
  qst/src/main/java/io/deephaven/qst/table/TableSpec.java
  qst/src/main/java/io/deephaven/qst/table/TableVisitorGeneric.java
  server/src/main/java/io/deephaven/server/table/ops/JoinTablesGrpcImpl.java
  table-api/src/main/java/io/deephaven/api/AsOfJoinMatch.java
  table-api/src/main/java/io/deephaven/api/AsOfJoinRule.java
  table-api/src/main/java/io/deephaven/api/JoinAddition.java
  table-api/src/main/java/io/deephaven/api/JoinMatch.java
  table-api/src/main/java/io/deephaven/api/ReverseAsOfJoinRule.java
  table-api/src/main/java/io/deephaven/api/Strings.java
  table-api/src/main/java/io/deephaven/api/TableOperations.java
  table-api/src/main/java/io/deephaven/api/TableOperationsAdapter.java
  table-api/src/main/java/io/deephaven/api/TableOperationsDefaults.java
  table-api/src/main/java/io/deephaven/api/expression/AsOfJoinMatchFactory.java
  table-api/src/test/java/io/deephaven/api/AsOfJoinMatchTest.java
Labels: table api, DocumentationNeeded, qst, ReleaseNotesNeeded

#3896 Bump gradle-docker-plugin to 9.3.1
  buildSrc/build.gradle
Labels: build, NoDocumentationNeeded, version-bump, NoReleaseNotesNeeded

#3908 Fix broken references in CPP client documentation
  cpp-client/deephaven/client/include/public/deephaven/client/client.h
  cpp-client/deephaven/client/src/client.cc
  cpp-client/doc/Doxyfile
  cpp-client/doc/chunks.rst
  cpp-client/doc/column_sources.rst
  cpp-client/doc/conf.py
  cpp-client/doc/main.rst
  cpp-client/doc/row_sequences.rst
  cpp-client/doc/ticking.rst
  cpp-client/doc/types.rst
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#3913 Remove SQL special case for DateTime
  engine/sql/src/main/java/io/deephaven/engine/sql/Sql.java
Labels: bug, NoDocumentationNeeded, NoReleaseNotesNeeded

#3909 Add and plumb AjRajTablesRequest
  authorization/src/main/java/io/deephaven/auth/codegen/impl/TableServiceContextualAuthWiring.java
  cpp-client/deephaven/client/proto/deephaven/proto/table.grpc.pb.cc
  cpp-client/deephaven/client/proto/deephaven/proto/table.grpc.pb.h
  cpp-client/deephaven/client/proto/deephaven/proto/table.pb.cc
  cpp-client/deephaven/client/proto/deephaven/proto/table.pb.h
  go/internal/proto/table/table.pb.go
  go/internal/proto/table/table_grpc.pb.go
  java-client/session/src/main/java/io/deephaven/client/impl/BatchTableRequestBuilder.java
  proto/proto-backplane-grpc/src/main/java/io/deephaven/proto/util/OperationHelper.java
  proto/proto-backplane-grpc/src/main/proto/deephaven/proto/table.proto
  py/client/pydeephaven/proto/table_pb2.py
  py/client/pydeephaven/proto/table_pb2_grpc.py
  qst/src/main/java/io/deephaven/qst/table/AsOfJoinTable.java
  server/src/main/java/io/deephaven/server/table/TableModule.java
  server/src/main/java/io/deephaven/server/table/ops/AjRajGrpcImpl.java
  server/src/main/java/io/deephaven/server/table/ops/JoinTablesGrpcImpl.java
  server/src/main/java/io/deephaven/server/table/ops/TableServiceGrpcImpl.java
  server/src/test/java/io/deephaven/server/table/ops/AsOfJoinGrpcTestBase.java
  server/src/test/java/io/deephaven/server/table/ops/WhereInGrpcTest.java
  table-api/src/main/java/io/deephaven/api/AsOfJoinMatch.java
Labels: grpc, NoDocumentationNeeded, ReleaseNotesNeeded

#3910 Rename getMeta() to meta()
  engine/api/src/main/java/io/deephaven/engine/table/Table.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/TableDefaults.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableAggregationTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableNaturalJoinTest.java
  engine/table/src/test/java/io/deephaven/engine/util/TestTableTools.java
  extensions/csv/src/test/java/io/deephaven/csv/TestCsvTools.java
  py/server/deephaven/table.py
  server/src/main/java/io/deephaven/server/table/ops/MetaTableGrpcImpl.java
Labels: query engine, DocumentationNeeded, ReleaseNotesNeeded

#3914 Update pydeephaven for aj/raj
  py/client/pydeephaven/__init__.py
  py/client/pydeephaven/_table_interface.py
  py/client/pydeephaven/_table_ops.py
  py/client/pydeephaven/query.py
  py/client/pydeephaven/table.py
Labels: DocumentationNeeded, python-client, breaking, ReleaseNotesNeeded

#3662 Restore totals table support in the JS API
  engine/table/src/main/java/io/deephaven/engine/util/TotalsTableBuilder.java
  web/client-api/src/main/java/io/deephaven/web/client/api/JoinableTable.java
  web/client-api/src/main/java/io/deephaven/web/client/api/JsTable.java
  web/client-api/src/main/java/io/deephaven/web/client/api/JsTotalsTable.java
  web/client-api/src/main/java/io/deephaven/web/client/api/JsTotalsTableConfig.java
  web/client-api/src/main/java/io/deephaven/web/client/api/tree/JsTreeTable.java
  web/client-api/src/main/java/io/deephaven/web/client/api/tree/enums/JsAggregationOperation.java
  web/client-api/src/main/java/io/deephaven/web/public/index.html
  web/client-api/src/main/java/io/deephaven/web/public/rollup.html
  web/client-api/src/main/java/io/deephaven/web/public/totals_tables.html
  web/client-api/src/main/java/io/deephaven/web/public/treetable.html
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/table_pb/aggspec/AggSpecNonUniqueSentinel.java
Labels: jsapi, DocumentationNeeded, ReleaseNotesNeeded

#3917 Remove ungroupAllBut
  engine/api/src/main/java/io/deephaven/engine/table/Table.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/TableDefaults.java
Labels: query engine, NoDocumentationNeeded, breaking, ReleaseNotesNeeded

#3919 Remove mergeBefore / mergeAfter
  engine/api/src/main/java/io/deephaven/engine/table/Table.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/TableDefaults.java
Labels: query engine, NoDocumentationNeeded, breaking, ReleaseNotesNeeded

#3916 Move getColumn to DataAccessHelpers
  Plot/src/main/java/io/deephaven/plot/util/PlotUtils.java
  Plot/src/main/java/io/deephaven/plot/util/tables/ColumnHandlerFactory.java
  engine/api/src/main/java/io/deephaven/engine/table/Table.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/DataAccessHelpers.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/TableAdapter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/TableDefaults.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/UncoalescedTable.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableAggregationTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableAjTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableJoinTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableNaturalJoinTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableSelectUpdateTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableSliceTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableSortTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableWhereTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableWouldMatchTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestAggBy.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestConcurrentInstantiation.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestPartitionAwareSourceTable.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestPartitionBy.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestSharedContext.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestSort.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestTotalsTable.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/by/TestSortedFirstOrLastByFactory.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/select/TestClockFilters.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/select/WhereFilterFactoryTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestCumMinMax.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestCumProd.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestCumSum.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestDelta.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestEmMinMax.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestEmStd.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestEma.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestEms.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestForwardFill.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestRollingAvg.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestRollingCount.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestRollingGroup.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestRollingMinMax.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestRollingProduct.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestRollingStd.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestRollingSum.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestRollingWAvg.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/util/CumulativeUtilTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/util/TestSyncTableFilter.java
  engine/table/src/test/java/io/deephaven/engine/util/TestCalendarMethodsFromTable.java
  engine/table/src/test/java/io/deephaven/engine/util/TestColorUtil.java
  engine/table/src/test/java/io/deephaven/engine/util/TestOuterJoinTools.java
  engine/table/src/test/java/io/deephaven/engine/util/TestTableTools.java
  extensions/csv/src/main/java/io/deephaven/csv/CsvTools.java
  extensions/csv/src/test/java/io/deephaven/csv/TestCsvTools.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/TestParquetTools.java
  extensions/performance/src/main/java/io/deephaven/engine/table/impl/util/PerformanceQueriesGeneral.java
  java-client/barrage-examples/src/main/java/io/deephaven/client/examples/SnapshotExampleBase.java
  java-client/barrage-examples/src/main/java/io/deephaven/client/examples/SubscribeExampleBase.java
  py/server/deephaven/numpy.py
  py/server/deephaven/pandas.py
  server/test/src/main/java/io/deephaven/server/test/FlightMessageRoundTripTest.java
Labels: query engine, NoDocumentationNeeded, breaking, ReleaseNotesNeeded

#3922 Wire up numRows and isStatic for TableHandle.
  cpp-client/deephaven/client/include/private/deephaven/client/impl/table_handle_impl.h
  cpp-client/deephaven/client/include/private/deephaven/client/impl/table_handle_manager_impl.h
  cpp-client/deephaven/client/include/public/deephaven/client/client.h
  cpp-client/deephaven/client/include/public/deephaven/client/utility/table_maker.h
  cpp-client/deephaven/client/src/client.cc
  cpp-client/deephaven/client/src/impl/table_handle_impl.cc
  cpp-client/deephaven/client/src/impl/table_handle_manager_impl.cc
  cpp-client/deephaven/client/src/utility/table_maker.cc
  cpp-client/tests/CMakeLists.txt
  cpp-client/tests/attributes_test.cc
  cpp-client/tests/new_table_test.cc
  cpp-client/tests/select_test.cc
  cpp-client/tests/sort_test.cc
  cpp-client/tests/test_util.cc
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#3918 Move getRecord to DataAccessHelpers
  engine/api/src/main/java/io/deephaven/engine/table/Table.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/DataAccessHelpers.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/KeyedTableListener.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/TableAdapter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/UncoalescedTable.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/MultiColumnSortTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestAggBy.java
Labels: query engine, NoDocumentationNeeded, breaking, NoReleaseNotesNeeded

#3924 C++ client: TableHandles release on the server when client is done with them
  cpp-client/deephaven/client/include/private/deephaven/client/impl/table_handle_impl.h
  cpp-client/deephaven/client/include/private/deephaven/client/impl/table_handle_manager_impl.h
  cpp-client/deephaven/client/include/private/deephaven/client/server/server.h
  cpp-client/deephaven/client/include/public/deephaven/client/client.h
  cpp-client/deephaven/client/src/impl/table_handle_impl.cc
  cpp-client/deephaven/client/src/impl/table_handle_manager_impl.cc
  cpp-client/deephaven/client/src/server/server.cc
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#3879 R Client 1.0
  .github/CODEOWNERS
  .gitignore
  R/rdeephaven/.gitignore
  R/rdeephaven/DESCRIPTION
  R/rdeephaven/LICENSE
  R/rdeephaven/NAMESPACE
  R/rdeephaven/R/client_options_wrapper.R
  R/rdeephaven/R/client_wrapper.R
  R/rdeephaven/R/exports.R
  R/rdeephaven/R/table_handle_wrapper.R
  R/rdeephaven/Read-and-delete-me
  R/rdeephaven/lib/build-cpp.sh
  R/rdeephaven/lib/cpp-dependencies/build-dependencies.sh
  R/rdeephaven/man/Client.Rd
  R/rdeephaven/man/ClientOptions.Rd
  R/rdeephaven/man/rdeephaven-package.Rd
  R/rdeephaven/src/CMakeLists.txt
  R/rdeephaven/src/Makevars
  R/rdeephaven/src/RcppExports.cpp
  R/rdeephaven/src/client.cpp
  R/rdeephaven/tests/testthat.R
  R/rdeephaven/tests/testthat/client_infrastructure.R
  R/rdeephaven/tests/testthat/test_client.R
  cpp-client/LICENSE
Labels: feature request, DocumentationNeeded, NoReleaseNotesNeeded, r-client

#3926 Post release bump to 0.26.0
  authorization-codegen/protoc-gen-contextual-auth-wiring
  authorization-codegen/protoc-gen-service-auth-wiring
  buildSrc/src/main/groovy/io.deephaven.common-conventions.gradle
  py/client/README.md
  py/client/pydeephaven/__init__.py
  py/client/setup.py
  py/embedded-server/deephaven_server/__init__.py
  py/server/deephaven/__init__.py
Labels: NoDocumentationNeeded, version-bump, ReleaseNotesNeeded

#3929 Improve CI uploaded artifacts
  .github/workflows/check-ci.yml
  .github/workflows/nightly-check-ci.yml
Labels: ci, NoDocumentationNeeded, NoReleaseNotesNeeded

#3932 Fix UpdateGraph not always available to performance trackers
  engine/table/src/main/java/io/deephaven/engine/table/impl/perf/UpdatePerformanceTracker.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/ServerStateTracker.java
  engine/table/src/main/java/io/deephaven/engine/tablelogger/impl/memory/MemoryTableLogger.java
Labels: bug, NoDocumentationNeeded, release blocker, NoReleaseNotesNeeded

#3928 Fix RowRedirectionLockFreeTest: Prevent Succeeding If Thread Fails
  engine/table/src/test/java/io/deephaven/engine/table/impl/util/RowRedirectionLockFreeTest.java
Labels: bug, test, NoDocumentationNeeded, NoReleaseNotesNeeded

#3933 Fix TestTableTools: wrong junit version
  engine/table/src/test/java/io/deephaven/engine/util/TestTableTools.java
Labels: bug, test, NoDocumentationNeeded, NoReleaseNotesNeeded

#3935 SessionState: Hold Open ExecutionContext During Perf-log Invocations
  server/src/main/java/io/deephaven/server/session/SessionState.java
Labels: grpc, NoDocumentationNeeded, NoReleaseNotesNeeded

#3942 Several JS API totals table fixes
  web/client-api/src/main/java/io/deephaven/web/client/api/JsTable.java
  web/client-api/src/main/java/io/deephaven/web/client/api/JsTotalsTableConfig.java
  web/client-api/src/main/java/io/deephaven/web/client/api/tree/enums/JsAggregationOperation.java
  web/client-api/src/main/java/io/deephaven/web/public/totals_tables.html
Labels: jsapi, NoDocumentationNeeded, ReleaseNotesNeeded

#3937 Consistently use lastVisibleState to read column information
  web/client-api/src/main/java/io/deephaven/web/client/api/subscription/TableViewportSubscription.java
Labels: jsapi, NoDocumentationNeeded, ReleaseNotesNeeded

#3945 Improve ReinterpretUtils for ZonedDateTime conversion, and generally enhance time conversion support
  engine/chunk/src/main/java/io/deephaven/chunk/ByteChunk.java
  engine/chunk/src/main/java/io/deephaven/chunk/CharChunk.java
  engine/chunk/src/main/java/io/deephaven/chunk/DoubleChunk.java
  engine/chunk/src/main/java/io/deephaven/chunk/FloatChunk.java
  engine/chunk/src/main/java/io/deephaven/chunk/IntChunk.java
  engine/chunk/src/main/java/io/deephaven/chunk/LongChunk.java
  engine/chunk/src/main/java/io/deephaven/chunk/ObjectChunk.java
  engine/chunk/src/main/java/io/deephaven/chunk/ShortChunk.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/ChunkedOperatorAggregationHelper.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/ssmcountdistinct/distinct/LongChunkedDistinctOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/ssmcountdistinct/distinct/LongRollupDistinctOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/ssmcountdistinct/unique/LongChunkedUniqueOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/ssmcountdistinct/unique/LongRollupUniqueOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/ssmpercentile/SsmChunkedPercentileOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/ReinterpretedColumn.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/BoxedColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/LongArraySource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/LongAsInstantColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/LongAsLocalDateColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/LongAsLocalTimeColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/LongAsTimeSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/LongAsZonedDateTimeColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/LongSparseArraySource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/NanosBasedTimeArraySource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/NanosBasedTimeSparseArraySource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/ReinterpretUtils.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/immutable/Immutable2DLongArraySource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/immutable/Immutable2DNanosBasedTimeArraySource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/immutable/ImmutableConstantLongSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/immutable/ImmutableConstantNanosBasedTimeSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/immutable/ImmutableLongArraySource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/immutable/ImmutableNanosBasedTimeArraySource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/RegionedColumnSourceLong.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/RegionedColumnSourceZonedDateTime.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/ring/AddsToRingsListener.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/TableTimeConversions.java
  replication/static/src/main/java/io/deephaven/replicators/ReplicateRegionsAndRegionedSources.java
  replication/static/src/main/java/io/deephaven/replicators/ReplicateSegmentedSortedMultiset.java
  replication/static/src/main/java/io/deephaven/replicators/ReplicateSourcesAndChunks.java
Labels: bug, query engine, core, NoDocumentationNeeded, ReleaseNotesNeeded

#3947 Wrap update graph
  py/server/deephaven/execution_context.py
  py/server/deephaven/table.py
  py/server/deephaven/table_listener.py
  py/server/deephaven/update_graph.py
  py/server/test_helper/__init__.py
Labels: NoDocumentationNeeded, python-server-side, NoReleaseNotesNeeded

#3948 Minimal support for TLS connection and extra headers in python and C++ clients.
  cpp-client/deephaven/client/CMakeLists.txt
  cpp-client/deephaven/client/include/private/deephaven/client/server/server.h
  cpp-client/deephaven/client/include/public/deephaven/client/client.h
  cpp-client/deephaven/client/include/public/deephaven/client/client_options.h
  cpp-client/deephaven/client/include/public/deephaven/client/flight.h
  cpp-client/deephaven/client/src/client.cc
  cpp-client/deephaven/client/src/client_options.cc
  cpp-client/deephaven/client/src/flight.cc
  cpp-client/deephaven/client/src/impl/table_handle_impl.cc
  cpp-client/deephaven/client/src/server/server.cc
  cpp-client/deephaven/client/src/subscription/subscribe_thread.cc
  cpp-client/deephaven/client/src/utility/table_maker.cc
  cpp-examples/create_table_with_arrow_flight/main.cc
  cpp-examples/read_csv/main.cc
  py/client/pydeephaven/_session_service.py
  py/client/pydeephaven/session.py
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#3940 Add blink time_table support
  py/server/deephaven/table_factory.py
  py/server/tests/test_table_factory.py
Labels: DocumentationNeeded, python-server-side, NoReleaseNotesNeeded

#3970 Fix sending duplicate headers from the python client.
  py/client/pydeephaven/_arrow_flight_service.py
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#3836 Remove docs blog and conceptual ticket autogeneration
  .github/workflows/create-docs-issues.js
Labels: NoDocumentationNeeded, internal, NoReleaseNotesNeeded

#3952 Ensure AuthContext is Available to Table Loggers
  Stats/build.gradle
  Stats/src/main/java/io/deephaven/stats/StatsDriver.java
  buildSrc/src/main/groovy/io.deephaven.java-classpath-conventions.gradle
  engine/context/build.gradle
  engine/table/src/main/java/io/deephaven/engine/table/impl/perf/UpdatePerformanceTracker.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/ServerStateTracker.java
  engine/table/src/main/java/io/deephaven/stats/Driver.java
Labels: feature request, NoDocumentationNeeded, authorization, authentication, NoReleaseNotesNeeded

#3972 List java.time.Instant as the primary classname for datetime types
  web/client-api/src/main/java/io/deephaven/web/client/api/parse/JsDataHandler.java
Labels: bug, jsapi, NoDocumentationNeeded, ReleaseNotesNeeded

#3981 Remove nightly-benchmarks.yml
  .github/workflows/nightly-benchmarks.yml
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#3984 Set jvm_maxmem on init_jvm
  .github/env/Linux/gradle.properties
  py/jpy-integration/src/pythonToJava/python/java_debug.py
  py/jpy-integration/src/pythonToJava/python/test/test_jpy.py
  py/server/test_helper/__init__.py
  sphinx/source/conf.py
Labels: test, NoDocumentationNeeded, NoReleaseNotesNeeded

#3979 PeriodicUpdateGraph: Fix thread count and initialization order bugs; update_graph.py: Don't deadlock transforms via auto-locking
  engine/context/src/test/java/io/deephaven/engine/context/TestQueryCompiler.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/rangejoin/RangeJoinOperation.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/ColumnRegionObject.java
  engine/table/src/main/java/io/deephaven/engine/updategraph/impl/PeriodicUpdateGraph.java
  engine/test-utils/src/main/java/io/deephaven/engine/context/TestExecutionContext.java
  engine/test-utils/src/main/java/io/deephaven/engine/testutil/ControlledUpdateGraph.java
  py/server/deephaven/update_graph.py
  server/test/src/main/java/io/deephaven/server/test/FlightMessageRoundTripTest.java
Labels: bug, query engine, core, NoDocumentationNeeded, user-reported, ReleaseNotesNeeded

#3961 Create BarrageChunkAppendingMarshaller ideal for TableDataService Usage
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/ReinterpretUtils.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/ArrowToTableConverter.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/BarrageChunkAppendingMarshaller.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/BarrageMarshallingException.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/BarrageStreamReader.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/BarrageUtil.java
  java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshotImpl.java
  java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java
  java-client/session/src/main/java/io/deephaven/client/impl/BearerHandler.java
  server/src/test/java/io/deephaven/server/barrage/BarrageBlinkTableTest.java
  server/test/src/main/java/io/deephaven/server/test/FlightMessageRoundTripTest.java
Labels: barrage, NoDocumentationNeeded, arrow, release blocker, NoReleaseNotesNeeded

#3983 Our UsePreviousValues implementations generally need to care about satisfaction, rather than just last notification step
  engine/table/src/main/java/io/deephaven/engine/table/impl/BaseTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/ConstituentDependency.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/InstrumentedTableListenerBase.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/MergedListener.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/SourceTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/SwapListener.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/SwapListenerEx.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/WhereListener.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/remote/ConstructSnapshot.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/StepUpdater.java
  engine/table/src/main/java/io/deephaven/engine/updategraph/impl/PeriodicUpdateGraph.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestConcurrentInstantiation.java
  engine/updategraph/src/main/java/io/deephaven/engine/updategraph/ClockInconsistencyException.java
  engine/updategraph/src/main/java/io/deephaven/engine/updategraph/LogicalClockImpl.java
  engine/updategraph/src/main/java/io/deephaven/engine/updategraph/NotificationQueue.java
  server/src/main/java/io/deephaven/server/barrage/BarrageMessageProducer.java
  server/src/test/java/io/deephaven/server/table/ExportTableUpdateListenerTest.java
Labels: bug, query engine, core, NoDocumentationNeeded, user-reported, ReleaseNotesNeeded

#3998 Improve the release process to better handle PyPi upload failures
  .github/workflows/publish-ci.yml
  RELEASE.md
Labels: ci, NoDocumentationNeeded, NoReleaseNotesNeeded

#3939 Update R6 class documentation in R Client
  R/rdeephaven/R/client_options_wrapper.R
  R/rdeephaven/R/client_wrapper.R
  R/rdeephaven/R/table_handle_wrapper.R
  R/rdeephaven/README.md
  R/rdeephaven/man/Client.Rd
  R/rdeephaven/man/ClientOptions.Rd
  R/rdeephaven/man/TableHandle.Rd
  R/rdeephaven/man/rdeephaven-package.Rd
Labels: documentation, NoDocumentationNeeded, NoReleaseNotesNeeded, r-client

#4004 Bump guava to 32.0.1-jre
  buildSrc/src/main/groovy/Classpaths.groovy
Labels: security, NoDocumentationNeeded, version-bump, NoReleaseNotesNeeded

#4006 Python client documentation: use code formatting and cross-references
  py/client/docs/source/examples.rst
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4000 Update versions of C++ dependent libraries, take 2.
  cpp-client/deephaven/client/CMakeLists.txt
  docker/registry/cpp-client-base/gradle.properties
  docker/registry/protoc-base/gradle.properties
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#3669 Correctly mark optional properties and union types in TypeScript definitions
  web/client-api/client-api.gradle
  web/client-api/src/main/java/io/deephaven/web/client/api/CoreClient.java
  web/client-api/src/main/java/io/deephaven/web/client/api/JsTable.java
  web/client-api/src/main/java/io/deephaven/web/client/api/JsTotalsTable.java
  web/client-api/src/main/java/io/deephaven/web/client/api/TableData.java
  web/client-api/src/main/java/io/deephaven/web/client/api/filter/FilterValue.java
  web/client-api/src/main/java/io/deephaven/web/client/api/i18n/JsNumberFormat.java
  web/client-api/src/main/java/io/deephaven/web/client/api/subscription/SubscriptionTableData.java
  web/client-api/src/main/java/io/deephaven/web/client/api/tree/JsRollupConfig.java
  web/client-api/src/main/java/io/deephaven/web/client/api/tree/JsTreeTable.java
  web/client-api/src/main/java/io/deephaven/web/client/api/widget/plot/JsAxisDescriptor.java
  web/client-api/src/main/java/io/deephaven/web/client/api/widget/plot/JsChartDescriptor.java
  web/client-api/src/main/java/io/deephaven/web/client/api/widget/plot/JsFigureDescriptor.java
  web/client-api/src/main/java/io/deephaven/web/client/api/widget/plot/JsSeriesDescriptor.java
  web/client-api/src/main/java/io/deephaven/web/client/ide/IdeConnection.java
  web/client-api/src/main/java/io/deephaven/web/client/ide/LspTranslate.java
  web/client-api/src/main/java/io/deephaven/web/shared/ide/lsp/CompletionItem.java
  web/client-api/src/main/java/io/deephaven/web/shared/ide/lsp/SignatureInformation.java
  web/client-api/src/test/java/io/deephaven/web/client/api/filter/FilterConditionTestGwt.java
  web/shared-beans/src/main/java/io/deephaven/web/shared/fu/JsArrays.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4015 Update cpp client roaring version to v1.3.0
  cpp-client/deephaven/dhcore/third_party/roaring/include/roaring/roaring.c
  cpp-client/deephaven/dhcore/third_party/roaring/include/roaring/roaring.h
  cpp-client/deephaven/dhcore/third_party/roaring/include/roaring/roaring.hh
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4008 Bump protobuf-java to 3.23.0
  buildSrc/src/main/groovy/Classpaths.groovy
Labels: security, NoDocumentationNeeded, NoReleaseNotesNeeded

#4001 Update R Client to keep up with cpp client, add is_static and num_rows
  R/rdeephaven/R/client_wrapper.R
  R/rdeephaven/R/table_handle_wrapper.R
  R/rdeephaven/man/ClientOptions.Rd
  R/rdeephaven/man/TableHandle.Rd
  R/rdeephaven/src/client.cpp
Labels: bug, NoDocumentationNeeded, NoReleaseNotesNeeded, r-client

#4019 Small C++ client README tweaks.
  cpp-client/README.md
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4024 C++ client changes : API when using doPut, and dependency tracking
  cpp-client/deephaven/client/CMakeLists.txt
  cpp-client/deephaven/client/include/private/deephaven/client/arrowutil/arrow_flight.h
  cpp-client/deephaven/client/include/private/deephaven/client/arrowutil/arrow_traits.h
  cpp-client/deephaven/client/include/private/deephaven/client/impl/table_handle_impl.h
  cpp-client/deephaven/client/include/private/deephaven/client/impl/table_handle_manager_impl.h
  cpp-client/deephaven/client/include/private/deephaven/client/server/server.h
  cpp-client/deephaven/client/include/public/deephaven/client/client.h
  cpp-client/deephaven/client/include/public/deephaven/client/flight.h
  cpp-client/deephaven/client/include/public/deephaven/client/utility/arrow_util.h
  cpp-client/deephaven/client/include/public/deephaven/client/utility/table_maker.h
  cpp-client/deephaven/client/src/arrowutil/arrow_flight.cc
  cpp-client/deephaven/client/src/client.cc
  cpp-client/deephaven/client/src/flight.cc
  cpp-client/deephaven/client/src/impl/table_handle_impl.cc
  cpp-client/deephaven/client/src/impl/table_handle_manager_impl.cc
  cpp-client/deephaven/client/src/server/server.cc
  cpp-client/deephaven/client/src/utility/arrow_util.cc
  cpp-client/deephaven/client/src/utility/table_maker.cc
  cpp-client/tests/attributes_test.cc
  cpp-client/tests/new_table_test.cc
  cpp-client/tests/select_test.cc
  cpp-client/tests/sort_test.cc
  cpp-client/tests/test_util.cc
  cpp-examples/create_table_with_arrow_flight/main.cc
  cpp-examples/read_csv/main.cc
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4028 Rename Table to ClientTable and move to different namespace, in order to reduce terminology confusion.
  cpp-client/deephaven/client/include/private/deephaven/client/impl/table_handle_impl.h
  cpp-client/deephaven/client/include/private/deephaven/client/subscription/subscribe_thread.h
  cpp-client/deephaven/client/src/impl/table_handle_impl.cc
  cpp-client/deephaven/client/src/subscription/subscribe_thread.cc
  cpp-client/deephaven/dhcore/CMakeLists.txt
  cpp-client/deephaven/dhcore/include/private/deephaven/dhcore/ticking/immer_table_state.h
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/clienttable/client_table.h
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/clienttable/schema.h
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/ticking/barrage_processor.h
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/ticking/ticking.h
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/utility/cython_support.h
  cpp-client/deephaven/dhcore/src/clienttable/client_table.cc
  cpp-client/deephaven/dhcore/src/clienttable/schema.cc
  cpp-client/deephaven/dhcore/src/ticking/barrage_processor.cc
  cpp-client/deephaven/dhcore/src/ticking/immer_table_state.cc
  cpp-client/deephaven/dhcore/src/utility/cython_support.cc
  cpp-examples/demos/chapter2.cc
  cpp-examples/demos/chapter3.cc
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4022 Call _refresh_token only when session is alive
  py/client/pydeephaven/session.py
  py/client/tests/test_session.py
Labels: NoDocumentationNeeded, python-client, NoReleaseNotesNeeded

#3996 Move globals scan and exec context scope to Server constructor
  py/embedded-server/java-runtime/src/main/java/io/deephaven/python/server/EmbeddedServer.java
Labels: NoDocumentationNeeded, python-server-side, ReleaseNotesNeeded

#4031 Small tweaks to the README.md for cpp-client.
  cpp-client/README.md
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4025 Change R client build to depend on a preexisting build of the C++ client.
  R/rdeephaven/README.md
  R/rdeephaven/lib/build-cpp.sh
  R/rdeephaven/lib/cpp-dependencies/build-dependencies.sh
  R/rdeephaven/src/Makevars
  R/rdeephaven/src/client.cpp
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4034 Modify C++ and R client wrapper to keep up with cpp client changes
  R/rdeephaven/R/client_wrapper.R
  R/rdeephaven/Read-and-delete-me
  R/rdeephaven/src/client.cpp
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded, r-client

#4039 Update java client for PSK
  java-client/example-utilities/src/main/java/io/deephaven/client/examples/AuthenticationOptions.java
Labels: NoDocumentationNeeded, java-client, NoReleaseNotesNeeded

#4035 Improve heap usage configurations
  .github/env/Linux/gradle.properties
  Integrations/build.gradle
  gradle.properties
  py/server/test_helper/__init__.py
  py/server/tests/__init__.py
Labels: build, ci, NoDocumentationNeeded, NoReleaseNotesNeeded

#3964 Provide a tool to convert python callables to java functional interfaces
  Integrations/src/main/java/io/deephaven/integrations/python/JavaLambdaFactory.java
  py/server/deephaven/jcompat.py
  py/server/tests/test_jcompat.py
Labels: NoDocumentationNeeded, python-server-side, NoReleaseNotesNeeded

#4038 Ignore parentheses when check vectorizability
  engine/table/src/main/java/io/deephaven/engine/table/impl/lang/QueryLanguageParser.java
  py/server/tests/test_vectorization.py
Labels: query engine, NoDocumentationNeeded, python-server-side, NoReleaseNotesNeeded

#4044 Update web version 0.41.3
  web/client-ui/Dockerfile
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4033 Use an ExecutionContext with an AuthContext during DeephavenApiServer#run
  server/src/main/java/io/deephaven/server/runner/DeephavenApiServer.java
Labels: bug, NoDocumentationNeeded, release blocker, NoReleaseNotesNeeded

#3955 Port Symbol table aggregation improvements from DHE
  engine/table/src/main/java/io/deephaven/engine/table/impl/BucketingContext.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/NaturalJoinHelper.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/SymbolTableToUniqueIdSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/AggregationControl.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/ChunkedOperatorAggregationHelper.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/StaticSymbolTableChunkedOperatorAggregationStateManager.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/SymbolTableSource.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableAggregationTest.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4009 Bump sslcontext-kickstart to 8.1.1
  buildSrc/src/main/groovy/Classpaths.groovy
  java-client/session/src/main/java/io/deephaven/client/impl/ChannelHelper.java
  server/jetty/src/main/java/io/deephaven/server/jetty/JettyBackedGrpcServer.java
  server/netty/src/main/java/io/deephaven/server/netty/NettyServerModule.java
Labels: NoDocumentationNeeded, version-bump, NoReleaseNotesNeeded

#4010 Bump groovy to 3.0.17
  buildSrc/src/main/groovy/Classpaths.groovy
Labels: NoDocumentationNeeded, version-bump, ReleaseNotesNeeded

#4002 Update Visitor pattern for qst Type / array
  engine/api/src/main/java/io/deephaven/engine/table/ColumnDefinition.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/TableCreatorImpl.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/ArrayBackedColumnSource.java
  java-client/flight/src/main/java/io/deephaven/client/impl/FieldAdapter.java
  java-client/flight/src/main/java/io/deephaven/client/impl/FieldVectorAdapter.java
  java-client/session/src/main/java/io/deephaven/client/impl/BatchTableRequestBuilder.java
  qst/src/main/java/io/deephaven/qst/array/Array.java
  qst/src/main/java/io/deephaven/qst/array/BooleanArray.java
  qst/src/main/java/io/deephaven/qst/array/ByteArray.java
  qst/src/main/java/io/deephaven/qst/array/CharArray.java
  qst/src/main/java/io/deephaven/qst/array/DoubleArray.java
  qst/src/main/java/io/deephaven/qst/array/FloatArray.java
  qst/src/main/java/io/deephaven/qst/array/GenericArray.java
  qst/src/main/java/io/deephaven/qst/array/IntArray.java
  qst/src/main/java/io/deephaven/qst/array/LongArray.java
  qst/src/main/java/io/deephaven/qst/array/PrimitiveArray.java
  qst/src/main/java/io/deephaven/qst/array/PrimitiveArrayBase.java
  qst/src/main/java/io/deephaven/qst/array/ShortArray.java
  qst/src/main/java/io/deephaven/qst/array/TypeToArrayBuilder.java
  qst/src/main/java/io/deephaven/qst/table/Clock.java
  qst/src/main/java/io/deephaven/qst/table/ClockSystem.java
  qst/src/main/java/io/deephaven/qst/table/InMemoryAppendOnlyInputTable.java
  qst/src/main/java/io/deephaven/qst/table/InMemoryKeyBackedInputTable.java
  qst/src/main/java/io/deephaven/qst/table/InputTable.java
  qst/src/main/java/io/deephaven/qst/table/TableLabelVisitor.java
  qst/src/main/java/io/deephaven/qst/type/ArrayType.java
  qst/src/main/java/io/deephaven/qst/type/ArrayTypeBase.java
  qst/src/main/java/io/deephaven/qst/type/BooleanType.java
  qst/src/main/java/io/deephaven/qst/type/ByteType.java
  qst/src/main/java/io/deephaven/qst/type/CharType.java
  qst/src/main/java/io/deephaven/qst/type/CustomType.java
  qst/src/main/java/io/deephaven/qst/type/DoubleType.java
  qst/src/main/java/io/deephaven/qst/type/FloatType.java
  qst/src/main/java/io/deephaven/qst/type/GenericType.java
  qst/src/main/java/io/deephaven/qst/type/GenericTypeBase.java
  qst/src/main/java/io/deephaven/qst/type/GenericVectorType.java
  qst/src/main/java/io/deephaven/qst/type/InstantType.java
  qst/src/main/java/io/deephaven/qst/type/IntType.java
  qst/src/main/java/io/deephaven/qst/type/LongType.java
  qst/src/main/java/io/deephaven/qst/type/NativeArrayType.java
  qst/src/main/java/io/deephaven/qst/type/PrimitiveType.java
  qst/src/main/java/io/deephaven/qst/type/PrimitiveTypeBase.java
  qst/src/main/java/io/deephaven/qst/type/PrimitiveVectorType.java
  qst/src/main/java/io/deephaven/qst/type/ShortType.java
  qst/src/main/java/io/deephaven/qst/type/StringType.java
  qst/src/main/java/io/deephaven/qst/type/Type.java
  qst/src/main/java/io/deephaven/qst/type/TypeHelper.java
  sql/src/main/java/io/deephaven/sql/TypeAdapter.java
Labels: NoDocumentationNeeded, breaking, ReleaseNotesNeeded

#4049 Fixes to merge, and OperationInitializationThreadPool initialization changes
  engine/api/src/main/java/io/deephaven/engine/table/PartitionedTableFactory.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/InitialFilterExecution.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/OperationInitializationThreadPool.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/partitioned/PartitionedTableCreatorImpl.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/OperationInitializationPoolJobScheduler.java
  engine/table/src/main/java/io/deephaven/engine/util/TableToolsMergeHelper.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableWhereTest.java
  server/src/main/java/io/deephaven/server/runner/DeephavenApiServer.java
Labels: bug, query engine, core, NoDocumentationNeeded, partitioned_tables, ReleaseNotesNeeded

#3954 Break out DeephavenApiServerModule implementation Modules
  server/src/main/java/io/deephaven/server/grpc/GrpcModule.java
  server/src/main/java/io/deephaven/server/runner/DeephavenApiServerModule.java
  server/src/main/java/io/deephaven/server/runner/scheduler/SchedulerModule.java
  server/src/main/java/io/deephaven/server/runner/updategraph/UpdateGraphModule.java
  server/src/main/java/io/deephaven/server/session/ScriptSessionModule.java
Labels: NoDocumentationNeeded, dagger, NoReleaseNotesNeeded

#4047 Address reported bug in Flight Boolean Columns
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/BarrageUtil.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4054 More explanations in README.md; update build-cpp-protos.sh to the lat…
  cpp-client/README.md
  proto/proto-backplane-grpc/src/main/proto/build-cpp-protos.sh
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4042 GRPC: Allow string duration parameters for UpdateBy ema/rolling windows
  cpp-client/deephaven/client/proto/deephaven/proto/table.pb.cc
  cpp-client/deephaven/client/proto/deephaven/proto/table.pb.h
  go/internal/proto/table/table.pb.go
  java-client/session/src/main/java/io/deephaven/client/impl/UpdateByBuilder.java
  java-client/session/src/test/java/io/deephaven/client/impl/UpdateBySpecBuilderTest.java
  proto/proto-backplane-grpc/src/main/proto/deephaven/proto/table.proto
  py/client/pydeephaven/proto/table_pb2.py
  py/client/pydeephaven/updateby.py
  py/client/tests/test_updateby.py
  py/server/tests/test_updateby.py
  server/src/main/java/io/deephaven/server/table/ops/UpdateByGrpcImpl.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4060 Fix accidental double-freeing of log entries and fix LogEntry API
  IO/src/main/java/io/deephaven/io/log/LogEntry.java
  IO/src/main/java/io/deephaven/io/log/impl/DelayedLogEntryImpl.java
  IO/src/main/java/io/deephaven/io/log/impl/DelayedLogEntryImpl2.java
  IO/src/main/java/io/deephaven/io/log/impl/LogEntryImpl.java
  IO/src/test/java/io/deephaven/io/log/impl/ConsolidatingLogEntry.java
  authentication/example-providers/psk/src/main/java/io/deephaven/authentication/psk/PskAuthenticationHandler.java
  authentication/src/main/java/io/deephaven/auth/AnonymousAuthenticationHandler.java
  log-factory/sinks/log-to-slf4j/src/main/java/io/deephaven/internal/log/LoggerSlf4j.java
Labels: bug, logging, NoDocumentationNeeded, breaking, ReleaseNotesNeeded

#4061 Java Arrow: Upgrade to 12.0.1; Use CommonsCompressionFactory for Feather
  buildSrc/src/main/groovy/Classpaths.groovy
  extensions/arrow/build.gradle
  extensions/arrow/src/main/java/io/deephaven/extensions/arrow/ArrowWrapperTools.java
Labels: bug, NoDocumentationNeeded, arrow, ReleaseNotesNeeded

#3994 Add new `update_by` operators to python client
  py/client/pydeephaven/updateby.py
  py/client/tests/test_query.py
  py/client/tests/test_updateby.py
  py/server/deephaven/updateby.py
  py/server/tests/test_updateby.py
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4016 Better handling for uncommon/exception gRPC cases
  grpc-java/grpc-servlet-jakarta/src/main/java/io/grpc/servlet/jakarta/ServletServerStream.java
  grpc-java/grpc-servlet-jakarta/src/main/java/io/grpc/servlet/jakarta/web/GrpcWebFilter.java
  grpc-java/grpc-servlet-jakarta/src/main/java/io/grpc/servlet/jakarta/web/GrpcWebOutputStream.java
  grpc-java/grpc-servlet-jakarta/src/main/java/io/grpc/servlet/jakarta/web/GrpcWebServletRequest.java
  grpc-java/grpc-servlet-jakarta/src/main/java/io/grpc/servlet/jakarta/web/GrpcWebServletResponse.java
Labels: grpc, NoDocumentationNeeded, ReleaseNotesNeeded

#4057 Auto publish pydeephaven
  .github/workflows/publish-ci.yml
Labels: ci, NoDocumentationNeeded, NoReleaseNotesNeeded

#4020 Improve error feedback when reading flight streams
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/BarrageUtil.java
  server/src/main/java/io/deephaven/server/arrow/ArrowFlightUtil.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#4071 Update TableSpec.Visitor pattern
  engine/table/src/main/java/io/deephaven/engine/table/impl/TableCreatorImpl.java
  java-client/session/src/main/java/io/deephaven/client/impl/BatchTableRequestBuilder.java
  qst/src/main/java/io/deephaven/qst/TableAdapterImpl.java
  qst/src/main/java/io/deephaven/qst/table/AggregateAllTable.java
  qst/src/main/java/io/deephaven/qst/table/AggregateTable.java
  qst/src/main/java/io/deephaven/qst/table/AsOfJoinTable.java
  qst/src/main/java/io/deephaven/qst/table/DropColumnsTable.java
  qst/src/main/java/io/deephaven/qst/table/EmptyTable.java
  qst/src/main/java/io/deephaven/qst/table/ExactJoinTable.java
  qst/src/main/java/io/deephaven/qst/table/HeadTable.java
  qst/src/main/java/io/deephaven/qst/table/InputTableBase.java
  qst/src/main/java/io/deephaven/qst/table/JoinTable.java
  qst/src/main/java/io/deephaven/qst/table/LazyUpdateTable.java
  qst/src/main/java/io/deephaven/qst/table/LinkDescriber.java
  qst/src/main/java/io/deephaven/qst/table/MergeTable.java
  qst/src/main/java/io/deephaven/qst/table/NaturalJoinTable.java
  qst/src/main/java/io/deephaven/qst/table/NewTable.java
  qst/src/main/java/io/deephaven/qst/table/ParentsVisitor.java
  qst/src/main/java/io/deephaven/qst/table/RangeJoinTable.java
  qst/src/main/java/io/deephaven/qst/table/ReverseTable.java
  qst/src/main/java/io/deephaven/qst/table/SelectDistinctTable.java
  qst/src/main/java/io/deephaven/qst/table/SelectTable.java
  qst/src/main/java/io/deephaven/qst/table/SnapshotTable.java
  qst/src/main/java/io/deephaven/qst/table/SnapshotWhenTable.java
  qst/src/main/java/io/deephaven/qst/table/SortTable.java
  qst/src/main/java/io/deephaven/qst/table/TableBase.java
  qst/src/main/java/io/deephaven/qst/table/TableHeader.java
  qst/src/main/java/io/deephaven/qst/table/TableLabelVisitor.java
  qst/src/main/java/io/deephaven/qst/table/TableSchema.java
  qst/src/main/java/io/deephaven/qst/table/TableSpec.java
  qst/src/main/java/io/deephaven/qst/table/TableVisitorGeneric.java
  qst/src/main/java/io/deephaven/qst/table/TailTable.java
  qst/src/main/java/io/deephaven/qst/table/TicketTable.java
  qst/src/main/java/io/deephaven/qst/table/TimeTable.java
  qst/src/main/java/io/deephaven/qst/table/UngroupTable.java
  qst/src/main/java/io/deephaven/qst/table/UpdateByTable.java
  qst/src/main/java/io/deephaven/qst/table/UpdateTable.java
  qst/src/main/java/io/deephaven/qst/table/UpdateViewTable.java
  qst/src/main/java/io/deephaven/qst/table/ViewTable.java
  qst/src/main/java/io/deephaven/qst/table/WhereInTable.java
  qst/src/main/java/io/deephaven/qst/table/WhereTable.java
Labels: NoDocumentationNeeded, qst, breaking, ReleaseNotesNeeded

#4066 Added validation for parameters in head_pct and tail_pct (#4011)
  engine/api/src/main/java/io/deephaven/engine/table/Table.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/SliceLikeOperation.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableSliceTest.java
Labels: bug, query engine, core, DocumentationNeeded, NoReleaseNotesNeeded

#4088 Put in the right place the doc for cpp-client's ClientOptions::addIntOption
  cpp-client/deephaven/client/include/public/deephaven/client/client_options.h
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4078 Deliver initial completed notification when subscribed table is empty
  java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java
Labels: bug, barrage, NoDocumentationNeeded, NoReleaseNotesNeeded

#4084 R client unit testing
  R/rdeephaven/R/client_options_wrapper.R
  R/rdeephaven/R/client_wrapper.R
  R/rdeephaven/R/helper_functions.R
  R/rdeephaven/R/table_handle_wrapper.R
  R/rdeephaven/tests/testthat/client_infrastructure.R
  R/rdeephaven/tests/testthat/test_client.R
  R/rdeephaven/tests/testthat/test_client_options_wrapper.R
  R/rdeephaven/tests/testthat/test_client_wrapper.R
  R/rdeephaven/tests/testthat/test_table_handle_wrapper.R
Labels: test, NoDocumentationNeeded, NoReleaseNotesNeeded, r-client

#4096 Fix dependency bug in Kafka ingest, and some debugging cleanup for JobScheduler.TaskInvoker
  Base/src/main/java/io/deephaven/base/log/LogOutput.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/MergedListener.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/JobScheduler.java
  engine/table/src/main/java/io/deephaven/stream/StreamToBlinkTableAdapter.java
  engine/updategraph/src/main/java/io/deephaven/engine/updategraph/OneShotUpdateCombiner.java
  engine/updategraph/src/main/java/io/deephaven/engine/updategraph/UpdateSourceCombiner.java
  engine/updategraph/src/main/java/io/deephaven/engine/updategraph/UpdateSourceRegistrar.java
  extensions/source-support/src/test/java/io/deephaven/generic/region/AppendOnlyFixedSizePageRegionTest.java
Labels: bug, query engine, core, kafka, NoDocumentationNeeded, ReleaseNotesNeeded

#4104 Delete CumulativeUtil (closes #4103).
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/CumulativeUtil.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/util/CumulativeUtilTest.java
Labels: feature request, core, NoDocumentationNeeded, ReleaseNotesNeeded

#4073 Add sortable column check
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/BarrageUtil.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/HierarchicalTableSchemaUtil.java
  go/pkg/client/example_import_table_test.go
  go/pkg/client/example_input_table_test.go
  go/pkg/client/example_table_ops_test.go
  web/client-api/src/main/java/io/deephaven/web/client/api/Column.java
  web/client-api/src/main/java/io/deephaven/web/client/api/Sort.java
  web/client-api/src/main/java/io/deephaven/web/client/api/barrage/WebBarrageUtils.java
  web/client-api/src/main/java/io/deephaven/web/client/api/barrage/def/ColumnDefinition.java
  web/client-api/src/main/java/io/deephaven/web/client/api/tree/JsTreeTable.java
  web/client-api/src/test/java/io/deephaven/web/client/api/filter/FilterConditionTestGwt.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#4107 SimpleKeyOrValueSerializer should respect "previous"
  extensions/kafka/src/main/java/io/deephaven/kafka/publish/SimpleKeyOrValueSerializer.java
Labels: bug, core, kafka, NoDocumentationNeeded, kafka-exhaust, ReleaseNotesNeeded

#4102 Improved version of chip/remove_old_calendars
  Plot/src/main/java/io/deephaven/plot/axistransformations/AxisTransforms.java
  Plot/src/test/java/io/deephaven/plot/axistransformations/TestAxisTransforms.java
  engine/table/src/test/java/io/deephaven/engine/util/TestCalendarMethodsFromTable.java
  engine/time/src/test/java/io/deephaven/time/calendar/TestCalendars.java
  props/configs/src/main/resources/default_calendar_imports.txt
  props/configs/src/main/resources/dh-defaults.prop
  props/test-configs/src/main/resources/calendar/BEIJING.calendar
  props/test-configs/src/main/resources/calendar/DTB.calendar
  props/test-configs/src/main/resources/calendar/GBLO.calendar
  props/test-configs/src/main/resources/calendar/GLOBAL.calendar
  props/test-configs/src/main/resources/calendar/JPOSE.calendar
  props/test-configs/src/main/resources/calendar/LSE.calendar
  props/test-configs/src/main/resources/calendar/MOSCOW.calendar
  props/test-configs/src/main/resources/calendar/MUMBAI.calendar
  props/test-configs/src/main/resources/calendar/USNY.calendar
  props/test-configs/src/main/resources/calendar/USNYSE.calendar
  props/test-configs/src/main/resources/calendar/USNYSEWEEKDAYS.calendar
  props/test-configs/src/main/resources/dh-tests.prop
  props/test-configs/src/main/resources/test_calendar_imports.txt
  py/server/test_helper/__init__.py
Labels: bug, core, DocumentationNeeded, ReleaseNotesNeeded

#4074 SessionService: Inject ErrorTransformer for DHE instead of Forcing Obfuscation
  py/embedded-server/java-runtime/src/main/java/io/deephaven/python/server/EmbeddedServer.java
  server/jetty/src/test/java/io/deephaven/server/jetty/JettyFlightRoundTripTest.java
  server/netty/src/test/java/io/deephaven/server/netty/NettyFlightRoundTripTest.java
  server/src/main/java/io/deephaven/server/arrow/ArrowFlightUtil.java
  server/src/main/java/io/deephaven/server/arrow/FlightServiceGrpcImpl.java
  server/src/main/java/io/deephaven/server/barrage/BarrageMessageProducer.java
  server/src/main/java/io/deephaven/server/hierarchicaltable/HierarchicalTableViewSubscription.java
  server/src/main/java/io/deephaven/server/notebook/FilesystemStorageServiceGrpcImpl.java
  server/src/main/java/io/deephaven/server/runner/CommunityDefaultsModule.java
  server/src/main/java/io/deephaven/server/session/ObfuscatingErrorTransformerModule.java
  server/src/main/java/io/deephaven/server/session/SessionService.java
  server/src/main/java/io/deephaven/server/session/SessionServiceGrpcImpl.java
  server/src/main/java/io/deephaven/server/session/SessionState.java
  server/src/test/java/io/deephaven/server/appmode/ApplicationServiceGrpcImplTest.java
  server/src/test/java/io/deephaven/server/barrage/BarrageBlinkTableTest.java
  server/src/test/java/io/deephaven/server/barrage/BarrageMessageRoundTripTest.java
  server/src/test/java/io/deephaven/server/runner/DeephavenApiServerTestBase.java
  server/src/test/java/io/deephaven/server/session/SessionServiceTest.java
  server/src/test/java/io/deephaven/server/session/SessionStateTest.java
  server/src/test/java/io/deephaven/server/table/ExportTableUpdateListenerTest.java
Labels: grpc, NoDocumentationNeeded, ReleaseNotesNeeded

#4109 A few more cleanups to JobScheduler.IterationManager.TaskInvoker to try to prevent or detect errors
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/JobScheduler.java
Labels: bug, query engine, core, NoDocumentationNeeded, ReleaseNotesNeeded

#4097 Improve error message for null column names and data arrays
  engine/api/src/main/java/io/deephaven/engine/table/ColumnDefinition.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/InMemoryTable.java
  engine/table/src/main/java/io/deephaven/engine/util/TableTools.java
Labels: bug, query engine, core, NoDocumentationNeeded, NoReleaseNotesNeeded

#4094 Add unit testing instructions to Readme
  R/rdeephaven/README.md
Labels: documentation, NoDocumentationNeeded, NoReleaseNotesNeeded

#4081 Add more options to ClientOptions in the R Client
  R/rdeephaven/R/client_options_wrapper.R
  R/rdeephaven/R/client_wrapper.R
  R/rdeephaven/R/helper_functions.R
  R/rdeephaven/man/ClientOptions.Rd
  R/rdeephaven/src/client.cpp
  R/rdeephaven/tests/testthat/test_client_options_wrapper.R
  R/rdeephaven/tests/testthat/test_client_wrapper.R
  R/rdeephaven/tests/testthat/test_table_handle_wrapper.R
Labels: NoDocumentationNeeded, authentication, ReleaseNotesNeeded, r-client

#4110 Replace all EngineTableLoggers
  DHProcess/src/main/java/io/deephaven/process/ProcessInfoStore.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/perf/UpdatePerformanceStreamPublisher.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/perf/UpdatePerformanceTracker.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/EngineMetrics.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/ProcessInfoImpl.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/QueryOperationPerformanceImpl.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/QueryOperationPerformanceStreamPublisher.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/QueryPerformanceImpl.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/QueryPerformanceStreamPublisher.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/ServerStateStreamPublisher.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/ServerStateTracker.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/StatsImpl.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/StatsStreamPublisher.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/TableLoggers.java
  engine/table/src/main/java/io/deephaven/engine/tablelogger/EngineTableLoggers.java
  engine/table/src/main/java/io/deephaven/engine/tablelogger/ProcessInfoLogLogger.java
  engine/table/src/main/java/io/deephaven/engine/tablelogger/ProcessMetricsLogLogger.java
  engine/table/src/main/java/io/deephaven/engine/tablelogger/QueryOperationPerformanceLogLogger.java
  engine/table/src/main/java/io/deephaven/engine/tablelogger/QueryPerformanceLogLogger.java
  engine/table/src/main/java/io/deephaven/engine/tablelogger/ServerStateLogLogger.java
  engine/table/src/main/java/io/deephaven/engine/tablelogger/UpdatePerformanceLogLogger.java
  engine/table/src/main/java/io/deephaven/engine/tablelogger/impl/memory/EngineTableLoggersFactoryMemoryImpl.java
  engine/table/src/main/java/io/deephaven/engine/tablelogger/impl/memory/ProcessInfoLogLoggerMemoryImpl.java
  engine/table/src/main/java/io/deephaven/engine/tablelogger/impl/memory/ProcessMetricsLogLoggerMemoryImpl.java
  engine/table/src/main/java/io/deephaven/engine/tablelogger/impl/memory/QueryOperationPerformanceLogLoggerMemoryImpl.java
  engine/table/src/main/java/io/deephaven/engine/tablelogger/impl/memory/QueryPerformanceLogLoggerMemoryImpl.java
  engine/table/src/main/java/io/deephaven/engine/tablelogger/impl/memory/ServerStateLogLoggerMemoryImpl.java
  engine/table/src/main/java/io/deephaven/engine/tablelogger/impl/memory/UpdatePerformanceLogLoggerMemoryImpl.java
  engine/table/src/main/java/io/deephaven/process/ProcessInfoStoreDBImpl.java
  engine/table/src/main/java/io/deephaven/process/StatsIntradayLoggerDBImpl.java
  server/test/src/main/java/io/deephaven/server/test/FlightMessageRoundTripTest.java
Labels: DocumentationNeeded, ReleaseNotesNeeded

#4115 Make AuthContext available to QPL, QOPL, and UPL
  engine/table/src/main/java/io/deephaven/engine/table/impl/perf/PerformanceEntry.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/perf/QueryPerformanceNugget.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/perf/UpdatePerformanceStreamPublisher.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/QueryOperationPerformanceStreamPublisher.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/QueryPerformanceStreamPublisher.java
  engine/table/src/main/java/io/deephaven/engine/util/AbstractScriptSession.java
Labels: feature request, query engine, core, NoDocumentationNeeded, ReleaseNotesNeeded
