Repository deephaven/deephaven-core, pull requests merged in 2023-09, with the labels that each got.

#4428 Add copy ctors to C++ client public API classes to facilitate R wrapping
  cpp-client/deephaven/dhclient/include/public/deephaven/client/client.h
  cpp-client/deephaven/dhclient/include/public/deephaven/client/client_options.h
  cpp-client/deephaven/dhclient/src/client.cc
  cpp-client/deephaven/dhclient/src/client_options.cc
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4388 Transition to python using native python time types instead of Java types
  py/server/deephaven/column.py
  py/server/deephaven/replay.py
  py/server/deephaven/table_factory.py
  py/server/deephaven/time.py
  py/server/tests/test_arrow.py
  py/server/tests/test_calendar.py
  py/server/tests/test_column.py
  py/server/tests/test_config.py
  py/server/tests/test_dtypes.py
  py/server/tests/test_numpy.py
  py/server/tests/test_pandas.py
  py/server/tests/test_plot/test_plot.py
  py/server/tests/test_replay.py
  py/server/tests/test_table.py
  py/server/tests/test_table_factory.py
  py/server/tests/test_time.py
  py/server/tests/test_update_graph.py
Labels: python, DocumentationNeeded, python-server-side, breaking, ReleaseNotesNeeded

#4400 Handle infinitesimal and negative variance in `UpdateBy#RollingStd()`
  engine/function/src/templates/Numeric.ftl
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/rollingstd/ByteRollingStdOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/rollingstd/CharRollingStdOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/rollingstd/DoubleRollingStdOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/rollingstd/FloatRollingStdOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/rollingstd/IntRollingStdOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/rollingstd/LongRollingStdOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/rollingstd/ShortRollingStdOperator.java
Labels: bug, NoDocumentationNeeded, NoReleaseNotesNeeded

#4356 Python wrapper for MultiJoin feature
  engine/table/src/main/java/io/deephaven/engine/table/impl/MultiJoinTableImpl.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableMultiJoinTest.java
  py/server/deephaven/jcompat.py
  py/server/deephaven/table.py
  py/server/tests/test_multijoin.py
Labels: python, DocumentationNeeded, python-server-side, ReleaseNotesNeeded

#4343 Make cummax consistent with cummin
  engine/function/src/templates/Numeric.ftl
Labels: bug, NoDocumentationNeeded, NoReleaseNotesNeeded

#4434 C++ client: input table support
  cpp-client/deephaven/dhclient/include/private/deephaven/client/impl/table_handle_impl.h
  cpp-client/deephaven/dhclient/include/private/deephaven/client/impl/table_handle_manager_impl.h
  cpp-client/deephaven/dhclient/include/private/deephaven/client/server/server.h
  cpp-client/deephaven/dhclient/include/public/deephaven/client/client.h
  cpp-client/deephaven/dhclient/src/client.cc
  cpp-client/deephaven/dhclient/src/impl/table_handle_impl.cc
  cpp-client/deephaven/dhclient/src/impl/table_handle_manager_impl.cc
  cpp-client/deephaven/dhclient/src/server/server.cc
  cpp-client/deephaven/tests/CMakeLists.txt
  cpp-client/deephaven/tests/input_table_test.cc
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4436 Make C++ Client API object move-only again.
  cpp-client/deephaven/dhclient/include/public/deephaven/client/client.h
  cpp-client/deephaven/dhclient/src/client.cc
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4437 Add a bit more logging to C++ client and tweak on close callbacks a bit.
  cpp-client/deephaven/dhclient/include/private/deephaven/client/server/server.h
  cpp-client/deephaven/dhclient/include/public/deephaven/client/client.h
  cpp-client/deephaven/dhclient/src/client.cc
  cpp-client/deephaven/dhclient/src/impl/client_impl.cc
  cpp-client/deephaven/dhclient/src/server/server.cc
  cpp-client/deephaven/dhcore/src/utility/utility.cc
  cpp-client/deephaven/tests/utility_test.cc
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4435 add import for Table
  py/client/pydeephaven/__init__.py
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4439 Update R client to some macro renaming in C++ client.
  R/rdeephaven/src/client.cpp
Labels: NoDocumentationNeeded, release blocker, NoReleaseNotesNeeded

#4443 Update RELEASE.md to explicitly list the files that have version numbers.
  RELEASE.md
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4431 Fix `LongArraySource#fillPrevChunk` When a Converter is Supplied
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/LongArraySource.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/select/TestReinterpretedColumn.java
  replication/static/src/main/java/io/deephaven/replicators/ReplicateSourcesAndChunks.java
Labels: bug, core, NoDocumentationNeeded, ReleaseNotesNeeded

#4360 4338 live pyobject
  Integrations/src/main/java/io/deephaven/integrations/python/PythonDeephavenSession.java
  engine/updategraph/src/main/java/io/deephaven/engine/liveness/ReferenceCountedLivenessNode.java
  engine/updategraph/src/main/java/io/deephaven/engine/liveness/ReferenceCountedLivenessReferent.java
  py/server/deephaven/_wrapper.py
  py/server/deephaven/appmode.py
  py/server/deephaven_internal/plugin/object/__init__.py
  py/server/deephaven_internal/script_session/__init__.py
  server/src/main/java/io/deephaven/server/object/ObjectServiceGrpcImpl.java
  server/src/main/java/io/deephaven/server/plugin/python/LivePyObjectWrapper.java
  server/src/main/java/io/deephaven/server/plugin/python/ObjectTypeAdapter.java
  server/src/main/java/io/deephaven/server/runner/DeephavenApiServer.java
  web/client-api/src/main/java/io/deephaven/web/client/api/widget/JsWidget.java
Labels: NoDocumentationNeeded, python-server-side, ReleaseNotesNeeded

#4441 Allow the creation of R Clients from other libraries (useful for DnD and in general)
  R/rdeephaven/DESCRIPTION
  R/rdeephaven/R/client_wrapper.R
  R/rdeephaven/inst/tests/testthat/test_client_wrapper.R
  R/rdeephaven/src/client.cpp
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded, r-client

#4447 Small improvements to RELEASE.md
  RELEASE.md
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4452 C++ Client: fix docs build
  cpp-client/doc/Doxyfile
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4453 Rename make_table_from_ticket to ticket_to_table in R client API
  R/rdeephaven/R/client_wrapper.R
  R/rdeephaven/inst/tests/testthat/test_client_wrapper.R
  py/client/pydeephaven/_console_service.py
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4451 DeferredViewTable: Only Manage When Refreshing
  engine/table/src/main/java/io/deephaven/engine/table/impl/DeferredViewTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/PartitionAwareSourceTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/SimpleSourceTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/ComposedFilter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/WhereFilter.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/DeferredViewTableTest.java
Labels: bug, core, NoDocumentationNeeded, ReleaseNotesNeeded

#4450 Make the definitions of col_defs consistent
  py/server/deephaven/stream/kafka/cdc.py
  py/server/deephaven/stream/kafka/consumer.py
  py/server/deephaven/stream/table_publisher.py
  py/server/deephaven/table.py
  py/server/deephaven_internal/auto_completer/_completer.py
  py/server/tests/test_kafka_consumer.py
Labels: NoDocumentationNeeded, python-server-side, NoReleaseNotesNeeded

#4456 Add skip initial table publish with kafka
  extensions/kafka/src/main/java/io/deephaven/kafka/KafkaPublishOptions.java
  extensions/kafka/src/main/java/io/deephaven/kafka/KafkaTools.java
  extensions/kafka/src/main/java/io/deephaven/kafka/publish/PublishToKafka.java
  py/server/deephaven/stream/kafka/producer.py
  py/server/tests/test_kafka_producer.py
Labels: feature request, kafka, DocumentationNeeded, kafka-exhaust, ReleaseNotesNeeded

#4464 Argument names to snake case in C++ level of R Client
  R/rdeephaven/src/client.cpp
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded, r-client

#4462 Add support for building with address sanitizer to C++ client's cmake setup
  cpp-client/deephaven/CMakeLists.txt
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4467 Remove the deephaven.config subpkg
  py/server/deephaven/config/__init__.py
  py/server/tests/test_config.py
Labels: NoDocumentationNeeded, python-server-side, NoReleaseNotesNeeded

#4427 Wrap FunctionGeneratedTableFactory for Python
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/FunctionGeneratedTableFactory.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/util/TestFunctionBackedTableFactory.java
  py/server/deephaven/__init__.py
  py/server/deephaven/table_factory.py
  py/server/tests/test_function_generated_table.py
Labels: python, DocumentationNeeded, ReleaseNotesNeeded

#4422 Make use of bulk conversion when creating datetime cols
  py/server/deephaven/column.py
  py/server/tests/test_column.py
Labels: NoDocumentationNeeded, python-server-side, NoReleaseNotesNeeded

#4472 AbstractFormulaColumn Must Copy ColumnDefinitionMap as it is Mutated by Caller
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/AbstractFormulaColumn.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/SelectColumn.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/DeferredViewTableTest.java
Labels: bug, core, NoDocumentationNeeded, NoReleaseNotesNeeded

#4373 Add Location removal support and update SourcePartitionedTable
  Util/src/main/java/io/deephaven/util/FindExceptionCause.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/ColumnSourceManager.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/ListenerRecorder.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/MergedListener.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/SourcePartitionedTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/SourceTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/locations/ImmutableTableLocationKey.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/locations/InvalidatedRegionException.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/locations/TableLocationProvider.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/locations/TableLocationRemovedException.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/locations/impl/AbstractTableLocationProvider.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/locations/impl/FilteredTableDataService.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/locations/impl/TableLocationSubscriptionBuffer.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/locations/impl/TableLocationUpdateSubscriptionBuffer.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/ConstituentTableException.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/UnionSourceManager.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/ColumnRegion.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/ColumnRegionByte.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/ColumnRegionChar.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/ColumnRegionChunkDictionary.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/ColumnRegionDouble.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/ColumnRegionFloat.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/ColumnRegionInt.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/ColumnRegionLong.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/ColumnRegionObject.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/ColumnRegionReferencingImpl.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/ColumnRegionShort.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/DeferredColumnRegionBase.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/GenericColumnRegionBase.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/RegionedColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/RegionedColumnSourceBase.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/RegionedColumnSourceManager.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/SourcePartitionedTableTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/sources/regioned/TestRegionedColumnSourceManager.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/sources/regioned/TstColumnRegionByte.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/sources/regioned/TstColumnRegionChar.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/sources/regioned/TstColumnRegionDouble.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/sources/regioned/TstColumnRegionFloat.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/sources/regioned/TstColumnRegionInt.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/sources/regioned/TstColumnRegionLong.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/sources/regioned/TstColumnRegionShort.java
  engine/test-utils/build.gradle
  engine/test-utils/src/main/java/io/deephaven/engine/testutil/locations/DependentRegistrar.java
  engine/test-utils/src/main/java/io/deephaven/engine/testutil/locations/TableBackedColumnLocation.java
  engine/test-utils/src/main/java/io/deephaven/engine/testutil/locations/TableBackedTableLocation.java
  engine/test-utils/src/main/java/io/deephaven/engine/testutil/locations/TableBackedTableLocationKey.java
  engine/test-utils/src/main/java/io/deephaven/engine/testutil/locations/TableBackedTableLocationProvider.java
  engine/test-utils/src/main/java/io/deephaven/engine/testutil/testcase/RefreshingTableTestCase.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/region/ParquetColumnRegionBase.java
  extensions/source-support/src/main/java/io/deephaven/generic/region/AppendOnlyFixedSizePageRegionByte.java
  extensions/source-support/src/main/java/io/deephaven/generic/region/AppendOnlyFixedSizePageRegionChar.java
  extensions/source-support/src/main/java/io/deephaven/generic/region/AppendOnlyFixedSizePageRegionDouble.java
  extensions/source-support/src/main/java/io/deephaven/generic/region/AppendOnlyFixedSizePageRegionFloat.java
  extensions/source-support/src/main/java/io/deephaven/generic/region/AppendOnlyFixedSizePageRegionInt.java
  extensions/source-support/src/main/java/io/deephaven/generic/region/AppendOnlyFixedSizePageRegionLong.java
  extensions/source-support/src/main/java/io/deephaven/generic/region/AppendOnlyFixedSizePageRegionObject.java
  extensions/source-support/src/main/java/io/deephaven/generic/region/AppendOnlyFixedSizePageRegionShort.java
  extensions/source-support/src/test/java/io/deephaven/generic/region/AppendOnlyFixedSizePageRegionTest.java
Labels: NoDocumentationNeeded

#4461 Setup ExecutionContext in Barrage Client Examples
  Util/src/main/java/io/deephaven/util/thread/ThreadInitializationFactory.java
  java-client/barrage-examples/src/main/java/io/deephaven/client/examples/BarrageClientExampleBase.java
  java-client/barrage-examples/src/main/java/io/deephaven/client/examples/SubscribeExampleBase.java
  java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java
Labels: bug, barrage, DocumentationNeeded, java-client, ReleaseNotesNeeded

#4473 Fix UpdateByListener.satisfied() and JobScheduler.IterationManager handling for errors in error reporting
  FishUtil/src/main/java/io/deephaven/util/process/BaseProcessEnvironment.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/remote/ConstructSnapshot.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/BucketedPartitionedUpdateByManager.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/UpdateBy.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/ZeroKeyUpdateByManager.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/JobScheduler.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/PartitionedTableTest.java
  engine/table/src/test/java/io/deephaven/engine/util/TestJobScheduler.java
  engine/test-utils/build.gradle
  engine/test-utils/src/main/java/io/deephaven/engine/testutil/testcase/FakeProcessEnvironment.java
  engine/test-utils/src/main/java/io/deephaven/engine/testutil/testcase/RefreshingTableTestCase.java
Labels: bug, query engine, core, NoDocumentationNeeded, ReleaseNotesNeeded

#4475 Give explicit instructions for Release build for C++ client; simplify R Makevars.
  R/rdeephaven/DESCRIPTION
  R/rdeephaven/R/table_handle_wrapper.R
  R/rdeephaven/src/Makevars
  cpp-client/README.md
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4477 Bump to 0.29.0
  R/rdeephaven/DESCRIPTION
  authorization-codegen/protoc-gen-contextual-auth-wiring
  authorization-codegen/protoc-gen-service-auth-wiring
  buildSrc/src/main/groovy/io.deephaven.common-conventions.gradle
  py/client-ticking/README.md
  py/client-ticking/setup.py
  py/client/README.md
  py/client/pydeephaven/__init__.py
  py/client/setup.py
  py/embedded-server/deephaven_server/__init__.py
  py/server/deephaven/__init__.py
Labels: NoDocumentationNeeded, version-bump, NoReleaseNotesNeeded

#4463 Improve generic types for TypedFunctions
  extensions/protobuf/build.gradle
  extensions/protobuf/src/main/java/io/deephaven/functions/BooleanFunctions.java
  extensions/protobuf/src/main/java/io/deephaven/functions/ByteFunctions.java
  extensions/protobuf/src/main/java/io/deephaven/functions/CharFunctions.java
  extensions/protobuf/src/main/java/io/deephaven/functions/DoubleFunctions.java
  extensions/protobuf/src/main/java/io/deephaven/functions/FloatFunctions.java
  extensions/protobuf/src/main/java/io/deephaven/functions/IntFunctions.java
  extensions/protobuf/src/main/java/io/deephaven/functions/LongFunctions.java
  extensions/protobuf/src/main/java/io/deephaven/functions/ObjectFunctions.java
  extensions/protobuf/src/main/java/io/deephaven/functions/PrimitiveFunctions.java
  extensions/protobuf/src/main/java/io/deephaven/functions/ShortFunctions.java
  extensions/protobuf/src/main/java/io/deephaven/functions/ToBooleanFunction.java
  extensions/protobuf/src/main/java/io/deephaven/functions/ToByteFunction.java
  extensions/protobuf/src/main/java/io/deephaven/functions/ToCharFunction.java
  extensions/protobuf/src/main/java/io/deephaven/functions/ToDoubleFunction.java
  extensions/protobuf/src/main/java/io/deephaven/functions/ToFloatFunction.java
  extensions/protobuf/src/main/java/io/deephaven/functions/ToIntFunction.java
  extensions/protobuf/src/main/java/io/deephaven/functions/ToLongFunction.java
  extensions/protobuf/src/main/java/io/deephaven/functions/ToObjectFunction.java
  extensions/protobuf/src/main/java/io/deephaven/functions/ToShortFunction.java
  extensions/protobuf/src/main/java/io/deephaven/functions/TypedFunctions.java
  extensions/protobuf/src/test/java/io/deephaven/functions/ToBooleanFunctionTest.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4481 Tweaks to support building the cpp-client in older linux distros/GCC versions.
  cpp-client/README.md
  cpp-client/build.gradle
  cpp-client/deephaven/CMakeLists.txt
  cpp-client/deephaven/dhclient/CMakeLists.txt
  cpp-client/deephaven/dhclient/include/public/deephaven/client/client.h
  cpp-client/deephaven/dhclient/include/public/deephaven/client/client_options.h
  cpp-client/deephaven/dhclient/src/client.cc
  cpp-client/deephaven/dhclient/src/client_options.cc
  cpp-client/deephaven/dhcore/CMakeLists.txt
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/utility/utility.h
  cpp-client/deephaven/examples/create_table_with_arrow_flight/CMakeLists.txt
  cpp-client/deephaven/examples/create_table_with_table_maker/CMakeLists.txt
  cpp-client/deephaven/examples/demos/CMakeLists.txt
  cpp-client/deephaven/examples/hello_world/CMakeLists.txt
  cpp-client/deephaven/examples/read_csv/CMakeLists.txt
  cpp-client/deephaven/examples/read_table_with_arrow_flight/CMakeLists.txt
  cpp-client/deephaven/examples/table_cleanup/CMakeLists.txt
  cpp-client/deephaven/tests/CMakeLists.txt
  cpp-client/deephaven/tests/select_test.cc
  docker/registry/cpp-client-base/gradle.properties
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4465 Add `agg_all_by()` to the R client and add error handling around empty aggregations in `agg_by()`
  R/rdeephaven/R/aggregate_wrapper.R
  R/rdeephaven/R/helper_functions.R
  R/rdeephaven/R/table_handle_wrapper.R
  R/rdeephaven/inst/tests/testthat/test_agg_by.R
  R/rdeephaven/src/client.cpp
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded, r-client

#4457 Removed ParquetHadoop module
  NOTICE.md
  ParquetHadoop/LICENSE
  ParquetHadoop/NOTICE
  ParquetHadoop/build.gradle
  ParquetHadoop/gradle.properties
  ParquetHadoop/src/main/java/io/deephaven/parquet/base/tempfix/ParquetMetadataConverter.java
  buildSrc/src/main/groovy/Classpaths.groovy
  extensions/parquet/base/build.gradle
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/ColumnWriterImpl.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/ParquetFileWriter.java
  extensions/parquet/compression/build.gradle
  extensions/parquet/table/build.gradle
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/ParquetSchemaReader.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/ParquetTools.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/layout/ParquetMetadataFileLayout.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/location/ParquetColumnLocation.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/location/ParquetTableLocationKey.java
  settings.gradle
Labels: feature request, parquet, NoDocumentationNeeded, NoReleaseNotesNeeded

#4492 Changes to build R client on Fedora.
  R/rdeephaven/DESCRIPTION
  R/rdeephaven/src/Makevars
  R/rdeephaven/src/client.cpp
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4494 Fix for crashing python parquet CI tests
  py/server/tests/test_parquet.py
Labels: bug, python, parquet, NoDocumentationNeeded, NoReleaseNotesNeeded

#4496 Update base images for cpp-client build; update cpp-client's README.
  cpp-client/README.md
  docker/registry/cpp-client-base/gradle.properties
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4344 Enforce page size limit in Parquet
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/ParquetInstructions.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/ParquetTableWriter.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/ParquetTableReadWriteTest.java
Labels: bug, parquet, NoDocumentationNeeded, NoReleaseNotesNeeded

#4498 Add Adoptium to profiled vendors list.
  Util/src/main/java/io/deephaven/util/profiling/ThreadProfiler.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#4500 Use new C++ base image that removes local from the directory layout.
  R/rdeephaven/src/Makevars
  cpp-client/README.md
  docker/registry/cpp-client-base/gradle.properties
  proto/proto-backplane-grpc/src/main/proto/build-cpp-protos.sh
  py/client-ticking/README.md
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4483 Fix for inconsistent tests
  engine/table/src/test/java/io/deephaven/engine/table/impl/util/TestFunctionGeneratedTableFactory.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/util/TestKeyedArrayBackedMutableTable.java
  py/server/deephaven/__init__.py
  py/server/tests/test_function_generated_table.py
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4363 Add docstrings to R Client
  R/rdeephaven/NAMESPACE
  R/rdeephaven/R/aggregate_wrapper.R
  R/rdeephaven/R/client_wrapper.R
  R/rdeephaven/R/table_handle_wrapper.R
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded, r-client

#4446 Added support for LZ4_RAW compression codec for Parquet
  extensions/parquet/compression/README.md
  extensions/parquet/compression/build.gradle
  extensions/parquet/compression/src/main/java/io/deephaven/parquet/compress/DeephavenCompressorAdapterFactory.java
  extensions/parquet/compression/src/main/java/io/deephaven/parquet/compress/LZ4WithLZ4RawBackupCompressorAdapter.java
  extensions/parquet/table/src/brotliTest/java/io/deephaven/parquet/table/BrotliParquetTableReadWriteTest.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/ParquetInstructions.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/ParquetTools.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/ParquetTableReadWriteTest.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/TestParquetTools.java
  extensions/parquet/table/src/test/resources/sample_lz4_compressed.parquet
  py/server/tests/test_parquet.py
Labels: feature request, parquet, DocumentationNeeded, NoReleaseNotesNeeded

#4511 Fix Python tests for FunctionGeneratedTable
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/FunctionGeneratedTableFactory.java
  py/server/deephaven/table_factory.py
  py/server/tests/test_function_generated_table.py
Labels: bug, query engine, core, NoDocumentationNeeded, NoReleaseNotesNeeded

#4510 Remove Z axis by default from ChartImpl
  Plot/src/main/java/io/deephaven/plot/ChartImpl.java
  plugin/figure/src/main/java/io/deephaven/figure/FigureWidgetTranslator.java
Labels: test, plotting, NoDocumentationNeeded, NoReleaseNotesNeeded

#4512 Generate docs
  R/rdeephaven/man/Client.Rd
  R/rdeephaven/man/TableHandle.Rd
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded, r-client

#4507 DH to work with byte arrays
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/ChunkInputStreamGenerator.java
  java-client/flight-dagger/src/test/java/io/deephaven/client/DeephavenFlightSessionTest.java
  java-client/flight-examples/src/main/java/io/deephaven/client/examples/AddToInputTable.java
  java-client/flight/src/main/java/io/deephaven/client/impl/FieldAdapter.java
  java-client/flight/src/main/java/io/deephaven/client/impl/FieldVectorAdapter.java
  java-client/flight/src/main/java/io/deephaven/client/impl/VectorHelper.java
Labels: barrage, core, DocumentationNeeded, ReleaseNotesNeeded

#4518 Modify Roxygen directives and NAMESPACE header to ensure devtools::document() produces consistent results
  R/rdeephaven/NAMESPACE
  R/rdeephaven/R/client_wrapper.R
  R/rdeephaven/R/table_handle_wrapper.R
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded, r-client

#4421 Raise exception when reading non-UTC adjusted timestamps in parquet
  .gitattributes
  .github/workflows/check-ci.yml
  .github/workflows/nightly-check-ci.yml
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/ParquetFileReader.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/ParquetSchemaReader.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/location/ParquetColumnLocation.java
  extensions/parquet/table/src/test/e0.py
  extensions/parquet/table/src/test/e0.requirements.txt
  extensions/parquet/table/src/test/e1.py
  extensions/parquet/table/src/test/e2.py
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/TestParquetTools.java
  extensions/parquet/table/src/test/resources/e0/brotli.parquet
  extensions/parquet/table/src/test/resources/e0/gzip.parquet
  extensions/parquet/table/src/test/resources/e0/lz4.parquet
  extensions/parquet/table/src/test/resources/e0/pyarrow_stats.parquet
  extensions/parquet/table/src/test/resources/e0/snappy.parquet
  extensions/parquet/table/src/test/resources/e0/uncompressed.parquet
  extensions/parquet/table/src/test/resources/e0/zstd.parquet
  extensions/parquet/table/src/test/resources/e1/brotli.parquet
  extensions/parquet/table/src/test/resources/e1/gzip.parquet
  extensions/parquet/table/src/test/resources/e1/lz4.parquet
  extensions/parquet/table/src/test/resources/e1/snappy.parquet
  extensions/parquet/table/src/test/resources/e1/uncompressed.parquet
  extensions/parquet/table/src/test/resources/e1/zstd.parquet
  extensions/parquet/table/src/test/resources/e2/brotli.parquet
  extensions/parquet/table/src/test/resources/e2/gzip.parquet
  extensions/parquet/table/src/test/resources/e2/lz4.parquet
  extensions/parquet/table/src/test/resources/e2/snappy.parquet
  extensions/parquet/table/src/test/resources/e2/uncompressed.parquet
  extensions/parquet/table/src/test/resources/e2/zstd.parquet
  extensions/parquet/table/src/test/resources/sample_lz4_compressed.parquet
  py/server/tests/data/crypto_trades.parquet
  py/server/tests/test_parquet.py
Labels: bug, parquet, NoDocumentationNeeded, NoReleaseNotesNeeded

#4526 Fix typo in delta method 'cols' docstring
  py/server/deephaven/updateby.py
Labels: bug, documentation, python, NoDocumentationNeeded, NoReleaseNotesNeeded

#4517 KafkaStreamPublisher: Fix ArrayIndexOutOfBoundsException
  extensions/kafka/src/main/java/io/deephaven/kafka/ingest/KafkaStreamPublisher.java
Labels: kafka, NoDocumentationNeeded, ReleaseNotesNeeded

#4190 Simplify ScriptSession dependencies
  engine/table/build.gradle
  engine/table/groovy/core/deephaven_core_utils.groovy
  engine/table/python/core/deephaven_jpy_init.py
  engine/table/src/main/java/io/deephaven/engine/util/jpy/JpyInit.java
  engine/table/src/main/resources/groovy/0-base.groovy
  engine/table/src/main/resources/groovy/2-calendars.groovy
  engine/table/src/main/resources/groovy/4-count-metrics.groovy
  props/configs/src/main/resources/dh-defaults.prop
  props/test-configs/src/main/resources/dh-tests.prop
  py/server/deephaven_internal/jvm/__init__.py
  python-engine-test/src/test/java/io/deephaven/engine/util/WorkerPythonEnvironment.java
Labels: python, DocumentationNeeded, groovy, ReleaseNotesNeeded

#4515 Deferring use of ExportObject shouldn't lead to error
  server/src/main/java/io/deephaven/server/object/ObjectServiceGrpcImpl.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#4479 ParquetTableWriter Extract/Replicate Transfer Kernels
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/ColumnWriter.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/MappedSchema.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/ParquetCacheTags.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/ParquetTableWriter.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/TypeInfos.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/transfer/BooleanTransfer.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/transfer/ByteTransfer.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/transfer/CharTransfer.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/transfer/CodecTransfer.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/transfer/DoubleTransfer.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/transfer/EncodedTransfer.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/transfer/FloatTransfer.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/transfer/IntCastablePrimitiveTransfer.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/transfer/IntTransfer.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/transfer/LongTransfer.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/transfer/PrimitiveTransfer.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/transfer/ShortTransfer.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/transfer/StringTransfer.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/transfer/TransferObject.java
  replication/static/build.gradle
  replication/static/src/main/java/io/deephaven/replicators/ReplicateParquetTransferObjects.java
Labels: core, NoDocumentationNeeded, port, NoReleaseNotesNeeded

#4530 Receive time for Kafka messages.
  engine/api/src/main/java/io/deephaven/engine/table/PartitionedTable.java
  extensions/kafka/src/main/java/io/deephaven/kafka/KafkaTools.java
  extensions/kafka/src/main/java/io/deephaven/kafka/ingest/ConsumerRecordToStreamPublisherAdapter.java
  extensions/kafka/src/main/java/io/deephaven/kafka/ingest/KafkaIngester.java
  extensions/kafka/src/main/java/io/deephaven/kafka/ingest/KafkaRecordConsumer.java
  extensions/kafka/src/main/java/io/deephaven/kafka/ingest/KafkaStreamPublisher.java
Labels: DocumentationNeeded, NoReleaseNotesNeeded

#4529 Make em* pydocs consistent with one another, fix emstd* formulas
  py/server/deephaven/updateby.py
Labels: documentation, NoDocumentationNeeded, python-server-side, NoReleaseNotesNeeded

#4513 Fix for failure in Head_By and AggAllBy after Format_Column
  engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/TableDefaults.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/AggAllByExcludeFormattingColumns.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/AggregateAllExclusions.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableAggregationTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestAggBy.java
  qst/src/main/java/io/deephaven/qst/table/AggregateAllTable.java
Labels: bug, query engine, core, NoDocumentationNeeded, NoReleaseNotesNeeded

#4416 Bump jetty to 11.0.16
  buildSrc/src/main/groovy/Classpaths.groovy
Labels: NoDocumentationNeeded, jetty, version-bump, NoReleaseNotesNeeded

#4539 SourceTable should remove itself from registrar, not UG
  engine/table/src/main/java/io/deephaven/engine/table/impl/SourceTable.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/SourcePartitionedTableTest.java
Labels: bug, query engine, core, NoDocumentationNeeded, ReleaseNotesNeeded

#4528 Support ZonedDateTime columns in plots
  Plot/src/main/java/io/deephaven/plot/util/tables/ColumnHandlerFactory.java
  Plot/src/test/java/io/deephaven/plot/util/tables/TestColumnHandlerFactory.java
Labels: bug, plotting, DocumentationNeeded, ReleaseNotesNeeded

#4538 Make Kafka KeyOrValueProducers public to enable external parsers.
  extensions/kafka/src/main/java/io/deephaven/kafka/AvroImpl.java
  extensions/kafka/src/main/java/io/deephaven/kafka/IgnoreImpl.java
  extensions/kafka/src/main/java/io/deephaven/kafka/JsonImpl.java
  extensions/kafka/src/main/java/io/deephaven/kafka/KafkaTools.java
  extensions/kafka/src/main/java/io/deephaven/kafka/ProtobufImpl.java
  extensions/kafka/src/main/java/io/deephaven/kafka/RawImpl.java
  extensions/kafka/src/main/java/io/deephaven/kafka/SimpleImpl.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4490 Add messageStream support for java client
  Plot/Plot.gradle
  java-client/example-utilities/src/main/java/io/deephaven/client/examples/TypedTicketConverter.java
  java-client/flight-examples/src/main/java/io/deephaven/client/examples/ConvertToTable.java
  java-client/session-dagger/build.gradle
  java-client/session-dagger/src/test/java/io/deephaven/client/ObjectServiceTest.java
  java-client/session-examples/build.gradle
  java-client/session-examples/src/main/java/io/deephaven/client/examples/FetchObject.java
  java-client/session-examples/src/main/java/io/deephaven/client/examples/MessageStreamSendReceive.java
  java-client/session/src/main/java/io/deephaven/client/impl/ClientData.java
  java-client/session/src/main/java/io/deephaven/client/impl/CustomObject.java
  java-client/session/src/main/java/io/deephaven/client/impl/Export.java
  java-client/session/src/main/java/io/deephaven/client/impl/ExportId.java
  java-client/session/src/main/java/io/deephaven/client/impl/FetchedObject.java
  java-client/session/src/main/java/io/deephaven/client/impl/FieldInfo.java
  java-client/session/src/main/java/io/deephaven/client/impl/HasExportId.java
  java-client/session/src/main/java/io/deephaven/client/impl/HasTypedTicket.java
  java-client/session/src/main/java/io/deephaven/client/impl/ObjectService.java
  java-client/session/src/main/java/io/deephaven/client/impl/ServerData.java
  java-client/session/src/main/java/io/deephaven/client/impl/ServerObject.java
  java-client/session/src/main/java/io/deephaven/client/impl/ServerObjectBase.java
  java-client/session/src/main/java/io/deephaven/client/impl/Session.java
  java-client/session/src/main/java/io/deephaven/client/impl/SessionImpl.java
  java-client/session/src/main/java/io/deephaven/client/impl/TableHandle.java
  java-client/session/src/main/java/io/deephaven/client/impl/TableObject.java
  java-client/session/src/main/java/io/deephaven/client/impl/TicketId.java
  java-client/session/src/main/java/io/deephaven/client/impl/TypedTicket.java
  java-client/session/src/main/java/io/deephaven/client/impl/UnknownObject.java
  plugin/echo/build.gradle
  plugin/echo/gradle.properties
  plugin/echo/src/main/java/io/deephaven/plugin/EchoObjectType.java
  server/src/main/java/io/deephaven/server/session/SessionState.java
  server/src/test/java/io/deephaven/server/object/ObjectServiceTest.java
  server/src/test/java/io/deephaven/server/runner/DeephavenApiServerTestBase.java
  settings.gradle
Labels: DocumentationNeeded, java-client, breaking, ReleaseNotesNeeded

#4550 Fix missing AuthContext on New Partition
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/UnionSourceManager.java
Labels: bug, core, NoDocumentationNeeded, partitioned_tables, ReleaseNotesNeeded

#4544 Fix spurious firing of language parser assertion for expressions including method type arguments
  engine/table/src/main/java/io/deephaven/engine/table/impl/lang/QueryLanguageParser.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/lang/LanguageParserDummyClass.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/lang/TestQueryLanguageParser.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4542 Add kwargs to function generated tables
  py/server/deephaven/table_factory.py
  py/server/tests/test_function_generated_table.py
Labels: NoDocumentationNeeded, python-server-side, NoReleaseNotesNeeded

#4547 Ensure that boolean partition columns are boxed
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/ParquetTools.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/TestParquetTools.java
Labels: parquet, NoDocumentationNeeded, ReleaseNotesNeeded

#4560 Fix formatting and formulas in UpdateBy docs
  py/server/deephaven/updateby.py
Labels: bug, documentation, NoDocumentationNeeded, NoReleaseNotesNeeded

#4551 Use new base image for cpp-client (towards R client CI).
  cpp-client/README.md
  cpp-client/build.gradle
  cpp-client/cpp-tests-to-junit.sh
  docker/registry/cpp-client-base/gradle.properties
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4548 Rename R `cross_join` to `join`, add documentation
  R/rdeephaven/R/table_handle_wrapper.R
  R/rdeephaven/inst/tests/testthat/test_table_ops.R
  R/rdeephaven/man/Client.Rd
  R/rdeephaven/man/TableHandle.Rd
  R/rdeephaven/src/client.cpp
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded, r-client

#4566 Fix bug in converting a DH table with all columns of the same type
  py/server/deephaven/pandas.py
Labels: bug, triage, NoDocumentationNeeded, python-server-side, NoReleaseNotesNeeded

#4412 R Client - UpdateBy
  R/rdeephaven/DESCRIPTION
  R/rdeephaven/NAMESPACE
  R/rdeephaven/R/agg_ops_wrapper.R
  R/rdeephaven/R/client_wrapper.R
  R/rdeephaven/R/helper_functions.R
  R/rdeephaven/R/operation_control.R
  R/rdeephaven/R/table_handle_wrapper.R
  R/rdeephaven/R/update_by_ops_wrapper.R
  R/rdeephaven/R/utility_functions.R
  R/rdeephaven/inst/tests/testthat/test_agg_by.R
  R/rdeephaven/inst/tests/testthat/test_agg_ops_wrappers.R
  R/rdeephaven/inst/tests/testthat/test_client_wrapper.R
  R/rdeephaven/inst/tests/testthat/test_update_by.R
  R/rdeephaven/inst/tests/testthat/test_update_by_ops_wrappers.R
  R/rdeephaven/src/client.cpp
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded, r-client

#4535 Rename and update docs for ObjectService ServerData and ClientData
  cpp-client/deephaven/dhclient/proto/deephaven/proto/object.pb.cc
  cpp-client/deephaven/dhclient/proto/deephaven/proto/object.pb.h
  java-client/session/src/main/java/io/deephaven/client/impl/ClientData.java
  java-client/session/src/main/java/io/deephaven/client/impl/ServerData.java
  proto/proto-backplane-grpc/src/main/proto/deephaven/proto/object.proto
  py/client/pydeephaven/experimental/plugin_client.py
  py/client/pydeephaven/proto/object_pb2.py
  server/src/main/java/io/deephaven/server/object/ObjectServiceGrpcImpl.java
  server/src/test/java/io/deephaven/server/object/ObjectServiceTest.java
  web/client-api/src/main/java/io/deephaven/web/client/api/widget/JsWidget.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/object_pb/ClientData.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/object_pb/ServerData.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/object_pb/StreamRequest.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/object_pb/StreamResponse.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded
