Repository deephaven/deephaven-core, pull requests merged in 2023-11, with the labels that each got.

#4735 Ensure defaults for float/double generation result in random values
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableAggregationTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/BaseUpdateByTest.java
  engine/test-utils/src/main/java/io/deephaven/engine/testutil/generator/BigIntegerGenerator.java
  engine/test-utils/src/main/java/io/deephaven/engine/testutil/generator/DoubleGenerator.java
  engine/test-utils/src/main/java/io/deephaven/engine/testutil/generator/FloatGenerator.java
Labels: test, NoDocumentationNeeded, NoReleaseNotesNeeded

#4680 Server-generated column statistics
  authorization/src/main/java/io/deephaven/auth/codegen/impl/ObjectServiceAuthWiring.java
  authorization/src/main/java/io/deephaven/auth/codegen/impl/TableServiceContextualAuthWiring.java
  cpp-client/deephaven/dhclient/proto/deephaven/proto/table.grpc.pb.cc
  cpp-client/deephaven/dhclient/proto/deephaven/proto/table.grpc.pb.h
  cpp-client/deephaven/dhclient/proto/deephaven/proto/table.pb.cc
  cpp-client/deephaven/dhclient/proto/deephaven/proto/table.pb.h
  engine/test-utils/src/main/java/io/deephaven/engine/testutil/generator/StringGenerator.java
  proto/proto-backplane-grpc/src/main/java/io/deephaven/proto/util/OperationHelper.java
  proto/proto-backplane-grpc/src/main/proto/deephaven/proto/table.proto
  py/client/pydeephaven/proto/table_pb2.py
  py/client/pydeephaven/proto/table_pb2_grpc.py
  replication/static/build.gradle
  replication/static/src/main/java/io/deephaven/replicators/ReplicateColumnStats.java
  server/src/main/java/io/deephaven/server/table/TableModule.java
  server/src/main/java/io/deephaven/server/table/ops/ColumnStatisticsGrpcImpl.java
  server/src/main/java/io/deephaven/server/table/ops/TableServiceGrpcImpl.java
  server/src/main/java/io/deephaven/server/table/stats/BigDecimalChunkedNumericalStats.java
  server/src/main/java/io/deephaven/server/table/stats/BigIntegerChunkedNumericalStats.java
  server/src/main/java/io/deephaven/server/table/stats/ByteChunkedNumericalStats.java
  server/src/main/java/io/deephaven/server/table/stats/CharacterChunkedStats.java
  server/src/main/java/io/deephaven/server/table/stats/ChunkedNumericalStatsKernel.java
  server/src/main/java/io/deephaven/server/table/stats/ChunkedStatsKernel.java
  server/src/main/java/io/deephaven/server/table/stats/DateTimeChunkedStats.java
  server/src/main/java/io/deephaven/server/table/stats/DoubleChunkedNumericalStats.java
  server/src/main/java/io/deephaven/server/table/stats/FloatChunkedNumericalStats.java
  server/src/main/java/io/deephaven/server/table/stats/IntegerChunkedNumericalStats.java
  server/src/main/java/io/deephaven/server/table/stats/LongChunkedNumericalStats.java
  server/src/main/java/io/deephaven/server/table/stats/ObjectChunkedStats.java
  server/src/main/java/io/deephaven/server/table/stats/ShortChunkedNumericalStats.java
  server/src/test/java/io/deephaven/server/table/stats/ChunkedStatsKernelTest.java
  web/client-api/src/main/java/io/deephaven/web/client/api/JsColumnStatistics.java
  web/client-api/src/main/java/io/deephaven/web/client/api/JsTable.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/table_pb/ColumnStatisticsRequest.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/table_pb_service/TableService.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/table_pb_service/TableServiceClient.java
Labels: jsapi, grpc, NoDocumentationNeeded, ReleaseNotesNeeded

#4764 Unit-test thread cleanup
  Util/src/main/java/io/deephaven/util/reference/CleanupReferenceProcessor.java
  java-client/session-dagger/src/test/java/io/deephaven/client/ObjectServiceTest.java
  server/src/main/java/io/deephaven/server/util/Scheduler.java
  server/src/test/java/io/deephaven/server/runner/DeephavenApiServerTestBase.java
  server/src/test/java/io/deephaven/server/runner/ServerBuilderInProcessModule.java
  server/src/test/java/io/deephaven/server/runner/scheduler/SchedulerDelegatingImplModule.java
Labels: clean up, test, ci, NoDocumentationNeeded, NoReleaseNotesNeeded

#4769 More explicit exception message for invalid key columns
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/ChunkedOperatorAggregationHelper.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableAggregationTest.java
Labels: query engine, core, NoDocumentationNeeded, NoReleaseNotesNeeded

#4752 Select: Reuse Results When Possible
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/analyzers/PreserveColumnLayer.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/analyzers/SelectAndViewAnalyzer.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/analyzers/StaticFlattenLayer.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableSelectUpdateTest.java
Labels: bug, query engine, core, NoDocumentationNeeded, ReleaseNotesNeeded

#4777 Python Client `import_table` Should not also Close the Writer
  py/client/pydeephaven/_arrow_flight_service.py
Labels: NoDocumentationNeeded, arrow, python-client, NoReleaseNotesNeeded

#4772 ExportObject: Add onSuccess Callback for use in TableService#batch
  server/src/main/java/io/deephaven/server/hierarchicaltable/HierarchicalTableServiceGrpcImpl.java
  server/src/main/java/io/deephaven/server/session/SessionState.java
  server/src/main/java/io/deephaven/server/table/ops/TableServiceGrpcImpl.java
  server/src/test/java/io/deephaven/server/session/SessionStateTest.java
Labels: bug, NoDocumentationNeeded, release blocker, ReleaseNotesNeeded

#4756 Add java client TableServiceAsync
  java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSession.java
  java-client/flight-dagger/src/test/java/io/deephaven/client/DeephavenFlightSessionTestBase.java
  java-client/session-dagger/src/test/java/io/deephaven/client/DeephavenSessionTestBase.java
  java-client/session-dagger/src/test/java/io/deephaven/client/SessionBatchMixinTest.java
  java-client/session-dagger/src/test/java/io/deephaven/client/SessionTableServicesTest.java
  java-client/session-dagger/src/test/java/io/deephaven/client/TableSpecTestBase.java
  java-client/session-dagger/src/test/java/io/deephaven/client/impl/TableServiceAsyncTest.java
  java-client/session-examples/src/main/java/io/deephaven/client/examples/FilterTable.java
  java-client/session-examples/src/main/java/io/deephaven/client/examples/TableManagerExample.java
  java-client/session-examples/src/main/java/io/deephaven/client/examples/TaintedExample.java
  java-client/session-examples/src/main/java/io/deephaven/client/examples/UnreferenceableTableExample.java
  java-client/session/src/main/java/io/deephaven/client/impl/Export.java
  java-client/session/src/main/java/io/deephaven/client/impl/ExportRequest.java
  java-client/session/src/main/java/io/deephaven/client/impl/ExportService.java
  java-client/session/src/main/java/io/deephaven/client/impl/ExportServiceRequest.java
  java-client/session/src/main/java/io/deephaven/client/impl/ExportStates.java
  java-client/session/src/main/java/io/deephaven/client/impl/ExportsRequest.java
  java-client/session/src/main/java/io/deephaven/client/impl/FutureHelper.java
  java-client/session/src/main/java/io/deephaven/client/impl/Session.java
  java-client/session/src/main/java/io/deephaven/client/impl/SessionBase.java
  java-client/session/src/main/java/io/deephaven/client/impl/SessionImpl.java
  java-client/session/src/main/java/io/deephaven/client/impl/TableHandle.java
  java-client/session/src/main/java/io/deephaven/client/impl/TableHandleManager.java
  java-client/session/src/main/java/io/deephaven/client/impl/TableHandleManagerBase.java
  java-client/session/src/main/java/io/deephaven/client/impl/TableHandleManagerBatch.java
  java-client/session/src/main/java/io/deephaven/client/impl/TableHandleManagerSerial.java
  java-client/session/src/main/java/io/deephaven/client/impl/TableService.java
  java-client/session/src/main/java/io/deephaven/client/impl/TableServiceAsyncImpl.java
  java-client/session/src/main/java/io/deephaven/client/impl/TableServiceDelegateBase.java
  java-client/session/src/main/java/io/deephaven/client/impl/TableServiceImpl.java
  java-client/session/src/test/java/io/deephaven/client/impl/ExportStatesTest.java
  server/test/src/main/java/io/deephaven/server/test/FlightMessageRoundTripTest.java
Labels: grpc, DocumentationNeeded, java-client, ReleaseNotesNeeded

#4783 Use last lexigraphical key for parquet schema inference
  engine/table/src/main/java/io/deephaven/engine/table/impl/locations/impl/KnownLocationKeyFinder.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/ParquetTools.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/ParquetTableReadWriteTest.java
Labels: bug, parquet, NoDocumentationNeeded, NoReleaseNotesNeeded

#4790 Correct EmStd empty table initialiation error.
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/emstd/BasePrimitiveEmStdOperator.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestEmStd.java
Labels: bug, NoDocumentationNeeded, NoReleaseNotesNeeded

#4793 Post Release Bump to 0.31.0
  R/rdeephaven/DESCRIPTION
  authorization-codegen/protoc-gen-contextual-auth-wiring
  authorization-codegen/protoc-gen-service-auth-wiring
  buildSrc/src/main/groovy/io.deephaven.common-conventions.gradle
  py/client-ticking/README.md
  py/client-ticking/setup.py
  py/client/README.md
  py/client/pydeephaven/__init__.py
  py/client/setup.py
  py/embedded-server/deephaven_server/__init__.py
  py/server/deephaven/__init__.py
Labels: NoDocumentationNeeded, version-bump, NoReleaseNotesNeeded

#4796 C++ Client: improve proto build script test for missing envars
  proto/proto-backplane-grpc/src/main/proto/build-cpp-protos.sh
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4797 C++ Client: some cleanups found while working on Windows port
  cpp-client/deephaven/dhclient/CMakeLists.txt
  cpp-client/deephaven/dhclient/include/private/deephaven/client/impl/escape_utils.h
  cpp-client/deephaven/dhclient/src/impl/escape_utils.cc
  cpp-client/deephaven/dhcore/include/private/deephaven/dhcore/immerutil/immer_column_source.h
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/types.h
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/utility/utility.h
  cpp-client/deephaven/dhcore/src/types.cc
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4763 Add support for MultiXYErrorBarSeries, MultiOHLCSeries figures
  Plot/src/main/java/io/deephaven/plot/datasets/multiseries/MultiOHLCSeries.java
  Plot/src/main/java/io/deephaven/plot/datasets/multiseries/MultiXYErrorBarSeries.java
  plugin/figure/src/main/java/io/deephaven/figure/FigureWidgetTranslator.java
  web/client-api/src/main/java/io/deephaven/web/client/api/widget/plot/JsFigure.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4802 Properly pass along exceptional state in BatchHandler
  java-client/session/src/main/java/io/deephaven/client/impl/ExportStates.java
  java-client/session/src/main/java/io/deephaven/client/impl/TableServiceAsyncImpl.java
Labels: bug, logging, NoDocumentationNeeded, java-client, NoReleaseNotesNeeded

#4805 Update protoc and cpp client base images.
  cpp-client/README.md
  docker/registry/cpp-clients-multi-base/gradle.properties
  docker/registry/protoc-base/gradle.properties
  proto/proto-backplane-grpc/Dockerfile
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4803 Apply typing.Literal whereever appropriate
  py/server/deephaven/dbc/__init__.py
  py/server/deephaven/pandas.py
  py/server/deephaven/table_factory.py
  py/server/deephaven/table_listener.py
  py/server/deephaven/time.py
Labels: NoDocumentationNeeded, python-server-side, NoReleaseNotesNeeded

#4807 Bump images post 0.30.0 release
  docker/registry/go/gradle.properties
  docker/registry/python/gradle.properties
  docker/registry/server-base/gradle.properties
  docker/registry/slim-base/gradle.properties
  docker/server-jetty/src/main/server-jetty/requirements.txt
  docker/server/src/main/server-netty/requirements.txt
  py/jpy-integration/build.gradle
  python-engine-test/build.gradle
Labels: NoDocumentationNeeded, version-bump, NoReleaseNotesNeeded

#4811 Avoid extra copying of r docs
  R/build.gradle
  R/r-doc.sh
Labels: build, NoDocumentationNeeded, NoReleaseNotesNeeded, r-client

#4808 `TableServiceAsyncTest`: Eliminate Compiler Overhead Variance; Close `QueryCompiler`'s `JavaFileManager`
  engine/context/src/main/java/io/deephaven/engine/context/QueryCompiler.java
  java-client/session-dagger/src/test/java/io/deephaven/client/DeephavenSessionTestBase.java
  java-client/session-dagger/src/test/java/io/deephaven/client/impl/TableServiceAsyncTest.java
  java-client/session/src/main/java/io/deephaven/client/impl/BearerHandler.java
  java-client/session/src/main/java/io/deephaven/client/impl/SessionImpl.java
  server/src/main/java/io/deephaven/server/runner/DeephavenApiServer.java
  server/src/test/java/io/deephaven/server/runner/DeephavenApiServerTestBase.java
Labels: bug, query engine, core, NoDocumentationNeeded, ReleaseNotesNeeded

#4791 JS TreeTable must always track key column values
  web/client-api/src/main/java/io/deephaven/web/client/api/tree/JsTreeTable.java
Labels: jsapi, NoDocumentationNeeded, ReleaseNotesNeeded, hierarchical_tables

#4820 Ensure LongWrapper is formatted as a Java long
  web/client-api/src/main/java/io/deephaven/web/client/api/i18n/JsNumberFormat.java
Labels: bug, jsapi, NoDocumentationNeeded, ReleaseNotesNeeded

#4816 Always export scope objects before performing other interactions
  web/client-api/src/main/java/io/deephaven/web/client/api/JsTable.java
  web/client-api/src/main/java/io/deephaven/web/client/api/WorkerConnection.java
  web/client-api/src/main/java/io/deephaven/web/client/api/impl/TicketAndPromise.java
  web/client-api/src/main/java/io/deephaven/web/client/api/tree/JsTreeTable.java
Labels: jsapi, plotting, NoDocumentationNeeded, ReleaseNotesNeeded, rollup

#4804 Server logs should be written when integration tests fail
  buildSrc/src/main/groovy/Docker.groovy
  buildSrc/src/main/groovy/io.deephaven.python-wheel.gradle
  proto/raw-js-openapi/build.gradle
Labels: build, docker, NoDocumentationNeeded, NoReleaseNotesNeeded

#4819 Moved Parquet specific methods out of DateTimeUtils
  engine/time/src/main/java/io/deephaven/time/DateTimeUtils.java
  engine/time/src/test/java/io/deephaven/time/TestDateTimeUtils.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/pagestore/topage/ToLocalDateTimePage.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/transfer/LocalDateTimeArrayTransfer.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/transfer/LocalDateTimeTransfer.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/transfer/LocalDateTimeVectorTransfer.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/util/TransferUtils.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/TestTransferUtils.java
  replication/static/src/main/java/io/deephaven/replicators/ReplicateParquetTransferObjects.java
Labels: core, parquet, NoDocumentationNeeded, NoReleaseNotesNeeded

#4786 Clarify standard deviation / variance documentation with Bessel's correction
  cpp-client/deephaven/dhclient/include/public/deephaven/client/client.h
  cpp-client/deephaven/dhclient/include/public/deephaven/client/update_by.h
  engine/function/src/templates/Numeric.ftl
  engine/table/src/main/java/io/deephaven/engine/util/TotalsTableBuilder.java
  go/pkg/client/query.go
  go/pkg/client/tablehandle.go
  py/client/pydeephaven/_table_interface.py
  py/client/pydeephaven/agg.py
  py/client/pydeephaven/table.py
  py/client/pydeephaven/updateby.py
  py/server/deephaven/agg.py
  py/server/deephaven/table.py
  py/server/deephaven/updateby.py
  table-api/src/main/java/io/deephaven/api/TableOperations.java
  table-api/src/main/java/io/deephaven/api/agg/Aggregation.java
  table-api/src/main/java/io/deephaven/api/agg/spec/AggSpecStd.java
  table-api/src/main/java/io/deephaven/api/agg/spec/AggSpecVar.java
  table-api/src/main/java/io/deephaven/api/updateby/UpdateByOperation.java
  web/WebDevelopersGuide.md
  web/client-api/src/main/java/io/deephaven/web/client/api/JsColumnStatistics.java
  web/client-api/src/main/java/io/deephaven/web/client/api/tree/enums/JsAggregationOperation.java
Labels: documentation, NoDocumentationNeeded, NoReleaseNotesNeeded

#4759 Support calling numpy ufuncs assigned to top-level names in formulas
  py/server/deephaven/table.py
  py/server/tests/test_pyfunc_return_java_values.py
Labels: NoDocumentationNeeded, python-server-side, NoReleaseNotesNeeded

#4815 change default dtype_backend for to_pandas
  py/server/deephaven/pandas.py
  py/server/tests/test_learn_gather.py
  py/server/tests/test_pandas.py
  py/server/tests/test_parquet.py
  py/server/tests/test_table.py
Labels: DocumentationNeeded, python-server-side, breaking, ReleaseNotesNeeded

#4828 Stop requesting column statistics for preview columns
  web/client-api/src/main/java/io/deephaven/web/client/api/JsTable.java
Labels: bug, jsapi, NoDocumentationNeeded, ReleaseNotesNeeded

#4813 Add TableDefinition column name helpers
  Plot/src/main/java/io/deephaven/plot/util/ArgumentValidations.java
  engine/api/src/main/java/io/deephaven/engine/table/TableDefinition.java
  engine/api/src/main/java/io/deephaven/engine/table/impl/NoSuchColumnException.java
  engine/benchmark/src/benchmark/java/io/deephaven/benchmark/engine/SortBenchmark.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/BaseTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/BucketingContext.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/CrossJoinHelper.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/NoSuchColumnException.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/RedefinableTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/TableDefaults.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/TableUpdateValidator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/ChunkedOperatorAggregationHelper.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/PartitionByChunkedOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/hierarchical/HierarchicalTableImpl.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/hierarchical/RollupTableImpl.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/remote/ConstructSnapshot.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/MultiSourceFunctionalColumn.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/snapshot/SnapshotInternalListener.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/UpdateBy.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/DynamicTableWriter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/KeyedArrayBackedMutableTable.java
  engine/table/src/main/java/io/deephaven/engine/util/OuterJoinTools.java
  engine/table/src/main/java/io/deephaven/engine/util/TableTools.java
  engine/table/src/main/java/io/deephaven/engine/util/TableToolsMergeHelper.java
  engine/table/src/main/java/io/deephaven/engine/util/TickSuppressor.java
  engine/table/src/main/java/io/deephaven/engine/util/TotalsTableBuilder.java
  engine/table/src/main/java/io/deephaven/engine/util/WindowCheck.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/MultiColumnSortTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableAggregationTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/SelectOverheadLimiter.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestAggBy.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestMoveColumns.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestTotalsTable.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/indexer/TestRowSetIndexer.java
  engine/test-utils/src/main/java/io/deephaven/engine/testutil/TstUtils.java
  engine/test-utils/src/main/java/io/deephaven/engine/testutil/locations/TableBackedColumnLocation.java
  extensions/jdbc/src/test/java/io/deephaven/jdbc/JdbcToTableAdapterTest.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/ParquetTableReadWriteTest.java
  server/src/main/java/io/deephaven/server/table/ops/SelectDistinctGrpcImpl.java
Labels: clean up, NoDocumentationNeeded, NoReleaseNotesNeeded

#4826 Use chunks in DynamicWhereFilter, fix a chunk leak, and cleanup some code generally
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/DynamicWhereFilter.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableWhereTest.java
Labels: query engine, core, NoDocumentationNeeded, ReleaseNotesNeeded

#4833 Fix a docstring error introduced in to_pandas() default dtype_backend change
  py/server/deephaven/pandas.py
Labels: NoDocumentationNeeded, python-server-side, NoReleaseNotesNeeded

#4835 ExportObject PUBLISHING State Change Bug
  server/src/main/java/io/deephaven/server/session/SessionState.java
Labels: bug, grpc, core, NoDocumentationNeeded, ReleaseNotesNeeded

#4209 README rework
  README.md
Labels: documentation, NoDocumentationNeeded, NoReleaseNotesNeeded

#4846 Added PR verification step after cherry pick
  RELEASE.md
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4780 JS API must support SKIP as an aggregation type
  web/client-api/src/main/java/io/deephaven/web/client/api/JsTotalsTableConfig.java
  web/client-api/src/main/java/io/deephaven/web/client/api/tree/JsRollupConfig.java
  web/client-api/src/main/java/io/deephaven/web/client/api/tree/enums/JsAggregationOperation.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded, rollup

#4787 JS API member/documentation cleanup
  web/client-api/src/main/java/io/deephaven/web/client/api/JsTable.java
  web/client-api/src/main/java/io/deephaven/web/client/api/filter/FilterValue.java
  web/client-api/src/main/java/io/deephaven/web/client/api/tree/JsTreeTable.java
  web/client-api/src/main/java/io/deephaven/web/client/ide/IdeConnection.java
Labels: documentation, NoDocumentationNeeded, NoReleaseNotesNeeded

#4831 Add parquet read TableDefinition support
  engine/table/src/main/java/io/deephaven/engine/table/impl/SourceTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/locations/TableLocationProvider.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/locations/impl/KnownLocationKeyFinder.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/ParquetTools.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/ParquetTableReadWriteTest.java
  py/server/deephaven/parquet.py
  py/server/tests/test_parquet.py
Labels: feature request, parquet, DocumentationNeeded, ReleaseNotesNeeded

#4794 Fix testing tools `NaN` comparison and correct new failing tests.
  engine/function/src/templates/Numeric.ftl
  engine/function/src/templates/TestNumeric.ftl
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/DoubleChunkedVarOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/FloatChunkedVarOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/rollingavg/ByteRollingAvgOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/rollingavg/CharRollingAvgOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/rollingavg/DoubleRollingAvgOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/rollingavg/FloatRollingAvgOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/rollingavg/IntRollingAvgOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/rollingavg/LongRollingAvgOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/rollingavg/ShortRollingAvgOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/rollingproduct/DoubleRollingProductOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/rollingproduct/FloatRollingProductOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/rollingstd/ByteRollingStdOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/rollingstd/CharRollingStdOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/rollingstd/DoubleRollingStdOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/rollingstd/FloatRollingStdOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/rollingstd/IntRollingStdOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/rollingstd/LongRollingStdOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/rollingstd/ShortRollingStdOperator.java
  engine/table/src/main/java/io/deephaven/engine/util/TableDiff.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/BaseUpdateByTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestRollingProduct.java
  replication/static/src/main/java/io/deephaven/replicators/ReplicateUpdateBy.java
Labels: bug, test, NoDocumentationNeeded, NoReleaseNotesNeeded

#4839 Apply query scope ctx on formula aggregation
  py/server/deephaven/agg.py
  py/server/deephaven/table.py
  py/server/tests/test_pt_proxy.py
  py/server/tests/test_table.py
Labels: NoDocumentationNeeded, python-server-side, NoReleaseNotesNeeded

#4771 Add topic, partition, and timestamp column kafka publishing support
  engine/api/src/main/java/io/deephaven/engine/table/ColumnDefinition.java
  engine/api/src/main/java/io/deephaven/engine/table/ColumnSource.java
  engine/api/src/main/java/io/deephaven/engine/table/Table.java
  engine/api/src/main/java/io/deephaven/engine/table/TableDefinition.java
  engine/api/src/main/java/io/deephaven/engine/table/TypeHelper.java
  extensions/kafka/src/main/java/io/deephaven/kafka/KafkaPublishOptions.java
  extensions/kafka/src/main/java/io/deephaven/kafka/KafkaTools.java
  extensions/kafka/src/main/java/io/deephaven/kafka/publish/PublishToKafka.java
  extensions/kafka/src/test/java/io/deephaven/kafka/KafkaPublishOptionsTest.java
  py/server/deephaven/stream/kafka/producer.py
  py/server/tests/test_kafka_producer.py
Labels: feature request, core, kafka, DocumentationNeeded, kafka-exhaust, user-reported, ReleaseNotesNeeded

#4851 Website integration for R HTML documentation
  .github/workflows/docs-ci.yml
  R/r-site.sh
Labels: documentation, NoDocumentationNeeded, ReleaseNotesNeeded, r-client

#4757 Invoke typedoc to produce browsable JS API documentation
  .github/workflows/docs-ci.yml
  settings.gradle
  web/client-api/client-api.gradle
  web/client-api/types/build.gradle
  web/client-api/types/gradle.properties
  web/client-api/types/package-lock.json
  web/client-api/types/package.json
  web/client-api/types/src/main/docker/theme.css
  web/client-api/types/tsconfig.json
Labels: documentation, jsapi, NoDocumentationNeeded, NoReleaseNotesNeeded

#4854 Correct the path to read generated typedoc when deploying
  .github/workflows/docs-ci.yml
Labels: documentation, jsapi, NoDocumentationNeeded, NoReleaseNotesNeeded

#4760 QueryPerformanceRecorder: Group Batched Operations as a Single Query
  engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/SelectOrUpdateListener.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/perf/BasePerformanceEntry.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/perf/PerformanceEntry.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/perf/QueryPerformanceNugget.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/perf/QueryPerformanceRecorder.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/perf/QueryPerformanceRecorderImpl.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/perf/QueryPerformanceRecorderState.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/perf/QueryProcessingResults.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/perf/QueryState.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/perf/UpdatePerformanceStreamPublisher.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/perf/UpdatePerformanceTracker.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/ConditionFilter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/DhFormulaColumn.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/codegen/JavaKernelBuilder.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/UpdateBy.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/AsyncErrorImpl.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/AsyncErrorStreamPublisher.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/EngineMetrics.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/OperationInitializationPoolJobScheduler.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/QueryOperationPerformanceImpl.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/QueryOperationPerformanceStreamPublisher.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/QueryPerformanceImpl.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/QueryPerformanceStreamPublisher.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/UpdateGraphJobScheduler.java
  engine/table/src/main/java/io/deephaven/engine/tablelogger/QueryOperationPerformanceLogLogger.java
  engine/table/src/main/java/io/deephaven/engine/tablelogger/QueryPerformanceLogLogger.java
  engine/table/src/main/java/io/deephaven/engine/util/TableShowTools.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/select/TestConstantFormulaEvaluation.java
  extensions/csv/src/main/java/io/deephaven/csv/CsvTools.java
  extensions/performance/src/main/java/io/deephaven/engine/table/impl/util/PerformanceQueries.java
  extensions/performance/src/main/java/io/deephaven/engine/table/impl/util/PerformanceQueriesGeneral.java
  props/configs/src/main/resources/defaultPackageFilters.qpr
  py/server/deephaven/perfmon.py
  py/server/tests/test_perfmon.py
  server/src/main/java/io/deephaven/server/arrow/ArrowFlightUtil.java
  server/src/main/java/io/deephaven/server/arrow/FlightServiceGrpcImpl.java
  server/src/main/java/io/deephaven/server/barrage/BarrageMessageProducer.java
  server/src/main/java/io/deephaven/server/console/ConsoleServiceGrpcImpl.java
  server/src/main/java/io/deephaven/server/hierarchicaltable/HierarchicalTableServiceGrpcImpl.java
  server/src/main/java/io/deephaven/server/object/ObjectServiceGrpcImpl.java
  server/src/main/java/io/deephaven/server/partitionedtable/PartitionedTableServiceGrpcImpl.java
  server/src/main/java/io/deephaven/server/runner/DeephavenApiServer.java
  server/src/main/java/io/deephaven/server/session/SessionServiceGrpcImpl.java
  server/src/main/java/io/deephaven/server/session/SessionState.java
  server/src/main/java/io/deephaven/server/session/TicketRouter.java
  server/src/main/java/io/deephaven/server/table/inputtables/InputTableServiceGrpcImpl.java
  server/src/main/java/io/deephaven/server/table/ops/TableServiceGrpcImpl.java
Labels: query engine, core, NoDocumentationNeeded, ReleaseNotesNeeded

#4855 C++ Client: fix one incorrect mutex unlock, remove one needless unlock
  cpp-client/deephaven/dhclient/src/impl/table_handle_impl.cc
  cpp-client/deephaven/dhclient/src/server/server.cc
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4857 C++ Client: avoid deprecated Arrow methods, plus conform to coding style
  cpp-client/deephaven/dhclient/include/public/deephaven/client/client.h
  cpp-client/deephaven/dhclient/include/public/deephaven/client/flight.h
  cpp-client/deephaven/dhclient/include/public/deephaven/client/utility/arrow_util.h
  cpp-client/deephaven/dhclient/src/client.cc
  cpp-client/deephaven/dhclient/src/flight.cc
  cpp-client/deephaven/dhclient/src/utility/arrow_util.cc
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4863 Fix URL in pkgdown file
  R/rdeephaven/pkgdown/_pkgdown.yml
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded, r-client

#4867 Correct R Docsite
  R/build.gradle
  R/r-site.sh
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded, r-client

#4862 QueryPerformanceRecorder: Changes for CorePlus Integration
  engine/table/src/main/java/io/deephaven/engine/table/impl/perf/PerformanceEntry.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/perf/QueryPerformanceNugget.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/perf/QueryPerformanceRecorder.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/perf/QueryPerformanceRecorderImpl.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/perf/QueryPerformanceRecorderState.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/perf/UpdatePerformanceStreamPublisher.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/perf/UpdatePerformanceTracker.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/ConditionFilter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/DhFormulaColumn.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/codegen/JavaKernelBuilder.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/QueryOperationPerformanceStreamPublisher.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/QueryPerformanceStreamPublisher.java
  extensions/performance/src/main/java/io/deephaven/engine/table/impl/util/PerformanceQueriesGeneral.java
Labels: core, NoDocumentationNeeded, NoReleaseNotesNeeded

#4853 Docs CI Upload Versioned Artifacts
  .github/workflows/docs-ci.yml
  RELEASE.md
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4876 ConstructSnapshot + BarrageMessageProducer: Use Static ConstructSnapshot Fast Path
  engine/table/src/main/java/io/deephaven/engine/table/impl/remote/ConstructSnapshot.java
  server/src/main/java/io/deephaven/server/barrage/BarrageMessageProducer.java
Labels: bug, barrage, core, NoDocumentationNeeded, ReleaseNotesNeeded

#4844 Added offset index based parquet reading support
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/ColumnChunkReader.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/ColumnChunkReaderImpl.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/ColumnPageReaderImpl.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/ColumnWriterImpl.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/ParquetFileReader.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/RowGroupReaderImpl.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/location/ParquetColumnLocation.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/location/ParquetTableLocation.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/metadata/TableInfo.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/pagestore/ColumnChunkPageStore.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/pagestore/FixedPageSizeColumnChunkPageStore.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/pagestore/OffsetIndexBasedColumnChunkPageStore.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/pagestore/VariablePageSizeColumnChunkPageStore.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/ParquetTableReadWriteTest.java
  extensions/parquet/table/src/test/resources/ReferenceParquetArrayData.parquet
  extensions/parquet/table/src/test/resources/ReferenceParquetData.parquet
  extensions/parquet/table/src/test/resources/ReferenceParquetFileWithDifferentPageSizes1.parquet
  extensions/parquet/table/src/test/resources/ReferenceParquetFileWithDifferentPageSizes2.parquet
  extensions/parquet/table/src/test/resources/ReferenceParquetVectorData.parquet
Labels: feature request, parquet, NoDocumentationNeeded, NoReleaseNotesNeeded

#4865 Add in-development version support
  .github/workflows/publish-ci.yml
  RELEASE.md
  authorization-codegen/protoc-gen-contextual-auth-wiring
  authorization-codegen/protoc-gen-service-auth-wiring
  authorization/README.md
  buildSrc/src/main/groovy/io.deephaven.common-conventions.gradle
  gradle.properties
  py/client-ticking/README.md
  py/client-ticking/build.gradle
  py/client-ticking/setup.py
  py/client/README.md
  py/client/pydeephaven/__init__.py
  py/client/setup.py
  py/embedded-server/deephaven_server/__init__.py
  py/embedded-server/setup.py
  py/server/deephaven/__init__.py
  py/server/setup.py
Labels: build, NoDocumentationNeeded, release, enhancement, NoReleaseNotesNeeded

#4880 Introduce Blink-To-Append-Only Memoization and Apply to TableLoggers
  engine/table/src/main/java/io/deephaven/engine/table/impl/BlinkTableTools.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/MemoizedOperationKey.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/OperationSnapshotControl.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/OperationSnapshotControlEx.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/EngineMetrics.java
  engine/table/src/main/java/io/deephaven/engine/updategraph/impl/PeriodicUpdateGraph.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestBlinkTableTools.java
Labels: query engine, core, DocumentationNeeded, ReleaseNotesNeeded

#4870 UPDATE: Change `timeTable` pydoc to match signature
  py/server/deephaven/table_factory.py
Labels: community, python, NoDocumentationNeeded, trivial, NoReleaseNotesNeeded

#4873 Add information about not requiring WSL for pip-installed Deephaven
  README.md
  py/server/README.md
Labels: documentation, NoDocumentationNeeded, NoReleaseNotesNeeded

#4885 Collect JsPlugin instances before starting Jetty
  plugin/src/main/java/io/deephaven/plugin/js/JsPluginRegistration.java
  server/jetty/src/main/java/io/deephaven/server/jetty/JettyBackedGrpcServer.java
  server/jetty/src/main/java/io/deephaven/server/jetty/JettyServerModule.java
  server/jetty/src/main/java/io/deephaven/server/jetty/JsPlugins.java
  server/src/main/java/io/deephaven/server/plugin/PluginRegistrationVisitor.java
  server/src/main/java/io/deephaven/server/plugin/PluginsModule.java
  server/src/main/java/io/deephaven/server/plugin/js/JsPluginNoopConsumerModule.java
Labels: NoDocumentationNeeded, plug-ins, NoReleaseNotesNeeded

#4886 Fix github action release versioning
  .github/scripts/gradle-properties.sh
  .github/workflows/publish-ci.yml
  RELEASE.md
Labels: ci, NoDocumentationNeeded, NoReleaseNotesNeeded

#4889 Address PartitionedTable transform and partitionedTransform dependency issues
  engine/api/src/main/java/io/deephaven/engine/table/PartitionedTable.java
  engine/api/src/main/java/io/deephaven/engine/table/PartitionedTableFactory.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/ChunkedOperatorAggregationHelper.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/partitioned/BaseTableTransformationColumn.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/partitioned/BiTableTransformationColumn.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/partitioned/PartitionedTableImpl.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/partitioned/PartitionedTableProxyImpl.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/partitioned/TableTransformationColumn.java
  engine/table/src/main/java/io/deephaven/engine/updategraph/impl/PeriodicUpdateGraph.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/PartitionedTableTest.java
Labels: bug, query engine, core, NoDocumentationNeeded, partitioned_tables, ReleaseNotesNeeded

#4883 C++ Client: vendor the "fmt" and "date" projects and start to use them
  cpp-client/deephaven/dhcore/CMakeLists.txt
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/types.h
  cpp-client/deephaven/dhcore/include/public/deephaven/third_party/fmt/args.h
  cpp-client/deephaven/dhcore/include/public/deephaven/third_party/fmt/chrono.h
  cpp-client/deephaven/dhcore/include/public/deephaven/third_party/fmt/color.h
  cpp-client/deephaven/dhcore/include/public/deephaven/third_party/fmt/compile.h
  cpp-client/deephaven/dhcore/include/public/deephaven/third_party/fmt/core.h
  cpp-client/deephaven/dhcore/include/public/deephaven/third_party/fmt/format-inl.h
  cpp-client/deephaven/dhcore/include/public/deephaven/third_party/fmt/format.h
  cpp-client/deephaven/dhcore/include/public/deephaven/third_party/fmt/os.h
  cpp-client/deephaven/dhcore/include/public/deephaven/third_party/fmt/ostream.h
  cpp-client/deephaven/dhcore/include/public/deephaven/third_party/fmt/printf.h
  cpp-client/deephaven/dhcore/include/public/deephaven/third_party/fmt/ranges.h
  cpp-client/deephaven/dhcore/include/public/deephaven/third_party/fmt/std.h
  cpp-client/deephaven/dhcore/include/public/deephaven/third_party/fmt/xchar.h
  cpp-client/deephaven/dhcore/src/types.cc
  cpp-client/deephaven/dhcore/src/utility/utility.cc
  cpp-client/deephaven/dhcore/third_party/date/LICENSE.txt
  cpp-client/deephaven/dhcore/third_party/date/README-deephaven.md
  cpp-client/deephaven/dhcore/third_party/date/include/date/date.h
  cpp-client/deephaven/dhcore/third_party/fmt/LICENSE.rst
  cpp-client/deephaven/dhcore/third_party/fmt/README-deephaven.md
  cpp-client/deephaven/dhcore/third_party/fmt/src/fmt.cc
  cpp-client/deephaven/dhcore/third_party/fmt/src/format.cc
  cpp-client/deephaven/dhcore/third_party/fmt/src/os.cc
  cpp-client/deephaven/tests/date_time_test.cc
  cpp-client/deephaven/tests/utility_test.cc
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4892 Provide JsPlugins as Singleton
  server/jetty/src/main/java/io/deephaven/server/jetty/JettyServerModule.java
Labels: bug, NoDocumentationNeeded, plug-ins, NoReleaseNotesNeeded

#4891 Add the optional dependencies parameters in the transform/partitioned_transform methods
  py/server/deephaven/table.py
  py/server/tests/test_partitioned_table.py
Labels: DocumentationNeeded, python-server-side, ReleaseNotesNeeded

#4860 C++ Client: update examples, demos, and docs with style guide, Arrow deprecation
  cpp-client/deephaven/examples/create_table_with_arrow_flight/main.cc
  cpp-client/deephaven/examples/demos/chapter1.cc
  cpp-client/deephaven/examples/doc/create_table_with_tablemaker.rst
  cpp-client/deephaven/examples/doc/fluent.rst
  cpp-client/deephaven/examples/doc/read_data_with_arrow_flight.rst
  cpp-client/deephaven/examples/read_csv/main.cc
  cpp-client/deephaven/examples/read_table_with_arrow_flight/main.cc
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4887 Add notes on releasing jsapi-types
  RELEASE.md
  web/client-api/types/package.json
Labels: jsapi, NoDocumentationNeeded, NoReleaseNotesNeeded

#4895 Added note to pydeephaven example
  py/client/docs/source/examples.rst
Labels: NoDocumentationNeeded, python-client, NoReleaseNotesNeeded

#4900 C++ client: remove all Stringf/Streamf and related
  cpp-client/deephaven/dhclient/include/public/deephaven/client/utility/table_maker.h
  cpp-client/deephaven/dhclient/src/impl/table_handle_impl.cc
  cpp-client/deephaven/dhclient/src/impl/table_handle_manager_impl.cc
  cpp-client/deephaven/dhclient/src/server/server.cc
  cpp-client/deephaven/dhclient/src/subscription/subscribe_thread.cc
  cpp-client/deephaven/dhclient/src/update_by.cc
  cpp-client/deephaven/dhclient/src/utility/arrow_util.cc
  cpp-client/deephaven/dhclient/src/utility/executor.cc
  cpp-client/deephaven/dhclient/src/utility/table_maker.cc
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/clienttable/client_table.h
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/container/row_sequence.h
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/types.h
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/utility/utility.h
  cpp-client/deephaven/dhcore/src/chunk/chunk.cc
  cpp-client/deephaven/dhcore/src/clienttable/client_table.cc
  cpp-client/deephaven/dhcore/src/clienttable/schema.cc
  cpp-client/deephaven/dhcore/src/column/column_source_utils.cc
  cpp-client/deephaven/dhcore/src/container/row_sequence.cc
  cpp-client/deephaven/dhcore/src/ticking/barrage_processor.cc
  cpp-client/deephaven/dhcore/src/ticking/immer_table_state.cc
  cpp-client/deephaven/dhcore/src/ticking/index_decoder.cc
  cpp-client/deephaven/dhcore/src/ticking/shift_processor.cc
  cpp-client/deephaven/dhcore/src/ticking/space_mapper.cc
  cpp-client/deephaven/dhcore/src/utility/utility.cc
  cpp-client/deephaven/tests/add_drop_test.cc
  cpp-client/deephaven/tests/aggregates_test.cc
  cpp-client/deephaven/tests/input_table_test.cc
  cpp-client/deephaven/tests/join_test.cc
  cpp-client/deephaven/tests/lastby_test.cc
  cpp-client/deephaven/tests/new_table_test.cc
  cpp-client/deephaven/tests/select_test.cc
  cpp-client/deephaven/tests/test_util.cc
  cpp-client/deephaven/tests/ticking_test.cc
  cpp-client/deephaven/tests/validation_test.cc
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4674 Clean up some legacy code and improve build
  Base/src/main/java/io/deephaven/base/stats/ItemUpdateListener.java
  Base/src/test/java/io/deephaven/base/stats/HistogramPower2Test.java
  Base/src/test/java/io/deephaven/base/stats/HistogramStateTest.java
  FishUtil/build.gradle
  FishUtil/cpp/MicroTimer.cpp
  FishUtil/cpp/MicroTimer.h
  FishUtil/cpp/SignalUtils.cpp
  FishUtil/cpp/SignalUtils.h
  FishUtil/gradle.properties
  FishUtil/src/main/java/io/deephaven/util/DateUtil.java
  FishUtil/src/main/java/io/deephaven/util/ExceptionUtil.java
  FishUtil/src/main/java/io/deephaven/util/Mailer.java
  FishUtil/src/main/java/io/deephaven/util/ThreadSafeDateFormat.java
  FishUtil/src/main/java/io/deephaven/util/Validate.java
  FishUtil/src/main/java/io/deephaven/util/formatters/ISO8601.java
  FishUtil/src/main/java/io/deephaven/util/signals/SignalSender.java
  FishUtil/src/main/java/io/deephaven/util/signals/SignalUtils.java
  FishUtil/src/main/java/io/deephaven/util/threads/ThreadDump.java
  IO/src/main/java/io/deephaven/io/NioUtil.java
  IO/src/main/java/io/deephaven/io/sched/Job.java
  IO/src/main/java/io/deephaven/io/sched/JobState.java
  IO/src/main/java/io/deephaven/io/sched/JobStateTimeoutQueue.java
  IO/src/main/java/io/deephaven/io/sched/Scheduler.java
  IO/src/main/java/io/deephaven/io/sched/TimedJob.java
  IO/src/main/java/io/deephaven/io/sched/YASchedulerImpl.java
  IO/src/test/java/io/deephaven/io/sched/TestJobStateTimeoutQueue.java
  Net/build.gradle
  Net/gradle.properties
  Net/src/main/java/io/deephaven/net/CommBase.java
  Net/src/main/java/io/deephaven/net/impl/nio/FastNIODriver.java
  Net/src/main/java/io/deephaven/net/impl/nio/NIODriver.java
  Stats/build.gradle
  Stats/src/main/java/io/deephaven/stats/StatsCPUCollector.java
  Stats/src/main/java/io/deephaven/stats/StatsDriver.java
  Stats/src/main/java/io/deephaven/stats/util/OSUtil.java
  TableLogger/TableLogger.gradle
  Util/src/main/java/io/deephaven/util/process/BaseProcessEnvironment.java
  Util/src/main/java/io/deephaven/util/process/DefaultFatalErrorReporter.java
  Util/src/main/java/io/deephaven/util/process/DefaultProcessEnvironment.java
  Util/src/main/java/io/deephaven/util/process/FatalErrorReporter.java
  Util/src/main/java/io/deephaven/util/process/FatalErrorReporterBase.java
  Util/src/main/java/io/deephaven/util/process/LoggerShutdownTask.java
  Util/src/main/java/io/deephaven/util/process/OnetimeShutdownTask.java
  Util/src/main/java/io/deephaven/util/process/ProcessEnvironment.java
  Util/src/main/java/io/deephaven/util/process/ShutdownManager.java
  Util/src/main/java/io/deephaven/util/process/ShutdownManagerImpl.java
  buildSrc/src/main/groovy/io.deephaven.java-classpath-conventions.gradle
  engine/table/build.gradle
  engine/table/src/main/java/io/deephaven/engine/updategraph/impl/PeriodicUpdateGraph.java
  engine/table/src/main/java/io/deephaven/engine/util/file/TrackedFileHandleFactory.java
  engine/table/src/test/java/io/deephaven/engine/util/file/TestTrackedFileHandleFactory.java
  engine/test-utils/build.gradle
  engine/time/build.gradle
  engine/updategraph/build.gradle
  engine/updategraph/src/main/java/io/deephaven/engine/liveness/Liveness.java
  proto/raw-js-openapi/Dockerfile
  server/build.gradle
  settings.gradle
Labels: feature request, build, clean up, core, NoDocumentationNeeded, ReleaseNotesNeeded

#4789 Add key column and column properties to JsPartitionedTable
  web/client-api/src/main/java/io/deephaven/web/client/api/JsPartitionedTable.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded
