Repository deephaven/deephaven-core, pull requests merged in 2023-12, with the labels that each got.

#4878 fix: Add BigDecimal and BigInteger as numeric aggregation options
  web/client-api/src/main/java/io/deephaven/web/client/api/tree/enums/JsAggregationOperation.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4613 EventDrivenUpdateGraph.
  engine/context/src/main/java/io/deephaven/engine/context/PoisonedUpdateGraph.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/perf/UpdatePerformanceTracker.java
  engine/table/src/main/java/io/deephaven/engine/updategraph/impl/BaseUpdateGraph.java
  engine/table/src/main/java/io/deephaven/engine/updategraph/impl/EventDrivenUpdateGraph.java
  engine/table/src/main/java/io/deephaven/engine/updategraph/impl/PeriodicUpdateGraph.java
  engine/table/src/main/java/io/deephaven/engine/updategraph/impl/PoisonedNotificationProcessor.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/CapturingUpdateGraph.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableTest.java
  engine/table/src/test/java/io/deephaven/engine/updategraph/impl/TestEventDrivenUpdateGraph.java
  engine/updategraph/src/main/java/io/deephaven/engine/updategraph/UpdateGraph.java
Labels: query engine, core, NoDocumentationNeeded, ReleaseNotesNeeded

#4926 Add a note in C++ client's README.md about build-dependencies.sh version.
  cpp-client/README.md
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4923 Simplify Input Table Interface.
  engine/table/src/main/java/io/deephaven/engine/table/impl/TableCreatorImpl.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/AppendOnlyArrayBackedInputTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/BaseArrayBackedInputTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/KeyedArrayBackedInputTable.java
  engine/table/src/main/java/io/deephaven/engine/util/config/InputTableEnumGetter.java
  engine/table/src/main/java/io/deephaven/engine/util/config/InputTableRowSetter.java
  engine/table/src/main/java/io/deephaven/engine/util/input/InputTableStatusListener.java
  engine/table/src/main/java/io/deephaven/engine/util/input/InputTableUpdater.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/util/TestFunctionGeneratedTableFactory.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/util/TestKeyedArrayBackedInputTable.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/util/TestKeyedArrayBackedMutableTable.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/BarrageUtil.java
  py/server/deephaven/table_factory.py
  server/src/main/java/io/deephaven/server/table/inputtables/InputTableServiceGrpcImpl.java
  server/src/main/java/io/deephaven/server/table/ops/CreateInputTableGrpcImpl.java
Labels: query engine, core, DocumentationNeeded, input-tables, ReleaseNotesNeeded

#4904 Docs CI Rework for Versioned Deploy
  .github/workflows/docs-ci-v2.yml
Labels: ci, NoDocumentationNeeded, NoReleaseNotesNeeded

#4939 Fix JS client leaking exported references, clarify dh.Widget API
  web/client-api/src/main/java/io/deephaven/web/client/api/JsPartitionedTable.java
  web/client-api/src/main/java/io/deephaven/web/client/api/WorkerConnection.java
  web/client-api/src/main/java/io/deephaven/web/client/api/console/JsVariableDefinition.java
  web/client-api/src/main/java/io/deephaven/web/client/api/tree/JsTreeTable.java
  web/client-api/src/main/java/io/deephaven/web/client/api/widget/JsWidget.java
  web/client-api/src/main/java/io/deephaven/web/client/api/widget/JsWidgetExportedObject.java
  web/client-api/src/main/java/io/deephaven/web/client/ide/IdeSession.java
Labels: documentation, jsapi, NoDocumentationNeeded, plug-ins, ReleaseNotesNeeded

#4940 fix: LongWrapper comparison through value instead of object
  web/client-api/src/main/java/io/deephaven/web/client/api/LongWrapper.java
Labels: jsapi, NoDocumentationNeeded, NoReleaseNotesNeeded

#4941 Docs CI V2 Rework For Old Rsync
  .github/workflows/docs-ci-v2.yml
Labels: ci, NoDocumentationNeeded, NoReleaseNotesNeeded

#4943 Bump server-base images
  docker/registry/server-base/gradle.properties
  docker/server-jetty/src/main/server-jetty/requirements.txt
  docker/server/src/main/server-netty/requirements.txt
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4945 Revert change auto-releasing fetch only widgets
  web/client-api/src/main/java/io/deephaven/web/client/api/widget/JsWidget.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4934 Adds InputTableService support for blink tables
  cpp-client/deephaven/dhclient/proto/deephaven/proto/table.pb.cc
  cpp-client/deephaven/dhclient/proto/deephaven/proto/table.pb.h
  engine/table/src/main/java/io/deephaven/engine/table/impl/TableCreatorImpl.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/BaseArrayBackedInputTable.java
  engine/table/src/main/java/io/deephaven/engine/util/input/InputTableUpdater.java
  engine/table/src/main/java/io/deephaven/stream/TablePublisher.java
  engine/table/src/main/java/io/deephaven/stream/TableStreamPublisherImpl.java
  java-client/session/src/main/java/io/deephaven/client/impl/BatchTableRequestBuilder.java
  proto/proto-backplane-grpc/src/main/proto/deephaven/proto/table.proto
  py/client/pydeephaven/proto/table_pb2.py
  qst/src/main/java/io/deephaven/qst/table/BlinkInputTable.java
  qst/src/main/java/io/deephaven/qst/table/InputTable.java
  qst/src/main/java/io/deephaven/qst/table/TableLabelVisitor.java
  server/src/main/java/io/deephaven/server/table/inputtables/InputTableServiceGrpcImpl.java
  server/src/main/java/io/deephaven/server/table/ops/CreateInputTableGrpcImpl.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4919 Make OperationInitializer non-static
  Integrations/src/main/java/io/deephaven/integrations/python/PythonDeephavenSession.java
  Util/src/main/java/io/deephaven/util/thread/ThreadInitializationFactory.java
  engine/context/src/main/java/io/deephaven/engine/context/ExecutionContext.java
  engine/context/src/main/java/io/deephaven/engine/context/PoisonedOperationInitializer.java
  engine/context/src/main/java/io/deephaven/engine/context/PoisonedUpdateGraph.java
  engine/context/src/test/java/io/deephaven/engine/context/TestQueryCompiler.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/AbstractFilterExecution.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/InitialFilterExecution.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/OperationInitializationThreadPool.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/partitioned/PartitionedTableImpl.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/partitioned/PartitionedTableProxyImpl.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/rangejoin/RangeJoinOperation.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/UnionSourceManager.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/UpdateBy.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/OperationInitializationPoolJobScheduler.java
  engine/table/src/main/java/io/deephaven/engine/updategraph/impl/PeriodicUpdateGraph.java
  engine/table/src/main/java/io/deephaven/engine/util/AbstractScriptSession.java
  engine/table/src/main/java/io/deephaven/engine/util/GroovyDeephavenSession.java
  engine/table/src/main/java/io/deephaven/engine/util/NoLanguageDeephavenSession.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/FuzzerTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/PartitionedTableTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableWhereTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/select/TestConditionFilterGeneration.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/select/TestFormulaColumnGeneration.java
  engine/table/src/test/java/io/deephaven/engine/updategraph/impl/TestEventDrivenUpdateGraph.java
  engine/table/src/test/java/io/deephaven/engine/util/scripts/TestGroovyDeephavenSession.java
  engine/test-utils/src/main/java/io/deephaven/engine/context/TestExecutionContext.java
  engine/test-utils/src/main/java/io/deephaven/engine/testutil/ControlledUpdateGraph.java
  engine/updategraph/src/main/java/io/deephaven/engine/updategraph/OperationInitializer.java
  props/configs/src/main/resources/dh-defaults.prop
  props/test-configs/src/main/resources/dh-tests.prop
  py/server/test_helper/__init__.py
  python-engine-test/src/test/java/io/deephaven/engine/table/impl/select/TestConditionFilter.java
  server/src/main/java/io/deephaven/server/console/NoConsoleSessionModule.java
  server/src/main/java/io/deephaven/server/console/SessionToExecutionStateModule.java
  server/src/main/java/io/deephaven/server/console/groovy/GroovyConsoleSessionModule.java
  server/src/main/java/io/deephaven/server/console/python/PythonConsoleSessionModule.java
  server/src/main/java/io/deephaven/server/console/python/PythonDebuggingModule.java
  server/src/main/java/io/deephaven/server/runner/DeephavenApiServer.java
  server/src/main/java/io/deephaven/server/runner/scheduler/SchedulerModule.java
  server/src/test/java/io/deephaven/server/appmode/ApplicationServiceGrpcImplTest.java
  server/src/test/java/io/deephaven/server/appmode/ApplicationTest.java
  server/test/src/main/java/io/deephaven/server/test/FlightMessageRoundTripTest.java
  sphinx/source/conf.py
Labels: DocumentationNeeded, ReleaseNotesNeeded

#4925 Add concrete JsPlugin
  docker/registry/server-base/gradle.properties
  docker/server-jetty/src/main/server-jetty/requirements.txt
  docker/server/src/main/server-netty/requirements.txt
  plugin/src/main/java/io/deephaven/plugin/Plugin.java
  plugin/src/main/java/io/deephaven/plugin/js/JsPlugin.java
  plugin/src/main/java/io/deephaven/plugin/js/JsPluginBase.java
  plugin/src/main/java/io/deephaven/plugin/js/JsPluginManifestPath.java
  plugin/src/main/java/io/deephaven/plugin/js/JsPluginPackagePath.java
  plugin/src/main/java/io/deephaven/plugin/js/Paths.java
  plugin/src/main/java/io/deephaven/plugin/js/PathsAll.java
  plugin/src/main/java/io/deephaven/plugin/js/PathsInternal.java
  plugin/src/main/java/io/deephaven/plugin/js/PathsPrefixes.java
  plugin/src/main/java/io/deephaven/plugin/js/package-info.java
  py/server/deephaven_internal/plugin/js/__init__.py
  py/server/deephaven_internal/plugin/register.py
  py/server/setup.py
  server/jetty/src/main/java/io/deephaven/server/jetty/CopyHelper.java
  server/jetty/src/main/java/io/deephaven/server/jetty/JsPluginManifest.java
  server/jetty/src/main/java/io/deephaven/server/jetty/JsPlugins.java
  server/jetty/src/main/java/io/deephaven/server/jetty/JsPluginsZipFilesystem.java
  server/jetty/src/test/java/io/deephaven/server/jetty/JettyFlightRoundTripTest.java
  server/jetty/src/test/java/io/deephaven/server/jetty/js/Example123Registration.java
  server/jetty/src/test/java/io/deephaven/server/jetty/js/Sentinel.java
  server/jetty/src/test/java/io/deephaven/server/plugin/js/JsPluginsManifestRegistration.java
  server/jetty/src/test/java/io/deephaven/server/plugin/js/JsPluginsNpmPackageRegistration.java
  server/jetty/src/test/resources/io/deephaven/server/jetty/js/examples/@deephaven_test/example1/dist/index.js
  server/jetty/src/test/resources/io/deephaven/server/jetty/js/examples/@deephaven_test/example1/dist/index2.js
  server/jetty/src/test/resources/io/deephaven/server/jetty/js/examples/@deephaven_test/example1/package.json
  server/jetty/src/test/resources/io/deephaven/server/jetty/js/examples/@deephaven_test/example2/dist/index.js
  server/jetty/src/test/resources/io/deephaven/server/jetty/js/examples/@deephaven_test/example2/dist/index2.js
  server/jetty/src/test/resources/io/deephaven/server/jetty/js/examples/@deephaven_test/example2/package.json
  server/jetty/src/test/resources/io/deephaven/server/jetty/js/examples/@deephaven_test/example3/index.js
  server/jetty/src/test/resources/io/deephaven/server/jetty/js/examples/manifest.json
  server/netty/src/test/java/io/deephaven/server/netty/NettyFlightRoundTripTest.java
  server/src/main/java/io/deephaven/server/plugin/PluginRegistrationVisitor.java
  server/src/main/java/io/deephaven/server/plugin/js/Jackson.java
  server/src/main/java/io/deephaven/server/plugin/js/JsPluginConfigDirRegistration.java
  server/src/main/java/io/deephaven/server/plugin/js/JsPluginFromNpmPackage.java
  server/src/main/java/io/deephaven/server/plugin/js/JsPluginManifest.java
  server/src/main/java/io/deephaven/server/plugin/js/JsPluginManifestEntry.java
  server/src/main/java/io/deephaven/server/plugin/js/JsPluginManifestRegistration.java
  server/src/main/java/io/deephaven/server/plugin/js/JsPluginModule.java
  server/src/main/java/io/deephaven/server/plugin/js/JsPluginNpmPackageRegistration.java
  server/src/main/java/io/deephaven/server/plugin/js/JsPluginsFromManifest.java
  server/src/main/java/io/deephaven/server/plugin/js/NpmPackage.java
  server/src/main/java/io/deephaven/server/plugin/python/CallbackAdapter.java
  server/test/src/main/java/io/deephaven/server/test/FlightMessageRoundTripTest.java
Labels: DocumentationNeeded, plug-ins, javascript, ReleaseNotesNeeded

#4949 Python API to access Java server threads
  Integrations/src/main/java/io/deephaven/integrations/python/PythonDeephavenSession.java
  py/server/deephaven/server/__init__.py
  py/server/deephaven/server/executors.py
Labels: NoDocumentationNeeded, release blocker, python-server-side, ReleaseNotesNeeded

#4944 Barrage Subscription/Snapshot Future's Manage Additional Liveness Until First #get
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/BarrageUtil.java
  java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSession.java
  java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshot.java
  java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshotImpl.java
  java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscription.java
  java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java
Labels: core, NoDocumentationNeeded, barrage-wrkr2wrkr, NoReleaseNotesNeeded

#4938 feat: Add iframe/widget endpoint for displaying widgets
  .github/workflows/update-web.yml
  server/jetty/src/main/java/io/deephaven/server/jetty/JettyBackedGrpcServer.java
  web/client-ui/Dockerfile
Labels: DocumentationNeeded, ReleaseNotesNeeded

#4951 Bump to 0.32.0-SNAPSHOT
  R/rdeephaven/DESCRIPTION
  gradle.properties
  web/client-api/types/package.json
Labels: NoDocumentationNeeded, version-bump, NoReleaseNotesNeeded

#4956 Update image refs to match base image bump to protobuf 3.21.2
  cpp-client/README.md
  cpp-client/deephaven/dhclient/proto/deephaven/proto/application.pb.cc
  cpp-client/deephaven/dhclient/proto/deephaven/proto/application.pb.h
  cpp-client/deephaven/dhclient/proto/deephaven/proto/config.pb.cc
  cpp-client/deephaven/dhclient/proto/deephaven/proto/config.pb.h
  cpp-client/deephaven/dhclient/proto/deephaven/proto/console.pb.cc
  cpp-client/deephaven/dhclient/proto/deephaven/proto/console.pb.h
  cpp-client/deephaven/dhclient/proto/deephaven/proto/hierarchicaltable.pb.cc
  cpp-client/deephaven/dhclient/proto/deephaven/proto/hierarchicaltable.pb.h
  cpp-client/deephaven/dhclient/proto/deephaven/proto/inputtable.pb.cc
  cpp-client/deephaven/dhclient/proto/deephaven/proto/inputtable.pb.h
  cpp-client/deephaven/dhclient/proto/deephaven/proto/object.pb.cc
  cpp-client/deephaven/dhclient/proto/deephaven/proto/object.pb.h
  cpp-client/deephaven/dhclient/proto/deephaven/proto/partitionedtable.pb.cc
  cpp-client/deephaven/dhclient/proto/deephaven/proto/partitionedtable.pb.h
  cpp-client/deephaven/dhclient/proto/deephaven/proto/session.pb.cc
  cpp-client/deephaven/dhclient/proto/deephaven/proto/session.pb.h
  cpp-client/deephaven/dhclient/proto/deephaven/proto/storage.pb.cc
  cpp-client/deephaven/dhclient/proto/deephaven/proto/storage.pb.h
  cpp-client/deephaven/dhclient/proto/deephaven/proto/table.pb.cc
  cpp-client/deephaven/dhclient/proto/deephaven/proto/table.pb.h
  cpp-client/deephaven/dhclient/proto/deephaven/proto/ticket.pb.cc
  cpp-client/deephaven/dhclient/proto/deephaven/proto/ticket.pb.h
  docker/registry/cpp-clients-multi-base/gradle.properties
  docker/registry/protoc-base/gradle.properties
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4958 Correctly allow base64 prefixes for "s/"
  web/client-api/src/main/java/io/deephaven/web/client/api/console/JsVariableDefinition.java
Labels: jsapi, NoDocumentationNeeded, ReleaseNotesNeeded

#4953 Distinguish between np type hints from Py ones
  py/server/deephaven/_udf.py
  py/server/tests/test_udf_numpy_args.py
Labels: NoDocumentationNeeded, python-server-side, NoReleaseNotesNeeded

#4931 fix: JsPartitionedTable keyColumn and keyColumnTypes ordering
  web/client-api/src/main/java/io/deephaven/web/client/api/JsPartitionedTable.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4961 Remove unused/broken tests
  Integrations/src/main/java/io/deephaven/integrations/python/PythonDeephavenSession.java
  python-engine-test/build.gradle
  python-engine-test/gradle.properties
  python-engine-test/src/test/build.gradle.template
  python-engine-test/src/test/java/io/deephaven/engine/table/impl/select/PythonMatchFilterTest.java
  python-engine-test/src/test/java/io/deephaven/engine/table/impl/select/TestConditionFilter.java
  python-engine-test/src/test/java/io/deephaven/engine/util/PickledResult.java
  python-engine-test/src/test/java/io/deephaven/engine/util/TestWorkerPythonEnvironment.java
  python-engine-test/src/test/java/io/deephaven/engine/util/WorkerPythonEnvironment.java
  settings.gradle
Labels: clean up, test, NoDocumentationNeeded, NoReleaseNotesNeeded

#4963 Disable Parallel Where for ConditionFilter
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/ConditionFilter.java
Labels: bug, core, NoDocumentationNeeded, ReleaseNotesNeeded

#4965 Move test generation code into README
  extensions/parquet/table/README.md
  extensions/parquet/table/src/test/e0.py
  extensions/parquet/table/src/test/e0.requirements.txt
  extensions/parquet/table/src/test/e1.py
  extensions/parquet/table/src/test/e1.requirements.txt
  extensions/parquet/table/src/test/e2.py
  extensions/parquet/table/src/test/e2.requirements.txt
Labels: clean up, security, NoDocumentationNeeded, NoReleaseNotesNeeded

#4962 Rework server tests to avoid using test sources from other projects
  server/build.gradle
  server/jetty/build.gradle
  server/netty/build.gradle
  server/test/build.gradle
  server/test/src/main/java/io/deephaven/server/runner/ExecutionContextUnitTestModule.java
Labels: test, NoDocumentationNeeded, NoReleaseNotesNeeded

#4968 Address dependency and liveness issues in KafkaTools.StreamPartitionedTable
  engine/table/src/main/java/io/deephaven/engine/table/impl/SourcePartitionedTable.java
  engine/table/src/main/java/io/deephaven/stream/StreamToBlinkTableAdapter.java
  engine/updategraph/src/main/java/io/deephaven/engine/updategraph/UpdateSourceCombiner.java
  extensions/kafka/src/main/java/io/deephaven/kafka/KafkaTools.java
Labels: bug, query engine, core, kafka, NoDocumentationNeeded, partitioned_tables, ReleaseNotesNeeded, point_release_candidate

#4966 Add dictionary (mapping) as a valid argument for new_table()
  py/server/deephaven/table_factory.py
  py/server/tests/test_table_factory.py
Labels: DocumentationNeeded, python-server-side, ReleaseNotesNeeded

#4979 Include column name in errors when creating InputColumn
  py/server/deephaven/column.py
Labels: NoDocumentationNeeded, python-server-side, NoReleaseNotesNeeded

#4980 UpdateGraph: Log Dependency Information On Failure to Proceed
  engine/table/src/main/java/io/deephaven/engine/updategraph/impl/BaseUpdateGraph.java
Labels: core, NoDocumentationNeeded, NoReleaseNotesNeeded

#4976 OperationInitializer usage bug fix and associated cleanups
  engine/context/src/main/java/io/deephaven/engine/context/ExecutionContext.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/AbstractFilterExecution.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/InitialFilterExecution.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/WhereListener.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/partitioned/PartitionedTableImpl.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/rangejoin/RangeJoinOperation.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/UpdateBy.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/OperationInitializerJobScheduler.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/UpdateGraphJobScheduler.java
  engine/table/src/main/java/io/deephaven/engine/updategraph/impl/PeriodicUpdateGraph.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableWhereTest.java
  server/src/main/java/io/deephaven/server/runner/DeephavenApiServer.java
Labels: bug, query engine, core, NoDocumentationNeeded, ReleaseNotesNeeded

#4912 fix: Add BigInteger and BigDecimal types to MatchFilter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/MatchFilter.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/select/WhereFilterFactoryTest.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4990 Go Client: Update code to match changes in TimeTableRequest, and reenable CI
  go/build.gradle
  go/internal/proto/application/application.pb.go
  go/internal/proto/application/application_grpc.pb.go
  go/internal/proto/config/config.pb.go
  go/internal/proto/config/config_grpc.pb.go
  go/internal/proto/console/console.pb.go
  go/internal/proto/console/console_grpc.pb.go
  go/internal/proto/hierarchicaltable/hierarchicaltable.pb.go
  go/internal/proto/hierarchicaltable/hierarchicaltable_grpc.pb.go
  go/internal/proto/inputtable/inputtable.pb.go
  go/internal/proto/inputtable/inputtable_grpc.pb.go
  go/internal/proto/object/object.pb.go
  go/internal/proto/object/object_grpc.pb.go
  go/internal/proto/partitionedtable/partitionedtable.pb.go
  go/internal/proto/partitionedtable/partitionedtable_grpc.pb.go
  go/internal/proto/session/session.pb.go
  go/internal/proto/session/session_grpc.pb.go
  go/internal/proto/storage/storage.pb.go
  go/internal/proto/storage/storage_grpc.pb.go
  go/internal/proto/table/table.pb.go
  go/internal/proto/table/table_grpc.pb.go
  go/internal/proto/ticket/ticket.pb.go
  go/pkg/client/query.go
  go/pkg/client/table_stub.go
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4974 `HashedRunFinder` run-finding improvements
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/HashedRunFinder.java
Labels: query engine, core, NoDocumentationNeeded, ReleaseNotesNeeded
