Repository deephaven/deephaven-core, pull requests merged in 2024-06, with the labels that each got.

#5555 fix: Expose layoutHints in JS API for TreeTable
  web/client-api/src/main/java/io/deephaven/web/client/api/tree/JsTreeTable.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5532 StorageService paths should be treated as opaque strings, part 1
  cpp-client/deephaven/dhclient/proto/deephaven/proto/storage.pb.cc
  cpp-client/deephaven/dhclient/proto/deephaven/proto/storage.pb.h
  go/internal/proto/storage/storage.pb.go
  props/configs/src/main/resources/dh-defaults.prop
  props/test-configs/src/main/resources/dh-tests.prop
  proto/proto-backplane-grpc/src/main/proto/deephaven/proto/storage.proto
  py/client/pydeephaven/proto/storage_pb2.py
  server/src/main/java/io/deephaven/server/notebook/FilesystemStorageServiceGrpcImpl.java
  web/client-api/src/main/java/io/deephaven/web/client/api/storage/JsItemDetails.java
  web/client-api/src/main/java/io/deephaven/web/client/api/storage/JsStorageService.java
  web/client-api/src/test/java/io/deephaven/web/ClientIntegrationTestSuite.java
  web/client-api/src/test/java/io/deephaven/web/client/api/AbstractAsyncGwtTestCase.java
  web/client-api/src/test/java/io/deephaven/web/client/api/storage/JsStorageServiceTestGwt.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/storage_pb/ListItemsResponse.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#5559 Generate ToChar/Short/ByteFunction interfaces and use in chunk apis
  engine/primitive/src/main/java/io/deephaven/engine/primitive/function/ToByteFunction.java
  engine/primitive/src/main/java/io/deephaven/engine/primitive/function/ToCharFunction.java
  engine/primitive/src/main/java/io/deephaven/engine/primitive/function/ToFloatFunction.java
  engine/primitive/src/main/java/io/deephaven/engine/primitive/function/ToShortFunction.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/ByteChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/CharChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/DoubleChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/FloatChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/IntChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/LongChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/ShortChunkInputStreamGenerator.java
  replication/static/src/main/java/io/deephaven/replicators/ReplicateBarrageUtils.java
  replication/static/src/main/java/io/deephaven/replicators/ReplicatePrimitiveInterfaces.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5524 fix!: `wavg()` and `wsum()` `Numeric` functions return `null` when provided a vector containing only `null` values
  engine/function/src/templates/Numeric.ftl
  engine/function/src/templates/TestNumeric.ftl
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/rollingwavg/BasePrimitiveRollingWAvgOperator.java
Labels: bug, query engine, NoDocumentationNeeded, breaking, ReleaseNotesNeeded

#5562 Fix names of type annotations not matching between definition and use.
  py/client/pydeephaven/session.py
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5577 Address initial lastNotificationStep issue for TimeTable and ReplayTableBase. Also correct TimeTable satisfaction testing.
  engine/table/src/main/java/io/deephaven/engine/table/impl/TimeTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/replay/ReplayTableBase.java
  engine/table/src/test/java/io/deephaven/engine/util/TimeTableTest.java
Labels: bug, query engine, core, NoDocumentationNeeded, ReleaseNotesNeeded

#5277 Initial commit of Iceberg integration.
  buildSrc/src/main/groovy/Classpaths.groovy
  extensions/iceberg/build.gradle
  extensions/iceberg/gradle.properties
  extensions/iceberg/s3/build.gradle
  extensions/iceberg/s3/gradle.properties
  extensions/iceberg/s3/src/main/java/io/deephaven/iceberg/util/IcebergToolsS3.java
  extensions/iceberg/s3/src/test/java/io/deephaven/iceberg/util/IcebergLocalStackTest.java
  extensions/iceberg/s3/src/test/java/io/deephaven/iceberg/util/IcebergMinIOTest.java
  extensions/iceberg/s3/src/test/java/io/deephaven/iceberg/util/IcebergToolsTest.java
  extensions/iceberg/s3/src/test/resources/warehouse/sales/sales_multi/data/00000-3-57e22ac8-7e7d-4830-aedb-14dab6fabdd6-0-00001.parquet
  extensions/iceberg/s3/src/test/resources/warehouse/sales/sales_multi/data/00000-4-3aacc74b-7f10-4e08-89ae-f1b1b578ce63-0-00001.parquet
  extensions/iceberg/s3/src/test/resources/warehouse/sales/sales_multi/data/00000-5-47debf3c-b256-4a04-9248-d7c69bec4881-0-00001.parquet
  extensions/iceberg/s3/src/test/resources/warehouse/sales/sales_multi/data/00000-6-7860a7c9-b3cb-4b2a-a69b-0f1e5c068512-0-00001.parquet
  extensions/iceberg/s3/src/test/resources/warehouse/sales/sales_multi/metadata/00000-8bdf65c1-a414-468b-b7b2-78558b2e8c1f.metadata.json
  extensions/iceberg/s3/src/test/resources/warehouse/sales/sales_multi/metadata/00001-30972e0f-9c8a-4fa9-911d-e356b2b04061.metadata.json
  extensions/iceberg/s3/src/test/resources/warehouse/sales/sales_multi/metadata/00002-559f7323-a010-4afe-8461-f5261787aae9.metadata.json
  extensions/iceberg/s3/src/test/resources/warehouse/sales/sales_multi/metadata/00003-366e4cb2-48c8-4f6d-bd6b-9b452de74dc3.metadata.json
  extensions/iceberg/s3/src/test/resources/warehouse/sales/sales_multi/metadata/02f91282-fecb-4479-bd3b-20a8a3aaa795-m0.avro
  extensions/iceberg/s3/src/test/resources/warehouse/sales/sales_multi/metadata/51be90a2-7294-4ebb-8eee-20d512fff8b0-m0.avro
  extensions/iceberg/s3/src/test/resources/warehouse/sales/sales_multi/metadata/77bfad1c-123c-452c-814d-298a1483a99f-m0.avro
  extensions/iceberg/s3/src/test/resources/warehouse/sales/sales_multi/metadata/a61cde47-0ced-4b74-b91a-9e32dd59b212-m0.avro
  extensions/iceberg/s3/src/test/resources/warehouse/sales/sales_multi/metadata/snap-1792185872197984875-1-51be90a2-7294-4ebb-8eee-20d512fff8b0.avro
  extensions/iceberg/s3/src/test/resources/warehouse/sales/sales_multi/metadata/snap-2001582482032951248-1-a61cde47-0ced-4b74-b91a-9e32dd59b212.avro
  extensions/iceberg/s3/src/test/resources/warehouse/sales/sales_multi/metadata/snap-3247344357341484163-1-77bfad1c-123c-452c-814d-298a1483a99f.avro
  extensions/iceberg/s3/src/test/resources/warehouse/sales/sales_multi/metadata/snap-8325605756612719366-1-02f91282-fecb-4479-bd3b-20a8a3aaa795.avro
  extensions/iceberg/s3/src/test/resources/warehouse/sales/sales_partitioned/data/year=2022/month=11/00000-8-981b110e-f66f-4474-a2a5-ad5e580e8f54-0-00001.parquet
  extensions/iceberg/s3/src/test/resources/warehouse/sales/sales_partitioned/data/year=2022/month=12/00001-9-981b110e-f66f-4474-a2a5-ad5e580e8f54-0-00001.parquet
  extensions/iceberg/s3/src/test/resources/warehouse/sales/sales_partitioned/metadata/00000-9635bc47-14fb-4a05-b8af-2c9f5986dfe6.metadata.json
  extensions/iceberg/s3/src/test/resources/warehouse/sales/sales_partitioned/metadata/4c305b6c-008f-407a-8e3b-ea1187f6421e-m0.avro
  extensions/iceberg/s3/src/test/resources/warehouse/sales/sales_partitioned/metadata/snap-5230665555732911945-1-4c305b6c-008f-407a-8e3b-ea1187f6421e.avro
  extensions/iceberg/s3/src/test/resources/warehouse/sales/sales_single/data/00000-2-1b3d5352-57ce-4968-b83d-30b13e1e7151-0-00001.parquet
  extensions/iceberg/s3/src/test/resources/warehouse/sales/sales_single/metadata/00000-3a7beb71-ae4e-42dd-ab04-884f6fd52372.metadata.json
  extensions/iceberg/s3/src/test/resources/warehouse/sales/sales_single/metadata/3395af41-65d8-41f0-8674-13624d6129c6-m0.avro
  extensions/iceberg/s3/src/test/resources/warehouse/sales/sales_single/metadata/snap-5481576066981634597-1-3395af41-65d8-41f0-8674-13624d6129c6.avro
  extensions/iceberg/s3/src/test/resources/warehouse/sample/all_types/ac528ac1-dea2-472b-b72b-48c4fdccc8bd.parquet
  extensions/iceberg/s3/src/test/resources/warehouse/sample/all_types/metadata/00000-bbb283f2-4659-434a-b422-227b8b15dfb9.metadata.json
  extensions/iceberg/s3/src/test/resources/warehouse/sample/all_types/metadata/00001-15b8eb1c-5cf6-4266-9f0c-5ae723cd77ba.metadata.json
  extensions/iceberg/s3/src/test/resources/warehouse/sample/all_types/metadata/388d67e5-5760-40c1-a460-c8c4ee5b8629-m0.avro
  extensions/iceberg/s3/src/test/resources/warehouse/sample/all_types/metadata/snap-6186754175552482648-1-388d67e5-5760-40c1-a460-c8c4ee5b8629.avro
  extensions/iceberg/src/main/java/io/deephaven/iceberg/layout/IcebergBaseLayout.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/layout/IcebergFlatLayout.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/layout/IcebergKeyValuePartitionedLayout.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/location/IcebergTableLocationFactory.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/location/IcebergTableLocationKey.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/location/IcebergTableParquetLocationKey.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/IcebergCatalogAdapter.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/IcebergInstructions.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/IcebergTools.java
  extensions/iceberg/src/test/java/io/deephaven/iceberg/TestCatalog/IcebergTestCatalog.java
  extensions/iceberg/src/test/java/io/deephaven/iceberg/TestCatalog/IcebergTestFileIO.java
  extensions/iceberg/src/test/java/io/deephaven/iceberg/TestCatalog/IcebergTestTable.java
  extensions/parquet/table/build.gradle
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/ParquetInstructions.java
  extensions/s3/build.gradle
  py/embedded-server/java-runtime/build.gradle
  server/build.gradle
  server/jetty-app-custom/build.gradle
  server/jetty-app/build.gradle
  server/netty-app/build.gradle
  settings.gradle
Labels: DocumentationNeeded, ReleaseNotesNeeded

#5578 Fix SourceTable coalesce bug when indexed columns are dropped
  engine/table/src/main/java/io/deephaven/engine/table/impl/dataindex/TableBackedDataIndex.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/MergedDataIndex.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/PartitioningColumnDataIndex.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/RegionedColumnSourceManager.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/locations/impl/TestSourceTableDataIndexes.java
Labels: bug, query engine, core, NoDocumentationNeeded, ReleaseNotesNeeded

#5510 [Breaking] Deleted deprecated parquet read/write APIs
  BenchmarkSupport/src/main/java/io/deephaven/benchmarking/runner/TableBenchmarkState.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/PartitionedTableTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableAggregationTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableNaturalJoinTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableSortTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestAggregatedSelect.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestCodecColumns.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestMapCodecColumns.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestSelectPreserveGrouping.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/locations/impl/TestSourceTableDataIndexes.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/sources/regioned/TestChunkedRegionedOperations.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/sources/regioned/TestObjectVectorUngroup.java
  extensions/parquet/benchmark/src/benchmark/java/io/deephaven/benchmark/parquet/table/TableWriteBenchmark.java
  extensions/parquet/table/src/brotliTest/java/io/deephaven/parquet/table/BrotliParquetTableReadWriteTest.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/ParquetTools.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/ParquetTableReadWriteTest.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/TestParquetIndexing.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/TestParquetTools.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/TestSymbolTableSource.java
  py/server/deephaven/parquet.py
  py/server/tests/test_parquet.py
Labels: parquet, NoDocumentationNeeded, release blocker, breaking, NoReleaseNotesNeeded

#5568 Upgrade aircompressor from v0.25 to v0.27
  extensions/parquet/compression/build.gradle
Labels: bug, parquet, NoDocumentationNeeded, ReleaseNotesNeeded

#5552 Cleanup to BarrageStreamGenerator and its related classes in antipation of porting to JS
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/BarrageStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/BarrageStreamGeneratorImpl.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/ChunkListInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/ConsecutiveDrainableStreams.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/DrainableByteArrayInputStream.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/BarrageUtil.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/TableToArrowConverter.java
  extensions/barrage/src/test/java/io/deephaven/extensions/barrage/BarrageStreamGeneratorTest.java
  server/src/main/java/io/deephaven/server/arrow/ArrowFlightUtil.java
  server/src/main/java/io/deephaven/server/arrow/ArrowModule.java
  server/src/main/java/io/deephaven/server/arrow/FlightServiceGrpcImpl.java
  server/src/main/java/io/deephaven/server/barrage/BarrageMessageProducer.java
  server/src/main/java/io/deephaven/server/hierarchicaltable/HierarchicalTableViewSubscription.java
  server/src/test/java/io/deephaven/server/barrage/BarrageBlinkTableTest.java
  server/src/test/java/io/deephaven/server/barrage/BarrageMessageRoundTripTest.java
Labels: barrage, NoDocumentationNeeded, NoReleaseNotesNeeded

#5580 Remove dtypes.int_/float_/int_array/float_array to eliminate confusion
  py/server/deephaven/csv.py
  py/server/deephaven/dtypes.py
  py/server/deephaven/filters.py
  py/server/tests/test_column.py
  py/server/tests/test_csv.py
  py/server/tests/test_dtypes.py
  py/server/tests/test_kafka_consumer.py
  py/server/tests/test_udf_scalar_args.py
Labels: python, DocumentationNeeded, python-server-side, breaking, ReleaseNotesNeeded

#5588 BaseArrayBackedInputTable user safety fixes
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/BaseArrayBackedInputTable.java
Labels: query engine, core, NoDocumentationNeeded, ReleaseNotesNeeded

#5540 Address missing DateTimeUtils functionality for LocalDateTime
  engine/time/src/main/java/io/deephaven/time/DateTimeUtils.java
  engine/time/src/test/java/io/deephaven/time/TestDateTimeUtils.java
Labels: core, NoDocumentationNeeded, ReleaseNotesNeeded

#5576 Update to GWT 2.11, clean up old gradle wiring
  buildSrc/src/main/groovy/Classpaths.groovy
  buildSrc/src/main/groovy/GwtTools.groovy
  gradle/web-client.gradle
  gradle/web-common.gradle
  open-api/lang-parser/lang-parser.gradle
  open-api/lang-tools/lang-tools.gradle
  open-api/shared-fu/shared-fu.gradle
  web/client-api/client-api.gradle
  web/client-api/src/main/java/io/deephaven/web/client/api/CoreClient.java
  web/client-api/src/main/java/io/deephaven/web/client/api/HasEventHandling.java
  web/client-api/src/main/java/io/deephaven/web/client/api/JsPartitionedTable.java
  web/client-api/src/main/java/io/deephaven/web/client/api/JsTable.java
  web/client-api/src/main/java/io/deephaven/web/client/api/JsTotalsTableConfig.java
  web/client-api/src/main/java/io/deephaven/web/client/api/WorkerConnection.java
  web/client-api/src/main/java/io/deephaven/web/client/api/barrage/stream/BiDiStream.java
  web/client-api/src/main/java/io/deephaven/web/client/api/barrage/stream/HandshakeStreamFactory.java
  web/client-api/src/main/java/io/deephaven/web/client/api/storage/JsStorageService.java
  web/client-api/src/main/java/io/deephaven/web/client/api/tree/JsRollupConfig.java
  web/client-api/src/main/java/io/deephaven/web/client/api/tree/JsTreeTable.java
  web/client-api/src/main/java/io/deephaven/web/client/api/widget/JsWidget.java
  web/client-api/src/main/java/io/deephaven/web/client/api/widget/calendar/JsBusinessCalendar.java
  web/client-api/src/main/java/io/deephaven/web/client/api/widget/calendar/JsHoliday.java
  web/client-api/src/main/java/io/deephaven/web/client/api/widget/plot/ChartData.java
  web/client-api/src/main/java/io/deephaven/web/client/api/widget/plot/FigureSubscription.java
  web/client-api/src/main/java/io/deephaven/web/client/api/widget/plot/JsChartDescriptor.java
  web/client-api/src/main/java/io/deephaven/web/client/api/widget/plot/JsFigureDescriptor.java
  web/client-api/src/main/java/io/deephaven/web/client/api/widget/plot/JsFigureFactory.java
  web/client-api/src/main/java/io/deephaven/web/client/api/widget/plot/JsMultiSeries.java
  web/client-api/src/main/java/io/deephaven/web/client/api/widget/plot/JsSeriesDescriptor.java
  web/client-api/src/main/java/io/deephaven/web/client/api/widget/plot/OneClick.java
  web/client-api/src/main/java/io/deephaven/web/client/fu/JsItr.java
  web/client-api/src/main/java/io/deephaven/web/client/ide/IdeSession.java
  web/client-api/src/test/java/io/deephaven/web/client/api/AbstractAsyncGwtTestCase.java
  web/client-api/src/test/java/io/deephaven/web/client/api/TableManipulationTestGwt.java
  web/client-backplane/client-backplane.gradle
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/table_pb_service/TableServiceClient.java
  web/shared-beans/shared-beans.gradle
Labels: build, NoDocumentationNeeded, NoReleaseNotesNeeded

#5586 `table_definition` will be optional for parquet `batch_write`
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/ParquetTools.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/ParquetTableReadWriteTest.java
  py/server/deephaven/parquet.py
  py/server/tests/test_parquet.py
Labels: feature request, parquet, NoDocumentationNeeded, ReleaseNotesNeeded

#5593 Adds docker registry projects for localstack and minio
  Integrations/build.gradle
  R/build.gradle
  buildSrc/src/main/groovy/Docker.groovy
  cpp-client/build.gradle
  docker/registry/localstack/build.gradle
  docker/registry/localstack/gradle.properties
  docker/registry/minio/build.gradle
  docker/registry/minio/gradle.properties
  docker/runtime-base/build.gradle
  docker/server-jetty/build.gradle
  docker/server/build.gradle
  docker/web-plugin-packager/build.gradle
  extensions/iceberg/s3/build.gradle
  extensions/iceberg/s3/gradle.properties
  extensions/parquet/table/build.gradle
  extensions/parquet/table/gradle.properties
  extensions/s3/build.gradle
  extensions/s3/gradle.properties
  extensions/s3/src/test/java/io/deephaven/extensions/s3/testlib/SingletonContainers.java
  go/build.gradle
  proto/proto-backplane-grpc/build.gradle
  proto/raw-js-openapi/build.gradle
  py/client-ticking/build.gradle
  py/client/build.gradle
  py/jpy-integration/build.gradle
  sphinx/sphinx.gradle
  web/client-api/client-api.gradle
  web/client-api/types/build.gradle
  web/client-ui/client-ui.gradle
Labels: test, NoDocumentationNeeded, NoReleaseNotesNeeded

#5599 Fix an issue with boxed type arg matching and disable np scalar warnings for numba
  engine/table/src/main/java/io/deephaven/engine/util/PyCallableWrapperJpyImpl.java
  py/server/deephaven/_udf.py
  py/server/tests/test_numba_guvectorize.py
  py/server/tests/test_numba_vectorized_column.py
  py/server/tests/test_udf_scalar_args.py
Labels: NoDocumentationNeeded, python-server-side, NoReleaseNotesNeeded

#5602 Fix csv.py parser mappings
  py/server/deephaven/csv.py
  py/server/tests/data/primitive_types.csv
  py/server/tests/test_csv.py
Labels: NoDocumentationNeeded, csv, ReleaseNotesNeeded

#5603 Make `region` optional for S3 instructions
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3AsyncClientFactory.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3Instructions.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3SeekableChannelProviderPlugin.java
  extensions/s3/src/test/java/io/deephaven/extensions/s3/S3InstructionsTest.java
  py/server/deephaven/experimental/s3.py
  py/server/tests/test_parquet.py
Labels: parquet, DocumentationNeeded, ReleaseNotesNeeded, s3

#5600 fix: Modify getKeyColumns method for JsInputTable
  web/client-api/src/main/java/io/deephaven/web/client/api/input/JsInputTable.java
  web/client-api/src/test/java/io/deephaven/web/ClientIntegrationTestSuite.java
  web/client-api/src/test/java/io/deephaven/web/client/api/InputTableTestGwt.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5604 CSV writer improvements
  extensions/csv/src/main/java/io/deephaven/csv/CsvTools.java
  extensions/csv/src/test/java/io/deephaven/csv/TestCsvTools.java
Labels: core, NoDocumentationNeeded, csv, ReleaseNotesNeeded

#5612 fix: Correctly pad zeroes for subsecond datetime formats
  web/client-api/src/main/java/io/deephaven/web/client/api/i18n/JsDateTimeFormat.java
  web/client-api/src/test/java/io/deephaven/web/client/api/i18n/JsDateTimeFormatTestGwt.java
Labels: jsapi, NoDocumentationNeeded, ReleaseNotesNeeded

#5616 fix: JS InputTable test failure and race
  web/client-api/src/test/java/io/deephaven/web/client/api/InputTableTestGwt.java
Labels: jsapi, test, NoDocumentationNeeded, NoReleaseNotesNeeded

#5597 Add instructions for patching old releases
  RELEASE.md
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5611 Improvements to buffered reading for parquet
  Util/channel/src/main/java/io/deephaven/util/channel/CachedChannelProvider.java
  Util/channel/src/main/java/io/deephaven/util/channel/LocalFSChannelProvider.java
  Util/channel/src/main/java/io/deephaven/util/channel/SeekableChannelsProvider.java
  Util/channel/src/test/java/io/deephaven/util/channel/CachedChannelProviderTest.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/ColumnChunkReaderImpl.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/ColumnPageReaderImpl.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/OffsetIndexReaderImpl.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/ParquetFileReader.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/ParquetTableReadWriteTest.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3SeekableChannelProvider.java
  extensions/trackedfile/src/main/java/io/deephaven/extensions/trackedfile/TrackedSeekableChannelsProvider.java
Labels: parquet, NoDocumentationNeeded, ReleaseNotesNeeded

#5621 Fix some issues in the test code found by numpy 2.0.0
  py/client/tests/test_table.py
  py/server/tests/test_numpy.py
  py/server/tests/test_pandas.py
Labels: python, NoDocumentationNeeded, ReleaseNotesNeeded

#5626 ci: Trigger actions on pull requests to rc/v* branches
  .github/workflows/check-ci.yml
  .github/workflows/create-docs-issues.yml
  .github/workflows/docs-ci.yml
  .github/workflows/label-check-ci.yml
  .github/workflows/publish-ci.yml
  .github/workflows/quick-ci.yml
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5623 Bump server base images for numpy 2
  docker/registry/server-base/gradle.properties
  docker/registry/slim-base/gradle.properties
  docker/server-jetty/src/main/server-jetty/requirements.txt
  docker/server/src/main/server-netty/requirements.txt
  py/server/tests/test_dbc.py
Labels: test, NoDocumentationNeeded, NoReleaseNotesNeeded

#5539 Add defensive bearer token rotation for java client
  java-client/session/src/main/java/io/deephaven/client/impl/BearerHandler.java
Labels: NoDocumentationNeeded, java-client, NoReleaseNotesNeeded

#5630 ci: Trigger actions on pull requests to rc/v* branches (#5626)
  .github/workflows/check-ci.yml
  .github/workflows/create-docs-issues.yml
  .github/workflows/docs-ci.yml
  .github/workflows/label-check-ci.yml
  .github/workflows/publish-ci.yml
  .github/workflows/quick-ci.yml
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5509 feat: Added query library functions to overload Period and Duration arithmetic
  engine/time/src/main/java/io/deephaven/time/DateTimeUtils.java
  engine/time/src/test/java/io/deephaven/time/TestDateTimeUtils.java
Labels: query engine, DocumentationNeeded, ReleaseNotesNeeded

#5628 fix: Remove table attribute size cutoff limit
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/BarrageUtil.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5618 fix: signal.pause is not available on Windows
  py/embedded-server/deephaven_server/cli.py
  py/embedded-server/java-runtime/src/main/java/io/deephaven/python/server/EmbeddedServer.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5571 Add a listener that only fires when all dependencies are satisfied
  Integrations/src/main/java/io/deephaven/integrations/python/PythonReplayListenerAdapter.java
  py/server/deephaven/table_listener.py
  py/server/tests/test_table_listener.py
Labels: DocumentationNeeded, python-server-side, ReleaseNotesNeeded

#5606 fix!: statistical functions should return `null` when provided a vector of only `null` values
  engine/function/src/templates/Numeric.ftl
  engine/function/src/templates/TestNumeric.ftl
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/ByteChunkedAvgOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/ByteChunkedVarOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/CharChunkedAvgOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/CharChunkedVarOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/DoubleChunkedAvgOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/DoubleChunkedReAvgOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/DoubleChunkedVarOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/FloatChunkedAvgOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/FloatChunkedReAvgOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/FloatChunkedReVarOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/FloatChunkedVarOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/IntChunkedAvgOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/IntChunkedVarOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/LongChunkedAvgOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/LongChunkedVarOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/ShortChunkedAvgOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/ShortChunkedVarOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/rollingavg/ByteRollingAvgOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/rollingavg/CharRollingAvgOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/rollingavg/DoubleRollingAvgOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/rollingavg/FloatRollingAvgOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/rollingavg/IntRollingAvgOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/rollingavg/LongRollingAvgOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/rollingavg/ShortRollingAvgOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/rollingstd/ByteRollingStdOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/rollingstd/CharRollingStdOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/rollingstd/DoubleRollingStdOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/rollingstd/FloatRollingStdOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/rollingstd/IntRollingStdOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/rollingstd/LongRollingStdOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/rollingstd/ShortRollingStdOperator.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableAggregationTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableAggregationTestFormulaStaticMethods.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestRollingAvg.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestRollingCount.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestRollingFormula.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestRollingGroup.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestRollingMinMax.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestRollingProduct.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestRollingStd.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestRollingSum.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestRollingWAvg.java
Labels: DocumentationNeeded, breaking, ReleaseNotesNeeded, devrel-watch

#5624 fix: Update web version to 0.78.2
  web/client-ui/Dockerfile
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5641 Remove latest symlink for docs-ci-v2
  .github/workflows/docs-ci-v2.yml
Labels: ci, NoDocumentationNeeded, NoReleaseNotesNeeded

#5638 Optimizations for BigDecimal and BigInteger parquet reads
  extensions/parquet/base/build.gradle
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/BigDecimalParquetBytesCodec.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/BigIntegerParquetBytesCodec.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/PageMaterializer.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/BigDecimalFromBytesMaterializer.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/BigDecimalFromIntMaterializer.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/BigDecimalFromLongMaterializer.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/BigIntegerMaterializer.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/BlobMaterializer.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/BoolMaterializer.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/ByteMaterializer.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/CharMaterializer.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/DoubleMaterializer.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/FloatMaterializer.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/InstantFromInt96Materializer.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/InstantNanosFromMicrosMaterializer.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/InstantNanosFromMillisMaterializer.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/IntMaterializer.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/LocalDateMaterializer.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/LocalDateTimeFromMicrosMaterializer.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/LocalDateTimeFromMillisMaterializer.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/LocalDateTimeFromNanosMaterializer.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/LocalDateTimeMaterializerBase.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/LocalTimeFromMicrosMaterializer.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/LocalTimeFromMillisMaterializer.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/LocalTimeFromNanosMaterializer.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/LongFromUnsignedIntMaterializer.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/LongMaterializer.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/LongMaterializerBase.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/ObjectMaterializerBase.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/ShortMaterializer.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/StringMaterializer.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/ParquetSchemaReader.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/TypeInfos.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/location/ParquetColumnLocation.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/pagestore/topage/ToBigDecimalBase.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/pagestore/topage/ToBigDecimalFromIntPage.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/pagestore/topage/ToBigDecimalFromLongPage.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/pagestore/topage/ToBigDecimalPage.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/pagestore/topage/ToBigIntegerPage.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/transfer/TransferObject.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/BigDecimalParquetBytesCodecTest.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/ParquetTableReadWriteTest.java
  extensions/parquet/table/src/test/resources/ReferenceDecimalLogicalType.parquet
  extensions/parquet/table/src/test/resources/ReferenceDecimalLogicalType2.parquet
  replication/static/src/main/java/io/deephaven/replicators/ReplicatePageMaterializers.java
  replication/static/src/main/java/io/deephaven/replicators/ReplicateToPage.java
Labels: parquet, NoDocumentationNeeded, ReleaseNotesNeeded

#5637 Allow extra headers in Barrage session creation
  py/server/deephaven/barrage.py
  py/server/tests/test_barrage.py
Labels: barrage, NoDocumentationNeeded, release blocker, python-client, NoReleaseNotesNeeded

#5633 ErrorTransformer: prevent NPE
  server/src/main/java/io/deephaven/server/appmode/ApplicationTicketResolver.java
  server/src/main/java/io/deephaven/server/console/ScopeTicketResolver.java
  server/src/main/java/io/deephaven/server/hierarchicaltable/HierarchicalTableServiceGrpcImpl.java
  server/src/main/java/io/deephaven/server/partitionedtable/PartitionedTableServiceGrpcImpl.java
  server/src/main/java/io/deephaven/server/session/ExportTicketResolver.java
  server/src/main/java/io/deephaven/server/session/SharedTicketResolver.java
  server/src/main/java/io/deephaven/server/session/TicketResolver.java
Labels: bug, core, NoDocumentationNeeded, release blocker, NoReleaseNotesNeeded

#5613 [BREAKING] Fix for OOM error when reading from S3
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3ChannelContext.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3Instructions.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3Request.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3RequestCache.java
  extensions/s3/src/test/java/io/deephaven/extensions/s3/S3InstructionsTest.java
  py/server/deephaven/experimental/s3.py
Labels: bug, parquet, NoDocumentationNeeded, breaking, ReleaseNotesNeeded, s3

#5652 Validate arg type for sort/partition_by
  py/server/deephaven/table.py
  py/server/tests/test_parquet.py
  py/server/tests/test_table.py
Labels: NoDocumentationNeeded, python-server-side, NoReleaseNotesNeeded

#5653 Fix getNextRowSequenceWithLength callsites that close
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/ChunkUtils.java
  engine/table/src/main/java/io/deephaven/engine/util/TickSuppressor.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5266 feat!: Remove deprecated Daylight Savings Time (DST) methods
  engine/time/src/main/java/io/deephaven/time/DateTimeUtils.java
Labels: query engine, NoDocumentationNeeded, release blocker, ReleaseNotesNeeded

#5590 feat: expose Iceberg features to python users
  buildSrc/src/main/groovy/Classpaths.groovy
  extensions/iceberg/s3/build.gradle
  extensions/iceberg/s3/src/main/java/io/deephaven/iceberg/util/IcebergToolsS3.java
  extensions/iceberg/s3/src/test/java/io/deephaven/iceberg/util/IcebergToolsTest.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/IcebergCatalogAdapter.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/IcebergInstructions.java
  py/server/deephaven/experimental/iceberg.py
  py/server/deephaven/jcompat.py
  py/server/deephaven/parquet.py
  py/server/deephaven/stream/table_publisher.py
  py/server/tests/test_iceberg.py
Labels: query engine, python, DocumentationNeeded, release blocker, python-server-side, ReleaseNotesNeeded

#5644 Change py-embedded-server from WARN to INFO logging
  py/embedded-server/java-runtime/src/main/resources/logback-minimal.xml
Labels: logging, NoDocumentationNeeded, ReleaseNotesNeeded

#5660 fix: correct weighted summation null handling behavior
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/LongChunkedWeightedSumOperator.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableAggregationTest.java
Labels: bug, NoDocumentationNeeded, NoReleaseNotesNeeded

#5662 fix: correct OOB test failures from mismatching Iceberg API table column names
  extensions/iceberg/s3/src/test/java/io/deephaven/iceberg/util/IcebergToolsTest.java
Labels: bug, NoDocumentationNeeded, NoReleaseNotesNeeded

#5664 Remove server dependency on extensions-iceberg
  server/build.gradle
Labels: NoDocumentationNeeded, release blocker, dependencies, NoReleaseNotesNeeded

#5663 fix: rename `iceberg:s3` sub-project to `iceberg-s3`.
  py/embedded-server/java-runtime/build.gradle
  server/jetty-app-custom/build.gradle
  server/jetty-app/build.gradle
  server/netty-app/build.gradle
  settings.gradle
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5659 fix: Only update the redir index on the first column
  web/client-api/src/main/java/io/deephaven/web/client/api/subscription/SubscriptionTableData.java
Labels: jsapi, plotting, NoDocumentationNeeded, ReleaseNotesNeeded

#5669 fix: Modify key table viewport to only include key columns
  web/client-api/src/main/java/io/deephaven/web/client/api/JsPartitionedTable.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5668 feat: reduce included dependencies for Iceberg implementation
  buildSrc/src/main/groovy/Classpaths.groovy
  extensions/iceberg/build.gradle
  extensions/kafka/build.gradle
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5682 C++ Client: End of Barrage stream should throw; reformat exception messages
  cpp-client/deephaven/dhclient/src/subscription/subscribe_thread.cc
  cpp-client/deephaven/dhcore/src/utility/utility.cc
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5684 C++ Client: fix WAvg, fix noexcept, optimize PercentileBy, fix comments
  cpp-client/deephaven/dhclient/include/private/deephaven/client/impl/table_handle_impl.h
  cpp-client/deephaven/dhclient/include/public/deephaven/client/client.h
  cpp-client/deephaven/dhclient/src/client.cc
  cpp-client/deephaven/dhclient/src/impl/table_handle_impl.cc
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5671 Instant Column gRPC Filters: Fix Range Quick Filters and use MatchFilter over ConditionFilter
  server/src/main/java/io/deephaven/server/table/ops/filter/FilterFactory.java
  server/src/main/java/io/deephaven/server/table/ops/filter/FilterPrinter.java
Labels: bug, web-client-ui, grpc, core, NoDocumentationNeeded, release blocker, NoReleaseNotesNeeded

#5685 C++ Client: support for interop, plus some interop test entry points
  cpp-client/deephaven/dhcore/CMakeLists.txt
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/interop/interop_util.h
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/interop/testapi/basic_interop_interactions.h
  cpp-client/deephaven/dhcore/src/interop/interop_util.cc
  cpp-client/deephaven/dhcore/src/interop/testapi/basic_interop_interactions.cc
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5687 C++ client: clean up some tests
  cpp-client/deephaven/tests/src/add_drop_test.cc
  cpp-client/deephaven/tests/src/attributes_test.cc
  cpp-client/deephaven/tests/src/join_test.cc
  cpp-client/deephaven/tests/src/sort_test.cc
  cpp-client/deephaven/tests/src/update_by_test.cc
  cpp-client/deephaven/tests/src/validation_test.cc
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5688 C++ Client: Small changes to support interop
  cpp-client/deephaven/dhclient/include/public/deephaven/client/update_by.h
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/clienttable/schema.h
  cpp-client/deephaven/dhcore/src/clienttable/schema.cc
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5686 Add javadoc and sources jar for shadow publishing
  buildSrc/src/main/groovy/io.deephaven.java-shadow-publishing-conventions.gradle
Labels: NoDocumentationNeeded, release blocker, NoReleaseNotesNeeded

#5689 Bump to 0.36.0-SNAPSHOT
  R/rdeephaven/DESCRIPTION
  gradle.properties
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5661 build: Bump to gradle 8.8
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: build, NoDocumentationNeeded, version-bump, NoReleaseNotesNeeded

#5691 chore: Add dependabot commit message prefix
  .github/dependabot.yml
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5695 feat(cppclient): provide entry points for C API
  cpp-client/deephaven/dhclient/CMakeLists.txt
  cpp-client/deephaven/dhclient/include/public/deephaven/client/interop/client_interop.h
  cpp-client/deephaven/dhclient/include/public/deephaven/client/interop/client_options_interop.h
  cpp-client/deephaven/dhclient/include/public/deephaven/client/interop/update_by_interop.h
  cpp-client/deephaven/dhclient/include/public/deephaven/client/utility/table_maker.h
  cpp-client/deephaven/dhclient/src/interop/client_interop.cc
  cpp-client/deephaven/dhclient/src/interop/client_options_interop.cc
  cpp-client/deephaven/dhclient/src/interop/update_by_interop.cc
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5696 test: Fix ArrayColumn Access WhereFilter Test
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableWhereTest.java
Labels: core, test, NoDocumentationNeeded, NoReleaseNotesNeeded

#5693 chore: Upgrade jedi to 0.19.1
  docker/registry/server-base/gradle.properties
  docker/registry/slim-base/gradle.properties
  docker/server-jetty/src/main/server-jetty/requirements.txt
  docker/server/src/main/server-netty/requirements.txt
  py/server/setup.py
Labels: NoDocumentationNeeded, ReleaseNotesNeeded
