Repository deephaven/deephaven-core, pull requests merged in 2024-07, with the labels that each got.

#5702 fix: correctly produce Kafka JSON nulls for int fields
  extensions/kafka/src/main/java/io/deephaven/kafka/publish/JsonKeyOrValueSerializer.java
Labels: bug, kafka, NoDocumentationNeeded, json, ReleaseNotesNeeded, point_release_candidate

#5705 fix(cppclient): Clarify a comment explaining why a test is disabled, …
  cpp-client/deephaven/tests/src/ungroup_test.cc
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5703 feat(csharpclient): First pass at a C# client
  csharp/.gitignore
  csharp/client/DeephavenClient/AggregateCombo.cs
  csharp/client/DeephavenClient/Aggregates.cs
  csharp/client/DeephavenClient/ArrowTable.cs
  csharp/client/DeephavenClient/Client.cs
  csharp/client/DeephavenClient/ClientOptions.cs
  csharp/client/DeephavenClient/ClientTable.cs
  csharp/client/DeephavenClient/DeephavenClient.csproj
  csharp/client/DeephavenClient/DeephavenClient.sln
  csharp/client/DeephavenClient/DhDateTime.cs
  csharp/client/DeephavenClient/DurationSpecifier.cs
  csharp/client/DeephavenClient/Interop/InteropSupport.cs
  csharp/client/DeephavenClient/Interop/TestApi/BasicInteropInteractions.cs
  csharp/client/DeephavenClient/SortPair.cs
  csharp/client/DeephavenClient/TableHandle.cs
  csharp/client/DeephavenClient/TableHandleManager.cs
  csharp/client/DeephavenClient/Ticking.cs
  csharp/client/DeephavenClient/TimePointSpecifier.cs
  csharp/client/DeephavenClient/UpdateBy.cs
  csharp/client/DeephavenClient/Utility/ColumnFactory.cs
  csharp/client/DeephavenClient/Utility/DeephavenConstants.cs
  csharp/client/DeephavenClient/Utility/Schema.cs
  csharp/client/DeephavenClient/Utility/TableMaker.cs
  csharp/client/DhClientTests/AddDropTest.cs
  csharp/client/DhClientTests/AggregatesTest.cs
  csharp/client/DhClientTests/BasicInteropInteractionsTest.cs
  csharp/client/DhClientTests/BasicTests.cs
  csharp/client/DhClientTests/CommonContextForTests.cs
  csharp/client/DhClientTests/DateTimeTest.cs
  csharp/client/DhClientTests/DhClientTests.csproj
  csharp/client/DhClientTests/DhClientTests.sln
  csharp/client/DhClientTests/DhClientTests.sln.DotSettings.user
  csharp/client/DhClientTests/FilterTest.cs
  csharp/client/DhClientTests/GlobalUsings.cs
  csharp/client/DhClientTests/HeadAndTailTest.cs
  csharp/client/DhClientTests/InputTableTest.cs
  csharp/client/DhClientTests/JoinTest.cs
  csharp/client/DhClientTests/LastByTest.cs
  csharp/client/DhClientTests/MergeTest.cs
  csharp/client/DhClientTests/ScriptTest.cs
  csharp/client/DhClientTests/SelectTest.cs
  csharp/client/DhClientTests/SortTest.cs
  csharp/client/DhClientTests/StringFilterTest.cs
  csharp/client/DhClientTests/TableHandleAttributesTest.cs
  csharp/client/DhClientTests/TableTest.cs
  csharp/client/DhClientTests/TestUtils.cs
  csharp/client/DhClientTests/TickingTest.cs
  csharp/client/DhClientTests/UngroupTest.cs
  csharp/client/DhClientTests/UpdateByTest.cs
  csharp/client/DhClientTests/ValidationTest.cs
  csharp/client/DhClientTests/ViewTest.cs
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5706 fix(cppclient): Remove extension from dhclient and dhcore for cross-platform compatibility
  csharp/client/DeephavenClient/Interop/InteropSupport.cs
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5645 fix: Expose base, "underlying" table for Partitioned Table Enhancements
  web/client-api/src/main/java/io/deephaven/web/client/api/JsPartitionedTable.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5715 ci: add gradle to dependabot
  .github/dependabot.yml
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5721 fix(cppclient): Update versions and change build type
  cpp-client/README.md
  cpp-client/deephaven/vcpkg-configuration.json
  cpp-client/deephaven/vcpkg.json
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5724 build: Remove java classpath conventions
  Base/build.gradle
  BenchmarkSupport/BenchmarkSupport.gradle
  ClientSupport/ClientSupport.gradle
  Configuration/build.gradle
  Generators/Generators.gradle
  IO/build.gradle
  Integrations/build.gradle
  ModelFarm/ModelFarm.gradle
  Numerics/Numerics.gradle
  Plot/Plot.gradle
  Util/Util.gradle
  Util/channel/build.gradle
  Util/function/build.gradle
  base-test-utils/build.gradle
  buildSrc/src/main/groovy/io.deephaven.java-classpath-conventions.gradle
  buildSrc/src/main/groovy/io.deephaven.java-common-conventions.gradle
  engine/api/build.gradle
  engine/context/build.gradle
  engine/function/build.gradle
  engine/primitive/build.gradle
  engine/rowset-test-utils/build.gradle
  engine/rowset/build.gradle
  engine/table/build.gradle
  engine/test-utils/build.gradle
  engine/time/build.gradle
  engine/tuple/build.gradle
  engine/updategraph/build.gradle
  engine/vector/build.gradle
  extensions/arrow/build.gradle
  extensions/barrage/build.gradle
  extensions/csv/build.gradle
  extensions/iceberg/build.gradle
  extensions/kafka/build.gradle
  extensions/parquet/base/build.gradle
  extensions/parquet/compression/build.gradle
  extensions/parquet/table/build.gradle
  extensions/protobuf/build.gradle
  extensions/s3/build.gradle
  extensions/source-support/build.gradle
  extensions/suanshu/build.gradle
  extensions/trackedfile/build.gradle
  gradle/libs.versions.toml
  java-client/barrage/build.gradle
  log-factory/build.gradle
  log-factory/sinks/log-to-logbuffer/build.gradle
  log-factory/sinks/logback-logbuffer/build.gradle
  log-factory/sinks/logback-print-stream-globals/build.gradle
  props/test-configs/build.gradle
  proto/proto-backplane-grpc/build.gradle
  py/jpy-integration/build.gradle
  replication/reflective/build.gradle
  replication/static/build.gradle
  replication/util/build.gradle
  server/build.gradle
  server/test-utils/build.gradle
  web/client-api/client-api.gradle
  web/shared-beans/shared-beans.gradle
Labels: build, NoDocumentationNeeded, NoReleaseNotesNeeded

#5729 fix: R CI docsite issue
  R/build.gradle
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5733 refactor: Remove unused java.awt checks in Require/Assert
  Base/src/main/java/io/deephaven/base/verify/Assert.java
  Base/src/main/java/io/deephaven/base/verify/Require.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5731 refactor: Compare final boxed/primitive types with equality
  Util/src/main/java/io/deephaven/util/type/TypeUtils.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5743 chore: Add assignees to dependabot PRs
  .github/dependabot.yml
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5750 Bump to 0.33.6-SNAPSHOT
  R/rdeephaven/DESCRIPTION
  gradle.properties
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5746 feat: Add auto-legalization for Iceberg Schema column names.
  extensions/iceberg/s3/src/test/java/io/deephaven/iceberg/util/IcebergToolsTest.java
  extensions/iceberg/s3/src/test/resources/warehouse/sales/sales_renamed/data/00000-4-62bcda08-a24a-4b17-a20a-e18edfea5b5a-0-00001.parquet
  extensions/iceberg/s3/src/test/resources/warehouse/sales/sales_renamed/metadata/00000-556b3c6d-3a0e-4912-916a-151f5d772a7b.metadata.json
  extensions/iceberg/s3/src/test/resources/warehouse/sales/sales_renamed/metadata/6154af6b-49cf-41eb-a340-ff60964e750d-m0.avro
  extensions/iceberg/s3/src/test/resources/warehouse/sales/sales_renamed/metadata/snap-1014870679100567484-1-6154af6b-49cf-41eb-a340-ff60964e750d.avro
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/IcebergCatalogAdapter.java
Labels: DocumentationNeeded, ReleaseNotesNeeded

#5595 feat: generator-based chunky Table data iteration
  Integrations/src/main/java/io/deephaven/integrations/python/PythonTableDataReader.java
  py/server/deephaven/_table_reader.py
  py/server/deephaven/table.py
  py/server/deephaven/table_listener.py
  py/server/tests/test_table_iterator.py
Labels: DocumentationNeeded, python-server-side, ReleaseNotesNeeded

#5747 refactor: Remove Math.nextUp call in QueryConstants
  engine/query-constants/build.gradle
  engine/query-constants/src/main/java/io/deephaven/util/QueryConstants.java
  engine/query-constants/src/test/java/io/deephaven/util/QueryConstantsTest.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#5757 chore: Bump calcite to 1.37.0
  gradle/libs.versions.toml
  sql/build.gradle
  sql/src/main/java/io/deephaven/sql/RexVisitorBase.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5725 build: Make it easier to manually run GWT tests from the IDE
  web/client-api/client-api.gradle
Labels: jsapi, test, NoDocumentationNeeded, NoReleaseNotesNeeded

#5755 fix(cpp-client): update vcpkg baseline to include fix for thrift 0.20.0 download hash
  cpp-client/deephaven/vcpkg-configuration.json
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5739 refactor!: Remove tracking of "culprit" from Require methods
  Base/src/main/java/io/deephaven/base/stats/Composite.java
  Base/src/main/java/io/deephaven/base/verify/Require.java
  Base/src/main/java/io/deephaven/base/verify/RequirementFailure.java
  Base/src/test/java/io/deephaven/base/TestLowGarbageArrayIntegerMap.java
  Base/src/test/java/io/deephaven/base/pool/TestThreadSafeLenientFixedSizePool.java
  DataStructures/src/main/java/io/deephaven/datastructures/util/CollectionUtil.java
  Util/src/main/java/io/deephaven/util/Utils.java
  Util/src/test/java/io/deephaven/util/pool/TestThreadSafeLenientFixedSizePool.java
Labels: NoDocumentationNeeded, breaking, ReleaseNotesNeeded

#5758 fix: For NPE when sorting dictionary-encoded null string columns
  engine/table/src/main/java/io/deephaven/engine/table/impl/SortHelpers.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/ColumnRegionChunkDictionary.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/ParquetTableReadWriteTest.java
  extensions/parquet/table/src/test/resources/ReferenceNullStringDictEncoded1.parquet
  extensions/parquet/table/src/test/resources/ReferenceNullStringDictEncoded2.parquet
Labels: bug, parquet, NoDocumentationNeeded, ReleaseNotesNeeded

#5730 refactor!: Remove gnu.trove from RowSet API
  engine/rowset/build.gradle
  engine/rowset/src/main/java/io/deephaven/engine/rowset/RowKeyRangeShiftCallback.java
  engine/rowset/src/main/java/io/deephaven/engine/rowset/RowSet.java
  engine/rowset/src/main/java/io/deephaven/engine/rowset/RowSetBuilderSequential.java
  engine/rowset/src/main/java/io/deephaven/engine/rowset/RowSetFactory.java
  engine/rowset/src/main/java/io/deephaven/engine/rowset/RowSetShiftCallback.java
  engine/rowset/src/main/java/io/deephaven/engine/rowset/RowSetShiftData.java
  engine/rowset/src/main/java/io/deephaven/engine/rowset/impl/WritableRowSetImpl.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/TableUpdateValidator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/ArrayBackedColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/BooleanArraySource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/ByteArraySource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/CharacterArraySource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/DoubleArraySource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/FloatArraySource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/IntegerArraySource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/LongArraySource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/NanosBasedTimeArraySource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/NanosBasedTimeSparseArraySource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/NullValueColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/ShortArraySource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/SingleValueColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/SparseArrayColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/immutable/ImmutableConstantByteSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/immutable/ImmutableConstantCharSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/immutable/ImmutableConstantDoubleSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/immutable/ImmutableConstantFloatSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/immutable/ImmutableConstantIntSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/immutable/ImmutableConstantLongSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/immutable/ImmutableConstantNanosBasedTimeSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/immutable/ImmutableConstantObjectSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/immutable/ImmutableConstantShortSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/ShiftData.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/util/RowSetShiftDataTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/util/ShiftDataTest.java
Labels: NoDocumentationNeeded, breaking, ReleaseNotesNeeded

#5749 fix: Remove table attribute size cutoff limit
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/BarrageUtil.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5712 feat: Modified parquet decompression from buffered to streaming operation
  IO/src/main/java/io/deephaven/io/streams/ByteBufferInputStream.java
  Util/channel/src/main/java/io/deephaven/util/channel/BaseSeekableChannelContext.java
  Util/channel/src/main/java/io/deephaven/util/channel/SeekableChannelContext.java
  Util/channel/src/main/java/io/deephaven/util/channel/SeekableChannelContextNull.java
  Util/channel/src/test/java/io/deephaven/util/channel/CachedChannelProviderTest.java
  engine/chunk/src/main/java/io/deephaven/chunk/sized/SizedBooleanChunk.java
  engine/chunk/src/main/java/io/deephaven/chunk/sized/SizedByteChunk.java
  engine/chunk/src/main/java/io/deephaven/chunk/sized/SizedCharChunk.java
  engine/chunk/src/main/java/io/deephaven/chunk/sized/SizedDoubleChunk.java
  engine/chunk/src/main/java/io/deephaven/chunk/sized/SizedFloatChunk.java
  engine/chunk/src/main/java/io/deephaven/chunk/sized/SizedIntChunk.java
  engine/chunk/src/main/java/io/deephaven/chunk/sized/SizedLongChunk.java
  engine/chunk/src/main/java/io/deephaven/chunk/sized/SizedObjectChunk.java
  engine/chunk/src/main/java/io/deephaven/chunk/sized/SizedShortChunk.java
  extensions/parquet/base/build.gradle
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/ColumnChunkReaderImpl.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/ColumnPageReaderImpl.java
  extensions/parquet/compression/build.gradle
  extensions/parquet/compression/src/main/java/io/deephaven/parquet/compress/CompressorAdapter.java
  extensions/parquet/compression/src/main/java/io/deephaven/parquet/compress/DecompressorHolder.java
  extensions/parquet/compression/src/main/java/io/deephaven/parquet/compress/DeephavenCompressorAdapterFactory.java
  extensions/parquet/compression/src/main/java/io/deephaven/parquet/compress/LZ4WithLZ4RawBackupCompressorAdapter.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/ParquetTableReadWriteTest.java
Labels: feature request, parquet, NoDocumentationNeeded, ReleaseNotesNeeded

#5766 fix(cpp-client): Make build instructions more explicit about server step.
  cpp-client/README.md
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5768 chore: Add SECURITY.md
  SECURITY.md
Labels: security, NoDocumentationNeeded, NoReleaseNotesNeeded

#5672 feat(api)!: Support merged listening on multiple tables
  Integrations/src/main/java/io/deephaven/integrations/python/PythonMergedListenerAdapter.java
  Integrations/src/main/java/io/deephaven/integrations/python/PythonUtils.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/MergedListener.java
  py/server/deephaven/table_listener.py
  py/server/tests/test_table_listener.py
  py/server/tests/test_udf_scalar_args.py
Labels: DocumentationNeeded, python-server-side, breaking, ReleaseNotesNeeded

#5779 fix: For failure in path to URI conversion on windows
  Base/src/main/java/io/deephaven/base/FileUtils.java
Labels: parquet, NoDocumentationNeeded, ReleaseNotesNeeded, point_release_candidate

#5784 chore: bump docker base images
  docker/registry/cpp-clients-multi-base/gradle.properties
  docker/registry/fedora/gradle.properties
  docker/registry/go/gradle.properties
  docker/registry/manylinux2014_x86_64/gradle.properties
  docker/registry/minio/gradle.properties
  docker/registry/protoc-base/gradle.properties
  docker/registry/python/gradle.properties
  docker/registry/server-base/gradle.properties
  docker/registry/slim-base/gradle.properties
  docker/server-jetty/src/main/server-jetty/requirements.txt
  docker/server/src/main/server-netty/requirements.txt
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5783 refactor: move partition kernel to test source set
  engine/table/src/test/java/io/deephaven/engine/table/impl/sort/partition/BytePartitionKernel.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/sort/partition/CharPartitionKernel.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/sort/partition/DoublePartitionKernel.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/sort/partition/FloatPartitionKernel.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/sort/partition/IntPartitionKernel.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/sort/partition/LongPartitionKernel.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/sort/partition/ObjectPartitionKernel.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/sort/partition/PartitionUtils.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/sort/partition/ShortPartitionKernel.java
  replication/static/src/main/java/io/deephaven/replicators/ReplicateSortKernel.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5789 perf: Add ForkJoinPool.commonPool()-based OperationInitializer for nested parallel DataIndex building
  engine/table/src/main/java/io/deephaven/engine/table/impl/ForkJoinPoolOperationInitializer.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/dataindex/TransformedDataIndex.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/MergedDataIndex.java
Labels: query engine, core, NoDocumentationNeeded, ReleaseNotesNeeded, point_release_candidate

#5792 fix(cpp-client): deephavenConfig.cmake provides transitive dependencies
  RELEASE.md
  cpp-client/build.gradle
  cpp-client/deephaven/CMakeLists.txt
  cpp-client/deephaven/cmake/deephavenConfig.cmake
  cpp-client/deephaven/dhclient/CMakeLists.txt
  cpp-client/deephaven/dhcore/CMakeLists.txt
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5773 feat: Add props for controlling WebGL settings
  props/configs/src/main/resources/dh-defaults.prop
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5800 ci: Publish jsapi-types patch release with v0.35 tag
  .github/workflows/publish-ci.yml
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5796 fix: correctly produce Kafka JSON nulls for int fields
  extensions/kafka/src/main/java/io/deephaven/kafka/publish/JsonKeyOrValueSerializer.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#5804 fix: Update web version 0.86.1
  web/client-ui/Dockerfile
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5798 fix: For NPE when sorting dictionary-encoded null string columns
  engine/table/src/main/java/io/deephaven/engine/table/impl/SortHelpers.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/ColumnRegionChunkDictionary.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/ParquetTableReadWriteTest.java
  extensions/parquet/table/src/test/resources/ReferenceNullStringDictEncoded1.parquet
  extensions/parquet/table/src/test/resources/ReferenceNullStringDictEncoded2.parquet
Labels: bug, parquet, NoDocumentationNeeded, ReleaseNotesNeeded

#5799 fix: For failure in path to URI conversion on windows
  Base/src/main/java/io/deephaven/base/FileUtils.java
Labels: bug, parquet, NoDocumentationNeeded, ReleaseNotesNeeded

#5692 refactor: Barrage stream reading into Chunks
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/BooleanChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/BooleanChunkReader.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/ByteChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/ByteChunkReader.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/CharChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/CharChunkReader.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/ChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/ChunkReader.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/DefaultChunkReadingFactory.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/DoubleChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/DoubleChunkReader.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/FixedWidthChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/FloatChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/FloatChunkReader.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/IntChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/IntChunkReader.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/LongChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/LongChunkReader.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/ShortChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/ShortChunkReader.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/VarBinaryChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/VarListChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/VarListChunkReader.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/VectorChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/VectorChunkReader.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/ArrowToTableConverter.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/BarrageChunkAppendingMarshaller.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/BarrageStreamReader.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/StreamReader.java
  extensions/barrage/src/test/java/io/deephaven/extensions/barrage/chunk/BarrageColumnRoundTripTest.java
  java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshotImpl.java
  java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java
  replication/static/src/main/java/io/deephaven/replicators/ReplicateBarrageUtils.java
  server/src/main/java/io/deephaven/server/arrow/ArrowFlightUtil.java
  server/test-utils/src/main/java/io/deephaven/server/test/FlightMessageRoundTripTest.java
Labels: barrage, NoDocumentationNeeded, NoReleaseNotesNeeded

#5802 perf: Add ForkJoinPool.commonPool()-based OperationInitializer for nested parallel DataIndex building
  engine/table/src/main/java/io/deephaven/engine/table/impl/ForkJoinPoolOperationInitializer.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/dataindex/TransformedDataIndex.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/MergedDataIndex.java
Labels: core, NoDocumentationNeeded, ReleaseNotesNeeded, point_release_candidate

#5781 refactor: use ObjectComparisons.compare for fixupObjectComparisons
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/ssmcountdistinct/ObjectSsmBackedSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/ssmminmax/ObjectSetResult.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/ssmpercentile/ObjectPercentileTypeHelper.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/join/dupcompact/ObjectDupCompactKernel.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/join/dupcompact/ObjectReverseDupCompactKernel.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/join/dupexpand/ObjectDupExpandKernel.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/join/stamp/ObjectNoExactReverseStampKernel.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/join/stamp/ObjectNoExactStampKernel.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/join/stamp/ObjectReverseStampKernel.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/join/stamp/ObjectStampKernel.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sort/timsort/ObjectByteTimsortDescendingKernel.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sort/timsort/ObjectByteTimsortKernel.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sort/timsort/ObjectIntTimsortDescendingKernel.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sort/timsort/ObjectIntTimsortKernel.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sort/timsort/ObjectLongTimsortDescendingKernel.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sort/timsort/ObjectLongTimsortKernel.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sort/timsort/ObjectTimsortDescendingKernel.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sort/timsort/ObjectTimsortKernel.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sortcheck/ObjectReverseSortCheck.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/ssa/ObjectChunkSsaStamp.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/ssa/ObjectReverseChunkSsaStamp.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/ssa/ObjectReverseSegmentedSortedArray.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/ssa/ObjectReverseSsaChecker.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/ssa/ObjectReverseSsaSsaStamp.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/ssa/ObjectSegmentedSortedArray.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/ssa/ObjectSsaChecker.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/ssa/ObjectSsaSsaStamp.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/ssms/ObjectSegmentedSortedMultiset.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/sort/partition/ObjectPartitionKernel.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/sort/timsort/BaseTestObjectTimSortKernel.java
  replication/reflective/build.gradle
  replication/static/src/main/java/io/deephaven/replicators/ReplicateSortKernel.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5808 fix: Check for null result in error handling
  engine/table/src/main/java/io/deephaven/engine/table/impl/MergedListener.java
Labels: NoDocumentationNeeded, python-server-side, NoReleaseNotesNeeded

#5805 feat: Update web version from 0.83.0 to 0.86.1
  web/client-ui/Dockerfile
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#5807 fix(cpp-client) Update C++ and R client
  R/build.gradle
  RELEASE.md
  cpp-client/README.md
  cpp-client/build.gradle
  cpp-client/deephaven/CMakeLists.txt
  cpp-client/deephaven/cmake/deephavenConfig.cmake
  cpp-client/deephaven/dhclient/CMakeLists.txt
  cpp-client/deephaven/dhclient/include/public/deephaven/client/interop/client_interop.h
  cpp-client/deephaven/dhclient/include/public/deephaven/client/interop/client_options_interop.h
  cpp-client/deephaven/dhclient/include/public/deephaven/client/interop/update_by_interop.h
  cpp-client/deephaven/dhclient/include/public/deephaven/client/update_by.h
  cpp-client/deephaven/dhclient/include/public/deephaven/client/utility/table_maker.h
  cpp-client/deephaven/dhclient/src/interop/client_interop.cc
  cpp-client/deephaven/dhclient/src/interop/client_options_interop.cc
  cpp-client/deephaven/dhclient/src/interop/update_by_interop.cc
  cpp-client/deephaven/dhcore/CMakeLists.txt
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/clienttable/schema.h
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/interop/interop_util.h
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/interop/testapi/basic_interop_interactions.h
  cpp-client/deephaven/dhcore/src/clienttable/schema.cc
  cpp-client/deephaven/dhcore/src/interop/interop_util.cc
  cpp-client/deephaven/dhcore/src/interop/testapi/basic_interop_interactions.cc
  cpp-client/deephaven/tests/src/add_drop_test.cc
  cpp-client/deephaven/tests/src/attributes_test.cc
  cpp-client/deephaven/tests/src/join_test.cc
  cpp-client/deephaven/tests/src/sort_test.cc
  cpp-client/deephaven/tests/src/ungroup_test.cc
  cpp-client/deephaven/tests/src/update_by_test.cc
  cpp-client/deephaven/tests/src/validation_test.cc
  cpp-client/deephaven/vcpkg-configuration.json
  cpp-client/deephaven/vcpkg.json
Labels: DocumentationNeeded, ReleaseNotesNeeded

#5812 fix: make TableListenerHandle a JObjectWrapper again (#5713)
  py/server/deephaven/table_listener.py
Labels: NoDocumentationNeeded, python-server-side, ReleaseNotesNeeded

#5813 feat: Add auto-legalization for Iceberg Schema column names
  extensions/iceberg/s3/src/test/java/io/deephaven/iceberg/util/IcebergToolsTest.java
  extensions/iceberg/s3/src/test/resources/warehouse/sales/sales_renamed/data/00000-4-62bcda08-a24a-4b17-a20a-e18edfea5b5a-0-00001.parquet
  extensions/iceberg/s3/src/test/resources/warehouse/sales/sales_renamed/metadata/00000-556b3c6d-3a0e-4912-916a-151f5d772a7b.metadata.json
  extensions/iceberg/s3/src/test/resources/warehouse/sales/sales_renamed/metadata/6154af6b-49cf-41eb-a340-ff60964e750d-m0.avro
  extensions/iceberg/s3/src/test/resources/warehouse/sales/sales_renamed/metadata/snap-1014870679100567484-1-6154af6b-49cf-41eb-a340-ff60964e750d.avro
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/IcebergCatalogAdapter.java
Labels: DocumentationNeeded, ReleaseNotesNeeded

#5810 fix: Fix readback of parquet files with missing dictionary page offse…
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/ColumnChunkReaderImpl.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/TestParquetTools.java
  extensions/parquet/table/src/test/resources/dictOffset/dh17395.parquet
  extensions/parquet/table/src/test/resources/dictOffset/dh17395_clean.parquet
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5777 feat: Added support to read parquet metadata files from S3
  Util/channel/src/main/java/io/deephaven/util/channel/CachedChannelProvider.java
  Util/channel/src/main/java/io/deephaven/util/channel/LocalFSChannelProvider.java
  Util/channel/src/main/java/io/deephaven/util/channel/SeekableChannelsProvider.java
  Util/channel/src/test/java/io/deephaven/util/channel/CachedChannelProviderTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableAggregationTest.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/ColumnChunkReaderImpl.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/ParquetUtils.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/ParquetTools.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/layout/ParquetKeyValuePartitionedLayout.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/layout/ParquetMetadataFileLayout.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/ParquetTableReadWriteTest.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/S3ParquetRemoteTest.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/S3ParquetTestBase.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/TestParquetTools.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3ChannelContext.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3SeekableChannelProvider.java
  extensions/trackedfile/src/main/java/io/deephaven/extensions/trackedfile/TrackedSeekableChannelsProvider.java
Labels: parquet, DocumentationNeeded, ReleaseNotesNeeded, s3

#5780 refactor!: Rearrange TypeUtils and ArrayTypeUtils so they can be shared with JS API
  Generators/src/main/java/io/deephaven/gen/JavaFunction.java
  Plot/src/main/java/io/deephaven/plot/util/ArgumentValidations.java
  Util/src/main/java/io/deephaven/util/type/ArrayTypeUtils.java
  Util/src/main/java/io/deephaven/util/type/NumericTypeUtils.java
  Util/src/main/java/io/deephaven/util/type/TypeUtils.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/AggregationProcessor.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/preview/ColumnPreviewManager.java
  engine/table/src/test/java/io/deephaven/engine/util/TestNumericTypeUtils.java
  engine/table/src/test/java/io/deephaven/engine/util/TestTypeUtils.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/BarrageUtil.java
  server/src/main/java/io/deephaven/server/table/ops/ColumnStatisticsGrpcImpl.java
Labels: NoDocumentationNeeded, breaking, ReleaseNotesNeeded

#5782 refactor!: Remove or inline Assert/Require methods so the classes can be shared with JS API
  Base/src/main/java/io/deephaven/base/verify/Assert.java
  Base/src/main/java/io/deephaven/base/verify/Require.java
  Plot/src/main/java/io/deephaven/plot/datasets/multiseries/AbstractMultiSeries.java
  Util/channel/src/main/java/io/deephaven/util/channel/CachedChannelProvider.java
  Util/src/main/java/io/deephaven/util/Utils.java
  Util/src/main/java/io/deephaven/util/datastructures/SubscriptionSet.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/SortOperation.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/AggregationProcessor.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/lang/QueryLanguageParser.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/BaseArrayBackedInputTable.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableAggregationTest.java
  engine/table/src/test/java/io/deephaven/engine/util/TestJobScheduler.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/table/BarrageTable.java
  server/src/main/java/io/deephaven/server/barrage/BarrageMessageProducer.java
  server/src/main/java/io/deephaven/server/hierarchicaltable/HierarchicalTableViewSubscription.java
Labels: NoDocumentationNeeded, breaking, ReleaseNotesNeeded

#5815 perf: PercentileTypeHelpers, use explicit comparison operator
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/ssmpercentile/BooleanPercentileTypeHelper.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/ssmpercentile/BytePercentileTypeHelper.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/ssmpercentile/CharPercentileTypeHelper.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/ssmpercentile/DoublePercentileTypeHelper.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/ssmpercentile/FloatPercentileTypeHelper.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/ssmpercentile/InstantPercentileTypeHelper.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/ssmpercentile/IntPercentileTypeHelper.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/ssmpercentile/LongPercentileTypeHelper.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/ssmpercentile/ObjectPercentileTypeHelper.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/ssmpercentile/ShortPercentileTypeHelper.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5816 perf: SortCheck, use explicit comparison operator
  engine/table/src/main/java/io/deephaven/engine/table/impl/sortcheck/ByteReverseSortCheck.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sortcheck/ByteSortCheck.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sortcheck/CharReverseSortCheck.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sortcheck/CharSortCheck.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sortcheck/DoubleReverseSortCheck.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sortcheck/DoubleSortCheck.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sortcheck/FloatReverseSortCheck.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sortcheck/FloatSortCheck.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sortcheck/IntReverseSortCheck.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sortcheck/IntSortCheck.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sortcheck/LongReverseSortCheck.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sortcheck/LongSortCheck.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sortcheck/ObjectReverseSortCheck.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sortcheck/ObjectSortCheck.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sortcheck/ShortReverseSortCheck.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sortcheck/ShortSortCheck.java
  replication/static/src/main/java/io/deephaven/replicators/ReplicateSortCheck.java
  replication/static/src/main/java/io/deephaven/replicators/ReplicateSortKernel.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5818 perf: Blink / AddOnly SortedFirstOrLast, use explicit comparison operator
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/ByteAddOnlySortedFirstOrLastChunkedOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/ByteBlinkSortedFirstOrLastChunkedOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/CharAddOnlySortedFirstOrLastChunkedOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/CharBlinkSortedFirstOrLastChunkedOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/DoubleAddOnlySortedFirstOrLastChunkedOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/DoubleBlinkSortedFirstOrLastChunkedOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/FloatAddOnlySortedFirstOrLastChunkedOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/FloatBlinkSortedFirstOrLastChunkedOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/IntAddOnlySortedFirstOrLastChunkedOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/IntBlinkSortedFirstOrLastChunkedOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/LongAddOnlySortedFirstOrLastChunkedOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/LongBlinkSortedFirstOrLastChunkedOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/ObjectAddOnlySortedFirstOrLastChunkedOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/ObjectBlinkSortedFirstOrLastChunkedOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/ShortAddOnlySortedFirstOrLastChunkedOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/ShortBlinkSortedFirstOrLastChunkedOperator.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5828 feat: Codec-api should support java8 for Enterprise
  codec/api/gradle.properties
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5829 fix(r-client): Add explicit mention of libxml2 and pandoc to R client's README.md
  R/rdeephaven/README.md
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5832 fix: Downgrade web UI to patch version v0.85.3
  web/client-ui/Dockerfile
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5830 feat: Make codec-api support java 8
  codec/api/gradle.properties
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5843 feat(cpp-client): Add GetTidAsString as a utility function
  cpp-client/deephaven/dhcore/CMakeLists.txt
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/utility/utility.h
  cpp-client/deephaven/dhcore/src/utility/utility_platform_specific.cc
  cpp-client/deephaven/tests/src/utility_test.cc
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5845 feat(cpp-client): Move GetHostname and GetEnv to dhcore
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/utility/utility.h
  cpp-client/deephaven/dhcore/src/utility/utility_platform_specific.cc
  cpp-client/deephaven/tests/src/utility_test.cc
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5844 feat(cpp-client): Use arrow-16.0.0 on Windows.
  cpp-client/deephaven/cmake/deephavenConfig.cmake
  cpp-client/deephaven/vcpkg.json
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5849 feat(cpp-client): utility function to read a password from stdin
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/utility/utility.h
  cpp-client/deephaven/dhcore/src/utility/utility.cc
  cpp-client/deephaven/dhcore/src/utility/utility_platform_specific.cc
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5850 fix: Make Java, Python wheel artifacts have same dependencies
  py/embedded-server/build.gradle
  py/embedded-server/java-runtime/build.gradle
  py/embedded-server/requirements-dev.txt
  py/embedded-server/tests/test_load_app_modules.py
  py/server/deephaven_internal/stream.py
  server/jetty-app/build.gradle
  server/netty-app/build.gradle
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#5857 fix(cpp-client): Add mising target link lib winsock2 for windows
  cpp-client/deephaven/dhcore/CMakeLists.txt
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5861 fix(cpp-client): Update README.md to make Linux and Windows instructions more consistent
  cpp-client/README.md
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5862 feat: Add nightly publishing job for SNAPSHOT jars
  .github/workflows/nightly-publish-ci.yml
  buildSrc/src/main/groovy/io/deephaven/project/util/PublishingTools.groovy
Labels: ci, NoDocumentationNeeded, NoReleaseNotesNeeded

#5867 fix(cpp-client): Make the instructions more explicit about the correct setting of VCPKG_ROOT
  cpp-client/README.md
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5859 refactor: centralize optional server dependencies into plugin
  buildSrc/src/main/groovy/io.deephaven.optional-server-dependencies.gradle
  py/embedded-server/java-runtime/build.gradle
  server/jetty-app/build.gradle
  server/netty-app/build.gradle
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5869 fix(cpp-client): Instructions to build on windows based on DHSRC and DHINSTALL env vars
  cpp-client/README.md
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5872 perf: Re-write the writing half of ExternalizableRowSetUtils
  engine/rowset/src/main/java/io/deephaven/engine/rowset/impl/ExternalizableRowSetUtils.java
  web/client-api/src/main/java/io/deephaven/web/client/api/barrage/CompressedRangeSetReader.java
Labels: query engine, core, NoDocumentationNeeded, ReleaseNotesNeeded

#5876 perf: RegionedColumnSourceManager.update to parallelize refresh or subscription for empty locations
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/RegionedColumnSourceManager.java
Labels: query engine, core, NoDocumentationNeeded, ReleaseNotesNeeded

#5846 refactor: Barrage and Chunk cleanup preparing for JS API support
  engine/chunk/src/main/java/io/deephaven/chunk/Chunk.java
  engine/chunk/src/main/java/io/deephaven/chunk/ChunkBase.java
  engine/chunk/src/main/java/io/deephaven/chunk/ChunkHelpers.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/BarrageStreamGeneratorImpl.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/array/ArrayReflectUtil.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/array/ObjectArrayExpansionKernel.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/BarrageProtoUtil.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/DefensiveCapture.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/ExposedByteArrayOutputStream.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/TableToArrowConverter.java
  extensions/barrage/src/test/java/io/deephaven/extensions/barrage/chunk/BarrageColumnRoundTripTest.java
  server/src/main/java/io/deephaven/server/util/UnaryInputStreamMarshaller.java
  server/src/test/java/io/deephaven/server/barrage/BarrageMessageRoundTripTest.java
Labels: barrage, NoDocumentationNeeded, ReleaseNotesNeeded
