Repository deephaven/deephaven-core, pull requests merged in 2024-08, with the labels that each got.

#5865 fix!: Update Iceberg snapshots table to use `Instant` timestamps.
  extensions/iceberg/s3/src/test/java/io/deephaven/iceberg/util/IcebergToolsTest.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/IcebergCatalogAdapter.java
Labels: NoDocumentationNeeded, breaking, ReleaseNotesNeeded

#5558 feat: Added support for parallel snapshot
  engine/table/src/main/java/io/deephaven/engine/exceptions/ColumnSnapshotUnsuccessfulException.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/hierarchical/HierarchicalTableSnapshotException.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/remote/ConstructSnapshot.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/analyzers/SelectColumnLayer.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/RedirectedColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/BarrageMessage.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableTest.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/ParquetTools.java
  server/src/main/java/io/deephaven/server/runner/DeephavenApiServer.java
Labels: feature request, query engine, core, NoDocumentationNeeded, ReleaseNotesNeeded

#5885 feat: Add TableTools.metaTable(TableDefinition)
  engine/api/src/main/java/io/deephaven/engine/table/Table.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/TableDefaults.java
  engine/table/src/main/java/io/deephaven/engine/util/TableTools.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5893 fix: disable py-client-ticking tests
  py/client-ticking/build.gradle
Labels: ci, NoDocumentationNeeded, NoReleaseNotesNeeded

#5886 feat: Add java client MultiJoin
  engine/sql/src/main/java/io/deephaven/engine/sql/TableCreatorTicketInterceptor.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/TableCreatorImpl.java
  java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshotImpl.java
  java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java
  java-client/barrage/src/main/java/io/deephaven/client/impl/TableSpecLabeler.java
  java-client/session-dagger/src/test/java/io/deephaven/client/DeephavenSessionTestBase.java
  java-client/session-dagger/src/test/java/io/deephaven/client/MultiJoinTest.java
  java-client/session/src/main/java/io/deephaven/client/impl/BatchTableRequestBuilder.java
  java-client/session/src/main/java/io/deephaven/client/impl/TableHandleManagerBase.java
  java-client/session/src/main/java/io/deephaven/client/impl/TableHandleManagerDelegate.java
  qst/src/main/java/io/deephaven/qst/TableAdapterImpl.java
  qst/src/main/java/io/deephaven/qst/TableCreator.java
  qst/src/main/java/io/deephaven/qst/table/MultiJoinInput.java
  qst/src/main/java/io/deephaven/qst/table/MultiJoinTable.java
  qst/src/main/java/io/deephaven/qst/table/ParentsVisitor.java
  qst/src/main/java/io/deephaven/qst/table/StackTraceMixInCreator.java
  qst/src/main/java/io/deephaven/qst/table/TableCreatorImpl.java
  qst/src/main/java/io/deephaven/qst/table/TableLabelVisitor.java
  qst/src/main/java/io/deephaven/qst/table/TableSpec.java
  qst/src/main/java/io/deephaven/qst/table/TableVisitorGeneric.java
  qst/src/test/java/io/deephaven/qst/table/MultiJoinTableTest.java
Labels: NoDocumentationNeeded, java-client, NoReleaseNotesNeeded

#5853 fix: update snapshot_when doc with trigger table being append-only requirement when history is requested.
  engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java
  py/server/deephaven/table.py
  py/server/tests/test_table.py
  table-api/src/main/java/io/deephaven/api/snapshot/SnapshotWhenOptions.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#5906 fix: Unit test and fix for AIOOBE in multiJoin when adding more than 3072 rows to an initially-empty result
  engine/table/src/main/java/io/deephaven/engine/table/impl/multijoin/IncrementalMultiJoinStateManagerTypedBase.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableMultiJoinTest.java
Labels: bug, query engine, core, NoDocumentationNeeded, ReleaseNotesNeeded

#5866 feat: Added --browser / --no-browser flag
  py/embedded-server/deephaven_server/cli.py
Labels: DocumentationNeeded, ReleaseNotesNeeded

#5891 feat: provide TableDefinition functions for Iceberg tables
  engine/table/src/main/java/io/deephaven/engine/util/TableTools.java
  extensions/iceberg/s3/src/test/java/io/deephaven/iceberg/util/IcebergToolsTest.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/IcebergCatalogAdapter.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#5913 fix: make table reader/depending modules work in Py 3.8/3.9
  py/server/deephaven/_table_reader.py
Labels: NoDocumentationNeeded, python-server-side, NoReleaseNotesNeeded

#5915 fix: Make Java, Python wheel artifacts have same dependencies
  py/embedded-server/build.gradle
  py/embedded-server/java-runtime/build.gradle
  py/embedded-server/requirements-dev.txt
  py/embedded-server/tests/test_load_app_modules.py
  py/server/deephaven_internal/stream.py
  server/jetty-app/build.gradle
  server/netty-app/build.gradle
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#5905 fix: update to setup-gradle
  .github/workflows/build-ci.yml
  .github/workflows/check-ci.yml
  .github/workflows/docs-ci.yml
  .github/workflows/nightly-check-ci.yml
  .github/workflows/nightly-image-check.yml
  .github/workflows/publish-ci.yml
  .github/workflows/quick-ci.yml
  .github/workflows/tag-base-images.yml
Labels: ci, NoDocumentationNeeded, NoReleaseNotesNeeded

#5889 refactor: BaseChunkInputStreamGenerator can be ReferenceCounted
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/BaseChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/VarBinaryChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/VarListChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/VectorChunkInputStreamGenerator.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#5918 feat: detect piped union
  .github/workflows/quick-ci.yml
Labels: ci, NoDocumentationNeeded, NoReleaseNotesNeeded

#5910 fix: `y_twin` pydoc
  Generators/src/main/java/io/deephaven/plot/util/GeneratePyV2FigureAPI.java
  py/server/deephaven/plot/figure.py
Labels: documentation, NoDocumentationNeeded, NoReleaseNotesNeeded

#5919 fix: update R DESCRIPTION file to include URL
  R/build.gradle
  R/rdeephaven/DESCRIPTION
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded, r-client

#5814 feat(table): add Table.diff method
  py/server/deephaven/table.py
  py/server/tests/test_table.py
  py/server/tests/testbase.py
Labels: DocumentationNeeded, python-server-side, ReleaseNotesNeeded

#5925 fix(r-client): add missing R package dependencies for building R client in its README.
  R/rdeephaven/README.md
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5752 feat: Add versioned gRPC user-agent for java client
  java-client/barrage-examples/src/main/java/io/deephaven/client/examples/BarrageClientExampleBase.java
  java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSessionFactoryConfig.java
  java-client/flight-examples/src/main/java/io/deephaven/client/examples/DoPutSpray.java
  java-client/flight-examples/src/main/java/io/deephaven/client/examples/FlightExampleBase.java
  java-client/flight/src/main/java/io/deephaven/client/impl/FlightSessionFactoryConfig.java
  java-client/session-dagger/src/main/java/io/deephaven/client/ClientDefaultsModule.java
  java-client/session-examples/src/main/java/io/deephaven/client/examples/SessionExampleBase.java
  java-client/session/src/main/java/io/deephaven/client/grpc/UserAgentUtility.java
  java-client/session/src/main/java/io/deephaven/client/impl/ClientChannelFactoryDefaulter.java
  java-client/session/src/main/java/io/deephaven/client/impl/ClientConfig.java
  java-client/session/src/main/java/io/deephaven/client/impl/SessionFactoryConfig.java
  py/embedded-server/java-runtime/src/main/java/io/deephaven/python/server/EmbeddedServer.java
  server/jetty-app-custom/src/main/java/io/deephaven/server/custom/CustomClientChannelFactoryModule.java
  server/jetty-app-custom/src/main/java/io/deephaven/server/custom/CustomComponentFactory.java
  server/jetty/src/main/java/io/deephaven/server/jetty/CommunityComponentFactory.java
  server/jetty/src/main/java/io/deephaven/server/jetty/JettyClientChannelFactoryModule.java
  server/netty/src/main/java/io/deephaven/server/netty/DeprecatedCommunityComponentFactory.java
  server/netty/src/main/java/io/deephaven/server/netty/NettyClientChannelFactoryModule.java
  server/src/main/java/io/deephaven/client/ClientDefaultsModule.java
  server/src/main/java/io/deephaven/server/runner/CommunityDefaultsModule.java
  server/src/main/java/io/deephaven/server/runner/DeephavenApiConfigModule.java
  server/src/main/java/io/deephaven/server/session/ClientChannelFactoryModule.java
  server/src/main/java/io/deephaven/server/session/SessionFactoryCreator.java
  server/src/main/java/io/deephaven/server/session/SslConfigModule.java
  server/test-utils/src/main/java/io/deephaven/server/runner/DeephavenApiServerTestBase.java
Labels: DocumentationNeeded, java-client, ReleaseNotesNeeded

#5932 fix: Test for proper clock settings before running clock tests
  engine/time/src/test/java/io/deephaven/time/TestDateTimeUtils.java
  engine/time/src/test/java/io/deephaven/time/calendar/TestStaticCalendarMethods.java
Labels: bug, NoDocumentationNeeded, NoReleaseNotesNeeded

#5930 feat: Throw exception when writing array/vector of big decimals to parquet
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/TypeInfos.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/ParquetTableReadWriteTest.java
Labels: parquet, NoDocumentationNeeded, ReleaseNotesNeeded

#5936 chore: Bump to jpy 0.18.0
  docker/registry/server-base/gradle.properties
  docker/server-jetty/src/main/server-jetty/requirements.txt
  docker/server/src/main/server-netty/requirements.txt
  gradle/libs.versions.toml
  py/embedded-server/setup.py
  py/server/setup.py
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#5914 feat: Added support to write parquet files to S3
  Util/channel/src/main/java/io/deephaven/util/channel/CachedChannelProvider.java
  Util/channel/src/main/java/io/deephaven/util/channel/CompletableOutputStream.java
  Util/channel/src/main/java/io/deephaven/util/channel/LocalFSChannelProvider.java
  Util/channel/src/main/java/io/deephaven/util/channel/SeekableChannelsProvider.java
  Util/channel/src/test/java/io/deephaven/util/channel/CachedChannelProviderTest.java
  extensions/parquet/base/build.gradle
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/ColumnWriterImpl.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/NullParquetMetadataFileWriter.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/ParquetFileWriter.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/ParquetMetadataFileWriter.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/ParquetUtils.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/PositionedBufferedOutputStream.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/RowGroupWriterImpl.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/ParquetMetadataFileWriterImpl.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/ParquetTableWriter.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/ParquetTools.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/ParquetTableReadWriteTest.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/S3ParquetTestBase.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/TestParquetTools.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3AsyncClientFactory.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3CompletableOutputStream.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3Instructions.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3SeekableChannelProvider.java
  extensions/s3/src/test/java/io/deephaven/extensions/s3/S3InstructionsTest.java
  extensions/s3/src/test/java/io/deephaven/extensions/s3/S3SeekableChannelSimpleTestBase.java
  extensions/s3/src/test/java/io/deephaven/extensions/s3/testlib/S3SeekableChannelTestSetup.java
  extensions/trackedfile/build.gradle
  extensions/trackedfile/src/main/java/io/deephaven/extensions/trackedfile/LocalCompletableOutputStream.java
  extensions/trackedfile/src/main/java/io/deephaven/extensions/trackedfile/TrackedSeekableChannelsProvider.java
  py/server/deephaven/experimental/s3.py
  py/server/deephaven/parquet.py
Labels: feature request, parquet, DocumentationNeeded, ReleaseNotesNeeded, s3

#5942 fix: Fix PartitioningColumnDataIndex: region RowSet provenance and index RowSet tracking
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/PartitioningColumnDataIndex.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/RegionedColumnSourceManager.java
Labels: query engine, core, NoDocumentationNeeded, point_release_candidate

#5943 fix: Only run nightly-publish-ci for deephaven project
  .github/workflows/nightly-publish-ci.yml
Labels: ci, NoDocumentationNeeded, NoReleaseNotesNeeded

#5945 fix: For failure in reading dictionary encoded parquet strings
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/ColumnChunkReaderImpl.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/S3ParquetRemoteTest.java
Labels: bug, parquet, NoDocumentationNeeded, ReleaseNotesNeeded

#5892 feat!: Add TableDefinition wrapper for python
  py/server/deephaven/_table_reader.py
  py/server/deephaven/column.py
  py/server/deephaven/experimental/iceberg.py
  py/server/deephaven/jcompat.py
  py/server/deephaven/learn/__init__.py
  py/server/deephaven/numpy.py
  py/server/deephaven/pandas.py
  py/server/deephaven/parquet.py
  py/server/deephaven/stream/kafka/consumer.py
  py/server/deephaven/stream/table_publisher.py
  py/server/deephaven/table.py
  py/server/deephaven/table_factory.py
  py/server/tests/test_barrage.py
  py/server/tests/test_column.py
  py/server/tests/test_csv.py
  py/server/tests/test_data_index.py
  py/server/tests/test_dbc.py
  py/server/tests/test_experiments.py
  py/server/tests/test_iceberg.py
  py/server/tests/test_numpy.py
  py/server/tests/test_parquet.py
  py/server/tests/test_partitioned_table.py
  py/server/tests/test_pt_proxy.py
  py/server/tests/test_table.py
  py/server/tests/test_table_definition.py
  py/server/tests/test_table_factory.py
  py/server/tests/test_table_iterator.py
  py/server/tests/test_table_listener.py
  py/server/tests/test_updateby.py
  py/server/tests/test_vectorization.py
Labels: DocumentationNeeded, ReleaseNotesNeeded

#5929 feat: Support on-error callback for Py listeners
  Integrations/build.gradle
  Integrations/src/main/java/io/deephaven/integrations/python/PythonMergedListenerAdapter.java
  Integrations/src/main/java/io/deephaven/integrations/python/PythonReplayListenerAdapter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/InstrumentedTableListenerBase.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/MergedListener.java
  py/server/deephaven/table_listener.py
  py/server/tests/test_table_listener.py
Labels: DocumentationNeeded, ReleaseNotesNeeded

#5924 perf: Remove Unnecessary Recursion from Select/Update
  Util/src/main/java/io/deephaven/util/SimpleTypeMap.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/QueryCompilerRequestProcessor.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/SelectOrUpdateListener.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/ShiftedColumnsFactory.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/lang/QueryLanguageParser.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/AbstractConditionFilter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/AbstractFormulaColumn.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/DhFormulaColumn.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/MatchFilter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/RangeFilter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/analyzers/BaseLayer.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/analyzers/ConstantColumnLayer.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/analyzers/DependencyLayerBase.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/analyzers/PreserveColumnLayer.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/analyzers/RedirectionLayer.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/analyzers/SelectAndViewAnalyzer.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/analyzers/SelectAndViewAnalyzerWrapper.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/analyzers/SelectColumnLayer.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/analyzers/SelectOrViewColumnLayer.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/analyzers/StaticFlattenLayer.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/analyzers/ViewColumnLayer.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/codegen/FormulaAnalyzer.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/lang/TestQueryLanguageParser.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/VarListChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/VarListChunkReader.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/array/BoxedBooleanArrayExpansionKernel.java
Labels: clean up, core, NoDocumentationNeeded, ReleaseNotesNeeded

#5946 fix: Go and JS clients should not require v1+v2 auth
  go/pkg/client/tokens.go
  web/client-api/src/main/java/io/deephaven/web/client/api/WorkerConnection.java
Labels: NoDocumentationNeeded, release blocker, ReleaseNotesNeeded

#5951 fix: post merge improvement on table listener code and docstring
  Integrations/src/main/java/io/deephaven/integrations/python/PythonMergedListenerAdapter.java
  Integrations/src/main/java/io/deephaven/integrations/python/PythonReplayListenerAdapter.java
  py/server/deephaven/table_listener.py
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5952 chore: Bump to 0.37.0-SNAPSHOT
  R/rdeephaven/DESCRIPTION
  cpp-client/deephaven/CMakeLists.txt
  gradle.properties
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5956 feat: Add static getter for TableDefinition in KafkaTools
  extensions/kafka/src/main/java/io/deephaven/kafka/KafkaTools.java
Labels: DocumentationNeeded, ReleaseNotesNeeded

#5788 chore: bump to Gradle 8.10
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: NoDocumentationNeeded, version-bump, NoReleaseNotesNeeded

#5961 fix: Parallel Where should not NPE on a Big TableUpdate With Both Adds and Mods
  engine/table/src/main/java/io/deephaven/engine/table/impl/AbstractFilterExecution.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableWhereParallelTest.java
Labels: bug, core, NoDocumentationNeeded, ReleaseNotesNeeded, point_release_candidate

#5959 fix: JS API should use GetConfigurationConstants for auth calls
  web/client-api/src/main/java/io/deephaven/web/client/api/CoreClient.java
  web/client-api/src/main/java/io/deephaven/web/client/api/WorkerConnection.java
  web/client-api/src/main/java/io/deephaven/web/client/api/barrage/stream/HandshakeStreamFactory.java
  web/client-api/src/main/java/io/deephaven/web/client/api/grpc/UnaryWithHeaders.java
Labels: jsapi, NoDocumentationNeeded, authentication, ReleaseNotesNeeded

#5970 feat: Expose Python/Groovy version to clients
  Integrations/src/main/java/io/deephaven/integrations/python/PythonDeephavenSession.java
  java-client/session-examples/build.gradle
  java-client/session-examples/src/main/java/io/deephaven/client/examples/PrintConfigurationConstants.java
  props/configs/src/main/resources/dh-defaults.prop
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#5972 fix: Parallel Where should not NPE on a Big TableUpdate With Both Adds and Mods (#5961)
  engine/table/src/main/java/io/deephaven/engine/table/impl/AbstractFilterExecution.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableWhereParallelTest.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#5975 fix(cpp-client): Provide correct instructions for making a RelWithDebInfo build
  cpp-client/README.md
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5974 feat: Add fileIO() method
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/IcebergCatalogAdapter.java
Labels: NoDocumentationNeeded, iceberg

#5971 chore: bump docker images
  docker/registry/cpp-clients-multi-base/gradle.properties
  docker/registry/fedora/gradle.properties
  docker/registry/go/gradle.properties
  docker/registry/localstack/gradle.properties
  docker/registry/manylinux2014_x86_64/gradle.properties
  docker/registry/minio/gradle.properties
  docker/registry/protoc-base/gradle.properties
  docker/registry/python/gradle.properties
  docker/registry/server-base/gradle.properties
  docker/registry/slim-base/gradle.properties
  docker/server-jetty/src/main/server-jetty/requirements.txt
  docker/server/src/main/server-netty/requirements.txt
  py/client-ticking/README.md
  py/client-ticking/pyClientTickingWheel/entrypoint.sh
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5965 fix: use correct syntax for code-block in python documentation
  py/server/deephaven/json/__init__.py
Labels: documentation, NoDocumentationNeeded, NoReleaseNotesNeeded

#5978 feat: Expose FileIO
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/IcebergCatalogAdapter.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded, iceberg

#5976 fix: Update web version 0.90.0 (#5963)
  web/client-ui/Dockerfile
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5954 fix: Provide a warning when running autocomplete in a way that could segfault
  py/server/deephaven_internal/auto_completer/__init__.py
  py/server/deephaven_internal/auto_completer/_completer.py
Labels: NoDocumentationNeeded, python-server-side, ReleaseNotesNeeded

#5979 fix: use correct syntax for code-block in python documentation
  py/server/deephaven/json/__init__.py
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#5977 fix: JS API should use GetConfigurationConstants for auth calls
  web/client-api/src/main/java/io/deephaven/web/client/api/CoreClient.java
  web/client-api/src/main/java/io/deephaven/web/client/api/WorkerConnection.java
  web/client-api/src/main/java/io/deephaven/web/client/api/barrage/stream/HandshakeStreamFactory.java
  web/client-api/src/main/java/io/deephaven/web/client/api/grpc/UnaryWithHeaders.java
Labels: jsapi, NoDocumentationNeeded, ReleaseNotesNeeded

#5981 fix: correct pydocs for table_definition in parquet
  py/server/deephaven/parquet.py
Labels: documentation, NoDocumentationNeeded, ReleaseNotesNeeded

#5982 fix: correct pydocs for table_definition in parquet
  py/server/deephaven/parquet.py
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#5980 fix: Provide a warning when running autocomplete in a way that could segfault
  py/server/deephaven_internal/auto_completer/__init__.py
  py/server/deephaven_internal/auto_completer/_completer.py
Labels: autocomplete, NoDocumentationNeeded, python-server-side, ReleaseNotesNeeded

#5984 feat: Add static getter for TableDefinition in KafkaTools
  extensions/kafka/src/main/java/io/deephaven/kafka/KafkaTools.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5988 fix(cpp-client): Fix certain error messages
  cpp-client/deephaven/dhcore/src/utility/utility_platform_specific.cc
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5986 fix(cpp-client): WinSock calls need to be prefaced by WSAStartup
  cpp-client/deephaven/dhcore/src/utility/utility_platform_specific.cc
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5987 feat(cpp-client): Add entry points for SetEnv() and UnsetEnv()
  cpp-client/deephaven/dhcore/CMakeLists.txt
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/interop/utility_interop.h
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/utility/utility.h
  cpp-client/deephaven/dhcore/src/interop/utility_interop.cc
  cpp-client/deephaven/dhcore/src/utility/utility_platform_specific.cc
  cpp-client/deephaven/tests/src/utility_test.cc
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5648 fix!: Fix a TimeRange off-by-one bug in nanosecond calculation
  engine/time/src/main/java/io/deephaven/time/calendar/BusinessCalendarXMLParser.java
  engine/time/src/main/java/io/deephaven/time/calendar/TimeRange.java
  engine/time/src/test/java/io/deephaven/time/calendar/TestBusinessCalendarXMLParser.java
  engine/time/src/test/java/io/deephaven/time/calendar/TestCalendarDay.java
  engine/time/src/test/java/io/deephaven/time/calendar/TestCalendars.java
  engine/time/src/test/java/io/deephaven/time/calendar/TestTimeRange.java
  engine/time/src/test/resources/PARSER-TEST.calendar
  props/configs/src/main/resources/calendar/UTC.calendar
Labels: bug, query engine, DocumentationNeeded, breaking, ReleaseNotesNeeded, June2024

#6000 fix: For broken pydocs for S3
  py/server/deephaven/experimental/s3.py
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded, s3

#6003 feat(csharp/client): Wrappers for some Enterprise Core+ features
  csharp/client/DeephavenClient/Client.cs
  csharp/client/DeephavenClient/DeephavenClient.csproj
  csharp/client/DeephavenClient/TableHandleManager.cs
  csharp/client/DeephavenClient/dhe_client/session/DndClient.cs
  csharp/client/DeephavenClient/dhe_client/session/DndTableHandleManager.cs
  csharp/client/DeephavenClient/dhe_client/session/SessionManager.cs
  csharp/client/DeephavenClient/interop/InteropSupport.cs
  csharp/client/DeephavenClient/interop/TestApi/BasicInteropInteractions.cs
  csharp/client/DeephavenClient/utility/ColumnFactory.cs
  csharp/client/DeephavenClient/utility/DeephavenConstants.cs
  csharp/client/DeephavenClient/utility/Schema.cs
  csharp/client/DeephavenClient/utility/TableMaker.cs
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5997 fix: Use parquet converted type only if logical type not set
  extensions/iceberg/s3/build.gradle
  extensions/iceberg/s3/src/test/java/io/deephaven/iceberg/util/IcebergLocalStackTest.java
  extensions/iceberg/s3/src/test/java/io/deephaven/iceberg/util/IcebergMinIOTest.java
  extensions/iceberg/s3/src/test/java/io/deephaven/iceberg/util/IcebergToolsTest.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/ParquetFileReader.java
Labels: bug, parquet, NoDocumentationNeeded, ReleaseNotesNeeded

#6002 fix(cpp-client): Bump arrow version (fixes Windows build)
  cpp-client/deephaven/vcpkg.json
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6004 feat(csharp/ExcelAddIn): First version of the Excel AddIn
  csharp/ExcelAddIn/DeephavenExcelFunctions.cs
  csharp/ExcelAddIn/ExcelAddIn.csproj
  csharp/ExcelAddIn/ExcelAddIn.csproj.user
  csharp/ExcelAddIn/ExcelAddIn.sln
  csharp/ExcelAddIn/Properties/launchSettings.json
  csharp/ExcelAddIn/README.md
  csharp/ExcelAddIn/StateManager.cs
  csharp/ExcelAddIn/exceldna/ExcelDnaHelpers.cs
  csharp/ExcelAddIn/factories/ConnectionManagerDialogFactory.cs
  csharp/ExcelAddIn/factories/CredentialsDialogFactory.cs
  csharp/ExcelAddIn/factories/SessionBaseFactory.cs
  csharp/ExcelAddIn/models/Credentials.cs
  csharp/ExcelAddIn/models/Session.cs
  csharp/ExcelAddIn/models/SimpleModels.cs
  csharp/ExcelAddIn/models/TableTriple.cs
  csharp/ExcelAddIn/operations/SnapshotOperation.cs
  csharp/ExcelAddIn/operations/SubscribeOperation.cs
  csharp/ExcelAddIn/providers/CorePlusClientProvider.cs
  csharp/ExcelAddIn/providers/DefaultSessionProvider.cs
  csharp/ExcelAddIn/providers/SessionProvider.cs
  csharp/ExcelAddIn/providers/SessionProviders.cs
  csharp/ExcelAddIn/providers/TableHandleProvider.cs
  csharp/ExcelAddIn/util/ActionAsDisposable.cs
  csharp/ExcelAddIn/util/ObserverContainer.cs
  csharp/ExcelAddIn/util/Renderer.cs
  csharp/ExcelAddIn/util/StatusOr.cs
  csharp/ExcelAddIn/util/TableDescriptor.cs
  csharp/ExcelAddIn/util/Utility.cs
  csharp/ExcelAddIn/util/WorkerThread.cs
  csharp/ExcelAddIn/viewmodels/ConnectionManagerDialogRow.cs
  csharp/ExcelAddIn/viewmodels/CredentialsDialogViewModel.cs
  csharp/ExcelAddIn/views/ConnectionManagerDialog.Designer.cs
  csharp/ExcelAddIn/views/ConnectionManagerDialog.cs
  csharp/ExcelAddIn/views/ConnectionManagerDialog.resx
  csharp/ExcelAddIn/views/CredentialsDialog.Designer.cs
  csharp/ExcelAddIn/views/CredentialsDialog.cs
  csharp/ExcelAddIn/views/CredentialsDialog.resx
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6008 feat(csharp/ExcelAddIn): allow insecure JSON URL for Core+; choose python/groovy for Core
  csharp/ExcelAddIn/factories/CredentialsDialogFactory.cs
  csharp/ExcelAddIn/factories/SessionBaseFactory.cs
  csharp/ExcelAddIn/models/Credentials.cs
  csharp/ExcelAddIn/viewmodels/CredentialsDialogViewModel.cs
  csharp/ExcelAddIn/views/CredentialsDialog.Designer.cs
  csharp/ExcelAddIn/views/CredentialsDialog.cs
  csharp/ExcelAddIn/views/CredentialsDialog.resx
  csharp/client/DeephavenClient/dhe_client/session/SessionManager.cs
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded
