Repository deephaven/deephaven-core, pull requests merged in 2024-01, with the labels that each got.

#4998 Go Client: Change TimeTable method to allow a variety of time/period types
  go/pkg/client/client_test.go
  go/pkg/client/table_stub.go
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4996 Adjust parameters for floating point tests
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/BucketedPartitionedUpdateByManager.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/ZeroKeyUpdateByManager.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableAggregationTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/BaseUpdateByTest.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4967 Bump to jetty 11.0.19
  buildSrc/src/main/groovy/Classpaths.groovy
Labels: NoDocumentationNeeded, jetty, version-bump, NoReleaseNotesNeeded

#4950 Add additional JsPlugin documentation
  plugin/src/main/java/io/deephaven/plugin/js/JsPlugin.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5008 Revise auto-generated doc issues
  .github/workflows/create-docs-issues.js
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5000 PagingChunkSource context protocol documentation, many silly cleanups, hints for channel context integration
  engine/api/src/main/java/io/deephaven/engine/table/Context.java
  engine/base/src/main/java/io/deephaven/engine/table/impl/ContextWithChunk.java
  engine/base/src/main/java/io/deephaven/engine/table/impl/DefaultChunkSource.java
  engine/table/src/main/java/io/deephaven/engine/page/ChunkPage.java
  engine/table/src/main/java/io/deephaven/engine/page/Page.java
  engine/table/src/main/java/io/deephaven/engine/page/PageStore.java
  engine/table/src/main/java/io/deephaven/engine/page/PagingChunkSource.java
  engine/table/src/main/java/io/deephaven/engine/page/PagingContextHolder.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/ColumnRegionByte.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/ColumnRegionChar.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/ColumnRegionDouble.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/ColumnRegionFloat.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/ColumnRegionInt.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/ColumnRegionLong.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/ColumnRegionObject.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/ColumnRegionShort.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/DeferredColumnRegionBase.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/RegionContextHolder.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/RegionedPageStore.java
  engine/time/src/main/java/io/deephaven/time/DateTimeUtils.java
  extensions/parquet/table/build.gradle
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/pagestore/ColumnChunkPageStore.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/pagestore/OffsetIndexBasedColumnChunkPageStore.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/pagestore/VariablePageSizeColumnChunkPageStore.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/region/ParquetColumnRegionBase.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/region/ParquetColumnRegionObject.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/transfer/LocalDateTimeArrayTransfer.java
  extensions/source-support/src/main/java/io/deephaven/generic/page/ChunkHolderPageBoolean.java
  extensions/source-support/src/main/java/io/deephaven/generic/page/ChunkHolderPageByte.java
  extensions/source-support/src/main/java/io/deephaven/generic/page/ChunkHolderPageChar.java
  extensions/source-support/src/main/java/io/deephaven/generic/page/ChunkHolderPageDouble.java
  extensions/source-support/src/main/java/io/deephaven/generic/page/ChunkHolderPageFloat.java
  extensions/source-support/src/main/java/io/deephaven/generic/page/ChunkHolderPageInt.java
  extensions/source-support/src/main/java/io/deephaven/generic/page/ChunkHolderPageLong.java
  extensions/source-support/src/main/java/io/deephaven/generic/page/ChunkHolderPageObject.java
  extensions/source-support/src/main/java/io/deephaven/generic/page/ChunkHolderPageShort.java
  extensions/source-support/src/main/java/io/deephaven/generic/region/AppendOnlyFixedSizePageRegionByte.java
  extensions/source-support/src/main/java/io/deephaven/generic/region/AppendOnlyFixedSizePageRegionChar.java
  extensions/source-support/src/main/java/io/deephaven/generic/region/AppendOnlyFixedSizePageRegionDouble.java
  extensions/source-support/src/main/java/io/deephaven/generic/region/AppendOnlyFixedSizePageRegionFloat.java
  extensions/source-support/src/main/java/io/deephaven/generic/region/AppendOnlyFixedSizePageRegionInt.java
  extensions/source-support/src/main/java/io/deephaven/generic/region/AppendOnlyFixedSizePageRegionLong.java
  extensions/source-support/src/main/java/io/deephaven/generic/region/AppendOnlyFixedSizePageRegionObject.java
  extensions/source-support/src/main/java/io/deephaven/generic/region/AppendOnlyFixedSizePageRegionShort.java
Labels: query engine, core, parquet, NoDocumentationNeeded, NoReleaseNotesNeeded

#5013 Fix pydeephaven-ticking package name and link
  py/client/docs/source/examples.rst
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5005 Python Client: avoid thread self-join on stop()
  py/client-ticking/src/pydeephaven_ticking/table_listener.py
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4986 Move OperationInitializer Construction to Dagger Object Graph
  Integrations/src/main/java/io/deephaven/integrations/python/PythonDeephavenSession.java
  engine/table/src/main/java/io/deephaven/engine/updategraph/impl/PeriodicUpdateGraph.java
  engine/table/src/main/java/io/deephaven/engine/util/AbstractScriptSession.java
  engine/table/src/main/java/io/deephaven/engine/util/GroovyDeephavenSession.java
  engine/table/src/main/java/io/deephaven/engine/util/NoLanguageDeephavenSession.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/FuzzerTest.java
  engine/table/src/test/java/io/deephaven/engine/util/scripts/TestGroovyDeephavenSession.java
  engine/test-utils/src/main/java/io/deephaven/engine/context/TestExecutionContext.java
  engine/test-utils/src/main/java/io/deephaven/engine/testutil/ControlledUpdateGraph.java
  py/server/test_helper/__init__.py
  server/src/main/java/io/deephaven/server/console/NoConsoleSessionModule.java
  server/src/main/java/io/deephaven/server/console/groovy/GroovyConsoleSessionModule.java
  server/src/main/java/io/deephaven/server/console/python/PythonConsoleSessionModule.java
  server/src/main/java/io/deephaven/server/runner/updategraph/UpdateGraphModule.java
  server/src/test/java/io/deephaven/server/appmode/ApplicationServiceGrpcImplTest.java
  server/src/test/java/io/deephaven/server/appmode/ApplicationTest.java
  server/test/src/main/java/io/deephaven/server/test/FlightMessageRoundTripTest.java
  sphinx/source/conf.py
Labels: configuration, core, NoDocumentationNeeded, NoReleaseNotesNeeded

#5018 Fix Server-Side ABORT That Should be CANCELLED
  server/src/main/java/io/deephaven/server/appmode/ApplicationServiceGrpcImpl.java
Labels: bug, core, test, NoDocumentationNeeded, NoReleaseNotesNeeded

#4927 docs: Add details about how to debug server
  README.md
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4985 Flight: Disable Batching Static Tables
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/BarrageUtil.java
  java-client/flight-dagger/src/test/java/io/deephaven/client/DeephavenFlightSessionTest.java
  web/client-api/src/main/java/io/deephaven/web/client/api/subscription/TableViewportSubscription.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4316 Log User-Friendly Error When AutoComplete is not Available
  server/src/main/java/io/deephaven/server/console/ConsoleServiceGrpcImpl.java
Labels: bug, py-autocomplete, NoDocumentationNeeded, NoReleaseNotesNeeded

#5025 Fix broken calendar unit tests over midnight.
  engine/time/src/main/java/io/deephaven/time/DateTimeUtils.java
  engine/time/src/test/java/io/deephaven/time/calendar/TestBusinessCalendar.java
  engine/time/src/test/java/io/deephaven/time/calendar/TestCalendar.java
Labels: bug, NoDocumentationNeeded, NoReleaseNotesNeeded

#5020 ReplayTable: Only Fail Table (not the server) on Error
  engine/table/src/main/java/io/deephaven/engine/table/impl/InstrumentedTableUpdateSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/InstrumentedUpdateSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/SourcePartitionedTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/SourceTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/TimeTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/replay/QueryReplayGroupedTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/replay/ReplayGroupedFullTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/replay/ReplayLastByGroupedTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/replay/ReplayTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/replay/ReplayTableBase.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/replay/Replayer.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/replay/ReplayerInterface.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/DelayedErrorNotifier.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/FunctionGeneratedTableFactory.java
  engine/table/src/main/java/io/deephaven/engine/updategraph/impl/BaseUpdateGraph.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/CapturingUpdateGraph.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/SourcePartitionedTableTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestPartitionAwareSourceTable.java
  engine/test-utils/src/main/java/io/deephaven/engine/testutil/testcase/RefreshingTableTestCase.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/table/BarrageTable.java
Labels: bug, core, NoDocumentationNeeded, ReleaseNotesNeeded

#5022 Add dependency on jpy>=0.15.0
  docker/registry/server-base/gradle.properties
  docker/server-jetty/src/main/server-jetty/requirements.txt
  docker/server/src/main/server-netty/requirements.txt
  py/server/setup.py
Labels: python, NoDocumentationNeeded, version-bump, ReleaseNotesNeeded

#4936 Share PyArrow table data with the server through ByteBuffer
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/ArrowToTableConverter.java
  py/server/deephaven/arrow.py
  py/server/tests/test_arrow.py
Labels: NoDocumentationNeeded, python-server-side, NoReleaseNotesNeeded

#5009 fix: Don't memoize retrieval of tables from JsPartitionedTable#getTable
  web/client-api/src/main/java/io/deephaven/web/client/api/JsPartitionedTable.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5034 Better error logging when calendars do not load properly
  engine/time/src/main/java/io/deephaven/time/calendar/BusinessCalendarXMLParser.java
  engine/time/src/main/java/io/deephaven/time/calendar/Calendars.java
Labels: bug, NoDocumentationNeeded, NoReleaseNotesNeeded

#5033 Support the use of 'from __future__ import annotations' in scripts where Python UDFs are defined.
  py/server/deephaven/_udf.py
Labels: NoDocumentationNeeded, python-server-side, NoReleaseNotesNeeded

#5038 BarrageTable: Use WritableRowRedirectionLockFree in Most Cases
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/WritableRowRedirection.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/table/BarrageBlinkTable.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/table/BarrageRedirectedTable.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/table/BarrageTable.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/BarrageUtil.java
  plugin/partitionedtable/src/main/java/io/deephaven/partitionedtable/PartitionedTableTypePlugin.java
  server/src/main/java/io/deephaven/server/arrow/ArrowFlightUtil.java
  server/src/main/java/io/deephaven/server/barrage/BarrageMessageProducer.java
Labels: bug, core, NoDocumentationNeeded, NoReleaseNotesNeeded

#5037 Move calendar initialization to server startup
  Integrations/build.gradle
  Plot/Plot.gradle
  Plot/src/test/java/io/deephaven/plot/axistransformations/TestAxisTransformBusinessCalendar.java
  Plot/src/test/java/io/deephaven/plot/axistransformations/TestAxisTransforms.java
  engine/time/build.gradle
  engine/time/src/main/java/io/deephaven/time/calendar/BusinessCalendar.java
  engine/time/src/main/java/io/deephaven/time/calendar/BusinessCalendarXMLParser.java
  engine/time/src/main/java/io/deephaven/time/calendar/Calendars.java
  engine/time/src/main/java/io/deephaven/time/calendar/CalendarsFromConfigurationModule.java
  engine/time/src/test/java/io/deephaven/time/calendar/CalendarInit.java
  engine/time/src/test/java/io/deephaven/time/calendar/TestCalendars.java
  engine/time/src/test/java/io/deephaven/time/calendar/TestStaticCalendarMethods.java
  py/embedded-server/java-runtime/src/main/java/io/deephaven/python/server/EmbeddedServer.java
  py/server/tests/test_calendar.py
  server/src/main/java/io/deephaven/server/runner/CommunityDefaultsModule.java
  server/src/main/java/io/deephaven/server/runner/DeephavenApiServer.java
  server/src/test/java/io/deephaven/server/runner/DeephavenApiServerTestBase.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5046 Fix a few additional failing calendar tests
  engine/table/build.gradle
  engine/table/src/test/java/io/deephaven/engine/table/impl/FuzzerTest.java
  engine/table/src/test/java/io/deephaven/engine/util/TestCalendarMethodsFromTable.java
Labels: bug, test, NoDocumentationNeeded, NoReleaseNotesNeeded

#5047 BarrageTable: Fix testCoalescingLargeUpdates out-of-memory
  server/src/test/java/io/deephaven/server/barrage/BarrageMessageRoundTripTest.java
Labels: core, test, NoDocumentationNeeded, NoReleaseNotesNeeded

#4988 Run JS API unit tests and integration tests in the Gradle build
  buildSrc/src/main/groovy/GwtTools.groovy
  docker/registry/selenium/build.gradle
  docker/registry/selenium/gradle.properties
  gradle/web-gwt-test.gradle
  web/client-api/client-api.gradle
  web/client-api/src/main/java/io/deephaven/web/client/api/JsTable.java
  web/client-api/src/test/java/io/deephaven/web/ClientIntegrationTestSuite.java
  web/client-api/src/test/java/io/deephaven/web/ClientUnitTestSuite.java
  web/client-api/src/test/java/io/deephaven/web/DeephavenIntegrationTest.gwt.xml
  web/client-api/src/test/java/io/deephaven/web/DeephavenUnitTest.gwt.xml
  web/client-api/src/test/java/io/deephaven/web/client/api/AbstractAsyncGwtTestCase.java
  web/client-api/src/test/java/io/deephaven/web/client/api/JsPredicate.java
  web/client-api/src/test/java/io/deephaven/web/client/api/NullValueTestGwt.java
  web/client-api/src/test/java/io/deephaven/web/client/api/TableManipulationTestGwt.java
  web/client-api/src/test/java/io/deephaven/web/client/api/TotalsTableTestGwt.java
  web/client-api/src/test/java/io/deephaven/web/client/api/filter/FilterConditionTestGwt.java
  web/client-api/src/test/java/io/deephaven/web/client/api/i18n/JsDateTimeFormatTestGwt.java
  web/client-api/src/test/java/io/deephaven/web/client/api/i18n/JsNumberFormatTestGwt.java
  web/client-api/src/test/java/io/deephaven/web/client/api/subscription/ConcurrentTableTestGwt.java
  web/client-api/src/test/java/io/deephaven/web/client/api/subscription/ViewportTestGwt.java
  web/client-api/src/test/java/io/deephaven/web/junit/RunStyleRemoteWebDriver.java
Labels: build, test, NoDocumentationNeeded, NoReleaseNotesNeeded

#5049 Post release bump to 0.33.0
  R/rdeephaven/DESCRIPTION
  gradle.properties
  web/client-api/types/package.json
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4999 JS API should expose if a table is refreshing
  cpp-client/deephaven/dhclient/proto/deephaven/proto/hierarchicaltable.pb.cc
  cpp-client/deephaven/dhclient/proto/deephaven/proto/hierarchicaltable.pb.h
  go/internal/proto/hierarchicaltable/hierarchicaltable.pb.go
  plugin/hierarchicaltable/src/main/java/io/deephaven/hierarchicaltable/HierarchicalTableTypePlugin.java
  proto/proto-backplane-grpc/src/main/proto/deephaven/proto/hierarchicaltable.proto
  py/client/pydeephaven/proto/hierarchicaltable_pb2.py
  web/client-api/src/main/java/io/deephaven/web/client/api/JsTable.java
  web/client-api/src/main/java/io/deephaven/web/client/api/JsTotalsTable.java
  web/client-api/src/main/java/io/deephaven/web/client/api/tree/JsTreeTable.java
  web/client-api/src/main/java/io/deephaven/web/client/state/ClientTableState.java
  web/client-api/src/test/java/io/deephaven/web/ClientIntegrationTestSuite.java
  web/client-api/src/test/java/io/deephaven/web/client/api/AbstractAsyncGwtTestCase.java
  web/client-api/src/test/java/io/deephaven/web/client/api/HierarchicalTableTestGwt.java
  web/client-api/src/test/java/io/deephaven/web/client/api/NullValueTestGwt.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven/proto/hierarchicaltable_pb/HierarchicalTableDescriptor.java
Labels: jsapi, grpc, NoDocumentationNeeded, ReleaseNotesNeeded

#5048 Eliminate Double Error Notifications in jsapi and Error Log
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/GrpcUtil.java
  server/src/main/java/io/deephaven/server/barrage/BarrageMessageProducer.java
  server/src/main/java/io/deephaven/server/session/SessionService.java
  server/src/main/java/io/deephaven/server/table/ExportedTableUpdateListener.java
  server/src/main/java/io/deephaven/server/table/ops/TableServiceGrpcImpl.java
  server/src/test/java/io/deephaven/server/session/SessionServiceTest.java
  server/src/test/java/io/deephaven/server/table/ExportTableUpdateListenerTest.java
  web/client-api/src/main/java/io/deephaven/web/client/api/HasEventHandling.java
  web/client-api/src/main/java/io/deephaven/web/client/api/WorkerConnection.java
  web/client-api/src/main/java/io/deephaven/web/client/api/barrage/stream/ResponseStreamWrapper.java
  web/client-api/src/main/java/io/deephaven/web/client/state/ClientTableState.java
Labels: bug, core, NoDocumentationNeeded, authorization, ReleaseNotesNeeded

#5057 Increase GWT test timeouts to avoid CI timeouts
  web/client-api/src/test/java/io/deephaven/web/client/api/HierarchicalTableTestGwt.java
  web/client-api/src/test/java/io/deephaven/web/client/api/TableManipulationTestGwt.java
  web/client-api/src/test/java/io/deephaven/web/client/api/subscription/ViewportTestGwt.java
Labels: test, NoDocumentationNeeded, NoReleaseNotesNeeded

#5053 Chunk pools should be easier to emulate in GWT
  engine/chunk/src/main/java/io/deephaven/chunk/ResettableBooleanChunk.java
  engine/chunk/src/main/java/io/deephaven/chunk/ResettableByteChunk.java
  engine/chunk/src/main/java/io/deephaven/chunk/ResettableCharChunk.java
  engine/chunk/src/main/java/io/deephaven/chunk/ResettableDoubleChunk.java
  engine/chunk/src/main/java/io/deephaven/chunk/ResettableFloatChunk.java
  engine/chunk/src/main/java/io/deephaven/chunk/ResettableIntChunk.java
  engine/chunk/src/main/java/io/deephaven/chunk/ResettableLongChunk.java
  engine/chunk/src/main/java/io/deephaven/chunk/ResettableObjectChunk.java
  engine/chunk/src/main/java/io/deephaven/chunk/ResettableShortChunk.java
  engine/chunk/src/main/java/io/deephaven/chunk/ResettableWritableBooleanChunk.java
  engine/chunk/src/main/java/io/deephaven/chunk/ResettableWritableByteChunk.java
  engine/chunk/src/main/java/io/deephaven/chunk/ResettableWritableCharChunk.java
  engine/chunk/src/main/java/io/deephaven/chunk/ResettableWritableDoubleChunk.java
  engine/chunk/src/main/java/io/deephaven/chunk/ResettableWritableFloatChunk.java
  engine/chunk/src/main/java/io/deephaven/chunk/ResettableWritableIntChunk.java
  engine/chunk/src/main/java/io/deephaven/chunk/ResettableWritableLongChunk.java
  engine/chunk/src/main/java/io/deephaven/chunk/ResettableWritableObjectChunk.java
  engine/chunk/src/main/java/io/deephaven/chunk/ResettableWritableShortChunk.java
  engine/chunk/src/main/java/io/deephaven/chunk/WritableBooleanChunk.java
  engine/chunk/src/main/java/io/deephaven/chunk/WritableByteChunk.java
  engine/chunk/src/main/java/io/deephaven/chunk/WritableCharChunk.java
  engine/chunk/src/main/java/io/deephaven/chunk/WritableDoubleChunk.java
  engine/chunk/src/main/java/io/deephaven/chunk/WritableFloatChunk.java
  engine/chunk/src/main/java/io/deephaven/chunk/WritableIntChunk.java
  engine/chunk/src/main/java/io/deephaven/chunk/WritableLongChunk.java
  engine/chunk/src/main/java/io/deephaven/chunk/WritableObjectChunk.java
  engine/chunk/src/main/java/io/deephaven/chunk/WritableShortChunk.java
  engine/chunk/src/main/java/io/deephaven/chunk/util/pools/BooleanChunkPool.java
  engine/chunk/src/main/java/io/deephaven/chunk/util/pools/BooleanChunkSoftPool.java
  engine/chunk/src/main/java/io/deephaven/chunk/util/pools/ByteChunkPool.java
  engine/chunk/src/main/java/io/deephaven/chunk/util/pools/ByteChunkSoftPool.java
  engine/chunk/src/main/java/io/deephaven/chunk/util/pools/CharChunkPool.java
  engine/chunk/src/main/java/io/deephaven/chunk/util/pools/CharChunkSoftPool.java
  engine/chunk/src/main/java/io/deephaven/chunk/util/pools/DoubleChunkPool.java
  engine/chunk/src/main/java/io/deephaven/chunk/util/pools/DoubleChunkSoftPool.java
  engine/chunk/src/main/java/io/deephaven/chunk/util/pools/FloatChunkPool.java
  engine/chunk/src/main/java/io/deephaven/chunk/util/pools/FloatChunkSoftPool.java
  engine/chunk/src/main/java/io/deephaven/chunk/util/pools/IntChunkPool.java
  engine/chunk/src/main/java/io/deephaven/chunk/util/pools/IntChunkSoftPool.java
  engine/chunk/src/main/java/io/deephaven/chunk/util/pools/LongChunkPool.java
  engine/chunk/src/main/java/io/deephaven/chunk/util/pools/LongChunkSoftPool.java
  engine/chunk/src/main/java/io/deephaven/chunk/util/pools/MultiChunkPool.java
  engine/chunk/src/main/java/io/deephaven/chunk/util/pools/ObjectChunkPool.java
  engine/chunk/src/main/java/io/deephaven/chunk/util/pools/ObjectChunkSoftPool.java
  engine/chunk/src/main/java/io/deephaven/chunk/util/pools/ShortChunkPool.java
  engine/chunk/src/main/java/io/deephaven/chunk/util/pools/ShortChunkSoftPool.java
  replication/static/src/main/java/io/deephaven/replicators/ReplicateSourcesAndChunks.java
Labels: jsapi, NoDocumentationNeeded, NoReleaseNotesNeeded

#4970 Extract variable api from ScriptSession, let ScriptSession guard reads
  Integrations/src/main/java/io/deephaven/integrations/python/PythonDeephavenSession.java
  engine/context/src/main/java/io/deephaven/engine/context/EmptyQueryScope.java
  engine/context/src/main/java/io/deephaven/engine/context/ExecutionContext.java
  engine/context/src/main/java/io/deephaven/engine/context/PoisonedQueryScope.java
  engine/context/src/main/java/io/deephaven/engine/context/QueryScope.java
  engine/context/src/main/java/io/deephaven/engine/context/StandaloneQueryScope.java
  engine/sql/src/main/java/io/deephaven/engine/sql/Sql.java
  engine/table/src/main/java/io/deephaven/engine/util/AbstractScriptSession.java
  engine/table/src/main/java/io/deephaven/engine/util/DelegatingScriptSession.java
  engine/table/src/main/java/io/deephaven/engine/util/GroovyDeephavenSession.java
  engine/table/src/main/java/io/deephaven/engine/util/NoLanguageDeephavenSession.java
  engine/table/src/main/java/io/deephaven/engine/util/ScriptSession.java
  engine/table/src/main/java/io/deephaven/engine/util/VariableProvider.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/FuzzerTest.java
  engine/table/src/test/java/io/deephaven/engine/util/scripts/TestGroovyDeephavenSession.java
  java-client/session-dagger/src/test/java/io/deephaven/client/ObjectServiceTest.java
  open-api/lang-tools/src/main/java/io/deephaven/lang/completion/ChunkerCompleter.java
  open-api/lang-tools/src/main/java/io/deephaven/lang/completion/CompletionRequest.java
  open-api/lang-tools/src/test/groovy/io/deephaven/lang/completion/ChunkerCompleterMixin.groovy
  open-api/lang-tools/src/test/groovy/io/deephaven/lang/completion/ChunkerCompletionHandlerTest.groovy
  open-api/lang-tools/src/test/groovy/io/deephaven/lang/completion/ChunkerGroovyTest.groovy
  open-api/lang-tools/src/test/groovy/io/deephaven/lang/completion/ChunkerParseTestMixin.groovy
  open-api/lang-tools/src/test/groovy/io/deephaven/lang/completion/ChunkerParserTest.groovy
  open-api/lang-tools/src/test/groovy/io/deephaven/lang/completion/ChunkerPythonTest.groovy
  open-api/lang-tools/src/test/groovy/io/deephaven/lang/completion/ColumnExpressionCompletionHandlerTest.groovy
  server/src/main/java/io/deephaven/server/console/ConsoleServiceGrpcImpl.java
  server/src/main/java/io/deephaven/server/console/ScopeTicketResolver.java
  server/src/main/java/io/deephaven/server/console/completer/JavaAutoCompleteObserver.java
  server/src/main/java/io/deephaven/server/console/completer/PythonAutoCompleteObserver.java
  server/src/main/java/io/deephaven/server/uri/QueryScopeResolver.java
  server/src/test/java/io/deephaven/server/appmode/ApplicationServiceGrpcImplTest.java
  server/src/test/java/io/deephaven/server/appmode/ApplicationTest.java
  server/src/test/java/io/deephaven/server/runner/DeephavenApiServerTestBase.java
  server/test/src/main/java/io/deephaven/server/test/FlightMessageRoundTripTest.java
Labels: NoDocumentationNeeded, python-server-side, groovy, ReleaseNotesNeeded

#5059 Go Client: Rewrite TestAsOfJoinQuery in query_test.go
  go/pkg/client/query_test.go
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5032 Re-implement `ParallelWhere` using `JobScheduler` semantics.
  engine/table/src/main/java/io/deephaven/engine/table/impl/AbstractFilterExecution.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/InitialFilterExecution.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/WhereListener.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/ConditionFilter.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableWhereTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestListenerFailure.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5072 Add a local copy of build-dependencies.sh for cpp-client, and add a PR check that is kept up to date.
  cpp-client/README.md
  cpp-client/build-dependencies.sh
  cpp-client/build.gradle
  docker/registry/cpp-clients-multi-base/gradle.properties
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5074 Fix `Where` performance regression
  engine/table/src/main/java/io/deephaven/engine/table/impl/AbstractFilterExecution.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5077 Use a Deque to avoid StackOverflow in ImmediateJobScheduler
  engine/table/src/main/java/io/deephaven/engine/table/impl/InitialFilterExecution.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/SelectOrUpdateListener.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/WhereListener.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/rangejoin/RangeJoinOperation.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/UpdateBy.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/ImmediateJobScheduler.java
Labels: core, NoDocumentationNeeded, NoReleaseNotesNeeded

#5092 Fixed a parquet python module failure when s3 extension is not included
  py/server/deephaven/experimental/s3.py
Labels: bug, parquet, NoDocumentationNeeded, NoReleaseNotesNeeded, s3

#5089 Fix ReadableByteChannel.read usages
  extensions/arrow/src/main/java/io/deephaven/extensions/arrow/ArrowWrapperTools.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/ColumnPageReaderImpl.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/ParquetFileReader.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/util/Helpers.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded
