Repository deephaven/deephaven-core, pull requests merged in 2024-11, with the labels that each got.

#6316 fix: Support reading partitioned parquet from S3 bucket root URI
  Base/src/main/java/io/deephaven/base/FileUtils.java
  Base/src/test/java/io/deephaven/base/FileUtilsTest.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/S3ParquetTestBase.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3SeekableChannelProvider.java
Labels: bug, parquet, NoDocumentationNeeded, ReleaseNotesNeeded, s3

#6175 feat: a new PartitionedTableService API in Python
  engine/base/src/main/java/io/deephaven/engine/table/impl/chunkboxer/ChunkBoxer.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/SourceTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/locations/TableLocation.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/locations/TableLocationProvider.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/locations/impl/TableLocationSubscriptionBuffer.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/locations/impl/TableLocationUpdateSubscriptionBuffer.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/RegionedColumnSourceManager.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestPartitionAwareSourceTable.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/sources/regioned/TestRegionedColumnSourceManager.java
  extensions/barrage/build.gradle
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/ArrowToTableConverter.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/BarrageUtil.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/PythonTableDataService.java
  py/server/deephaven/experimental/table_data_service.py
  py/server/tests/test_table_data_service.py
  server/src/main/java/io/deephaven/server/arrow/ArrowFlightUtil.java
Labels: DocumentationNeeded, python-server-side, ReleaseNotesNeeded

#6318 fix(go): Disable Example_runScript for now because it breaks nightlies
  go/pkg/client/example_run_script_test.go
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6319 fix(cpp-client): Add comments, fix typos, correct parameter names
  cpp-client/deephaven/dhclient/include/public/deephaven/client/client.h
  cpp-client/deephaven/dhclient/include/public/deephaven/client/client_options.h
  cpp-client/deephaven/dhcore/include/private/deephaven/dhcore/ticking/immer_table_state.h
  cpp-client/deephaven/dhcore/include/private/deephaven/dhcore/ticking/space_mapper.h
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/clienttable/client_table.h
  cpp-client/deephaven/dhcore/src/ticking/barrage_processor.cc
  cpp-client/deephaven/dhcore/src/ticking/immer_table_state.cc
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6329 chore: Update nightly slack job step
  .github/workflows/nightly-check-ci.yml
Labels: ci, NoDocumentationNeeded, NoReleaseNotesNeeded

#6331 revert: "fix(go): Disable Example_runScript for now because it breaks nightlies (#6318)"
  go/pkg/client/example_run_script_test.go
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6332 revert: Roll back jetty upgrade, back to 11.0.20 from 11.0.24
  gradle/libs.versions.toml
Labels: NoDocumentationNeeded, jetty, dependencies, NoReleaseNotesNeeded

#6335 test: Increased timeout for S3 unit tests
  extensions/iceberg/s3/src/test/java/io/deephaven/iceberg/util/S3WarehouseSqliteCatalogBase.java
  extensions/s3/src/test/java/io/deephaven/extensions/s3/testlib/S3Helper.java
  extensions/s3/src/test/java/io/deephaven/extensions/s3/testlib/S3SeekableChannelTestSetup.java
Labels: test, NoDocumentationNeeded, NoReleaseNotesNeeded, s3

#6336 chore: Only run linkChecker job on Deephaven repository
  .github/workflows/links.yml
Labels: ci, NoDocumentationNeeded, NoReleaseNotesNeeded

#6334 fix: Alows clients to expect that query performance results have been logged before they receive a response
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/GrpcUtil.java
  server/src/main/java/io/deephaven/server/arrow/ArrowFlightUtil.java
  server/src/main/java/io/deephaven/server/arrow/FlightServiceGrpcImpl.java
  server/src/main/java/io/deephaven/server/console/ConsoleServiceGrpcImpl.java
  server/src/main/java/io/deephaven/server/hierarchicaltable/HierarchicalTableServiceGrpcImpl.java
  server/src/main/java/io/deephaven/server/object/ObjectServiceGrpcImpl.java
  server/src/main/java/io/deephaven/server/partitionedtable/PartitionedTableServiceGrpcImpl.java
  server/src/main/java/io/deephaven/server/session/SessionService.java
  server/src/main/java/io/deephaven/server/session/SessionServiceGrpcImpl.java
  server/src/main/java/io/deephaven/server/session/SessionState.java
  server/src/main/java/io/deephaven/server/table/inputtables/InputTableServiceGrpcImpl.java
  server/src/main/java/io/deephaven/server/table/ops/TableServiceGrpcImpl.java
Labels: grpc, NoDocumentationNeeded, session, ReleaseNotesNeeded, point_release_candidate

#6338 refactor: make utility classes UnboxTransform and ToChunkTypeTransform public
  Util/function/build.gradle
  Util/function/src/main/java/io/deephaven/function/UnboxTransform.java
  extensions/kafka/src/main/java/io/deephaven/kafka/ProtobufImpl.java
  extensions/protobuf/build.gradle
  extensions/protobuf/src/main/java/io/deephaven/function/ToChunkTypeTransform.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6342 docs: Remove old web developer guide
  web/WebDevelopersGuide.md
Labels: documentation, jsapi, NoDocumentationNeeded, NoReleaseNotesNeeded

#5617 refactor: Deleted legacy snapshot logic
  engine/table/src/main/java/io/deephaven/engine/table/impl/remote/ConstructSnapshot.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/remote/DeltaUpdates.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/remote/InitialSnapshot.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/remote/InitialSnapshotTable.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/SnapshotTestUtils.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/remote/TestConstructSnapshot.java
  extensions/arrow/src/test/java/io/deephaven/extensions/arrow/ArrowWrapperToolsTest.java
Labels: NoDocumentationNeeded, breaking, ReleaseNotesNeeded

#6348 chore: bump jpy to 0.19.0
  docker/registry/server-base/gradle.properties
  docker/registry/slim-base/gradle.properties
  docker/server-jetty/src/main/server-jetty/requirements.txt
  docker/server/src/main/server-netty/requirements.txt
  gradle/libs.versions.toml
  py/embedded-server/setup.py
  py/server/setup.py
Labels: python, NoDocumentationNeeded, jpy, version-bump, ReleaseNotesNeeded

#6346 feat: Enable unique values in column statistics calls from JS
  web/client-api/src/main/java/io/deephaven/web/client/api/JsColumnStatistics.java
  web/client-api/src/main/java/io/deephaven/web/client/api/JsTable.java
  web/client-api/src/test/java/io/deephaven/web/ClientIntegrationTestSuite.java
  web/client-api/src/test/java/io/deephaven/web/client/api/ColumnStatisticsTestGwt.java
Labels: jsapi, NoDocumentationNeeded, ReleaseNotesNeeded

#6301 chore: Update gRPC to 1.65.1
  gradle/libs.versions.toml
  grpc-java/grpc-servlet-jakarta/src/main/java/io/grpc/servlet/jakarta/AsyncServletOutputStreamWriter.java
  grpc-java/grpc-servlet-jakarta/src/main/java/io/grpc/servlet/jakarta/GrpcServlet.java
  grpc-java/grpc-servlet-jakarta/src/main/java/io/grpc/servlet/jakarta/ServletAdapter.java
  grpc-java/grpc-servlet-jakarta/src/main/java/io/grpc/servlet/jakarta/ServletServerBuilder.java
  grpc-java/grpc-servlet-jakarta/src/main/java/io/grpc/servlet/jakarta/ServletServerStream.java
  grpc-java/grpc-servlet-websocket-jakarta/src/main/java/io/grpc/servlet/web/websocket/MultiplexedWebsocketStreamImpl.java
  grpc-java/grpc-servlet-websocket-jakarta/src/main/java/io/grpc/servlet/web/websocket/WebsocketStreamImpl.java
  java-client/session/build.gradle
  server/test-utils/build.gradle
Labels: grpc, NoDocumentationNeeded, version-bump, ReleaseNotesNeeded

#6344 chore: Update .lycheeignore
  .lycheeignore
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6317 fix: Deprecate and stop firing JS token refresh event
  web/client-api/src/main/java/io/deephaven/web/client/api/CoreClient.java
  web/client-api/src/main/java/io/deephaven/web/client/api/WorkerConnection.java
  web/client-api/src/main/java/io/deephaven/web/client/ide/IdeConnection.java
Labels: jsapi, NoDocumentationNeeded, ReleaseNotesNeeded

#6350 chore: Update TableReference protobuf documentation
  go/internal/proto/table/table.pb.go
  proto/proto-backplane-grpc/src/main/proto/deephaven/proto/table.proto
Labels: documentation, NoDocumentationNeeded, NoReleaseNotesNeeded

#6360 fix: Static aggregations when a data index uses different names for the key columns should remap names correctly
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/ChunkedOperatorAggregationHelper.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableAggregationTest.java
Labels: query engine, core, NoDocumentationNeeded, ReleaseNotesNeeded, point_release_candidate

#6340 chore: Bump the compiler, runtime, and test runtime version to Java 21
  buildSrc/src/main/groovy/io.deephaven.java-open-nio.gradle
  buildSrc/src/main/groovy/io.deephaven.java-toolchain-conventions.gradle
  clock-impl/build.gradle
  clock-impl/src/test/java/io/deephaven/base/clock/SystemClockJdkInternalMiscVmTest.java
  clock-impl/src/test/java/io/deephaven/base/clock/SystemClockTest.java
  hotspot-impl/build.gradle
  hotspot-impl/src/test/java/io/deephaven/hotspot/HotSpotTest.java
  hotspot-impl/src/test/java/io/deephaven/hotspot/impl/HotSpotImplTest.java
Labels: build, NoDocumentationNeeded, NoReleaseNotesNeeded

#6366 fix: Address a number of liveness-related issues
  engine/table/src/main/java/io/deephaven/engine/table/impl/AddOnlyToBlinkTableAdapter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/AsOfJoinHelper.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/BaseTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/InstrumentedTableUpdateListenerAdapter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/ListenerRecorder.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/MergedListener.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/ShiftObliviousInstrumentedListenerAdapter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/SourcePartitionedTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/SourceTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/TimeTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/UpdatableTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/UpdateSourceQueryTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/asofjoin/BucketedChunkedAjMergedListener.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/hierarchical/HierarchicalTableImpl.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/locations/TableLocationProvider.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/locations/impl/AbstractTableLocation.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/locations/impl/AbstractTableLocationProvider.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/BaseIncrementalReleaseFilter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/ClockFilter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/RollingReleaseFilter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/FunctionGeneratedTableFactory.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/HashSetBackedTableFactory.java
  engine/table/src/main/java/io/deephaven/engine/util/AbstractScriptSession.java
  engine/table/src/main/java/io/deephaven/engine/util/WindowCheck.java
  engine/table/src/main/java/io/deephaven/stream/StreamToBlinkTableAdapter.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableAjTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestPartitionAwareSourceTable.java
  engine/test-utils/src/main/java/io/deephaven/engine/testutil/EvalNuggetSet.java
  engine/test-utils/src/main/java/io/deephaven/engine/testutil/TstUtils.java
  engine/updategraph/src/main/java/io/deephaven/engine/liveness/DelegatingLivenessReferent.java
  engine/updategraph/src/main/java/io/deephaven/engine/liveness/LivenessScopeStack.java
  engine/updategraph/src/main/java/io/deephaven/engine/liveness/ReferenceCountedLivenessNode.java
  engine/updategraph/src/main/java/io/deephaven/engine/liveness/ReferenceCountedLivenessReferent.java
  engine/updategraph/src/main/java/io/deephaven/engine/liveness/RetainedReferenceTracker.java
  engine/updategraph/src/main/java/io/deephaven/engine/updategraph/UpdateSourceCombiner.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/table/BarrageTable.java
  extensions/kafka/src/main/java/io/deephaven/kafka/publish/PublishToKafka.java
  java-client/barrage-examples/src/main/java/io/deephaven/client/examples/SubscribeExampleBase.java
  java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshotImpl.java
  java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java
  server/src/main/java/io/deephaven/server/barrage/BarrageMessageProducer.java
  server/src/main/java/io/deephaven/server/hierarchicaltable/HierarchicalTableViewSubscription.java
  server/src/main/java/io/deephaven/server/plugin/python/LivePyObjectWrapper.java
  server/src/main/java/io/deephaven/server/session/SessionState.java
  server/src/main/java/io/deephaven/server/table/ExportedTableUpdateListener.java
Labels: bug, query engine, core, DocumentationNeeded, ReleaseNotesNeeded

#6371 fix!: ensure Iceberg layouts own the SeekableChannelsProvider
  Util/channel/src/main/java/io/deephaven/util/channel/SeekableChannelsProviderLoader.java
  Util/channel/src/main/java/io/deephaven/util/channel/SeekableChannelsProviderPlugin.java
  extensions/iceberg/s3/src/main/java/io/deephaven/iceberg/util/S3InstructionsProviderPlugin.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/internal/DataInstructionsProviderLoader.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/internal/DataInstructionsProviderPlugin.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/layout/IcebergBaseLayout.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/location/IcebergTableParquetLocationKey.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/ParquetTools.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/layout/DeephavenNestedPartitionLayout.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/layout/ParquetFlatPartitionedLayout.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/layout/ParquetKeyValuePartitionedLayout.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/layout/ParquetMetadataFileLayout.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/location/ParquetTableLocationKey.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/GCSSeekableChannelProviderPlugin.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3SeekableChannelProviderPlugin.java
  extensions/s3/src/test/java/io/deephaven/extensions/s3/S3SeekableChannelSimpleTestBase.java
  extensions/s3/src/test/java/io/deephaven/extensions/s3/testlib/S3SeekableChannelTestSetup.java
  extensions/trackedfile/src/main/java/io/deephaven/extensions/trackedfile/TrackedSeekableChannelsProviderPlugin.java
Labels: NoDocumentationNeeded, breaking, ReleaseNotesNeeded

#6373 refactor: Removed out some unused Parquet APIs
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/MappedSchema.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/ParquetInstructions.java
Labels: parquet, NoDocumentationNeeded, breaking, NoReleaseNotesNeeded

#6347 feat: Simplify Barrage Viewport Table Updates
  engine/rowset/src/main/java/io/deephaven/engine/rowset/RowSetShiftData.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/FlattenOperation.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/remote/ConstructSnapshot.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/BarrageMessage.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/BarrageSnapshotOptions.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/BarrageStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/BarrageStreamGeneratorImpl.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/BarrageSubscriptionOptions.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/DefaultChunkReadingFactory.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/table/BarrageRedirectedTable.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/table/BarrageTable.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/ArrowToTableConverter.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/BarrageStreamReader.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/StreamReaderOptions.java
  gradle/libs.versions.toml
  java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshotImpl.java
  java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java
  java-client/flight-examples/src/main/java/io/deephaven/client/examples/DoExchange.java
  java-client/flight/build.gradle
  server/src/main/java/io/deephaven/server/barrage/BarrageMessageProducer.java
  server/src/main/java/io/deephaven/server/hierarchicaltable/HierarchicalTableViewSubscription.java
  server/src/test/java/io/deephaven/server/barrage/BarrageBlinkTableTest.java
  server/src/test/java/io/deephaven/server/barrage/BarrageMessageRoundTripTest.java
  server/test-utils/src/main/java/io/deephaven/server/test/FlightMessageRoundTripTest.java
  web/client-api/src/main/java/io/deephaven/web/client/api/barrage/WebBarrageMessage.java
  web/client-api/src/main/java/io/deephaven/web/client/api/barrage/WebBarrageStreamReader.java
  web/client-api/src/main/java/io/deephaven/web/client/api/barrage/data/WebBarrageSubscription.java
  web/client-api/src/main/java/io/deephaven/web/client/api/barrage/data/WebByteColumnData.java
  web/client-api/src/main/java/io/deephaven/web/client/api/barrage/data/WebCharColumnData.java
  web/client-api/src/main/java/io/deephaven/web/client/api/barrage/data/WebColumnData.java
  web/client-api/src/main/java/io/deephaven/web/client/api/barrage/data/WebDoubleColumnData.java
  web/client-api/src/main/java/io/deephaven/web/client/api/barrage/data/WebFloatColumnData.java
  web/client-api/src/main/java/io/deephaven/web/client/api/barrage/data/WebIntColumnData.java
  web/client-api/src/main/java/io/deephaven/web/client/api/barrage/data/WebLongColumnData.java
  web/client-api/src/main/java/io/deephaven/web/client/api/barrage/data/WebObjectColumnData.java
  web/client-api/src/main/java/io/deephaven/web/client/api/barrage/data/WebShortColumnData.java
  web/client-api/src/main/java/io/deephaven/web/client/api/subscription/AbstractTableSubscription.java
  web/client-api/src/main/java/io/deephaven/web/client/api/subscription/SubscriptionType.java
  web/client-api/src/main/java/io/deephaven/web/client/api/subscription/TableSubscription.java
  web/client-api/src/main/java/io/deephaven/web/client/api/subscription/TableViewportSubscription.java
  web/client-api/src/main/java/io/deephaven/web/client/api/tree/JsTreeTable.java
  web/shared-beans/src/main/java/io/deephaven/web/shared/data/RangeSet.java
Labels: jsapi, barrage, core, DocumentationNeeded, barrage-wrkr2wrkr, ReleaseNotesNeeded

#6375 feat!: provide key columns as scalars (vs. vectors) to `RollingFormula`
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/BucketedPartitionedUpdateByManager.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/UpdateByBucketHelper.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/UpdateByOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/UpdateByOperatorFactory.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/UpdateByWindow.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/UpdateByWindowCumulative.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/UpdateByWindowRollingBase.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/UpdateByWindowRollingTicks.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/UpdateByWindowRollingTime.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/ZeroKeyUpdateByManager.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/rollingformulamulticolumn/RollingFormulaMultiColumnOperator.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestRollingFormula.java
Labels: DocumentationNeeded, ReleaseNotesNeeded

#6391 fix: Use correct naming conventions for Parquet list
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/MappedSchema.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/TypeInfos.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/MappedSchemaTest.java
Labels: parquet, NoDocumentationNeeded, ReleaseNotesNeeded

#6381 feat: Add Parquet field_id writing
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/ColumnWriterImpl.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/MappedSchema.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/ParquetInstructions.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/TypeInfos.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/ParquetInstructionsTest.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/TestParquetTools.java
  extensions/parquet/table/src/test/resources/NestedStruct1.parquet
  extensions/parquet/table/src/test/resources/NestedStruct2.parquet
  extensions/parquet/table/src/test/resources/ReferenceListParquetFieldIds.parquet
  extensions/parquet/table/src/test/resources/ReferencePartitionedFieldIds/Partition=0/table.parquet
  extensions/parquet/table/src/test/resources/ReferencePartitionedFieldIds/Partition=1/table.parquet
  extensions/parquet/table/src/test/resources/ReferenceSimpleParquetFieldIds.parquet
Labels: parquet, NoDocumentationNeeded, NoReleaseNotesNeeded

#6399 fix: Use the string representation of a Python UDF as its name when it doesn't have the __name__ attribute
  engine/table/src/main/java/io/deephaven/engine/util/PyCallableWrapperJpyImpl.java
  py/server/tests/test_udf_scalar_args.py
Labels: NoDocumentationNeeded, python-server-side, ReleaseNotesNeeded

#6398 fix: Expanding hierarchical rows should account for viewport position
  web/client-api/src/main/java/io/deephaven/web/client/api/tree/JsTreeTable.java
  web/client-api/src/test/java/io/deephaven/web/client/api/HierarchicalTableTestGwt.java
Labels: bug, jsapi, NoDocumentationNeeded, release blocker, ReleaseNotesNeeded, hierarchical_tables

#6341 feat: Ensure data read order reflects commit sequence in Iceberg tables
  engine/table/src/main/java/io/deephaven/engine/table/impl/locations/TableLocationKey.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/locations/impl/PartitionedTableLocationKey.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/locations/impl/StandaloneTableLocationKey.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/locations/local/FileTableLocationKey.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/locations/local/URITableLocationKey.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/locations/impl/SimpleTableLocationKey.java
  engine/test-utils/src/main/java/io/deephaven/engine/testutil/locations/TableBackedTableLocationKey.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/PythonTableDataService.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/layout/IcebergBaseLayout.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/layout/IcebergFlatLayout.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/layout/IcebergKeyValuePartitionedLayout.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/location/IcebergTableParquetLocationKey.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/location/TableIdentifierComparator.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/IcebergCatalogAdapter.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/IcebergTableAdapter.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/IcebergUpdateMode.java
Labels: feature request, NoDocumentationNeeded, ReleaseNotesNeeded, iceberg

#6378 feat(csharp): A Windows Installer for the Deephaven Excel Add-In
  csharp/.gitignore
  csharp/ExcelAddIn/ExcelAddIn.csproj
  csharp/ExcelAddInInstaller/.gitignore
  csharp/ExcelAddInInstaller/CustomActions/CustomActions.cs
  csharp/ExcelAddInInstaller/CustomActions/CustomActions.csproj
  csharp/ExcelAddInInstaller/CustomActions/CustomActions.sln
  csharp/ExcelAddInInstaller/CustomActions/MsiSession.cs
  csharp/ExcelAddInInstaller/CustomActions/Properties/AssemblyInfo.cs
  csharp/ExcelAddInInstaller/CustomActions/README.md
  csharp/ExcelAddInInstaller/CustomActions/RegistryKeys.cs
  csharp/ExcelAddInInstaller/CustomActions/RegistryManager.cs
  csharp/ExcelAddInInstaller/ExcelAddInInstaller.aip
  csharp/ExcelAddInInstaller/TestCustomActions/App.config
  csharp/ExcelAddInInstaller/TestCustomActions/Program.cs
  csharp/ExcelAddInInstaller/TestCustomActions/Properties/AssemblyInfo.cs
  csharp/ExcelAddInInstaller/TestCustomActions/TestCustomActions.csproj
  csharp/ExcelAddInInstaller/certificates-public/README.md
  csharp/ExcelAddInInstaller/certificates-public/deephaven.cer
  csharp/ExcelAddInInstaller/dhinstall/.gitignore
  csharp/ExcelAddInInstaller/dhinstall/README.md
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6395 fix: Correct rollup and tree snapshot code to wait for missed structural dependencies
  engine/table/src/main/java/io/deephaven/engine/table/impl/hierarchical/HierarchicalTableImpl.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/hierarchical/RollupTableImpl.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/hierarchical/TreeTableFilter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/hierarchical/TreeTableImpl.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableTreeTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestHierarchicalTableSnapshots.java
Labels: bug, query engine, core, NoDocumentationNeeded, user-reported, ReleaseNotesNeeded, rollup, point_release_candidate

#6407 fix: Ensure that rollup and tree snapshot tests succeed reliably
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestHierarchicalTableSnapshots.java
Labels: query engine, core, NoDocumentationNeeded, NoReleaseNotesNeeded

#6408 fix: return type for IcebergCatalogAdapter::load_table in python
  py/server/deephaven/experimental/iceberg.py
Labels: bug, NoDocumentationNeeded, ReleaseNotesNeeded, iceberg

#6401 fix: Close Jetty h2 streams with RST_STREAM and no error code
  grpc-java/grpc-servlet-jakarta/src/main/java/io/grpc/servlet/jakarta/AsyncServletOutputStreamWriter.java
Labels: grpc, NoDocumentationNeeded, release blocker, python-client, jetty, ReleaseNotesNeeded

#6411 fix: Apply auto-locking in time_window()
  py/server/deephaven/experimental/__init__.py
  py/server/tests/test_experiments.py
Labels: NoDocumentationNeeded, python-server-side, ReleaseNotesNeeded

#6413 ci: Add cpwright to CODEOWNERS for /py, protos, gwt, and function lib…
  .github/CODEOWNERS
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6412 ci: Trigger actions on pull requests to rc/v* branches
  .github/workflows/check-ci.yml
  .github/workflows/create-docs-issues.yml
  .github/workflows/docs-ci.yml
  .github/workflows/label-check-ci.yml
  .github/workflows/publish-ci.yml
  .github/workflows/quick-ci.yml
Labels: ci, NoDocumentationNeeded, NoReleaseNotesNeeded

#6416 fix: various numpy backports
  py/client/setup.py
  py/client/tests/test_table.py
  py/server/tests/test_numpy.py
  py/server/tests/test_pandas.py
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6410 fix: Correct rollup and tree snapshot code to wait for missed structural dependencies
  engine/table/src/main/java/io/deephaven/engine/table/impl/hierarchical/HierarchicalTableImpl.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/hierarchical/RollupTableImpl.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/hierarchical/TreeTableFilter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/hierarchical/TreeTableImpl.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableTreeTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestHierarchicalTableSnapshots.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded, hierarchical_tables

#6409 fix: JS API rollups with unique aggs must specify null sentinel (#6202)
  web/client-api/src/main/java/io/deephaven/web/client/api/tree/JsRollupConfig.java
  web/client-api/src/main/java/io/deephaven/web/public/rollup.html
  web/client-api/src/test/java/io/deephaven/web/client/api/HierarchicalTableTestGwt.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#6365 feat: Allow a Filter to be used as the Expression in a SelectColumn.
  engine/table/src/main/java/io/deephaven/engine/table/impl/WouldMatchOperation.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/AbstractConditionFilter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/FilterSelectColumn.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/SelectColumn.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/WhereFilter.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableSelectUpdateTest.java
Labels: DocumentationNeeded, NoReleaseNotesNeeded

#5989 feat: Added support to write iceberg tables
  extensions/iceberg/s3/src/main/java/io/deephaven/iceberg/util/IcebergToolsS3.java
  extensions/iceberg/s3/src/test/java/io/deephaven/iceberg/util/IcebergToolsTest.java
  extensions/iceberg/s3/src/test/java/io/deephaven/iceberg/util/IcebergWriteInstructionsTest.java
  extensions/iceberg/s3/src/test/java/io/deephaven/iceberg/util/LocalstackWarehouseSqliteCatalogTest.java
  extensions/iceberg/s3/src/test/java/io/deephaven/iceberg/util/MinioWarehouseSqliteCatalogTest.java
  extensions/iceberg/s3/src/test/java/io/deephaven/iceberg/util/S3WarehouseSqliteCatalogBase.java
  extensions/iceberg/s3/src/test/java/io/deephaven/iceberg/util/TableParquetWriterOptionsTest.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/base/IcebergUtils.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/layout/IcebergBaseLayout.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/IcebergCatalogAdapter.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/IcebergReadInstructions.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/IcebergTableAdapter.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/IcebergTableWriter.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/IcebergWriteInstructions.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/SchemaProvider.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/SchemaProviderInternal.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/TableParquetWriterOptions.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/TableWriterOptions.java
  extensions/iceberg/src/test/java/io/deephaven/iceberg/PyIceberg1Test.java
  extensions/iceberg/src/test/java/io/deephaven/iceberg/junit5/FileWarehouseSqliteCatalogTest.java
  extensions/iceberg/src/test/java/io/deephaven/iceberg/junit5/SqliteCatalogBase.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/ParquetFileWriter.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/CompletedParquetWrite.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/ParquetInstructions.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/ParquetTableWriter.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/ParquetTools.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/ParquetTableReadWriteTest.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/S3ParquetLocalStackTest.java
  py/server/deephaven/experimental/iceberg.py
  py/server/deephaven/experimental/s3.py
  py/server/tests/test_iceberg.py
Labels: parquet, DocumentationNeeded, ReleaseNotesNeeded, s3, iceberg

#6406 fix: Better chunk cleanup on StreamToBlinkTableAdapter.destroy, and a few listener.destroy fixes
  engine/table/src/main/java/io/deephaven/engine/table/impl/AsOfJoinHelper.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/asofjoin/BucketedChunkedAjMergedListener.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/chunkcolumnsource/ByteChunkColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/chunkcolumnsource/CharChunkColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/chunkcolumnsource/DoubleChunkColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/chunkcolumnsource/FloatChunkColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/chunkcolumnsource/IntChunkColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/chunkcolumnsource/LongChunkColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/chunkcolumnsource/ObjectChunkColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/chunkcolumnsource/ShortChunkColumnSource.java
  engine/table/src/main/java/io/deephaven/stream/StreamToBlinkTableAdapter.java
  engine/table/src/test/java/io/deephaven/stream/TestStreamToBlinkTableAdapter.java
  engine/updategraph/src/main/java/io/deephaven/engine/updategraph/UpdateGraph.java
Labels: query engine, core, NoDocumentationNeeded, ReleaseNotesNeeded

#6420 revert: RST_STREAM(cancel) fix for gRPC, this seems to be breaking JS gRPC client
  grpc-java/grpc-servlet-jakarta/src/main/java/io/grpc/servlet/jakarta/AsyncServletOutputStreamWriter.java
Labels: jsapi, grpc, NoDocumentationNeeded, release blocker, python-client, ReleaseNotesNeeded

#6431 chore: Bump docker images
  docker/registry/fedora/gradle.properties
  docker/registry/go/gradle.properties
  docker/registry/manylinux2014_x86_64/gradle.properties
  docker/registry/minio/gradle.properties
  docker/registry/protoc-base/gradle.properties
  docker/registry/python/gradle.properties
  docker/registry/server-base/gradle.properties
  docker/registry/slim-base/gradle.properties
  docker/server-jetty/src/main/server-jetty/requirements.txt
  docker/server/src/main/server-netty/requirements.txt
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6430 fix: Added support to read iceberg tables partitioned by date
  extensions/iceberg/src/main/java/io/deephaven/iceberg/base/IcebergUtils.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/layout/IcebergKeyValuePartitionedLayout.java
  extensions/iceberg/src/test/java/io/deephaven/iceberg/junit5/SqliteCatalogBase.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded, iceberg

#6424 fix: Close Jetty h2 streams with RST_STREAM and no error code
  grpc-java/grpc-servlet-jakarta/src/main/java/io/grpc/servlet/jakarta/web/GrpcWebOutputStream.java
  grpc-java/grpc-servlet-jakarta/src/main/java/io/grpc/servlet/jakarta/web/GrpcWebServletRequest.java
  grpc-java/grpc-servlet-jakarta/src/main/java/io/grpc/servlet/jakarta/web/GrpcWebServletResponse.java
Labels: jsapi, grpc, NoDocumentationNeeded, python-client, ReleaseNotesNeeded, point_release_candidate

#6442 fix(cpp-client): Change tests to use Deephaven literals for LocalDate and LocalTime
  cpp-client/deephaven/tests/src/table_test.cc
  cpp-client/deephaven/tests/src/ticking_test.cc
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6402 fix: NPE in ProtobufDescriptorParserImpl for repeated nested repeated fields
  extensions/protobuf/src/main/java/io/deephaven/protobuf/ProtobufDescriptorParserImpl.java
  extensions/protobuf/src/test/java/io/deephaven/protobuf/ProtobufDescriptorParserTest.java
  extensions/protobuf/src/test/proto/mytest.proto
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6443 feat(csharp/ExcelAddInInstaller): Add Dialog, Banner, and Icon branding to the Deephaven Installer
  csharp/ExcelAddInInstaller/ExcelAddInInstaller.aip
  csharp/ExcelAddInInstaller/resources/Banner.jpg
  csharp/ExcelAddInInstaller/resources/Dialog.jpg
  csharp/ExcelAddInInstaller/resources/Icon.ico
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6437 chore: Update GWT/JsInterop/Elemental2 versions
  gradle/libs.versions.toml
  web/client-api/src/main/resources/io/deephaven/web/super/java/math/BigInteger.java
Labels: jsapi, NoDocumentationNeeded, dependencies, ReleaseNotesNeeded

#6440 chore: Bump gradle to 8.11.1
  gradle/wrapper/gradle-wrapper.properties
Labels: build, NoDocumentationNeeded, version-bump, NoReleaseNotesNeeded

#6444 fix: Credentials Resolution Bug in S3 Reads
  extensions/s3/src/main/java/io/deephaven/extensions/s3/ResolvingCredentials.java
Labels: bug, NoDocumentationNeeded, ReleaseNotesNeeded, s3

#6446 fix: Expose TableSubscription.close() to JS
  web/client-api/src/main/java/io/deephaven/web/client/api/subscription/TableSubscription.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded
