Repository deephaven/deephaven-core, pull requests merged in 2024-03, with the labels that each got.

#5211 Fix the hyperlink to the ticking readme
  py/client/docs/source/examples.rst
Labels: NoDocumentationNeeded, python-client, NoReleaseNotesNeeded

#5216 Address Blink table usage of `i`, `ii`, `k`, and column arrays; address improper memoization sharing between blink and non-blink table copies
  engine/table/src/main/java/io/deephaven/engine/table/impl/BlinkTableTools.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/MemoizedOperationKey.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/AbstractConditionFilter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/AbstractFormulaColumn.java
Labels: bug, feature request, query engine, core, DocumentationNeeded, ReleaseNotesNeeded

#5219 Update docs issue autogeneration to point to new docs repo
  .github/workflows/create-docs-issues.js
Labels: DocumentationNeeded, NoReleaseNotesNeeded

#5204 build: Add provenence flag when publishing jsapi-types
  .github/workflows/publish-ci.yml
  web/client-api/types/.npmrc
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5227 eval string annotation with func's globals
  py/server/deephaven/_jpy.py
  py/server/deephaven/_udf.py
  py/server/deephaven/agg.py
  py/server/deephaven/execution_context.py
  py/server/deephaven/table_listener.py
  py/server/deephaven/time.py
Labels: NoDocumentationNeeded, python-server-side, NoReleaseNotesNeeded

#5050 fix: Mark JsPartitionedTable.getTable as nullable
  web/client-api/src/main/java/io/deephaven/web/client/api/JsPartitionedTable.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5228 Bump test startup timeout dramatically to stop seeing this failure
  web/client-api/src/test/java/io/deephaven/web/client/api/HierarchicalTableTestGwt.java
Labels: test, NoDocumentationNeeded, NoReleaseNotesNeeded

#5235 Fix Python 3.8 compatibility issue
  py/server/deephaven/_udf.py
Labels: NoDocumentationNeeded, python-server-side, NoReleaseNotesNeeded

#5237 Dramatically increase timeout for another part of failing test
  web/client-api/src/test/java/io/deephaven/web/client/api/HierarchicalTableTestGwt.java
Labels: test, NoDocumentationNeeded, NoReleaseNotesNeeded

#5242 Check for empty data for add/delete/+async on InputTable
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/BaseArrayBackedInputTable.java
  py/server/tests/test_table_factory.py
Labels: bug, NoDocumentationNeeded, input-tables, ReleaseNotesNeeded

#5236 Generalize Python InputTable class
  py/server/deephaven/table.py
  py/server/deephaven/table_factory.py
  py/server/tests/test_table_factory.py
Labels: python, NoDocumentationNeeded, input-tables, NoReleaseNotesNeeded

#5247 Added fix for File.toURI regression
  Base/src/main/java/io/deephaven/base/FileUtils.java
  Util/channel/src/main/java/io/deephaven/util/channel/SeekableChannelsProvider.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/ColumnChunkReaderImpl.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/ParquetFileReader.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/ParquetTableWriter.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/ParquetTools.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/location/ParquetTableLocationKey.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/ParquetTableReadWriteTest.java
Labels: bug, parquet, NoDocumentationNeeded, ReleaseNotesNeeded, s3

#5256 Make column_to_numpy_array private
  py/server/deephaven/numpy.py
  py/server/deephaven/table_listener.py
Labels: NoDocumentationNeeded, python-server-side, NoReleaseNotesNeeded

#5251 Add SafeCloseable context manager wrapper
  py/server/deephaven/jcompat.py
  py/server/tests/test_jcompat.py
Labels: python, NoDocumentationNeeded, NoReleaseNotesNeeded

#5249 Make python timezone conversions handle more cases
  py/server/deephaven/time.py
  py/server/tests/test_time.py
Labels: bug, NoDocumentationNeeded, ReleaseNotesNeeded, devrel-watch

#5245 Make time of day methods handle daylight savings time (DST) better
  engine/time/src/main/java/io/deephaven/time/DateTimeUtils.java
  engine/time/src/test/java/io/deephaven/time/TestDateTimeUtils.java
Labels: DocumentationNeeded, ReleaseNotesNeeded, devrel-watch

#5151 Provide query library functions for computing differences and sort order
  engine/function/src/templates/Numeric.ftl
  engine/function/src/templates/Sort.ftl
  engine/function/src/templates/TestNumeric.ftl
  engine/function/src/templates/TestSort.ftl
  engine/table/src/main/java/io/deephaven/libs/GroovyStaticImports.java
Labels: query engine, DocumentationNeeded, ReleaseNotesNeeded

#5006 Python Client: add instructions that set DEEPHAVEN_VERSION
  py/client-ticking/README.md
  py/client/README.md
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5271 Only support zoneinfo for python 3.9+
  py/server/deephaven/time.py
  py/server/tests/test_time.py
Labels: bug, python, NoDocumentationNeeded, python-server-side, NoReleaseNotesNeeded

#5260 Fix input table jpy restriction
  py/server/deephaven/_wrapper.py
  py/server/deephaven/table_factory.py
  py/server/tests/test_table_factory.py
Labels: python, NoDocumentationNeeded, input-tables, NoReleaseNotesNeeded

#5273 Bump server base images, jpy>=0.16.0
  docker/registry/server-base/gradle.properties
  docker/registry/slim-base/gradle.properties
  docker/server-jetty/src/main/server-jetty/requirements.txt
  docker/server/src/main/server-netty/requirements.txt
  py/embedded-server/setup.py
  py/jpy-ext/build.gradle
  py/server/setup.py
Labels: NoDocumentationNeeded, jpy, version-bump, NoReleaseNotesNeeded

#5284 C++ client: make sure that the select test covers all types
  cpp-client/deephaven/tests/select_test.cc
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5286 C++ Client: fix FillChunk and missing types for ticking callbacks
  cpp-client/deephaven/dhclient/include/private/deephaven/client/arrowutil/arrow_column_source.h
  cpp-client/deephaven/dhclient/src/subscription/subscribe_thread.cc
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/chunk/chunk.h
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/types.h
  cpp-client/deephaven/dhcore/src/ticking/immer_table_state.cc
  cpp-client/deephaven/tests/ticking_test.cc
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5285 C++ client: process Barrage shifts properly
  cpp-client/deephaven/dhcore/include/private/deephaven/dhcore/immerutil/immer_column_source.h
  cpp-client/deephaven/dhcore/src/container/row_sequence.cc
  cpp-client/deephaven/dhcore/src/ticking/space_mapper.cc
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5283 Python ticking client: if no Barrage metadata, pass NULL to C++ handler
  py/client-ticking/src/pydeephaven_ticking/_core.pyx
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5254 Check arg type against Py UDF signature at query compile time
  engine/table/src/main/java/io/deephaven/engine/table/impl/lang/QueryLanguageParser.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/AbstractConditionFilter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/DhFormulaColumn.java
  engine/table/src/main/java/io/deephaven/engine/util/PyCallableWrapper.java
  engine/table/src/main/java/io/deephaven/engine/util/PyCallableWrapperJpyImpl.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/lang/PyCallableWrapperDummyImpl.java
  py/server/deephaven/_udf.py
  py/server/deephaven/dtypes.py
  py/server/tests/test_numba_guvectorize.py
  py/server/tests/test_udf_args.py
  py/server/tests/test_udf_return_java_values.py
  py/server/tests/test_vectorization.py
Labels: DocumentationNeeded, python-server-side, ReleaseNotesNeeded

#5282 Allow for specifying extra class paths to embedded server.
  py/embedded-server/deephaven_server/server.py
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5287 Bump to gradle 8.7
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: build, NoDocumentationNeeded, version-bump, NoReleaseNotesNeeded

#5267 Build py-ticking wheel using docker on top of a manylinux base image.
  cpp-client/README.md
  cpp-client/build.gradle
  cpp-client/deephaven/CMakeLists.txt
  docker/registry/fedora/build.gradle
  docker/registry/fedora/gradle.properties
  docker/registry/manylinux2014_x86_64/build.gradle
  docker/registry/manylinux2014_x86_64/gradle.properties
  docker/registry/ubi-minimal/build.gradle
  docker/registry/ubi-minimal/gradle.properties
  py/client-ticking/build.gradle
  py/client-ticking/setup.py
  py/client-ticking/src/pydeephaven_ticking/py.typed
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5300 Improve set inclusion kernel performance
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/DynamicWhereFilter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/setinclusion/ByteSetInclusionKernel.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/setinclusion/CharSetInclusionKernel.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/setinclusion/DoubleSetInclusionKernel.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/setinclusion/FloatSetInclusionKernel.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/setinclusion/IntSetInclusionKernel.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/setinclusion/LongSetInclusionKernel.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/setinclusion/ObjectSetInclusionKernel.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/setinclusion/SetInclusionKernel.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/setinclusion/ShortSetInclusionKernel.java
Labels: query engine, core, NoDocumentationNeeded, NoReleaseNotesNeeded

#5301 C++ client: delete stray debug code
  cpp-client/deephaven/tests/ticking_test.cc
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5302 RspRowSequence and SortedRangesRowSequence should invalidate their RowSequenceAsChunkImpl on reset instead of closing it
  engine/rowset/src/main/java/io/deephaven/engine/rowset/impl/RowSequenceAsChunkImpl.java
  engine/rowset/src/main/java/io/deephaven/engine/rowset/impl/ShiftedRowSequence.java
  engine/rowset/src/main/java/io/deephaven/engine/rowset/impl/WritableRowSetImpl.java
  engine/rowset/src/main/java/io/deephaven/engine/rowset/impl/rsp/RspRowSequence.java
  engine/rowset/src/main/java/io/deephaven/engine/rowset/impl/sortedranges/SortedRangesRowSequence.java
Labels: query engine, core, NoDocumentationNeeded, NoReleaseNotesNeeded
