Repository deephaven/deephaven-core, pull requests merged in 2024-09, with the labels that each got.

#6011 feat(csharp/ExcelAddIn): Make connections in the background
  csharp/ExcelAddIn/StateManager.cs
  csharp/ExcelAddIn/factories/CredentialsDialogFactory.cs
  csharp/ExcelAddIn/models/Session.cs
  csharp/ExcelAddIn/providers/ClientProvider.cs
  csharp/ExcelAddIn/providers/CorePlusClientProvider.cs
  csharp/ExcelAddIn/providers/SessionProvider.cs
  csharp/ExcelAddIn/providers/TableHandleProvider.cs
  csharp/ExcelAddIn/util/SimpleAtomicReference.cs
  csharp/ExcelAddIn/util/StatusOr.cs
  csharp/ExcelAddIn/util/Utility.cs
  csharp/ExcelAddIn/views/CredentialsDialog.cs
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6012 fix(csharp/ExcelAddIn): adjust and clarify README.md
  csharp/ExcelAddIn/README.md
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6018 fix: For failing nightly check test
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/ParquetTableReadWriteTest.java
Labels: bug, parquet, NoDocumentationNeeded, NoReleaseNotesNeeded

#6006 fix: Python embedded server should shut down any jvm threads/work it can
  py/embedded-server/build.gradle
  py/embedded-server/deephaven_server/server.py
  py/embedded-server/java-runtime/src/main/java/io/deephaven/python/server/EmbeddedServer.java
Labels: NoDocumentationNeeded, python-server-side, jpy, ReleaseNotesNeeded

#5958 feat: Support `remove_blink` to remove blink table semantics in server-side Python
  py/server/deephaven/table.py
  py/server/tests/test_table.py
Labels: python, DocumentationNeeded, python-server-side, ReleaseNotesNeeded

#5966 feat: Add TableDataService#getRawTableLocationProvider
  engine/table/src/main/java/io/deephaven/engine/table/impl/locations/TableDataService.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/locations/impl/AbstractTableDataService.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/locations/impl/CompositeTableDataService.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/locations/impl/FilteredTableDataService.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/DummyTableLocation.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestPartitioningColumns.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/locations/impl/TestTableDataService.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6022 feat: Added support to write vector/array of big decimals to parquet
  engine/primitive/src/main/java/io/deephaven/engine/primitive/iterator/CloseablePrimitiveIterator.java
  engine/table/src/main/java/io/deephaven/engine/util/BigDecimalUtils.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/TypeInfos.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/transfer/TransferObject.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/ParquetTableReadWriteTest.java
  py/server/tests/test_parquet.py
Labels: feature request, parquet, NoDocumentationNeeded, ReleaseNotesNeeded

#6007 feat: Added native support to read/write parquet files from GCS URIs
  engine/table/src/main/java/io/deephaven/engine/table/impl/locations/local/URIStreamKeyValuePartitionLayout.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/S3ParquetRemoteTest.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/GCSSeekableChannelProvider.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/GCSSeekableChannelProviderPlugin.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3Instructions.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3SeekableChannelProvider.java
Labels: feature request, parquet, DocumentationNeeded, ReleaseNotesNeeded, s3

#6027 fix: Correct misspelling in TableDiff Javadoc
  engine/table/src/main/java/io/deephaven/engine/util/TableDiff.java
Labels: documentation, NoDocumentationNeeded, trivial, NoReleaseNotesNeeded

#5754 feat: add generic Iceberg catalog adapter creation to Java / Python
  extensions/iceberg/s3/build.gradle
  extensions/iceberg/s3/src/main/java/io/deephaven/iceberg/util/IcebergToolsS3.java
  extensions/iceberg/s3/src/main/java/io/deephaven/iceberg/util/S3InstructionsProviderPlugin.java
  extensions/iceberg/s3/src/test/java/io/deephaven/iceberg/util/IcebergLocalStackTest.java
  extensions/iceberg/s3/src/test/java/io/deephaven/iceberg/util/IcebergMinIOTest.java
  extensions/iceberg/s3/src/test/java/io/deephaven/iceberg/util/IcebergToolsTest.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/internal/DataInstructionsProviderLoader.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/internal/DataInstructionsProviderPlugin.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/layout/IcebergBaseLayout.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/layout/IcebergFlatLayout.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/layout/IcebergKeyValuePartitionedLayout.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/IcebergCatalogAdapter.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/IcebergTools.java
  extensions/iceberg/src/test/java/io/deephaven/iceberg/TestCatalog/IcebergTestCatalog.java
  extensions/iceberg/src/test/java/io/deephaven/iceberg/TestCatalog/IcebergTestFileIO.java
  extensions/iceberg/src/test/java/io/deephaven/iceberg/TestCatalog/IcebergTestTable.java
  extensions/s3/src/test/java/io/deephaven/extensions/s3/testlib/SingletonContainers.java
  py/server/deephaven/experimental/iceberg.py
Labels: DocumentationNeeded, ReleaseNotesNeeded

#6030 feat(csharp/ExcelAddIn): ExcelAddIn demo v6: Respond to demo feedback
  csharp/ExcelAddIn/StateManager.cs
  csharp/ExcelAddIn/factories/ConnectionManagerDialogFactory.cs
  csharp/ExcelAddIn/factories/CredentialsDialogFactory.cs
  csharp/ExcelAddIn/managers/ConnectionManagerDialogManager.cs
  csharp/ExcelAddIn/managers/ConnectionManagerDialogRowManager.cs
  csharp/ExcelAddIn/models/Session.cs
  csharp/ExcelAddIn/models/SimpleModels.cs
  csharp/ExcelAddIn/providers/SessionProvider.cs
  csharp/ExcelAddIn/providers/SessionProviders.cs
  csharp/ExcelAddIn/util/ObservableConverter.cs
  csharp/ExcelAddIn/viewmodels/ConnectionManagerDialogRow.cs
  csharp/ExcelAddIn/viewmodels/CredentialsDialogViewModel.cs
  csharp/ExcelAddIn/views/ConnectionManagerDialog.Designer.cs
  csharp/ExcelAddIn/views/ConnectionManagerDialog.cs
  csharp/ExcelAddIn/views/ConnectionManagerDialog.resx
  csharp/ExcelAddIn/views/CredentialsDialog.Designer.cs
  csharp/ExcelAddIn/views/CredentialsDialog.cs
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6031 feat(csharp/ExcelAddIn): ExcelAddIn demo v7: Better GUI, better threading, better sharing
  csharp/ExcelAddIn/DeephavenExcelFunctions.cs
  csharp/ExcelAddIn/ExcelAddIn.csproj.user
  csharp/ExcelAddIn/StateManager.cs
  csharp/ExcelAddIn/factories/ConnectionManagerDialogFactory.cs
  csharp/ExcelAddIn/factories/CredentialsDialogFactory.cs
  csharp/ExcelAddIn/managers/ConnectionManagerDialogManager.cs
  csharp/ExcelAddIn/managers/ConnectionManagerDialogRowManager.cs
  csharp/ExcelAddIn/models/Session.cs
  csharp/ExcelAddIn/models/TableTriple.cs
  csharp/ExcelAddIn/operations/SnapshotOperation.cs
  csharp/ExcelAddIn/operations/SubscribeOperation.cs
  csharp/ExcelAddIn/providers/ClientProvider.cs
  csharp/ExcelAddIn/providers/CredentialsProvider.cs
  csharp/ExcelAddIn/providers/DefaultEndpointTableProvider.cs
  csharp/ExcelAddIn/providers/DefaultSessionProvider.cs
  csharp/ExcelAddIn/providers/FilteredTableProvider.cs
  csharp/ExcelAddIn/providers/ITableProvider.cs
  csharp/ExcelAddIn/providers/PersistentQueryProvider.cs
  csharp/ExcelAddIn/providers/SessionProvider.cs
  csharp/ExcelAddIn/providers/SessionProviders.cs
  csharp/ExcelAddIn/providers/TableHandleProvider.cs
  csharp/ExcelAddIn/providers/TableProvider.cs
  csharp/ExcelAddIn/util/ObservableConverter.cs
  csharp/ExcelAddIn/util/SimpleAtomicReference.cs
  csharp/ExcelAddIn/util/TableDescriptor.cs
  csharp/ExcelAddIn/util/Utility.cs
  csharp/ExcelAddIn/util/VersionTracker.cs
  csharp/ExcelAddIn/util/WorkerThread.cs
  csharp/ExcelAddIn/viewmodels/ConnectionManagerDialogRow.cs
  csharp/ExcelAddIn/viewmodels/CredentialsDialogViewModel.cs
  csharp/ExcelAddIn/views/ConnectionManagerDialog.cs
  csharp/ExcelAddIn/views/CredentialsDialog.cs
  csharp/ExcelAddIn/views/DeephavenMessageBox.Designer.cs
  csharp/ExcelAddIn/views/DeephavenMessageBox.cs
  csharp/ExcelAddIn/views/DeephavenMessageBox.resx
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6045 fix: Remove dependency on particular repo for package installation
  R/build.gradle
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6024 feat!: Add infer_objects argument to the to_table() function in the DH pandas module
  py/server/deephaven/pandas.py
  py/server/tests/test_pandas.py
Labels: DocumentationNeeded, python-server-side, breaking, ReleaseNotesNeeded

#6043 fix: Added additional jetty configuration options
  server/jetty/src/main/java/io/deephaven/server/jetty/JettyBackedGrpcServer.java
  server/jetty/src/main/java/io/deephaven/server/jetty/JettyConfig.java
Labels: grpc, NoDocumentationNeeded, jetty, ReleaseNotesNeeded

#6046 feat: Infrastructure for generating protobuf docs
  docker/registry/protoc-base/gradle.properties
  proto/proto-backplane-grpc/Dockerfile
  proto/proto-backplane-grpc/build.gradle
Labels: documentation, NoDocumentationNeeded, ReleaseNotesNeeded

#6068 docs: Update R client readme for clarity, new env var instructions
  R/rdeephaven/README.md
Labels: documentation, NoDocumentationNeeded, NoReleaseNotesNeeded

#6063 fix: Correctly support flight Date/Time types in JS
  engine/table/src/main/java/io/deephaven/engine/table/impl/preview/ColumnPreviewManager.java
  web/client-api/src/main/java/io/deephaven/web/client/api/LocalDateWrapper.java
  web/client-api/src/main/java/io/deephaven/web/client/api/LocalTimeWrapper.java
  web/client-api/src/main/java/io/deephaven/web/client/api/barrage/WebChunkReaderFactory.java
  web/shared-beans/src/main/java/io/deephaven/web/shared/data/LocalDate.java
  web/shared-beans/src/main/java/io/deephaven/web/shared/data/LocalTime.java
Labels: jsapi, NoDocumentationNeeded, arrow, ReleaseNotesNeeded

#6072 fix: Updated parquet-hadoop version 1.14.0 -> 1.14.1
  gradle/libs.versions.toml
Labels: parquet, NoDocumentationNeeded, ReleaseNotesNeeded

#6050 fix: Disable Jetty's webapp configuration
  server/jetty/src/main/java/io/deephaven/server/jetty/JettyBackedGrpcServer.java
Labels: NoDocumentationNeeded, jetty, ReleaseNotesNeeded

#6073 chore: update c++ base images
  cpp-client/README.md
  cpp-client/build-dependencies.sh
  cpp-client/build.gradle
  cpp-client/deephaven/cmake/deephavenConfig.cmake
  cpp-client/deephaven/dhclient/proto/deephaven/proto/application.pb.cc
  cpp-client/deephaven/dhclient/proto/deephaven/proto/application.pb.h
  cpp-client/deephaven/dhclient/proto/deephaven/proto/config.pb.cc
  cpp-client/deephaven/dhclient/proto/deephaven/proto/config.pb.h
  cpp-client/deephaven/dhclient/proto/deephaven/proto/console.pb.cc
  cpp-client/deephaven/dhclient/proto/deephaven/proto/console.pb.h
  cpp-client/deephaven/dhclient/proto/deephaven/proto/hierarchicaltable.pb.cc
  cpp-client/deephaven/dhclient/proto/deephaven/proto/hierarchicaltable.pb.h
  cpp-client/deephaven/dhclient/proto/deephaven/proto/inputtable.pb.cc
  cpp-client/deephaven/dhclient/proto/deephaven/proto/inputtable.pb.h
  cpp-client/deephaven/dhclient/proto/deephaven/proto/object.pb.cc
  cpp-client/deephaven/dhclient/proto/deephaven/proto/object.pb.h
  cpp-client/deephaven/dhclient/proto/deephaven/proto/partitionedtable.pb.cc
  cpp-client/deephaven/dhclient/proto/deephaven/proto/partitionedtable.pb.h
  cpp-client/deephaven/dhclient/proto/deephaven/proto/session.pb.cc
  cpp-client/deephaven/dhclient/proto/deephaven/proto/session.pb.h
  cpp-client/deephaven/dhclient/proto/deephaven/proto/storage.pb.cc
  cpp-client/deephaven/dhclient/proto/deephaven/proto/storage.pb.h
  cpp-client/deephaven/dhclient/proto/deephaven/proto/table.pb.cc
  cpp-client/deephaven/dhclient/proto/deephaven/proto/table.pb.h
  cpp-client/deephaven/dhclient/proto/deephaven/proto/ticket.pb.cc
  cpp-client/deephaven/dhclient/proto/deephaven/proto/ticket.pb.h
  docker/registry/cpp-clients-multi-base/gradle.properties
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6078 fix: Include column name in exception when ColumnSource.cast fails
  engine/api/src/main/java/io/deephaven/engine/table/ColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/TableDefaults.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableTest.java
Labels: core, NoDocumentationNeeded, NoReleaseNotesNeeded

#6076 fix: JS charts should handle shifts, read subscription data by key
  web/client-api/src/main/java/io/deephaven/web/client/api/subscription/AbstractTableSubscription.java
  web/client-api/src/main/java/io/deephaven/web/client/api/subscription/TableViewportSubscription.java
  web/client-api/src/main/java/io/deephaven/web/client/api/widget/plot/ChartData.java
  web/client-api/src/main/java/io/deephaven/web/client/api/widget/plot/FigureSubscription.java
  web/shared-beans/src/main/java/io/deephaven/web/shared/data/RangeSet.java
  web/shared-beans/src/test/java/io/deephaven/web/shared/data/RangeSetTest.java
Labels: jsapi, plotting, NoDocumentationNeeded, ReleaseNotesNeeded

#6086 feat(cpp-client): Add support for LocalDate and LocalTime
  cpp-client/deephaven/dhclient/include/private/deephaven/client/arrowutil/arrow_column_source.h
  cpp-client/deephaven/dhclient/include/public/deephaven/client/utility/table_maker.h
  cpp-client/deephaven/dhclient/src/arrowutil/arrow_client_table.cc
  cpp-client/deephaven/dhclient/src/subscription/subscribe_thread.cc
  cpp-client/deephaven/dhclient/src/utility/arrow_util.cc
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/chunk/chunk.h
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/chunk/chunk_traits.h
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/column/column_source.h
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/column/column_source_helpers.h
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/types.h
  cpp-client/deephaven/dhcore/src/chunk/chunk_maker.cc
  cpp-client/deephaven/dhcore/src/column/column_source_helpers.cc
  cpp-client/deephaven/dhcore/src/ticking/immer_table_state.cc
  cpp-client/deephaven/dhcore/src/types.cc
  cpp-client/deephaven/dhcore/src/utility/cython_support.cc
  cpp-client/deephaven/tests/src/select_test.cc
  cpp-client/deephaven/tests/src/table_test.cc
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6105 feat(cpp-client): Additional Cython support for LocalDate and LocalTime
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/column/array_column_source.h
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/types.h
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/utility/cython_support.h
  cpp-client/deephaven/dhcore/src/utility/cython_support.cc
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6028 feat: Improvements to the S3 API
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/S3ParquetRemoteTest.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/S3ParquetTestBase.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/Credentials.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/DefaultCredentials.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3AsyncClientFactory.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3Instructions.java
  py/server/deephaven/experimental/s3.py
Labels: parquet, DocumentationNeeded, ReleaseNotesNeeded, s3

#5990 feat: Support generic publish/fetch for plugins
  py/client/pydeephaven/_arrow_flight_service.py
  py/client/pydeephaven/_batch_assembler.py
  py/client/pydeephaven/_console_service.py
  py/client/pydeephaven/_input_table_service.py
  py/client/pydeephaven/_session_service.py
  py/client/pydeephaven/_table_ops.py
  py/client/pydeephaven/_table_service.py
  py/client/pydeephaven/experimental/plugin_client.py
  py/client/pydeephaven/experimental/server_object.py
  py/client/pydeephaven/session.py
  py/client/pydeephaven/table.py
  py/client/pydeephaven/ticket.py
  py/client/tests/test_plugin_client.py
  py/client/tests/test_session.py
  py/client/tests/test_table.py
Labels: DocumentationNeeded, ReleaseNotesNeeded

#6061 feat: Add add_async/delete_async methods in InputTable
  Integrations/src/main/java/io/deephaven/integrations/python/PythonInputTableStatusListenerAdapter.java
  py/server/deephaven/table_factory.py
  py/server/deephaven/table_listener.py
  py/server/tests/test_table_factory.py
Labels: DocumentationNeeded, python-server-side, ReleaseNotesNeeded

#6085 fix: JS should modify data in redirected space, not key space
  web/client-api/src/main/java/io/deephaven/web/client/api/barrage/data/WebBarrageSubscription.java
Labels: jsapi, NoDocumentationNeeded, release blocker, ReleaseNotesNeeded

#6048 fix: Add pyarrow date64/time64('ns') to the list of supported Arrow data types in the Python client
  py/client/pydeephaven/_arrow.py
  py/client/tests/test_session.py
Labels: NoDocumentationNeeded, python-client, ReleaseNotesNeeded

#6122 fix: Correct JoinControl.tableSize to ensure that we leave excess capacity to fit within our load factor tolerances
  engine/table/src/main/java/io/deephaven/engine/table/impl/JoinControl.java
Labels: query engine, core, NoDocumentationNeeded, release blocker, ReleaseNotesNeeded

#6127 feat: Support type checking when retrieving an objectColumnIterator
  engine/api/src/main/java/io/deephaven/engine/table/Table.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/TableAdapter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/UncoalescedTable.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/sources/regioned/TestChunkedRegionedOperations.java
Labels: query engine, core, NoDocumentationNeeded, ReleaseNotesNeeded

#6129 feat: Publish protobuf documentation to website
  .github/workflows/docs-ci.yml
Labels: documentation, NoDocumentationNeeded, ReleaseNotesNeeded

#6134 test: Skip tests to make CI pass
  py/client/tests/test_plugin_client.py
Labels: NoDocumentationNeeded, python-client, NoReleaseNotesNeeded

#6135 fix: Fix protobuf doc deployment
  .github/workflows/docs-ci.yml
Labels: bug, NoDocumentationNeeded, NoReleaseNotesNeeded

#6137 fix(cpp-client): Correctly process Deephaven NULL convention for types with underlying int64 representation
  cpp-client/deephaven/dhcore/src/utility/cython_support.cc
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6081 perf: Embed WindowCheck in TimeSeriesFilter.
  engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/WouldMatchOperation.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/TimeSeriesFilter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/WhereFilter.java
  engine/table/src/main/java/io/deephaven/engine/util/WindowCheck.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableWhereTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/select/TestTimeSeriesFilter.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/util/TestTimeSeriesFilter.java
  engine/table/src/test/java/io/deephaven/engine/util/TestClock.java
Labels: DocumentationNeeded, ReleaseNotesNeeded, point_release_candidate

#6106 feat(py/client-ticking): Add support for LocalDate and LocalTime
  py/client-ticking/README.md
  py/client-ticking/src/pydeephaven_ticking/_core.pxd
  py/client-ticking/src/pydeephaven_ticking/_core.pyx
  py/client-ticking/tests/test_ticking_all_types.py
  py/client-ticking/tests/test_ticking_basic.py
  py/client/README.md
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6140 style: Make hadoop config follow pep 8 guidelines in Iceberg adapter
  py/server/deephaven/experimental/iceberg.py
Labels: size:1, python, NoDocumentationNeeded, NoReleaseNotesNeeded

#6136 feat(cpp-client): Generate protos for C++ as part of the build
  cpp-client/build.gradle
  cpp-client/deephaven/dhclient/CMakeLists.txt
  cpp-client/deephaven/dhclient/proto/deephaven/proto/application.grpc.pb.cc
  cpp-client/deephaven/dhclient/proto/deephaven/proto/application.grpc.pb.h
  cpp-client/deephaven/dhclient/proto/deephaven/proto/application.pb.cc
  cpp-client/deephaven/dhclient/proto/deephaven/proto/application.pb.h
  cpp-client/deephaven/dhclient/proto/deephaven/proto/config.grpc.pb.cc
  cpp-client/deephaven/dhclient/proto/deephaven/proto/config.grpc.pb.h
  cpp-client/deephaven/dhclient/proto/deephaven/proto/config.pb.cc
  cpp-client/deephaven/dhclient/proto/deephaven/proto/config.pb.h
  cpp-client/deephaven/dhclient/proto/deephaven/proto/console.grpc.pb.cc
  cpp-client/deephaven/dhclient/proto/deephaven/proto/console.grpc.pb.h
  cpp-client/deephaven/dhclient/proto/deephaven/proto/console.pb.cc
  cpp-client/deephaven/dhclient/proto/deephaven/proto/console.pb.h
  cpp-client/deephaven/dhclient/proto/deephaven/proto/hierarchicaltable.grpc.pb.cc
  cpp-client/deephaven/dhclient/proto/deephaven/proto/hierarchicaltable.grpc.pb.h
  cpp-client/deephaven/dhclient/proto/deephaven/proto/hierarchicaltable.pb.cc
  cpp-client/deephaven/dhclient/proto/deephaven/proto/hierarchicaltable.pb.h
  cpp-client/deephaven/dhclient/proto/deephaven/proto/inputtable.grpc.pb.cc
  cpp-client/deephaven/dhclient/proto/deephaven/proto/inputtable.grpc.pb.h
  cpp-client/deephaven/dhclient/proto/deephaven/proto/inputtable.pb.cc
  cpp-client/deephaven/dhclient/proto/deephaven/proto/inputtable.pb.h
  cpp-client/deephaven/dhclient/proto/deephaven/proto/object.grpc.pb.cc
  cpp-client/deephaven/dhclient/proto/deephaven/proto/object.grpc.pb.h
  cpp-client/deephaven/dhclient/proto/deephaven/proto/object.pb.cc
  cpp-client/deephaven/dhclient/proto/deephaven/proto/object.pb.h
  cpp-client/deephaven/dhclient/proto/deephaven/proto/partitionedtable.grpc.pb.cc
  cpp-client/deephaven/dhclient/proto/deephaven/proto/partitionedtable.grpc.pb.h
  cpp-client/deephaven/dhclient/proto/deephaven/proto/partitionedtable.pb.cc
  cpp-client/deephaven/dhclient/proto/deephaven/proto/partitionedtable.pb.h
  cpp-client/deephaven/dhclient/proto/deephaven/proto/session.grpc.pb.cc
  cpp-client/deephaven/dhclient/proto/deephaven/proto/session.grpc.pb.h
  cpp-client/deephaven/dhclient/proto/deephaven/proto/session.pb.cc
  cpp-client/deephaven/dhclient/proto/deephaven/proto/session.pb.h
  cpp-client/deephaven/dhclient/proto/deephaven/proto/storage.grpc.pb.cc
  cpp-client/deephaven/dhclient/proto/deephaven/proto/storage.grpc.pb.h
  cpp-client/deephaven/dhclient/proto/deephaven/proto/storage.pb.cc
  cpp-client/deephaven/dhclient/proto/deephaven/proto/storage.pb.h
  cpp-client/deephaven/dhclient/proto/deephaven/proto/table.grpc.pb.cc
  cpp-client/deephaven/dhclient/proto/deephaven/proto/table.grpc.pb.h
  cpp-client/deephaven/dhclient/proto/deephaven/proto/table.pb.cc
  cpp-client/deephaven/dhclient/proto/deephaven/proto/table.pb.h
  cpp-client/deephaven/dhclient/proto/deephaven/proto/ticket.grpc.pb.cc
  cpp-client/deephaven/dhclient/proto/deephaven/proto/ticket.grpc.pb.h
  cpp-client/deephaven/dhclient/proto/deephaven/proto/ticket.pb.cc
  cpp-client/deephaven/dhclient/proto/deephaven/proto/ticket.pb.h
  proto/proto-backplane-grpc/build.gradle
  proto/proto-backplane-grpc/src/main/proto/build-cpp-protos.sh
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6145 chore: Bump to Java 23 in nightly testing
  .github/scripts/gradle-properties.sh
  .github/workflows/nightly-check-ci.yml
  Configuration/src/test/java/io/deephaven/configuration/TestConfiguration.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6146 test: Fix a potential leak or worse in the test
  py/client/pydeephaven/ticket.py
  py/client/tests/test_plugin_client.py
Labels: test, NoDocumentationNeeded, NoReleaseNotesNeeded

#6144 feat: Add support for using JDBC Catalog for Iceberg testing
  extensions/iceberg/TESTING.md
  extensions/iceberg/build.gradle
  extensions/iceberg/src/main/java/io/deephaven/iceberg/layout/IcebergBaseLayout.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/relative/RelativeFileIO.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/relative/RelativeInputFile.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/relative/RelativeOutputFile.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/IcebergCatalogAdapter.java
  extensions/iceberg/src/test/java/io/deephaven/iceberg/CatalogAdapterTest.java
  extensions/iceberg/src/test/java/io/deephaven/iceberg/PyIceberg1Test.java
  extensions/iceberg/src/test/java/io/deephaven/iceberg/TestCatalog/IcebergTestTable.java
  extensions/iceberg/src/test/java/io/deephaven/iceberg/junit5/CatalogAdapterBase.java
  extensions/iceberg/src/test/java/io/deephaven/iceberg/sqlite/DbResource.java
  extensions/iceberg/src/test/java/io/deephaven/iceberg/sqlite/SqliteHelper.java
  extensions/iceberg/src/test/resources/io/deephaven/iceberg/sqlite/db_resource/catalogs/pyiceberg-1/dh-default.db/cities/data/00000-0-6976b5d5-cc59-4f48-bcc5-3a4bf37e5139.parquet
  extensions/iceberg/src/test/resources/io/deephaven/iceberg/sqlite/db_resource/catalogs/pyiceberg-1/dh-default.db/cities/data/00000-0-cc668bfb-107c-4122-8d64-9a078f2f45a9.parquet
  extensions/iceberg/src/test/resources/io/deephaven/iceberg/sqlite/db_resource/catalogs/pyiceberg-1/dh-default.db/cities/metadata/00000-4aec1d46-5bde-4642-bac7-cc7573558c7e.metadata.json
  extensions/iceberg/src/test/resources/io/deephaven/iceberg/sqlite/db_resource/catalogs/pyiceberg-1/dh-default.db/cities/metadata/00001-3128d2b2-934f-483e-b2b0-4c08baebc5b2.metadata.json
  extensions/iceberg/src/test/resources/io/deephaven/iceberg/sqlite/db_resource/catalogs/pyiceberg-1/dh-default.db/cities/metadata/00002-262f9917-5f0d-478c-aba2-a05842613e29.metadata.json
  extensions/iceberg/src/test/resources/io/deephaven/iceberg/sqlite/db_resource/catalogs/pyiceberg-1/dh-default.db/cities/metadata/00003-979e64ae-2052-4569-b9f1-1b45ab0c2be0.metadata.json
  extensions/iceberg/src/test/resources/io/deephaven/iceberg/sqlite/db_resource/catalogs/pyiceberg-1/dh-default.db/cities/metadata/6976b5d5-cc59-4f48-bcc5-3a4bf37e5139-m0.avro
  extensions/iceberg/src/test/resources/io/deephaven/iceberg/sqlite/db_resource/catalogs/pyiceberg-1/dh-default.db/cities/metadata/cc668bfb-107c-4122-8d64-9a078f2f45a9-m0.avro
  extensions/iceberg/src/test/resources/io/deephaven/iceberg/sqlite/db_resource/catalogs/pyiceberg-1/dh-default.db/cities/metadata/snap-1743193108934390753-0-cc668bfb-107c-4122-8d64-9a078f2f45a9.avro
  extensions/iceberg/src/test/resources/io/deephaven/iceberg/sqlite/db_resource/catalogs/pyiceberg-1/dh-default.db/cities/metadata/snap-4630159959461529013-0-6976b5d5-cc59-4f48-bcc5-3a4bf37e5139.avro
  extensions/iceberg/src/test/resources/io/deephaven/iceberg/sqlite/db_resource/dh-iceberg-test.db
  extensions/iceberg/src/test/resources/io/deephaven/iceberg/sqlite/db_resource/generate-pyiceberg-1.py
  gradle/libs.versions.toml
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6155 fix(py-client-test): Read PluginClients In Order; fix shared_ticket Ref
  py/client/tests/test_plugin_client.py
  server/src/main/java/io/deephaven/server/object/ObjectServiceGrpcImpl.java
Labels: bug, test, NoDocumentationNeeded, NoReleaseNotesNeeded

#6020 feat!: Support Multijoin in the Python client
  py/client/pydeephaven/_table_ops.py
  py/client/pydeephaven/_table_service.py
  py/client/pydeephaven/session.py
  py/client/pydeephaven/table.py
  py/client/tests/test_multijoin.py
  py/server/deephaven/table.py
  py/server/tests/test_multijoin.py
Labels: DocumentationNeeded, python-client, breaking, ReleaseNotesNeeded

#6148 fix: JS Barrage snapshots must overwrite server viewport
  web/client-api/src/main/java/io/deephaven/web/client/api/subscription/TableViewportSubscription.java
  web/client-api/src/test/java/io/deephaven/web/client/api/subscription/ViewportTestGwt.java
Labels: jsapi, NoDocumentationNeeded, release blocker, ReleaseNotesNeeded

#6154 chore: Fix broken links in markdown.
  CONTRIBUTING.md
  R/rdeephaven/README.md
  README.md
  containers/groovy-examples/README.md
  containers/python-examples-redpanda/README.md
  containers/python-examples/All-AI/README.md
  containers/python-examples/NLTK/README.md
  containers/python-examples/PyTorch/README.md
  containers/python-examples/SciKit-Learn/README.md
  containers/python-examples/TensorFlow/README.md
  containers/python-examples/base/README.md
  containers/python-redpanda/README.md
  containers/python/All-AI/README.md
  containers/python/NLTK/README.md
  containers/python/PyTorch/README.md
  containers/python/SciKit-Learn/README.md
  containers/python/TensorFlow/README.md
  containers/python/base/README.md
  cpp-client/README.md
  csharp/ExcelAddIn/README.md
  debezium/demo/README.md
  docker/web-plugin-packager/README.md
  server/jetty-app/README.md
Labels: size:2, NoDocumentationNeeded, NoReleaseNotesNeeded

#6150 fix: Fix Iceberg JDBC tests on Java 23
  extensions/iceberg/build.gradle
  extensions/iceberg/src/test/java/io/deephaven/iceberg/PyIceberg1Test.java
  extensions/iceberg/src/test/java/io/deephaven/iceberg/junit5/CatalogAdapterBase.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded
