Repository deephaven/deephaven-core, pull requests merged in 2024-02, with the labels that each got.

#5086 Submit gradle-aware dependency information to Github
  .github/workflows/dependency-submission.yml
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5102 Update slf4j and logback versions
  buildSrc/src/main/groovy/Classpaths.groovy
Labels: security, NoDocumentationNeeded, version-bump, NoReleaseNotesNeeded

#5108 Bump commons-compress
  buildSrc/src/main/groovy/io.deephaven.java-classpath-conventions.gradle
Labels: security, NoDocumentationNeeded, version-bump, NoReleaseNotesNeeded

#5103 Fixed a bug in reading metadata files
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/ColumnChunkReaderImpl.java
Labels: bug, parquet, NoDocumentationNeeded, NoReleaseNotesNeeded

#5098 Increase one more failing test timeout
  web/client-api/src/test/java/io/deephaven/web/client/api/HierarchicalTableTestGwt.java
Labels: jsapi, test, NoDocumentationNeeded, NoReleaseNotesNeeded

#5095 Fix S3ChannelContext.FragmentState#cancelAndRelease
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3SeekableByteChannel.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5104 Update avro version
  extensions/kafka/build.gradle
Labels: security, NoDocumentationNeeded, version-bump, NoReleaseNotesNeeded

#5106 Update xerial snappy-java version
  extensions/parquet/compression/build.gradle
Labels: security, NoDocumentationNeeded, version-bump, NoReleaseNotesNeeded

#5107 Bump postgresql version
  authentication/example-providers/sql-username-password/build.gradle
Labels: security, NoDocumentationNeeded, version-bump, NoReleaseNotesNeeded

#5083 Add Py version check for using eval_str flag of the inspect.signature()
  py/server/deephaven/_udf.py
Labels: NoDocumentationNeeded, python-server-side, NoReleaseNotesNeeded

#5110 DEEPHAVEN_VERSION must be set when installing py-client wheel
  py/client/build.gradle
Labels: build, test, NoDocumentationNeeded, python-client, NoReleaseNotesNeeded

#5100 Add support of 1D arrays in UDF vectorization
  engine/table/src/main/java/io/deephaven/engine/util/PyCallableWrapperJpyImpl.java
  py/server/deephaven/_udf.py
  py/server/tests/test_vectorization.py
Labels: DocumentationNeeded, python-server-side, ReleaseNotesNeeded

#5117 Ensure wildcard imports work against JRE classes
  engine/table/build.gradle
  engine/table/src/main/java/io/deephaven/engine/util/GroovyDeephavenSession.java
  engine/table/src/test/java/io/deephaven/engine/util/scripts/TestGroovyDeephavenSession.java
  engine/table/src/test/java/io/deephaven/engine/util/scripts/wontbeused/WontBeUsed.java
Labels: NoDocumentationNeeded, groovy, ReleaseNotesNeeded

#5087 Add endpointOverride S3 support
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/ParquetTableReadWriteTest.java
  extensions/s3/build.gradle
  extensions/s3/gradle.properties
  extensions/s3/src/main/java/io/deephaven/extensions/s3/AwsCredentials.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/AwsSdkV2Credentials.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/BasicCredentials.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/Credentials.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/DefaultCredentials.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3Instructions.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3SeekableByteChannel.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3SeekableChannelProvider.java
  extensions/s3/src/test/java/io/deephaven/extensions/s3/S3InstructionsTest.java
  extensions/s3/src/test/java/io/deephaven/extensions/s3/S3SeekableChannelLocalStackTest.java
  extensions/s3/src/test/java/io/deephaven/extensions/s3/S3SeekableChannelMinIOTest.java
  extensions/s3/src/test/java/io/deephaven/extensions/s3/S3SeekableChannelTestBase.java
  extensions/s3/src/test/java/io/deephaven/extensions/s3/SingletonContainers.java
  py/server/deephaven/experimental/s3.py
  py/server/tests/test_parquet.py
Labels: DocumentationNeeded, ReleaseNotesNeeded

#5121 Add AggWAvg support for rollup()
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/AggregationProcessor.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/ChunkedWeightedAverageOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/RollupConstants.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/WeightedAverageOperator.java
  py/server/tests/test_table.py
Labels: DocumentationNeeded, ReleaseNotesNeeded

#5125 Propagate Blink Attribute Downstream of View/UpdateView/Select/UpdateView
  engine/table/src/main/java/io/deephaven/engine/table/impl/BaseTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/analyzers/SelectAndViewAnalyzerWrapper.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableSelectUpdateTest.java
Labels: query engine, core, NoDocumentationNeeded, ReleaseNotesNeeded

#5130 Bump base image, update numba cutoff to Python 3.12
  docker/registry/server-base/gradle.properties
  docker/server-jetty/src/main/server-jetty/requirements.txt
  docker/server/src/main/server-netty/requirements.txt
  py/server/setup.py
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5134 Increase another failing test timeout
  web/client-api/src/test/java/io/deephaven/web/client/api/HierarchicalTableTestGwt.java
Labels: jsapi, test, NoDocumentationNeeded, NoReleaseNotesNeeded

#5058 Replace usage of trove in Chunk APIs
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/BooleanChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/ByteChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/CharChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/ChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/DoubleChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/FixedWidthChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/FloatChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/IntChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/LongChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/ShortChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/VarBinaryChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/VarListChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/VectorChunkInputStreamGenerator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/ArrowToTableConverter.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/BarrageChunkAppendingMarshaller.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/BarrageStreamReader.java
  extensions/barrage/src/test/java/io/deephaven/extensions/barrage/chunk/BarrageColumnRoundTripTest.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#4907 Deploy `@deephaven/jsapi-types` during release, provide tools for nightly builds
  .github/workflows/publish-ci.yml
  RELEASE.md
  docker/registry/node/gradle.properties
  proto/raw-js-openapi/.npmrc
  proto/raw-js-openapi/.nvmrc
  proto/raw-js-openapi/build.gradle
  proto/raw-js-openapi/package-lock.json
  proto/raw-js-openapi/package.json
  web/client-api/client-api.gradle
  web/client-api/src/main/java/io/deephaven/web/client/api/JsLayoutHints.java
  web/client-api/src/main/java/io/deephaven/web/client/api/TableData.java
  web/client-api/types/.npmrc
  web/client-api/types/.nvmrc
  web/client-api/types/README.md
  web/client-api/types/build.gradle
  web/client-api/types/package-lock.json
  web/client-api/types/package.json
Labels: build, jsapi, NoDocumentationNeeded, release, NoReleaseNotesNeeded

#5093 Reduce public visibility into io.deephaven.parquet.base
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/AbstractBulkValuesWriter.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/BulkWriter.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/ColumnChunkReaderImpl.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/ColumnPageReaderImpl.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/ColumnWriterImpl.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/GenericArrayBuffer.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/Helpers.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/PageMaterializer.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/PageMaterializerFactory.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/ParquetFileReader.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/PlainBinaryChunkedWriter.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/PlainBooleanChunkedWriter.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/PlainDoubleChunkedWriter.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/PlainFloatChunkedWriter.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/PlainIntChunkedWriter.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/PlainLongChunkedWriter.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/RleIntChunkedWriter.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/RowGroupReaderImpl.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/RowGroupWriterImpl.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/RunLengthBitPackingHybridBufferDecoder.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5123 PythonScopeJpyImpl: Disable Conversion Cache
  Integrations/src/main/java/io/deephaven/integrations/python/PythonDeephavenSession.java
  Integrations/src/main/java/io/deephaven/integrations/python/PythonObjectWrapper.java
  engine/context/src/main/java/io/deephaven/engine/context/EmptyQueryScope.java
  engine/context/src/main/java/io/deephaven/engine/context/PoisonedQueryScope.java
  engine/context/src/main/java/io/deephaven/engine/context/QueryScope.java
  engine/context/src/main/java/io/deephaven/engine/context/QueryScopeParam.java
  engine/context/src/main/java/io/deephaven/engine/context/StandaloneQueryScope.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/lang/QueryLanguageParser.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/AbstractConditionFilter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/AbstractFormulaColumn.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/DhFormulaColumn.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/codegen/FormulaAnalyzer.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/python/FormulaColumnPython.java
  engine/table/src/main/java/io/deephaven/engine/util/AbstractScriptSession.java
  engine/table/src/main/java/io/deephaven/engine/util/GroovyDeephavenSession.java
  engine/table/src/main/java/io/deephaven/engine/util/NoLanguageDeephavenSession.java
  engine/table/src/main/java/io/deephaven/engine/util/PyCallableWrapperJpyImpl.java
  engine/table/src/main/java/io/deephaven/engine/util/PythonScope.java
  engine/table/src/main/java/io/deephaven/engine/util/PythonScopeJpyImpl.java
  engine/table/src/main/java/io/deephaven/engine/util/ScriptSession.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/lang/TestQueryLanguageParser.java
  server/src/main/java/io/deephaven/server/console/python/PythonGlobalScopeCopyModule.java
  server/src/main/java/io/deephaven/server/console/python/PythonGlobalScopeModule.java
  server/src/main/java/io/deephaven/server/console/python/PythonImportInitializer.java
  table-api/src/main/java/io/deephaven/api/util/NameValidator.java
Labels: bug, core, python, NoDocumentationNeeded, ReleaseNotesNeeded

#5149 Fix unrendered HTML in py client doc
  py/client/docs/source/examples.rst
Labels: documentation, size:1, NoDocumentationNeeded, NoReleaseNotesNeeded

#5137 Improve S3, parquet, and SeekableChannelsProvider
  Base/src/main/java/io/deephaven/base/reference/PooledObjectReference.java
  Base/src/test/java/io/deephaven/base/reference/PooledObjectReferenceTest.java
  Util/channel/build.gradle
  Util/channel/src/main/java/io/deephaven/util/channel/CachedChannelProvider.java
  Util/channel/src/main/java/io/deephaven/util/channel/ChannelPositionInputStream.java
  Util/channel/src/main/java/io/deephaven/util/channel/Channels.java
  Util/channel/src/main/java/io/deephaven/util/channel/ContextHolderImpl.java
  Util/channel/src/main/java/io/deephaven/util/channel/LocalFSChannelProvider.java
  Util/channel/src/main/java/io/deephaven/util/channel/ReadableByteChannelNoClose.java
  Util/channel/src/main/java/io/deephaven/util/channel/SeekableChannelContext.java
  Util/channel/src/main/java/io/deephaven/util/channel/SeekableChannelContextNull.java
  Util/channel/src/main/java/io/deephaven/util/channel/SeekableChannelsProvider.java
  Util/channel/src/test/java/io/deephaven/util/channel/CachedChannelProviderTest.java
  Util/src/main/java/io/deephaven/util/referencecounting/ReferenceCounted.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/ColumnChunkReaderImpl.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/ColumnPageReaderImpl.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/ParquetFileReader.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/RowGroupReaderImpl.java
  extensions/parquet/compression/src/main/java/io/deephaven/parquet/compress/CompressorAdapter.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/location/ParquetColumnLocation.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/location/ParquetTableLocation.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/pagestore/ColumnChunkPageStore.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/pagestore/OffsetIndexBasedColumnChunkPageStore.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/pagestore/VariablePageSizeColumnChunkPageStore.java
  extensions/s3/build.gradle
  extensions/s3/src/main/java/io/deephaven/extensions/s3/AnonymousCredentials.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/BufferPool.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/ByteBufferAsyncResponseTransformer.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/Credentials.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3ChannelContext.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3Instructions.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3SeekableByteChannel.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3SeekableChannelProvider.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/SegmentedBufferPool.java
  extensions/s3/src/test/java/io/deephaven/extensions/s3/CredentialsTest.java
  extensions/s3/src/test/java/io/deephaven/extensions/s3/S3InstructionsTest.java
  extensions/s3/src/test/java/io/deephaven/extensions/s3/SingletonContainers.java
  extensions/trackedfile/src/main/java/io/deephaven/extensions/trackedfile/TrackedSeekableChannelsProvider.java
  py/server/deephaven/experimental/s3.py
  server/jetty-app/src/main/resources/logback.xml
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5155 Reduce Verbose Logging in Generators
  Generators/src/main/java/io/deephaven/gen/AbstractBasicJavaGenerator.java
  Generators/src/main/java/io/deephaven/libs/GroovyStaticImportGenerator.java
  Generators/src/main/java/io/deephaven/libs/StaticCalendarMethodsGenerator.java
  Generators/src/main/java/io/deephaven/plot/util/GeneratePlottingConvenience.java
Labels: core, NoDocumentationNeeded, NoReleaseNotesNeeded

#5152 Clarify responsibilities when calling this method
  py/server/deephaven/server/executors.py
Labels: documentation, NoDocumentationNeeded, NoReleaseNotesNeeded

#5141 Add TrustCustom
  ssl/config/src/main/java/io/deephaven/ssl/config/Trust.java
  ssl/config/src/main/java/io/deephaven/ssl/config/TrustCustom.java
  ssl/config/src/main/java/io/deephaven/ssl/config/TrustStore.java
  ssl/config/src/test/java/io/deephaven/ssl/config/SSLConfigTest.java
  ssl/config/src/test/resources/io/deephaven/ssl/config/server.chain.crt
  ssl/kickstart/src/main/java/io/deephaven/ssl/config/impl/KickstartUtils.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5144 Add exception for exponential operators providing non-descending timestamps.
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/UpdateByBucketHelper.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/em/BasePrimitiveEMOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/em/BigDecimalEMOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/em/BigIntegerEMOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/em/ByteEMOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/em/CharEMOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/em/DoubleEMOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/em/FloatEMOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/em/IntEMOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/em/LongEMOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/em/ShortEMOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/emstd/BigDecimalEmStdOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/emstd/BigIntegerEmStdOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/emstd/ByteEmStdOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/emstd/CharEmStdOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/emstd/DoubleEmStdOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/emstd/FloatEmStdOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/emstd/IntEmStdOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/emstd/LongEmStdOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/emstd/ShortEmStdOperator.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5153 GRPC support for MultiJoin, improved support for RangeJoin
  authorization/src/main/java/io/deephaven/auth/codegen/impl/TableServiceContextualAuthWiring.java
  cpp-client/deephaven/dhclient/proto/deephaven/proto/table.grpc.pb.cc
  cpp-client/deephaven/dhclient/proto/deephaven/proto/table.grpc.pb.h
  cpp-client/deephaven/dhclient/proto/deephaven/proto/table.pb.cc
  cpp-client/deephaven/dhclient/proto/deephaven/proto/table.pb.h
  go/internal/proto/table/table.pb.go
  go/internal/proto/table/table_grpc.pb.go
  proto/proto-backplane-grpc/src/main/java/io/deephaven/proto/util/OperationHelper.java
  proto/proto-backplane-grpc/src/main/proto/deephaven/proto/table.proto
  py/client/pydeephaven/proto/table_pb2.py
  py/client/pydeephaven/proto/table_pb2_grpc.py
  server/src/main/java/io/deephaven/server/grpc/GrpcErrorHelper.java
  server/src/main/java/io/deephaven/server/table/TableModule.java
  server/src/main/java/io/deephaven/server/table/ops/MultiJoinGrpcImpl.java
  server/src/main/java/io/deephaven/server/table/ops/RangeJoinGrpcImpl.java
  server/src/main/java/io/deephaven/server/table/ops/TableServiceGrpcImpl.java
  server/src/test/java/io/deephaven/server/table/ops/MultiJoinGrpcTest.java
  server/src/test/java/io/deephaven/server/table/ops/RangeJoinGrpcTest.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5145 Drop Usage of `ensureGil` from PythonDeephavenSession and Copy Current Scope
  Integrations/src/main/java/io/deephaven/integrations/python/PythonDeephavenSession.java
  engine/context/src/main/java/io/deephaven/engine/context/EmptyQueryScope.java
  engine/context/src/main/java/io/deephaven/engine/context/PoisonedQueryScope.java
  engine/context/src/main/java/io/deephaven/engine/context/QueryScope.java
  engine/context/src/main/java/io/deephaven/engine/context/StandaloneQueryScope.java
  engine/sql/src/main/java/io/deephaven/engine/sql/Sql.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/AbstractConditionFilter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/codegen/FormulaAnalyzer.java
  engine/table/src/main/java/io/deephaven/engine/util/AbstractScriptSession.java
  engine/table/src/main/java/io/deephaven/engine/util/GroovyDeephavenSession.java
  engine/table/src/main/java/io/deephaven/engine/util/NoLanguageDeephavenSession.java
  engine/table/src/main/java/io/deephaven/engine/util/PythonScope.java
  engine/table/src/main/java/io/deephaven/engine/util/PythonScopeJpyImpl.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/lang/TestQueryLanguageParser.java
  server/src/main/java/io/deephaven/server/console/ScopeTicketResolver.java
  table-api/src/main/java/io/deephaven/api/util/NameValidator.java
Labels: query engine, core, NoDocumentationNeeded, NoReleaseNotesNeeded

#5165 Introduce TableInitializationException to Propagate JobScheduler Failures
  engine/api/src/main/java/io/deephaven/engine/exceptions/TableInitializationException.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/BucketedPartitionedUpdateByManager.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/ZeroKeyUpdateByManager.java
  engine/table/src/test/java/io/deephaven/engine/util/TestJobScheduler.java
Labels: query engine, core, NoDocumentationNeeded, NoReleaseNotesNeeded

#5154 When Sorting with a Static Symbol Table use a RowKey or RowPosition ColumnSource
  engine/api/src/main/java/io/deephaven/engine/table/Table.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/SortHelpers.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/SortOperation.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/ChunkedOperatorAggregationHelper.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/ArrayBackedColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/ArraySourceHelper.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/RowIdSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/RowKeyColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/RowPositionColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/RegionedColumnSourceWithDictionary.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/PartitionedTableTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableWhereTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/sources/TestRowKeyColumnSource.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/sources/TestRowPositionColumnSource.java
Labels: query engine, core, NoDocumentationNeeded, ReleaseNotesNeeded

#5166 Fix test failures from wrapping job scheduler errors in `TableInitializationExceptions`
  engine/table/src/test/java/io/deephaven/engine/table/impl/PartitionedTableTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableWhereTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestEmMinMax.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestEmStd.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestEma.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestEms.java
Labels: bug, core, test, NoDocumentationNeeded, NoReleaseNotesNeeded

#5167 Use reader's schema for kafka avro deserialization
  extensions/kafka/src/main/java/io/deephaven/kafka/AvroImpl.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#5119 Provide more context for failed aggregation operators.
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/AggregationOperatorException.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/ChunkedOperatorAggregationHelper.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/util/TestFreezeBy.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5173 Post release bump to 0.34.0-SNAPSHOT
  R/rdeephaven/DESCRIPTION
  gradle.properties
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5174 Add "runtime" / "development" scopes to dependency submission
  .github/workflows/dependency-submission.yml
Labels: ci, NoDocumentationNeeded, NoReleaseNotesNeeded

#5178 Bump commons-compress to 1.26.0
  buildSrc/src/main/groovy/io.deephaven.java-classpath-conventions.gradle
Labels: security, NoDocumentationNeeded, NoReleaseNotesNeeded

#5180 Add optional S3 dependency to py embedded-server
  py/embedded-server/java-runtime/build.gradle
  server/jetty-app-custom/build.gradle
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5179 Bump to confluent version 7.6.0
  extensions/kafka/build.gradle
Labels: security, NoDocumentationNeeded, NoReleaseNotesNeeded

#5181 Bump calcite to 1.36.0, add json-path constraint
  sql/build.gradle
Labels: security, NoDocumentationNeeded, NoReleaseNotesNeeded

#5169 Make 'numba' a soft dependency for the Python server API
  py/server/deephaven/_dep.py
  py/server/deephaven/_udf.py
Labels: NoDocumentationNeeded, python-server-side, NoReleaseNotesNeeded

#5187 Remove old benchmark script
  .github/tools/README.md
  .github/tools/deephaven-gh-runner-init.sh
  .github/tools/metrics/benchmark_capture.py
  .github/tools/metrics/requirements.txt
  .github/tools/metrics/templates/benchmark_dashboard.json.j2
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5191 Update publish-ci to continue on certain failures
  .github/workflows/publish-ci.yml
Labels: ci, NoDocumentationNeeded, NoReleaseNotesNeeded

#5188 Quiesce `RetainedRefrenceTracker#ensureReferencesDroppedInternal` by Disabling `CLEANUP_LOG_ENABLED` by Default
  engine/updategraph/src/main/java/io/deephaven/engine/liveness/Liveness.java
Labels: core, NoDocumentationNeeded, NoReleaseNotesNeeded

#5175 More helpful error when UDF arg type check failed
  py/server/deephaven/_udf.py
  py/server/tests/test_numba_guvectorize.py
  py/server/tests/test_udf_numpy_args.py
Labels: NoDocumentationNeeded, python-server-side, NoReleaseNotesNeeded

#5195 Added fix for bug in managing context objects
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/pagestore/ColumnChunkPageStore.java
Labels: parquet, NoDocumentationNeeded, NoReleaseNotesNeeded, s3

#5196 Added py.typed marker for deephaven
  py/client/pydeephaven/py.typed
  py/client/setup.py
  py/embedded-server/deephaven_server/py.typed
  py/embedded-server/setup.py
  py/server/deephaven/py.typed
  py/server/setup.py
Labels: feature request, python, NoDocumentationNeeded, python-client, python-server-side, ReleaseNotesNeeded

#5201 Fix learn dependency issue
  py/server/deephaven/learn/__init__.py
Labels: bug, python, NoDocumentationNeeded, NoReleaseNotesNeeded, learn

#5148 Provide upperBin and lowerBin signatures that accept Durations
  engine/time/src/main/java/io/deephaven/time/DateTimeUtils.java
  engine/time/src/test/java/io/deephaven/time/TestDateTimeUtils.java
Labels: query engine, DocumentationNeeded, ReleaseNotesNeeded

#5200 Support use of DType instances in Py UDF annotations
  py/server/deephaven/_udf.py
  py/server/deephaven/dtypes.py
  py/server/tests/test_udf_return_java_values.py
Labels: NoDocumentationNeeded, python-server-side, NoReleaseNotesNeeded

#5203 Bump to jetty 11.0.20
  buildSrc/src/main/groovy/Classpaths.groovy
Labels: security, NoDocumentationNeeded, NoReleaseNotesNeeded

#5197 Improve WindowCheck memory usage.
  engine/table/build.gradle
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/TimeSeriesFilter.java
  engine/table/src/main/java/io/deephaven/engine/util/WindowCheck.java
  engine/table/src/test/java/io/deephaven/engine/util/TestWindowCheck.java
  engine/test-utils/build.gradle
  engine/test-utils/src/main/java/io/deephaven/engine/testutil/GenerateTableUpdates.java
  engine/test-utils/src/main/java/io/deephaven/engine/testutil/QueryTableTestBase.java
  engine/test-utils/src/main/java/io/deephaven/engine/testutil/testcase/RefreshingTableTestCase.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5193 Fix bugs in moveColumns and renameColumns
  engine/api/src/main/java/io/deephaven/engine/table/Table.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/BaseTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/TableAdapter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/TableDefaults.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/UncoalescedTable.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestMoveColumns.java
  py/server/deephaven/table.py
  py/server/tests/test_update_graph.py
  table-api/src/main/java/io/deephaven/api/Strings.java
Labels: bug, query engine, core, DocumentationNeeded, ReleaseNotesNeeded
