Repository deephaven/deephaven-core, pull requests merged in 2024-12, with the labels that each got.

#6434 fix: Boxed primitives trigger ClassCastException in ArrayPreview for protobuf repeated fields
  engine/table/src/main/java/io/deephaven/engine/table/impl/preview/ArrayPreview.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6451 fix: erroneous QueryCompiler retry when nothing unaccounted for
  engine/context/src/test/java/io/deephaven/engine/context/TestQueryCompiler.java
  engine/table/src/main/java/io/deephaven/engine/context/QueryCompilerImpl.java
Labels: bug, query engine, core, NoDocumentationNeeded, ReleaseNotesNeeded, point_release_candidate

#6461 fix: Boxed primitives trigger ClassCastException in ArrayPreview for protobuf repeated fields (#6434)
  engine/table/src/main/java/io/deephaven/engine/table/impl/preview/ArrayPreview.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6445 chore: Bump to 0.38.0-SNAPSHOT
  R/rdeephaven/DESCRIPTION
  cpp-client/deephaven/CMakeLists.txt
  gradle.properties
  py/client-ticking/README.md
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6460 fix: NPE in ProtobufDescriptorParserImpl for repeated nested repeated…
  extensions/protobuf/src/main/java/io/deephaven/protobuf/ProtobufDescriptorParserImpl.java
  extensions/protobuf/src/test/java/io/deephaven/protobuf/ProtobufDescriptorParserTest.java
  extensions/protobuf/src/test/proto/mytest.proto
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6448 fix: Expose TableSubscription.close() to JS (#6446)
  web/client-api/src/main/java/io/deephaven/web/client/api/subscription/AbstractTableSubscription.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded, point_release_candidate

#6463 fix: JS subscriptions should return correct size while updating
  web/client-api/src/main/java/io/deephaven/web/client/api/JsTable.java
  web/client-api/src/main/java/io/deephaven/web/client/api/subscription/AbstractTableSubscription.java
  web/client-api/src/main/java/io/deephaven/web/client/api/subscription/TableViewportSubscription.java
Labels: jsapi, NoDocumentationNeeded, ReleaseNotesNeeded, point_release_candidate

#6465 chore: Bump to jpy 1.0.0
  docker/registry/server-base/gradle.properties
  docker/server-jetty/src/main/server-jetty/requirements.txt
  docker/server/src/main/server-netty/requirements.txt
  gradle/libs.versions.toml
  py/embedded-server/setup.py
  py/server/setup.py
Labels: NoDocumentationNeeded, ReleaseNotesNeeded, point_release_candidate

#6473 fix: JS viewports must allow subscription to be changed while waiting
  web/client-api/src/main/java/io/deephaven/web/client/api/subscription/AbstractTableSubscription.java
  web/client-api/src/main/java/io/deephaven/web/client/api/subscription/TableViewportSubscription.java
  web/client-api/src/test/java/io/deephaven/web/client/api/subscription/ViewportTestGwt.java
Labels: bug, jsapi, NoDocumentationNeeded, ReleaseNotesNeeded, point_release_candidate

#6475 fix: Update Web version v0.99.2, fix table plugins props
  web/client-ui/Dockerfile
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6464 fix: JS subscriptions should return correct size while updating (#6463)
  web/client-api/src/main/java/io/deephaven/web/client/api/JsTable.java
  web/client-api/src/main/java/io/deephaven/web/client/api/subscription/AbstractTableSubscription.java
  web/client-api/src/main/java/io/deephaven/web/client/api/subscription/TableViewportSubscription.java
  web/client-api/src/test/java/io/deephaven/web/client/api/subscription/ViewportTestGwt.java
Labels: jsapi, NoDocumentationNeeded, ReleaseNotesNeeded

#6476 feat: JS clients can provide custom grpc transports
  web/client-api/src/main/java/io/deephaven/web/client/api/ConnectOptions.java
  web/client-api/src/main/java/io/deephaven/web/client/api/QueryConnectable.java
  web/client-api/src/main/java/io/deephaven/web/client/api/WorkerConnection.java
  web/client-api/src/main/java/io/deephaven/web/client/api/barrage/stream/BiDiStream.java
  web/client-api/src/main/java/io/deephaven/web/client/api/grpc/GrpcTransport.java
  web/client-api/src/main/java/io/deephaven/web/client/api/grpc/GrpcTransportFactory.java
  web/client-api/src/main/java/io/deephaven/web/client/api/grpc/GrpcTransportOptions.java
  web/client-api/src/main/java/io/deephaven/web/client/api/grpc/HeaderValueUnion.java
  web/client-api/src/main/java/io/deephaven/web/client/api/grpc/MultiplexedWebsocketTransport.java
  web/client-api/src/main/java/io/deephaven/web/client/ide/IdeConnection.java
  web/client-api/src/test/java/io/deephaven/web/ClientIntegrationTestSuite.java
  web/client-api/src/test/java/io/deephaven/web/client/api/grpc/GrpcTransportTestGwt.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/grpcweb/transports/transport/TransportOptions.java
Labels: jsapi, NoDocumentationNeeded, ReleaseNotesNeeded, point_release_candidate

#6481 chore: code cleanup, properly scope rpcWrapper context detach
  server/src/main/java/io/deephaven/server/session/SessionServiceGrpcImpl.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6477 feat: Don't fail when reading non-identity partitioning field
  extensions/iceberg/src/main/java/io/deephaven/iceberg/layout/IcebergKeyValuePartitionedLayout.java
  extensions/iceberg/src/test/java/io/deephaven/iceberg/Pyiceberg2Test.java
  extensions/iceberg/src/test/resources/io/deephaven/iceberg/sqlite/db_resource/catalogs/pyiceberg-2/trading.db/data/data/datetime_day=2024-11-26/symbol=AMZN/00000-0-d9c06748-9892-404f-a744-7bbfd06d0eeb.parquet
  extensions/iceberg/src/test/resources/io/deephaven/iceberg/sqlite/db_resource/catalogs/pyiceberg-2/trading.db/data/data/datetime_day=2024-11-26/symbol=GOOG/00000-1-d9c06748-9892-404f-a744-7bbfd06d0eeb.parquet
  extensions/iceberg/src/test/resources/io/deephaven/iceberg/sqlite/db_resource/catalogs/pyiceberg-2/trading.db/data/data/datetime_day=2024-11-27/symbol=AAPL/00000-2-d9c06748-9892-404f-a744-7bbfd06d0eeb.parquet
  extensions/iceberg/src/test/resources/io/deephaven/iceberg/sqlite/db_resource/catalogs/pyiceberg-2/trading.db/data/data/datetime_day=2024-11-27/symbol=MSFT/00000-3-d9c06748-9892-404f-a744-7bbfd06d0eeb.parquet
  extensions/iceberg/src/test/resources/io/deephaven/iceberg/sqlite/db_resource/catalogs/pyiceberg-2/trading.db/data/data/datetime_day=2024-11-28/symbol=MSFT/00000-4-d9c06748-9892-404f-a744-7bbfd06d0eeb.parquet
  extensions/iceberg/src/test/resources/io/deephaven/iceberg/sqlite/db_resource/catalogs/pyiceberg-2/trading.db/data/metadata/00000-0956ea6c-b522-447f-a2f4-5c6e7b104783.metadata.json
  extensions/iceberg/src/test/resources/io/deephaven/iceberg/sqlite/db_resource/catalogs/pyiceberg-2/trading.db/data/metadata/00001-4e3fe6dc-5e3e-4da1-9da3-666cbad70ace.metadata.json
  extensions/iceberg/src/test/resources/io/deephaven/iceberg/sqlite/db_resource/catalogs/pyiceberg-2/trading.db/data/metadata/d9c06748-9892-404f-a744-7bbfd06d0eeb-m0.avro
  extensions/iceberg/src/test/resources/io/deephaven/iceberg/sqlite/db_resource/catalogs/pyiceberg-2/trading.db/data/metadata/snap-2806418501596315192-0-d9c06748-9892-404f-a744-7bbfd06d0eeb.avro
  extensions/iceberg/src/test/resources/io/deephaven/iceberg/sqlite/db_resource/dh-iceberg-test.db
  extensions/iceberg/src/test/resources/io/deephaven/iceberg/sqlite/db_resource/generate-pyiceberg-1.py
  extensions/iceberg/src/test/resources/io/deephaven/iceberg/sqlite/db_resource/generate-pyiceberg-2.py
Labels: DocumentationNeeded, ReleaseNotesNeeded, point_release_candidate, iceberg

#6462 fix: Ensure Flight SQL acquires shared lock
  extensions/flight-sql/src/main/java/io/deephaven/server/flightsql/FlightSqlResolver.java
  extensions/flight-sql/src/main/java/io/deephaven/server/flightsql/TableCreatorScopeTickets.java
  extensions/flight-sql/src/test/java/io/deephaven/server/flightsql/FlightSqlTest.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded, point_release_candidate, sql

#6482 fix: Added support to read iceberg tables partitioned by date
  extensions/iceberg/src/main/java/io/deephaven/iceberg/base/IcebergUtils.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/layout/IcebergKeyValuePartitionedLayout.java
  extensions/iceberg/src/test/java/io/deephaven/iceberg/junit5/SqliteCatalogBase.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded, iceberg

#6483 feat: Don't fail when reading non-identity partitioning field
  extensions/iceberg/src/main/java/io/deephaven/iceberg/layout/IcebergKeyValuePartitionedLayout.java
  extensions/iceberg/src/test/java/io/deephaven/iceberg/Pyiceberg2Test.java
  extensions/iceberg/src/test/resources/io/deephaven/iceberg/sqlite/db_resource/catalogs/pyiceberg-2/trading.db/data/data/datetime_day=2024-11-26/symbol=AMZN/00000-0-d9c06748-9892-404f-a744-7bbfd06d0eeb.parquet
  extensions/iceberg/src/test/resources/io/deephaven/iceberg/sqlite/db_resource/catalogs/pyiceberg-2/trading.db/data/data/datetime_day=2024-11-26/symbol=GOOG/00000-1-d9c06748-9892-404f-a744-7bbfd06d0eeb.parquet
  extensions/iceberg/src/test/resources/io/deephaven/iceberg/sqlite/db_resource/catalogs/pyiceberg-2/trading.db/data/data/datetime_day=2024-11-27/symbol=AAPL/00000-2-d9c06748-9892-404f-a744-7bbfd06d0eeb.parquet
  extensions/iceberg/src/test/resources/io/deephaven/iceberg/sqlite/db_resource/catalogs/pyiceberg-2/trading.db/data/data/datetime_day=2024-11-27/symbol=MSFT/00000-3-d9c06748-9892-404f-a744-7bbfd06d0eeb.parquet
  extensions/iceberg/src/test/resources/io/deephaven/iceberg/sqlite/db_resource/catalogs/pyiceberg-2/trading.db/data/data/datetime_day=2024-11-28/symbol=MSFT/00000-4-d9c06748-9892-404f-a744-7bbfd06d0eeb.parquet
  extensions/iceberg/src/test/resources/io/deephaven/iceberg/sqlite/db_resource/catalogs/pyiceberg-2/trading.db/data/metadata/00000-0956ea6c-b522-447f-a2f4-5c6e7b104783.metadata.json
  extensions/iceberg/src/test/resources/io/deephaven/iceberg/sqlite/db_resource/catalogs/pyiceberg-2/trading.db/data/metadata/00001-4e3fe6dc-5e3e-4da1-9da3-666cbad70ace.metadata.json
  extensions/iceberg/src/test/resources/io/deephaven/iceberg/sqlite/db_resource/catalogs/pyiceberg-2/trading.db/data/metadata/d9c06748-9892-404f-a744-7bbfd06d0eeb-m0.avro
  extensions/iceberg/src/test/resources/io/deephaven/iceberg/sqlite/db_resource/catalogs/pyiceberg-2/trading.db/data/metadata/snap-2806418501596315192-0-d9c06748-9892-404f-a744-7bbfd06d0eeb.avro
  extensions/iceberg/src/test/resources/io/deephaven/iceberg/sqlite/db_resource/dh-iceberg-test.db
  extensions/iceberg/src/test/resources/io/deephaven/iceberg/sqlite/db_resource/generate-pyiceberg-1.py
  extensions/iceberg/src/test/resources/io/deephaven/iceberg/sqlite/db_resource/generate-pyiceberg-2.py
Labels: NoDocumentationNeeded, ReleaseNotesNeeded, iceberg

#6479 feat: JS clients can provide custom grpc transports (#6476)
  web/client-api/src/main/java/io/deephaven/web/client/api/ConnectOptions.java
  web/client-api/src/main/java/io/deephaven/web/client/api/QueryConnectable.java
  web/client-api/src/main/java/io/deephaven/web/client/api/WorkerConnection.java
  web/client-api/src/main/java/io/deephaven/web/client/api/barrage/stream/BiDiStream.java
  web/client-api/src/main/java/io/deephaven/web/client/api/grpc/GrpcTransport.java
  web/client-api/src/main/java/io/deephaven/web/client/api/grpc/GrpcTransportFactory.java
  web/client-api/src/main/java/io/deephaven/web/client/api/grpc/GrpcTransportOptions.java
  web/client-api/src/main/java/io/deephaven/web/client/api/grpc/HeaderValueUnion.java
  web/client-api/src/main/java/io/deephaven/web/client/api/grpc/MultiplexedWebsocketTransport.java
  web/client-api/src/main/java/io/deephaven/web/client/ide/IdeConnection.java
  web/client-api/src/test/java/io/deephaven/web/ClientIntegrationTestSuite.java
  web/client-api/src/test/java/io/deephaven/web/client/api/grpc/GrpcTransportTestGwt.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/grpcweb/transports/transport/TransportOptions.java
Labels: jsapi, grpc, NoDocumentationNeeded, ReleaseNotesNeeded

#6478 fix: reapply RST_STREAM(cancel) workaround, and disable grpc-timeout
  grpc-java/grpc-servlet-jakarta/src/main/java/io/grpc/servlet/jakarta/AsyncServletOutputStreamWriter.java
  grpc-java/grpc-servlet-jakarta/src/main/java/io/grpc/servlet/jakarta/ServletAdapter.java
Labels: grpc, NoDocumentationNeeded, ReleaseNotesNeeded, point_release_candidate

#6441 fix: Close Jetty h2 streams with RST_STREAM and no error code
  grpc-java/grpc-servlet-jakarta/src/main/java/io/grpc/servlet/jakarta/AsyncServletOutputStreamWriter.java
  grpc-java/grpc-servlet-jakarta/src/main/java/io/grpc/servlet/jakarta/ServletAdapter.java
  grpc-java/grpc-servlet-jakarta/src/main/java/io/grpc/servlet/jakarta/web/GrpcWebOutputStream.java
  grpc-java/grpc-servlet-jakarta/src/main/java/io/grpc/servlet/jakarta/web/GrpcWebServletRequest.java
  grpc-java/grpc-servlet-jakarta/src/main/java/io/grpc/servlet/jakarta/web/GrpcWebServletResponse.java
Labels: jsapi, grpc, NoDocumentationNeeded, python-client, ReleaseNotesNeeded

#6472 chore: Bump selenium to 4.27.0
  docker/registry/selenium/gradle.properties
  gradle/libs.versions.toml
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6489 fix: Ensure Flight SQL acquires shared lock
  extensions/flight-sql/src/main/java/io/deephaven/server/flightsql/FlightSqlResolver.java
  extensions/flight-sql/src/main/java/io/deephaven/server/flightsql/TableCreatorScopeTickets.java
  extensions/flight-sql/src/test/java/io/deephaven/server/flightsql/FlightSqlTest.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#6490 chore: Bump to jpy 1.0.0
  docker/registry/fedora/gradle.properties
  docker/registry/go/gradle.properties
  docker/registry/manylinux2014_x86_64/gradle.properties
  docker/registry/minio/gradle.properties
  docker/registry/protoc-base/gradle.properties
  docker/registry/python/gradle.properties
  docker/registry/server-base/gradle.properties
  docker/registry/slim-base/gradle.properties
  docker/server-jetty/src/main/server-jetty/requirements.txt
  docker/server/src/main/server-netty/requirements.txt
  gradle/libs.versions.toml
  py/embedded-server/setup.py
  py/server/setup.py
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#6491 fix: erroneous QueryCompiler retry when nothing unaccounted for
  engine/context/src/test/java/io/deephaven/engine/context/TestQueryCompiler.java
  engine/table/src/main/java/io/deephaven/engine/context/QueryCompilerImpl.java
Labels: bug, core, NoDocumentationNeeded, ReleaseNotesNeeded

#6492 chore: Bump to 0.37.2-SNAPSHOT
  R/rdeephaven/DESCRIPTION
  cpp-client/deephaven/CMakeLists.txt
  gradle.properties
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6498 fix: Correct two errors in generated types
  web/client-api/src/main/java/io/deephaven/web/client/api/QueryConnectable.java
  web/client-api/src/main/java/io/deephaven/web/client/api/event/Event.java
  web/client-api/src/main/java/io/deephaven/web/client/api/grpc/GrpcTransportFactory.java
  web/client-api/types/build.gradle
Labels: documentation, jsapi, NoDocumentationNeeded, ReleaseNotesNeeded, point_release_candidate

#6499 chore: Fix broken proto link in README
  README.md
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6500 chore: Give link checker write permissions
  .github/workflows/links.yml
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6502 fix: correct instantiation of `rollup` `count_where` operator.
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/AggregationProcessor.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestRollup.java
  py/server/tests/test_rollup_tree_table.py
Labels: bug, NoDocumentationNeeded, NoReleaseNotesNeeded
