Repository deephaven/deephaven-core, pull requests merged in 2024-10, with the labels that each got.

#6108 chore: Bump gradle to 8.10.2
  gradle/wrapper/gradle-wrapper.properties
Labels: NoDocumentationNeeded, version-bump, trivial, NoReleaseNotesNeeded

#6158 fix: JS API should pass date/number formatting to UI
  web/client-api/src/main/java/io/deephaven/web/client/api/barrage/def/ColumnDefinition.java
  web/client-api/src/test/java/io/deephaven/web/client/api/subscription/ViewportTestGwt.java
Labels: jsapi, NoDocumentationNeeded, release blocker, ReleaseNotesNeeded

#6130 feat: Added support to specify AWS profile through S3 instructions
  extensions/iceberg/s3/src/test/java/io/deephaven/iceberg/util/IcebergLocalStackTest.java
  extensions/iceberg/s3/src/test/java/io/deephaven/iceberg/util/IcebergMinIOTest.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/S3ParquetLocalStackTest.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/S3ParquetMinIOTest.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/S3ParquetTestBase.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/AnonymousCredentials.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/AwsSdkV2Credentials.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/BasicCredentials.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/Credentials.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/DefaultCredentials.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/ProfileCredentials.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/ResolvingCredentials.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3AsyncClientFactory.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3CompletableOutputStream.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3Instructions.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3Utils.java
  extensions/s3/src/test/java/io/deephaven/extensions/s3/S3InstructionsTest.java
  extensions/s3/src/test/java/io/deephaven/extensions/s3/testlib/SingletonContainers.java
  py/server/deephaven/experimental/s3.py
  py/server/tests/test_s3_instructions.py
Labels: feature request, DocumentationNeeded, ReleaseNotesNeeded, s3, iceberg

#6167 fix(py-test): Wait for Full Cycle Before Checking if SubTable Failed
  py/server/tests/test_table.py
Labels: python, test, NoDocumentationNeeded, NoReleaseNotesNeeded

#6173 fix: Connection errors should be correctly passed to the UI
  web/client-api/src/main/java/io/deephaven/web/client/api/HasEventHandling.java
  web/client-api/src/main/java/io/deephaven/web/client/api/QueryConnectable.java
  web/client-api/src/main/java/io/deephaven/web/client/api/WorkerConnection.java
Labels: jsapi, NoDocumentationNeeded, ReleaseNotesNeeded

#6178 chore: remove superfluous TODO
  proto/proto-backplane-grpc/src/main/proto/deephaven/proto/table.proto
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6182 fix: Rename SortedRanges.longSparseCapacity property to longSparseMaxCapacity for consistency.
  engine/rowset/src/main/java/io/deephaven/engine/rowset/impl/sortedranges/SortedRanges.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6184 fix: Ensure ParquetTools.readTable attaches the inferred definition
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/ParquetInstructions.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/ParquetTools.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6183 fix: Added support to read parquet files with empty row groups
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/location/ParquetTableLocation.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/ParquetTableReadWriteTest.java
  extensions/parquet/table/src/test/resources/ReferenceParquetWithEmptyRowGroup1.parquet
  extensions/parquet/table/src/test/resources/ReferenceParquetWithEmptyRowGroup2.parquet
  extensions/parquet/table/src/test/resources/datasetWithEmptyRowgroups/file1.parquet
  extensions/parquet/table/src/test/resources/datasetWithEmptyRowgroups/file2.parquet
  extensions/parquet/table/src/test/resources/datasetWithEmptyRowgroups/file3.parquet
Labels: parquet, NoDocumentationNeeded, ReleaseNotesNeeded

#6188 feat: Add manual parquet testing for deephaven-core-test-data
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/ParquetToolsTestDataTest.java
Labels: test, parquet, NoDocumentationNeeded, NoReleaseNotesNeeded

#6191 feat: Use REST Catalog config properties for DataInstructionsProviderPlugin
  extensions/iceberg/s3/src/main/java/io/deephaven/iceberg/util/IcebergToolsS3.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/IcebergCatalogAdapter.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/IcebergTools.java
Labels: DocumentationNeeded, NoReleaseNotesNeeded, iceberg

#6197 fix(test): Eliminate Race Between LivenessScope Closing and GC
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableAjTest.java
Labels: bug, NoDocumentationNeeded, NoReleaseNotesNeeded

#6192 fix: Remove 'uri' as required Iceberg property
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/IcebergTools.java
  py/server/deephaven/experimental/iceberg.py
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded, iceberg

#6205 fix: Fix chunk filling loop bug that broke rollup snapshots with viewports bigger than 512 rows
  engine/table/src/main/java/io/deephaven/engine/table/impl/hierarchical/HierarchicalTableImpl.java
Labels: bug, query engine, core, NoDocumentationNeeded, user-reported, ReleaseNotesNeeded, rollup

#6199 fix: Capture QueryCompiler for plotting PartitionedTable transform
  Plot/src/main/java/io/deephaven/plot/AxesImpl.java
  Plot/src/main/java/io/deephaven/plot/filters/SelectableDataSet.java
  Plot/src/test/java/io/deephaven/plot/example_plots/SimpleXYTable.java
Labels: bug, plotting, NoDocumentationNeeded, ReleaseNotesNeeded

#6202 fix: JS API rollups with unique aggs must specify null sentinel
  web/client-api/src/main/java/io/deephaven/web/client/api/tree/JsRollupConfig.java
  web/client-api/src/main/java/io/deephaven/web/public/rollup.html
  web/client-api/src/test/java/io/deephaven/web/client/api/HierarchicalTableTestGwt.java
Labels: jsapi, NoDocumentationNeeded, ReleaseNotesNeeded, rollup

#6196 feat: Read parquet metadata files with custom table definition
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/ParquetFileReader.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/ParquetTools.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/layout/ParquetMetadataFileLayout.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/ParquetDeephavenExamplesTest.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/ParquetTableReadWriteTest.java
  extensions/s3/src/test/java/io/deephaven/extensions/s3/CredentialsTest.java
  extensions/s3/src/test/java/io/deephaven/extensions/s3/S3InstructionsTest.java
Labels: feature request, parquet, NoDocumentationNeeded, ReleaseNotesNeeded

#6207 test: Added reference parquet files and tests for ObjectCodec implementations
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestCodecColumns.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestMapCodecColumns.java
  engine/table/src/test/resources/ReferenceParquetWithCodecColumns.parquet
  engine/table/src/test/resources/ReferenceParquetWithMapCodecData.parquet
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/ParquetTableReadWriteTest.java
  extensions/parquet/table/src/test/resources/ReferenceParquetWithCodecData.parquet
  extensions/parquet/table/src/test/resources/ReferenceParquetWithRowsetCodecData.parquet
Labels: test, parquet, NoDocumentationNeeded, NoReleaseNotesNeeded

#6209 docs: Add note about flag for protoc 3.12.x - 3.14.x
  authorization/README.md
Labels: documentation, NoDocumentationNeeded, NoReleaseNotesNeeded

#6198 feat: Support windows build for py/client-ticking
  py/client-ticking/README.md
  py/client-ticking/setup.py
  py/client-ticking/src/pydeephaven_ticking/table_listener.py
  py/client/requirements-dev.txt
  py/client/tests/test_console.py
  py/client/tests/test_multi_session.py
  py/client/tests/test_session.py
  py/client/tests/test_table.py
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6212 fix: Don't try to expose TypedTicket through JS API
  web/client-api/src/main/java/io/deephaven/web/client/api/JsPartitionedTable.java
  web/client-api/src/main/java/io/deephaven/web/client/api/tree/JsTreeTable.java
Labels: documentation, jsapi, NoDocumentationNeeded, NoReleaseNotesNeeded

#6211 fix: Subscribing to an uncoalesced table must not make it seem coalesced
  web/client-api/src/main/java/io/deephaven/web/client/api/Column.java
  web/client-api/src/main/java/io/deephaven/web/client/api/JsTable.java
  web/client-api/src/main/java/io/deephaven/web/client/state/ClientTableState.java
Labels: jsapi, NoDocumentationNeeded, release blocker, ReleaseNotesNeeded

#6217 fix: For iceberg test failures with unclosed ResolvingFileIO instance
  extensions/iceberg/s3/src/test/java/io/deephaven/iceberg/util/IcebergToolsTest.java
  extensions/iceberg/src/test/java/io/deephaven/iceberg/TestCatalog/IcebergTestCatalog.java
  extensions/iceberg/src/test/java/io/deephaven/iceberg/TestCatalog/IcebergTestTable.java
Labels: test, NoDocumentationNeeded, NoReleaseNotesNeeded

#6213 feat: Add register to CleanupReferenceProcessor
  Util/src/main/java/io/deephaven/util/reference/CleanupReferenceProcessor.java
  Util/src/test/java/io/deephaven/util/reference/CleanupReferenceProcessorTest.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6204 feat: Add add_only_to_blink() function
  engine/table/src/main/java/io/deephaven/engine/table/impl/AddOnlyToBlinkTableAdapter.java
  py/server/deephaven/stream/__init__.py
  py/server/tests/test_table_factory.py
Labels: DocumentationNeeded, python-server-side, ReleaseNotesNeeded

#6091 chore: Bump commons-text to 1.12.0
  engine/context/build.gradle
  gradle/libs.versions.toml
Labels: NoDocumentationNeeded, version-bump, NoReleaseNotesNeeded

#6222 chore: Update dependabot pull request limit
  .github/dependabot.yml
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6269 chore: Add nightly test coverage for dependabot PRs
  .github/workflows/nightly-check-ci.yml
Labels: ci, NoDocumentationNeeded, NoReleaseNotesNeeded

#6195 feat: Add slice API for gRPC and pydeephaven
  authorization/src/main/java/io/deephaven/auth/codegen/impl/TableServiceContextualAuthWiring.java
  go/internal/proto/table/table.pb.go
  go/internal/proto/table/table_grpc.pb.go
  proto/proto-backplane-grpc/src/main/java/io/deephaven/proto/util/OperationHelper.java
  proto/proto-backplane-grpc/src/main/proto/deephaven/proto/table.proto
  py/client/pydeephaven/_table_interface.py
  py/client/pydeephaven/_table_ops.py
  py/client/pydeephaven/proto/table_pb2.py
  py/client/pydeephaven/proto/table_pb2_grpc.py
  py/client/pydeephaven/table.py
  py/client/tests/test_table.py
  py/server/deephaven/table.py
  server/src/main/java/io/deephaven/server/table/TableModule.java
  server/src/main/java/io/deephaven/server/table/ops/SliceGrpcImpl.java
  server/src/main/java/io/deephaven/server/table/ops/TableServiceGrpcImpl.java
  server/src/test/java/io/deephaven/server/table/ops/SliceGrpcTest.java
Labels: grpc, DocumentationNeeded, python-client, ReleaseNotesNeeded

#6098 chore: Bump spockframework to 2.3-groovy-3.0
  gradle/libs.versions.toml
Labels: NoDocumentationNeeded, version-bump, NoReleaseNotesNeeded

#6215 fix: Wrap TicketRouter flightInfoFor and resolve calls with wrapAsFailedExport
  server/src/main/java/io/deephaven/server/session/TicketRouter.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#5378 feat: Only initialize BusinessCalendar caches when data is accessed and improve caching performance
  Generators/src/main/java/io/deephaven/libs/StaticCalendarMethodsGenerator.java
  engine/time/src/main/java/io/deephaven/time/calendar/BusinessCalendar.java
  engine/time/src/main/java/io/deephaven/time/calendar/Calendar.java
  engine/time/src/main/java/io/deephaven/time/calendar/CalendarDay.java
  engine/time/src/main/java/io/deephaven/time/calendar/ReadOptimizedConcurrentCache.java
  engine/time/src/main/java/io/deephaven/time/calendar/YearMonthSummaryCache.java
  engine/time/src/test/java/io/deephaven/time/calendar/TestBusinessCalendar.java
  engine/time/src/test/java/io/deephaven/time/calendar/TestCalendar.java
  engine/time/src/test/java/io/deephaven/time/calendar/TestCalendarDay.java
  engine/time/src/test/java/io/deephaven/time/calendar/TestReadOptimizedConcurrentCache.java
  engine/time/src/test/java/io/deephaven/time/calendar/TestStaticCalendarMethods.java
  engine/time/src/test/java/io/deephaven/time/calendar/TestYearMonthSummaryCache.java
Labels: query engine, NoDocumentationNeeded, NoReleaseNotesNeeded, devrel-watch, March2024

#6274 fix: Ensure surefire-action-report for nightly only runs on main
  .github/workflows/nightly-check-ci.yml
Labels: ci, NoDocumentationNeeded, NoReleaseNotesNeeded

#6286 chore(gradle): Upgrade JavaParser to 3.26.2
  engine/table/src/main/java/io/deephaven/engine/table/impl/ShiftedColumnsFactory.java
  gradle/libs.versions.toml
Labels: core, NoDocumentationNeeded, version-bump, ReleaseNotesNeeded

#6272 feat: Add slice API for TableOperations
  engine/api/src/main/java/io/deephaven/engine/table/Table.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/partitioned/PartitionedTableProxyImpl.java
  java-client/session-dagger/src/test/java/io/deephaven/client/SliceTest.java
  java-client/session/src/main/java/io/deephaven/client/impl/BatchTableRequestBuilder.java
  qst/src/main/java/io/deephaven/qst/TableAdapterImpl.java
  qst/src/main/java/io/deephaven/qst/table/ParentsVisitor.java
  qst/src/main/java/io/deephaven/qst/table/SliceTable.java
  qst/src/main/java/io/deephaven/qst/table/TableBase.java
  qst/src/main/java/io/deephaven/qst/table/TableLabelVisitor.java
  qst/src/main/java/io/deephaven/qst/table/TableSpec.java
  qst/src/main/java/io/deephaven/qst/table/TableVisitorGeneric.java
  table-api/src/main/java/io/deephaven/api/TableOperations.java
  table-api/src/main/java/io/deephaven/api/TableOperationsAdapter.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6168 ci: Add link checking to CI
  .github/workflows/links.yml
Labels: ci, NoDocumentationNeeded, NoReleaseNotesNeeded

#6285 feat: Add arrow Schema as supported type
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/DefaultChunkInputStreamGeneratorFactory.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/DefaultChunkReadingFactory.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/ArrowIpcUtil.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/BarrageUtil.java
  extensions/barrage/src/test/java/io/deephaven/extensions/barrage/util/ArrowIpcUtilTest.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6292 chore: Fix some broken links
  authentication/example-providers/README.md
  licenses/DCL-notice-template.md
  web/client-api/src/main/java/io/deephaven/web/public/linked/index.html
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6291 chore: Track links to omit in lychee
  .lycheeignore
Labels: size:1, NoDocumentationNeeded, NoReleaseNotesNeeded, github_actions

#6303 chore: Update gradle enterprise plugin to develocity plugin
  settings.gradle
Labels: build, NoDocumentationNeeded, version-bump, NoReleaseNotesNeeded

#6268 feat!: Updated API for Iceberg read operations
  extensions/iceberg/s3/src/test/java/io/deephaven/iceberg/util/IcebergToolsTest.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/layout/IcebergBaseLayout.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/layout/IcebergFlatLayout.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/layout/IcebergKeyValuePartitionedLayout.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/IcebergInstructions.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/IcebergReadInstructions.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/IcebergTable.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/IcebergTableAdapter.java
  extensions/iceberg/src/test/java/io/deephaven/iceberg/PyIceberg1Test.java
  py/server/deephaven/experimental/iceberg.py
  py/server/tests/test_iceberg.py
Labels: DocumentationNeeded, breaking, ReleaseNotesNeeded, iceberg

#6290 build: Remove dependency for hadoop-hdfs-client
  extensions/iceberg/build.gradle
  gradle/libs.versions.toml
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6305 chore: bump registry images
  docker/registry/cpp-clients-multi-base/gradle.properties
  docker/registry/fedora/gradle.properties
  docker/registry/go/gradle.properties
  docker/registry/localstack/gradle.properties
  docker/registry/manylinux2014_x86_64/gradle.properties
  docker/registry/minio/gradle.properties
  docker/registry/protoc-base/gradle.properties
  docker/registry/python/gradle.properties
  docker/registry/server-base/gradle.properties
  docker/registry/slim-base/gradle.properties
  docker/server-jetty/src/main/server-jetty/requirements.txt
  docker/server/src/main/server-netty/requirements.txt
  py/client-ticking/build.gradle
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6300 chore: Update lychee ignore file
  .lycheeignore
  README.md
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6110 feat: Support all java.lang.Math in the query language
  engine/function/src/templates/Numeric.ftl
  engine/function/src/templates/TestNumeric.ftl
  engine/table/src/main/java/io/deephaven/libs/GroovyStaticImports.java
Labels: query engine, DocumentationNeeded, ReleaseNotesNeeded

#6313 fix: WouldMatch does not properly memoize.
  engine/table/src/main/java/io/deephaven/engine/table/impl/MemoizedOperationKey.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/WouldMatchOperation.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/MatchFilter.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableWhereTest.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded
