Repository deephaven/deephaven-core, pull requests merged in 2025-06, with the labels that each got.

#6932 fix: DH-19570: UnionSourceManager Should Not Inspect Stale Slot Location Entries
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/UnionRedirection.java
  engine/table/src/test/java/io/deephaven/engine/util/TestTableTools.java
Labels: bug, query engine, core, NoDocumentationNeeded, ReleaseNotesNeeded

#6937 fix: DH-19593: Min Max Secondary Operators Can Have Wrong Type
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/AggregationProcessor.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/by/AggregationProcessorTest.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6938 chore: Bump to 0.39.4
  R/rdeephaven/DESCRIPTION
  cpp-client/deephaven/CMakeLists.txt
  gradle.properties
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6941 feat: add AWS SessionCredentials to S3 module
  extensions/s3/src/main/java/io/deephaven/extensions/s3/Credentials.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/SessionCredentials.java
  extensions/s3/src/test/java/io/deephaven/extensions/s3/CredentialsTest.java
  py/server/deephaven/experimental/s3.py
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6942 refactor: DH-19625: Refactor Rebase Definition Check into Utility Method.
  engine/table/src/main/java/io/deephaven/engine/table/impl/hierarchical/HierarchicalTableImpl.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/hierarchical/RollupTableImpl.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/hierarchical/TreeTableImpl.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6953 fix: NPE in UnionSourceManager When Constituent Fails
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/UnionSourceManager.java
  engine/table/src/test/java/io/deephaven/engine/util/TestTableTools.java
Labels: bug, query engine, core, NoDocumentationNeeded, ReleaseNotesNeeded, point_release_candidate

#6954 test: add nested field Parquet column resolver test
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/TestParquetTools.java
  extensions/parquet/table/src/test/resources/NestedStruct3.parquet
Labels: parquet, NoDocumentationNeeded, NoReleaseNotesNeeded

#6956 fix: NPE in UnionSourceManager When Constituent Fails
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/UnionSourceManager.java
  engine/table/src/test/java/io/deephaven/engine/util/TestTableTools.java
Labels: bug, query engine, core, NoDocumentationNeeded, ReleaseNotesNeeded

#6944 fix: DH-19549: Bug fixes for pushdown predicate
  engine/table/src/main/java/io/deephaven/engine/table/impl/AbstractColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/AbstractFilterExecution.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/PushdownFilterMatcher.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/locations/impl/AbstractTableLocation.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/RegionedColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/RegionedColumnSourceBase.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/RegionedColumnSourceManager.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableWhereTest.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/location/ParquetTableLocation.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/ParquetTableFilterTest.java
  extensions/parquet/table/src/test/resources/NestedStruct3.parquet
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6957 fix: DH-19694: Add the check for the new variant of agg formula
  py/server/deephaven/agg.py
  py/server/tests/test_table.py
Labels: python, NoDocumentationNeeded, NoReleaseNotesNeeded

#6943 feat: DH-19501: Expose Aggregated Columns in JSTreeTable
  web/client-api/src/main/java/io/deephaven/web/client/api/tree/JsTreeTable.java
  web/client-api/src/test/java/io/deephaven/web/client/api/HierarchicalTableTestGwt.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6961 feat: DH-19501: Expose Aggregated Columns in JSTreeTable (#6943)
  web/client-api/src/main/java/io/deephaven/web/client/api/tree/JsTreeTable.java
  web/client-api/src/test/java/io/deephaven/web/client/api/HierarchicalTableTestGwt.java
Labels: jsapi, NoDocumentationNeeded, NoReleaseNotesNeeded

#6965 fix: DH-19713: Lots of columns produce filename to long for generated hashers.
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/typed/TypedHasherFactory.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableAggregationTest.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6966 feat: Make newTable and mergeTables available from IdeConnection
  web/client-api/src/main/java/io/deephaven/web/client/ide/IdeConnection.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6970 chore: Bump to 0.39.5
  R/rdeephaven/DESCRIPTION
  cpp-client/deephaven/CMakeLists.txt
  gradle.properties
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded
