Repository deephaven/deephaven-core, pull requests merged in 2025-09, with the labels that each got.

#7136 feat: DH-18062: Make IcebergCatalogAdapter Closeable
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/IcebergCatalogAdapter.java
  extensions/iceberg/src/test/java/io/deephaven/iceberg/junit5/SqliteCatalogBase.java
  py/server/deephaven/experimental/iceberg.py
  py/server/tests/test_iceberg.py
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#7147 fix: DH-20103 Improve error message for unsupported Timestamp column data types
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/UpdateBy.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestUpdateByGeneral.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#7153 feat(csharp/client): DH-20309: Simplify the SharableDict implementation. Add Unit Tests
  csharp/client/Dh_NetClient/AssemblyInfo.cs
  csharp/client/Dh_NetClient/sharables/Bitset64.cs
  csharp/client/Dh_NetClient/sharables/NodeHelpers.cs
  csharp/client/Dh_NetClient/sharables/SharableDict.cs
  csharp/client/Dh_NetClient/sharables/immutable/Destructuring.cs
  csharp/client/Dh_NetClient/sharables/immutable/ImmutableBase.cs
  csharp/client/Dh_NetClient/sharables/immutable/ImmutableLeaf.cs
  csharp/client/Dh_NetClient/sharables/immutable/ImmutableNode.cs
  csharp/client/Dh_NetClient/util/SharableDict.cs
  csharp/client/Dh_NetClientTests/AggregatesTest.cs
  csharp/client/Dh_NetClientTests/Dh_NetClientTests.sln.DotSettings.user
  csharp/client/Dh_NetClientTests/SharableDictTest.cs
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#7109 feat: DH-19410: Add multiple row-group write support
  docs/groovy/how-to-guides/data-import-export/parquet-instructions.md
  docs/python/how-to-guides/data-import-export/parquet-export.md
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/ParquetInstructions.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/ParquetTableWriter.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/RowGroupTableIteratorVisitor.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/location/ParquetTableLocation.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/metadata/RowGroupInfo.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/ParquetInstructionsTest.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/ParquetTableReadWriteTest.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/TestRowGroupTableIteratorVisitor.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/metadata/TestRowGroupInfo.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/metadata/TestRowGroupInfoVisitor.java
  py/server/deephaven/parquet.py
  py/server/tests/test_parquet.py
Labels: DocumentationNeeded, ReleaseNotesNeeded

#7188 fix: DH-20379: Python scope does not work in format_columns
  py/server/deephaven/table.py
  py/server/tests/test_table.py
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#7193 revert: "ci: Skip Java checks if only docs have changed"
  .github/workflows/check-ci.yml
  .github/workflows/publish-ci.yml
  .github/workflows/quick-ci.yml
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#7200 feat: DH-19889: Converted TableInfo to copyable style
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/metadata/TableInfo.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/metadata/TestTableInfo.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#7197 fix: DH-20416: fix docs-ci workflow so it doesn't fail on forks
  .github/workflows/docs-ci.yml
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#7191 feat: DH-20385: migrate to ZoneId
  Base/src/main/java/io/deephaven/base/log/LogOutput.java
  Base/src/main/java/io/deephaven/base/text/TimestampBuffer.java
  Base/src/main/java/io/deephaven/base/text/TimestampBufferMicros.java
  Base/src/test/java/io/deephaven/base/text/TestConvert.java
  Configuration/src/main/java/io/deephaven/configuration/Configuration.java
  IO/src/main/java/io/deephaven/io/logger/LoggerImpl.java
  IO/src/main/java/io/deephaven/io/logger/NullLoggerImpl.java
  IO/src/main/java/io/deephaven/io/logger/ProcessStreamLoggerImpl.java
  Stats/src/main/java/io/deephaven/stats/StatsDriver.java
  log-factory/sinks/log-to-file/src/main/java/io/deephaven/internal/log/LoggerFactoryFile.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#7206 chore: Bump to 0.41.0
  R/rdeephaven/DESCRIPTION
  cpp-client/deephaven/CMakeLists.txt
  gradle.properties
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#7227 docs: Fix broken links in Groovy "generate query strings" doc
  docs/groovy/how-to-guides/generate-query-strings.md
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#7224 chore: Bump docker images
  docker/registry/go/gradle.properties
  docker/registry/manylinux2014_x86_64/gradle.properties
  docker/registry/minio/gradle.properties
  docker/registry/protoc-base/gradle.properties
  docker/registry/python/gradle.properties
  docker/registry/server-base/gradle.properties
  docker/registry/slim-base/gradle.properties
  docker/server-jetty/src/main/server-jetty/requirements.txt
  docker/server/src/main/server-netty/requirements.txt
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#7228 fix: DH-20448, DH-20449: Better schema information for complex types
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/DefaultChunkReaderFactory.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/BarrageUtil.java
  server/jetty/src/test/java/io/deephaven/server/jetty/BarrageChunkFactoryTest.java
  server/src/test/java/io/deephaven/server/barrage/BarrageMessageRoundTripTest.java
  server/test-utils/src/main/java/io/deephaven/server/test/FlightMessageRoundTripTest.java
  web/client-api/src/main/java/io/deephaven/web/client/api/barrage/WebChunkReaderFactory.java
  web/client-api/src/test/java/io/deephaven/web/client/api/subscription/ViewportTestGwt.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded, point_release_candidate

#7235 ci: DH-20496: Delete unused tools from runner in nightly workflow. Add some disk space instrumentation.
  .github/workflows/nightly-check-ci.yml
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#7236 chore: Bump to 0.40.2
  R/rdeephaven/DESCRIPTION
  cpp-client/deephaven/CMakeLists.txt
  gradle.properties
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#7239 ci: DH-20496: Also delete unused tools from check workflow.
  .github/workflows/check-ci.yml
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#7062 feat: DH-19475 predicate pushdown - parquet dictionary support
  engine/table/src/main/java/io/deephaven/engine/table/impl/AbstractFilterExecution.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/BasePushdownFilterContext.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/PushdownResult.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/ConditionFilter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/UnionSourceManager.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/RegionedColumnSourceManager.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/ColumnWriterImpl.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/ParquetFileWriter.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/RowGroupWriterImpl.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/ParquetInstructions.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/ParquetTableWriter.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/location/ParquetColumnLocation.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/location/ParquetTableLocation.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/ParquetTableFilterTest.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/ParquetTableReadWriteTest.java
  extensions/parquet/table/src/test/resources/ReferenceParquetWithDictionaryAndEmptyRowGroups.parquet
Labels: DocumentationNeeded, ReleaseNotesNeeded

#7249 docs: Nightly validation fixes
  docs/groovy/how-to-guides/data-import-export/iceberg.md
  docs/groovy/reference/data-import-export/Iceberg/iceberg-table-writer.md
  docs/groovy/tutorials/crash-course/configure.md
  docs/python/getting-started/crash-course/configure.md
  docs/python/getting-started/crash-course/export-data.md
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#7251 ci: Consolidate nightly docs slack notifications
  .github/workflows/nightly-docs.yml
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#7253 ci: Skip Java checks if only docs have changed while still passing required checks
  .github/workflows/check-ci.yml
  .github/workflows/publish-ci.yml
  .github/workflows/quick-ci.yml
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#7254 ci: Fix skipping checks for docs only changes on push
  .github/workflows/check-ci.yml
  .github/workflows/publish-ci.yml
  .github/workflows/quick-ci.yml
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded
