Repository deephaven/deephaven-core, pull requests merged in 2025-04, with the labels that each got.

#6740 fix: ListFields should always return up-to-date snapshot
  server/src/main/java/io/deephaven/server/appmode/ApplicationServiceGrpcImpl.java
  server/src/test/java/io/deephaven/server/appmode/ApplicationServiceGrpcImplTest.java
Labels: grpc, NoDocumentationNeeded, ReleaseNotesNeeded

#6751 fix: PartitioningColumnDataIndex fix empty added rowsets and last notification step
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/PartitioningColumnDataIndex.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestPartitionAwareSourceTableNoMocks.java
Labels: bug, core, NoDocumentationNeeded, ReleaseNotesNeeded, point_release_candidate

#6754 feat: DH-19123: Improve Documentation around TableUpdate RowSet resource management.
  Integrations/src/main/java/io/deephaven/integrations/python/PythonReplayListenerAdapter.java
  engine/api/src/main/java/io/deephaven/engine/table/TableUpdate.java
  engine/api/src/test/java/io/deephaven/engine/table/TableUpdateTest.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/BaseTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/TableUpdateImpl.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#6721 feat: DH-18258: Improved handling of maximum concurrent write requests to S3
  Util/channel/src/main/java/io/deephaven/util/channel/CachedChannelProvider.java
  Util/channel/src/main/java/io/deephaven/util/channel/SeekableChannelContext.java
  Util/channel/src/main/java/io/deephaven/util/channel/SeekableChannelsProvider.java
  Util/channel/src/main/java/io/deephaven/util/channel/SeekableChannelsProviderDelegate.java
  Util/channel/src/test/java/io/deephaven/util/channel/CachedChannelProviderTest.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/layout/IcebergKeyValuePartitionedLayout.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/ParquetFileReader.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/ParquetTools.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/pagestore/ColumnChunkPageStore.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3CompletableOutputStream.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3DelegateProvider.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3Instructions.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3ReadContext.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3ReadRequest.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3ReadRequestCache.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3SeekableByteChannel.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3SeekableChannelProvider.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3WriteContext.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3WriteRequest.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/UniversalS3Provider.java
  extensions/s3/src/test/java/io/deephaven/extensions/s3/S3SeekableChannelSimpleTestBase.java
  extensions/trackedfile/src/main/java/io/deephaven/extensions/trackedfile/LocalCompletableOutputStream.java
  extensions/trackedfile/src/main/java/io/deephaven/extensions/trackedfile/TrackedSeekableChannelsProvider.java
Labels: feature request, NoDocumentationNeeded, ReleaseNotesNeeded, s3

#6588 fix: Make the TDS size-sub-failure test more deterministic
  py/server/tests/test_table_data_service.py
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6758 fix: DH-18515: Barrage ChunkReaders Now Consistently Set Size When outChunk is Supplied
  engine/base/src/main/java/io/deephaven/engine/table/impl/ContextWithChunk.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/BaseChunkReader.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/BooleanChunkReader.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/ByteChunkReader.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/CharChunkReader.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/DoubleChunkReader.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/FixedWidthChunkReader.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/FloatChunkReader.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/IntChunkReader.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/LongChunkReader.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/MapChunkReader.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/NullChunkReader.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/ShortChunkReader.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/TransformingChunkReader.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/UnionChunkReader.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/VarBinaryChunkReader.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/array/BooleanArrayExpansionKernel.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/array/BoxedBooleanArrayExpansionKernel.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/array/ByteArrayExpansionKernel.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/array/CharArrayExpansionKernel.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/array/DoubleArrayExpansionKernel.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/array/FloatArrayExpansionKernel.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/array/IntArrayExpansionKernel.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/array/LongArrayExpansionKernel.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/array/ObjectArrayExpansionKernel.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/array/ShortArrayExpansionKernel.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/vector/BooleanVectorExpansionKernel.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/vector/ByteVectorExpansionKernel.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/vector/CharVectorExpansionKernel.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/vector/DoubleVectorExpansionKernel.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/vector/FloatVectorExpansionKernel.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/vector/IntVectorExpansionKernel.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/vector/LongVectorExpansionKernel.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/vector/ObjectVectorExpansionKernel.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/vector/ShortVectorExpansionKernel.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/BarrageMessageReaderImpl.java
  extensions/barrage/src/test/java/io/deephaven/extensions/barrage/chunk/BarrageColumnRoundTripTest.java
  server/jetty/src/test/java/io/deephaven/server/jetty/BarrageChunkFactoryTest.java
  web/client-api/src/main/java/io/deephaven/web/client/api/BigDecimalWrapper.java
  web/client-api/src/main/java/io/deephaven/web/client/api/BigIntegerWrapper.java
  web/client-api/src/main/java/io/deephaven/web/client/api/barrage/WebBarrageMessageReader.java
  web/client-api/src/main/java/io/deephaven/web/client/api/barrage/WebChunkReaderFactory.java
  web/client-api/src/test/java/io/deephaven/web/client/api/widget/plot/ChartDataTestGwt.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#6743 feat: DH-18249 Improved handling of data index on partitioning column
  engine/table/src/main/java/io/deephaven/engine/table/impl/indexer/DataIndexer.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/RegionedColumnSourceManager.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/ParquetInstructions.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/ParquetTools.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/ParquetTableReadWriteTest.java
  extensions/parquet/table/src/test/resources/referencePartitionedDataWithIndexOnPC/PC1=/PC2=0/.dh_metadata/indexes/PC1/index_PC1_data.parquet
  extensions/parquet/table/src/test/resources/referencePartitionedDataWithIndexOnPC/PC1=/PC2=0/.dh_metadata/indexes/PC2/index_PC2_data.parquet
  extensions/parquet/table/src/test/resources/referencePartitionedDataWithIndexOnPC/PC1=/PC2=0/data.parquet
  extensions/parquet/table/src/test/resources/referencePartitionedDataWithIndexOnPC/PC1=/PC2=1/.dh_metadata/indexes/PC1/index_PC1_data.parquet
  extensions/parquet/table/src/test/resources/referencePartitionedDataWithIndexOnPC/PC1=/PC2=1/.dh_metadata/indexes/PC2/index_PC2_data.parquet
  extensions/parquet/table/src/test/resources/referencePartitionedDataWithIndexOnPC/PC1=/PC2=1/data.parquet
  extensions/parquet/table/src/test/resources/referencePartitionedDataWithIndexOnPC/PC1=/PC2=2/.dh_metadata/indexes/PC1/index_PC1_data.parquet
  extensions/parquet/table/src/test/resources/referencePartitionedDataWithIndexOnPC/PC1=/PC2=2/.dh_metadata/indexes/PC2/index_PC2_data.parquet
  extensions/parquet/table/src/test/resources/referencePartitionedDataWithIndexOnPC/PC1=/PC2=2/data.parquet
  extensions/parquet/table/src/test/resources/referencePartitionedDataWithIndexOnPC/PC1=1/PC2=0/.dh_metadata/indexes/PC1/index_PC1_data.parquet
  extensions/parquet/table/src/test/resources/referencePartitionedDataWithIndexOnPC/PC1=1/PC2=0/.dh_metadata/indexes/PC2/index_PC2_data.parquet
  extensions/parquet/table/src/test/resources/referencePartitionedDataWithIndexOnPC/PC1=1/PC2=0/data.parquet
  extensions/parquet/table/src/test/resources/referencePartitionedDataWithIndexOnPC/PC1=1/PC2=1/.dh_metadata/indexes/PC1/index_PC1_data.parquet
  extensions/parquet/table/src/test/resources/referencePartitionedDataWithIndexOnPC/PC1=1/PC2=1/.dh_metadata/indexes/PC2/index_PC2_data.parquet
  extensions/parquet/table/src/test/resources/referencePartitionedDataWithIndexOnPC/PC1=1/PC2=1/data.parquet
  extensions/parquet/table/src/test/resources/referencePartitionedDataWithIndexOnPC/PC1=1/PC2=2/.dh_metadata/indexes/PC1/index_PC1_data.parquet
  extensions/parquet/table/src/test/resources/referencePartitionedDataWithIndexOnPC/PC1=1/PC2=2/.dh_metadata/indexes/PC2/index_PC2_data.parquet
  extensions/parquet/table/src/test/resources/referencePartitionedDataWithIndexOnPC/PC1=1/PC2=2/data.parquet
Labels: parquet, NoDocumentationNeeded, ReleaseNotesNeeded

#6765 feat: Internal tools to explore Iceberg metadata as Tables
  extensions/iceberg/src/main/java/io/deephaven/iceberg/internal/Explore.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6769 feat: Create a S3 universal provider
  Util/channel/src/main/java/io/deephaven/util/channel/SeekableChannelsProviderDelegate.java
  Util/channel/src/main/java/io/deephaven/util/channel/SeekableChannelsProviderLoader.java
  Util/channel/src/main/java/io/deephaven/util/channel/SeekableChannelsProviderPlugin.java
  Util/channel/src/main/java/io/deephaven/util/channel/SeekableChannelsProviderPluginBase.java
  extensions/iceberg/s3/src/main/java/io/deephaven/iceberg/util/S3InstructionsProviderPlugin.java
  extensions/iceberg/s3/src/test/java/io/deephaven/iceberg/util/S3WarehouseSqliteCatalogBase.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/layout/IcebergBaseLayout.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/GCSSeekableChannelProvider.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/GCSSeekableChannelProviderPlugin.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3ASeekableChannelProvider.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3ASeekableChannelProviderPlugin.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3Constants.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3DelegateProvider.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3NSeekableChannelProvider.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3NSeekableChannelProviderPlugin.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3SeekableChannelProvider.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3SeekableChannelProviderPlugin.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/UniversalS3Provider.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/UniversalS3SeekableChannelProviderPlugin.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/UriToS3SeekableChannelProvider.java
  extensions/s3/src/test/java/io/deephaven/extensions/s3/testlib/S3SeekableChannelTestSetup.java
  extensions/trackedfile/src/main/java/io/deephaven/extensions/trackedfile/TrackedSeekableChannelsProviderPlugin.java
  replication/static/build.gradle
  replication/static/src/main/java/io/deephaven/replicators/ReplicateChannelProviders.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#6771 feat: DH-18613: Update S3RequestCache.java to use KeyedObjectHashmap#replace
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3ReadRequestCache.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6770 feat: DH-18258: Improved handling of maximum concurrent write requests to S3
  Util/channel/src/main/java/io/deephaven/util/channel/CachedChannelProvider.java
  Util/channel/src/main/java/io/deephaven/util/channel/SeekableChannelContext.java
  Util/channel/src/main/java/io/deephaven/util/channel/SeekableChannelsProvider.java
  Util/channel/src/main/java/io/deephaven/util/channel/SeekableChannelsProviderDelegate.java
  Util/channel/src/test/java/io/deephaven/util/channel/CachedChannelProviderTest.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/layout/IcebergKeyValuePartitionedLayout.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/ParquetFileReader.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/ParquetTools.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/pagestore/ColumnChunkPageStore.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3CompletableOutputStream.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3DelegateProvider.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3Instructions.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3ReadContext.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3ReadRequest.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3ReadRequestCache.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3SeekableByteChannel.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3SeekableChannelProvider.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3WriteContext.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3WriteRequest.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/UniversalS3Provider.java
  extensions/s3/src/test/java/io/deephaven/extensions/s3/S3SeekableChannelSimpleTestBase.java
  extensions/trackedfile/src/main/java/io/deephaven/extensions/trackedfile/LocalCompletableOutputStream.java
  extensions/trackedfile/src/main/java/io/deephaven/extensions/trackedfile/TrackedSeekableChannelsProvider.java
Labels: feature request, NoDocumentationNeeded, ReleaseNotesNeeded, s3

#6784 fix: DH-18613: Revert "Update S3RequestCache.java to use KeyedObject…"
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3ReadRequestCache.java
Labels: bug, NoDocumentationNeeded, NoReleaseNotesNeeded

#6736 feat: DH-19056: Service loaded DoExchange handlers and marshallers to allow for pluggable types.
  extensions/flight-sql/src/adbcTest/java/io/deephaven/server/flightsql/JettyTestComponent.java
  extensions/flight-sql/src/jdbcTest/java/io/deephaven/server/flightsql/FlightSqlTestModule.java
  server/jetty/src/test/java/io/deephaven/server/jetty/BarrageChunkFactoryTest.java
  server/src/main/java/io/deephaven/server/arrow/ArrowFlightUtil.java
  server/src/main/java/io/deephaven/server/arrow/ArrowModule.java
  server/src/main/java/io/deephaven/server/arrow/BarrageRequestHelpers.java
  server/src/main/java/io/deephaven/server/arrow/BarrageSnapshotRequestHandler.java
  server/src/main/java/io/deephaven/server/arrow/BarrageSubscriptionRequestHandler.java
  server/src/main/java/io/deephaven/server/arrow/ExchangeMarshaller.java
  server/src/main/java/io/deephaven/server/arrow/ExchangeMarshallerModule.java
  server/src/main/java/io/deephaven/server/arrow/ExchangeRequestHandlerFactory.java
  server/src/main/java/io/deephaven/server/arrow/HierarchicalTableViewExchangeMarshaller.java
  server/src/main/java/io/deephaven/server/arrow/TableExchangeMarshaller.java
  server/src/main/java/io/deephaven/server/barrage/BarrageMessageProducer.java
  server/src/main/java/io/deephaven/server/hierarchicaltable/HierarchicalTableViewSubscription.java
  server/src/main/java/io/deephaven/server/runner/DeephavenApiServerModule.java
  server/test-utils/src/main/java/io/deephaven/server/test/FlightMessageRoundTripTest.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6796 fix: make local spotless happy again
  server/jetty/src/test/java/io/deephaven/server/jetty/BarrageChunkFactoryTest.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6797 fix: DH-19238: Barrage Must use VectorChunkAdapter to Copy Virtual Vectors on PUG
  server/src/main/java/io/deephaven/server/barrage/BarrageMessageProducer.java
  server/src/test/java/io/deephaven/server/barrage/BarrageMessageRoundTripTest.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#6786 feat: DH-19223: Use PerformanceEntries to visualize Update Graph
  Integrations/build.gradle
  engine/table/src/main/java/io/deephaven/engine/table/impl/BaseTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/DeferredViewTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/HasParentPerformanceIds.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/HasRefreshingSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/InstrumentedTableListenerBase.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/InstrumentedTableUpdateListener.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/InstrumentedTableUpdateListenerAdapter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/InstrumentedUpdateSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/MergedListener.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/PartitionAwareSourceTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/ShiftObliviousInstrumentedListener.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/SimpleSourceTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/SourceTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/TimeTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/perf/PerformanceEntry.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/perf/UpdatePerformanceAncestorStreamPublisher.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/perf/UpdatePerformanceStreamPublisher.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/perf/UpdatePerformanceTracker.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/DynamicWhereFilter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/UnionSourceManager.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/TableLoggers.java
  engine/table/src/main/java/io/deephaven/engine/tablelogger/EngineTableLoggers.java
  engine/table/src/main/java/io/deephaven/engine/tablelogger/UpdatePerformanceAncestorLogger.java
  engine/table/src/main/java/io/deephaven/engine/tablelogger/impl/memory/EngineTableLoggersFactoryMemoryImpl.java
  engine/table/src/main/java/io/deephaven/engine/updategraph/impl/BaseUpdateGraph.java
  engine/table/src/main/java/io/deephaven/engine/util/TableTools.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/FuzzerTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableAggregationTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestConcurrentInstantiation.java
  engine/test-utils/src/main/java/io/deephaven/engine/testutil/testcase/RefreshingTableTestCase.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/table/BarrageBlinkTable.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/table/BarrageRedirectedTable.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/table/BarrageTable.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/ArrowToTableConverter.java
  extensions/performance/build.gradle
  extensions/performance/src/main/java/io/deephaven/engine/table/impl/util/UpdateAncestorViz.java
  extensions/performance/src/test/java/io/deephaven/engine/table/impl/util/TestUpdateAncestorViz.java
  gradle/libs.versions.toml
  java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSnapshotImpl.java
  java-client/barrage/src/main/java/io/deephaven/client/impl/BarrageSubscriptionImpl.java
  props/test-configs/src/main/resources/dh-tests.prop
  py/server/deephaven/perfmon.py
  py/server/tests/test_perfmon.py
  server/src/test/java/io/deephaven/server/barrage/BarrageBlinkTableTest.java
  server/src/test/java/io/deephaven/server/barrage/BarrageMessageRoundTripTest.java
Labels: DocumentationNeeded, ReleaseNotesNeeded

#6789 feat(cpp-client): redo TableMaker/Comparer, and the tests that use them [part 3/8 of groupby]
  cpp-client/deephaven/dhclient/CMakeLists.txt
  cpp-client/deephaven/dhclient/include/private/deephaven/client/arrowutil/arrow_array_converter.h
  cpp-client/deephaven/dhclient/include/public/deephaven/client/client.h
  cpp-client/deephaven/dhclient/include/public/deephaven/client/utility/arrow_util.h
  cpp-client/deephaven/dhclient/include/public/deephaven/client/utility/table_maker.h
  cpp-client/deephaven/dhclient/src/arrowutil/arrow_array_converter.cc
  cpp-client/deephaven/dhclient/src/utility/arrow_util.cc
  cpp-client/deephaven/dhclient/src/utility/table_maker.cc
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/types.h
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/utility/utility.h
  cpp-client/deephaven/dhcore/src/types.cc
  cpp-client/deephaven/examples/create_table_with_arrow_flight/main.cc
  cpp-client/deephaven/tests/include/private/deephaven/tests/test_util.h
  cpp-client/deephaven/tests/src/add_drop_test.cc
  cpp-client/deephaven/tests/src/aggregates_test.cc
  cpp-client/deephaven/tests/src/filter_test.cc
  cpp-client/deephaven/tests/src/head_and_tail_test.cc
  cpp-client/deephaven/tests/src/input_table_test.cc
  cpp-client/deephaven/tests/src/join_test.cc
  cpp-client/deephaven/tests/src/lastby_test.cc
  cpp-client/deephaven/tests/src/merge_tables_test.cc
  cpp-client/deephaven/tests/src/new_table_test.cc
  cpp-client/deephaven/tests/src/script_test.cc
  cpp-client/deephaven/tests/src/select_test.cc
  cpp-client/deephaven/tests/src/sort_test.cc
  cpp-client/deephaven/tests/src/string_filter_test.cc
  cpp-client/deephaven/tests/src/table_test.cc
  cpp-client/deephaven/tests/src/test_util.cc
  cpp-client/deephaven/tests/src/ticking_test.cc
  cpp-client/deephaven/tests/src/time_unit_test.cc
  cpp-client/deephaven/tests/src/ungroup_test.cc
  cpp-client/deephaven/tests/src/update_by_test.cc
  cpp-client/deephaven/tests/src/validation_test.cc
  cpp-client/deephaven/tests/src/view_test.cc
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6790 fix(cpp-client): Consolidate some redundant functionality [part 4/8 of groupby]
  cpp-client/deephaven/dhclient/CMakeLists.txt
  cpp-client/deephaven/dhclient/include/private/deephaven/client/arrowutil/arrow_client_table.h
  cpp-client/deephaven/dhclient/include/private/deephaven/client/arrowutil/arrow_column_source.h
  cpp-client/deephaven/dhclient/include/private/deephaven/client/arrowutil/arrow_value_converter.h
  cpp-client/deephaven/dhclient/src/arrowutil/arrow_client_table.cc
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6793 feat(cpp-client): Upgrade ElementTypeId to the richer ElementType representation [part 7/8 of groupby]
  cpp-client/deephaven/dhclient/include/private/deephaven/client/arrowutil/arrow_column_source.h
  cpp-client/deephaven/dhclient/include/public/deephaven/client/utility/arrow_util.h
  cpp-client/deephaven/dhclient/src/arrowutil/arrow_array_converter.cc
  cpp-client/deephaven/dhclient/src/interop/client_interop.cc
  cpp-client/deephaven/dhclient/src/utility/arrow_util.cc
  cpp-client/deephaven/dhcore/include/private/deephaven/dhcore/immerutil/abstract_flex_vector.h
  cpp-client/deephaven/dhcore/include/private/deephaven/dhcore/immerutil/immer_column_source.h
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/clienttable/schema.h
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/column/array_column_source.h
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/column/buffer_column_source.h
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/column/column_source.h
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/types.h
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/utility/cython_support.h
  cpp-client/deephaven/dhcore/src/clienttable/schema.cc
  cpp-client/deephaven/dhcore/src/ticking/immer_table_state.cc
  cpp-client/deephaven/dhcore/src/types.cc
  cpp-client/deephaven/dhcore/src/utility/cython_support.cc
  cpp-client/deephaven/tests/src/buffer_column_source_test.cc
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6805 chore: Minor fix to readme
  README.md
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6806 chore: Fix missing quotes in README
  README.md
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6808 fix: DH-19248: Restore ensureSize to ContextWithChunk.
  engine/base/src/main/java/io/deephaven/engine/table/impl/ContextWithChunk.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6794 feat(cpp-client): Add nested containers in order to support groupby [part 8/8 of groupby]
  cpp-client/deephaven/dhclient/src/arrowutil/arrow_array_converter.cc
  cpp-client/deephaven/dhclient/src/arrowutil/arrow_client_table.cc
  cpp-client/deephaven/dhcore/CMakeLists.txt
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/chunk/chunk.h
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/chunk/chunk_traits.h
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/column/array_column_source.h
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/column/column_source.h
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/column/column_source_helpers.h
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/container/container.h
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/types.h
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/utility/utility.h
  cpp-client/deephaven/dhcore/src/chunk/chunk_maker.cc
  cpp-client/deephaven/dhcore/src/clienttable/client_table.cc
  cpp-client/deephaven/dhcore/src/container/container.cc
  cpp-client/deephaven/dhcore/src/ticking/immer_table_state.cc
  cpp-client/deephaven/dhcore/src/utility/cython_support.cc
  cpp-client/deephaven/dhcore/src/utility/utility.cc
  cpp-client/deephaven/tests/CMakeLists.txt
  cpp-client/deephaven/tests/src/group_test.cc
  cpp-client/deephaven/tests/src/ticking_test.cc
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6772 feat: Enforce stricter web security rules
  extensions/flight-sql/src/adbcTest/java/io/deephaven/server/flightsql/JettyTestComponent.java
  extensions/flight-sql/src/jdbcTest/java/io/deephaven/server/flightsql/JettyTestComponent.java
  props/configs/src/main/resources/dh-defaults.prop
  server/jetty-11/src/main/java/io/deephaven/server/jetty11/AllowedHttpMethodsCustomizer.java
  server/jetty-11/src/main/java/io/deephaven/server/jetty11/ConfiguredHeadersCustomizer.java
  server/jetty-11/src/main/java/io/deephaven/server/jetty11/JettyBackedGrpcServer.java
  server/jetty-11/src/main/java/io/deephaven/server/jetty11/JettyConfig.java
  server/jetty-11/src/test/java/io/deephaven/server/jetty11/JettyFlightRoundTripTest.java
  server/jetty/src/main/java/io/deephaven/server/jetty/AllowedHttpMethodsCustomizer.java
  server/jetty/src/main/java/io/deephaven/server/jetty/ConfiguredHeadersCustomizer.java
  server/jetty/src/main/java/io/deephaven/server/jetty/JettyBackedGrpcServer.java
  server/jetty/src/main/java/io/deephaven/server/jetty/JettyConfig.java
  server/jetty/src/test/java/io/deephaven/server/jetty/BarrageChunkFactoryTest.java
  server/jetty/src/test/java/io/deephaven/server/jetty/JettyFlightRoundTripTest.java
Labels: web-client-ui, grpc, DocumentationNeeded, jetty, ReleaseNotesNeeded

#6812 feat: DH-19223: Defer UpdatePerformanceTracker initialization when logging ancestors.
  engine/table/src/main/java/io/deephaven/engine/table/impl/perf/UpdatePerformanceTracker.java
  engine/table/src/main/java/io/deephaven/engine/updategraph/impl/BaseUpdateGraph.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6813 fix: Correct hardcoded path for docs-ci job to upload proto/grpc docs
  .github/workflows/docs-ci.yml
Labels: documentation, build, NoDocumentationNeeded, NoReleaseNotesNeeded

#6811 feat: DH-19167 Constituent filtering for rollups
  engine/api/src/main/java/io/deephaven/engine/table/hierarchical/RollupTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/hierarchical/RollupTableImpl.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestRollup.java
  engine/test-utils/src/main/java/io/deephaven/engine/testutil/HierarchicalTableTestTools.java
  server/src/main/java/io/deephaven/server/hierarchicaltable/HierarchicalTableServiceGrpcImpl.java
Labels: DocumentationNeeded, NoReleaseNotesNeeded

#6815 test: Fail on reading Iceberg table with unsupported type
  extensions/iceberg/src/test/java/io/deephaven/iceberg/junit5/SqliteCatalogBase.java
Labels: test, NoDocumentationNeeded, NoReleaseNotesNeeded, iceberg

#6816 fix: DH-19289: NPE Generating Compiler Diagnostic Message
  engine/context/src/test/java/io/deephaven/engine/context/TestQueryCompiler.java
  engine/table/src/main/java/io/deephaven/engine/context/QueryCompilerImpl.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/AbstractFormulaColumn.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/ConditionFilter.java
  extensions/performance/src/test/java/io/deephaven/engine/table/impl/util/TestUpdateAncestorViz.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6655 feat: add `updateView()` capabilities to `rollup` tables
  engine/api/src/main/java/io/deephaven/engine/table/hierarchical/RollupTable.java
  engine/api/src/main/java/io/deephaven/engine/table/hierarchical/UpdateViewOperationsRecorder.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/hierarchical/BaseNodeOperationsRecorder.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/hierarchical/RollupNodeOperationsRecorder.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/hierarchical/RollupTableImpl.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/hierarchical/TreeNodeOperationsRecorder.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/SwitchColumn.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/WrappedSelectColumn.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestHierarchicalTableSnapshots.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestRollupTable.java
  go/internal/proto/hierarchicaltable/hierarchicaltable.pb.go
  proto/proto-backplane-grpc/src/main/proto/deephaven_core/proto/hierarchicaltable.proto
  py/client/deephaven_core/proto/hierarchicaltable_pb2.py
  py/server/deephaven/table.py
  py/server/tests/test_rollup_tree_table.py
  server/src/main/java/io/deephaven/server/hierarchicaltable/HierarchicalTableServiceGrpcImpl.java
  server/src/main/java/io/deephaven/server/table/ops/AggregationAdapter.java
  web/client-api/src/main/java/io/deephaven/web/client/api/Column.java
  web/client-api/src/main/java/io/deephaven/web/client/api/CustomColumn.java
  web/client-api/src/main/java/io/deephaven/web/client/api/CustomColumnOptions.java
  web/client-api/src/main/java/io/deephaven/web/client/api/JsTable.java
  web/client-api/src/main/java/io/deephaven/web/client/api/tree/JsTreeTable.java
  web/client-api/src/test/java/io/deephaven/web/client/api/HierarchicalTableTestGwt.java
  web/client-api/src/test/java/io/deephaven/web/client/api/subscription/ViewportTestGwt.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven_core/proto/Hierarchicaltable_pb.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven_core/proto/hierarchicaltable_pb/HierarchicalTableApplyRequest.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven_core/proto/hierarchicaltable_pb/RollupNodeTypeMap.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven_core/proto/hierarchicaltable_pb/UpdateViewRequest.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven_core/proto/table_pb/Selectable.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven_core/proto/table_pb/selectable/TypeCase.java
Labels: DocumentationNeeded, ReleaseNotesNeeded

#6820 fix: Ensure that Iceberg metadata tables fail on loadTable
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/IcebergCatalogAdapter.java
  extensions/iceberg/src/test/java/io/deephaven/iceberg/junit5/SqliteCatalogBase.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6825 fix(cpp-client,py/client): some clarifications in README.md files
  cpp-client/README.md
  py/client/README.md
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6819 build: Fix two oversights in our published jars
  Util/immutables/gradle.properties
  buildSrc/src/main/groovy/io.deephaven.java-publishing-conventions.gradle
Labels: build, NoDocumentationNeeded, NoReleaseNotesNeeded

#6834 chore: bump org.apache.iceberg:iceberg-bom from 1.8.1 to 1.9.0
  extensions/iceberg/s3/src/main/java/io/deephaven/extensions/s3/DeephavenAwsClientFactory.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/InferenceImpl.java
  gradle/libs.versions.toml
Labels: NoDocumentationNeeded, version-bump, NoReleaseNotesNeeded

#6836 fix: Bug fix for rolling_formula with constant formulas.
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/UpdateBy.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestRollingFormula.java
Labels: bug, NoDocumentationNeeded, ReleaseNotesNeeded

#6837 build: Adds JS API jars as resources to publish to Maven Central
  Base/build.gradle
  BenchmarkSupport/BenchmarkSupport.gradle
  Configuration/build.gradle
  IO/build.gradle
  buildSrc/src/main/groovy/GwtTools.groovy
  buildSrc/src/main/groovy/io.deephaven.java-gwt-dependency.gradle
  buildSrc/src/main/groovy/io.deephaven.javadoc-conventions.gradle
  engine/chunk/build.gradle
  extensions/barrage/build.gradle
  open-api/lang-parser/lang-parser.gradle
  py/jpy-integration/build.gradle
  web/client-api/client-api.gradle
  web/client-api/gradle.properties
  web/client-backplane/client-backplane.gradle
  web/client-backplane/gradle.properties
  web/shared-beans/gradle.properties
  web/shared-beans/shared-beans.gradle
Labels: build, NoDocumentationNeeded, ReleaseNotesNeeded

#6838 feat(cpp-client): Move method to make it available to others [pyticking 4/7]
  cpp-client/deephaven/dhclient/src/arrowutil/arrow_array_converter.cc
  cpp-client/deephaven/dhcore/CMakeLists.txt
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/container/container_util.h
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6831 feat(py/client-ticking): Add nested list support to Python ticking client [pyticking 6/7]
  py/client-ticking/src/pydeephaven_ticking/_core.pxd
  py/client-ticking/src/pydeephaven_ticking/_core.pyx
  py/client-ticking/tests/test_ticking_lists.py
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6832 feat(cpp-client): Remove redundant ElementTypeId support from Schema [pyticking 7/7]
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/clienttable/schema.h
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/utility/cython_support.h
  cpp-client/deephaven/dhcore/src/clienttable/schema.cc
  cpp-client/deephaven/dhcore/src/utility/cython_support.cc
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6839 feat: Allow downstream applications to contribute, control web resources
  server/jetty-11/src/main/java/io/deephaven/server/jetty11/JettyBackedGrpcServer.java
  server/jetty/src/main/java/io/deephaven/server/jetty/JettyBackedGrpcServer.java
  server/src/main/java/io/deephaven/server/resources/ServerResource.java
  server/src/main/java/io/deephaven/server/resources/ServerResources.java
  web/src/main/java/io/deephaven/web/WebResources.java
  web/web.gradle
Labels: build, jsapi, NoDocumentationNeeded, ReleaseNotesNeeded
