Repository deephaven/deephaven-core, pull requests merged in 2025-01, with the labels that each got.

#6516 fix: Add missing default values for the callback proxies in TableDataService
  py/server/deephaven/experimental/table_data_service.py
Labels: NoDocumentationNeeded, python-server-side, NoReleaseNotesNeeded

#6525 chore: bump base image for jpy 1.1.0
  docker/registry/server-base/gradle.properties
  docker/server-jetty/src/main/server-jetty/requirements.txt
  docker/server/src/main/server-netty/requirements.txt
  gradle/libs.versions.toml
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6529 chore: Bump jpy requirements
  py/embedded-server/setup.py
  py/server/setup.py
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6530 chore: Bump jpy requirements
  py/embedded-server/setup.py
  py/server/setup.py
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6528 fix: Ensure that DataIndexes produced by a RegionedColumnSourceManager are retained by the DataIndexer
  engine/table/src/main/java/io/deephaven/engine/table/impl/dataindex/RemappedDataIndex.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/indexer/DataIndexer.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/MergedDataIndex.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/PartitioningColumnDataIndex.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableTest.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/ParquetTableReadWriteTest.java
Labels: query engine, core, DocumentationNeeded, ReleaseNotesNeeded

#6527 feat: Add SourcePartitionedTable support to PythonTableDataService
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/PythonTableDataService.java
  py/server/deephaven/experimental/table_data_service.py
  py/server/tests/test_table_data_service.py
Labels: core, python, DocumentationNeeded, ReleaseNotesNeeded

#6532 feat: Add SourcePartitionedTable support to PythonTableDataService
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/PythonTableDataService.java
  py/server/deephaven/experimental/table_data_service.py
  py/server/tests/test_table_data_service.py
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6533 fix: Ensure that DataIndexes produced by a RegionedColumnSourceManager are retained by the DataIndexer
  engine/table/src/main/java/io/deephaven/engine/table/impl/dataindex/RemappedDataIndex.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/indexer/DataIndexer.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/MergedDataIndex.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/PartitioningColumnDataIndex.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableTest.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/ParquetTableReadWriteTest.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6519 fix: Add feature to control systemic property of executeCode
  engine/updategraph/src/main/java/io/deephaven/engine/util/systemicmarking/SystemicObjectTracker.java
  go/internal/proto/console/console.pb.go
  java-client/session/src/main/java/io/deephaven/client/impl/ConsoleSession.java
  java-client/session/src/main/java/io/deephaven/client/impl/ExecuteCodeOptions.java
  java-client/session/src/main/java/io/deephaven/client/impl/SessionImpl.java
  proto/proto-backplane-grpc/src/main/proto/deephaven_core/proto/console.proto
  py/client/build.gradle
  py/client/deephaven_core/proto/console_pb2.py
  py/client/pydeephaven/_console_service.py
  py/client/pydeephaven/session.py
  py/client/tests/test_session.py
  server/src/main/java/io/deephaven/server/console/ConsoleServiceGrpcImpl.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#6534 fix: Add feature to control systemic property of executeCode
  engine/updategraph/src/main/java/io/deephaven/engine/util/systemicmarking/SystemicObjectTracker.java
  go/internal/proto/console/console.pb.go
  java-client/session/src/main/java/io/deephaven/client/impl/ConsoleSession.java
  java-client/session/src/main/java/io/deephaven/client/impl/ExecuteCodeOptions.java
  java-client/session/src/main/java/io/deephaven/client/impl/SessionImpl.java
  proto/proto-backplane-grpc/src/main/proto/deephaven_core/proto/console.proto
  py/client/build.gradle
  py/client/deephaven_core/proto/console_pb2.py
  py/client/pydeephaven/_console_service.py
  py/client/pydeephaven/session.py
  py/client/tests/test_session.py
  server/src/main/java/io/deephaven/server/console/ConsoleServiceGrpcImpl.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#6535 fix: JS API viewports should throw only for basic data issues
  web/client-api/src/main/java/io/deephaven/web/client/api/subscription/TableViewportSubscription.java
Labels: jsapi, NoDocumentationNeeded, ReleaseNotesNeeded

#6536 fix: Correct two errors in generated types
  web/client-api/src/main/java/io/deephaven/web/client/api/QueryConnectable.java
  web/client-api/src/main/java/io/deephaven/web/client/api/event/Event.java
  web/client-api/src/main/java/io/deephaven/web/client/api/grpc/GrpcTransportFactory.java
  web/client-api/types/build.gradle
Labels: documentation, jsapi, NoDocumentationNeeded, ReleaseNotesNeeded

#6537 fix: JS API viewports should throw only for basic data issues
  web/client-api/src/main/java/io/deephaven/web/client/api/subscription/TableViewportSubscription.java
Labels: jsapi, NoDocumentationNeeded, ReleaseNotesNeeded

#6538 feat: DH-18364: Add Property to Disable Core DataIndex
  engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/MatchFilter.java
Labels: query engine, core, NoDocumentationNeeded, ReleaseNotesNeeded, point_release_candidate

#6539 feat: DH-18364: Add Property to Disable Core DataIndex
  engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/MatchFilter.java
Labels: query engine, NoDocumentationNeeded, NoReleaseNotesNeeded

#6513 refactor: DH-18308: Remove NullNanAwareComparator in favor of built-in Comparators.
  engine/function/src/main/java/io/deephaven/function/comparators/NullNaNAwareComparator.java
  engine/function/src/templates/Sort.ftl
  engine/function/src/templates/TestSort.ftl
  engine/function/src/test/java/io/deephaven/function/comparators/TestNullNaNAwareComparator.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6540 chore: Update workflow runners to ubuntu-24.04
  .github/workflows/build-ci.yml
  .github/workflows/check-ci.yml
  .github/workflows/cla.yml
  .github/workflows/conventional-pr-check.yml
  .github/workflows/create-docs-issues.yml
  .github/workflows/dependency-submission.yml
  .github/workflows/docs-ci.yml
  .github/workflows/label-check-ci.yml
  .github/workflows/links.yml
  .github/workflows/nightly-check-ci.yml
  .github/workflows/nightly-image-check.yml
  .github/workflows/publish-check-ci.yml
  .github/workflows/publish-ci.yml
  .github/workflows/quick-ci.yml
  .github/workflows/tag-base-images.yml
  .github/workflows/update-web.yml
Labels: ci, NoDocumentationNeeded, NoReleaseNotesNeeded

#6542 fix(cpp-client): use std::getline for reading passwords
  cpp-client/deephaven/dhcore/src/utility/utility.cc
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6545 chore: Bump to 0.37.3-SNAPSHOT
  R/rdeephaven/DESCRIPTION
  cpp-client/deephaven/CMakeLists.txt
  gradle.properties
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6546 fix: Chart subscriptions shouldn't reverse positions
  web/client-api/src/main/java/io/deephaven/web/client/api/widget/plot/ChartData.java
Labels: jsapi, plotting, NoDocumentationNeeded, ReleaseNotesNeeded

#6547 fix: Chart subscriptions shouldn't reverse positions
  web/client-api/src/main/java/io/deephaven/web/client/api/widget/plot/ChartData.java
Labels: jsapi, plotting, NoDocumentationNeeded, ReleaseNotesNeeded

#6548 fix: correct `OuterJoinTools.leftOuterJoin/fullOuterJoin()` output when RHS initally empty
  engine/table/src/main/java/io/deephaven/engine/table/impl/CrossJoinHelper.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/BitMaskingColumnSource.java
  engine/table/src/test/java/io/deephaven/engine/util/TestOuterJoinTools.java
Labels: bug, NoDocumentationNeeded, ReleaseNotesNeeded

#6551 fix: correct OuterJoinTools.leftOuterJoin/fullOuterJoin() output when RHS initally empty
  engine/table/src/main/java/io/deephaven/engine/table/impl/CrossJoinHelper.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/BitMaskingColumnSource.java
  engine/table/src/test/java/io/deephaven/engine/util/TestOuterJoinTools.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#6432 test: Add Flight SQL ADBC Java tests
  extensions/flight-sql/build.gradle
  extensions/flight-sql/src/adbcTest/java/io/deephaven/server/DeephavenServerTestBase.java
  extensions/flight-sql/src/adbcTest/java/io/deephaven/server/flightsql/FlightSqlAdbcTestBase.java
  extensions/flight-sql/src/adbcTest/java/io/deephaven/server/flightsql/FlightSqlTestModule.java
  extensions/flight-sql/src/adbcTest/java/io/deephaven/server/flightsql/JettyTestComponent.java
  extensions/flight-sql/src/adbcTest/java/io/deephaven/server/flightsql/jetty/FlightSqlAdbcTestJetty.java
  gradle/libs.versions.toml
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6552 fix: DH-18395: Address performance problems with large numbers of table locations caused by serial unmanage
  engine/table/src/main/java/io/deephaven/engine/table/impl/SourcePartitionedTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/SourceTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/locations/impl/PartitionedTableLocationKey.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/locations/impl/TableLocationSubscriptionBuffer.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/locations/local/FileTableLocationKey.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/locations/local/URITableLocationKey.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/ManyLocationsTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/SourcePartitionedTableTest.java
  engine/test-utils/src/main/java/io/deephaven/engine/testutil/locations/TableBackedTableLocationKey.java
  engine/test-utils/src/main/java/io/deephaven/engine/testutil/locations/TableBackedTableLocationProvider.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#6561 feat: DH-18364: Add Property to Disable Core DataIndex (#6539)
  engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/MatchFilter.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6562 chore: Version bump to 0.36.2-SNAPSHOT
  R/rdeephaven/DESCRIPTION
  cpp-client/deephaven/CMakeLists.txt
  gradle.properties
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6549 test: Simple ChartData tests for JS API
  web/client-api/src/test/java/io/deephaven/web/ClientIntegrationTestSuite.java
  web/client-api/src/test/java/io/deephaven/web/CustomTransportTest.gwt.xml
  web/client-api/src/test/java/io/deephaven/web/client/api/grpc/GrpcTransportTestGwt.java
  web/client-api/src/test/java/io/deephaven/web/client/api/widget/plot/ChartDataTestGwt.java
Labels: jsapi, test, NoDocumentationNeeded, NoReleaseNotesNeeded

#6565 feat: Add j_collection_to_list() in jcompat.py
  py/server/deephaven/jcompat.py
  py/server/tests/test_jcompat.py
Labels: NoDocumentationNeeded, python-server-side, ReleaseNotesNeeded

#6550 feat: parse Parquet schema from ParquetMetadataConverter
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/ParquetFileReader.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/ParquetSchemaReader.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/layout/ParquetMetadataFileLayout.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/location/ParquetTableLocationKey.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#6567 ci: Publish jsapi-types patch release with v0.36 tag
  .github/workflows/publish-ci.yml
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6568 chore: Bump to Kafka 3.8.0, Confluent 7.8.0
  gradle/libs.versions.toml
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#6570 fix: DH-18433: SourcePartitionedTable needs to check the size of pending locations even if there are no added or removed locations
  engine/table/src/main/java/io/deephaven/engine/table/impl/SourcePartitionedTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/locations/impl/TableLocationSubscriptionBuffer.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/SourcePartitionedTableTest.java
  engine/test-utils/src/main/java/io/deephaven/engine/testutil/TstUtils.java
Labels: query engine, core, NoDocumentationNeeded, NoReleaseNotesNeeded

#6571 fix: DH-18433: SourcePartitionedTable needs to check the size of pending locations even if there are no added or removed locations (#6570)
  engine/table/src/main/java/io/deephaven/engine/table/impl/SourcePartitionedTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/locations/impl/TableLocationSubscriptionBuffer.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/SourcePartitionedTableTest.java
  engine/test-utils/src/main/java/io/deephaven/engine/testutil/TstUtils.java
Labels: bug, query engine, core, NoDocumentationNeeded, NoReleaseNotesNeeded

#6573 fix: Add semi-required "webhook-type" to slack actions
  .github/workflows/create-docs-issues.yml
  .github/workflows/nightly-check-ci.yml
  .github/workflows/nightly-image-check.yml
  .github/workflows/nightly-publish-ci.yml
Labels: ci, NoDocumentationNeeded, NoReleaseNotesNeeded

#6577 feat: DH-18423: add a systemic_obj_tracker module in the Py server API
  engine/updategraph/src/main/java/io/deephaven/engine/util/systemicmarking/SystemicObjectTracker.java
  py/server/deephaven/systemic_obj_tracker.py
  py/server/test_helper/__init__.py
  py/server/tests/test_systemic_obj_tracker.py
Labels: DocumentationNeeded, ReleaseNotesNeeded

#6566 feat: DH-18351: Add `CumCountWhere()` and `RollingCountWhere()` features to `UpdateBy`
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/UpdateByOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/UpdateByOperatorFactory.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/UpdateByWindowRollingBase.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/countwhere/CountWhereOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/internal/BaseByteUpdateByOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/internal/BaseCharUpdateByOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/internal/BaseDoubleUpdateByOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/internal/BaseFloatUpdateByOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/internal/BaseIntUpdateByOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/internal/BaseLongUpdateByOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/internal/BaseObjectUpdateByOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/internal/BaseShortUpdateByOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/rollingformula/BooleanRollingFormulaOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/rollingformula/ByteRollingFormulaOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/rollingformula/CharRollingFormulaOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/rollingformula/DoubleRollingFormulaOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/rollingformula/FloatRollingFormulaOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/rollingformula/IntRollingFormulaOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/rollingformula/LongRollingFormulaOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/rollingformula/ObjectRollingFormulaOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/rollingformula/ShortRollingFormulaOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/rollingformulamulticolumn/RollingFormulaMultiColumnOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/rollinggroup/RollingGroupOperator.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestAggBy.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestCumCountWhere.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestRollingCountWhere.java
  go/internal/proto/table/table.pb.go
  java-client/session/src/main/java/io/deephaven/client/impl/UpdateByBuilder.java
  java-client/session/src/test/java/io/deephaven/client/impl/UpdateBySpecBuilderTest.java
  proto/proto-backplane-grpc/src/main/proto/deephaven_core/proto/table.proto
  py/client/deephaven_core/proto/table_pb2.py
  py/client/pydeephaven/table.py
  py/client/pydeephaven/updateby.py
  py/client/tests/test_updateby.py
  py/server/deephaven/agg.py
  py/server/deephaven/updateby.py
  py/server/tests/test_updateby.py
  server/src/main/java/io/deephaven/server/table/ops/UpdateByGrpcImpl.java
  table-api/src/main/java/io/deephaven/api/agg/Aggregation.java
  table-api/src/main/java/io/deephaven/api/updateby/UpdateByOperation.java
  table-api/src/main/java/io/deephaven/api/updateby/spec/CumCountWhereSpec.java
  table-api/src/main/java/io/deephaven/api/updateby/spec/RollingCountWhereSpec.java
  table-api/src/main/java/io/deephaven/api/updateby/spec/UpdateBySpec.java
Labels: query engine, DocumentationNeeded, ReleaseNotesNeeded

#6575 chore: Bump base images
  docker/registry/cpp-clients-multi-base/gradle.properties
  docker/registry/go/gradle.properties
  docker/registry/manylinux2014_x86_64/gradle.properties
  docker/registry/minio/gradle.properties
  docker/registry/protoc-base/gradle.properties
  docker/registry/python/gradle.properties
  docker/registry/selenium/gradle.properties
  docker/registry/server-base/gradle.properties
  docker/registry/slim-base/gradle.properties
  docker/server-jetty/src/main/server-jetty/requirements.txt
  docker/server/src/main/server-netty/requirements.txt
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6558 feat: DH-18399: Add ParquetColumnResolver
  Util/src/main/java/io/deephaven/util/annotations/InternalUseOnly.java
  extensions/iceberg/src/test/java/io/deephaven/iceberg/junit5/SqliteCatalogBase.java
  extensions/parquet/base/build.gradle
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/ColumnChunkReaderImpl.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/ColumnWriterImpl.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/RowGroupWriterImpl.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/impl/ColumnDescriptorUtil.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/impl/ParquetSchemaUtil.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/impl/package-info.java
  extensions/parquet/base/src/test/java/io/deephaven/parquet/base/TestParquetTimeUtils.java
  extensions/parquet/base/src/test/java/io/deephaven/parquet/impl/ParquetSchemaUtilTest.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/ParquetInstructions.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/ParquetSchemaReader.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/location/ParquetColumnResolver.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/location/ParquetColumnResolverMap.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/location/ParquetFieldIdColumnResolverFactory.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/location/ParquetTableLocation.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/location/ParquetTableLocationKey.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/ParquetInstructionsTest.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/ParquetTableReadWriteTest.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/TestParquetTools.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/location/ParquetFieldIdColumnResolverFactoryTest.java
Labels: parquet, NoDocumentationNeeded, ReleaseNotesNeeded

#6592 chore: Bump to 0.37.5-SNAPSHOT
  R/rdeephaven/DESCRIPTION
  cpp-client/deephaven/CMakeLists.txt
  gradle.properties
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6585 perf: DH-18300: Improve DataIndex performance.
  Base/src/main/java/io/deephaven/base/AtomicUtil.java
  Base/src/main/java/io/deephaven/base/stats/ThreadSafeCounter.java
  Base/src/main/java/io/deephaven/base/stats/ThreadSafeValue.java
  Base/src/main/java/io/deephaven/base/stats/Value.java
  Base/src/test/java/io/deephaven/base/stats/TestValue.java
  CONTRIBUTING.md
  engine/api/src/main/java/io/deephaven/engine/table/BasicDataIndex.java
  engine/api/src/main/java/io/deephaven/engine/table/DataIndex.java
  engine/api/src/main/java/io/deephaven/engine/table/DataIndexOptions.java
  engine/benchmark/src/benchmark/java/io/deephaven/benchmark/engine/GroupByBenchmark.java
  engine/benchmark/src/benchmark/java/io/deephaven/benchmark/engine/LastByBenchmark.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/AbstractColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/JoinControl.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/dataindex/RemappedDataIndex.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/dataindex/StandaloneDataIndex.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/dataindex/TableBackedDataIndex.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/dataindex/TransformedDataIndex.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/analyzers/SelectColumnLayer.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/MergedDataIndex.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/PartitioningColumnDataIndex.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/sources/regioned/TestRegionedColumnSourceManager.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#6593 perf: DH-18300: Improve DataIndex performance. (#6585)
  Base/src/main/java/io/deephaven/base/AtomicUtil.java
  Base/src/main/java/io/deephaven/base/stats/ThreadSafeCounter.java
  Base/src/main/java/io/deephaven/base/stats/ThreadSafeValue.java
  Base/src/main/java/io/deephaven/base/stats/Value.java
  Base/src/test/java/io/deephaven/base/stats/TestValue.java
  CONTRIBUTING.md
  engine/api/src/main/java/io/deephaven/engine/table/BasicDataIndex.java
  engine/api/src/main/java/io/deephaven/engine/table/DataIndex.java
  engine/api/src/main/java/io/deephaven/engine/table/DataIndexOptions.java
  engine/benchmark/src/benchmark/java/io/deephaven/benchmark/engine/GroupByBenchmark.java
  engine/benchmark/src/benchmark/java/io/deephaven/benchmark/engine/LastByBenchmark.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/AbstractColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/JoinControl.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/dataindex/RemappedDataIndex.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/dataindex/StandaloneDataIndex.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/dataindex/TableBackedDataIndex.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/dataindex/TransformedDataIndex.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/analyzers/SelectColumnLayer.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/MergedDataIndex.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/PartitioningColumnDataIndex.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/sources/regioned/TestRegionedColumnSourceManager.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6602 feat(csharp/ExcelAddIn): Add a version number and display it in the GUI
  csharp/ExcelAddIn/util/Utility.cs
  csharp/ExcelAddIn/views/ConnectionManagerDialog.Designer.cs
  csharp/ExcelAddIn/views/ConnectionManagerDialog.cs
  csharp/ExcelAddIn/views/ConnectionManagerDialog.resx
  csharp/ExcelAddIn/views/CredentialsDialog.Designer.cs
  csharp/ExcelAddIn/views/CredentialsDialog.cs
  csharp/ExcelAddIn/views/CredentialsDialog.resx
  csharp/ExcelAddInInstaller/ExcelAddInInstaller.aip
  csharp/ExcelAddInInstaller/Prerequisites/.NET 8.0/.gitignore
  csharp/ExcelAddInInstaller/Prerequisites/.NET 8.0/README.md
  csharp/ExcelAddInInstaller/VERSIONS.md
  csharp/ExcelAddInInstaller/dhinstall/.gitignore
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6603 fix: DH-18482: EventDrivenUpdateGraph: Allow two concurrent threads to safely requestRefresh()
  engine/table/src/main/java/io/deephaven/engine/updategraph/impl/BaseUpdateGraph.java
  engine/table/src/main/java/io/deephaven/engine/updategraph/impl/EventDrivenUpdateGraph.java
  engine/table/src/test/java/io/deephaven/engine/updategraph/impl/TestEventDrivenUpdateGraph.java
Labels: query engine, core, NoDocumentationNeeded, ReleaseNotesNeeded, point_release_candidate

#6591 fix: JS clients must not release tickets for pending operations
  web/client-api/src/main/java/io/deephaven/web/client/api/tree/JsTreeTable.java
Labels: jsapi, grpc, NoDocumentationNeeded, ReleaseNotesNeeded, point_release_candidate
