Repository deephaven/deephaven-core, pull requests merged in 2025-05, with the labels that each got.

#6841 chore: Bump-to-0.40.0-SNAPSHOT
  R/rdeephaven/DESCRIPTION
  cpp-client/deephaven/CMakeLists.txt
  gradle.properties
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6843 fix: DH-19357 Fix the bug of calling a property in the req stream
  py/client/pydeephaven/experimental/plugin_client.py
  py/client/tests/test_plugin_client.py
Labels: NoDocumentationNeeded, python-client, plug-ins, NoReleaseNotesNeeded, point_release_candidate

#6849 fix: DH-19320: Correct intermittent UpdateGraphViz Test Failure
  extensions/performance/src/test/java/io/deephaven/engine/table/impl/util/TestUpdateAncestorViz.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6844 chore(R): Remove unused R client CMakeLists.txt
  R/rdeephaven/src/CMakeLists.txt
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6850 ci: Set Corey as a Code Owner for R.
  .github/CODEOWNERS
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6851 docs(py/client-ticking): DOC-749: List supported ticking types
  py/client/docs/source/examples.rst
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6853 docs(py/client-ticking): DH-19373: Update python ticking doc comments
  py/client-ticking/src/pydeephaven_ticking/_util.py
  py/client-ticking/src/pydeephaven_ticking/table_listener.py
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6716 feat: DH-19384: New methods for rollup creation in support of Pivot tables.
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/AggregationProcessor.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/hierarchical/RollupTableImpl.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6842 docs: Conventional release notes instructions
  RELEASE.md
  deephaven-changelog
Labels: DocumentationNeeded, NoReleaseNotesNeeded

#6854 refactor: DH-19384: Refactors to support pivots.
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/BarrageMessageWriterImpl.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/BarrageProtoUtil.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/BarrageUtil.java
  java-client/session/build.gradle
  java-client/session/src/main/java/io/deephaven/client/impl/AggregationBuilder.java
  java-client/session/src/main/java/io/deephaven/client/impl/BatchTableRequestBuilder.java
  java-client/session/src/main/java/io/deephaven/client/impl/FilterAdapter.java
  server/src/main/java/io/deephaven/server/hierarchicaltable/HierarchicalTableGrpcHelper.java
  server/src/main/java/io/deephaven/server/hierarchicaltable/HierarchicalTableServiceGrpcImpl.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6855 chore: bump to gradle 8.14
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6857 refactor: DH-19384: Permit startExchange with a PathId.
  java-client/flight/src/main/java/io/deephaven/client/impl/FlightClientHelper.java
  java-client/flight/src/main/java/io/deephaven/client/impl/FlightSession.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6860 fix: DH-19357 Fix the bug of calling a property in the req stream (#6…
  py/client/pydeephaven/experimental/plugin_client.py
  py/client/tests/test_plugin_client.py
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6861 fix: Address bug in SingleSidedComparableRangeFilter#copy function.
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/SingleSidedComparableRangeFilter.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableWhereTest.java
Labels: bug, NoDocumentationNeeded, ReleaseNotesNeeded

#6859 refactor: DH-19384: Refactors in support of pivots.
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/AggregationProcessor.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/hierarchical/RollupTableImpl.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/BarrageMessageWriterImpl.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/BarrageProtoUtil.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/BarrageUtil.java
  java-client/flight/src/main/java/io/deephaven/client/impl/FlightClientHelper.java
  java-client/flight/src/main/java/io/deephaven/client/impl/FlightSession.java
  java-client/session/build.gradle
  java-client/session/src/main/java/io/deephaven/client/impl/AggregationBuilder.java
  java-client/session/src/main/java/io/deephaven/client/impl/BatchTableRequestBuilder.java
  java-client/session/src/main/java/io/deephaven/client/impl/FilterAdapter.java
  server/src/main/java/io/deephaven/server/hierarchicaltable/HierarchicalTableGrpcHelper.java
  server/src/main/java/io/deephaven/server/hierarchicaltable/HierarchicalTableServiceGrpcImpl.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6852 fix: DH-19311: Permit multiple constituents from GetTable partitioned table service call.
  engine/table/src/main/java/io/deephaven/engine/table/impl/partitioned/PartitionedTableImpl.java
  go/internal/proto/partitionedtable/partitionedtable.pb.go
  proto/proto-backplane-grpc/src/main/proto/deephaven_core/proto/partitionedtable.proto
  py/client/deephaven_core/proto/partitionedtable_pb2.py
  server/src/main/java/io/deephaven/server/partitionedtable/PartitionedTableServiceGrpcImpl.java
  server/src/test/java/io/deephaven/server/partitionedtable/TestPartitionedTableService.java
  web/client-api/src/main/java/io/deephaven/web/client/api/JsPartitionedTable.java
  web/client-api/src/test/java/io/deephaven/web/client/api/PartitionedTableTestGwt.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven_core/proto/partitionedtable_pb/GetTableRequest.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven_core/proto/partitionedtable_pb/gettablerequest/UniqueBehaviorMap.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6862 fix: DH-19311: Permit multiple constituents from GetTable partitionedtable service call. (#6852)
  engine/table/src/main/java/io/deephaven/engine/table/impl/partitioned/PartitionedTableImpl.java
  go/internal/proto/partitionedtable/partitionedtable.pb.go
  proto/proto-backplane-grpc/src/main/proto/deephaven_core/proto/partitionedtable.proto
  py/client/deephaven_core/proto/partitionedtable_pb2.py
  server/src/main/java/io/deephaven/server/partitionedtable/PartitionedTableServiceGrpcImpl.java
  server/src/test/java/io/deephaven/server/partitionedtable/TestPartitionedTableService.java
  web/client-api/src/main/java/io/deephaven/web/client/api/JsPartitionedTable.java
  web/client-api/src/test/java/io/deephaven/web/client/api/PartitionedTableTestGwt.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven_core/proto/partitionedtable_pb/GetTableRequest.java
  web/client-backplane/src/main/java/io/deephaven/javascript/proto/dhinternal/io/deephaven_core/proto/partitionedtable_pb/gettablerequest/UniqueBehaviorMap.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6650 feat: DH-18145: Write timeout configuration with S3
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3ClientFactory.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3CompletableOutputStream.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3Instructions.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3ReadRequest.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3SeekableChannelProvider.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3Utils.java
  extensions/s3/src/test/java/io/deephaven/extensions/s3/S3InstructionsTest.java
  extensions/s3/src/test/java/io/deephaven/extensions/s3/S3SeekableChannelSimpleTestBase.java
  extensions/s3/src/test/java/io/deephaven/extensions/s3/testlib/S3SeekableChannelTestSetup.java
  py/server/deephaven/experimental/s3.py
  py/server/tests/test_s3_instructions.py
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#6866 chore: Bump to 0.39.2-SNAPSHOT
  R/rdeephaven/DESCRIPTION
  cpp-client/deephaven/CMakeLists.txt
  gradle.properties
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6858 feat: DH-19044: implement serial Filter API
  engine/table/src/main/java/io/deephaven/engine/table/impl/DeferredViewTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/ConditionFilter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/FilterToListImpl.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/WhereFilterAdapter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/WhereFilterDelegatingBase.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/WhereFilterInvertedImpl.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/WhereFilterSerialImpl.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableWhereParallelTest.java
  java-client/session/src/main/java/io/deephaven/client/impl/FilterAdapter.java
  sql/src/main/java/io/deephaven/sql/FilterSimplifier.java
  table-api/src/main/java/io/deephaven/api/ConcurrencyControl.java
  table-api/src/main/java/io/deephaven/api/Strings.java
  table-api/src/main/java/io/deephaven/api/filter/ExtractAnds.java
  table-api/src/main/java/io/deephaven/api/filter/Filter.java
  table-api/src/main/java/io/deephaven/api/filter/FilterSerial.java
  table-api/src/test/java/io/deephaven/api/StringsTest.java
  table-api/src/test/java/io/deephaven/api/filter/FilterTest.java
Labels: core, DocumentationNeeded, NoReleaseNotesNeeded

#6868 fix: update Iceberg Explore partitionStats
  extensions/iceberg/src/main/java/io/deephaven/iceberg/internal/Explore.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6869 chore: bump docker registry images
  docker/registry/go/gradle.properties
  docker/registry/manylinux2014_x86_64/gradle.properties
  docker/registry/minio/gradle.properties
  docker/registry/protoc-base/gradle.properties
  docker/registry/python/gradle.properties
  docker/registry/server-base/gradle.properties
  docker/registry/slim-base/gradle.properties
  docker/server-jetty/src/main/server-jetty/requirements.txt
  docker/server/src/main/server-netty/requirements.txt
  py/server/tests/test_parquet.py
Labels: NoDocumentationNeeded, version-bump, NoReleaseNotesNeeded

#6871 fix: remove anon classes from NameMappingProvider, ResolverProvider
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/NameMappingProvider.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/NameMappingProviderImpl.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/ResolverProvider.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/ResolverProviderImpl.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6840 feat: DH-18260: Added support to read/write list types to Iceberg
  extensions/iceberg/s3/src/test/java/io/deephaven/iceberg/util/IcebergToolsTest.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/base/IcebergUtils.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/IcebergCatalogAdapter.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/IcebergTableWriter.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/InferenceImpl.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/Resolver.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/ResolverFactory.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/TypeCompatibility.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/TypeInference.java
  extensions/iceberg/src/test/java/io/deephaven/iceberg/PyIcebergListColumnTest.java
  extensions/iceberg/src/test/java/io/deephaven/iceberg/junit5/SqliteCatalogBase.java
  extensions/iceberg/src/test/java/io/deephaven/iceberg/util/ResolverFromTest.java
  extensions/iceberg/src/test/java/io/deephaven/iceberg/util/ResolverInferTest.java
  extensions/iceberg/src/test/java/io/deephaven/iceberg/util/ResolverTest.java
  extensions/iceberg/src/test/java/io/deephaven/iceberg/util/TypeCompatibilityTest.java
  extensions/iceberg/src/test/java/io/deephaven/iceberg/util/TypeInferenceFromDeephavenTypeTest.java
  extensions/iceberg/src/test/java/io/deephaven/iceberg/util/TypeInferenceFromIcebergTypeTest.java
  extensions/iceberg/src/test/resources/io/deephaven/iceberg/sqlite/db_resource/catalogs/list-columns/list_test.db/data/data/00000-0-70bc42b7-6710-4ebb-91c8-9216275bf0f4.parquet
  extensions/iceberg/src/test/resources/io/deephaven/iceberg/sqlite/db_resource/catalogs/list-columns/list_test.db/data/metadata/00000-947d1e94-8a4f-4973-bbd2-66983f585bef.metadata.json
  extensions/iceberg/src/test/resources/io/deephaven/iceberg/sqlite/db_resource/catalogs/list-columns/list_test.db/data/metadata/00001-552afc73-7a34-4616-a7f6-b701e1a55fed.metadata.json
  extensions/iceberg/src/test/resources/io/deephaven/iceberg/sqlite/db_resource/catalogs/list-columns/list_test.db/data/metadata/70bc42b7-6710-4ebb-91c8-9216275bf0f4-m0.avro
  extensions/iceberg/src/test/resources/io/deephaven/iceberg/sqlite/db_resource/catalogs/list-columns/list_test.db/data/metadata/snap-6689651917744191683-0-70bc42b7-6710-4ebb-91c8-9216275bf0f4.avro
  extensions/iceberg/src/test/resources/io/deephaven/iceberg/sqlite/db_resource/dh-iceberg-test.db
  extensions/iceberg/src/test/resources/io/deephaven/iceberg/sqlite/db_resource/generate-pyiceberg-list-columns.py
Labels: NoDocumentationNeeded, ReleaseNotesNeeded, iceberg

#6873 feat: expose IcebergTableAdapter.nameMapping
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/IcebergTableAdapter.java
  extensions/iceberg/src/test/java/io/deephaven/iceberg/junit5/SqliteCatalogBase.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6874 chore: bump to testing Java 24
  .github/workflows/nightly-check-ci.yml
  Configuration/src/test/java/io/deephaven/configuration/TestConfiguration.java
  extensions/iceberg/build.gradle
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6872 fix: DH-18168: Improve handling of failures when writing parquet files
  Base/src/main/java/io/deephaven/base/FileUtils.java
  Base/src/test/java/io/deephaven/base/FileUtilsTest.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/ParquetTools.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6886 fix: DH-19465: Sorted Rollup snapshot breaks when keys are removed.
  engine/table/src/main/java/io/deephaven/engine/table/impl/hierarchical/RollupTableImpl.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/hierarchical/TreeSourceRowLookup.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/hierarchical/TreeTableImpl.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestHierarchicalTableSnapshots.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded, point_release_candidate

#6900 fix: DH-19465: Sorted Rollup snapshot breaks when keys are removed.
  engine/table/src/main/java/io/deephaven/engine/table/impl/hierarchical/RollupTableImpl.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/hierarchical/TreeSourceRowLookup.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/hierarchical/TreeTableImpl.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestHierarchicalTableSnapshots.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#6894 refactor: DH-19527: Allow Overriding Metadata for BarrageMessageWriterImpl.SubView
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/BarrageMessageWriterImpl.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6905 fix: remove anon classes from NameMappingProvider, ResolverProvider
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/NameMappingProvider.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/NameMappingProviderImpl.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/ResolverProvider.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/ResolverProviderImpl.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6906 feat: Add Iceberg BuildCatalogOptions
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/BuildCatalogOptions.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/IcebergTools.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/InferenceInstructions.java
  extensions/iceberg/src/test/java/io/deephaven/iceberg/util/BuildCatalogOptionsTest.java
  extensions/iceberg/src/test/java/io/deephaven/iceberg/util/LoadTableOptionsTest.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6908 feat: DH-18145: Write timeout configuration with S3
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3ClientFactory.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3CompletableOutputStream.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3Instructions.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3ReadRequest.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3SeekableChannelProvider.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3Utils.java
  extensions/s3/src/test/java/io/deephaven/extensions/s3/S3InstructionsTest.java
  extensions/s3/src/test/java/io/deephaven/extensions/s3/S3SeekableChannelSimpleTestBase.java
  extensions/s3/src/test/java/io/deephaven/extensions/s3/testlib/S3SeekableChannelTestSetup.java
  py/server/deephaven/experimental/s3.py
  py/server/tests/test_s3_instructions.py
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6909 feat: DH-19448: Use S3 client for Iceberg from S3FileIO
  extensions/iceberg/s3/build.gradle
  extensions/iceberg/s3/src/main/java/io/deephaven/extensions/s3/S3FallbackFileIOAdapter.java
  extensions/iceberg/s3/src/main/java/io/deephaven/extensions/s3/S3FileIOAdapter.java
  extensions/iceberg/s3/src/main/java/io/deephaven/extensions/s3/S3FileIOAdapterBase.java
  extensions/iceberg/s3/src/main/java/io/deephaven/iceberg/util/DeephavenS3ClientCredentialsProvider.java
  extensions/iceberg/s3/src/main/java/io/deephaven/iceberg/util/IcebergToolsS3.java
  extensions/iceberg/s3/src/main/java/io/deephaven/iceberg/util/S3InstructionsProviderPlugin.java
  extensions/iceberg/s3/src/test/java/io/deephaven/iceberg/util/IcebergToolsTest.java
  extensions/iceberg/s3/src/test/java/io/deephaven/iceberg/util/S3WarehouseSqliteCatalogBase.java
  extensions/iceberg/s3/src/test/java/io/deephaven/iceberg/util/TableParquetWriterOptionsTest.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/BuildCatalogOptions.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/FileIOAdapter.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/FileIOAdapterBase.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/IcebergTableAdapter.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/IcebergTableWriter.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/IcebergTools.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/InjectAWSProperties.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/LocalFileIOAdapter.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/TableParquetWriterOptions.java
  extensions/iceberg/src/test/java/io/deephaven/iceberg/TestCatalog/IcebergTestCatalog.java
  extensions/iceberg/src/test/java/io/deephaven/iceberg/util/BuildCatalogOptionsTest.java
  extensions/iceberg/src/test/java/io/deephaven/iceberg/util/InjectDeephavenPropertiesTest.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/ParquetInstructions.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/ParquetTools.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/S3ParquetTestBase.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3Constants.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3Instructions.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3SeekableChannelProvider.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/UniversalS3SeekableChannelProviderPlugin.java
  extensions/s3/src/test/java/io/deephaven/extensions/s3/S3SeekableChannelSimpleTestBase.java
  extensions/s3/src/test/java/io/deephaven/extensions/s3/testlib/S3SeekableChannelTestSetup.java
  extensions/s3/src/test/java/io/deephaven/extensions/s3/testlib/SingletonContainers.java
  gradle/libs.versions.toml
  py/server/deephaven/experimental/iceberg.py
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6912 feat: Add NameMappingProvider introspection
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/IcebergCatalogAdapter.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/NameMappingProvider.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/NameMappingProviderImpl.java
  extensions/iceberg/src/test/java/io/deephaven/iceberg/util/NameMappingProviderTest.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6916 chore: Bump to 0.39.3
  R/rdeephaven/DESCRIPTION
  cpp-client/deephaven/CMakeLists.txt
  gradle.properties
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded
