Repository deephaven/deephaven-core, pull requests merged in 2025-10, with the labels that each got.

#7255 fix: DH-20516: Add implicit barriers to serial Selectables. (#7252)
  docs/groovy/conceptual/query-engine/parallelization.md
  engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/analyzers/SelectAndViewAnalyzer.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableSelectBarrierTest.java
  table-api/src/main/java/io/deephaven/api/ConcurrencyControl.java
Labels: DocumentationNeeded, ReleaseNotesNeeded

#7258 fix: DH-20516: Default property sense (and documentation) was inverted.
  docs/groovy/conceptual/query-engine/parallelization.md
  engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableSelectBarrierTest.java
Labels: DocumentationNeeded, NoReleaseNotesNeeded

#7256 fix: DH-20523: Include update graph name in log messages.
  engine/table/src/main/java/io/deephaven/engine/updategraph/impl/BaseUpdateGraph.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#7263 chore: Bump to 0.40.3
  R/rdeephaven/DESCRIPTION
  cpp-client/deephaven/CMakeLists.txt
  gradle.properties
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#7238 docs: DOC-922,DH-18080: Document column expression validation.
  docs/groovy/conceptual/formula-validation-configuration.md
  docs/groovy/conceptual/query-table-configuration.md
  docs/groovy/sidebar.json
Labels: documentation, NoDocumentationNeeded, NoReleaseNotesNeeded

#7231 fix: DH-20408: Allow column renames to properly mask collisions.
  docs/groovy/how-to-guides/drop-move-rename-columns.md
  docs/groovy/reference/table-operations/select/rename-columns.md
  docs/groovy/snapshots/77d79ee9d599897650dcb15173a08bde.json
  docs/python/how-to-guides/drop-move-rename-columns.md
  docs/python/reference/table-operations/select/rename-columns.md
  docs/python/snapshots/c66de1d1a14ff1daf9bed1fdd6d46189.json
  engine/api/src/main/java/io/deephaven/engine/table/Table.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/RedefinableTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/RenameColumnHelper.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableTest.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/ParquetTableReadWriteTest.java
  py/server/deephaven/table.py
Labels: bug, NoDocumentationNeeded, ReleaseNotesNeeded

#7149 fix: DH-19929: support Avro String[] types
  extensions/kafka/src/main/java/io/deephaven/kafka/ingest/GenericRecordArrayFieldCopier.java
  extensions/kafka/src/main/java/io/deephaven/kafka/ingest/GenericRecordStringFieldCopier.java
  extensions/kafka/src/test/java/io/deephaven/kafka/ingest/TestAvroAdapter.java
  extensions/kafka/src/test/resources/avro-examples/stringarray.avsc
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#7262 fix: DH-20540: Ensure DataIndex pushdown is not short-circuited
  engine/table/src/main/java/io/deephaven/engine/table/impl/BasePushdownFilterContext.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/locations/impl/AbstractTableLocation.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/location/ParquetTableLocation.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/location/ParquetTableLocationTest.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#7269 refactor: DH-20568: Refactor DHProcess Module for use outside EngineMetrics.
  DHProcess/src/main/java/io/deephaven/process/ProcessInfoLogVisitor.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/ProcessInfoImpl.java
  engine/table/src/main/java/io/deephaven/process/ProcessInfoConfig.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#7282 chore: update docs codeowners
  .github/CODEOWNERS
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#7289 docs: Community Core MCP guides
  docs/groovy/how-to-guides/mcp.md
  docs/groovy/sidebar.json
  docs/python/how-to-guides/mcp.md
  docs/python/sidebar.json
Labels: documentation, NoDocumentationNeeded, NoReleaseNotesNeeded

#7288 chore: DH-20611: Add dependency constraint on json-smart
  extensions/flight-sql/build.gradle
  gradle/libs.versions.toml
  sql/build.gradle
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#7283 docs: DOC-629-java-packages
  docs/groovy/how-to-guides/install-and-use-java-packages.md
  docs/groovy/snapshots/a44012b47db2de50184f3f141dc2607f.json
  docs/python/how-to-guides/install-and-use-java-packages.md
  docs/python/snapshots/e936f37b3e47dd806335e267bf1f9940.json
Labels: documentation, NoDocumentationNeeded, NoReleaseNotesNeeded

#7293 chore: DH-20611: Add dependency constraint on json-smart
  extensions/flight-sql/build.gradle
  gradle/libs.versions.toml
  sql/build.gradle
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#7294 fix: DH-20614: correct PartitionAwareSourceTable partition column filter handling
  engine/table/src/main/java/io/deephaven/engine/table/impl/PartitionAwareSourceTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/filter/ExtractSerialFilters.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableWhereTest.java
  engine/test-utils/src/main/java/io/deephaven/engine/testutil/filters/ParallelizedRowSetCapturingFilter.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/ParquetTableFilterTest.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded
