Repository deephaven/deephaven-core, pull requests merged in 2025-03, with the labels that each got.

#6678 test: DH-18259: Add empty-table test for Iceberg
  extensions/iceberg/src/test/java/io/deephaven/iceberg/Pyiceberg2Test.java
  extensions/iceberg/src/test/resources/io/deephaven/iceberg/sqlite/db_resource/catalogs/pyiceberg-2/trading.db/data_empty/metadata/00000-ba9e11f2-a7b1-43bb-9cac-7d9081820b06.metadata.json
  extensions/iceberg/src/test/resources/io/deephaven/iceberg/sqlite/db_resource/dh-iceberg-test.db
  extensions/iceberg/src/test/resources/io/deephaven/iceberg/sqlite/db_resource/generate-pyiceberg-2.py
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6670 chore: Remove unnecessary dependency, add missing direct dependencies
  Integrations/build.gradle
  authentication/build.gradle
  authentication/example-providers/mtls/build.gradle
  authorization-codegen/build.gradle
  buildSrc/src/main/groovy/io.deephaven.java-shadow-publishing-conventions.gradle
  extensions/iceberg/s3/build.gradle
  extensions/parquet/table/build.gradle
  extensions/performance/build.gradle
  web/client-api/client-api.gradle
Labels: build, NoDocumentationNeeded, dependencies, NoReleaseNotesNeeded

#6667 fix: DH-18803: Add qst Type find support for componentType
  engine/sql/src/main/java/io/deephaven/engine/sql/Sql.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/locations/util/PartitionParser.java
  engine/table/src/test/java/io/deephaven/qst/type/GenericVectorTest.java
  engine/table/src/test/java/io/deephaven/qst/type/PrimitiveVectorTest.java
  extensions/flight-sql/src/test/java/io/deephaven/server/flightsql/FlightSqlTest.java
  extensions/kafka/src/main/java/io/deephaven/kafka/SimpleImpl.java
  qst/type/build.gradle
  qst/type/src/main/java/io/deephaven/qst/type/GenericVectorType.java
  qst/type/src/main/java/io/deephaven/qst/type/PrimitiveVectorType.java
  qst/type/src/main/java/io/deephaven/qst/type/Type.java
  qst/type/src/test/java/io/deephaven/qst/type/TypeTest.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#6681 docs: Create venv in the user dir instead of /tmp
  README.md
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6666 feat: DH-18778: Add rebase method to TreeTable and RollupTable in support of ACLs.
  engine/api/src/main/java/io/deephaven/engine/table/hierarchical/RollupTable.java
  engine/api/src/main/java/io/deephaven/engine/table/hierarchical/TreeTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/hierarchical/RollupTableImpl.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/hierarchical/TreeTableImpl.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestHierarchicalTableSnapshots.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestRollup.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestTreeTable.java
  engine/test-utils/src/main/java/io/deephaven/engine/testutil/HierarchicalTableTestTools.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6682 refactor: remove extraneous ExecutionContext wrapping in QueryTable.copy
  engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6669 fix: convert primitives to Objects inside of WebChunkReaderFactory
  replication/static/src/main/java/io/deephaven/replicators/ReplicateBarrageUtils.java
  web/client-api/src/main/java/io/deephaven/web/client/api/barrage/WebBarrageMessageReader.java
  web/client-api/src/main/java/io/deephaven/web/client/api/barrage/WebChunkReaderFactory.java
  web/client-api/src/main/java/io/deephaven/web/client/api/barrage/data/WebBarrageSubscription.java
  web/client-api/src/main/java/io/deephaven/web/client/api/barrage/data/WebByteColumnData.java
  web/client-api/src/main/java/io/deephaven/web/client/api/barrage/data/WebCharColumnData.java
  web/client-api/src/main/java/io/deephaven/web/client/api/barrage/data/WebColumnData.java
  web/client-api/src/main/java/io/deephaven/web/client/api/barrage/data/WebDoubleColumnData.java
  web/client-api/src/main/java/io/deephaven/web/client/api/barrage/data/WebFloatColumnData.java
  web/client-api/src/main/java/io/deephaven/web/client/api/barrage/data/WebIntColumnData.java
  web/client-api/src/main/java/io/deephaven/web/client/api/barrage/data/WebLongColumnData.java
  web/client-api/src/main/java/io/deephaven/web/client/api/barrage/data/WebObjectColumnData.java
  web/client-api/src/main/java/io/deephaven/web/client/api/barrage/data/WebShortColumnData.java
  web/client-api/src/main/java/io/deephaven/web/client/api/subscription/AbstractTableSubscription.java
  web/client-api/src/main/java/io/deephaven/web/client/api/subscription/TableViewportSubscription.java
  web/client-api/src/main/java/io/deephaven/web/client/state/ClientTableState.java
  web/client-api/src/test/java/io/deephaven/web/client/api/HierarchicalTableTestGwt.java
Labels: bug, jsapi, barrage, NoDocumentationNeeded, ReleaseNotesNeeded

#6686 fix: DH-18886: TableUpdateValidator uses Bad ModifiedColumnSet
  engine/table/src/main/java/io/deephaven/engine/table/impl/TableUpdateValidator.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestTableUpdateValidator.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#6683 chore: bump docker images
  docker/registry/cpp-clients-multi-base/gradle.properties
  docker/registry/go/gradle.properties
  docker/registry/manylinux2014_x86_64/gradle.properties
  docker/registry/minio/gradle.properties
  docker/registry/protoc-base/gradle.properties
  docker/registry/python/gradle.properties
  docker/registry/server-base/gradle.properties
  docker/registry/slim-base/gradle.properties
  docker/server-jetty/src/main/server-jetty/requirements.txt
  docker/server/src/main/server-netty/requirements.txt
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6685 refactor: add computeEnclosed with boolean shouldEnclose
  engine/api/src/main/java/io/deephaven/engine/table/hierarchical/TreeTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/JoinControl.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/ChunkedOperatorAggregationHelper.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/indexer/DataIndexer.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/partitioned/PartitionedTableImpl.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/partitioned/PartitionedTableProxyImpl.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/BucketedPartitionedUpdateByManager.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/UpdateBy.java
  engine/updategraph/src/main/java/io/deephaven/engine/liveness/LivenessScopeStack.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6695 chore: Update more modules to Java 11 now that this is the baseline for flight
  Base/gradle.properties
  Configuration/gradle.properties
  IO/gradle.properties
  SevenZip/gradle.properties
  Util/immutables/gradle.properties
  Util/pool/gradle.properties
  Util/processenvironment/gradle.properties
  Util/thread/gradle.properties
  buildSrc/src/main/groovy/io.deephaven.java-toolchain-conventions.gradle
  clock/gradle.properties
  codec/api/gradle.properties
  engine/query-constants/gradle.properties
  java-client/uri/gradle.properties
  log-factory/gradle.properties
  py/jpy-config/gradle.properties
  py/jpy-ext/gradle.properties
  qst/gradle.properties
  qst/type/gradle.properties
  sql/gradle.properties
  ssl/config/gradle.properties
  ssl/kickstart/gradle.properties
  table-api/gradle.properties
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#6663 feat: JS Clients can read constituent data in unaggregated columns
  web/client-api/src/main/java/io/deephaven/web/client/api/barrage/def/ColumnDefinition.java
  web/client-api/src/main/java/io/deephaven/web/client/api/tree/JsTreeTable.java
  web/client-api/src/test/java/io/deephaven/web/client/api/HierarchicalTableTestGwt.java
Labels: jsapi, NoDocumentationNeeded, ReleaseNotesNeeded, rollup

#6668 feat: DH-18149: Simplified passing s3 instructions for iceberg writing
  extensions/iceberg/s3/src/test/java/io/deephaven/iceberg/util/TableParquetWriterOptionsTest.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/base/IcebergUtils.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/internal/DataInstructionsProviderLoader.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/layout/IcebergBaseLayout.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/layout/IcebergFlatLayout.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/layout/IcebergKeyValuePartitionedLayout.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/IcebergReadInstructions.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/IcebergTableAdapter.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/IcebergTableWriter.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/TableParquetWriterOptions.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/TableWriterOptions.java
  extensions/iceberg/src/test/java/io/deephaven/iceberg/junit5/SqliteCatalogBase.java
  py/server/deephaven/experimental/iceberg.py
Labels: feature request, DocumentationNeeded, ReleaseNotesNeeded

#6646 feat: DH-18143: Improve handling of sort order for Iceberg tables
  extensions/iceberg/src/main/java/io/deephaven/iceberg/base/IcebergUtils.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/layout/IcebergBaseLayout.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/location/IcebergTableLocationFactory.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/location/IcebergTableParquetLocation.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/location/IcebergTableParquetLocationKey.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/IcebergTableWriter.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/SchemaProvider.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/SchemaProviderInternal.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/SortOrderProvider.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/SortOrderProviderInternal.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/TableWriterOptions.java
  extensions/iceberg/src/test/java/io/deephaven/iceberg/TestCatalog/IcebergRefreshingTestTable.java
  extensions/iceberg/src/test/java/io/deephaven/iceberg/junit5/SqliteCatalogBase.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3SeekableChannelProviderPlugin.java
  py/server/deephaven/experimental/iceberg.py
Labels: feature request, DocumentationNeeded, ReleaseNotesNeeded, iceberg

#6701 fix: DH-18968: Close ManifestReader in IcebergBaseLayout.findKeys
  extensions/iceberg/s3/src/test/java/io/deephaven/iceberg/util/S3WarehouseSqliteCatalogBase.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/base/IcebergUtils.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/layout/IcebergBaseLayout.java
  extensions/iceberg/src/test/java/io/deephaven/iceberg/base/IcebergTestUtils.java
  extensions/iceberg/src/test/java/io/deephaven/iceberg/junit5/SqliteCatalogBase.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6702 feat(cpp-client): Update date.h thirdparty library from 3.0.1 to 3.0.3; fixes gcc13/ubuntu24 build failure
  cpp-client/deephaven/dhcore/third_party/date/README-deephaven.md
  cpp-client/deephaven/dhcore/third_party/date/include/date/date.h
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded, c++-client

#6703 feat(cppclient): C++ client demo tracking feed times
  cpp-client/deephaven/dhcore/CMakeLists.txt
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/utility/time.h
  cpp-client/deephaven/examples/demos/CMakeLists.txt
  cpp-client/deephaven/examples/demos/feedtimes.cc
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6697 fix: If using python, any thread that calls python must have a python frame
  Base/src/main/java/io/deephaven/base/system/StandardStreamState.java
  server/src/main/java/io/deephaven/server/console/python/DebuggingInitializer.java
  server/src/main/java/io/deephaven/server/console/python/PythonConsoleSessionModule.java
  server/src/main/java/io/deephaven/server/console/python/PythonGlobalScopeCopyModule.java
  server/src/main/java/io/deephaven/server/console/python/PythonGlobalScopeModule.java
  server/src/main/java/io/deephaven/server/log/LogInit.java
  server/src/main/java/io/deephaven/server/runner/DeephavenApiServer.java
Labels: NoDocumentationNeeded, python-server-side, ReleaseNotesNeeded

#6713 fix: DH-19003: ensure ATLP.getTLIfPresent returns a managed TableLocation
  engine/table/src/main/java/io/deephaven/engine/table/impl/locations/impl/AbstractTableLocationProvider.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6680 feat: Add method to construct InputTableUpdater from Table
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/BaseArrayBackedInputTable.java
  engine/table/src/main/java/io/deephaven/engine/util/input/InputTableUpdater.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/util/TestKeyedArrayBackedInputTable.java
  py/server/deephaven/table_factory.py
  py/server/tests/test_table_factory.py
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6714 fix: DH-19005: Off-by-one in showWithRowSet Column Width
  engine/table/src/main/java/io/deephaven/engine/util/TableShowTools.java
  engine/table/src/test/java/io/deephaven/engine/util/TestTableTools.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#6715 fix: JS Widget should defer firing message events
  web/client-api/src/main/java/io/deephaven/web/client/api/widget/JsWidget.java
Labels: jsapi, grpc, NoDocumentationNeeded, ReleaseNotesNeeded

#6564 feat: DH-18414: SourcePartitionedTable: Allow deferred existence checking and add partitioning columns
  Base/src/main/java/io/deephaven/base/WeakReferenceManager.java
  Util/src/main/java/io/deephaven/util/datastructures/ArrayWeakReferenceManager.java
  Util/src/main/java/io/deephaven/util/datastructures/LinkedWeakReferenceManager.java
  Util/src/main/java/io/deephaven/util/datastructures/WeakReferenceManager.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/SourcePartitionedTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/alternatingcolumnsource/AlternatingColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/locations/impl/SingleTableLocationProvider.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/analyzers/ViewColumnLayer.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/RegionedColumnSourceManager.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/SourcePartitionedTableTest.java
  engine/updategraph/src/main/java/io/deephaven/engine/updategraph/UpdateSourceCombiner.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/PythonTableDataService.java
  py/server/deephaven/experimental/table_data_service.py
Labels: query engine, core, DocumentationNeeded, ReleaseNotesNeeded

#6717 build: Allow jetty-run task -Pdebug to take a value for the debug port
  server/jetty-app/build.gradle
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6700 feat: DH-18856: Add Median to jsapi Aggregation Options
  web/client-api/src/main/java/io/deephaven/web/client/api/JsTotalsTableConfig.java
  web/client-api/src/main/java/io/deephaven/web/client/api/tree/enums/JsAggregationOperation.java
  web/client-api/src/test/java/io/deephaven/web/client/api/TotalsTableTestGwt.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6718 fix: Reenable the skipped tests
  py/server/tests/test_arrow.py
Labels: python, NoDocumentationNeeded, NoReleaseNotesNeeded

#6719 fix: PythonTableDataService use __eq__ instead of PyObject#equals
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/util/PythonTableDataService.java
  py/server/deephaven/experimental/table_data_service.py
  py/server/tests/test_table_data_service.py
Labels: bug, python, DocumentationNeeded, ReleaseNotesNeeded

#6720 chore: Bump to 0.39.0-SNAPSHOT
  R/rdeephaven/DESCRIPTION
  cpp-client/deephaven/CMakeLists.txt
  gradle.properties
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6649 feat: Format signature help when valid docstring style
  py/server/deephaven_internal/auto_completer/_completer.py
  py/server/deephaven_internal/auto_completer/_signature_help.py
  py/server/setup.py
  py/server/tests/test_docstring_parser.py
  server/src/main/java/io/deephaven/server/console/completer/PythonAutoCompleteObserver.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6687 fix: ArrowWrapperTools Must Account For Timestamp Column's TimeUnit
  extensions/arrow/src/main/java/io/deephaven/extensions/arrow/ArrowWrapperTools.java
  extensions/arrow/src/main/java/io/deephaven/extensions/arrow/sources/ArrowInstantColumnSource.java
  extensions/arrow/src/test/java/io/deephaven/extensions/arrow/ArrowTimestampVectorTest.java
  extensions/arrow/src/test/resources/timestamp_vector.arrow
  extensions/arrow/src/test/resources/timestamp_vectors.arrow
  replication/reflective/src/main/java/io/deephaven/replicators/GenerateArrowColumnSourceTests.java
  replication/reflective/src/main/java/io/deephaven/replicators/GenerateArrowColumnSources.java
Labels: bug, NoDocumentationNeeded, arrow, ReleaseNotesNeeded

#6724 feat: Create an S3 universal provider
  Util/channel/src/main/java/io/deephaven/util/channel/SeekableChannelsProviderDelegate.java
  Util/channel/src/main/java/io/deephaven/util/channel/SeekableChannelsProviderLoader.java
  Util/channel/src/main/java/io/deephaven/util/channel/SeekableChannelsProviderPlugin.java
  Util/channel/src/main/java/io/deephaven/util/channel/SeekableChannelsProviderPluginBase.java
  extensions/iceberg/s3/src/main/java/io/deephaven/iceberg/util/S3InstructionsProviderPlugin.java
  extensions/iceberg/s3/src/test/java/io/deephaven/iceberg/util/S3WarehouseSqliteCatalogBase.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/layout/IcebergBaseLayout.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/GCSSeekableChannelProvider.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/GCSSeekableChannelProviderPlugin.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3ASeekableChannelProvider.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3ASeekableChannelProviderPlugin.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3Constants.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3DelegateProvider.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3NSeekableChannelProvider.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3NSeekableChannelProviderPlugin.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3SeekableChannelProvider.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/S3SeekableChannelProviderPlugin.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/UniversalS3Provider.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/UniversalS3SeekableChannelProviderPlugin.java
  extensions/s3/src/main/java/io/deephaven/extensions/s3/UriToS3SeekableChannelProvider.java
  extensions/s3/src/test/java/io/deephaven/extensions/s3/testlib/S3SeekableChannelTestSetup.java
  extensions/trackedfile/src/main/java/io/deephaven/extensions/trackedfile/TrackedSeekableChannelsProviderPlugin.java
  replication/static/build.gradle
  replication/static/src/main/java/io/deephaven/replicators/ReplicateChannelProviders.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6737 chore: bump org.apache.parquet:parquet-hadoop from 1.15.0 to 1.15.1
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/TestParquetTools.java
  gradle/libs.versions.toml
Labels: NoDocumentationNeeded, version-bump, NoReleaseNotesNeeded

#6735 build: Fix two gRPC build quirks
  gradle/libs.versions.toml
  proto/proto-backplane-grpc/Dockerfile
  proto/proto-backplane-grpc/build.gradle
Labels: build, grpc, NoDocumentationNeeded, NoReleaseNotesNeeded

#6734 chore: bump selenium to 4.30.0
  docker/registry/selenium/gradle.properties
  gradle/libs.versions.toml
Labels: NoDocumentationNeeded, version-bump, NoReleaseNotesNeeded

#6723 test: Add Py ADBC/FlightSQLClient test cases
  py/client/build.gradle
  py/client/requirements-dev.txt
  py/client/tests/test_flightsql.py
Labels: python, NoDocumentationNeeded, NoReleaseNotesNeeded

#6738 refactor: Update Iceberg key finders
  extensions/iceberg/src/main/java/io/deephaven/iceberg/layout/IcebergBaseLayout.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/layout/IcebergFlatLayout.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/layout/IcebergKeyValuePartitionedLayout.java
  extensions/iceberg/src/main/java/io/deephaven/iceberg/util/IcebergTableAdapter.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded, iceberg

#6739 fix: DH-19077: Remove ModifiedColumnSet empty check from validateUpdateIndices.
  engine/table/src/main/java/io/deephaven/engine/table/impl/BaseTable.java
  props/test-configs/src/main/resources/dh-tests.prop
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6741 fix: DH-18900: ObjectSegmentedSortedMultiset#toArray must return a COMPONENT_TYPE[] not an Object[]
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/ssmcountdistinct/ObjectSsmBackedSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/ssms/ByteSegmentedSortedMultiset.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/ssms/CharSegmentedSortedMultiset.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/ssms/DoubleSegmentedSortedMultiset.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/ssms/FloatSegmentedSortedMultiset.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/ssms/IntSegmentedSortedMultiset.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/ssms/LongSegmentedSortedMultiset.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/ssms/ObjectSegmentedSortedMultiset.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/ssms/ShortSegmentedSortedMultiset.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableSelectUpdateTest.java
  replication/static/src/main/java/io/deephaven/replicators/ReplicateSegmentedSortedMultiset.java
Labels: bug, core, NoDocumentationNeeded, ReleaseNotesNeeded
