Repository deephaven/deephaven-core, pull requests merged in 2025-02, with the labels that each got.

#6605 fix: DH-18153: Handle numpy's new shape typing in UDF parsing
  py/server/deephaven/_udf.py
  py/server/tests/test_udf_return.py
Labels: NoDocumentationNeeded, python-server-side, ReleaseNotesNeeded

#6607 fix: DH-18567: Filter locations before removal allowed checks.
  engine/table/src/main/java/io/deephaven/engine/table/impl/SourceTable.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestPartitionAwareSourceTable.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestPartitionAwareSourceTableNoRemoval.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#5854 feat: JS API support for shared tickets
  web/client-api/src/main/java/io/deephaven/web/client/api/ClientConfiguration.java
  web/client-api/src/main/java/io/deephaven/web/client/api/JsPartitionedTable.java
  web/client-api/src/main/java/io/deephaven/web/client/api/JsTable.java
  web/client-api/src/main/java/io/deephaven/web/client/api/JsTotalsTable.java
  web/client-api/src/main/java/io/deephaven/web/client/api/QueryConnectable.java
  web/client-api/src/main/java/io/deephaven/web/client/api/ServerObject.java
  web/client-api/src/main/java/io/deephaven/web/client/api/TableTicket.java
  web/client-api/src/main/java/io/deephaven/web/client/api/Tickets.java
  web/client-api/src/main/java/io/deephaven/web/client/api/WorkerConnection.java
  web/client-api/src/main/java/io/deephaven/web/client/api/console/JsVariableDefinition.java
  web/client-api/src/main/java/io/deephaven/web/client/api/input/JsInputTable.java
  web/client-api/src/main/java/io/deephaven/web/client/api/tree/JsTreeTable.java
  web/client-api/src/main/java/io/deephaven/web/client/api/widget/JsWidget.java
  web/client-api/src/main/java/io/deephaven/web/client/api/widget/JsWidgetExportedObject.java
  web/client-api/src/main/java/io/deephaven/web/client/ide/IdeConnection.java
  web/client-api/src/main/java/io/deephaven/web/client/ide/IdeSession.java
  web/client-api/src/main/java/io/deephaven/web/client/ide/SharedExportBytesUnion.java
  web/client-api/src/test/java/io/deephaven/web/ClientIntegrationTestSuite.java
  web/client-api/src/test/java/io/deephaven/web/client/api/SharedObjectTestGwt.java
Labels: jsapi, NoDocumentationNeeded, ReleaseNotesNeeded

#6615 fix: DH-18482: EventDrivenUpdateGraph: Allow two concurrent threads to safely requestRefresh(), and ensure clean errors for nested refresh attempts (#6603)
  engine/table/src/main/java/io/deephaven/engine/updategraph/impl/BaseUpdateGraph.java
  engine/table/src/main/java/io/deephaven/engine/updategraph/impl/EventDrivenUpdateGraph.java
  engine/table/src/test/java/io/deephaven/engine/updategraph/impl/TestEventDrivenUpdateGraph.java
Labels: query engine, core, NoDocumentationNeeded, user-reported, ReleaseNotesNeeded, point_release_candidate

#6614 fix: DH-18567: Filter locations before removal allowed checks. (#6607)
  engine/table/src/main/java/io/deephaven/engine/table/impl/SourceTable.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestPartitionAwareSourceTable.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestPartitionAwareSourceTableNoRemoval.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#6617 feat: DH-18588: Allow name.rootFile as a config file specifier
  Configuration/src/main/java/io/deephaven/configuration/Configuration.java
  Configuration/src/test/java/io/deephaven/configuration/TestConfiguration.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#6616 fix: Promises in Tree subscriptions should reject if aborted
  web/client-api/src/main/java/io/deephaven/web/client/api/tree/JsTreeTable.java
Labels: bug, jsapi, NoDocumentationNeeded, NoReleaseNotesNeeded

#6541 chore: Bump gradle to 8.12.1
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: build, NoDocumentationNeeded, NoReleaseNotesNeeded

#6613 ci: Invoke webhook on PR merge
  .github/workflows/create-docs-issues.js
  .github/workflows/pr-merge-webhook.yml
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6606 feat: DH-18174: Delay reading from parquet file when creating table and column location
  engine/table/src/main/java/io/deephaven/engine/table/impl/locations/TableLocation.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/locations/impl/AbstractTableLocation.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/RegionedColumnSourceManager.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/location/ParquetColumnLocation.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/location/ParquetTableLocation.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/ParquetTableReadWriteTest.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/TestParquetTools.java
Labels: feature request, NoDocumentationNeeded, ReleaseNotesNeeded

#6622 feat: DH-18174: Delay reading from parquet file when creating table and column location
  engine/table/src/main/java/io/deephaven/engine/table/impl/locations/TableLocation.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/locations/impl/AbstractTableLocation.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/RegionedColumnSourceManager.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/location/ParquetColumnLocation.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/location/ParquetTableLocation.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/ParquetTableReadWriteTest.java
Labels: feature request, parquet, NoDocumentationNeeded, ReleaseNotesNeeded

#6574 refactor: no-ticket: make DeferredColumnRegionBase more efficient wrt volatile
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/DeferredColumnRegionBase.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6620 feat: DH-18493: Add Table.is_failed property
  py/server/deephaven/table.py
  py/server/tests/test_barrage.py
  py/server/tests/test_table.py
  py/server/tests/test_table_data_service.py
Labels: NoDocumentationNeeded, python-server-side, ReleaseNotesNeeded

#6623 fix: Support whole range of byte values for booleans
  engine/query-constants/src/main/java/io/deephaven/util/BooleanUtils.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/BooleanSparseArraySource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/fill/BooleanFillByOperator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/BooleanChunkInputStreamGenerator.java
  extensions/barrage/src/test/java/io/deephaven/extensions/barrage/chunk/BarrageColumnRoundTripTest.java
  extensions/json-jackson/src/main/java/io/deephaven/json/jackson/BoolMixin.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/PlainBooleanChunkedWriter.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/TestParquetTools.java
  qst/src/main/java/io/deephaven/qst/array/BooleanArray.java
  replication/static/src/main/java/io/deephaven/replicators/ReplicateSourcesAndChunks.java
  replication/static/src/main/java/io/deephaven/replicators/ReplicateUpdateBy.java
  web/client-api/src/main/java/io/deephaven/web/client/api/parse/JsDataHandler.java
Labels: barrage, parquet, NoDocumentationNeeded, ReleaseNotesNeeded, point_release_candidate

#6621 feat: DH-18588: Allow shortened Name.rootFIle config file specifier
  Configuration/src/main/java/io/deephaven/configuration/Configuration.java
  Configuration/src/test/java/io/deephaven/configuration/TestConfiguration.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded, point_release_candidate

#6624 fix: Support whole range of byte values for booleans
  engine/query-constants/src/main/java/io/deephaven/util/BooleanUtils.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/BooleanSparseArraySource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/fill/BooleanFillByOperator.java
  extensions/barrage/src/main/java/io/deephaven/extensions/barrage/chunk/BooleanChunkInputStreamGenerator.java
  extensions/barrage/src/test/java/io/deephaven/extensions/barrage/chunk/BarrageColumnRoundTripTest.java
  extensions/json-jackson/src/main/java/io/deephaven/json/jackson/BoolMixin.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/PlainBooleanChunkedWriter.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/TestParquetTools.java
  qst/src/main/java/io/deephaven/qst/array/BooleanArray.java
  replication/static/src/main/java/io/deephaven/replicators/ReplicateSourcesAndChunks.java
  replication/static/src/main/java/io/deephaven/replicators/ReplicateUpdateBy.java
  web/client-api/src/main/java/io/deephaven/web/client/api/parse/JsDataHandler.java
Labels: barrage, parquet, NoDocumentationNeeded, ReleaseNotesNeeded

#6618 fix: JS clients must not release tickets for pending operations
  web/client-api/src/main/java/io/deephaven/web/client/api/tree/JsTreeTable.java
  web/client-api/src/main/java/io/deephaven/web/client/fu/JsAbortSignal.java
Labels: bug, jsapi, NoDocumentationNeeded, ReleaseNotesNeeded, rollup

#6563 chore: bump org.apache.parquet:parquet-hadoop from 1.14.3 to 1.15.0
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/TestParquetTools.java
  gradle/libs.versions.toml
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#6625 chore: Bump version to 0.37.6-SNAPSHOT
  R/rdeephaven/DESCRIPTION
  cpp-client/deephaven/CMakeLists.txt
  gradle.properties
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6586 build: DH-18477: Java coverage generated conditionally
  buildSrc/src/main/groovy/TestTools.groovy
  buildSrc/src/main/groovy/io.deephaven.java-jacoco-conventions.gradle
  buildSrc/src/main/groovy/io.deephaven.java-test-conventions.gradle
  coverage/README.md
  coverage/build.gradle
  coverage/exclude-packages.txt
  coverage/gather-coverage.py
  coverage/gradle.properties
  settings.gradle
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6609 feat(cpp-client): Honor Arrow TimeUnit when converting Timestamp and Time64 to ColumnSource
  cpp-client/deephaven/dhclient/CMakeLists.txt
  cpp-client/deephaven/dhclient/include/private/deephaven/client/arrowutil/arrow_column_source.h
  cpp-client/deephaven/dhclient/include/public/deephaven/client/utility/internal_types.h
  cpp-client/deephaven/dhclient/include/public/deephaven/client/utility/table_maker.h
  cpp-client/deephaven/dhclient/src/arrowutil/arrow_column_source.cc
  cpp-client/deephaven/dhclient/src/utility/arrow_util.cc
  cpp-client/deephaven/dhcore/include/public/deephaven/dhcore/types.h
  cpp-client/deephaven/tests/CMakeLists.txt
  cpp-client/deephaven/tests/src/time_unit_test.cc
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6627 ci: DH-18625: Slack notification if DHC publish step fails
  .github/workflows/nightly-check-ci.yml
  .github/workflows/publish-ci.yml
Labels: ci, NoDocumentationNeeded, NoReleaseNotesNeeded

#6634 chore: Update copyright date spotless fix
  cpp-client/deephaven/dhclient/include/public/deephaven/client/utility/internal_types.h
  cpp-client/deephaven/dhclient/src/arrowutil/arrow_column_source.cc
  cpp-client/deephaven/tests/src/time_unit_test.cc
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6630 fix: DH-18472 correct the ordering of result columns in `update_by`
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/UpdateBy.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/UpdateByOperatorFactory.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/updateby/TestUpdateByGeneral.java
Labels: bug, NoDocumentationNeeded, ReleaseNotesNeeded

#6639 fix: Expose offset property on JS TreeViewportData
  web/client-api/src/main/java/io/deephaven/web/client/api/subscription/AbstractTableSubscription.java
  web/client-api/src/main/java/io/deephaven/web/client/api/subscription/ViewportData.java
  web/client-api/src/main/java/io/deephaven/web/client/api/tree/TreeViewportData.java
Labels: documentation, jsapi, NoDocumentationNeeded, ReleaseNotesNeeded

#6638 fix: JS ChartData should write updates to the correct row
  web/client-api/src/main/java/io/deephaven/web/client/api/widget/plot/ChartData.java
  web/client-api/src/test/java/io/deephaven/web/client/api/AbstractAsyncGwtTestCase.java
  web/client-api/src/test/java/io/deephaven/web/client/api/widget/plot/ChartDataTestGwt.java
Labels: jsapi, plotting, NoDocumentationNeeded, ReleaseNotesNeeded, point_release_candidate

#6635 build: Code Coverage for Nightly Build Workflows
  .github/workflows/nightly-check-ci.yml
  coverage/gather-coverage.py
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6645 test: Improve test resilience if startForUnitTests fails
  server/src/main/java/io/deephaven/server/runner/DeephavenApiServer.java
Labels: test, NoDocumentationNeeded, NoReleaseNotesNeeded

#6647 test: Restore old behavior of timeout per script line
  web/client-api/src/test/java/io/deephaven/web/client/api/AbstractAsyncGwtTestCase.java
  web/client-api/src/test/java/io/deephaven/web/client/api/widget/plot/ChartDataTestGwt.java
Labels: jsapi, test, NoDocumentationNeeded, NoReleaseNotesNeeded

#6642 fix: DH-18539: Fix incorrect snapshot results on historical sorted rollups.
  engine/api/src/main/java/io/deephaven/engine/table/Table.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/SortOperation.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/SortedColumnsAttribute.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/RedirectedColumnSource.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestHierarchicalTableSnapshots.java
  go/pkg/client/example_import_table_test.go
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#6648 fix: DH-18539: Fix incorrect snapshot results on historical sorted rollups.
  engine/api/src/main/java/io/deephaven/engine/table/Table.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/SortOperation.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/SortedColumnsAttribute.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/RedirectedColumnSource.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestHierarchicalTableSnapshots.java
  go/pkg/client/example_import_table_test.go
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#6643 fix: JS ChartData should write updates to the correct row (#6638)
  web/client-api/src/main/java/io/deephaven/web/client/api/widget/plot/ChartData.java
  web/client-api/src/test/java/io/deephaven/web/client/api/AbstractAsyncGwtTestCase.java
  web/client-api/src/test/java/io/deephaven/web/client/api/widget/plot/ChartDataTestGwt.java
Labels: jsapi, NoDocumentationNeeded, ReleaseNotesNeeded

#6664 fix: Improve JS API handling of formatting data
  web/client-api/src/main/java/io/deephaven/web/client/api/subscription/AbstractTableSubscription.java
  web/client-api/src/main/java/io/deephaven/web/client/api/subscription/TableViewportSubscription.java
  web/client-api/src/test/java/io/deephaven/web/client/api/subscription/ViewportTestGwt.java
Labels: jsapi, NoDocumentationNeeded, ReleaseNotesNeeded
