Repository deephaven/deephaven-core, pull requests merged in 2025-07, with the labels that each got.

#6981 fix: DH-19808: Expose the hidden FlightClient instance in FlightSession of the Java client
  java-client/flight/src/main/java/io/deephaven/client/impl/FlightSession.java
Labels: NoDocumentationNeeded, java-client, NoReleaseNotesNeeded

#6892 feat: DH-18998, DH-18999: Enable etags
  server/jetty/src/main/java/io/deephaven/server/jetty/ControlledCacheHttpContent.java
  server/jetty/src/main/java/io/deephaven/server/jetty/ControlledCacheHttpContentFactory.java
  server/jetty/src/main/java/io/deephaven/server/jetty/EmptyResource.java
  server/jetty/src/main/java/io/deephaven/server/jetty/JettyBackedGrpcServer.java
  server/jetty/src/main/java/io/deephaven/server/jetty/PathPrefixResource.java
  server/jetty/src/main/java/io/deephaven/server/jetty/WrappedResource.java
  server/jetty/src/test/java/io/deephaven/server/jetty/JettyFlightRoundTripTest.java
  server/test-utils/src/main/java/io/deephaven/server/test/FlightMessageRoundTripTest.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#6994 fix: DH-19792: NPE when normalizing FilterCondition.invoke.
  server/src/main/java/io/deephaven/server/table/ops/filter/AbstractNormalizeFilters.java
  server/src/main/java/io/deephaven/server/table/ops/filter/NormalizeFilterUtil.java
  server/src/test/java/io/deephaven/server/table/ops/filter/NormalizeNotsTest.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#6992 fix: DH-19852: Fail Aggregations using Array Keys
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/ChunkedOperatorAggregationHelper.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableAggregationTest.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#6993 fix: DH-19797: Vector Grouping Columns Broken in Rollups
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/AggregationProcessor.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/NullColumnAggregationTransformer.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/rollup/NullColumns.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/rollup/RollupAggregation.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/rollup/RollupAggregationOutputs.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/hierarchical/RollupTableImpl.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestRollupTable.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#6990 fix: DH-19830: lastBy on Blink Tables Reports Incorrect Previous Values for Vectors.
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/BaseBlinkFirstOrLastChunkedOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/BlinkFirstChunkedOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/CopyingPermutedBlinkFirstOrLastChunkedOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/snapshot/SnapshotUtils.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/BlinkTableOperationsTest.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#6998 feat: DH-19859: WindowCheck should not force a table to be refreshing if nothing will ever change.
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/TimeSeriesFilter.java
  engine/table/src/main/java/io/deephaven/engine/util/WindowCheck.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/DeferredViewTableTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/select/TestTimeSeriesFilter.java
  engine/table/src/test/java/io/deephaven/engine/util/TestWindowCheck.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#6984 fix: DH-19338: Ensure we have an ExecutionContext while handling HierarchicalTableViewSubscription snapshots.
  engine/table/src/main/java/io/deephaven/engine/table/impl/perf/PerformanceEntry.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/FunctionGeneratedTableFactory.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/SelectOverheadLimiter.java
  engine/table/src/test/java/io/deephaven/engine/updategraph/impl/TestEventDrivenUpdateGraph.java
  extensions/performance/src/test/java/io/deephaven/engine/table/impl/util/TestUpdateAncestorViz.java
  props/test-configs/src/main/resources/dh-tests.prop
  server/src/main/java/io/deephaven/server/hierarchicaltable/HierarchicalTableViewSubscription.java
  server/src/test/java/io/deephaven/server/partitionedtable/TestPartitionedTableService.java
  server/src/test/java/io/deephaven/server/table/ExportTableUpdateListenerTest.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#6988 feat: Improve JobScheduler interface with cleanup callback
  engine/table/src/main/java/io/deephaven/engine/context/QueryCompilerImpl.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/AbstractFilterExecution.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/rangejoin/RangeJoinOperation.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/remote/ConstructSnapshot.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/analyzers/SelectColumnLayer.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/RegionedColumnSourceManager.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/UpdateBy.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/JobScheduler.java
  engine/table/src/test/java/io/deephaven/engine/util/TestJobScheduler.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#7002 feat: Add temporary JS API table fetch call without preview
  web/client-api/src/main/java/io/deephaven/web/client/ide/IdeConnection.java
  web/client-api/src/main/java/io/deephaven/web/client/ide/IdeSession.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#7000 refactor: DH-19526: Added convertValue to replicators for Pushdown PR
  engine/query-constants/src/main/java/io/deephaven/util/QueryConstants.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/ParquetTimeUtils.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/ByteMaterializer.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/CharMaterializer.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/DoubleFromFloatMaterializer.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/DoubleMaterializer.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/FloatMaterializer.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/InstantNanosFromMicrosMaterializer.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/InstantNanosFromMillisMaterializer.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/IntFromBooleanMaterializer.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/IntFromUnsignedByteMaterializer.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/IntFromUnsignedShortMaterializer.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/IntMaterializer.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/LocalDateMaterializer.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/LocalDateTimeFromMicrosMaterializer.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/LocalDateTimeFromMillisMaterializer.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/LocalDateTimeFromNanosMaterializer.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/LocalTimeFromMicrosMaterializer.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/LocalTimeFromMillisMaterializer.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/LocalTimeFromNanosMaterializer.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/LongFromBooleanMaterializer.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/LongFromIntMaterializer.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/LongFromUnsignedByteMaterializer.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/LongFromUnsignedIntMaterializer.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/LongFromUnsignedShortMaterializer.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/LongMaterializer.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/ParquetMaterializerUtils.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/ShortFromBooleanMaterializer.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/ShortFromUnsignedByteMaterializer.java
  extensions/parquet/base/src/main/java/io/deephaven/parquet/base/materializers/ShortMaterializer.java
  extensions/parquet/base/src/test/java/io/deephaven/parquet/base/materializers/TestLocalDateTimeMaterializers.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/transfer/LocalDateTimeArrayTransfer.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/transfer/LocalDateTimeTransfer.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/transfer/LocalDateTimeVectorTransfer.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/transfer/TransferUtils.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/ParquetTableReadWriteTest.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/transfer/TestTransferUtils.java
  extensions/parquet/table/src/test/resources/ReferenceDHNullTimestamp.parquet
  replication/static/src/main/java/io/deephaven/replicators/ReplicatePageMaterializers.java
  replication/static/src/main/java/io/deephaven/replicators/ReplicateParquetTransferObjects.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#7003 feat: Add temporary JS API table fetch call without preview
  web/client-api/src/main/java/io/deephaven/web/client/ide/IdeConnection.java
  web/client-api/src/main/java/io/deephaven/web/client/ide/IdeSession.java
Labels: jsapi, NoDocumentationNeeded, release blocker, NoReleaseNotesNeeded

#7004 feat: DH-18998, DH-18999: Enable etags (#6892)
  server/jetty/src/main/java/io/deephaven/server/jetty/ControlledCacheHttpContent.java
  server/jetty/src/main/java/io/deephaven/server/jetty/ControlledCacheHttpContentFactory.java
  server/jetty/src/main/java/io/deephaven/server/jetty/EmptyResource.java
  server/jetty/src/main/java/io/deephaven/server/jetty/JettyBackedGrpcServer.java
  server/jetty/src/main/java/io/deephaven/server/jetty/PathPrefixResource.java
  server/jetty/src/main/java/io/deephaven/server/jetty/WrappedResource.java
  server/jetty/src/test/java/io/deephaven/server/jetty/JettyFlightRoundTripTest.java
  server/test-utils/src/main/java/io/deephaven/server/test/FlightMessageRoundTripTest.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#7006 fix: DH-19569: Eliminate racy/incorrect Clock.system() testing in TestDateTimeUtils.testClock()
  engine/time/src/test/java/io/deephaven/time/TestDateTimeUtils.java
Labels: test, NoDocumentationNeeded, NoReleaseNotesNeeded

#7016 chore: Update gradle-maven-publish-plugin to 0.34.0
  .github/workflows/nightly-publish-ci.yml
  .github/workflows/publish-ci.yml
  buildSrc/build.gradle
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#7021 fix: DH-18607: Use BooleanUtils#isNull when checking for null boolean
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/BooleanSparseArraySource.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/sources/AbstractBooleanColumnSourceTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/sources/TestBooleanArraySource.java
  replication/static/src/main/java/io/deephaven/replicators/ReplicateSourceAndChunkTests.java
  replication/static/src/main/java/io/deephaven/replicators/ReplicateSourcesAndChunks.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#7018 feat: use JobScheduler for pushdown estimate
  engine/table/src/main/java/io/deephaven/engine/table/impl/AbstractColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/AbstractFilterExecution.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/PushdownFilterMatcher.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/locations/impl/AbstractTableLocation.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/RegionedColumnSourceBase.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/RegionedColumnSourceManager.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableWhereTest.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/location/ParquetTableLocation.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/ParquetTableFilterTest.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#7037 feat: DH-19978: Add assertBlink, assertAddOnly and assertAppendOnly to Table.
  engine/api/src/main/java/io/deephaven/engine/table/Table.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/BaseTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/SourceTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/SourceTableComponentFactory.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/TableAdapter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/RegionedColumnSourceManager.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/RegionedTableComponentFactoryImpl.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/verify/AppendOnlyAssertionFailure.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/verify/AppendOnlyAssertionInstrumentedListenerAdapter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/verify/TableAssertions.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestPartitionAwareSourceTable.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestPartitionAwareSourceTableNoRemoval.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestSimpleSourceTable.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/select/TestTimeSeriesFilter.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/sources/regioned/TestRegionedColumnSourceManager.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/verify/TestTableAssertions.java
Labels: DocumentationNeeded, ReleaseNotesNeeded

#7044 fix: DH-20027: ModifiedColumnSet.ALL.containsAll does not always return True.
  engine/api/src/main/java/io/deephaven/engine/table/ModifiedColumnSet.java
  engine/api/src/test/java/io/deephaven/engine/table/ModifiedColumnSetTest.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#7035 fix: DH-19924: Rewrite ungroup.
  engine/table/src/main/java/io/deephaven/engine/table/impl/MemoizedOperationKey.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/UngroupOperation.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/UngroupSizeKernel.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/BitMaskingColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/BitShiftingColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/CrossJoinRightColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/RedirectedColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/ShiftedColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/UngroupableColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/UngroupedArrayColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/UngroupedBooleanArrayColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/UngroupedBoxedBooleanArrayColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/UngroupedByteVectorColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/UngroupedCharVectorColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/UngroupedDoubleVectorColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/UngroupedFloatVectorColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/UngroupedIntVectorColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/UngroupedLongVectorColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/UngroupedObjectVectorColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/UngroupedShortVectorColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/aggregate/BaseAggregateColumnSource.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableUngroupTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/SimulateUngroupableColumnSource.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestConcurrentInstantiation.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestUngroupRebase.java
  engine/test-utils/src/main/java/io/deephaven/engine/testutil/GenerateTableUpdates.java
  engine/test-utils/src/main/java/io/deephaven/engine/testutil/testcase/RefreshingTableTestCase.java
  py/server/tests/test_update_graph.py
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#7049 fix: DH-20003: auth transform should not be applied to outputs of HierarchicalTable or PartitionedTable service ops.
  server/src/main/java/io/deephaven/server/hierarchicaltable/HierarchicalTableServiceGrpcImpl.java
  server/src/main/java/io/deephaven/server/partitionedtable/PartitionedTableServiceGrpcImpl.java
  server/src/test/java/io/deephaven/server/partitionedtable/TestPartitionedTableService.java
Labels: NoDocumentationNeeded, authorization, ReleaseNotesNeeded, rollup

#7057 fix: Guard against nulls when transforming filter messages
  server/src/main/java/io/deephaven/server/table/ops/filter/FilterFactory.java
  server/src/main/java/io/deephaven/server/table/ops/filter/FilterPrinter.java
  server/src/main/java/io/deephaven/server/table/ops/filter/NormalizeNots.java
  server/src/test/java/io/deephaven/server/table/ops/filter/NormalizeNotsTest.java
  web/client-api/src/test/java/io/deephaven/web/client/api/TableManipulationTestGwt.java
Labels: grpc, NoDocumentationNeeded, ReleaseNotesNeeded, point_release_candidate

#7056 fix: DH-20035: whereIn must coalesce set table. (#7052)
  engine/table/src/main/java/io/deephaven/engine/table/impl/QueryTable.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableWhereTest.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#7042 fix: Update web version 1.3.0 (#7038)
  web/client-ui/Dockerfile
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#7058 fix: DH-18483: Guard against nulls when transforming filter messages (#7057)
  server/src/main/java/io/deephaven/server/table/ops/filter/FilterFactory.java
  server/src/main/java/io/deephaven/server/table/ops/filter/FilterPrinter.java
  server/src/main/java/io/deephaven/server/table/ops/filter/NormalizeNots.java
  server/src/test/java/io/deephaven/server/table/ops/filter/NormalizeNotsTest.java
  web/client-api/src/test/java/io/deephaven/web/client/api/TableManipulationTestGwt.java
Labels: grpc, NoDocumentationNeeded, ReleaseNotesNeeded

#6958 fix: Pushdown improvements
  engine/rowset/build.gradle
  engine/rowset/src/main/java/io/deephaven/engine/rowset/RowSetFactory.java
  engine/rowset/src/test/java/io/deephaven/engine/rowset/RowSetFactoryUnionInsertTest.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/AbstractColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/AbstractFilterExecution.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/PushdownFilterMatcher.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/PushdownResult.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/locations/impl/AbstractTableLocation.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/BooleanSingleValueSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/ByteSingleValueSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/CharacterSingleValueSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/DoubleSingleValueSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/FloatSingleValueSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/IntegerSingleValueSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/LongSingleValueSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/NullValueColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/ObjectSingleValueSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/RowKeyAgnosticChunkSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/ShortSingleValueSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/immutable/ImmutableConstantByteSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/immutable/ImmutableConstantCharSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/immutable/ImmutableConstantDoubleSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/immutable/ImmutableConstantFloatSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/immutable/ImmutableConstantIntSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/immutable/ImmutableConstantLongSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/immutable/ImmutableConstantNanosBasedTimeSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/immutable/ImmutableConstantObjectSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/immutable/ImmutableConstantShortSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/RegionedColumnSourceBase.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/RegionedColumnSourceManager.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/PushdownResultTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableWhereTest.java
  extensions/parquet/table/src/main/java/io/deephaven/parquet/table/location/ParquetTableLocation.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/ParquetTableFilterTest.java
  props/test-configs/src/main/resources/dh-tests.prop
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#7061 chore: Bump to 0.39.7
  R/rdeephaven/DESCRIPTION
  cpp-client/deephaven/CMakeLists.txt
  gradle.properties
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#7059 fix(cpp-client): DH-20054: Fix Windows build warnings and typos in comments
  cpp-client/deephaven/dhclient/include/public/deephaven/client/client.h
  cpp-client/deephaven/dhcore/include/private/deephaven/dhcore/immerutil/immer_column_source.h
  cpp-client/deephaven/tests/src/new_table_test.cc
  cpp-client/deephaven/tests/src/ticking_test.cc
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded
