Repository deephaven/deephaven-core, pull requests merged in 2025-08, with the labels that each got.

#7063 fix: DH-20058: Address inappropriate chunk freeing in CountWhereOperator
  engine/chunk/src/main/java/io/deephaven/chunk/util/pools/PoolableChunk.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/CountWhereOperator.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/chunkcolumnsource/ByteChunkColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/chunkcolumnsource/CharChunkColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/chunkcolumnsource/ChunkColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/chunkcolumnsource/DoubleChunkColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/chunkcolumnsource/FloatChunkColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/chunkcolumnsource/IntChunkColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/chunkcolumnsource/LongChunkColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/chunkcolumnsource/ObjectChunkColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/chunkcolumnsource/ShortChunkColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/countwhere/CountWhereOperator.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#7069 feat: DH-20059 Predicate pushdown through merged tables (UnionSourceManager)
  engine/table/src/main/java/io/deephaven/engine/table/impl/AbstractFilterExecution.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/PushdownFilterMatcher.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/UnionColumnSource.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/UnionSourceManager.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/RegionedColumnSourceManager.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/NoPushdownColumnSourceWrapper.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableWhereTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/TestConcurrentInstantiation.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/ParquetTableFilterTest.java
Labels: DocumentationNeeded, ReleaseNotesNeeded

#7082 refactor: DH-20135: migrate javapoet
  authorization-codegen/build.gradle
  authorization-codegen/src/main/java/io/deephaven/auth/codegen/GenerateContextualAuthWiring.java
  authorization-codegen/src/main/java/io/deephaven/auth/codegen/GenerateServiceAuthWiring.java
  authorization/README.md
  engine/table/build.gradle
  engine/table/src/main/java/io/deephaven/engine/table/impl/asofjoin/TypedAsOfJoinFactory.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/typed/HasherConfig.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/typed/TypedAggregationFactory.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/typed/TypedHasherFactory.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/multijoin/TypedMultiJoinFactory.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/naturaljoin/TypedNaturalJoinFactory.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/hashing/TypedUpdateByFactory.java
  gradle/libs.versions.toml
  replication/reflective/build.gradle
  replication/reflective/src/main/java/io/deephaven/replicators/GenerateArrowColumnSourceTests.java
  replication/reflective/src/main/java/io/deephaven/replicators/GenerateArrowColumnSources.java
  replication/reflective/src/main/java/io/deephaven/replicators/ReplicateTypedHashers.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#7084 fix: DH-20142: Revert "refactor: DH-20135: migrate javapoet (#7082)"
  authorization-codegen/build.gradle
  authorization-codegen/src/main/java/io/deephaven/auth/codegen/GenerateContextualAuthWiring.java
  authorization-codegen/src/main/java/io/deephaven/auth/codegen/GenerateServiceAuthWiring.java
  authorization/README.md
  engine/table/build.gradle
  engine/table/src/main/java/io/deephaven/engine/table/impl/asofjoin/TypedAsOfJoinFactory.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/typed/HasherConfig.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/typed/TypedAggregationFactory.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/by/typed/TypedHasherFactory.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/multijoin/TypedMultiJoinFactory.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/naturaljoin/TypedNaturalJoinFactory.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/updateby/hashing/TypedUpdateByFactory.java
  gradle/libs.versions.toml
  replication/reflective/build.gradle
  replication/reflective/src/main/java/io/deephaven/replicators/GenerateArrowColumnSourceTests.java
  replication/reflective/src/main/java/io/deephaven/replicators/GenerateArrowColumnSources.java
  replication/reflective/src/main/java/io/deephaven/replicators/ReplicateTypedHashers.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#7083 fix: DH-20132: Lazy MergedDataIndex must include key columns.
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/MergedDataIndex.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/ParquetTableReadWriteTest.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#7085 fix: DH-20132: Lazy MergedDataIndex must include key columns.
  engine/table/src/main/java/io/deephaven/engine/table/impl/sources/regioned/MergedDataIndex.java
  extensions/parquet/table/src/test/java/io/deephaven/parquet/table/ParquetTableReadWriteTest.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#7090 fix: DH-20129: Return delegated AwsCredentialsProvider
  extensions/iceberg/s3/src/main/java/io/deephaven/iceberg/util/DeephavenS3ClientCredentialsProvider.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#7088 feat: Update web version 1.5.1 (#7072)
  web/client-ui/Dockerfile
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#7092 chore: Bump to 0.39.8
  R/rdeephaven/DESCRIPTION
  cpp-client/deephaven/CMakeLists.txt
  gradle.properties
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#7110 feat: DH-18857: Allow Vector and Array columns to be handled by quick filter backend.
  engine/table/src/main/java/io/deephaven/engine/table/impl/chunkfilter/ChunkFilter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/WhereFilterFactory.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/WhereFilterPatternImpl.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/vectorchunkfilter/ByteArrayChunkFilter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/vectorchunkfilter/ByteVectorChunkFilter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/vectorchunkfilter/CharArrayChunkFilter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/vectorchunkfilter/CharVectorChunkFilter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/vectorchunkfilter/DoubleArrayChunkFilter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/vectorchunkfilter/DoubleVectorChunkFilter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/vectorchunkfilter/FloatArrayChunkFilter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/vectorchunkfilter/FloatVectorChunkFilter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/vectorchunkfilter/IntArrayChunkFilter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/vectorchunkfilter/IntVectorChunkFilter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/vectorchunkfilter/LongArrayChunkFilter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/vectorchunkfilter/LongVectorChunkFilter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/vectorchunkfilter/ObjectArrayChunkFilter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/vectorchunkfilter/ObjectVectorChunkFilter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/vectorchunkfilter/ShortArrayChunkFilter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/vectorchunkfilter/ShortVectorChunkFilter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/vectorchunkfilter/VectorChunkFilter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/vectorchunkfilter/VectorComponentFilterWrapper.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableWhereInTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/QueryTableWhereTest.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/select/vectorchunkfilter/TestVectorComponentFilterWrapper.java
  replication/static/build.gradle
  replication/static/src/main/java/io/deephaven/replicators/ReplicateVectorChunkFilters.java
  replication/util/src/main/java/io/deephaven/replication/ReplicationUtils.java
Labels: DocumentationNeeded, ReleaseNotesNeeded

#7112 fix: DH-20184: Blank Py ODBC doc page
  py/server/deephaven/dbc/odbc.py
Labels: python, NoDocumentationNeeded, NoReleaseNotesNeeded

#7108 feat: DH-16341 Keyed transpose
  engine/table/src/main/java/io/deephaven/engine/table/impl/util/KeyedTranspose.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/util/KeyedTransposeTest.java
  py/server/deephaven/table.py
  py/server/tests/test_keyed_transpose.py
Labels: DocumentationNeeded, ReleaseNotesNeeded

#7116 fix: DH-20166: Log all export errors.
  server/src/main/java/io/deephaven/server/session/SessionState.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#7130 fix: DH-20166: Log all export errors. (#7116)
  server/src/main/java/io/deephaven/server/session/SessionState.java
Labels: NoDocumentationNeeded, ReleaseNotesNeeded

#7107 fix: DH-20146: make codec-api and implementations Java 8 compatible
  buildSrc/src/main/groovy/io.deephaven.java-toolchain-conventions.gradle
  codec/api/gradle.properties
  codec/builtin/build.gradle
  codec/builtin/gradle.properties
  codec/builtin/src/main/java/io/deephaven/util/codec/CodecUtil.java
  codec/builtin/src/main/java/io/deephaven/util/codec/EncodingInfoUtf8.java
  engine/query-constants/gradle.properties
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#7131 chore: Bump to 0.39.9
  R/rdeephaven/DESCRIPTION
  cpp-client/deephaven/CMakeLists.txt
  gradle.properties
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#7134 feat: DH-20126: Permit Resolvers without Ticket Prefix, Ticket Resolvers with ServiceLoader
  server/jetty-app-11/src/main/java/io/deephaven/server/jetty11/CommunityComponentFactory.java
  server/jetty-app/src/main/java/io/deephaven/server/jetty/CommunityComponentFactory.java
  server/src/main/java/io/deephaven/server/runner/TicketResolversFromServiceLoader.java
  server/src/main/java/io/deephaven/server/session/TicketResolver.java
  server/src/main/java/io/deephaven/server/session/TicketRouter.java
  server/src/main/java/io/deephaven/server/session/WantsTicketRouter.java
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded

#7132 fix: DH-20139: Remove $CLASSNAME$ Substitution
  engine/context/src/test/java/io/deephaven/engine/context/TestQueryCompiler.java
  engine/table/build.gradle
  engine/table/src/main/java/io/deephaven/engine/context/QueryCompilerImpl.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/ConditionFilter.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/DhFormulaColumn.java
  engine/table/src/main/java/io/deephaven/engine/table/impl/select/codegen/JavaKernelBuilder.java
  engine/table/src/main/java/io/deephaven/engine/util/DynamicCompileUtils.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/select/TestConditionFilterGeneration.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/select/TestFormulaColumnGeneration.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/select/sample/Formula.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/select/sample/FormulaKernel.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/select/sample/GeneratedFilterKernel.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/select/sample2/GeneratedFilterKernel.java
  engine/table/src/test/java/io/deephaven/engine/table/impl/util/ModelFileGenerator.java
Labels: bug, query engine, core, NoDocumentationNeeded, ReleaseNotesNeeded, point_release_candidate

#7138 fix(cpp-client): DH-20266: Improve C++ Windows build times by providing the /MP flag
  cpp-client/build-windows-clients.bat
  cpp-client/deephaven/dhclient/CMakeLists.txt
  cpp-client/deephaven/dhcore/CMakeLists.txt
  cpp-client/deephaven/tests/CMakeLists.txt
Labels: NoDocumentationNeeded, NoReleaseNotesNeeded
